### ISSUE TITLE
Don;t forget to update the README and re-publish the extension

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode-eslint#1]

**Comment by dbaeumer** [comment]
@seanmcbreen: what do we usually put into the readme. There isn't much to say.

**Comment by m-sanders** [comment]
I would like to know how about how to use `"eslint.options"`? I am really not having much luck with getting .eslintignore files to work. 

I have tried placing it in the root directory, this doesn't appear to work.

I have tried adding the .eslintignore file using `"eslint.options"`:

```
	"eslint.options": {
		"ignorePath": ".eslintignore" 
	}
```

And also with an absolute path:

```
	"eslint.options": {
		"ignorePath": "/path/to/this/file/.eslintignore" 
	}
```

I have also tried adding the patterns with the `"ignorePattern"` option:

```
	"eslint.options": {
		"ignorePattern": "somefile.js"
	}
```

All without luck! All on OS X. 

I am making the assumption here that this is not a bug and rather its my miss-understanding of the implementation...

**Comment by lean** [comment]
I am without luck too. I am on Win 10 and can not find the mode to run the linter. 
I have this in my config file:
```json	
"eslint.enable": true,
"javascript.validate.enable": false
```
whats wrong ?

**Comment by jwulf** [comment]
@dbaeumer: something like

"Thanks for installing the fabulous eslinter extension. Here's how you use it:"

**Comment by dbaeumer** [comment]
@lean: to get a decent eslint validation you need to have a .eslintrc file. You can generate one using the eslint cli and run eslint --init.

I also updated the readme to explain the option bag and to help with the getting started. See https://marketplace.visualstudio.com/items/dbaeumer.vscode-eslint

**Comment by egamma** [comment]
@dbaeumer would it make sense to provide a command that creates a default .eslintrc file?

**Comment by dbaeumer** [comment]
@m-sanders: I create a separate issue for the ignore file since it is a bug not covered by the readme update. See #6

**Comment by dbaeumer** [comment]
@egamma yes, opened #7
