### ISSUE TITLE
 Configuration for rule "no-console" is invalid

### ISSUE THREAD

**Issue by palnes** [Microsoft/vscode-eslint#100]
Error message: 
`Configuration for rule "no-console" is invalid: Value "2,[object Object]" has more items than allowed.`

.eslintrc:
`"no-console": [2, { "allow": ["warn", "error"] }],`

There are several of these errors on various rules, all linked to configuration options. eslint CLI does not report errors on the `.eslintrc`, nor on the use of `console.warn` or `console.error`.

**Comment by dbaeumer** [comment]
Works for me on latest. Closing.

![capture](https://cloud.githubusercontent.com/assets/1931590/22589538/0ca90846-ea0b-11e6-8643-9ca7df643bb9.png)
