### ISSUE TITLE
An option for autofixing certain types of suggestions

### ISSUE THREAD

**Issue by kachkaev** [microsoft/vscode-eslint#1000]
The [suggestions API](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions) helps avoid unwanted 'magic' changes, but may become an inconvenience in some circumstances. We recently bumped the dependencies in one large project and noticed that [`react-hooks/exhaustive-deps`](https://reactjs.org/docs/hooks-rules.html#eslint-plugin) is no longer being autofixed.

I understand that this is a feature and not a bug – it originates from https://github.com/facebook/react/issues/16313 and has valid reasons. However, I was wondering if VSCode ESLint extension could provide a solution this new need to manually accept trivial suggestions in some selected cases.

We follow the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html) in all components, so after writing a new React hook we end up using this menu with an almost 100% probability:

![Screenshot 2020-06-25 at 12 28 01](https://user-images.githubusercontent.com/608862/85711905-aa56d100-b6df-11ea-8108-3311723ddea8.png)

It’d be great if we could, say, mention `react-hooks/exhaustive-deps` somewhere in VSCode’s `settings.json` and save ourselves from a need to do that. VSCode ESLint extension would just pick the first available suggestion from the list as if we used the menu if _autofix on save_ is enabled.

I saw @dbaeumer’s statement saying that [suggestions by definition can't be autofixed](https://github.com/microsoft/vscode-eslint/issues/91#issuecomment-601620498). This makes me wonder if this is a conceptual or a technical limitation. If it's the former, what what do you think of enhancing the extension and thus helping developers save time in the described scenario?

**PS:** Congrats on issue #1000 🎉🕺 Awesome extension ❤️

**Comment by dbaeumer** [comment]
@kachkaev I see your point but IMO something like this shouldn't go into the extension. It would IMO be more consistent if the react ESLint plugin would allow you to say to generate an auto fix instead of a suggestions. This would then keep all the ESLint config in one place.
