### ISSUE TITLE
prefer-template autofix adds extra spaces inside placeholders.

### ISSUE THREAD

**Issue by mattfbacon** [microsoft/vscode-eslint#1001]
Here's an example:   
```js
var foo = 3;
var baz = 'bar' + foo;
```
Invoking `eslint --fix` from the command line results in the proper correction: ``var baz = `bar${foo}`;``. However, using VSCode's Quick Fix ("Fix this prefer-template problem") results in the following: ``var baz = `bar${··foo}`;`` (The dots indicate spaces). It would seem that the number of spaces (in this case 2) around the concatenation operator are prepended inside the placeholder.      
For example, if I write, `var baz = 'bar'··+··foo;`, then I'll get, ``var baz = `bar${····foo}`;``.

Conversely, if I were to write `var baz = foo·+·'bar';`, I would get ``var baz = `${foo··}bar`;``: the same behavior as above.

While this isn't critical (I can always just use `eslint --fix` from the command line) it's quite annoying.

**Comment by dbaeumer** [comment]
@mattfbacon  can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by mattfbacon** [comment]
Here you go: <https://github.com/mattfbacon/prefer-template-issue-demo>

**Comment by rchl** [comment]
@mattfbacon you should probably also provide relevant eslint configuration in your repo.

**Comment by mattfbacon** [comment]
Hmm, now that I've added prefer-template to the .eslintrc, it seems to be an issue with `eslint --fix` as well. I've opened https://github.com/eslint/eslint/issues/13453 and I'll close this.

**Comment by dbaeumer** [comment]
@mattfbacon thanks for reporting this back.

**Comment by mattfbacon** [comment]
Hmm, interesting. The folks at ESLint suggested to add `"parserOptions": { "ecmaVersion": 2015 }` to my .eslintrc, which made `eslint --fix` work. However, the code action in VS Code still exhibits the same issue.

**Comment by dbaeumer** [comment]
@mattfbacon can you please update your sample to contain a package.json file with the eslint version and plugins to install. Thanks

**Comment by mattfbacon** [comment]
Yes, of course. I was using my global version 7.4.0. It has been added.

**Comment by dbaeumer** [comment]
Actually this is correct. eslint --fix fixes all autofixable problems. If you run the same in VS Code (for example using the command or source actions on save) then everything is fix correctly as well.

Internally ESLint generates two fixes, first for the template error and then for the spacing problem. 

I am closing this issue since this is the intended ESLint npm module behavior.

**Comment by mattfbacon** [comment]
Ah, I see. I guess it's just my opinion that the prefer-template fix uses my preference for the curly spacing, but this plugin fixes each issue one by one. Just a different way of thinking about it, and I can appreciate the extra control that that give you.

Thanks for your help.
