### ISSUE TITLE
Feature Request: Can we make the server npm-installable?

### ISSUE THREAD

**Issue by justinabrahms** [microsoft/vscode-eslint#1003]
I'd love the ability to start the server with something like this:

```
npm install vscode-eslint
vscode-eslint-server
```

This will allow me to use this language server in other proceses (beyond eslint) with easy installation mechanisms.

**Comment by dbaeumer** [comment]
Agree that this would be cool.

**Comment by danielpza** [comment]
@dbaeumer any news on this issue? I'll be glad to work on this feature if needed.

**Comment by dbaeumer** [comment]
No news. Feature is marked as `help wanted`

**Comment by danielpza** [comment]
@dbaeumer I made a PR #1053

**Comment by dbaeumer** [comment]
Commented on the PR.

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!

**Comment by entropitor** [comment]
This comment is probably very relevant here as well: https://github.com/microsoft/vscode-eslint/pull/1053#issuecomment-936237529
