### ISSUE TITLE
Feature Request: Lint the whole project when file is closed and has changed.

### ISSUE THREAD

**Issue by ooyyloo** [microsoft/vscode-eslint#1006]
I want to lint the whole project when opening the workspace, and whenever I change the code or I close a file, the specific rules can be executed and the infos of errors that is to be displayed on VSCode are changed.

**Comment by dbaeumer** [comment]
The extension provide a task that can lint the whole project. See `eslint.lintTask` setting. VS Code has the ability to mark task as auto start when opening a workspace. Hope that helps.

**Comment by ooyyloo** [comment]
> The extension provide a task that can lint the whole project. See `eslint.lintTask` setting. VS Code has the ability to mark task as auto start when opening a workspace. Hope that helps.

The rule that I want to implement should be executed when the code is changed and when the file is closed. And I want to see the errors displayed in the code(not in the command line).

**Comment by dbaeumer** [comment]
The errors produces by task are presented in the code and the problem view.

**Comment by ooyyloo** [comment]
> The errors produces by task are presented in the code and the problem view.

The errors produced by task are a bit different in the code from the errors produced by the extension itself, and it's unnecessary to show errors in the problem view when I'm coding.
Could you add a setting which tells this extension to lint the whole project when opening the workspace if the setting is true?

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
