### ISSUE TITLE
show the warning or issue underline only for variable name with `no-var`

### ISSUE THREAD

**Issue by zuhairtaha** [microsoft/vscode-eslint#1008]
When I enable `no-var` rule at vscode it shows a line under the variable declaration and value, but at webstorm it shows that only under the word `var`. It is annoying when the variable name is long for example when it is a function like this:
```js
var doSomething = function () {
// codes goes here...
// codes goes here...
}
```
all code lines will be underlined, but at webstorm only under `var`
Is there anyway to do that for vscode, or maybe if not exists I suggest to add another value for rules like this
```json
  "rules": {
    "no-var": "hint",
```
`"hint"` is my suggestion in addition to `"warn", "error", "off"` that exists

**Comment by dbaeumer** [comment]
Actually the extension doesn't post process any error generated by ESLint itself. So if you do see the same error range in the terminal then there is little I can do.
