### ISSUE TITLE
VSCode eslint not showing warnings from "plugin:" rules

### ISSUE THREAD

**Issue by razvanmandache** [microsoft/vscode-eslint#1009]
I'm migrating from TSLint to ESLint in a React CRA project.
Using eslint 6.6.0.

I have the following eslint config
`{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
    "react-app",
    "prettier"
  ],
  "rules": {
    "no-console": "warn"
  }
}`

As per CRA docs, I set the following variable in the .env file
`EXTEND_ESLINT=true`

Due to "_plugin:@typescript-eslint/recommended_" i get the following warning on build

`./src/services/usePromise.ts
  Line 30:12:  Missing return type on function  @typescript-eslint/explicit-function-return-type`

But VSCode does not show the warning in the editor

![image](https://user-images.githubusercontent.com/8089471/87295925-41a48c80-c506-11ea-85e3-9fd1a723c589.png)

If I then manually add the rule in .eslintrc such

`  
...
"rules": {
    "no-console": "warn",
    "@typescript-eslint/explicit-function-return-type": "warn"
  }`

Then VSCode picks up and displays the warning in the editor

![image](https://user-images.githubusercontent.com/8089471/87296053-787aa280-c506-11ea-837c-34b2a5c4249f.png)

It looks like, while the rules coming from the typescript-eslint plugin are picked up by eslint when linting from the command line, VSCode eslint ignores the rules coming from the plugin.

If I remove "_plugin:@typescript-eslint/recommended_" from "_extends_" array, then the warning does not show up in the command line on build, so I'm quite sure that that is the rule's source.

**Comment by dbaeumer** [comment]
@razvanmandache can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by razvanmandache** [comment]
Hi @dbaeumer 
Thanks for taking an interest in this. 

I created a new CRA project in this repo here https://github.com/razvanmandache/vscode-eslint-test

Had some trouble reproducing the issue, but managed to do in the end.
I started by copying the relevant config (e.g. .eslintrc) files and the relevant packages (e.g. eslint, typescript-eslint, etc.) from the project I encountered the issue in to the new CRA project. I installed the packages, ran the dev-server, but I did not experience the same issue again i.e. I did not get the related warning in the console . It seem that what I initially copied (in this 2nd commit [964ee08](https://github.com/razvanmandache/vscode-eslint-test/commit/964ee08e529a4633bc35c8e829742e9a3909c39f)) was not enough to cause an issue.

I then copied over the entire contents of package.json from the main project, reinstalled all the packages (after deleting package.lock.json and node_modules) and only then the warning started showing up.
I thought that whatever changed in this 3rd commit here [de0941c](https://github.com/razvanmandache/vscode-eslint-test/commit/de0941c9e3a487c504cfd9707516df48116650ab) has something to do with it. 

I removed some irrelevant packages in a 4th commit [9df93ec](https://github.com/razvanmandache/vscode-eslint-test/commit/9df93ec0ec483f05ac428f12c027845c8f472162), reinstall packages, ran the dev server and again the warning message was there. 

Just to double check, I checked out the last commit where the issue was not present (meaning this 2nd commit [964ee08](https://github.com/razvanmandache/vscode-eslint-test/commit/964ee08e529a4633bc35c8e829742e9a3909c39f), reinstalled the packages as before, but unfortunately when I ran the dev server, I did get the warning message again. 


In neither case, when the warning was present in the console or not, the warning did not show up as a squiggly yellow line in VSCode text editor. I'm now starting to think that's more likely a problem with either my setup or one of the eslint plugin, then with the eslint extension, but you can of course try it out for yourself too if you want.

**Comment by dbaeumer** [comment]
Actually, I cloned the repository and I don't see any errors when executing eslint in the terminal using `./node_modules/.bin/eslint src/usePromise.ts`. In general the extension behaves as eslint executed on the command line. Can you please ensure that executing eslint in the terminal works correctly. If you still don't see an error in VS Code, please ping with steps to reproduce.

**Comment by razvanmandache** [comment]
Thanks for testing this out.

I have tested myself too and it does work as expected when running eslint from command line.
Seems that it's most likely an issue with how CRA handles the eslint config and not with vscode eslint extension.

**Comment by dbaeumer** [comment]
@razvanmandache how did you run ESLint in the terminal.

**Comment by razvanmandache** [comment]
I ran it as you described with "/node_modules/.bin/eslint src/usePromise.ts".
I was confirming that, just like yourself, I did not get any warnings or errors when running from the command line. 
Sorry if my phrasing wasn't clear. 

The vscode eslint extension seems to be handling the eslint config correctly i.e. produces the same results as when linting from the command line.

**Comment by dbaeumer** [comment]
OK. That makes sense then. I will close the issue. Please ping if you still think there is something that needs to be done in the extension itself.
