### ISSUE TITLE
Parsing error of a not existent tsconfig.json file

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode-eslint#1010]
Issue Type: <b>Bug</b>

I was not able to determine what triggers the following behavior:

- I'm editing the file `client/client.ts`
- Suddenly, for various files opened in tabs (not all of them), the following error appears:
`Parsing error: Cannot read file 'c:\program files\microsoft vs code\client\tsconfig.json'.` The details of one of them are:
```
{
	"resource": "/D:/Projects/MyProject/client/types.d.ts",
	"owner": "eslint",
	"severity": 8,
	"message": "Parsing error: Cannot read file 'c:\\program files\\microsoft vs code\\client\\tsconfig.json'.",
	"source": "eslint",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```
See the screenshot:
![image](https://user-images.githubusercontent.com/865866/87323170-b55a8f80-c52e-11ea-9a70-aba60c14b947.png)

If I click on one of the error messages (for example related to the file `types.d.ts`), the following notification appears:
```
Unable to open 'types.d.ts': ModelService: Cannot add model because it already exists!.
```
When the problem happens, the only solution is to restart VSCode.
Eslint works perfectly except for this.
I'm continuing monitoring my environment to see if I can determine what triggers the problem.
Thanks for looking!
mario

Extension version: 2.1.6
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.00GB free)|
|Process Argv|D:\Projects\IdeaIgniterEnvironment\IdeaIgniterEnvironment.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@crystalfp  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by crystalfp** [comment]
Thanks! This does not happen from the terminal, only in VS Code. The problem I have to provide an example is that I don't know yet what triggers this behavior. It happens sometimes. Do you have any suggestion on what to collect when it happens?
Thanks!
mario

**Comment by crystalfp** [comment]
It seems that eslint plugin loses the workspace directory value and resort to the program installation directory.

**Comment by dbaeumer** [comment]
@crystalfp actually the server set the workspace directory on every validation run. So a GitHub repository that demos that would be highly appreciated.

**Comment by missferret** [comment]
This is actually happening to me with Webstorm...

**Comment by dbaeumer** [comment]
A reproducible case would still be helpful.

**Comment by agcty** [comment]
Also see this happening  🤔

**Comment by dbaeumer** [comment]
@agcty can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by agcty** [comment]
> @agcty can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

I'm not sure how to reproduce this to be honest, I just tried to copy my repo and then I was presented with this popup:

![image](https://user-images.githubusercontent.com/12101091/89621780-36891600-d892-11ea-88c9-d9cd69a958f0.png)

After you click allow it seems to work as expected. Is there any way to force this popup in existing repos?
