### ISSUE TITLE
Unable to resolve path to module

### ISSUE THREAD

**Issue by captDaylight** [microsoft/vscode-eslint#1013]
Code runs as expected when I start me server, and I can run `eslint` on the command line without any errors. However, in vscode I'm getting the errors `Unable to resolve path to module './routes/index'.eslintimport/no-unresolved` and 
`Missing file extension for "./routes/index"eslintimport/extensions` when I open `./src/index.ts`:

```ts
import express from 'express';
import routes from './routes'; // issue here
// import routes from './routes/index'; // I've also tried this

const app = express();
const port = process.env.SERVER_PORT || 8080;

app.use('/', routes);

app.listen(port, () => {
  console.log(`server started at http://localhost:${port}`);
});
```

Vscode will even autocomplete the file structure but still show the eslint error after.

Folder structure:
```
├── .eslintrc.json
├── .vscode
│   └── settings.json
├── package.json
└── src
    ├── index.ts
    └── routes
        └── index.ts
```

I've tried both of these `.vscode` settings:
```json
{
    "eslint.workingDirectories": [
      "./src"
    ]
}
```
(found the below from #595)
```json
{
    "eslint.workingDirectories": [
      { "directory": "./src", "changeProcessCWD": true }
    ]
}
```

eslint version:
`"eslint": "^7.3.1",`

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
