### ISSUE TITLE
No error highlighting

### ISSUE THREAD

**Issue by LadIQe** [microsoft/vscode-eslint#1014]
Hi guys, I have really strange problem with my projects.

I have multiple projects but 2 of them have same base and use same versions of eslint and prettier and also same version of .eslintrc.js. Both of them are typescript react projects

Weird thing is that one project is working fine, eslint is highlighting errors and also formatting them. Second project only formats and thats it.

I tried
- reinstalling vs code
- reinstalling extensions
- reinstalling packages
- installing latest versions of packages
- set different rules

Nothing works.

Here is .vscode folder
```
{
  "typescript.tsdk": "node_modules\\typescript\\lib",
  "editor.formatOnSave": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ]
}
```

Here is .eslintrc.js
```
module.exports = {
  parser: '@typescript-eslint/parser',  // Specifies the ESLint parser
  extends: [
    'plugin:react/recommended',  // Uses the recommended rules from @eslint-plugin-react
    'plugin:@typescript-eslint/recommended',  // Uses the recommended rules from @typescript-eslint/eslint-plugin    
    "prettier/@typescript-eslint", // Uses eslint-config-prettier to disable ESLint rules from @typescript-eslint/eslint-plugin that would conflict with prettier
    "plugin:prettier/recommended" // Enables eslint-plugin-prettier and eslint-config-prettier. This will display prettier errors as ESLint errors. Make sure this is always the last configuration in the extends array.
  ],
  
  parserOptions: {
    ecmaVersion: 2018,  // Allows for the parsing of modern ECMAScript features
    sourceType: 'module',  // Allows for the use of imports
  },
  rules: {
    // Place to specify ESLint rules. Can be used to overwrite rules specified from the extended configs
    // e.g. "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/no-inferrable-types": false,
    "@typescript-eslint/ban-ts-ignore": false,
    "@typescript-eslint/camelcase": false,
    "@typescript-eslint/no-use-before-define": false,
    "@typescript-eslint/no-var-requires": false,
    "@typescript-eslint/no-namespace": false,
    "@typescript-eslint/explicit-function-return-type": false,
    "@typescript-eslint/interface-name-prefix": false,
    "@typescript-eslint/no-explicit-any": false,
    "@typescript-eslint/no-non-null-assertion": false,
    "@typescript-eslint/no-unused-vars": false,
    "react/no-deprecated": false,
    "react/display-name": false,
  },
};
```

Here is .prettierrc.js
```
module.exports = {
  semi: true,
  trailingComma: "all",
  singleQuote: true,
  printWidth: 160,  
};
```

Part of package.json
```
"@typescript-eslint/eslint-plugin": "^2.6.1",
"@typescript-eslint/parser": "^2.6.1",
"eslint": "^5.13.0",
 "eslint-config-airbnb": "^17.1.0",
 "eslint-config-prettier": "^6.5.0",
 "eslint-formatter-friendly": "^6.0.0",
 "eslint-import-resolver-webpack": "^0.10.1",
 "eslint-loader": "^2.1.0",
 "eslint-plugin-import": "^2.14.0",
 "eslint-plugin-jsx-a11y": "^6.1.1",
 "eslint-plugin-prettier": "^3.1.1",
 "eslint-plugin-react": "^7.11.1",
 "eslint-plugin-react-redux": "^2.3.0",
 "prettier": "^1.19.1",
```

Thank you guys

edit: I forgot one thing, when I open .js files, highlighting works well

**Comment by sramzan** [comment]
+1 I had to downgrade my version of the eslint plugin to 2.16 and everything is working again. 

Due to the latest version of either the plugin or VSCode there is a prompt when launching VSCode that asks if I would like to allow "node_modules/eslint" to be used. Seems like there is a class between the latest eslint version and VSCode.

**Comment by MrKafr** [comment]
+1 same problem. Even downgrading eslint extension does not help. One project is working and others doesnt.

**Comment by dbaeumer** [comment]
@LadIQe does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
@jjensen-ebsco this is expected. Since the ESLint extension loads and executes code on the users behalf we had to add a dialog letting the user know about it. If you don't allow it the extension will not load the ESLint library and hence can't validate the file.

**Comment by LadIQe** [comment]
ok so I have update, I deleted everything that have eslint in name, reinstalled packages, created config files from scratch, now it is working. I have no idea where was problem, I got this idea when I created test project where everything was working as expected, so sorry for no more usable info for this kind of problem :/

**Comment by dbaeumer** [comment]
OK Thanks. I will close the issue then.
