### ISSUE TITLE
eslint error: Received request 'eslint/probleFailed in yarn monorepo project

### ISSUE THREAD

**Issue by heavenkiller2018** [microsoft/vscode-eslint#1015]
I created a vue typescript  project. Eslint works correct in alone repo, but occurs some error in  in yarn monorepo project.

I created a repo to show this problem: https://github.com/heavenkiller2018/vue-monrepo-eslint_error.
![image](https://user-images.githubusercontent.com/45555611/87792651-c5e47000-c876-11ea-8e63-80f376e32853.png)

eslint of vscode could function correct in *.vue, 
![image](https://user-images.githubusercontent.com/45555611/87792947-25db1680-c877-11ea-8498-ac525ede0338.png)

but not in other files like *.ts, *.js.  and the output of eslint console shows: 
![image](https://user-images.githubusercontent.com/45555611/87792994-3b504080-c877-11ea-9ea9-82cde56f0836.png)

```shell
[Trace - 下午9:25:43] Received notification 'eslint/status'.
[Trace - 下午9:25:43] Received request 'eslint/probleFailed - (35)'.
[Trace - 下午9:25:43] Sending response 'eslint/probleFailed - (35)'. Processing request took 0ms
```

I don't know wha'ts the matter. It seems about the eslint module of vscode
@dbaeumer
![a](https://user-images.githubusercontent.com/45555611/87793633-19a38900-c878-11ea-88be-2677c6c5895e.png)
![b](https://user-images.githubusercontent.com/45555611/87793634-1b6d4c80-c878-11ea-960d-dc1683e187d7.png)

**Comment by dbaeumer** [comment]
@heavenkiller2018  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
