### ISSUE TITLE
Extension won't run with pnpm

### ISSUE THREAD

**Issue by brunoparga** [microsoft/vscode-eslint#1018]
Hello! Whenever my editor tries to run ESLint automatically via the extension, I run into the following error:

```
(node:97815) UnhandledPromiseRejectionWarning: Error: Command failed: pnpm root -g
 ERROR  No write access to the found global executable directories

    at checkExecSyncError (child_process.js:634:11)
    at Object.execSync (child_process.js:670:15)
    at Object.execSync (electron/js2c/asar.js:696:23)
    at Object.get (/home/bruno/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.1.5/server/out/eslintServer.js:1:33524)
(...)
```

Is this related to the newly-added support for pnpm on vscode? Any ideas on how to get the extension working again?

Thanks!

**Comment by dbaeumer** [comment]
@brunoparga what happens when you run `pnpm root -g`

**Comment by brunoparga** [comment]
```
 ERROR  No write access to the found global executable directories
The found directories:
/usr/bin
/bin
```

That's the same error I get when I try `pnpm add -g <package_name>`. What I think this means is that something in the extension is trying to do something I can only do as root.

**Comment by dbaeumer** [comment]
Yes, that problem is that I need to know where global package are installed. The interesting thing is that I only need to read a setting not to write to a global location. Has anyone a idea how to solve this. I am not a `pnpm` expert.

**Comment by brunoparga** [comment]
Thank you for your replies. I am not an expert either, just a user. I have forwarded your explanation to their Gitter channel. Is there anything else I could do to help you help me?

**Comment by dbaeumer** [comment]
Lets see what is coming back.

**Comment by brunoparga** [comment]
As per the referenced issue, this has been solved by `pnpm` allowing access to the setting your extension needs. Thank you very much for your help, Dirk!
