### ISSUE TITLE
Formatting not working for javascriptreact files

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/vscode-eslint#1022]
I tried enabling it using 

```json
		"eslint.format.enable": true,
		"[javascript]": {
			"editor.defaultFormatter": "dbaeumer.vscode-eslint"
		},
		"[javascriptreact]": {
			"editor.defaultFormatter": "dbaeumer.vscode-eslint"
		}
```

but I always get the "extension eslint cannot format ..." error. For plain js files it works fine though.

**Comment by dbaeumer** [comment]
@ThiefMaster can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by ThiefMaster** [comment]
I was testing on my project https://github.com/indico/indico/ but it's kind of huge, so not sure if it's a good way to reproduce it. I hoped it may simply be some hardcoded check that only allows it to run on `javascript` files but not any other JS-like file type.

Let me know if there's any place I can look for details what may cause this error. There's nothing in the ESLint output pane related to it.

**Comment by dbaeumer** [comment]
Actually it is huge. Can you try to produce a stiped down version. The formatter works for me without problems. 

One thing: do code actions on save work for you?

**Comment by ThiefMaster** [comment]
OK I just had the same problem with a normal .js file, and found some JSX files where it worked just fine...

![image](https://user-images.githubusercontent.com/179599/87947202-45ef1d80-caa3-11ea-8bcc-b93e36b3f26d.png)


In case it helps, `permissions_widget.js` is one of the files where it does not work. If I run "Format document with" I also don't get eslint as an option to choose.

**Comment by dbaeumer** [comment]
Can you do two things:

- on a file where it fails can you run eslint in the terminal with the --fix option to see if it works there. 
- if yes,  can you add the `eslint.debug: true` setting and provide the output of the ESLint channel.

**Comment by ThiefMaster** [comment]
Oh, I found the problem. This file is listed in my `.eslintignore`. It would be nice if there was an option to use eslint's `--no-ignore` option because while I may not want to see eslint warnings when running eslint via pre-commit or CI, I may want to see them when actually editing such a file.

**Comment by dbaeumer** [comment]
@ThiefMaster you can. See the setting `eslint.options` documented here: https://github.com/microsoft/vscode-eslint According to the CLI documentation the property to set is `ignore`

**Comment by ThiefMaster** [comment]
Thanks, this helped:

```json
		"eslint.options": {
			"ignore": false,
		},
```
