### ISSUE TITLE
All files with an `eslintignore` file extension should be considered of type "Ignore"

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode-eslint#1024]
The extension only applies the "Ignore" language to files with the exact name `.eslintignore` by default.
It should instead include all files ending with the extension `eslintignore`, regardless of the prefix.

VSCode's built in file icon theme recognizes the file as an eslintignore file and shows the matching icon beside it,
but this extension doesn't apply the language to it.

A project might include multiple `.eslintignore` files in the same folder, and configure ESLint to use one or the other,
depending on the need. All of the files should have the correct language regardless of their filename, all that should matter is the file extension.

**Repro:** Create and open a file named `project.eslintignore`
**Expected:** The language mode will be set to the "Ignore" language
**Actual:** The language mode is "Plain Text"

**Comment by dbaeumer** [comment]
Makes sense to me.
