### ISSUE TITLE
The extension is behind the editor and improperly reports errors

### ISSUE THREAD

**Issue by sean256** [microsoft/vscode-eslint#1026]
I can't reliably replicate this on demand, but it's been happening frequently enough that it's becoming a problem.

Here is a snippet of what code I have in the editor

```js
{
  // ...stuff up here
  foobar: {
    dialog: [
      {
        name: `Foo ${R}`,
        text: '[large]stuff![/]',
        pos: 'right',
      },
    ],
  },
}
```

This is what the ESLint Extension sees

![Screen Shot 2020-07-23 at 1 26 23 PM](https://user-images.githubusercontent.com/6920955/88335863-d9656000-cce8-11ea-8b6d-e602fdb75460.png)

Eventually after enough edits it will eventually catch up. Sometimes I have to relaunch VSCode to get it to update. I'm not even sure where to begin troubleshooting this.

**Comment by dbaeumer** [comment]
As always it would be best to have reproducable steps. But I understand that this is hard in that case. Could you enable tracing `"eslint.trace.server": "messages"` and post the trace from the eslint output channel here.

**Comment by sean256** [comment]
I got something to reliably replicate,

stringFunctions.js
```js
const templateReplacer = (templateString, map) => templateString
	.replace(/{{(\w+)}}/g, (match, key) => {
		const value = map[key];
		return value || match;
	});

const foo = {
	foobar: {
		dialog: [
		  	{
				name: `Foo ${R}`,
				text: '[large]stuff![/]',
				pos: 'right',
			},
		],
	},
};

module.exports = {
	templateReplacer,
	foo,
};

```

If I open this file eslint will be fine. But, if I cut and paste back the contents inside the `foo` object it will error out and tell me there is a false error.

Here is the output you asked for:

```
[Trace - 5:41:57 PM] Sending notification 'textDocument/didOpen'.
[Trace - 5:41:57 PM] Received request 'workspace/configuration - (39)'.
[Trace - 5:41:57 PM] Sending response 'workspace/configuration - (39)'. Processing request took 3ms
[Trace - 5:41:57 PM] NODE_PATH value is: /Users/REDACTED/.nvm/versions/node/v12.16.1/lib/node_modules
[Trace - 5:41:58 PM] Received notification 'window/logMessage'.
[Info  - 5:41:58 PM] Cannot read property 'value' of null Occurred while linting /Volumes/REDACTED/source/lib/common/stringFunctions.js:11
[Trace - 5:41:58 PM] Received notification 'eslint/status'.
[Trace - 5:42:02 PM] Sending notification 'textDocument/didChange'.
[Trace - 5:42:02 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 5:42:02 PM] Received notification 'eslint/status'.
[Trace - 5:42:03 PM] Sending notification 'textDocument/didChange'.
[Trace - 5:42:03 PM] Received notification 'window/logMessage'.
[Info  - 5:42:03 PM] Cannot read property 'value' of null Occurred while linting /Volumes/REDACTED/source/lib/common/stringFunctions.js:11
[Trace - 5:42:03 PM] Received notification 'eslint/status'.
[Trace - 5:42:11 PM] Sending request 'textDocument/codeAction - (342)'.
[Trace - 5:42:11 PM] Received response 'textDocument/codeAction - (342)' in 3ms.
```

**Comment by sean256** [comment]
Finally have something legit. I found a file which reliably replicates the issue and I have no idea why.

Output:

```
[Trace - 5:49:00 PM] Sending request 'textDocument/codeAction - (361)'.
[Trace - 5:49:00 PM] Received response 'textDocument/codeAction - (361)' in 0ms.
[Trace - 5:49:01 PM] Sending notification 'textDocument/didClose'.
[Trace - 5:49:01 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 5:49:03 PM] Sending notification 'textDocument/didOpen'.
[Trace - 5:49:03 PM] Received request 'workspace/configuration - (42)'.
[Trace - 5:49:03 PM] Sending response 'workspace/configuration - (42)'. Processing request took 5ms
[Trace - 5:49:03 PM] NODE_PATH value is: /Users/REDACTED/.nvm/versions/node/v12.16.1/lib/node_modules
[Trace - 5:49:03 PM] Received notification 'window/logMessage'.
[Info  - 5:49:03 PM] Cannot read property 'value' of null Occurred while linting /Volumes/REDACTED/source/lib/web/REDACTED/REDACTED.js:38
[Trace - 5:49:03 PM] Received notification 'eslint/status'.
[Trace - 5:49:06 PM] Sending notification 'textDocument/didChange'.
[Trace - 5:49:06 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 5:49:06 PM] Received notification 'eslint/status'.
[Trace - 5:49:06 PM] Sending notification 'textDocument/didChange'.
[Trace - 5:49:06 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 5:49:06 PM] Received notification 'eslint/status'.
[Trace - 5:49:07 PM] Sending notification 'textDocument/didChange'.
[Trace - 5:49:07 PM] Received notification 'window/logMessage'.
[Info  - 5:49:07 PM] Cannot read property 'value' of null Occurred while linting /Volumes/REDACTED/source/lib/web/REDACTED/REDACTED.js:38
[Trace - 5:49:07 PM] Received notification 'eslint/status'.
```

Since this is for work, I had to heavily redact some of this, but the "problem" line is intact.

```js
const L = 'FOO';
const R = 'BAR';

// TODO: COMPLETE TEXT

module.exports = {
	start: {
		dialog: [
			{
				name: 'Bob',
				text: 'REDACTED',
			},
			{
				name: 'Bob',
				text: 'REDACTED',
				pos: 'right',
			},
		],
		choices: [
			{
				text: 'REDACTED',
				toNode: 'foo',
			},
		],
	},
	foo: {
		dialog: [
			{
				name: 'Bob',
				text: 'REDACTED',
			},
			{
				name: 'Bob',
				text: 'REDACTED',
				pos: 'right',
			},
			{
				name: `Char ${L}`,
				text: `REDACTED`,
			},
			{
				name: `Char ${R}`,
				text: 'REDACTED',
				pos: 'right',
			},
			{
				name: `Char ${L}`,
				text: 'REDACTED',
			},
			{
				name: `Char ${L}`,
				text: 'REDACTED',
			},
		],
		choices: [
			{
				text: 'REDACTED',
				toNode: 'bar',
			},
			{
				text: 'REDACTED',
				toNode: 'foobar',
			},
		],
	},
};
```

The full file is 320 lines. I discovered if I cut it down to less than 100 lines it doesn't happen. Maybe some async race condition with line processing??

**Comment by dbaeumer** [comment]
@sean256 thanks for getting back. This actually looks like a problem with ESLint itself (e.g. `Cannot read property 'value' of null Occurred while linting /Volumes/REDACTED/source/lib/web/REDACTED/REDACTED.js:38` https://github.com/eslint/eslint/blob/master/lib/linter/linter.js#L1182)

Since you can reproduce this. When it happens does linting work in the terminal on that file.

**Comment by sean256** [comment]
> This actually looks like a problem with ESLint itself

If I run eslint from the CLI it's fine. I'm not sure how this plugin works, but somehow it (with eslint?) are seeing an outdated version of the file. In my very first post here you can see the discrepancy in the screenshot. What the eslint plugin shows is not what is actually in the editor.

**Comment by dbaeumer** [comment]
That is really strange since the actual exception comes from ESLint itself. The line `Cannot read property 'value' of null Occurred while linting /Volumes/REDACTED/source/lib/web/REDACTED/REDACTED.js:38` is issued by the ESLint npm module. It doesn't come from the extension.

Do you see a chance to provide me with a GitHub repository I can clone that demos this?

**Comment by sean256** [comment]
I found my issue!

I was using the old `babel-eslint` parser. When I swapped it out for `@babel/eslint-parser` it all started working.

It's still very strange that running `eslint` from cli worked thought, 🤷‍♂️

**Comment by dbaeumer** [comment]
@sean256 for better performance the extension keeps an ESLint process running that it reuses. Otherwise we would need to launch a new process after every n ms
