### ISSUE TITLE
Is it possible to upload the latest 2.1.9 version of vsix to the GitHub release?

### ISSUE THREAD

**Issue by yaegassy** [microsoft/vscode-eslint#1029]
Thanks for this language server and VSCode extension!

I build `vscode-eslint` and use it primarily in `Vim`.

It is very useful to have a pre-built vscode-eslint available.

No vsix uploads on GitHub release since the "2.1.4 preview release".

https://github.com/microsoft/vscode-eslint/releases/tag/release%2F2.1.4-next.1

Is it possible to upload the latest 2.1.9 version of vsix to the GitHub release?

Also, it would be very helpful if you could upload it when you version up.

**Comment by dbaeumer** [comment]
2.1.9 is not officially released yet. I uploaded 2.1.8.
