### ISSUE TITLE
Create a run command

### ISSUE THREAD

**Issue by garyee** [microsoft/vscode-eslint#1030]
Hi,

very good extension I would be lost without.
For my workflow it would be great if there where a doLint command, so that I could bin a keyboard shortcut to it.
My problem basically is that if i set `eslint.run` to `onType`  I get overwelmed with all the red lines so I set it to `onSave`. But if I save the file my project will immediatly start to rebuild which is good, just not if I got an error because I have to build it "from zero" which takes more time then a rebuild.
If I could trigger the run manually with a keyboard shortcut this would solve my problem, as I could trigger the linting manually.

**Comment by dbaeumer** [comment]
The `eslint.lintTask.enable` option might be your friend. It adds a task to which you then can bind a keyboard shortcut. If you only want to validate a single file you can always create a custom task using variables and bind a keyboard short cut to the custom task.
