### ISSUE TITLE
Extension issue take time

### ISSUE THREAD

**Issue by farrukhjalil** [microsoft/vscode-eslint#1032]
- Issue Type: `Bug`
- Extension Name: `vscode-eslint`
- Extension Version: `2.1.8`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.47.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by dbaeumer** [comment]
@farrukhjalil you don't have the content from the clipboard anymore. Without it there is little I can do.
