### ISSUE TITLE
"lint whole folder" task on Windows does not work if "bash" is used as default shell

### ISSUE THREAD

**Issue by pkrukp** [microsoft/vscode-eslint#1038]
Hi,

I'm using "Git Bash" as default shell for vscode. If I try to run "lint whole folder" task it ends with error:

```
> Executing task: node_modules\.bin\eslint.cmd . <

/usr/bin/bash: node_modules.bineslint.cmd: command not found
The terminal process "C:\Program Files\Git\bin\bash.exe '-c', 'node_modules\.bin\eslint.cmd .'" failed to launch (exit code: 127).
```

bash interprets "\\" as special character.

I wonder if there's some solution for this... Maybe force using "Command Prompt" (cmd.exe) as shell?
I tried using forward slashes: `node_modules/.bin/eslint.cmd .`  but cmd.exe does not like it: `'node_modules' is not recognized as an internal or external command`

ESLint from marketplace (v2.1.8)

**Comment by nair-sumesh** [comment]
Same here. Any solution found yet?

**Comment by dbaeumer** [comment]
Dups #795
