### ISSUE TITLE
extension does not work with extended config files

### ISSUE THREAD

**Issue by jasonswearingen** [microsoft/vscode-eslint#1041]
If I have a ```.eslintrc.js``` like this, it works for build-time linting but not the eslint VSCode plugin:

```javascript
// This is a workaround for https://github.com/eslint/eslint/issues/3458
require('@rushstack/eslint-config/patch/modern-module-resolution');

module.exports = {
	extends: ['@xlib/eslint-config'],
	parserOptions: { tsconfigRootDir: __dirname },
	rules: { 'tsdoc/syntax': 'error' }
};
```

I tried a lot of different things, including just having the ```@xlib/eslint-config``` do nothing except a single rule, and do nothing except itself extend ```@rushstack/eslint-config```  but nothing works.

Here is a git branch with the example code:  https://github.com/jasonswearingen/xlib-monorepo/tree/vscode-eslint-bug1

and here are repro instructions:
```bash
npm install -g pnpm
pnpm install -g @microsoft/rush
# navigate to the xlib-monorepo
cd ./repos/xlib-monorepo/
rush install
rush build  #you'll see eslint errors show up
cd ./example-apps/verify-node/
code .  
```
- running vscode, open the ```.eslintrc.js``` and ```example.test.ts``` files.   you'll see that no eslint error show up.
- from the ```rush build``` step above you would see the eslint warnings, and also if you run ```pnpm build``` you'll see them.

**Comment by jasonswearingen** [comment]
I should add, that with some extend choices it seems to work, but when trying to create a repro step to show that I wasn't able to find an example of it sometimes working.

**Comment by dbaeumer** [comment]
@jasonswearingen this is very likely caused by the same reason described here: https://github.com/microsoft/vscode-eslint/issues/1040#issuecomment-669193727

The rush tool patches the ESLint script to make ESLint work in their setup which VS Code doesn't know about. IMO they should if this patching is necessary do the same for VS Code settings. 

Please ping if you think this is not a dub of #1040.

**Comment by jasonswearingen** [comment]
@dbaeumer it may be related, but not the same problem I think.

In my project's main branch if I use ```extends: ['@rushstack/eslint-config'],```  your eslint plugin works.     It's only when I try to  ```extends: ['@xlib/eslint-config'],``` my own (basically empty) eslint-config that the VSCode ESLint plugin doesn't work.

I didn't mention this because in my basic repro steps because it doesn't seem to work on my windows machine  (but it does under ubuntu via WSL2)

That said, this module resolution stuff + derived configs from multiple packages that rushstack does sure seems super hacky, so I don't blame you for not wanting to look at it.  I'm just going to copy/paste the eslint configs for the near term.

**Comment by jasonswearingen** [comment]
i created an sample project from scratch and eslint seems to work with extends.  so probably is a rushstack problem.  I'll be doing more research on this.

**Comment by jasonswearingen** [comment]
@dbaeumer so I figured out the problem.   mostly "user error"

If people are having problems, I would recomend you tell them to troubleshoot by first running ```eslint .``` from the command line.

In my case, the ```"extends": [ "@xlib/eslint-config",],``` is referencing a project that doesn't have the various eslint plugins installed, so running ```eslint .``` errors with the appropriate messages.      running ```pnpm build``` or ```rush build``` doesn't fail, probably because it's using some internal version of eslint.  so it looks like (from the naive user) that everything is working properly.

**Comment by dbaeumer** [comment]
@jasonswearingen happy to hear that you were able to track this down. And yes `eslint --debug .` helps a lot :-)
