### ISSUE TITLE
Please publish an updated version to OpenVSX

### ISSUE THREAD

**Issue by jankeromnes** [microsoft/vscode-eslint#1042]
Hello! 👋 

ESLint users from VSCodium, Gitpod, Theia, etc. are all reporting that https://open-vsx.org/extension/dbaeumer/vscode-eslint is now outdated -- it's still `2.1.3` on OpenVSX, while it seems that vscode-eslint `2.1.8` is already out.

See https://github.com/open-vsx/publish-extensions/issues/91

Could you please publish an updated `dbaeumer.vscode-eslint` to https://open-vsx.org ? (It's typically just a matter of running a single command, `npx ovsx publish`.)

Many thanks! 💯 🙏

**Comment by TheJaredWilcurt** [comment]
10 month bump

**Comment by purkhusid** [comment]
Bump! Would be super nice if it was made part of the release process to also release to Open VSX

**Comment by maksimr** [comment]
Do we have any chance to see the new version on Open VSX? 😶

**Comment by 01Sharpshooter** [comment]
It would be super nice as any version <2.2.0 is now just broken for ESLint 8 projects due to the lack of CliEngine which will only become a bigger issue with time. Thanks in advance!

**Comment by dbaeumer** [comment]
@chrisdias assigning to you.

**Comment by 01Sharpshooter** [comment]
Seems like the OpenVSX guys solved it themselves for now. 2.2.2 is available there.
