### ISSUE TITLE
eslint.lintTask.options doesn't work

### ISSUE THREAD

**Issue by bskydive** [microsoft/vscode-eslint#1043]
I'm try to make project independent config file and rule set

```json
"eslint.options": {
		"preferGlobal": true,
		"configFile": "/coding/lint/.eslintrc.js",
},
"eslint.lintTask.options": "--no-eslintrc ."
```
has no effect, when I try to use external eslintrc config

In `/coding/lint/` all works fine, but in other project folders not. I've got eslint error messages about conflicting plugins in `--config` and `local` .eslintrc

cli wariant `eslint --no-eslintrc --debug` works fine in any folder

**Comment by bskydive** [comment]
workaround: rename local project `.eslintrc.js` into `.eslintrc.js1`

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
