### ISSUE TITLE
Autofix being seemingly applied twice

### ISSUE THREAD

**Issue by brunoparga** [microsoft/vscode-eslint#1044]
This is possibly a follow-up to #1018 .

I don't have a 100% clear picture of what's going on, but my best guess is that the autofixes on save are being applied twice. For example, I often get two semicolons at the end of a line which had none. For a more specific and harder to explain example:

```
// original (with a space after undefined)
  if (props) { return props }
  if (notes) { return notes }
  return undefined 

// post-autosave with autofix
  if (props) { return props; }
  if (notes) { return note; s; }
  return undefin; ed;
```

What could be going on here?

VSCodium v1.47.3, extension v2.1.5, node v14.7.0, pnpm v5.4.12. 

Edited to add: another thing that makes me think the autofix is being applied twice is: hitting Ctrl+Z usually makes the file look correct, with the autofix applied.

**Comment by dbaeumer** [comment]
@brunoparga what happens if you run eslint in the terminal with the `--fix` options.  And can you please provide me with a GitHub repository I can clone that demos what you are experiencing. Otherwise it is very hard to tell why this is happening.

**Comment by brunoparga** [comment]
Sorry it took me a while to post this. [This repo](https://github.com/brunoparga/cicero/) has the problem. Running eslint --fix in the terminal performs the right fixes, only once.

The versions have since been updated to VSCodium 1.49.0, vscode-eslint 2.1.5, node 14.10.1,  pnpm 5.5.13.

**Comment by dbaeumer** [comment]
Can you provide me with the VS Code settings.json and which file you are seeing the issue in?

**Comment by brunoparga** [comment]
On this repository, I saw the issue on ./src/components/App.tsx and ./src/components/shared/Topbar.tsx, but I expect it would happen on pretty much any TS files. I think I also saw it on CSS files. On another repo, it also happens on non-TS JavaScript files.

Here's my `settings.json`:

```
{
    "breadcrumbs.enabled": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "diffEditor.renderSideBySide": false,
    "editor.codeActionsOnSave": {
        "source.fixAll": true,
        "source.fixAll.eslint": true,
    },
    "editor.fontFamily": "'Fira Code', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
    "editor.fontLigatures": true,
    "editor.fontSize": 16,
    "editor.minimap.enabled": false,
    "editor.rulers": [
        100
    ],
    "editor.tabSize": 2,
    "eslint.alwaysShowStatus": true,
    "eslint.format.enable": true,
    "eslint.packageManager": "pnpm",
    "eslint.run": "onSave",
    "files.autoSave": "afterDelay",
    "git.autofetch": true,
    "git.confirmSync": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "window.zoomLevel": 0,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.startupEditor": "newUntitledFile",
}
```

**Comment by dbaeumer** [comment]
I don't fully understand why but the eslint server is called two times to compute the fixes. You can woraround this but removing `"source.fixAll": true` from your settings.

**Comment by dbaeumer** [comment]
Root cause is this: https://github.com/microsoft/vscode/issues/106924

I also added some protection code on my end.
