### ISSUE TITLE
ESLint Crashes and Will Not Restart

### ISSUE THREAD

**Issue by henryboisdequin** [microsoft/vscode-eslint#1045]
Issue Type: <b>Bug</b>

Message: The ESLint server crashed 5 times in the last 3 minutes. The server will not be restarted.

After updating VSCode, ESLint crashed and I couldn't use ESLint in my project before reinstalling the extension.

Extension version: 2.1.8
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
