### ISSUE TITLE
Plugin not working with create-react-app projects

### ISSUE THREAD

**Issue by jtarvainen** [microsoft/vscode-eslint#1046]
I cannot get vscode-eslint to work in Visual Studio Code with create-react-app projects. Command-line linting works fine from the project root, but not in the editor (i.e. I get warnings in the command line, but they don't appear in the editor). The plugin also works fine with other projects not created with create-react-app.  

I have not installed eslint globally, and have also not installed it locally for this project since eslint is included with create-react-app.

Versions:
- Node: 12.16.2
- VS Code: 1.47.3
- vscode-eslint: 2.1.8
- create-react-app: 3.4.1
- eslint (included with create-react-app): 6.8.0 

Thanks in advance for your help!

EDIT: here's my package.json:

> {
>   "name": "test-react-app",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@testing-library/jest-dom": "^4.2.4",
>     "@testing-library/react": "^9.5.0",
>     "@testing-library/user-event": "^7.2.1",
>     "react": "^16.13.1",
>     "react-dom": "^16.13.1",
>     "react-scripts": "3.4.1"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject"
>   },
>   "eslintConfig": {
>     "extends": [
>       "react-app",
>       "airbnb"
>     ]
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
>   "devDependencies": {
>     "eslint-config-airbnb": "^18.2.0",
>     "eslint-config-react-app": "^5.2.1",
>     "eslint-plugin-import": "^2.22.0",
>     "eslint-plugin-jest": "^23.20.0",
>     "eslint-plugin-jsx-a11y": "^6.3.1",
>     "eslint-plugin-react": "^7.20.5"
>   }
> }

**Comment by dbaeumer** [comment]
Does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by jtarvainen** [comment]
Thanks for your response.

Yes, the validation works correctly in the terminal.

I tested the issue by simply creating a new React app ('npx create-react-app myApp') and opening it in VS Code. Since this example contains no customization on my end, could you use the same command to verify the issue? I can of course also provide a GitHub repo if that would help.

**Comment by dbaeumer** [comment]
This works for me after creating a poper `.eslintrc.json` for react.

<img width="451" alt="capture" src="https://user-images.githubusercontent.com/1931590/90529044-8d84ca00-e173-11ea-8ef7-3dbaef023e32.png">

**Comment by jtarvainen** [comment]
Could you please share the .eslintrc.json file so I could try it out?

Also, can you confirm that you don't have eslint installed globally?

**Comment by dbaeumer** [comment]
I created the eslintrc file by running `eslint --init`

**Comment by jtarvainen** [comment]
I had previously not done that, since selecting any of the popular style guides as a basis results in the local installation of a version of eslint (in my case, 7.7.0) that is incompatible with create-react-app's requirements and prevents the project from starting with the following error:

> There might be a problem with the project dependency tree.
> It is likely not a bug in Create React App, but something you need to fix locally.
> 
> The react-scripts package provided by Create React App requires a dependency:
> 
>   "eslint": "^6.6.0"
> 
> Don't try to install it manually: your package manager does it automatically.
> However, a different version of eslint was detected higher up in the tree:
> 
> [...]/node_modules/eslint (version: 7.7.0) 
> 
> Manually installing incompatible versions is known to cause hard-to-debug issues.

However, I now ran the command with the following selections:

> ? How would you like to use ESLint? **To check syntax, find problems, and enforce code style**
> ? What type of modules does your project use? **JavaScript modules (import/export)**
> ? Which framework does your project use? **React**
> ? Does your project use TypeScript? **No**
> ? Where does your code run? **Browser**
> ? How would you like to define a style for your project? **Answer questions about your style**
> ? What format do you want your config file to be in? **JavaScript**
> ? What style of indentation do you use? **Tabs**
> ? What quotes do you use for strings? **Single**
> ? What line endings do you use? **Unix**
> ? Do you require semicolons? **No**

This results in the following:

> Local ESLint installation not found.
> The config that you've selected requires the following dependencies:
> 
> eslint-plugin-react@latest eslint@latest
> Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
> Successfully created .eslintrc.js file in [...]/myapp
> ESLint was installed locally. We recommend using this local copy instead of your globally-installed copy.

After doing this, an .eslintrc.js file is created and running eslint in the terminal starts to work (I immediately get errors in index.js). However, validation still doesn't appear in VS Code, even after restarting the editor.

By the way, whenever I open the newly-created React app in VS Code for the first time, it asks me if the ESLint extension can use the locally-installed for validation. I've always allowed it.

Does this provide any insight into the issue?

**Comment by jtarvainen** [comment]
EDIT: the problem seems to have disappeared by itself. It may have something to do with the fact that I deleted a VS Code workspace settings file, but even that doesn't sound plausible. Anyway, all seems to be well now. Thanks for your help.

**Comment by dbaeumer** [comment]
I will close the issue then. Please ping if you have new insights.
