### ISSUE TITLE
Probe not enabling checking for ts files even though eslint is configured if using `babel-eslint` parser

### ISSUE THREAD

**Issue by dten** [microsoft/vscode-eslint#1047]
Hey, we have typescript enabled via babel. (hoping that's not cause for an immediate no).
But basically the plugin won't detect that it's configured. because it expects a very specific parser

Was hoping it could be changed such that the presence of the plugin `'@typescript-eslint'` could be counted as sufficient configuration.

My feeling is that this is similar to the detection of the vue plugin.

if you're wondering this is our eslint config minus the rules

and yes the cli gives lints, and yes forcing it on in the settings results in lints in vs code

```
const utils = require('./build/utils.js')

module.exports = {
  root: true,
  parser: 'vue-eslint-parser',
  parserOptions: {
    parser: 'babel-eslint',
    sourceType: 'module',
  },
  settings: {
    'import/resolver': {
      alias: {
        extensions: ['.js', '.vue', '.json', '.ts'],
        map: [
          ['@', utils.root('src')],
        ],
      }
    },
  },
  env: {
    browser: true,
  },
  extends: [
    'standard',
    'plugin:vue/essential',
  ],
  plugins: [
    'vue',
    'import',
    '@typescript-eslint',
  ],
  rules: {
   ...
  },
}
```

**Comment by dten** [comment]
<_< seems my config works for the normal eslint rules without that plugin though, and the config doesn't help do the ts specific rules (uh).
which i guess means that nothing about the config would tell you that ts was enabled. you'd have to check the babel config

**Comment by dbaeumer** [comment]
@dten your analysis is correct. Still can you please provide me with a GitHub repository I can clone that demos what you are experiencing. Helps setting up a repro and fixing it.

**Comment by dbaeumer** [comment]
@dten I think I have fixed this in the meantime. Are you still seeing this. If yes, can you please provide a repository I can clone that demos this? Thanks.

**Comment by maxedmands** [comment]
FWIW, I'm facing this issue too! I just set up a (really simple) repository that reproduces this problem:

https://github.com/maxedmands/vscode-eslint-bug-repro

(Note that I'm experiencing this in a repository where switching off of babel-eslint isn't an option, at least not in the near term!)

**Comment by dbaeumer** [comment]
Thanks for the repository. I will look into why probing for this fails. However if you know that everything is setup correctly you can always force the validation using

```
{
	"eslint.validate": ["typescript"]
}
```

which makes your example work.
