### ISSUE TITLE
How does vscode-eslint decide which ECMAVersion to use?

### ISSUE THREAD

**Issue by sidntrivedi012** [microsoft/vscode-eslint#1049]
Hey all 👋 ,

Was setting up ESLint using the VSCode-ESLint extention, but was amazed to see that it added ecmaVersion to `2020`. Since I don't exactly know which version my project follows. Should I put it as 2020 to get better results or 6 (ES6) so that I may be safe from new syntax? Wanted to confirm that is putting a new version like`2020` backwards compatible?

Thanks!!

**Comment by dbaeumer** [comment]
The extension is relying on the setup the comes with eslint itself. See https://eslint.org/
