### ISSUE TITLE
Plugin complains that *.d.ts not included in a project

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode-eslint#1051]
Issue Type: <b>Bug</b>

I'm adding *.d.ts files in the same directory as the corresponding *.ts files to satisfy the import statements.

The `eslint.yaml` file contains `parserOptions.project` that points to the corresponding tsconfig.json file. This file contains: `include: ["*"]` statement. But the plugin, and **not** eslint standalone, complains:
```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: client\shortcuts.d.ts.
The file must be included in at least one of the projects provided.
```
Explicitly putting `"*.d.ts"` in `include:` or in `exclude` does not change anything.

What I'm doing wrong? Or is a limitation of the plugin?
mario

Extension version: 2.1.8
VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by crystalfp** [comment]
Solved: I have to reference my *.d.ts files in "include" with `**/*.d.ts` Instead `"*"` or `"*.d.ts"` apparently do not find the file.

My question. Are these globs relative to the `tsconfig.json` file location or relative to the workspace directory?

Thanks!

**Comment by dbaeumer** [comment]
@crystalfp those are relative to the `tsconfig.json` file. In general question about the `tsconfig.json` file are better ask in the TypeScript repository.

**Comment by crystalfp** [comment]
Well, no. "include" works as specified outside the plugin, inside the plugin seems the base directory is the workplace one, not where the tsconfig file is located.

**Comment by dbaeumer** [comment]
Hmm, I think I misunderstood you then. The include inside a tsconfig should be relative to the tsconfig.
