### ISSUE TITLE
Failed to load config "./node_modules/kcd-scripts/eslint.js" to extend from.

### ISSUE THREAD

**Issue by Mossop** [microsoft/vscode-eslint#1052]
Since #974 is locked this is a re-file for the same issue that still occurs and is reproducible with the repository at https://github.com/Mossop/vscode-eslint-974.

Simply clone, `npm install` and then open the directory in VS Code and open the test.ts file there. You'll quickly see a popup notification complaining about referencing `./node_modules/kcd-scripts/eslint.js` which correctly doesn't exist as `kcd-scripts` is a dev-dependency of `@testing-library/dom` and so not installed. The ESLint CLI shows no such error.

**Comment by dbaeumer** [comment]
This works for me without problems. Here is what I see after running npm install and opening the workspace

<img width="845" alt="capture" src="https://user-images.githubusercontent.com/1931590/91299601-2d5cdc00-e7a2-11ea-89dc-4d6bd6e264de.png">

**Comment by Mossop** [comment]
Ah you're right, looks like it depends on some settings. I narrowed it down to requiring these settings:

```
{
    "eslint.validate": [
        "typescript",
    ],
    "typescript.tsserver.experimental.enableProjectDiagnostics": true,
}
```

So perhaps this is actually a bug in the TypeScript project diagnostics?

**Comment by dbaeumer** [comment]
Could be. Best would be to file an issue against VS Code then. I will close the issue. Ping if you think there is something this extension needs to do.
