### ISSUE TITLE
Nested plugins not loaded correctly

### ISSUE THREAD

**Issue by pauliunas** [microsoft/vscode-eslint#1054]
There have been various (now closed) issues regarding shared configs in monorepos and the loading of eslint plugins. The config often works with eslint when running from command line, but doesn't in the plugin because it can't load this or that eslint plugin. The usual suggestion is to use the `resolvePluginsRelativeTo` option. This works fine if all the packages in the monorepo use the same config, so you can just point it to the package that has the shared config inside `node_modules`, but it doesn't work for more complicated cases.

For example, we have an eslint plugin that exposes several custom rules and a recommended config. The recommended config uses some rules from other plugins that are real dependencies of our plugin:

```js
module.exports = {
  env: {
    "browser": true
  },
  extends: [
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:react/recommended"
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    "project": "tsconfig.json",
    "sourceType": "module"
  },
  plugins: [
    "@typescript-eslint",
    "react-hooks",
    "import",
    "prefer-arrow",
    "deprecation"
  ],
  rules: {
    ...
  }
}
```

In order for this config to work, we have to use `"resolvePluginsRelativeTo": "./node_modules/@bentley/eslint-plugin"` in `.vscode/settings.json` / `eslint.options`. However, there are some packages in the monorepo (let's call it `packageA`) that extend the config and add their own rules, sometimes from other eslint plugins:

```json
{
  "plugins": [
    "jsx-a11y",
    "@bentley"
  ],
  "extends": [
    "plugin:@bentley/recommended",
    "plugin:jsx-a11y/recommended"
  ],
  "settings": {
    "react": {
      "version": "detect"
    }
  }
}
```

In this case, the `jsx-a11y` plugin won't be loaded because `resolvePluginsRelativeTo` is set to the `@bentley/eslint-plugin` package instead of `packageA`. If we don't set `resolvePluginsRelativeTo`, it won't load the remaining plugins like `@typescript-eslint`, `react-hooks` etc.

I want to make it clear that this setup works fine when running ESLint from command line. I don't know what's different with `vscode-eslint` that it doesn't load nested plugins. The way I see it, ESLint loads plugins relative to the package that requests them, so `jsx-a11y` would be loaded relative to `packageA` while `@typescript-eslint` and others would be loaded relative to `@bentley/eslint-plugin`, because the config that requests them is in that package.

**Comment by dbaeumer** [comment]
@pauliunas without having a GitHub repository I can clone to debug this it is hard to tell. Could you please provide one?

My guess is that since you have a mono repository it might have something to do with the working directory setup.

**Comment by pauliunas** [comment]
> 
> 
> @pauliunas without having a GitHub repository I can clone to debug this it is hard to tell. Could you please provide one?
> 
> My guess is that since you have a mono repository it might have something to do with the working directory setup.

I copy/pasted the relevant parts into this repository I had created for a previous issue. That reproduces the problem for me.
https://github.com/pauliunas/rush-example

**Comment by pauliunas** [comment]
@dbaeumer any luck debugging this issue?

**Comment by dbaeumer** [comment]
@pauliunas how is this different from https://github.com/microsoft/vscode-eslint/issues/1040. I am a little reluctant to look into considering all the tricks the rush tooling does to make ESLint work.

**Comment by dbaeumer** [comment]
I cloned the repository and ran rush and they still patch the eslint command and patch in a custom `NODE_PATH` which very likely makes loading the typescript plugin work. 

Any additional insights why this is different than #1040.

**Comment by pauliunas** [comment]
First of all, in the previous one, the config was hosted as part of a regular npm package. I was expecting that switching to an actual eslint plugin with shared configs would make it work better, as that workflow is more "standard".

But more importantly, I found a use case in which the `resolvePluginsRelativeTo` workaround doesn't work: as outlined in the top comment, adding additional eslint plugins to a package means you just can't get the plugin to work no matter what. I just realized I forgot to include that in the example monorepo, but if you try to add a new eslint plugin to (for example) apps/my-app and use its rules, it just won't work, with `resolvePluginsRelativeTo` or without it.

**Comment by dbaeumer** [comment]
The `--resolve-plugins-relative-to` option can only specify one directory. However the `NODE_PATH` env which rush patches into the ESLint command can provide n path which very likely makes this work since it gives you n relative paths.

I think to track this down we need someone from the community with rush expertise. 

Have you every tried to use the `eslint.nodePath` setting with the same value?

**Comment by pauliunas** [comment]
Interesting, I can't reproduce it anymore in the example repo. I'm guessing it might have been something wrong with my environment setup. On a clean monorepo, setting `resolvePluginsRelativeTo` to the internal eslint plugin now loads plugins both from the target package and from the internal plugin.

I've since moved all our rules into modular/optional configs in our internal plugin as a workaround, so the issue doesn't persist. I'll see if I can catch the error again and report back. Maybe `eslint.nodePath` will help in some way. Does it accept relative paths? We will probably want to have it set to the package root as well as the plugin in `node_modules`.

I'm closing this issue for now, until I can get the error to pop up again. Thank you for your patience 👍

**Comment by dbaeumer** [comment]
If you have a repro please ping me in this issue. We can then reopen.
