### ISSUE TITLE
Casing of [import] does not match the underlying filesystem.

### ISSUE THREAD

**Issue by snowManF** [microsoft/vscode-eslint#1056]
hello

 I‘m getting false positive with the plugin on the rule "import/no-unresolved" in Visual Studio Code.
Casing of [import] does not match the underlying filesystem.

But  run eslint , I don't got this error.

i don‘t know how to fix this problem, if anyone knows please help me，Thanks a bundle!

**Comment by dbaeumer** [comment]
Are you sure that error comes from ESLint and not the TypeScript compiler. I know that they have a corresponding setting. If it comes from ESLint then can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
