### ISSUE TITLE
eslint-plugin-sort-class-members sorting class members

### ISSUE THREAD

**Issue by Daaron3** [microsoft/vscode-eslint#1062]
Eslint: 6.8.0
eslint-plugin-sort-class-members: 1.8.0
Vscode Eslint Plugin: 2.1.8
Vscode: 1.48.2
OS: Windows_NT x64

Hello, I use plugin for eslint sort-class-members https://github.com/bryanrsmith/eslint-plugin-sort-class-members that sorts class members by groups and then sorts members alphabeticaly in this groups. 

The plugin works perfectly in the console and sorts members alphabeticaly right. In IntelliJ works plugin the same but in Vscode works sorting differently. 

**I have two propertries:** 

```
public chapter = 10;
public crap = true;
```

**Error message is:** 

`Expected property crap to come before property chapter.eslint(sort-class-members/sort-class-members)`

I think because vscode eslint plugin execept that _"ch"_ is one character therefore _"c"_ must be before _"ch"_.

**Expected behaviour:** 

_chapter_ must be before _crap_ because _"h"_ is before _"r"_.

**Comment by dbaeumer** [comment]
The VS Code ESLint extension doesn't do the sorting. It forwards to the eslint and the plugin. Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
