### ISSUE TITLE
Dynamic comment prefix based on file type?

### ISSUE THREAD

**Issue by dotansimha** [microsoft/vscode-eslint#1064]
As I can see in the code here:
https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1666-L1680

The actions for disabling are always using `//` or `/*`, but in some cases, like with files of type `.yaml`, a `#` needs to be used instead of `//`. 

What do you think? Is that a valid use case? If so, I can open a PR ;)

**Comment by dbaeumer** [comment]
Actually that does make sense and someone already started to look into this for Coffeescript. So may be you can simply extend the PR https://github.com/microsoft/vscode-eslint/pull/857/files
