### ISSUE TITLE
Proposal for supporting Diagnostic.code in object form

### ISSUE THREAD

**Issue by rchl** [microsoft/vscode-eslint#1065]
As discussed in https://github.com/microsoft/vscode-eslint/issues/992, the `Diagnostic.code` will also allow an object form in the next version of the spec. Yet when I look at https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/ it's still not included there.

Can this be clarified? Is it on track to make it and where it's being proposed?

**Comment by dbaeumer** [comment]
The reason for this is that we had internal discussion about a different approach. But I do agree this needs to be documented. I will follow up on this.

**Comment by rchl** [comment]
I think I've meant to file this in the LSP repository so feel free to move if possible.

**Comment by dbaeumer** [comment]
The LSP issue is: https://github.com/microsoft/vscode-languageserver-node/issues/601

**Comment by dbaeumer** [comment]
I will close the issue.
