### ISSUE TITLE
Support to customize eslint location for lint task

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode-eslint#1066]
According to the Readme:

> If you want to lint the whole workspace set eslint.lintTask.enable to true and the extension will also contribute the eslint: lint whole folder task. 

I enabled that setting, but if I press Ctrl-Shift-P and type `whole folder` it doesn't find anything. I'm using VSCode 1.48.2 with the ESLint plugin version 2.1.8.

**Comment by Timmmm** [comment]
Ah, it's a "Task" not a "Command". You might want to explain in the Readme how to activate it since it isn't obvious!

**Comment by Timmmm** [comment]
Although... it still doesn't work:

```
zsh:1: command not found: eslint
The terminal process "/bin/zsh '-c', 'eslint .'" failed to launch (exit code: 127).
```

I don't have `eslint` in my `PATH`, (it's in `node_modules`). This extension can find it in normal operation. I guess you need to use the "find eslint" logic for this task too.

**Comment by dbaeumer** [comment]
Where do you have eslint installed. The best I think would be to provide a setting since it might be difficult to handle all locations correctly.

**Comment by Timmmm** [comment]
It is in a parent directory's `node_modules`, i.e. `../node_modules/.bin/eslint`.

I don't understand how it works already though - or does the extension bundle its own copy of ESLint?

**Comment by dbaeumer** [comment]
No, the extension doesn't bundle its own copy of eslint

**Comment by Timmmm** [comment]
Ah so I looked into the code and when running normally, it [calls](https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L737) VSCode's [`Files.resolve()`](https://github.com/microsoft/vscode-languageserver-node/blob/d2a3322666101a3c246369f4098d430adc18f2d5/server/src/node/files.ts#L41) function which returns `/Users/me/myproject/node_modules/eslint/lib/api.js`.

So it's using eslint through its API rather than calling the command line. Honestly I feel like this is a better approach - I don't really want the extension to provide an ESLint task (I can add that myself really easily). I want it to provide a *command* that runs ESLint via `api.js` on all the files, and then puts all of the results in the "Problems" output.

That has the added benefit of being able to click on the problems to go to them (you can't do that with the standard ESLint command line output).

A fair bit more work but it would be much more useful.

**Comment by dbaeumer** [comment]
For all the details around this please see https://github.com/microsoft/vscode-eslint/issues/91. Any objection to dup it.

**Comment by Timmmm** [comment]
Yeah seems reasonable. I don't think supporting a custom location for the task is that useful given that I can easily just write my own task to run eslint.
