### ISSUE TITLE
Different formatting on each file save

### ISSUE THREAD

**Issue by JekRock** [microsoft/vscode-eslint#1069]
When using the vscode-eslint and eslint-plugin-prettier on each file save the formatting result will be different.
#### package.json
```json
{
  "name": "prettier-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-eslint": "^10.1.0"
  },
  "devDependencies": {
    "eslint": "^7.2.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-prettier": "^3.1.4",
    "prettier": "2.1.1"
  }
}

```
#### .eslintrc.json
```json
{
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 2018
    },
    "extends": [
        "airbnb-base",
        "prettier",
        "plugin:prettier/recommended"
    ],
    "rules": {
        "semi": "error",
        "space-before-function-paren": [
            "error",
            "always"
        ]
    },
    "plugins": [
        "prettier"
    ]
}
```
#### VSCode settings.json
```json
{
    "eslint.alwaysShowStatus": true,
    "eslint.lintTask.enable": true,
    "eslint.validate": [
        "javascript"
    ],
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    }
}
```

#### index.js
```javascript
function someFunction() {}

function anotherFunction () {}

```
### Steps to reproduce

1. Install the vscode-eslint extension
2. Open the project with all setting specified above
3. Call npm i
4. Change anything in the index.js (for example, add a new line at the end of the file)
5. Save the index.js file
6. After saving the index.js file the "someFunction" function will get a space between its brackets and the function name, and the space after the "anotherFunction" will be removed.
7. Repeat the 4th and 5th steps.
8. Now the formatting is the opposite to the 6th step (the same as it was before executing any steps).

When the eslint is started from the command line, the issue is not reproducible.

**Comment by dbaeumer** [comment]
Which formatter do you have configured in VS Code. From how this looks it is not ESLint. Might be TS which would explain this.

And can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by JekRock** [comment]
@dbaeumer please find the repository with instructions [here](https://github.com/JekRock/vscode-eslint-formatting)

**Comment by dbaeumer** [comment]
This is due to your configuration. The default prettier config recommends no space and you ask for a space. Since ESLint (the npm module) computes these fixes in a loop the once either complains about the other or vice versa. I had some code that always force a re-computation but that had negative performance impacts so I took it out for code action on save.

I suggest that you make the configuration the same for prettier and eslint.

**Comment by JekRock** [comment]
@dbaeumer thanks for your answer.
That behaviour of the plugin still looks strange to me. I thout that eslint and prettier apply changes sequentially so the result for the provided example will be file formatted by either eslint or by prettier. But it contains the result of both formatters in the same file (and they switch on each save).
Shouldn't the result of the formatting be consistent?

**Comment by dbaeumer** [comment]
See this 

> I had some code that always force a re-computation but that had negative performance impacts so I took it out for code action on save.

What I basically do is I remember the fixes from the reported problems to speed up the save. If I have overlaps I drop the overlaps. So the fix for you would be to give you a setting to always force the re-computation. But as said that makes things slow. This is why I recommend to use the same configuration for both prettier and eslint.

**Comment by JekRock** [comment]
I got your point.
Thanks for the answer!

**Comment by dbaeumer** [comment]
Closing the issue then. Thanks for your understanding.
