### ISSUE TITLE
[feature request] Warnings not display but still formated on save

### ISSUE THREAD

**Issue by BjMrq** [microsoft/vscode-eslint#1070]
Hello, 
I Was wondering if it is possible (or could be made possible) to have a configuration option as such:
- eslint rules with a "warn" level would be not displayed in the ide to avoid visual "pollution" but still formatted on saving

use case:
- Set up some rules like indentation and spacing on warn level
- writing a bunch off code, not taking care of indentation and spacings 
- I don't get "bothered" by warnings along the way 
- when I save it is still taking care of

something like eslint.quiet but that would still apply formating

(maybe it exist and I missed it)
Thanks !

**Comment by BjMrq** [comment]
Or a 

eslint.displayRuleLevel

and you can choose the level off the rules you want displayed

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode-eslint/pull/993

**Comment by BjMrq** [comment]
Hello, thanks your response.
I am not sure how it is a duplicate.
It will allow to override rules, but will be able to not display some in the IDE but still fix them on save?

**Comment by dbaeumer** [comment]
Yes, that was the request and the started implemention in the PR.
