### ISSUE TITLE
VS Code:  Couldn't start client ESLint 

### ISSUE THREAD

**Issue by Bow2Jesus** [microsoft/vscode-eslint#1071]
The ESLint extension quit working in VS Code when I closed and reopened VS Code.  It still works fine when ran from the command line.  It produces the following output when the extension is invoked by VS Code:

[Info  - 9:37:15 AM] ESLint server stopped.
[Info  - 9:37:16 AM] ESLint server stopped.
[Error - 9:37:16 AM] Starting client failed
Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:549:9)
	at c:\Users\i338909\.vscode\extensions\dbaeumer.vscode-eslint-2.1.8\client\out\extension.js:1:120106

I have tried numerous things including completely uninstalling and reinstalling everything related to the ESLint extension.

**Comment by dbaeumer** [comment]
Actually no idea. The client can't spawn the server process. Any specific security settings on your machine. And is there anything in the console (Help > Toggle Developer Tools).
