### ISSUE TITLE
Creating a Global Config Package

### ISSUE THREAD

**Issue by karlhorky** [microsoft/vscode-eslint#1073]
Hi there!

First of all, thanks for all of your work on this, ESLint is great, especially for beginners learning what is correct and what isn't.

Similar to @cyberbiont's query from #976, I'm trying to create a global ESLint config for all projects that will get replaced by a local configuration file + local ESLint install, if it exists.

The reason I want this is so that I as a teacher and also all of the students of @upleveled can get feedback on potential issues with JavaScript code in a new project (sometimes small 20-minute demo projects with just an index.js file) without having to set up a bunch of packages and creating ESLint configuration in the project.

I have a first version working here, although I'm not sure if this is a good approach:

https://github.com/upleveled/upleveled-vscode-eslint-base-config

I accomplish this by depending on [`react-scripts`](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts) (from [`create-react-app`](https://github.com/facebook/create-react-app)), which provides an installation of `eslint` and also some base configuration.

Currently I'm using `eslint.nodePath`, `eslint.options.configFile` and `eslint.options.resolvePluginsRelativeTo`:

```json
{
  "eslint.nodePath": "/Users/karl/projects/upleveled-vscode-eslint-base-config/node_modules",
  "eslint.options": {
    "configFile": "/Users/karl/projects/upleveled-vscode-eslint-base-config/.eslintrc.js",
    "resolvePluginsRelativeTo": "/Users/karl/projects/upleveled-vscode-eslint-base-config/node_modules"
  }
}
```

I searched around through the issues in this repo a lot, but I couldn't find a concrete set of guidelines or tips as to how best create this "global ESLint configuration" for all projects.

@dbaeumer or anyone else who knows, would you be able to point me in the right direction as to:

1. Is this is a good approach?
2. Are there pitfalls with this approach?
3. Can this be improved in any way? Also open to completely different solutions :)

**Comment by dbaeumer** [comment]
@karlhorky actually I think this is not a good approach. Tweaking nodePath, configFile and plugin resolving are expert level knobs and I am pretty sure such tweaks will cause problems if you later on add additional ESLint plugins. 

ESLint (the npm module) support default configuration stored in an npm module. See https://eslint.org/docs/user-guide/configuring#using-a-shareable-configuration-package

Have you thought about going down that path?

**Comment by karlhorky** [comment]
> Tweaking nodePath, configFile and plugin resolving are expert level knobs and I am pretty sure such tweaks will cause problems if you later on add additional ESLint plugins.

Right yeah, I would like to avoid this if possible too.

> ESLint (the npm module) support default configuration stored in an npm module

> Have you thought about going down that path?

Right yeah I would like to use a shared configuration if that would be possible without installing any libraries in a project. As per in the original description, one of the main motivations is this:

> The reason I want this is so that I as a teacher and also all of the students of @upleveled can get feedback on potential issues with JavaScript code in a new project (sometimes small 20-minute demo projects with just an index.js file) without having to set up a bunch of packages and creating ESLint configuration in the project.

So the workflow looks like this:

1. Create a throwaway demo project folder with only an index.js inside
2. Show some concept or feature in Node.js or browser code
3. While this is happening, VS Code ESLint is providing a default set of feedback (eg. `no-unused-vars`), based on this global configuration

As far as I know, creating a shared configuration would add a lot of steps to that (having to install ESLint and the package), making it unviable for quick demo / prototype projects.

What I would like is some default global configuration + ESLint binary that is used, but ONLY if the project itself doesn't have a configuration set up.

Some additional keywords, in case anyone is searching for this: built-in, fallback

**Comment by dbaeumer** [comment]
In this case I would opt that you use yeoman generator. All a student has to do is to type yo myexample and you can generate everything. The generator even runs npm install.

**Comment by karlhorky** [comment]
Scaffolding and generating tools can be useful to save typing, but we do not want to have tooling installed in all of our super small demos.

The idea is: when a code editor is opened with a new `index.js` in an empty folder, it should have some default best practices linting provided without having to install anything.

Does this go against the ideals of this project? It seems that there is some reluctance to support this use case - is it technically complex to do so?

**Comment by dbaeumer** [comment]
All I can say is that your current approach will sooner or later cause problems. If you look how ESLint is normally used things are installed locally into your workspace.

Another idea would be to have a VS Code extension that does this. You could even bundle extensions into a feature pack.

I will close the issue since there is no intention in the ESLint extension itself to support this. We can still discuss solution in this issue.

**Comment by karlhorky** [comment]
Ok, thanks for the feedback.

Maybe the best "correct" way of doing it would be another VS Code extension, with built-in binaries for ESLint.

Could you quickly expound on your comment below as to what types of problems configuring `eslint.nodePath`, `eslint.options.configFile` and `eslint.options.resolvePluginsRelativeTo` can cause?

> I am pretty sure such tweaks will cause problems if you later on add additional ESLint plugins

**Comment by dbaeumer** [comment]
`eslint.nodePath` change the way how node looks for modules. This might not work with all plugins available for ESlint. Same for `resolvePluginsRelativeTo`

**Comment by karlhorky** [comment]
Alright, I'll keep that in mind.

I suppose I won't get around to creating a new VS Code extension any time soon, so instead I've reverted to setting up a "shared config" and requiring that it be installed in each project.

It's unfortunate for smaller projects that shouldn't have any dependencies, but I guess that's the state of the art for tooling right now.

**Comment by lqzhgood** [comment]
I think providing a default (global) configuration would be very helpful for writing small scripts in daily life.

**Comment by gjfLeo** [comment]
Hi there! Is any solution on this now? 🥹
