### ISSUE TITLE
cannot lint with @typescript-eslint/parser on remote under ~/

### ISSUE THREAD

**Issue by yxzh614** [microsoft/vscode-eslint#1075]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/25242391/93870106-4ef8a700-fcff-11ea-9576-608c9d58d1a4.png)

Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: ../../../../../home/yuexianzhe/repos/trident/src/ad/business/basic-plan-info/components/stock-table/BusinessInfo.tsx.
The file must be included in at least one of the projects provided.

![image](https://user-images.githubusercontent.com/25242391/93869476-6b481400-fcfe-11ea-80c9-fc241440309a.png)

im using ssh remote,the first option in the picture won't cause this but the second will

Extension version: 2.1.8
VS Code version: Code - Insiders 1.50.0-insider (9e505675670d65138405321a60b0df4ddec28799, 2020-09-16T05:43:58.570Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.14.81.bm.15-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|-psn_0_24266531 --crash-reporter-id e54118f2-0119-49c1-9d21-4322321ba39a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.227.12.168|
|OS|Linux x64 4.14.81.bm.15-amd64|
|CPUs|Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|15.42GB (1.96GB free)|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@yxzh614  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by tbuschto** [comment]
I have the same issue under Windows using WSL/Ubuntu, VSC 1.49.1, extension v2.1.8. It works fine using the eslint cli AND it works when starting VS Code without WSL. It also works if I create a tsconfig.json dedicated to eslint at the project root instead of separate tsconfig.json files for my different sub-projects.

**Comment by yxzh614** [comment]
hello @dbaeumer , here it is https://github.com/yxzh614/eslint-demo 
clone it on devbox, use vscode remote to open it, and npm install and then eslint will ask if allow to use local eslint, allow it and the error will show in src/index.tsx
![image](https://user-images.githubusercontent.com/25242391/94108667-4aa0cb00-fe72-11ea-8f20-ffa7bc731503.png)

is there something wrong with eslintrc or tsconfig?

**Comment by sploders101** [comment]
I just found this issue diagnosing a similar problem. VSCode ESLint was validating vue files (as well as the typescript within them), but not the typescript files themselves. Adding this to my settings fixed the problem:

```
{
	"eslint.validate": [
		"typescript",
	]
}
```

However, typescript is still listed under `eslint.probe`, so it may be an issue with probing for language support.
![Screenshot_20200924_145832](https://user-images.githubusercontent.com/26530958/94199672-6c03b600-fe76-11ea-92df-716a1227ceef.png)

**Comment by dbaeumer** [comment]
Here is what I get when cloning it: 

<img width="658" alt="capture" src="https://user-images.githubusercontent.com/1931590/94249303-fc4a0580-ff1f-11ea-90d1-8172a66e5237.png">

It even works without problems using GitHub Codespaces. Any additional info?

<img width="819" alt="capture" src="https://user-images.githubusercontent.com/1931590/94249827-b93c6200-ff20-11ea-9ff1-bf16ae024dd9.png">

**Comment by sploders101** [comment]
It looks like @yxzh614 forgot to include the main piece of the issue in the reproduction. It only seems to happen (at least for me) when using the extension *through* a remote session. GitHub workspaces (to my knowledge) works differently, in that it sends the *UI* to you, where VSCode Remote extensions essentially split the program in half, and do a lot of processing locally still, while proxying filesystem requests, etc through the remote session. If you'd like, I can provide a fork of the repro with a devcontainer config when I get time.

**Comment by yxzh614** [comment]
@sploders101 you are right it only happen on vscode remote

![image](https://user-images.githubusercontent.com/25242391/94354903-1ddaf680-00b2-11eb-8304-2a3e2844a0f2.png)

This is output of eslint when I open my dir by /data00/home/yuexianzhe/repos/trident

![image](https://user-images.githubusercontent.com/25242391/94354925-44009680-00b2-11eb-94c1-a582e16bcc42.png)

This is output of eslint when I open my dir by ~/repos/trident

**Comment by yxzh614** [comment]
trying to debug
```
{
    "code": "import React from 'react'; // errors here\n\nconst c = 1; // no eslint unused var errors\n\nexport const App: React.FC = () => (\n    <div>app</div>\n);\n",
    "comment": true,
    "comments": [],
    "createDefaultProgram": false,
    "debugLevel": {},
    "errorOnTypeScriptSyntacticAndSemanticIssues": false,
    "errorOnUnknownASTType": false,
    "extraFileExtensions": [],
    "filePath": "/home/yuexianzhe/repos/eslint-fail-demo/src/index.tsx",
    "jsx": true,
    "loc": true,
    "preserveNodeMaps": true,
    "projects": [
        "./tsconfig.json"
    ],
    "range": true,
    "strict": false,
    "tokens": [],
    "tsconfigRootDir": "/data00/home/yuexianzhe/repos/eslint-fail-demo",
    "useJSXTextNode": true
}
```

**Comment by dbaeumer** [comment]
> GitHub workspaces (to my knowledge) works differently, in that it sends the UI to you, where VSCode Remote extensions essentially split the program in half, and do a lot of processing locally still, while proxying filesystem requests, etc through the remote session. 

This is not correct. From a Remote perspective GitHub code spaces works the same as VS Code remote with docker containers. The difference is that the UI is run in the Web browser instead of Electron. 

I also tested the problem locally using a remote session (see first screen short in https://github.com/microsoft/vscode-eslint/issues/1075#issuecomment-698821622). To understand why this is not working I would need more information. Especially which kind of remote setup you are using and whether eslint works correctly in the terminal in that remote setup.
