### ISSUE TITLE
ESLint allow message wording

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-eslint#1076]
Current wording:

The ESLint extension will use 'node_modules/eslint' for validation, which is installed locally in 'Node'. If you trust this version of ESLint including all plugins and configuration files it will load, press 'Allow', otherwise press 'Do Not Allow'. Press 'Always Allow' if you trust all local installed ESLint versions in any folder or 'Cancel' to disable ESLINT for this session.

What I propose:

The ESLint extension will use 'node_modules/eslint' for validation, which is installed locally in 'Node'. Do you trust this version of ESLint including all plugins and configuration files it will load?
 
Checkbox: "Remember my choice for all workspaces" by default checked off. Instead of "workspaces" we can say "folders"
Two Buttons: `Trust`    `Do Not Trust`

Pressing enter is Trust, `esc` is Do Not Trust

<img width="380" alt="Screenshot 2020-09-22 at 14 09 19" src="https://user-images.githubusercontent.com/1926584/93887809-73488980-fce7-11ea-8aef-1bade9a75362.png">

**Comment by dbaeumer** [comment]
@isidorn thanks. Good improvement. 

@isidorn & @bpasero : do you know how to add a checkbox to a messag dialog triggered via our API

**Comment by bpasero** [comment]
@dbaeumer I am not the original author of the API but looking at it it seems we do not allow you to have a checkbox, mainly because it seems both notification and dialog share the same API and in notifications we do not allow a checkbox either. Best you can do is have a "Always Allow" button, and not a checkbox.

**Comment by dbaeumer** [comment]
@bpasero Thanks!

**Comment by isidorn** [comment]
Oh sucks. I was not aware we do not support the checkbox from extension API.
Then my suggestion is getting worse... You would have to have three buttons
"Trust Always" "Trust for This Folder" "Do Not Trust"

**Comment by dbaeumer** [comment]
@bpasero next question :-) How do I add a line break in an information message shown in the notification center ?

**Comment by bpasero** [comment]
@dbaeumer also not possible sorry. We wanted to prevent extensions spamming the user with lots of text. That is really not the intention of the API, so formatting is limited to just text and links within.

**Comment by bpasero** [comment]
Btw I think a modal dialog is good for this and I am not opposed to having new API to make this work nicely if something is missing (e.g. like checkbox support). 

I am not in the loop of the discussion about UX, but what is the final result going to be?

**Comment by dbaeumer** [comment]
Will demo something today in the standup.

**Comment by dbaeumer** [comment]
@isidorn I changed the wording and buttons to get it more alligned with the key chain dialog. I also try to avoid the word `trust` but talk about executing code on you behave. This is what I actually do :-)

<img width="429" alt="capture" src="https://user-images.githubusercontent.com/1931590/94246119-9e1b2380-ff1b-11ea-87e6-93648e707da0.png">

Please ping if you disagree with this.

**Comment by isidorn** [comment]
Looks good. The empty line gave it more clarity and the wording is clearer now. Good job :)
