### ISSUE TITLE
Feature: "fix all problems" on save 

### ISSUE THREAD

**Issue by JonathanWolfe** [Microsoft/vscode-eslint#108]
I'd be very nice if the plugin came with an option to run the "fix all problems" after saving like is done in other editors. 

If I get some time at work, I can look into adding this. But I wanted to submit this issue as well in case the vscode team wanted to handle it.

**Comment by gertcuykens** [comment]
Also do fix all problems on 
![image](https://cloud.githubusercontent.com/assets/863731/17459546/cb18f262-5c3c-11e6-8dc4-754f41065d2e.png)
Thanks

**Comment by flesler** [comment]
:+1:

**Comment by dbaeumer** [comment]
The VS Code 1.6 release will have API to particiapte in save. When this is in and available I will adapt it.

**Comment by dbaeumer** [comment]
I adopted the API and release a new version of the extension. Please note that auto fix on save only works for manual save or for save on focus lost. This is consistent with format on save in VS Code.
