### ISSUE TITLE
option to disable rule in .eslintrc.js 

### ISSUE THREAD

**Issue by hacknlove** [microsoft/vscode-eslint#1081]
regarding disabling eslint rules you offer:

* disable ___ for this line
* disable ___ for the entire file

I would love to also have

* disable __ in .eslintrc.js 

Thank you.

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
