### ISSUE TITLE
Is the extension using eslint library for the eslint.format.enable?

### ISSUE THREAD

**Issue by josh-hemphill** [microsoft/vscode-eslint#1082]
I'm tying to implement using only Eslint for both linting and formatting in another extension for Vue SFC files but I couldn't find anything in the eslint docs about using its library for applying the formatting.
When looking through the codebase, it looked like it was using vscode functions, but I couldn't follow exactly what it was doing.
Could someone point me in the right direction?

**Comment by dbaeumer** [comment]
Two things you need to do:
- enable that the extension hooks up the formatter using `eslint.format.enable` setting
- if you have more than one formatter you need to let VS Code know which one to use using the `editor.defaultFormatter` setting.

**Comment by dbaeumer** [comment]
The corresponding code is here: https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1997
