### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rony1987** [microsoft/vscode-eslint#1083]
- Issue Type: `Bug`
- Extension Name: `vscode-eslint`
- Extension Version: `2.1.8`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by dbaeumer** [comment]
@rony1987 without the needed data from the clipboard there is little I can do. When you see that the next time please don't forget to paste the data from the clipboard into the issue. 

Thanks!
