### ISSUE TITLE
Run onSave vs onType setting is broken

### ISSUE THREAD

**Issue by indignant** [microsoft/vscode-eslint#1085]
Hey there!

There's a setting for deciding when to run eslint: either on save or on type.

```
Eslint: Run
Run the linter on save (onSave) or on type (onType)
```

I have it set to `onSave` because I find it distracting otherwise, but unfortunately the linting still happens as I type.

ESLint Plugin: v2.1.8
VSCode: 1.49.2
OS: Catalina 10.15.4

Not really sure what other information I could provide, except that disabling the plugin prevents linting; of course I'd still like to lint - just when I save.

**Comment by dbaeumer** [comment]
This works for me: 

![cast](https://user-images.githubusercontent.com/1931590/95554830-22d46a00-0a11-11eb-8218-c7724b367b68.gif)

Can you make sure you upgrade to the lastest both VS Code (1.50.0) itself and the ESLint (2.1.10) extension 

If you still see that please provider me with a GitHub repository I can clone that demos this.

**Comment by antonbobrov** [comment]
I have a similar problem. I enabled formatting on save. Today, after the update, it works wrong. Before the update my code was formatted according to my eslint rules, now it isn't. Although, when I try to "fix all auto-fixable problems", it works fine.
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/11936437/95577516-f59cb180-0a3a-11eb-96fe-eb9d23b14af7.gif)

**Comment by dbaeumer** [comment]
@antonbobrov how do you enable format on save. Via code actions or via format?

**Comment by dbaeumer** [comment]
@antonbobrov you might be more interested in https://github.com/microsoft/vscode-eslint/issues/1086

**Comment by antonbobrov** [comment]
> @antonbobrov how do you enable format on save. Via code actions or via format?

Via format. I've also tried 
`"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
}` and it works. Thank you for the idea. Though, still don't know what's wrong with the "format".

**Comment by dbaeumer** [comment]
@antonbobrov can you provide me with a repository I can clone that demos the broken format behaviour. As you can see in #1086 format on save works for me.
