### ISSUE TITLE
v2.1.10 - Extension 'ESlint' cannot be a formatter

### ISSUE THREAD

**Issue by chunsenye** [microsoft/vscode-eslint#1090]
In older versions, the formatter works
![image](https://user-images.githubusercontent.com/30768615/95832349-bd63de80-0d6c-11eb-8b6b-80bb4ea4ea7a.png)
when I update to v2.1.10 it doesn't work
![image](https://user-images.githubusercontent.com/30768615/95832522-f13f0400-0d6c-11eb-9bc2-aab91e5d34e0.png)
I had add the option
![image](https://user-images.githubusercontent.com/30768615/95832677-34997280-0d6d-11eb-8b83-9a470c99316f.png)

**Comment by code-for-coffee** [comment]
@chunsenye check out #1086 for a potential fix.

**Comment by dbaeumer** [comment]
Dups #1086
