### ISSUE TITLE
Set node_modules path

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/vscode-eslint#1091]
I'm using ESLint for VS Code with a project that its `node_modules` directory path is not in the root of the working dir.
I tried to configure the settings: `"eslint.nodePath": "./src/node_modules"` but I still get an error:

> Failed to load plugin 'react' declared in 'src\.eslintrc.json': Cannot find module 'eslint-plugin-react'
> Require stack:
> -<project_path>\\\_\_placeholder\_\_.js
> Happened while validating <scanned_file>
> This can happen for a couple of reasons:
> 1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
> 2. If ESLint is installed globally, then make sure 'eslint-plugin-react' is installed globally as well.
> 3. If ESLint is installed locally, then 'eslint-plugin-react' isn't installed correctly.

The eslint-plugin-react is installed locally in the `src/node_modules` path.

Note I am able to run the eslint manually from the terminal (when the working dir is `src`).

Any idea how to tell the plugin where are the node modules?

**Comment by dbaeumer** [comment]
@hraz-msft the `eslint.workingDirectories` setting will very likely be your friend (see https://github.com/microsoft/vscode-eslint/blob/master/README.md). Set it to the src directory as well.

**Comment by hraz-msft** [comment]
Thanks @dbaeumer , I have changed VSCode settings to this configuration now:
```
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "editor.formatOnSave": true,
  "eslint.alwaysShowStatus": true,
  "eslint.workingDirectories": ["/src"],
```

And my `src` folder contains the `.eslintrc.json` and `node_modules`.

But I still get this error:
> Failed to load plugin 'react' declared in 'src\\.eslintrc.json': Cannot find module 'eslint-plugin-react'
> Require stack:
> -<project_path>\\\_\_placeholder\_\_.js
> Happened while validating <scanned_file>
> This can happen for a couple of reasons:
> 1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
> 2. If ESLint is installed globally, then make sure 'eslint-plugin-react' is installed globally as well.
> 3. If ESLint is installed locally, then 'eslint-plugin-react' isn't installed correctly.

It seems that it finds the `.eslintrc.json` (as before) but not finding the `node_modules`. And everything works fine with manual command: `node_modules\.bin\eslint.cmd <path>` under `src` folder.

**Comment by dbaeumer** [comment]
@hraz-msft can you provide me with a GitHub repository I can clone that demos this?

**Comment by hraz-msft** [comment]
I can't share the original code yet, so I created a repro repo: https://github.com/hraz-msft/ESLintTest

The root directory is the directory that I open with VSCode (cannot be changed since in our real project we have more parts). `src` contains basic React project with custom ESLint config.

**Note that in this sample there are two `src` directories - one in the root directory and one under `src/src`. When I say `src` I mean the one in the `root` directory**

In the `.eslintrc.json` I have an example rule of `intent: ["error", 4"]` while `App.tsx` has intent of 2 spaces.

ESLint inside VSCode cannot show the error and cannot fix it on save and throws this error in the log console:
![image](https://user-images.githubusercontent.com/66222191/96425036-3a2b0880-1204-11eb-84cc-9a187a0b8645.png)

While is in the `node_modules` directory (under `src`)
![image](https://user-images.githubusercontent.com/66222191/96425123-562eaa00-1204-11eb-8d0f-0bbd4bd01f3d.png)

**Comment by dbaeumer** [comment]
The working directory setting you specified is an absolute path (e.g. starts with a `/`). Using `./src` makes it work as expected.

I will close the issue. Please ping if this will not make it work for you.

**Comment by dbaeumer** [comment]
<img width="436" alt="capture" src="https://user-images.githubusercontent.com/1931590/96458596-63a65d00-1221-11eb-88f5-776a3e40bf92.png">

**Comment by hraz-msft** [comment]
Ahh, one tiny character made all the difference... It is working. Thank you very much!
