### ISSUE TITLE
ESLint conflicts with Prettier after VSCode update

### ISSUE THREAD

**Issue by Darkzarich** [microsoft/vscode-eslint#1093]
### Summary

After VSCode got updated to version 1.50.1 ESLint started to conflict with Prettier . There is `.eslintrc.js` in my project folder and it states that I prefer using **single quotes** but from the log output of Prettier I see `singleQuote": false`, it puts **double quotes** everywhere and it's not the only rule that gets ignored. I believe there is some conflict happening that wasn't here before the update: when I press save all single quotes become double quotes but if I press save again for a split second quotes turn into single quotes and then double quotes again

![gif](https://media.discordapp.net/attachments/431043579016904705/767909119029805116/vscodegif.gif)

Everything was working fine before the update so there shouldn't be any problem with configs I think... I'm not exactly sure what got changed so now it's broken and isn't working as was before

### Additional information

**VS Code Version**:  1.50.1

**ESLint Extension Version**: v2.1.13

**OS and version**: Windows 10

**Comment by dbaeumer** [comment]
@Darkzarich can you provide me with a workspace that shows this?

**Comment by Darkzarich** [comment]
@dbaeumer thank you, I've solved this issue just now: apparently I somehow turned on vscode settings `editor. formatOnSave` and it was conflicting with a similar line from ESLint config. Now everything is alright!

**Comment by dbaeumer** [comment]
OK. Great. Closing the issue then.
