### ISSUE TITLE
Relative path for "eslint.runtime" appears to cause ES Lint not to load.

### ISSUE THREAD

**Issue by stefan505** [microsoft/vscode-eslint#1094]
Within `.vscode/settings.json` we specify the following:

```
	"eslint.nodePath": "./platform/node_modules",
	"eslint.runtime": "./platform/node/node.exe",
```

This was working fine, but with the combination of VS Code v1.50.1 and vscode-eslint v2.1.13 this has stopped working.

Log (Window) output:

```
[2020-10-22 15:11:07.849] [renderer1] [error] spawn ./platform/node/node.exe ENOENT: Error: spawn ./platform/node/node.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[2020-10-22 15:11:08.822] [renderer1] [error] Launching server using runtime ./platform/node/node.exe failed.
```

ESLint output:

```
[Info  - 15:11:07] ESLint server is starting
[Info  - 15:11:07] ESLint server stopped.
[Error - 15:11:07] Starting client failed
Launching server using runtime ./platform/node/node.exe failed.
```

Possible regression?

**Comment by stefan505** [comment]
Noticed now that making the paths absolute paths prevents the error from happening, so it must be something related to relative paths we use (and require).

**Comment by dbaeumer** [comment]
@stefan505 the reason for this is a security fix of VS Code itself which will not start the extension host on the workspace folder anymore. But this happened a long time ago and I tested 1.48.0 and it shows the same behavior. I might be able to fix it for some cases but it will not work in a multi workspace folder setup or in a single file validate.

**Comment by dbaeumer** [comment]
I looked into it and I can mitigate this in a single folder setup. But the fix needs to go into the LSP libraries so it will take some time until it makes it way into the ESLint version since I need to catchup with a new LSP version.

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/vscode-languageserver-node/commit/12d7aaa38448e8ed5a2fc8f9480a93508ab38884 for the mitigation.
