### ISSUE TITLE
ES LINT Starting client failed

### ISSUE THREAD

**Issue by emuguy1** [microsoft/vscode-eslint#1095]
TypeError: Cannot read property 'toLowerCase' of null
	at Object.e.fromString (/Users/admin/.vscode/extensions/dbaeumer.vscode-eslint-2.1.13/client/out/extension.js:1:147330)
	at y.refreshTrace (/Users/admin/.vscode/extensions/dbaeumer.vscode-eslint-2.1.13/client/out/extension.js:1:54524)
	at y.initialize (/Users/admin/.vscode/extensions/dbaeumer.vscode-eslint-2.1.13/client/out/extension.js:1:47145)
	at /Users/admin/.vscode/extensions/dbaeumer.vscode-eslint-2.1.13/client/out/extension.js:1:46752
[Info  - 1:39:16 PM] ESLint server running in node v12.14.1

**Comment by dbaeumer** [comment]
@emuguy1 do you have any kind of setting set to `null`. ?

**Comment by dbaeumer** [comment]
As a workaround don't use null as a value.

**Comment by emuguy1** [comment]
eslint.trace.service has the value null
What can i use else then

**Comment by emuguy1** [comment]
I used off and it works now. Thank you

**Comment by alisa-alisa** [comment]
@emuguy1 I have exactly the same problem. I added trace service line but still has the same issue. Could you please advise me what helped you?

```
{
    "[javascript]": {
        "editor.formatOnSave": true,
    },
    "[typescript]": {
        "editor.formatOnSave": true,
    },
    "eslint.enable": true,
    "eslint.format.enable": true,
    "eslint.trace.service": "off"
}
```

**Comment by emuguy1** [comment]
I did exactly what you can already have done. Sounds like another issue. sr.
