### ISSUE TITLE
Conflict with prettier rule with fix on autosave

### ISSUE THREAD

**Issue by jrm2k6** [microsoft/vscode-eslint#1096]
In one of my file I get a warning related to an import needed to be broken up onto multiple lines:

<img width="858" alt="Screen Shot 2020-10-24 at 9 29 54 AM" src="https://user-images.githubusercontent.com/1088099/97087003-aa0e0a00-15db-11eb-8e23-a5c46019659c.png">

When applying the prettier fix, it becomes:

<img width="436" alt="Screen Shot 2020-10-24 at 9 30 06 AM" src="https://user-images.githubusercontent.com/1088099/97087009-b6926280-15db-11eb-832f-9591949e3ae9.png">

But, now, when saving (I have autofix on save enabled), it goes back to the original state, thus with an error.

My extension version is `v2.1.13`.

I took a look at the different settings for the extension itself but was not able to find anything meaningful.
Happy to investigate more, but not sure where to start to give you something more helpful.

Thanks!

**Comment by dbaeumer** [comment]
@jrm2k6  can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by jrm2k6** [comment]
Sure, this is the repo I was having this issue with https://github.com/jrm2k6/akee-electron.

**Comment by dbaeumer** [comment]
@jrm2k6 Seems to be private. Can you add me to the repository temporarily so that I can clone it?

**Comment by jrm2k6** [comment]
@dbaeumer I am so sorry. I assume you only need to be able to clone it, not actually run it?

**Comment by dbaeumer** [comment]
I only need to clone it. Thanks!

**Comment by dbaeumer** [comment]
Actually the repository doesn't seem to be self contained. I get

**Comment by dbaeumer** [comment]
Actually, the repository is not self contained. Can you provide me with the auto fix on save setting you are using?

**Comment by jrm2k6** [comment]
@dbaeumer Are you talking about checking the extension settings in vscode? What is the easiest way to export those?
From my global `settings.json`:

```
// Place your settings in this file to overwrite the default settings
{
    "window.zoomLevel": 1,
    "javascript.implicitProjectConfig.experimentalDecorators": true,
    "workbench.colorTheme": "Apollo Midnight",
    "editor.minimap.enabled": false,
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "eslint.alwaysShowStatus": true,
    "eslint.format.enable": true
}
```

**Comment by dbaeumer** [comment]
@jrm2k6 I can't reproduce this. This makes me think that you have another extension installed that contributes a formatter for TSX files which will be used on format on save with conflicting settings to the eslint validation. Can you reproduce this when all extension except ESLint are disabled.

**Comment by jrm2k6** [comment]
@dbaeumer I think I had something related to this extension https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero conflicting. Removing that extension fixed it.
Sorry for the red herring.

**Comment by dbaeumer** [comment]
No problem.
