### ISSUE TITLE
node/no-missing-{import|require} don’t found `fs/promises` module

### ISSUE THREAD

**Issue by valtlai** [microsoft/vscode-eslint#1097]
The [`no-missing-import`](https://github.com/mysticatea/eslint-plugin-node/blob/v11.1.0/docs/rules/no-missing-import.md) and [`no-missing-require`](https://github.com/mysticatea/eslint-plugin-node/blob/v11.1.0/docs/rules/no-missing-require.md) rules from [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node) don’t found the built-in [`fs/promises`](https://nodejs.org/api/fs.html#fs_fs_promises_api) module.

This only happens in the VS&nbsp;Code UI but not in the CLI (`npm test`, `npx eslint .` etc.) on Node 14 or newer.

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by valtlai** [comment]
@dbaeumer Yeah, here it is: [valtlai/vscode-eslint-issue-1097](/valtlai/vscode-eslint-issue-1097)

**Comment by dbaeumer** [comment]
@valtlai I see the same errors in vscode and the terminal

<img width="563" alt="capture" src="https://user-images.githubusercontent.com/1931590/97190814-80550e80-17a6-11eb-982f-26afd74d8d18.png">

<img width="518" alt="capture" src="https://user-images.githubusercontent.com/1931590/97190850-8b0fa380-17a6-11eb-8927-33a2a68d6b16.png">

**Comment by valtlai** [comment]
@dbaeumer Which Node version did you use? I can reproduce what’s in your comment on Node 13 or older.

**Comment by dbaeumer** [comment]
@valtlai for the extension the node version which ships with VS Code (see About dialog). On the command line `v12.8.1`

**Comment by valtlai** [comment]
@valtlai Oh, the different Node versions caused the issue. Setting the `eslint.runtime` option to use the system Node helped, so closing the issue.
