### ISSUE TITLE
.eslintignore in a monorepo is not applied

### ISSUE THREAD

**Issue by denis-sokolov** [microsoft/vscode-eslint#1100]
A .eslintignore file in a submodule in a monorepo is ignored and warnings are still shown when opening ignored files.

Given this directory structure:
```
module-a/
module-b/
  b-src/
  .eslintignore
  .eslintrc.js
```

Expected:
1. `/module-b/.eslintrc.js` is applied to configure linting on `b-src`.
2. `/module-b/.eslintignore` is applied to ignore some files in `b-src`.

Actual:
1. `/module-b/.eslintrc.js` is applied to configure linting on `b-src`.
2. `/module-b/.eslintignore` is NOT applied.
3. If I create a `/.eslintignore`, then it is respected.

Workaround:
`ignorePatterns` in `.eslintrc.js` is still respected.

**Comment by dbaeumer** [comment]
This is actually how ESLint works itself. The `.eslintrc.js` file is resolved relative to the file being validated whereas the `.eslintignore` file is resolved relative to the current working directory. So if you run eslint in a terminal with a cwd of the root (the parent of module-a and module-b) then it will fail as well.

To let the extension know about working directories you can use the setting `eslint.workingDirectories`.

Pleaser ping if this doesn't fix the problem.

**Comment by denis-sokolov** [comment]
I can confirm in my codebase running eslint from the top-level directory does not respect the eslintignore file. I was not aware that was the eslint behavior, I appreciate you taking the time to explain. Thank you!
