### ISSUE TITLE
compat plugin - advanced browserslist config not respected

### ISSUE THREAD

**Issue by jens-t** [microsoft/vscode-eslint#1102]
The eslint-plugin-compat has an option to overwrite the package.json browserslist config, with a specific config for the compat plugin, as shown here:
https://github.com/amilajack/eslint-plugin-compat/wiki/Advanced-Browserslist-Configs#inline-eslint-config

This works fine when running eslint at the command line, but not with vscode-eslint. Vscode-eslint ignores the browserslist config defined as `"compat/compat": ["error", "supports es6-module"],`, instead it uses the browserslist config from the package.json.

**Comment by dbaeumer** [comment]
@jens-t can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by jens-t** [comment]
During trying to reproduce this behaviour in a test repo, i noticed this is not a vscode-eslint bug, it is caused by eslint-plugin-compat itself. I will add an issue there.

Sorry, closing here.
