### ISSUE TITLE
Option to disable vscode user settings from workspace settings?

### ISSUE THREAD

**Issue by josh-hemphill** [microsoft/vscode-eslint#1104]
What the title says.
I have global user settings that conflict with various repositories, there should be some way for the workspace settings in the repository to reject all settings that are higher in the hierarchy.
I've tried explicitly the base and `overrideConfigFile` without success. Defining `"root":true` and/or `"rulePaths":["./"]` doesn't do it either.

**Comment by dbaeumer** [comment]
@josh-hemphill it sounds like you are asking for a general VS Code feature. I would therefore suggest you file an issue against VS Code itself. If you think that is ESLint specific can you please explain.

**Comment by josh-hemphill** [comment]
Yes, sorry, I'm talking about ESLint rules specifically. If rules are defined in User settings, then there is no way to clear them just for that workspace and use the workspace's rules or the file-defined rules only. 
It's particularly annoying when you have a rule defining indentation in user settings, and the workspace doesn't define the rule explicitly, because it's just inheriting the defaults.

**Comment by dbaeumer** [comment]
@josh-hemphill can you provide me with an example? Why would you configure ESLint rules in a vscode settings file?

**Comment by josh-hemphill** [comment]
@dbaeumer Now that I think about it, it doesn't make quite as much sense, but I use it as a default for all of my personal projects so I only have to copy it into a file if I plan to publish the project. With the current synchronization options it might make more sense to stick it all in a user snippet instead. Though if it's not super involved, it might be nice to have boolean option just to exclude merging from user settings in case others are using it for passing other options to eslint.

**Comment by dbaeumer** [comment]
I have to say I am still not understanding your request. Can you please provide me with an example.

**Comment by josh-hemphill** [comment]
Having settings like the following let me just open an empty folder and start writing some `.js` files for testing/data-manipulation without adding any `.eslintrc` files `package.json` or anything else. And if vscode-eslint is also my formatter, this means all my code just auto-fixes/formats to my preferred style without additional configuration.

```json
	// user settings.json
	"eslint.format.enable": true,
	"eslint.options": {
		"baseConfig": {
			"parserOptions": {
				"ecmaVersion": 2020
			}
		},
		"rules": {
			"indent": [
				"warn",
				"tab"
			],
			"linebreak-style": [
				"warn",
				"unix"
			],
	},
```

**Comment by josh-hemphill** [comment]
Oh, you mean of a solution? Having a config property in workspace settings like `eslint.mergeUserOptions: false` which would exclude user settings from being passed to `eslint.options`. Or to make it a little more consistent, maybe just let `eslint.options` or `eslint.options.rules` be set to false to only allow options/rules from files, completely bypassing rules or options in vscode settings.

**Comment by dbaeumer** [comment]
Although you can use the `eslint.options` for this it is by far not the recommended way. It is more there to pass options that you typically pass as a command line argument to the eslint command in the terminal.

You can achieve the same by having a `.eslintrc.json` file in you home folder.  Then this even works nicely when running ESLint in the terminal.

I am actually against extending the ESlint settings story with a `root` property or some merge options unless VS Code itself wants to offer it. VS code settings are scoped on the settings name which in this case is `eslint.options`. There is no merging of sub properties.

I am actually leaning towards closing this feature request as won't fix since as said this can already be achieved with native ESLint features.

**Comment by josh-hemphill** [comment]
Yeah, I'm going to change how I'm doing, though it might come up again for some other use case where `eslint.options` in the user settings conflicts with workspace settings.
