### ISSUE TITLE
I chose "Allow" every time this popup appeared, and now my auto-format on save has stopped working!

### ISSUE THREAD

**Issue by drew-royster** [microsoft/vscode-eslint#1106]
This has also happened to me.

ESLINT output shows

```
[Info  - 6:08:48 PM] ESLint server is starting
[Info  - 6:08:49 PM] ESLint server running in node v12.14.1
[Info  - 6:08:49 PM] ESLint server is running.
[Info  - 6:08:50 PM] ESLint library loaded from: /Users/<USER>/Documents/<repo>/node_modules/eslint/lib/api.js
```

I chose "Allow" every time this popup appeared, and now my auto-format on save has stopped working!

_Originally posted by @sarahsga in https://github.com/microsoft/vscode-eslint/issues/1012#issuecomment-659546167_

**Comment by dbaeumer** [comment]
@drew-royster can you share a repository I can clone that demos this. Are you seeing eslint errors in the problems view?

**Comment by drew-royster** [comment]
Apologies I believe that this was a mistake on my end.

**Comment by dbaeumer** [comment]
No problem.
