### ISSUE TITLE
Unexpected top-level property "overrides[0].extends"

### ISSUE THREAD

**Issue by SSmale** [microsoft/vscode-eslint#1108]
[I am following this tutorial](https://dev.to/bzvyagintsev/migrate-angular-app-to-eslint-with-prettier-airbnb-styleguide-husky-and-lint-staged-862) to add ESlint to my Angular 10 application but get the following error message in the ESLint plugin console: 
` Error: ESLint configuration in <FILE> is invalid:
	- Unexpected top-level property "overrides[0].extends".`

I have had a google but have not found anything to point to the root of the problem as the format in the ESlint config seems to be valid and I can run it from the CLI fine.

**Comment by dbaeumer** [comment]
@SSmale does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by SSmale** [comment]
Hi @dbaeumer, 

yes it seems to be working fine in the cli. Unfortunately i can't provide the repo i am working in but will try to get a mini one up together later

**Comment by SSmale** [comment]
Ok, so I reloaded the VS Code window and it just worked.... must have been a red herring....
