### ISSUE TITLE
node_modules is not ignored by default with VSCode Remote

### ISSUE THREAD

**Issue by denis-sokolov** [microsoft/vscode-eslint#1109]
[By default ESLint ignores](https://eslint.org/docs/user-guide/configuring) `node_modules`, even when it is not included in the `ignorePatterns` configuration option. vscode-eslint follows this pattern when I open the directory normally.

vscode-eslint starts showing linting warnings in node_modules if I open the same directory using [VSCode Remote with SSH](https://code.visualstudio.com/docs/remote/ssh). vscode-eslint over ssh still respects `ignorePatterns`, so if I add `node_modules` there, it correctly ignores them.

I do not use a monorepo in this project, my `eslint.workingDirectories` option is empty.

The inconsistency seems undesired, although the impact is quite low.

Possibly related: #486

**Comment by dbaeumer** [comment]
What happens when you run eslint in the terminal in that setup.

**Comment by denis-sokolov** [comment]
If I run it in the directory, it ignores node_modules. But notice I can’t (or don’t know how to) reproduce “that setup”, since it’s specific to VSCode Remote protocol. When I run a script in the terminal, the directory is local from the perspective of eslint binary.

**Comment by dbaeumer** [comment]
> When I run a script in the terminal, the directory is local from the perspective of eslint binary.

The same is true for the ESLint extension. VS Code remotes the extension into the other 'machine'. SO the extension does see the same as the terminal does.

Can you provide me with a GitHub repository that demos this and instructions which remote setup you are using?

**Comment by denis-sokolov** [comment]
I see. It’s really unexpected then I receive such behavior. As I’ve said, VSCode on the machine correctly ignores node_modules, only VSCode over SSH does not. I was making an assumption it’s working directory related, that the remote folder is opened as a sort of FUSE path, and that’s what makes it different. If it actually runs on the remote machine, it should behave the same way.

I see, given that this is not as obvious as I hoped for, I will have to prepare a reproduction repo. I will do my best, but please excuse a delay, since doing that takes more time than creating a bug report. Thanks for your help, by the way!

**Comment by dbaeumer** [comment]
We architecture remote in a way that it sees the same files and layout as if it would run in a local machine to avoid exactly problems that would come up if you would mount the remote FS into a local machine.

**Comment by denis-sokolov** [comment]
I can reliably reproduce the problem with a particular project directory that I have, but I am unable to create an independent reproduction.

The closest I’ve got is noticing that if I use the exact same directory with the exact same file, but I move it (rename it), then the editor starts behaving correctly. This implies there’s some state preserved somewhere that is bound to my project path, but is outside of the workspace settings.

ESLint log has differences between running in the two cases. Most notably, it has a different value of `basePath`.
    - Directory with incorrect behavior: `basePath: '/monorepo/projectA/node_modules/@types/react'`
    - Directory with the correct behavior: `basePath: '/monorepo'`
This also generates some different ignore patterns and eventually leads to running the linter on the file or not running. 

<details><summary>Diff in more detail</summary>

![image](https://user-images.githubusercontent.com/113721/99193658-1ca97a00-2783-11eb-8d19-69e9af9da0c8.png)

```diff
@@ -2,10 +2,10 @@ ESLint server is starting
 ESLint server running in node v12.14.1
 ESLint server is running.
 ESLint library loaded from: /monorepo/projectA/node_modules/eslint/lib/api.js
-eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo/projectA/node_modules/@types/react', loose: false } ]
-eslint:ignore-pattern   processed: { basePath: '/monorepo/projectA/node_modules/@types/react', patterns: [ '/**/node_modules/*' ] }
-eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo/projectA/node_modules/@types/react', loose: false } ]
-eslint:ignore-pattern   processed: { basePath: '/monorepo/projectA/node_modules/@types/react', patterns: [ '/**/node_modules/*' ] }
+eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo', loose: false } ]
+eslint:ignore-pattern   processed: { basePath: '/monorepo', patterns: [ '/**/node_modules/*' ] }
+eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo', loose: false } ]
+eslint:ignore-pattern   processed: { basePath: '/monorepo', patterns: [ '/**/node_modules/*' ] }
 eslint:rules Loading rule 'constructor-super' (remaining=281)
 eslint:rules Loading rule 'for-direction' (remaining=280)
 eslint:rules Loading rule 'getter-return' (remaining=279)
@@ -79,28 +79,21 @@ eslint:rules Loading rule 'no-template-curly-in-string' (remaining=212)
 eslint:rules Loading rule 'no-throw-literal' (remaining=211)
 eslint:rules Loading rule 'prefer-promise-reject-errors' (remaining=210)
 eslint:rules Loading rule 'eqeqeq' (remaining=209)
-eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo/projectA/node_modules/@types/react', loose: false }, IgnorePattern { patterns: [ '/*.js' ], basePath: '/monorepo/projectA', loose: false } ]
-eslint:ignore-pattern   processed: { basePath: '/monorepo/projectA', patterns: [ '/node_modules/@types/react/**/node_modules/*', '/*.js' ] }
-eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo/projectA/node_modules/@types/react', loose: false } ]
-eslint:ignore-pattern   processed: { basePath: '/monorepo/projectA/node_modules/@types/react', patterns: [ '/**/node_modules/*' ] }
-eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo/projectA/node_modules/@types/react', loose: false } ]
-eslint:ignore-pattern   processed: { basePath: '/monorepo/projectA/node_modules/@types/react', patterns: [ '/**/node_modules/*' ] }
-eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo/projectA/node_modules/@types/react', loose: false }, IgnorePattern { patterns: [ '/*.js' ], basePath: '/monorepo/projectA', loose: false } ]
-eslint:ignore-pattern   processed: { basePath: '/monorepo/projectA', patterns: [ '/node_modules/@types/react/**/node_modules/*', '/*.js' ] }
+eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo', loose: false }, IgnorePattern { patterns: [ '/*.js' ], basePath: '/monorepo/projectA', loose: false } ]
+eslint:ignore-pattern   processed: { basePath: '/monorepo', patterns: [ '/**/node_modules/*', '/projectA/*.js' ] }
+eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo', loose: false } ]
+eslint:ignore-pattern   processed: { basePath: '/monorepo', patterns: [ '/**/node_modules/*' ] }
+eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo', loose: false } ]
+eslint:ignore-pattern   processed: { basePath: '/monorepo', patterns: [ '/**/node_modules/*' ] }
+eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/monorepo', loose: false }, IgnorePattern { patterns: [ '/*.js' ], basePath: '/monorepo/projectA', loose: false } ]
+eslint:ignore-pattern   processed: { basePath: '/monorepo', patterns: [ '/**/node_modules/*', '/projectA/*.js' ] }
 eslint:ignore-pattern Check {
   filePath: '/monorepo/projectA/node_modules/@types/react/index.d.ts',
   dot: false,
-  relativePath: 'node_modules/@types/react/index.d.ts',
-  result: false
+  relativePath: 'projectA/node_modules/@types/react/index.d.ts',
+  result: true
 }
-eslint:cli-engine Lint /monorepo/projectA/node_modules/@types/react/index.d.ts
-eslint:linter Linting code for /monorepo/projectA/node_modules/@types/react/index.d.ts (pass 1)
-eslint:linter Verify
-eslint:linter With ConfigArray: /monorepo/projectA/node_modules/@types/react/index.d.ts
-eslint:linter Generating fixed text for /monorepo/projectA/node_modules/@types/react/index.d.ts (pass 1)
-eslint:source-code-fixer Applying fixes
-eslint:source-code-fixer shouldFix parameter was false, not attempting fixes
-eslint:cli-engine Linting complete in: 1262ms
+eslint:cli-engine Linting complete in: 5ms
 eslint:rules Loading rule 'accessor-pairs' (remaining=208)
 eslint:rules Loading rule 'array-bracket-newline' (remaining=207)
 eslint:rules Loading rule 'array-bracket-spacing' (remaining=206)
```

</details>

The logs above is with `eslint.workingDirectories` set to `[]`. Although the problem happens with `[{ "mode": "auto" }]`, too.

Seeing how this is dependent on some state specific to my project directory, I expect the debugging cost to be too high, so I’m closing the issue. If you desire to investigate with the given limitations, or would like to keep the issue open for other reasons, by all means, please reopen and let me know how I can help. Thank you!

**Comment by dbaeumer** [comment]
@denis-sokolov thanks for the information. I will have a time limited look to see if I notice something.

**Comment by denis-sokolov** [comment]
The logs above already suggest that the problem is more about incorrect detection of basePath, and is unrelated to ignoring node_modules. Today I can further confirm that by observing another difference in behavior between a local and Remote versions: I get “Parsing error: parserOptions.project has been set for @typescript-eslint/parser. The file does not match your project config.” only in the Remote version. Not in local and not in CLI.

No action is needed, added for posterity.

**Comment by dbaeumer** [comment]
@denis-sokolov thanks for getting back and the clarification!
