### ISSUE TITLE
@angular-eslint/component-selector highlighting in vscode-eslint extension

### ISSUE THREAD

**Issue by SSmale** [microsoft/vscode-eslint#1110]
Hi,

Not sure where the issue would lie so have created an issue in both projects 

https://github.com/angular-eslint/angular-eslint/issues/174

**Comment by dbaeumer** [comment]
@SSmale does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by SSmale** [comment]
Please ignore this, i was getting my settings mixed up. Sorry
