### ISSUE TITLE
ESLint cannot find tsconfig.json in a Firebase project

### ISSUE THREAD

**Issue by osharaki** [microsoft/vscode-eslint#1115]
I have a Flutter project with a Firebase project located in a directory (called cloud) within it. I have an _index.ts_ file located at _cloud/functions/src_. The Firebase project structure looks like this:

![image](https://user-images.githubusercontent.com/38385026/99115601-f6ed6b00-25f2-11eb-8588-fd830f5cbd7c.png)

For some reason, I get an error on the `import` keyword in the first line of _index.ts_ that says:
> Parsing error: Connot read file <path-to-file>/tsconfig.json

I get the same error when I hover over the `module` keyword in `.eslintrc.js`.

Here's my _.eslintrc.js_:
```
module.exports = {
  env: {
    browser: true,
    es6: true,
    node: true,
  },
  extends: [
    "plugin:import/errors",
    "plugin:import/warnings",
    "plugin:import/typescript",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "tsconfig.json",
    sourceType: "module",
  },
  plugins: [
    "@typescript-eslint",
    "import",
  ],
  rules: {
    "@typescript-eslint/adjacent-overload-signatures": "error",
    "@typescript-eslint/no-empty-function": "error",
    "@typescript-eslint/no-empty-interface": "warn",
    "@typescript-eslint/no-floating-promises": "error",
    "@typescript-eslint/no-namespace": "error",
    "@typescript-eslint/no-unnecessary-type-assertion": "error",
    "@typescript-eslint/prefer-for-of": "warn",
    "@typescript-eslint/triple-slash-reference": "error",
    "@typescript-eslint/unified-signatures": "warn",
    "comma-dangle": ["error", "always-multiline"],
    "constructor-super": "error",
    eqeqeq: ["warn", "always"],
    "import/no-deprecated": "warn",
    "import/no-extraneous-dependencies": "error",
    "import/no-unassigned-import": "warn",
    "no-cond-assign": "error",
    "no-duplicate-case": "error",
    "no-duplicate-imports": "error",
    "no-empty": [
      "error",
      {
        allowEmptyCatch: true,
      },
    ],
    "no-invalid-this": "error",
    "no-new-wrappers": "error",
    "no-param-reassign": "error",
    "no-redeclare": "error",
    "no-sequences": "error",
    "no-shadow": [
      "error",
      {
        hoist: "all",
      },
    ],
    "no-throw-literal": "error",
    "no-unsafe-finally": "error",
    "no-unused-labels": "error",
    "no-var": "warn",
    "no-void": "error",
    "prefer-const": "warn",
  },
  settings: {
    jsdoc: {
      tagNamePreference: {
        returns: "return",
      },
    },
  },
};
```

And here's _tsconfig.json_:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017"
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

I've searched quite a bit online and one thing I found [here](https://github.com/microsoft/vscode-eslint/issues/722#issuecomment-519611301) that seemed to work was adding this to my user settings
```
"eslint.workingDirectories": [
        {
            "directory": "cloud/functions",
            "changeProcessCWD": true
        },
    ]c
```
This removes the error from the `import` and highlights errors in my code that indeed show up when I attempt to deploy my project. It does, however, also change the error that appears over the `module` keyword in _.eslintrc.js_ to

> Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided.

Which is apparently being caused by ESLint including files that it shouldn't. But there seem to be ways to get around that as described [here](https://stackoverflow.com/a/62157530/4348037). 
I also tried following the [suggestion](https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration) to remove the `parserOptions.project` property entirely from _.eslintrc.js_, but then the linting rules required by Firebase don't get applied and I'm only informed of errors when I attempt to deploy.

**Comment by dbaeumer** [comment]
@osharaki  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by osharaki** [comment]
> @osharaki does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

`npm run lint` works fine. I created a dummy repo [here](https://github.com/osharaki/firebase-eslint) that reproduces the error.
Don't forget to run `npm install` inside the */functions* directory.

**Comment by dbaeumer** [comment]
Actually you see the same problem when running eslint in the terminal in the workspace root

<img width="744" alt="capture" src="https://user-images.githubusercontent.com/1931590/99376667-8467de00-28c5-11eb-8c32-dc91586fef1c.png">

Validation works correctly when running inside the `functions` folder. So you need to let the extension know about this working directory setup using the `eslint.workingDirectories` setting.

**Comment by phillsv87** [comment]
> Actually you see the same problem when running eslint in the terminal in the workspace root
> 
> <img alt="capture" width="744" src="https://user-images.githubusercontent.com/1931590/99376667-8467de00-28c5-11eb-8c32-dc91586fef1c.png">
> 
> Validation works correctly when running inside the `functions` folder. So you need to let the extension know about this working directory setup using the `eslint.workingDirectories` setting.

This worked for me too. My functions directory was in a backend project under the root of my main project.
``` json
// .vscode/seetings.json
{
    "eslint.workingDirectories": [
        "backend/functions"
    ]
}
```

**Comment by HobaiRiku** [comment]
I add ` tsconfigRootDir: __dirname`  to eslintrc file and it work: 
```js
parserOptions: {
    project: 'tsconfig.json',
    sourceType: 'module',
    tsconfigRootDir: __dirname
  },
```

**Comment by nsquaredotone** [comment]
I can't believe that this issue still exists when initializing firebase with Typescript.

**Comment by yelkamel** [comment]
I still have this issue ... :'(

**Comment by shovelmn12** [comment]
Same :\

**Comment by cto-mantiqh** [comment]
> ```js
> tsconfigRootDir: __dirname
> ```

This worked for me!
