### ISSUE TITLE
Plugin cannot handle filename case changes

### ISSUE THREAD

**Issue by vdh** [microsoft/vscode-eslint#1116]
When a file is renamed in a way that changes case (e.g. `components/foo.jsx` to `components/Foo.jsx`), the plugin never stops caching the previous file's pathname. Even after reloading the window or restarting VSCode, it still reports false-negatives on the file (e.g.`Filename 'foo' must match the exported and transformed name 'Foo'.` for the `filenames/match-exported` rule). The ESLint CLI doesn't report any issues.

**Comment by dbaeumer** [comment]
@vdh can you please provide me with a GitHub repository I can clone that demos what you are experiencing. This ensure I test it with the same setup. This might be a problem with VS Code itself. I don't know if VS Code changes the URI on case insensitive file systems in that case.

**Comment by vdh** [comment]
Here's a minimal reproduction I was able to make: https://github.com/vdh/rename-issue-test

If the problem doesn't appear in VSCode after a clone and `npm install`, you might have to check out the previous commit (`8842e4008dde82ad1b1ad566e27c5ea5cbf27122`), open the file in VSCode, then check out the rename commit (`95ad5f537a468cebf4ec878c047fd528048a4abd`).

For context I'm currently on macOS Catalina 10.15.7 and VSCode 1.51.1, since it may be related to VSCode or the file system.

**Comment by dbaeumer** [comment]
@vdh thanks for the repository. How do you do the rename. I tested it with renaming inside VS Code and there everything works for me:

![cast](https://user-images.githubusercontent.com/1931590/99368068-08689880-28bb-11eb-84ac-06748980ecad.gif)

**Comment by dbaeumer** [comment]
If I checkout `8842e4008dde82ad1b1ad566e27c5ea5cbf27122` open the file and then checkout master again VS Code correctly shows me that the old file got deleted and when opening the new one no errors are shown.  Can you please add some steps.

**Comment by vdh** [comment]
I think this might be an issue with VSCode and case-insensitive file systems (WSL emulates Linux which is case-sensitive, so you probably didn't encounter it).

This issue looks like it might be what I'm experiencing, based on the similar misbehaving tabs, and something bad being cached somewhere inside the `workspaceStorage` folder: https://github.com/microsoft/vscode/issues/102627 It's unfortunate that they seem to have closed it though.

Since this looks more like a VSCode bug than an issue with this extension, I'll close this issue.

**Comment by dbaeumer** [comment]
Let me test this on Windows then.

**Comment by dbaeumer** [comment]
Reopening...
