### ISSUE TITLE
ESLint typing imports from custom paths as "any"

### ISSUE THREAD

**Issue by isaacparker2** [microsoft/vscode-eslint#1117]
I've defined custom paths in tsconfig.json, and though the compiler finds/types them correctly and eslint itself seems to work correctly when running in the terminal, within VSCode I get errors when trying to use imports from these custom paths. The linting errors I get are come from rules including "no-unsafe-call", "restrict-template-expressions", "no-unsafe-access", and are all explained as due to the imported value being of type "any".

I _think_ this issue might also related to my use of a monorepo setup, as I only intermittently have the same problem in a single-package setup.

I've created a minimal reproduction with this repo: https://github.com/isaacparker2/eslint-test .
The custom path is defined [here](https://github.com/isaacparker2/eslint-test/blob/master/packages/package1/tsconfig.json#L8), and the linting error occurs [here](https://github.com/isaacparker2/eslint-test/blob/master/packages/package1/src/test.ts).

**Comment by dbaeumer** [comment]
When running eslint in the terminal in which working directory do you do that. It it is not the workspace root then you need to let the eslint extension know about such a working directory setup using the `eslint.workingDirectories` setting.

I actually guess that when you run eslint in the terminal you do that in `packages/package1`

**Comment by dbaeumer** [comment]
Without a working directory setup the terminal and the extension produces the same result

<img width="664" alt="capture" src="https://user-images.githubusercontent.com/1931590/99376336-14f1ee80-28c5-11eb-8134-6a2b466cda8e.png">

<img width="680" alt="capture" src="https://user-images.githubusercontent.com/1931590/99376369-21764700-28c5-11eb-9203-8030ac5b2dac.png">

**Comment by isaacparker2** [comment]
Ah, adding eslint.workingDirectories to `.vscode/settings.json` in the root fixes it!

```
{
  "eslint.workingDirectories": [{ "pattern": "./packages/*/" }]
}
```
Thanks so much for taking the time to help!
