### ISSUE TITLE
Extension eslint cannot format .../[id]/index.tsx files

### ISSUE THREAD

**Issue by michalkvasnicak** [microsoft/vscode-eslint#1118]
I use eslint as a formatter for `.tsx?` files but it is unable to format files that contain `[]` in the path. I found that it was mentioned in #1086 in comment https://github.com/microsoft/vscode-eslint/issues/1086#issuecomment-716451836. 

It doesn't work for `[id]/index.tsx` and `[id].tsx`

![image](https://user-images.githubusercontent.com/174716/99501136-a328ac00-297b-11eb-94f7-db7fcc1b0df4.png)

Visual Studio Code:

```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (1 wk ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

VSEslint: `v2.1.13`

**Comment by dbaeumer** [comment]
This works for me with js files. In the extension there is no difference between tsx / js or ts files in regards to formatting. Can you provide me with a Github repository I can clone that demos what you are seeing.

<img width="744" alt="capture" src="https://user-images.githubusercontent.com/1931590/99516793-e50f1d80-298e-11eb-94ab-f4b0b4b3884c.png">
