### ISSUE TITLE
The ESLint server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by artyomtrityak** [Microsoft/vscode-eslint#112]
I got this message "The ESLint server crashed 5 times in the last 3 minutes. The server will not be restarted." on .jsx file save.
There is no explanation why was it crashed 5 times and how to fix this issue.

Is there any way to understand how to fix this issue and see more explicit error?

Some details:

```
"babel-eslint": "^4.1.8",
"eslint": "^2.4.0",
"eslint-plugin-react": "^3.16.1",
```

.eslintrc
```
{
  "env": {
    "browser": true,
    "node": true
  },
  "parser": "babel-eslint",
  "plugins": ["react"],
  "globals": {
    "define": true,
    "requirejs": true,
    "analytics": true
  },
  "rules": {
    "semi": [2, "always"],
    "no-alert": 2,
    "no-debugger": 2,
    "no-empty": 2,
    "new-cap": 0,
    "no-dupe-class-members": 2,
    "no-restricted-syntax": [2, "WithStatement"],
    "no-unused-expressions": 2,
    "no-trailing-spaces": 1,
    "no-shadow": 2,
    "no-undef": 2,
    "no-use-before-define": 0,

    "react/jsx-boolean-value": [2, "always"],
    "react/jsx-no-undef": 2,
    "react/jsx-uses-react": 2,
    "react/jsx-uses-vars": 2,
    "react/no-did-mount-set-state": 2,
    "react/no-did-update-set-state": 2,
    "react/no-multi-comp": 1,
    "react/no-unknown-property": 2,
    "react/react-in-jsx-scope": 2
  }
}
```

**Comment by dbaeumer** [comment]
@artyomtrityak do you have a repository I can clone that shows the behavior. Usually when crashing the client doesn't have a lot of information why.

**Comment by abalmus** [comment]
+1

**Comment by dbaeumer** [comment]
I was able to reproduce a case where a eslint plugin call process.exit() which in the case of the server shutdowns the server. It was basically a misconfiguration of the eslint / eslint plugin setup.

I added code on the server that detects that case and shows a corresponding message to the user.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode-eslint/issues/114.

I will keep this issue open until a new version of ESLint is publish to see if the exit is really causing this.

**Comment by abalmus** [comment]
Ok not I can see the ERROR in output: 
Error: Cannot find module 'estraverse-fb'

**Comment by dbaeumer** [comment]
@abalmus good to see that you get better error messages now. At the end there is little the eslint extension can do if the eslint library has problems with a certain setup. What is always a good thing to do is to run eslint from the command line to see if it works. 

Any objections to close this issue.

**Comment by abalmus** [comment]
Yeah good point, think you! I think this one can be closed.

**Comment by dbaeumer** [comment]
Closing.
