### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Kirun1** [microsoft/vscode-eslint#1121]
- Issue Type: `Performance`
- Extension Name: `vscode-eslint`
- Extension Version: `2.1.13`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ps\AppData\Local\Temp\dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by dbaeumer** [comment]
@Kirun1 can you please attach the cpu profile.
