### ISSUE TITLE
Eslint cannot format document that are too deep in the filetree ...

### ISSUE THREAD

**Issue by MLKiiwy** [microsoft/vscode-eslint#1123]
Took me a while to reproduce the issue. The plugin cannot accept file that are deeper than 6 directories ...

I have a document under `packages/ask-generic-react/src/theme/storybook/text/index.stories.tsx` -> if I try to format it with eslint using the command Format or in autosave, I get a error message in the taskbar "Cannot format document ...."

If I move the same file, one level upper in the filetree: `packages/ask-generic-react/src/theme/storybook/index.stories.tsx`, the formater works ... 

I'm running VSCode on ubuntu linux.

**Comment by dbaeumer** [comment]
Works for me.

![cast](https://user-images.githubusercontent.com/1931590/99802689-68b83e00-2b38-11eb-81b5-8e8de75f2bfa.gif)


Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by MLKiiwy** [comment]
Sorry I can't with my actual repo, it's a company private one.

**Comment by dbaeumer** [comment]
Can you distill something?
