### ISSUE TITLE
Do not use Number.MAX_VALUE but 2147483647

### ISSUE THREAD

**Issue by entropitor** [microsoft/vscode-eslint#1125]
E.g. 
https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1833
and
https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1729

Because
https://github.com/microsoft/vscode-languageserver-node/blob/3690f97c7997d883fcc97d365e5e1d5c3af4dd31/types/src/main.ts#L131-L138
namely
https://github.com/microsoft/vscode-languageserver-node/blob/3690f97c7997d883fcc97d365e5e1d5c3af4dd31/types/src/main.ts#L134
which calls
https://github.com/microsoft/vscode-languageserver-node/blob/3690f97c7997d883fcc97d365e5e1d5c3af4dd31/types/src/main.ts#L81-L84
which calls
https://github.com/microsoft/vscode-languageserver-node/blob/3690f97c7997d883fcc97d365e5e1d5c3af4dd31/types/src/main.ts#L3362-L3364

while Number.MAX_VALUE is `1.7976931348623157e+308`

I'm not sure how this is working for vscode but when I set it up for vim, I've got to replace this with 2147483647 or I get an error and codeAction is not working

**Comment by dbaeumer** [comment]
Agree, especially since in 3.16 version of the spec integer and integer are defined.

**Comment by entropitor** [comment]
Is `uinteger.MAX_VALUE` something that needs to be added to the shared library? If so, is there a link to a ticket somewhere?

**Comment by dbaeumer** [comment]
I already added it but didn't release a new version yet.
