### ISSUE TITLE
Improved TypeScript detection

### ISSUE THREAD

**Issue by vzaidman** [microsoft/vscode-eslint#1129]
Hey I saw

> Improved TypeScript detection - As soon as TypeScript is correctly configured inside ESLint, you no longer need additional configuration through VS Code's eslint.validate setting. The same is true for HTML and Vue.js files.

In changelog. Can you explain what it does, please?

Can I run the extension with TypeScript?

**Comment by dbaeumer** [comment]
Yes, you can run the extension with TypeScript. See https://github.com/typescript-eslint/typescript-eslint on how this works in ESLint itself.

**Comment by vzaidman** [comment]
thanks!
can you please explain how `eslint.validate` works with typescript?

**Comment by dbaeumer** [comment]
With `eslint.validate` you can force TypeScript validation. But I am not aware of a single case right now where this is necessary. TypeScript is validated correctly if ESLint is configured correctly to do so.

**Comment by vzaidman** [comment]
gotcha. for me it worked only when I used:
```
    "eslint.validate": ["javascript", "javascriptreact", "typescript", "typescriptreact"],
```

**Comment by beeplin** [comment]
> With `eslint.validate` you can force TypeScript validation. But I am not aware of a single case right now where this is necessary. TypeScript is validated correctly if ESLint is configured correctly to do so.

@dbaeumer I figured out that this only works when 

1) the `.eslintrc.js` is located at the root of the vscode workingspace, or

2) the vscode workingspace as a `.vscode/settings.json` as such:

```json
{
  "eslint.workingDirectories": [
    { "directory": "./server", "changeProcessCWD": true },
    { "directory": "./www", "changeProcessCWD": true }
  ]
}
```

If neither is true, we now have to use  `"eslint.validate": ["javascript", "javascriptreact", "typescript", "typescriptreact"]` instead, as @vzaidman saide above.

**Comment by dbaeumer** [comment]
@beeplin does validation happen correctly in the terminal without doing a cd into server or www before?

**Comment by beeplin** [comment]
@dbaeumer oops actually it works well both in commandline and in vscode. Turned out I was wrong, maybe because I set up some cache for eslint wrongly. New mind. And good job for the wonderful tool~!
