### ISSUE TITLE
"Casing of {file path} does not match the underlying filesystem" Mac

### ISSUE THREAD

**Issue by tpoppen** [microsoft/vscode-eslint#1130]
![image](https://user-images.githubusercontent.com/6015146/100261857-fc12ba00-2f10-11eb-91cd-38fc0a79f1fb.png)

The file path and casing does match. 

This issue started happening a couple days ago. I've reloaded the VSCode window, I've restarted VSCode, tried uninstalling and reinstalling the extension, and have restarted my machine several times.

**Comment by dbaeumer** [comment]
Did you rename those lately. There is an issue in VS Code that keeps the old casing of a file when listed in the editor group. Removing them all there should get you into a clean state again.

I fixed this in ESLint, but haven't released a new version yet. Will come mid Dezemeber. 

Dups https://github.com/microsoft/vscode-eslint/issues/1116

**Comment by tpoppen** [comment]
No, they were brand new files, only one name was given to them.

**Comment by dbaeumer** [comment]
Because is sounded like being a dup of #1116 and you can always comment on closed issues.

Does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by tpoppen** [comment]
Fair enough. I'll work on getting the additional information today and tomorrow between thanksgiving events. Thank you.

**Comment by dbaeumer** [comment]
Great. Ping when available.

**Comment by tpoppen** [comment]
I tried duplicating it in a fresh project and I can't get it to happen... For now I'm going to close this and investigate if it's something to do with our own configuration or if it's a side effect of our configuration and the duplicate you linked to.
