### ISSUE TITLE
Firebase/TypeScript project: 'Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser'

### ISSUE THREAD

**Issue by hithomasmorelli** [microsoft/vscode-eslint#1135]
Related to #1115

When a TypeScript Firebase Cloud Functions workspace is open in VS Code, opening `functions/.eslintrc.js` causes the following error to be presented:

<img width="698" src="https://user-images.githubusercontent.com/22722644/101280324-6e608580-37c0-11eb-8223-3c229d51ee40.png">

In the workspace's `.vscode/settings.json` file, I've set `"eslint.workingDirectories"` to `["./functions"]`.

I've created a repository that should be able to reproduce the issue - see https://github.com/hithomasmorelli/vscode-eslint-parseroptions-project-repro (README contains instructions on how to reproduce)

**Comment by dbaeumer** [comment]
Same happens to me when executing eslint in the terminal.

<img width="694" alt="capture" src="https://user-images.githubusercontent.com/1931590/101497470-4d886380-396b-11eb-8c13-3d0b5aea64c6.png">


Since the extension requires a correctly setup eslint there is nothing I can do except showing the error as well.

I am closing the issue. Please ping if you think there is something that should be addressed in the ESLint extension itself.

**Comment by hithomasmorelli** [comment]
Apologies, this appears to be an issue with (or with my setup of) `typescript-eslint`. Sorry for raising it here!

**Comment by hithomasmorelli** [comment]
@dbaeumer is there a way to tell vscode-eslint to only lint files that match a specified pattern *within* the `./functions` working directory?

i.e. `npm run lint` on the dummy repo calls `eslint "src/**/*"` - it'd be good if I could set up the VSCode ESLint extension so that it would only lint the files that match that same pattern.

Changing `.vscode/settings.json` to

```json
{
    "eslint.workingDirectories": [{
        "pattern": "./functions/src/**/*"
    }],
}
```

doesn't work, as the extension now can't read the `tsconfig.json` file in the `functions` directory&mdash;

<img width="936" alt="screenshot: .eslintrc.js (functions): Parsing error: Cannot read file '[redacted]/vscode-eslint-parseroptions-project-repro/tsconfig.json'. [eslint 1, 1]" src="https://user-images.githubusercontent.com/22722644/101508452-9a6e3900-396f-11eb-97d0-f4796830f752.png">

&mdash;but keeping it as

```json
{
    "eslint.workingDirectories": ["./functions"]
}
```

means that it picks up on files I don't want it attempting to lint, such as `.eslintrc.js`.

**Comment by dbaeumer** [comment]
ESLint itself has support for this. Check for `.eslintignore` files.
