### ISSUE TITLE
[2.1.13] Suddenly not resolving modules anymore on working projects

### ISSUE THREAD

**Issue by Friksel** [microsoft/vscode-eslint#1136]
For some reason the eslint extension cannot find/resolve NONE of the modules anymore on a working project that was finding everything before without issue. It looks like this is a change in the extension I don't know about or an issue.

At first when I saw this I thought I needed to upgrade the eslint package, so I'm at the latest version of eslint now, but without success.

Looking in the Output panel though I see this a weird error thrown by the extension (by eslintServer.js):
```
Error resolving webpackConfig Error: Cannot find module 'webpack/package.json'
```

Which makes sense that it cannot find it as my package.json is in the root of the project, as normal, but shouldn't look there in the first place. Not sure why it's searching in some webpack folder the project doesn't even have, but it's obvious that it cannot find it there.

The ESLint label in the bottomright corner is marked with a double checkbox, so it's not blocked or whatever.

[edit] I see that at least v2.1.10, v2.1.8 and v2.1.7, so the previous three versions, have the exact same issue and same error message in the output. But I didn't change anything AFAIK to both the project as well as to the installed modules. I'm at the latest version of VS Code for a while now (1.51.1) and didn't have this problem recently. Also just checked for updates on VS Code but there weren't any.
This was definitely working last week and didn't change anything manually since, so beats me what's going on.

It's now suddenly broken in ALL projects, so definitely not project-related. I'm using the locally installed eslint package on each project.

**Something I need to know? Some change in the settings maybe I'm not aware of? Do we need to manually set the location of the package.json now or something? Is this a known issue in the extension?**

Further info:
* Working on Windows 10 
* Vs Code: v1.51.1
* eslint: v7.15.0 (installed locally in project, no global package available)
* eslint-plugin-import: v2.22.1
* eslint-import-resolver-webpack: v0.12.2

**Comment by dbaeumer** [comment]
@Friksel  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Friksel** [comment]
@dbaeumer  Thanks for your response.

When running `npx eslint path-to\file.js` in the a terminal eslint executes, but there are no messages in the output other than the `console.log()` I put inside the `webpack.config.js` myself, but repeated several times in a row. This is probably due to me using the `import` plugin and the `webpack` import/resolver.

It doesn't make sense to remove this plugin and the webpack resolver for testing purposes IMO because the resolve-thing is the whole issue here. It can resolve local files with a relative path perfectly fine, but cannot find any module from the node_modules folder nor webpack aliases. These were working before for years and I can't think of any change I made to the config that could cause this. I also compared this to other projects.

I am completely blank at this point as this was working before. But obviously somewhere in the chain something changed. Any clue where to look?

**Comment by dbaeumer** [comment]
@Friksel can you please provider me with a GitHub repository I can clone that demos this.

**Comment by dbaeumer** [comment]
Could be a working directory issue. You might want to have a look at the `eslint.workingDirectories` setting.

**Comment by Friksel** [comment]
> @Friksel can you please provider me with a GitHub repository I can clone that demos this.
Sorry, I never send projects for obvious reasons. Also I'm using both webpack es well as eslint setups both pretty standard with webpack and eslint configs in the root of the projectfolder, together with the package.json. And it always worked fine that way (for years). But if you have a particular question I can always look of course.

> Could be a working directory issue. You might want to have a look at the `eslint.workingDirectories` setting.
I don't have that setting set. Never had either. So I would expect the default would be to look for a package.json in the root of the project, as that's the standard. I could try to set that setting manually, but I'm not sure where to set it too, as I would expect everything to be default. 

I've just tried adding the setting like this, but it doesn't help, still the same issues:
```
"eslint.workingDirectories": [
        { 
            "directory" : "./", 
            "changeProcessCWD": true
        }
    ],
```

Could you please tell me how to set that setting to have the package.json in the root and confirm that's really necesary if I'm using standard locations for config files? Thanks

**Comment by dbaeumer** [comment]
The working directory setting is usually necessary if you have a multi project repository with different configs per folder. 

It is hard to say why this is not working for you unless I get a GitHub repository I can look at. If you can share your project could you distil a reproducible case.

**Comment by mvirbicianskas** [comment]
Having same issue, previously had this:
```
"eslint.workingDirectories": [ {  "mode": "auto" } ],
```
Removing it didn't help, resetting decisions didn't help, reinstalling the extension didn't help.
It seems with newer VSCode versions ESLint doesn't respect `.eslintrc.json` in the root directory for some reason. 
VSCode version: 1.52.0
Node: 12
ESLint version: 2.1.14

**Comment by dbaeumer** [comment]
@mvirbicianskas can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by mvirbicianskas** [comment]
hey @dbaeumer apologies, should've started with that, here's public library I just created https://github.com/mvirbicianskas/Eslint Not sure whether it's correct approach to share such stuff?

**Comment by dbaeumer** [comment]
@mvirbicianskas this works for me as expected

<img width="731" alt="capture" src="https://user-images.githubusercontent.com/1931590/102206153-727d5900-3ecc-11eb-8f55-7aaa5755440e.png">

**Comment by mvirbicianskas** [comment]
@dbaeumer this is weird, I've restarted the editor multiple times and it didn't work, after now, after quitting - it started working ¯\_(ツ)_/¯ except for my project is still not working 😂  but apparently this is not extension's issue.
Sorry for bothering 🙏

**Comment by Friksel** [comment]
> The working directory setting is usually necessary if you have a multi project repository with different configs per folder.

I don't have a multi-project repository. And so don't have different configs per folder. As said, the config was working fine before for years. Without that setting.

> It is hard to say why this is not working for you unless I get a GitHub repository I can look at. If you can share your project could you distil a reproducible case.

As I wrote before I never send projects. And it shouldn't be necesary to debug this issue.

**Comment by dbaeumer** [comment]
The working directory setting you use is basically a noop since using the workspace root is the default. An example on how this setting is supposed to be used is here: https://github.com/microsoft/vscode-eslint#settings-options look for the bullet about `eslint.workingDirectories`.

Since ESLint depends on so many parameters (version, plugins, configuration files, package.json entries, and eventually webpack configuration and TS configuration files) debugging this does from my experience require an example. Otherwise it is very unlikely that we ever talk about the same setup.

If you can't share your repository publicly you can add my GitHub id to it and I will receive a notification on how to clone it.

**Comment by Friksel** [comment]
> The working directory setting you use is basically a noop since using the workspace root is the default. 

Why then did you give this advise in the first place? Come on man, read my posts before advising.

> Since ESLint depends on so many parameters (version, plugins, configuration files, package.json entries, and eventually webpack configuration and TS configuration files) debugging this does from my experience require an example. Otherwise it is very unlikely that we ever talk about the same setup.

A good developer knows what questions to ask. Requesting a full project from a user to debug an issue in your own extension is pretty lame to me.

Several times I now asked you to ask questions so I can help you, but you refuse to ask these questions. You obviously don't want to help. I quit helping you debugging the issues in your extension now. You obviously don't want to fix this nor recognise this issue.

**Comment by mvirbicianskas** [comment]
whoa there, @Friksel chill dude. I don't think you're being asked to provide full project repo. See my example above - try to reproduce the issue in a separate repository with as minimal configuration as possible and if it happens that it's really a bug inside the extension you will have to share that minimal reproduced repo here.

**Comment by dbaeumer** [comment]
@mvirbicianskas thanks for jumping in. You are correct I don't need the full repository, a distilled version is enough which I tried to point out in this comment https://github.com/microsoft/vscode-eslint/issues/1136#issuecomment-744681195 via

> could you distil a reproducible case.

This is also documented in our issue guidlines: https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests

@Friksel ESlint and most of its plugins and configurations resolve files relative to a current working directory. So if ESLint can't find certain files than in many cases the current working directory is not correct. The setting I pointed you too gives you control over the working directory the eslint server is using when validating certain files.

**Comment by Friksel** [comment]
@dbaeumer Doing more testing the issue has to do with the latest version of the Eslint package which was released 12 days ago (or something that stopped working with that version) in combination of npm vs pnpm and the vscode-eslint extension. 

When downgrading to an earlier version, I just tested 7.11.0 up to right before 7.14.0, so right before the latest version 7.15.0 (updates also automatically update the packages `eslint-config-airbnb-base` and `eslint-plugin-import` with pnpm) the vscode-eslint extension is working fine again. But when upgrading to 7.15.0 again after that it's broke again and visa versa.

Before I never had set the setting `"eslint.packageManager"`, but I just found out about that setting and set it to pnpm like so `"eslint.packageManager": "pnpm". But that doesn't make a difference, and as said, before it was working fine without setting it.

Looking at the change log of eslint 7.15.0 it doesn't seem to be a huge update though, so not sure what's causing this update to fail resolving while earlier versions where working fine.

I also notice that eslint 7.15.0 and the vscode-eslint extension DO work when moving the project completely from `pnpm` to `npm` instead. So if I completely remove the full `node_modules` folder and pnpm yaml (pnpm's alternative to the package.lock file) and re-install everything again, but with `npm` instead of `pnpm`, eslint and vscode-eslint work as expected and resolve fine even with eslint 7.15.0. But when after that I remove the `node_modules` folder again and install everything with `pnpm` again it cannot resolve the modules anymore and vscode-eslint throws the error that it cannot find the module `webpack\package.json` (which does exist btw; `node_modules\webpack (= symlink)\package.json`)

This is project dependent though, as all projects here DO work with pnpm and eslint@7.15.0 (and related packages)/ vscode-eslint, except for two projects where all packages have the same versions. And I even did a complete refreshed install with `pnpm install` after removing both the pnpm yaml-file and the node_modules folder.

I also ran a `Eslint: reset library execution decisions` to be absolutely sure vscode-eslint uses the locally installed eslint AND picks up the `pnpm` setting. And after executing that restarted VS Code just to be sure.

But none of this seem to help. The only thing that's directly comes into mind by comparing all projects that work and the two projects that don't is that the non-working projects use the package `svgo-sprite-loader` . But that shouldn't trigger any issue in a file that's not even using that module I'd say.

> @Friksel ESlint and most of its plugins and configurations resolve files relative to a current working directory. So if ESLint can't find certain files than in many cases the current working directory is not correct. The setting I pointed you too gives you control over the working directory the eslint server is using when validating certain files.

Yes, I know that by now. But the working directory IS okay and as I said many times now it always worked too and as you can see in this post it IS working when using NPM and it is even working in the project showing this issue (that was working for years) when switching eslint back to 7.14.0, so one version before the last update which happens to be released exactly 12 days ago.

**Comment by Friksel** [comment]
Alright. The issue didn't have anything to do with Eslint, nor everything related.

There is an issue in the latest version of the `svg-sprite-loader` node package; it's trying to execute some internal code to require 'webpack/package.json', but can't find it and so throws an error causing the full vscode-eslint process to stop by this error.
Changing the webpackVersion constant in that module by hand now fixes the issue.

Just found out there are more people with the same issue here:
https://github.com/JetBrains/svg-sprite-loader/issues/417

Not sure why vscode-eslint is more sensitive to this than direct command line eslint though, as that wasn't showing any error nor stopped the process, but at least found the issue now finally.

Sorry for all the inconvience. Closing this issue now.

**Comment by dbaeumer** [comment]
I am happy to hear that you could solve the issue.

**Comment by quoyi** [comment]
> Alright. The issue didn't have anything to do with Eslint, nor everything related.
> 
> There is an issue in the latest version of the `svg-sprite-loader` node package; it's trying to execute some internal code to require 'webpack/package.json', but can't find it and so throws an error causing the full vscode-eslint process to stop by this error.
> Changing the webpackVersion constant in that module by hand now fixes the issue.
> 
> Just found out there are more people with the same issue here:
> [JetBrains/svg-sprite-loader#417](https://github.com/JetBrains/svg-sprite-loader/issues/417)
> 
> Not sure why vscode-eslint is more sensitive to this than direct command line eslint though, as that wasn't showing any error nor stopped the process, but at least found the issue now finally.
> 
> Sorry for all the inconvience. Closing this issue now.

You are my hero! Thanks!
