### ISSUE TITLE
Cannot lint .eslintrc.json

### ISSUE THREAD

**Issue by datbth** [microsoft/vscode-eslint#1137]
## Problem
I'm using `eslint-plugin-json-format` to lint json files.  
The plugin is working fine when using `eslint` cli, and on vscode for json files that are **not** `.eslintrc.json`.  
So not sure if I'm missing something to make vscode-eslint lint `.eslintrc.json` as well?
## What I'm seeing
Output of `yarn eslint .`:  
![image](https://user-images.githubusercontent.com/15865062/101886212-c38c0500-3bcd-11eb-91c3-8742ed6ddcae.png)  
Vscode Problems tab:  
![image](https://user-images.githubusercontent.com/15865062/101886292-dbfc1f80-3bcd-11eb-82bb-d60c5026b8d1.png)
My Vscode settings.json part for eslint:  
```
    "eslint.alwaysShowStatus": true,
    "eslint.trace.server": "verbose",
    "eslint.nodePath": "/home/datbui/.nvm/versions/node/v12.16.1/bin/node",
    "eslint.packageManager": "yarn",
    "eslint.validate": [
        "vue",
        "html",
        "javascript",
        "typescript",
        "json"
    ],
    "eslint.onIgnoredFiles": "warn",
```
## Reproduce
https://github.com/datbth/vscode_eslint_json_format

**Comment by dbaeumer** [comment]
@datbth the problem is that the langauge id of `.eslintrc.json` file is `jsonc` sinc rc files support comments. Simply add `jsonc` to the validate list and it will work

**Comment by datbth** [comment]
I see. Thank you for your response
