### ISSUE TITLE
Schema validation fails in `ignorePatterns` that was added in eslint v7

### ISSUE THREAD

**Issue by sdalonzo** [microsoft/vscode-eslint#1139]
I have an `@scope/eslint-config` package published from our monorepo and I'm trying to consume it in a separate project.

ESLint works correctly when invoked via the CLI. However, in `vscode-eslint`, I get the following error:

```sh
[Error - 10:32:57 PM] ESLint stack trace:
[Error - 10:32:57 PM] Error: ESLint configuration in .eslintrc.js » @pcln/eslint-config is invalid:
	- Unexpected top-level property "ignorePatterns".
```

We use the `ignorePatterns` to exempt a list of folders by convention (build dirs, coverage reports, static storybooks, etc) in the `eslint-config` so that all of our projects don't need to maintain a list of all the standard ignores.

It seems like maybe the schema validator doesn't consider `ignorePatterns` as a valid member of the schema. Is there a way to override it?

Thanks for your time!

-steve

**Comment by dbaeumer** [comment]
@sdalonzo actually the extension doesn't do any schema validation by itself. It delegates everything to the eslint npm module. Since it is working in the terminal can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by elliottregan** [comment]
I also am having this issue. Command line works fine, VS Code throws an error. VS Code was fine with the syntax, and decided recently to stop working.

**Comment by patelrikin** [comment]
Check your eslint version, old eslint versions complain about this issue. Seems like `ignorePatterns` was added after v6
