### ISSUE TITLE
Option to disable error notifications

### ISSUE THREAD

**Issue by Jet132** [microsoft/vscode-eslint#1140]
Hello, I would like to suggest a setting that allows one to disable the error notifications.
Unfortunately, VSCode as far as I have found does not have good build-in notification controls, so an option like `Disable Error Notifications` would be nice to have. Else each time I edit a file with errors I get spammed with notifications that there was an error which is distracting.

**Comment by dbaeumer** [comment]
@Jet132 can you provide me with steps to reproduce this. Usually error notification should be rare and usually point to problems with the ESLint setup. Best would be a GitHub repository to clone.

**Comment by Jet132** [comment]
I can't seem to reproduce the issue right now though I haven't put that much time into it. It could be something with the configuration or the setup as the affected project used symlinks in windows (via `yarn link`) which also caused some other issues. I'll close this issue for now until it happens again and I can better investigate it.

**Comment by A9B8C7D6** [comment]
I would like this for LaTeX error notifications, since I know what the errors are there, I don't appreciate error popups constantly appearing on the side of my screen. I have the filename in red anyways, to let me know there's an error, the notification doesn't give me any additional information
