### ISSUE TITLE
Automatically detect package manager

### ISSUE THREAD

**Issue by nickmccurdy** [microsoft/vscode-eslint#1141]
Based on https://github.com/microsoft/vscode/issues/102050

VSCode now automatically detects the package manager by default and exposes the package manager (whether automatically discovered or manually specified in `npm.packageManager` setting) in the `npm.packageManager` command. As a result we can use the `npm.packageManager` command instead of our own `packageManager` setting.

There's a similar implementation in https://github.com/prettier/prettier-vscode/pull/1700, but this extension has a different architecture and I couldn't figure out how to access the package manager from the language server.

**Comment by dbaeumer** [comment]
The problem is a little that VS Code doesn't expose this as API so it needs to be re-implemented here.

**Comment by dbaeumer** [comment]
PR welcome.

**Comment by nickmccurdy** [comment]
> The problem is a little that VS Code doesn't expose this as API so it needs to be re-implemented here.

It actually does now.

```ts
await commands.executeCommand<"npm" | "pnpm" | "yarn">("npm.packageManager")
        ```

> PR welcome.

I tried to port https://github.com/prettier/prettier-vscode/pull/1700 to this repository but unfortunately `executeCommand` doesn't seem to be available in language servers. I have no idea how to edit a language server so I'd appreciate help with that, though anyone is also welcome to port the PR themselves as long as they add me as the `--author`.

**Comment by dbaeumer** [comment]
Nice, I didn't know this. 

For the PR: 

- we would need to deprecate the setting in ESLint
- when we resolve the configuration in the client code call the command and sent that result instead. https://github.com/microsoft/vscode-eslint/blob/master/client/src/extension.ts#L1435

**Comment by wilkinson4** [comment]
Any updates on this?

**Comment by dbaeumer** [comment]
PR still welcome :-)

**Comment by rotu** [comment]
I think this issue is finished and should be closed.

**Comment by dbaeumer** [comment]
@rotu  Correct! Thanks for pointing this out
