### ISSUE TITLE
Read rules from VS code's settings.json

### ISSUE THREAD

**Issue by haojun99** [microsoft/vscode-eslint#1142]
Can I put the rules (in .eslintrc.json) in VS code's settings.json? The reason is I have multiple machines and want the rules in sync across all machines. VS code's settings can be synced. If we can add the rules directly inside VS code's setting, the rules for eslint will also be in sync.

**Comment by dbaeumer** [comment]
No there is no support to store eslint configurations in the settings.json and there are no plans to add this support since ESLint itself has already a sophisticated settings story.
