### ISSUE TITLE
"Fix-on-Save" Produces Incorrect Output

### ISSUE THREAD

**Issue by SE2Dev** [microsoft/vscode-eslint#1143]
When enabling "fix on save", vscode-eslint appears to produce different results than it would if you were to explicitly run the "ESLint: Fix all auto-fixable problems" command. 

I've managed to correct this behavior by overriding the `mode` in (resolveSettings](https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1933) by forcing it to treat all fix requests as though they originated from the command.

By the time `resolveSettings` completes in the attached example, `"\n;\n"` is included in the results.

The attached example illustrates my point a bit better. Using the included workspace settings, saving `index.js` will produce a different result than if a user were to explicitly call "ESLint: Fix all auto-fixable problems" or run ESLint from the CLI.

Original Source

```js
const myconst = "hello"
const anothervar = 4
```

"ESLint: Fix all auto-fixable problems" output:
(eslint cli produces these same results)

```js
const myconst = "hello";
const anothervar = 4;

```

Fix on Save Output
```js
const myconst = "hello";
const anothervar = 4
;

```

I've also included `lint.js` which can be used to see what ESLint's raw message set is, as well as to see how ESLint's CLI resolves file edits (`apply_edits` is taken almost entirely directly from ESLint's CLI source).

[vscode-eslint-bug.tar.gz](https://github.com/microsoft/vscode-eslint/files/5718695/vscode-eslint-bug.tar.gz)

**Comment by dbaeumer** [comment]
@SE2Dev thanks for the great test case.

**Comment by SE2Dev** [comment]
@dbaeumer I just wanted to give a heads up. Although this issue was resolved in the 2.1.20 release, 2.1.25 appears to have a regression regarding this issue.

**Comment by dbaeumer** [comment]
@SE2Dev does the same test case reproduces it?

**Comment by SE2Dev** [comment]
Yep

**Comment by dbaeumer** [comment]
Can again reproduce. Thanks for reporting.
