### ISSUE TITLE
Constant dialogs

### ISSUE THREAD

**Issue by rhernandog** [microsoft/vscode-eslint#1146]
I'm working on a project with Vue and I keep getting this dialogs popping up whenever a validation problem comes up. The normal and expected behaviour is the error/warning underline in the particular code and the indication of the number of errors/warnings in the status bar, but this is new and quite annoying.

![eslint-dialogs](https://user-images.githubusercontent.com/4622323/102716769-ab4a7300-42bc-11eb-9016-6a8ecfdb5dab.gif)

As you can see, two more notifications come up as I delete the particular directive. Is worth noticing that it doesn't happen with all the directives, for example no error when writing an empty `v-model`.

I tried disabling prettier just in case and it keeps happening. Also tried with this setting: `"extensions.ignoreRecommendations": true` but it also keeps happening.

I'll try this with other projects and see if it happens as well.

Let me know if you want a sample repo for this.

**Comment by TheDutchCoder** [comment]
I hav this issue too, but less frequent.
Usually it starts when typing some unimported method like Vue's `ref` (it auto-imports obviously).

**Comment by dbaeumer** [comment]
@rhernandog what happens if you validate that file in the error state in the terminal. Do you see some kind of exception?

And can you please provide me with a GitHub repository I can clone that demos what you are experiencing. That I can reproduce this and can investigate as well.
