### ISSUE TITLE
"Parsing error: Debug Failure. Expected -1 >= 0" everytime a new file is created

### ISSUE THREAD

**Issue by almeidx** [microsoft/vscode-eslint#1148]
Everytime I create a new file on any project that uses ESLint, I get this error:
![](https://i.imgur.com/iMAPVHN.png)

This error then appears on all files until I restart vscode

<details>
<summary>Details</summary>

`devDependencies`:
```json
{
    "@typescript-eslint/eslint-plugin": "^4.11.0",
    "@typescript-eslint/parser": "^4.11.0",
    "eslint": "^7.7.0",
    "eslint-config-marine": "^7.2.0",
    "eslint-config-prettier": "^7.1.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-prettier": "^3.1.4"
}
```

`.eslintrc.js`
```js
/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable @typescript-eslint/no-require-imports */
const { join } = require('path');

module.exports = {
  extends: 'marine/prettier/node',
  parserOptions: {
    project: join(__dirname, './tsconfig.eslint.json'),
  },
  env: {
    es2021: true,
    node: true,
  },
  rules: {
    '@typescript-eslint/naming-convention': [
      'error',
      {
        format: ['PascalCase', 'UPPER_CASE', 'camelCase'],
        leadingUnderscore: 'allow',
        selector: 'variable',
      },
      {
        format: ['PascalCase'],
        leadingUnderscore: 'allow',
        selector: 'typeLike',
      },
      {
        format: ['camelCase'],
        leadingUnderscore: 'allow',
        selector: 'function',
      },
    ],
    '@typescript-eslint/no-extraneous-class': 0,
    '@typescript-eslint/no-non-null-assertion': 0,
    'no-implicit-coercion': 0,
    'no-negated-condition': 0,
    'prettier/prettier': [
      2,
      {
        printWidth: 120,
        useTabs: false,
        tabWidth: 2,
        singleQuote: true,
        quoteProps: 'as-needed',
        trailingComma: 'all',
        endOfLine: 'lf',
      },
    ],
  },
  ignorePatterns: ['packages/**/dist/*', 'packages/**/node_modules/*', 'node_modules/*'],
};
```

VSCode about page:
![](https://i.imgur.com/4jrQXDN.png)
</details>

**Comment by dbaeumer** [comment]
Actually it works for me so it is for sure related to some config or plugin configuration. Can you please provide me with a GitHub repository I can clone that demos what you are experiencing. This ensure I see the same setup in which you see the error.

**Comment by almeidx** [comment]
> Actually it works for me so it is for sure related to some config or plugin configuration. Can you please provide me with a GitHub repository I can clone that demos what you are experiencing. This ensure I see the same setup in which you see the error.

Unfortunately, I cannot, since apparently this error only happens on 2 specific projects (which are extremely similar, structure-wise), and both of them are not open source. However, I contacted a friend which also has access to one of the projects (told them exactly what to do, extensions, configuration) and the error does not happen on their side. 

Knowing this information, I uninstalled VSCode completely and installed VSCode Insiders. I simply installed the ESLint extension and, to my surprise, the error still appeared. I have tried removing a lot of code from one of the projects, and I couldn't find a consistent way to reproduce this error. And due to the vagueness of the error provided by the extension, I just couldn't find something useful to provide to you.

**Comment by almeidx** [comment]
And something I forgot to mention, by the time I created this issue, I have updated both projects and error stopped occurring, so I guess I will just close this.

**Comment by Srounsroun** [comment]
I just had this error, could be related to some CRLF and LF issue on files when switching branch.
I Execute this to make it clean : 
`git rm -rf --cached .`
`git reset --hard HEAD`

**Comment by lancejpollard** [comment]
I think VSCode just needs to be restarted every now and then for this error to resolve, at least that is how it was for me.

**Comment by Dodobrat** [comment]
I fixed it by doing the following steps:

1. Go to the command prompt: 
`Ctrl + Shift + p`     OR     `Cmd + Shift + p` for Mac

2. Type in 'restart' and select "ESLint: Restart ESLint Server"

That way you don't have to close and reopen VSCode

**Comment by matan44** [comment]
For me the only thing that worked was a new workspace
