### ISSUE TITLE
 Cannot read property 'loc' of undefined

### ISSUE THREAD

**Issue by zhongzhong0505** [microsoft/vscode-eslint#1149]
type const in ts file , output above error messages

[Error - 6:22:23 PM] ESLint stack trace:
[Error - 6:22:23 PM] TypeError: Cannot read property 'loc' of undefined
Occurred while linting /Users/xxx/xxx/test/unit/xxx/src/core/xxxx/xxx/cell/xxxx.spec.ts:1
    at Object.VariableDeclaration [as listener] (/Users/xxxx/xxx/node_modules/eslint/lib/rules/indent.js:1422:69)
    at /Users/xxx/xxx/node_modules/eslint/lib/rules/indent.js:1634:55
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/xxxx/xxx/node_modules/eslint/lib/rules/indent.js:1634:26)
    at /Users/xxxx/xxxx/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/xxxx/sheet/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/xxx/xxxx/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/xxx/xxx/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.leaveNode (/Users/xxxx/xxx/node_modules/eslint/lib/linter/node-event-generator.js:306:14)

![image](https://user-images.githubusercontent.com/15847574/103082543-4de45800-4615-11eb-88d2-982fb2181aaa.png)

**Comment by dbaeumer** [comment]
@zhongzhong0505 also surfaced via a dialog in the ESlint extension for VS Code this is caused by an exception in ESLint itself (the npm module). Could you please file an issue against ESLint itself (https://github.com/eslint/eslint). 

Let me know how it goes with that issue.

**Comment by zhongzhong0505** [comment]
> @zhongzhong0505 also surfaced via a dialog in the ESlint extension for VS Code this is caused by an exception in ESLint itself (the npm module). Could you please file an issue against ESLint itself (https://github.com/eslint/eslint).
> 
> Let me know how it goes with that issue.

ok, i already create issue in eslint repo.

**Comment by brandonwoz** [comment]
Also have this issue and posted on ESLint's git

**Comment by C-alcium** [comment]
For situations like this where we are waiting on a fix, is there an option to silence this toast inside Vscode? It pops up every time I type a character

**Comment by efeminella** [comment]
As @C-alcium had suggested, is there a configuration setting that can be used to suppress specific toasts, such as this one while a fix is pending?

**Comment by dbaeumer** [comment]
There is no setting in VS Code to filter those and adding code to ESLint seems wired especially since there is a easy fix for this. See https://github.com/eslint/eslint/issues/13957

**Comment by fuchunhui** [comment]
> There is no setting in VS Code to filter those and adding code to ESLint seems wired especially since there is a easy fix for this. See [eslint/eslint#13957](https://github.com/eslint/eslint/issues/13957)

it works. [@typescript-eslint/indent](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/indent.md)

```
{
  // note you must disable the base rule as it can report incorrect errors
   "indent": "off",
  "@typescript-eslint/indent": ["error"]
}
```
