### ISSUE TITLE
eslint setting option deprecated

### ISSUE THREAD

**Issue by juunone** [microsoft/vscode-eslint#1150]
hello, i have one question.
i have `.vscode/setting.json` with local project vscode settings.
but there is deprected option, it is `eslint.enable`
it has view warning with this messages.
`This setting is deprecated. Disable ESLint using the extensions viewlet.`

i use eslint extenstion with version `2.1.14`
is it ESLint extension version < 2.x, eslint.enable option was deprecated right?

**Comment by dbaeumer** [comment]
Instead of using the `eslint.enable` setting you can now enable / disable ESLint using the extensions viewlet. That is why the setting is deprecated. If you have set it to true simply remove it. If set to false disable the extension for the corresponding workspace folder which will have the same effect.

**Comment by AlexZeitler** [comment]
What is the "extensions viewlet"?

**Comment by dbaeumer** [comment]
This viewlet in VS Code
<img width="305" alt="capture" src="https://user-images.githubusercontent.com/1931590/105815367-16b9eb80-5fb3-11eb-918a-060aeb8660c9.png">

**Comment by AlexZeitler** [comment]
@dbaeumer Thanks!

**Comment by wjune211** [comment]
thanks!

**Comment by juunone** [comment]
thank you!

**Comment by mirko77** [comment]
I cannot disable/enable it on folder basis, how would I do that?

**Comment by dbaeumer** [comment]
Actually the extension management viewlet does currently not support this. The only options are to use the deprecated setting or have a different workspace file.

**Comment by devinrhode2** [comment]
I am migrating one of our companies projects to XO, which has it's own vscode extension.

Inside the new XO project, I am adding `"eslint.enable": false,` to our projects `.vscode/settings.json` file.

If `eslint.enable` was removed, we could get the same end result if there was a [`eslint.requireConfig` option](https://github.com/microsoft/vscode-eslint/issues/1194#issue-822929076)

**Comment by dbaeumer** [comment]
I undepreciated `eslint.enable`
