### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by andig** [microsoft/vscode-eslint#1153]
Having vscode-eslint installed kills the macbook's battery:

<img width="1280" alt="Screenshot 2021-01-03 at 16 20 33" src="https://user-images.githubusercontent.com/184815/103482181-a10d9600-4ddf-11eb-883f-6b9022023705.png">

These are the relevant eslint settings:

    "editor.codeActionsOnSave": {
        "source.organizeImports.eslint": true,
        "source.fixAll.eslint": true
    },
    "eslint.validate": [
        "javascript"
    ],
    "eslint.format.enable": true

I'm wondering if I need to specifically exclude `node_modules` in the eslint config?

**Comment by dbaeumer** [comment]
@andig this is very likely caused by a problem in ESLint or one of its plugins which are used to compute the fixes. Can you please provide me with a GitHub repository I can clone that demos what you are experiencing. Otherwise it is impossible to tell what is going on.

**Comment by andig** [comment]
What might help is if there was some output showing what jobs are running plus their elapsed runtime. At least thats what e.g. gopls does. Gonna close here- has not happend again since.

**Comment by dbaeumer** [comment]
@andig: you can do that. Use the setting `eslint.debug=true`
