### ISSUE TITLE
Improve documentation on configuration option eslint.validate

### ISSUE THREAD

**Issue by some-user123** [microsoft/vscode-eslint#1159]
At the moment the docs regarding `eslint.validate` say:

> This is an old legacy setting and should in normal cases not be necessary anymore. Defaults to `["javascript", "javascriptreact"].`

In my case, typescript files are not linted in VSCode if I don't specify this explicitely in `eslint.validate`. I'm wondering if this is already a "non-normal case". Could this be specified in more detail in which cases `validate` is not needed ("normal cases") and when it is needed?

**Comment by dbaeumer** [comment]
@some-user123 validation of TypeScript files should happen automatically if ESLint is configured correctly. Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by some-user123** [comment]
Sure, please find the repo here: https://github.com/some-user123/vscode-eslint-issue-1159

`yarn lint` will complain about `test.ts`. In VSCode I don't see any error, unless I add a `.vscode/settings.json` with
```json
{
  "eslint.validate": ["typescript"]
}
```

Also noticeable: If I remove this `settings.json` linting in VSCode still works -- until the next restart.

**Comment by some-user123** [comment]
Is the provided information sufficient? Do you need anything else?

**Comment by dbaeumer** [comment]
@some-user123 missed it. I will have a look.

**Comment by dbaeumer** [comment]
I tried to use the repository but it doesn't work. The repository depends on many node modules that seem to be gloablly installed on your system (e.g. typescript, eslint-plugin-vue, @vue/typescript/recommended). Can you please provide me with a repository that is self contained otherwise it is very hard to tell why things aren't working (we might use different versions of the modules)

**Comment by some-user123** [comment]
Thanks for looking into it.

I don't have globally installed modules except npm and yarn. Typescript is referenced in `app1/package.json`. I should have pointed out more clearly that the repo uses yarn workspaces. 

Steps to reproduce:
- `git clone ...`
- `yarn install --frozen-lockfile`
- `yarn lint`
```
$ yarn lint
yarn run v1.22.10
$ eslint "**/*.{ts,tsx,js,jsx,vue}"

...\vscode-eslint-issue-1159\app1\test.ts
  1:1   warning  Unexpected console statement                        no-console
  1:13  warning  Replace `"Am·I·linted?")⏎` with `'Am·I·linted?');`  prettier/prettier

✖ 2 problems (0 errors, 2 warnings)
  0 errors and 1 warning potentially fixable with the `--fix` option.

Done in 3.48s.
```

- Open folder in VSCode, open `app1/test.ts`.

![image](https://user-images.githubusercontent.com/74715856/107767239-fae57200-6d34-11eb-97e0-51be7fdc4ee5.png)

**Comment by dbaeumer** [comment]
Hve you tried `eslint.workingDirectories`. In setups with multiple project folders ESLint needs to know the working directories. A good indication for the setting is also that validating in a terminal requires a `cd` to work.

**Comment by dbaeumer** [comment]
The validate setting got un-deprecated a while back.
