### ISSUE TITLE
No ESLint configuration found for /snap/code/[...]/node_modules/typescript/lib/lib.esnext.intl.d.ts

### ISSUE THREAD

**Issue by Doeke** [microsoft/vscode-eslint#1160]
No errors/warnings with running eslint on the project directory, but In the VSCode ESLint output I get following warning spammed after a few seconds:

[Warn  - 1:02:57 AM] 
No ESLint configuration (e.g .eslintrc) found for file: /snap/code/52/usr/share/code/resources/app/extensions/node_modules/typescript/lib/lib.esnext.intl.d.ts
File will not be validated. Alternatively you can disable ESLint by executing the 'Disable ESLint' command.

Are node_modules not supposed to be ignored by eslint?
I tried adding node_modules to files.exclude setting but it made no difference.

In addition to this warning I also got error notifications for missing eslint config to extend from inside a package in node_modules in my project folder, which I solved by installing the internal package that included said config.

I checked and none of these problems are present when using eslint client directly, for some reason VSCode ESLint extension is sending files found in node_modules to be checked by eslint. I think it's actually checking all files in node_modules both in the vscode installation and in my project, which is making the extension is run sluggish for me as well.

VSCode eslint: 2.1.14
Node: 15.5.1
ESLint: 7.17.0

**Comment by dbaeumer** [comment]
@Doeke  does the validation happen correctly when you use eslint in the terminal from the worspace folder root. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Doeke** [comment]
@dbaeumer Yes, validation in terminal works as expected (no errors)

Here's a repo: https://github.com/Doeke/vscode-eslint-bug/tree/master

I installed VS Code with snap, if that matters.

**Comment by dbaeumer** [comment]
This fails for me with a different error message:

<img width="612" alt="capture" src="https://user-images.githubusercontent.com/1931590/105681262-31c42700-5ef1-11eb-95cf-61aa6eb3bf5c.png">

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
