### ISSUE TITLE
Support static configuration options which are evaluated on server start and hence can be relative.

### ISSUE THREAD

**Issue by mingluzhang** [microsoft/vscode-eslint#1165]
The folder structure of the project is like this,

/Src
----.eslintrc.js
----package.json
----/node_modules
----tsconfig.json
/Core

I'd like to use /Src/.eslintrc.js in both /Src and /Core. 
But currently only errors in /Src can be found.
What settings should I set in VSCode to achieve my goal?

**Comment by dbaeumer** [comment]
@mingluzhang  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by mingluzhang** [comment]
You can repro this issue from [this repo](https://github.com/mingluzhang/eslint-trouble-shoot). Thanks.

**Comment by dbaeumer** [comment]
@mingluzhang Thanks

Can you please provide me with the command line (e.g. calling eslint directly) that makes it validate. I notice that you only have a `.eslintrc.js` in projects. When validating core you need to let the extension know that it should use the `.eslintrc.js` from project. You can do this using the `eslint.options` setting. Something like `"eslint.options.configFile": "path to the config file"`

**Comment by mingluzhang** [comment]
Actually I would use the command,
`cd ../Core
eslint -c "../Project/.eslintrc.js" --ext ts --ext tsx .`

**Comment by mingluzhang** [comment]
You can ref the script of "npm run test" which defined in file of /Project/package.json

**Comment by mingluzhang** [comment]
> @mingluzhang Thanks
> 
> Can you please provide me with the command line (e.g. calling eslint directly) that makes it validate. I notice that you only have a `.eslintrc.js` in projects. When validating core you need to let the extension know that it should use the `.eslintrc.js` from project. You can do this using the `eslint.options` setting. Something like `"eslint.options.configFile": "path to the config file"`

I think I have tried to add `"eslint.options.configFile": "{$workingdirectory}/.eslintrc.js" but still had no effect on files in /Core.
Could you please try to confirm that for me? Thanks a lot!

**Comment by dbaeumer** [comment]
You can't use varaibles like `${workingdirectory}` in settings since there is no support in VS Code for it. So you can only use a full path right now. Alternatively you can create a symlink from Code to project if you want to ensure that you only have one content.

**Comment by mingluzhang** [comment]
> You can't use varaibles like `${workingdirectory}` in settings since there is no support in VS Code for it. So you can only use a full path right now. Alternatively you can create a symlink from Code to project if you want to ensure that you only have one content.

How to make the symlink? Could you please provide one complete example config based on my repo which can cover both /Core and /Project?

**Comment by dbaeumer** [comment]
Sym links are a OS concept. From the path separator you are using it seems that you are on Linux / Mac. Then `ln -s` is your friend. 

In the `Core` directory run `ln -s ../Project/.eslintrc.js .eslintrc.js`

**Comment by mingluzhang** [comment]
> Sym links are a OS concept. From the path separator you are using it seems that you are on Linux / Mac. Then `ln -s` is your friend.
> 
> In the `Core` directory run `ln -s ../Project/.eslintrc.js .eslintrc.js`

No, but I'm on the Windows platform.

**Comment by mingluzhang** [comment]
> You can't use varaibles like `${workingdirectory}` in settings since there is no support in VS Code for it. So you can only use a full path right now. Alternatively you can create a symlink from Code to project if you want to ensure that you only have one content.

Base on the repo which used to reproduce the issue, could you please provide an example of the config which can make /Core be covered as well?

**Comment by dbaeumer** [comment]
I can't since the setup depends on your folder structure. Assuming that the workspace folder is under `C:\Users\mingluzhang\projects` the setting's value is `C:/Users/mingluzhang/projects/eslint-trouble-shoot/Project/.eslintrc.js`.

The command to create links under Windows is `mklink`.

**Comment by mingluzhang** [comment]
> I can't since the setup depends on your folder structure. Assuming that the workspace folder is under `C:\Users\mingluzhang\projects` the setting's value is `C:/Users/mingluzhang/projects/eslint-trouble-shoot/Project/.eslintrc.js`.
> 
> The command to create links under Windows is `mklink`.

Actually after using "mklink /d" to create a new link of /Core in /Project, vscode-eslint can find errors from the path of /Project/Core, but can't from the path of /Core.
I think it partially solved this issue.

**Comment by mingluzhang** [comment]
> > I can't since the setup depends on your folder structure. Assuming that the workspace folder is under `C:\Users\mingluzhang\projects` the setting's value is `C:/Users/mingluzhang/projects/eslint-trouble-shoot/Project/.eslintrc.js`.
> > The command to create links under Windows is `mklink`.
> 
> * After using "mklink /d" to create a new link of /Core in /Project, vscode-eslint can find errors from the path of /Project/Core, but can't from the path of /Core.
> * If not create new link of /Core, set `eslint.options.configFile = C:/RoyZhang/eslint-trouble-shoot/Client/Project/.eslintrc.js` which is the absolute path of eslint config, vscode-eslint can find errors from both /Core and /Project.

@dbaeumer I wonder do you have the plan to support relative path in `eslint.options.configFile`?

**Comment by dbaeumer** [comment]
@mingluzhang relative path are complicated since the eslint server is kept alive for validating n files and therefore the current working directory of the server changes to accommodate different files. We would need a `eslint.staticOptions`  section that is evaluated only once on server startup.

**Comment by mingluzhang** [comment]
Thanks for your explanation, and your advices to solve this problem.

**Comment by mingluzhang** [comment]
Hope to see the feature release asap. 👍

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
