### ISSUE TITLE
vscode-eslint only validating open file not entire project

### ISSUE THREAD

**Issue by simkessy** [microsoft/vscode-eslint#1166]
I only get eslint validation on the active file and not the entire project which makes it challenging to find all errors. 

Is it possible to get all the files validated?

**Comment by dbaeumer** [comment]
There is a VS Code task you can run to validate all files. This isn't done automatically since ESLint doesn't support incremental linting and linting all files in a project can take quite some time. See the setting `eslint.lintTask`.
