### ISSUE TITLE
Eslint Not Working - Not Showing in status bar though always show is set to enable

### ISSUE THREAD

**Issue by LP-Codes** [microsoft/vscode-eslint#1171]
Issue Type: <b>Bug</b>

ESLint is not running because the deprecated setting 'eslint.enable' is set to false. Remove the setting and use the extension disablement feature.
Though- setting has been set to true 

Extension version: 2.1.14
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.63GB (1.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@LP-Codes can you please provide me with a GitHub repository I can clone that demos this. Did you disable the extension in the extension viewlet?

**Comment by LP-Codes** [comment]
@ dbaeumer  thanks for checking out FYI after fresh install the issue was resolved it seems user & workspace settings were conflicting
