### ISSUE TITLE
`Enable|Disable ESLint for this Workspace` commands not available

### ISSUE THREAD

**Issue by marcelbeumer** [microsoft/vscode-eslint#1172]
Hi, thanks for the great work on vscode-eslint!

The README says there should be two commands

```
Disable ESLint for this Workspace: disables ESLint extension for this workspace.
Enable ESLint for this Workspace: enable ESLint extension for this workspace.
```

But they are not available in vscode. Using latest everything: vscode 1.52.1 and vscode-eslint 2.1.14

I turn on/off the plugin regularly because of how slow eslint becomes with the modern complex TS linting rules. I now do that through the extensions panel, but would be great to have those commands.

Thanks in advance

**Comment by dbaeumer** [comment]
@marcelbeumer actually the commands got removed in favour of the Extension Panel to have a consistent experience. I will update the documentation.
