### ISSUE TITLE
Not linting json files in VS Code

### ISSUE THREAD

**Issue by fractionalJoe** [microsoft/vscode-eslint#1173]
Linting works when running the command `npx eslint **/*`. These issues show up for my TS files but not for my JSON files, even though there are a lot of issues in my JSON files.

.eslintrc.json
```javascript
{
    "env": {
        "es2021": true,
        "node": true
    },
    "extends": [
        "google",
        "eslint:recommended"
    ],
    "ignorePatterns": [
        "build/**"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
        "quotes": [
            "error",
            "double",
            {
                "avoidEscape": true
            }
        ]
    }
}
```

**Comment by dbaeumer** [comment]
@fractionalJoe since this can depend on a lot of different things can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by fractionalJoe** [comment]
@dbaeumer https://gitlab.com/fractionalJoe/demo-eslint. Thanks for looking into this!

**Comment by dbaeumer** [comment]
Which json file in your repository do you want to see linted. 

I also noticed that you haven't installed any plugin to lint JSON files. ESLint out of the box doesn't lint JSON. You need a plugin like `eslint-plugin-json`

**Comment by fractionalJoe** [comment]
Thank you! I didn't realize that plugin was needed. I was able to remove my overrides for JSON. I've changed the indent in the package.json file so that it doesn't conform (rule expects 2 but I have it set at 4). But the eslint cli command isn't catching this either, so it's not an issue with this extension. This can be closed, but if you could point me in the right direction I would be grateful.

**Comment by dbaeumer** [comment]
Thanks for getting back. Closing then.
