### ISSUE TITLE
eslint can not work，this is my logs.

### ISSUE THREAD

**Issue by zhuijing** [microsoft/vscode-eslint#1177]
![image](https://user-images.githubusercontent.com/25924193/107138836-d878e080-6951-11eb-82f6-7c28f32a03b6.png)

**Comment by dbaeumer** [comment]
@newBird01 does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
