### ISSUE TITLE
[QUESTION] `.eslintrc.json` vs `.eslintrc.yml`

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode-eslint#1178]
Similar to #76.

I'm just wondering here why this plugin doesn't show autocomplete for rules in `.eslint.yml`? It's not a big deal for me, but I'd like to know what is preferable format and which one should I use: `.eslintrc.json` or `.eslintrc.yml`?

<details>
<summary>.json autocomplete screenshot</summary>

![image](https://user-images.githubusercontent.com/46503702/107233057-34fffc80-6a33-11eb-9bda-32752d9cef28.png)

</details>

**Comment by zardoy** [comment]
@dbaeumer

**Comment by dbaeumer** [comment]
It is up to you to decide. VS Code ships with a JSON language pack this is why you get code complete. VS Code doesn't ship with a YML language pack so there is no smartness in YML files.
