### ISSUE TITLE
Getting error "Unterminated string literal" when using strings in jsx.

### ISSUE THREAD

**Issue by m-garg** [Microsoft/vscode-eslint#118]
When using multiple class names, we need to push the few class names to the new line; but the plugin gives an error saying  "Unterminated string literal". Linting of all other JSX/react specific code is being done without any problem.

<div className="class1 class2 class3

class4 class5 class6

class7 class8">

Will get an error at end of class3 and class6 - "Unterminated string literal".

`OS Version`: OS X El Capitan
`vscode version`: 1.4.0
`plugin version`: 0.10.18
`eslint -v`: v3.3.1
 
PS: When I run eslint through command line, it doesn't give error for this case.

**Comment by dbaeumer** [comment]
@m-garg what prefix does the error show [js] or [eslint]. I suspect that this error doesn't come from eslint since in strict js talk this is not allowed in js and jsx files.

**Comment by m-garg** [comment]
@dbaeumer The prefix is [js]. Ok, so the fix would be to disable the javascript validation?
