### ISSUE TITLE
ESLint not working in some components in React

### ISSUE THREAD

**Issue by oguru** [microsoft/vscode-eslint#1180]
Hi

I've been having issues with ESLint. It seemed to work fine in an older project but i think it's even broken in that now. I've managed to get it working in at least 1 component in a React project, but it doesn't on another in the same directory heirarchy (at least not with the rules i've added - the default create-react-app linting works).

I made the project with create-react-app. In my package.json I have:

```
"eslintConfig": {
  "extends": [
    "react-app",
    "react-app/jest",
    "shared-config"
  ]
},
```

and `"lint:fix": "eslint src/**/*.js --fix"` under scripts.

In my eslintrc.json I have:

```
"plugins": [
  "react"
],
"settings": {
  "react": {
    "version": "detect"
        }
    },
"parserOptions": {
  "ecmaVersion": 6,
  "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
        }
    },
"extends": [
  "plugin:react/recommended"
],
"env": {
  "browser": true,
  "node": true,
  "commonjs": true,
  "es6": true
}
```

and then all my custom rules after.

It is the default formatter in my settings and i have the VSCode plugin installed. Rules in my settings.json are:

```
"eslint.alwaysShowStatus": true,
"eslint.format.enable": true,
"eslint.runtime": "",
"editor.defaultFormatter": "dbaeumer.vscode-eslint",
"eslint.codeAction.showDocumentation": {        
  "enable": true
},
"eslint.packageManager": "yarn",
"eslint.workingDirectories": [
        {"pattern": "./*/"}
   ],
```

I added this too as it fixed issues for someone else but it didn't work for me:

```
"eslint.validate": [
  "vue",
  "html",
  "javascript",
  "typescript",
  "javascriptreact",
  "typescriptreact"
]
```,

I went through every rule to get it how i like it because i use it as my code formatter too as i don't like opinionated ones like prettier.

Every other code formatter i've installed since i've had these problems (as far as i can remember) also doesn't work. The component that it doesn't seem to be working in is showing 1 error which i think is coming from the original settings from create-react-app.

Can anyone see any obvious issues? I'd be incredibly grateful if anyone can help as this has been driving me crazy for a while!

Thanks

**Comment by dbaeumer** [comment]
@oguru does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by oguru** [comment]
@dbaeumer I'd not used the terminal for ESLint before but it was working so after some further investigation I found that I was extending things that didn't exist which seemed to have been causing the issue, so it's all good now. Sorry for messing you around!
