### ISSUE TITLE
ESLint can't detect Babel config if @babel/eslint-parser is used as parser  

### ISSUE THREAD

**Issue by Suntechnick** [microsoft/vscode-eslint#1181]
package.json dependencies:
```
    "@babel/eslint-parser": "^7.12.16",
    "eslint": "^7.19.0"
```

.eslintrc
```
{
  "root": true,
  "env": {
    "browser": true,
    "node": true
  },
  "parser": "@babel/eslint-parser"
}
```

Babel config is located on the root of my project, same as .eslintrc:
![Screenshot 2021-02-12 at 16 59 06](https://user-images.githubusercontent.com/30172623/107784029-a4d3f700-6d53-11eb-92b4-185a1807351a.png)

But vscode-eslint can't seem to detect babel config:
![Screenshot 2021-02-12 at 16 56 01](https://user-images.githubusercontent.com/30172623/107784093-ba492100-6d53-11eb-8da8-65fb44d4b02f.png)

Project itself is building and linting fine via command line, so I assume this issue is related to vscode-eslint.
I also tried to specify exact path to babel config in .eslintrc but still had no success.

Thank you for help!

**Comment by Suntechnick** [comment]
It seems this problem is with my configuration of eslint. Sorry.

**Comment by JonFranchi** [comment]
I'm experiencing this same issue @Suntechnick , so I'm curious what your issue was.  I am using `babel.config.js` and upgraded to use `@babel/eslint-parser` and now VScode lint rules seem broken.  

I'm having no issues with Babel or ESlint anywhere else, but VScode-eslint seems to think it's broken with a `no babel config file detected...` error.

**Comment by sgtpenguin** [comment]
In my case, a wordpress project, the babelrc file was kept in the theme, which is not the root directory of the repo.  VSCode needs to know which directories to look for, so something like this can be added to workspace config in `.vscode/settings.json`

```
{
  "eslint.workingDirectories": [
    "./wp-content/themes/my-theme"
  ]
}
```
