### ISSUE TITLE
Autofix is different from format on save

### ISSUE THREAD

**Issue by mariusrak** [microsoft/vscode-eslint#1183]
Running `ESLint: Fix all auto-fixable Problems`  formats code differently that it is done on format on save. 
Exactly in
```js
render () {
  ...
}
```
is difference with space before parenthesis. On fix it is added, on save it is removed and error appears.

**Comment by dbaeumer** [comment]
Are you sure that you use eslint for format on save and not the built in TS/JS formatter. You need to configure this using 

```
	"editor.codeActionsOnSave": {
		"source.fixAll.eslint": true
	}
```

**Comment by mariusrak** [comment]
Yes, I have this in my settings.

**Comment by dbaeumer** [comment]
One thing the extension does is to reuse fixes from previous linter runs. Since they can overlap some of the fixes might be dropped. You can force the extension to re-compute the fixes on save (which slows down save) using the setting `"eslint.codeActionsOnSave.mode": "all"`. If this doesn't help  can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by mariusrak** [comment]
I have this setting also. It'd be difficult to share a repo. But am I only one who experience this discrepancy?

**Comment by dbaeumer** [comment]
Open once yes. I had a handful of those issues in the past but they got resolved. Is your source on GitHub. You could invite me to the repository only giving me read access.

**Comment by mariusrak** [comment]
The repo is under NDA so I cannot share it. But maybe would help that I'm running VSCode with remote connection on WSL2 Ubuntu 20.04 and here's my `.eslintrc.json`:
```
{
  "env": {
    "browser": true,
    "es6": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "standard-react",
    "standard",
    "plugin:json/recommended"
  ],
  "globals": {
    "server": false,
    "browser": false,
    "expect": false,
    "Globals": true
  },
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 11,
    "sourceType": "module"
  },
  "plugins": [
    "react",
    "json"
  ],
  "rules": {
    "jsx-quotes": ["error", "prefer-single"],
    "react/jsx-handler-names": 0,
    "react/display-name": 0,
    "import/no-unresolved": 0,
    "import/no-absolute-path": 0,
    "no-underscore-dangle": [
      "error",
      {
        "allow": [
          "_id",
          "_ensureIndex",
          "_verifyEmailToken",
          "_resetPasswordToken",
          "_name",
          "_schema"
        ]
      }
    ],
    "react/prop-types": 0
  }
}
```
and my `.editorconfig`:
```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

```

**Comment by mariusrak** [comment]
I have also noticed, that when I create a new file and pres format (Shift+Alt+F) it will ignore .eslintrc.json and format it with 8 spaces instead of configured 2.

**Comment by dbaeumer** [comment]
I am pretty sure that this has nothing to do with WSL2 since I am a heavy user of it as well :-)

Unfortunately something like this depends on a lot of things (eslint version, install plugins, config files, settings) so without steps on how to reproduce this it is very hard to track down. Could you distill a small test repository?

**Comment by mariusrak** [comment]
I just had to set it up one more time, but through GUI.
Right click on document > Format Document With > ESLint
I don't understand why it ignored my settings, but it works now.
Thanks for your time.

**Comment by dbaeumer** [comment]
No problem.
