### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Murad-Git** [microsoft/vscode-eslint#1184]
- Issue Type: `Performance`
- Extension Name: `vscode-eslint`
- Extension Version: `2.1.14`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MISHMU~1\AppData\Local\Temp\dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by dbaeumer** [comment]
@Murad-Git can you please attach the referenced profile (e.g. `c:\Users\MISHMU~1\AppData\Local\Temp\dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt`)

**Comment by matzeeable** [comment]
Hi @dbaeumer !

I am experiencing the same issues with high CPU load even without doing anything.

![image](https://user-images.githubusercontent.com/1008534/111327498-ba4b8200-866d-11eb-882c-636a2a1fd91e.png)

Where do I find the CPU profile on my Linux machine? I need also mention that I am using the Remote SSH extension of VSCode, but I never had this issue two weeks ago.

Regards,
Matthew 😊

**Comment by dbaeumer** [comment]
@matzeeable your issue is different from @Murad-Git since you are effect by a high CPU load of the server. 

To understand what is happening can you provide me with steps on how to reproduce this best by giving me a GitHub repository I can clone?

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by matzeeable** [comment]
@dbaeumer FYI:  The issue was caused by a `sudo sysctl fs.aio-max-nr` modification. I have done this modification because I needed to run multiple MySQL databases on my system ([source](https://stackoverflow.com/a/45598111/5506547)). I do not know if this helps someone, but perhaps you have changed this in the past, too.
