### ISSUE TITLE
Extension cannot parse file under @tests directory

### ISSUE THREAD

**Issue by Fr33maan** [microsoft/vscode-eslint#1185]
If I rename that directory `@test` or `@tests`, then it's working. 

`Generating fixed text for /home/freeman/dev/app/src/screens/settings/account/@testss/unit/CancelSubscription.cmp.test.tsx`

`Generating fixed text for /home/freeman/dev/app/src/screens/settings/account/@test/unit/CancelSubscription.cmp.test.tsx`

But with a directory named `@tests` I got:

`Extension 'ESLint' cannot format 'src/screens/settings/account/@tests/unit/CancelSubscription.cmp.test.tsx'`

No logs in the VSCode output while extension is in debug mode. 

Maybe something about VSCode ?

**Comment by dbaeumer** [comment]
Need to investigate. How are you triggering format. Via keyboard or on save automatically.

**Comment by Fr33maan** [comment]
Both: Save or Ctrl + Shift + I
Saving the file does not even display the message.
Only when keyboarding

**Comment by dbaeumer** [comment]
OK. Thanks.

**Comment by Fr33maan** [comment]
@dbaeumer I just discovered that everything under a `lib` directory will be ignored too.
message is:
"File ignored because of a matching ignore pattern. Use "--no-ignore" to override.eslint"

Not sure how to add this param to the runner of the extension

**Comment by dbaeumer** [comment]
Do you have a `.eslintignore` file?

**Comment by Fr33maan** [comment]
omg Im so sorry bro. I indeed have it and lib is inside.
My bad for that time waste.

**Comment by Fr33maan** [comment]
`.eslintignore` file content

```
src/lib/**/*
**/__mocks__/**/*
**/@tests/**/*
```

**Comment by dbaeumer** [comment]
No problem. Stuff like that happens :-)
