### ISSUE TITLE
Unexpected token in Angular HTML (prettier rule)

### ISSUE THREAD

**Issue by snebjorn** [microsoft/vscode-eslint#1186]
I'm getting errors reported in my Angular HTML

I've applied the workaround mentioned in #929 for getting linting squiggles in the HTML.

**What version of `eslint` are you using?**
7.20.0

**What version of `prettier` are you using?**
2.2.1

**What version of `eslint-plugin-prettier` are you using?**
3.3.0

**What version of `vscode-eslint` are you using?**
> Name: ESLint
> Id: dbaeumer.vscode-eslint
> Description: Integrates ESLint JavaScript into VS Code.
> Version: 2.1.14
> Publisher: Dirk Baeumer
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

Actually it's pretty hard to tell that this is the correct repo for that extension :)

**What version of VSCode are you using?**
> Version: 1.53.2 (user setup)
> Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
> Date: 2021-02-11T11:48:04.245Z
> Electron: 11.2.1
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19041

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```jsonc
// .eslintrc.json
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "overrides": [
    {
      "files": ["*.html"],
      "extends": [
        "plugin:@angular-eslint/template/recommended",
        "plugin:prettier/recommended"
      ]
    }
  ]
}
```

**What source code are you linting?**
Angular HTML

![image](https://user-images.githubusercontent.com/1266245/108503113-211a8d00-72b4-11eb-9fc0-05cc9d75695c.png)

I tried fixing it with a prettier override as suggested here https://dev.to/gsarciotto/migrating-and-configuring-eslint-with-angular-11-3fg1
```json
// .prettierrc
{
    "overrides": [
        {
            "files": "*.html",
            "options": {
                "parser": "angular"
            }
        }
    ]
}
```
That fixed the errors when running ESLint from the commandline via `ng lint`
But they still show up in the editor.

**What did you expect to happen?**
No error

**What actually happened?**
This error is shown
> Parsing error: Unexpected token eslintprettier/prettier)

**Comment by snebjorn** [comment]
I got this working. Don't remember what made it work. I just tried all the things.

**Comment by jedihacks** [comment]
Had the same issue, and fixed it by removing the 2nd plugin under extends for the HTML files only

`{
      "files": ["*.html"],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ]
    }`

**Comment by fomenkogregory** [comment]
> Had the same issue, and fixed it by removing the 2nd plugin under extends for the HTML files only
> 
> `{ "files": ["*.html"], "extends": [ "plugin:@angular-eslint/template/recommended" ] }`

Emmm, so you just disabled prettier. It's the same "fix" as deleting the project 🙂

**Comment by rivasm44** [comment]
Im fix it issue removing the second plugin `{
			"files": ["*.html"],
			"extends": ["plugin:@angular-eslint/template/recommended"],
			"rules": {}
		}`
