### ISSUE TITLE
Visual Studio Code does not show red underline for eslint errors, although the extension still works

### ISSUE THREAD

**Issue by rudyhuynh** [microsoft/vscode-eslint#1187]
The extension works as expected in PROBLEMS panel, there is also a lightbulb, but there is no red underline on the code:

<img width="630" alt="Screenshot 2021-02-22 at 3 27 02 PM" src="https://user-images.githubusercontent.com/17097854/108675937-6c39d780-7522-11eb-9b30-3df7607debc5.png">

Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.4.0

**Comment by dbaeumer** [comment]
Very likely a dup of https://github.com/microsoft/vscode/issues/116305. Do you have the settings described here: https://github.com/microsoft/vscode/issues/116305#issuecomment-780099359

**Comment by rudyhuynh** [comment]
@dbaeumer Indeed, it is, thank you and closing the issue now.
