### ISSUE TITLE
Don't show "ESLint" in the status bar when a non-applicable file is open

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-eslint#1189]
Based on https://github.com/microsoft/vscode-eslint/issues/1068 I assume that minimizing the activation scope to specific file types isn't desired (but maybe I'm wrong?), but would it be possible to not show "ESLint" in the status bar when you have e.g. a `.rs` file open?

**Comment by dbaeumer** [comment]
The problem here is that we can only decide whether ESLint will validate a file if the user gave permission to run the ESLint library (the status bar item has NO blocked sign). Is this the case for you? If so can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by brettcannon** [comment]
Unfortunately I can only reliably trigger it on a personal, private repo, but it's causing the "✔✔ ESLint" to show when opening the `README.md` file (the repo itself only contains JSON and Python files otherwise).

**Comment by dbaeumer** [comment]
OK, the two check marks explain it. You have allowed ESLint to run everywehere. To signal this to the user we show ESLint status icon always when running in the mode.

**Comment by brettcannon** [comment]
So is the expectation that I install it disabled and then manually enable it per workspace?

**Comment by dbaeumer** [comment]
Yes and No. The problem is that I need to show an indication when `Always Allow` was selected to indicate the mode. Instead of having another status item we decided to show the ESLint one instead. However this will change when ESLint will adopt the trusted workspace model VS Code is working on.

**Comment by brettcannon** [comment]
Ah, OK, now I get it: because I said I trusted ESLint you're being upfront by visually indicating it's always running so people are aware of that fact. And since ESLint is being triggered for me by e.g. `README.md` it's showing up all the time even for repos with zero JS/TS.

I'm going to go ahead and close this since the trusted workspaces approach totally solves the reason I brought this up. I can disable the extension as necessary for now.
