### ISSUE TITLE
The eslint process becomes a zombie process and takes up a lot of CPU

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode-eslint#1191]
![截屏2021-03-01 09 53 23](https://user-images.githubusercontent.com/9758711/109442767-05fa0b00-7a74-11eb-8f18-05f1cc0d3ab4.png)

It can be seen from the image. ref: https://github.com/microsoft/vscode/issues/117647

1. There are multiple instances of eslint server running, and they are isolated processes
2. These processes will not exit and consume a lot of CPU

**Comment by dbaeumer** [comment]
The extension starts an ESLint server for every open VS Code window. 

When this happens do you still have a VS Code window open? Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by vagusX** [comment]
@dbaeumer how about using new ESLint v7 asynchronous API https://github.com/eslint/eslint/issues/3565#issuecomment-636069910

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
