### ISSUE TITLE
Text cursor jumping randomly in editor when autoSave enabled

### ISSUE THREAD

**Issue by bachmannn** [microsoft/vscode-eslint#1193]
I have these rules enabled using ``eslint 6.8.0`` in the workspace and ``autoSave`` vs code set to 1000.

```json
{
        "eslint:recommended",
        "plugin:react/recommended",
        "prettier",
        "eslint-config-prettier",
        "plugin:@typescript-eslint/recommended"
}
```
**Bug**
The text cusor jumps pack 4 spaces or the nearest word, sometimes it deletes words too, for example:

```
testing 123 testing|
testing 123|testing

testing 123 testing|
testing 12|
```
Is there a specific rule causing this, a bug makes more sense?

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are experiencing. Otherwise it is alamost impossible to investigate errors like this.

**Comment by bachmannn** [comment]
> Can you please provide me with a GitHub repository I can clone that demos what you are experiencing. Otherwise it is alamost impossible to investigate errors like this.

You can replicate the issue by doing ``create-react-library -t typescript``. It comes with a bunch of linting rules but the issue is specific to how vscode editor works on them.

**Additional Steps to Reproduce**
1. Install 3 VSCode addons ESLint-EditorConfig-Prettier
2. Set autoSave 1000 that causes frequent jumping cursor (easier to reproduce) 
3. Use Prettier addon as default formatter in vscode
4. Eslint addon is conflicting with .editorconfig which have the same rules, if you disable either (like rename .editorconfig) then issue goes away

For example this happened to me:

```
import React from 'react';

class FooComponent|
# after 1000 turned into
class ponent|FooCom
```

**Comment by dbaeumer** [comment]
@bachmannn can you please provide me with a GitHub repository I can clone. From my experience something like this depends on many things (settings, used versions, ...) that it will be very hard to ensure we are looking at the same setup without me cloning something were you can produce the error.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
