### ISSUE TITLE
Add `requireConfig`-like option to only run eslint if it's configured

### ISSUE THREAD

**Issue by selrond** [microsoft/vscode-eslint#1194]
Currently, when I work inside projects, that don't have eslint set up, it always runs (and marks a lot of things as errors / warnings), as it's not configured properly.

One solution to this may be something like `prettier-vscode`'s [`prettier.requireConfig`](https://github.com/prettier/prettier-vscode#prettierrequireconfig-default-false) option.
It prevents prettier from formatting files if prettier is not configured in a workspace.

Would it be possible / feasible to have something like that for `vscode-eslint`, or is there already a solution which I'm not aware of?

**Comment by dbaeumer** [comment]
There is a deprecated setting `eslint.enable`. The recommended way to do this in VS Code is to disable the extension for the workspace folder using the extensions viewlet.

**Comment by selrond** [comment]
Thanks, yes, seems to be the only solution for now. I was looking for a more automated solution though

**Comment by dbaeumer** [comment]
What do you mean by automated ?

**Comment by selrond** [comment]
is there an `.eslintrc` (or any other eslint config) ? enable extension : disable extension

see the prettier link in the original comment

**Comment by dbaeumer** [comment]
@selrond Then we should un deprecate `enable` and not find yet another solution.

**Comment by dbaeumer** [comment]
I am still don't understand what you mean by automated.

**Comment by selrond** [comment]
ok nevermind, not big of an issue
