### ISSUE TITLE
"Cannot read property 'toLowerCase' of null"

### ISSUE THREAD

**Issue by Awyssa** [microsoft/vscode-eslint#1195]
Hello, apologies in advance as I can see this issue has come up before,  but I still have no workaround. 

```
TypeError: Cannot read property 'toLowerCase' of null
    at Object.e.fromString (/Users/ernest/.vscode/extensions/dbaeumer.vscode-eslint-2.1.14/client/out/extension.js:1:44688)
    at R.refreshTrace (/Users/ernest/.vscode/extensions/dbaeumer.vscode-eslint-2.1.14/client/out/extension.js:1:139367)
    at R.initialize (/Users/ernest/.vscode/extensions/dbaeumer.vscode-eslint-2.1.14/client/out/extension.js:1:131626)
    at /Users/ernest/.vscode/extensions/dbaeumer.vscode-eslint-2.1.14/client/out/extension.js:1:131226
[Info  - 5:39:46 PM] ESLint server running in node v12.18.3
```

tried removing the  "eslint.trace.server", and/or changing it, but to no avail. Did uninstall on npm and vscode, still same issue. Cannot resolve issue.

Maybe I am being very stupid and it's an obvious fix, or perhaps many others are having the same issue and we can all resolve this together. Please request more info if needed.

**Comment by dbaeumer** [comment]
@Awyssa do you have any `null` value in your settings (user or workspace)?

**Comment by Awyssa** [comment]
Hi Dirk, thanks for the response! 
My VSCode settings were setting the trace.server to null, was silly of me to not check that initially. Followed these steps to fix it, just in case anyone else ran into this.

Open settings.json in VSCode, not the one that says default settings
See if you’ve got the line 'eslint.trace.server: null'
If it is in there then remove it.

Thanks again for the response, and hope this serves anyone else some assistance.

**Comment by dbaeumer** [comment]
@Awyssa can you comment why you reopened. The issue got fixed in the LSP libraries but not imported into ESLint yet.

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/common/connection.ts#L198

**Comment by Awyssa** [comment]
@dbaeumer did not mean to reopen, apologies for the confusion.

**Comment by dbaeumer** [comment]
No, I was asking if there was a reason why you reopened it.
