### ISSUE TITLE
Reduce each severity by one level, i.e. display ESLint error as VS Code warning and display ESLint warning as VS Code info

### ISSUE THREAD

**Issue by stenzengel** [microsoft/vscode-eslint#1199]
**Issue**
As pointed out in issue #468, most ESLint shared configs use "error" as their default rule severity, but should often be displayed as warnings in VS Code since they are often less important and thus should not be mixed with TypeScript errors. In addition, an even less important (e.g. stylistic) rule in ESLint is normally (or can be) configured with severity "warn", which should be displayed as "Information" in VS  Code, to be  distinguishable from more important ESLint errors (displayed as VS Code warnings).

**Proposed Solution**
Add an configuration flag to reduce each severity by one level, i.e. display an ESLint error as VS Code warning and display an ESLint warning as VS Code information.

In Pull Request #1164 (authored by @JoshuaKGoldberg), a solution to this issue is proposed, but it seems to need more configuration. Another disadvantage of this "duplicated" configuration is, that it does not allow to re-use the difference in the configuration of the severity levels for build scripts. I.e. a warning problem in VS Code should probably fail an integration build, because there are ESLint errors, but information problems in VS Code should never fail the build, because they are configured as ESLint warnings.

**Comment by dbaeumer** [comment]
@stenzengel I would like to fold this with the work @JoshuaKGoldberg is doing and have a special customization value that simply lowers the severity. Would that work for you?

**Comment by stenzengel** [comment]
@dbaeumer Yes, that would work for me. Should I close this issue now or should it be closed when this customization is part of #1164 and the merge request is merged?

**Comment by dbaeumer** [comment]
I think we should keep it open to not forget about it.

**Comment by JoshuaKGoldberg** [comment]
> not forget about it

Heh, that's what I did -- but I'm glad we're seeing this conversation now!

Bringing in https://github.com/microsoft/vscode-eslint/pull/1164#discussion_r571976055 here, how about this rough shape for the configuration object?

```
"eslint.rules.customizations": [
	{ "rule": "no-*", "override": "info" },   // override all no-* rules to info
	{ "rule": "!no-*", "override": "warn" },  // override all other (not no-*) rules to warn
	{ "rule": "*console*", "reset": "original" },  // reset all *console* rules to the original config
	{ "rule": "*syntax*", "reset": "lower" },  // reset all *syntax* rules to one lower than the original config
```

**Comment by stenzengel** [comment]
@JoshuaKGoldberg I am really happy that you work on #1164. Your proposal would complete cover my use case. 

What do you think about this shape for the configuration object?
```jsonc
"eslint.rules.customizations": [
	{ "rule": "no-*", "severity": "info" },       // override all no-* rules to info
	{ "rule": "!no-*", "severity": "warn" },      // override all other (not no-*) rules to warn
	{ "rule": "*console*", "severity": "original" }, // reset all *console* rules to the original config
	{ "rule": "*syntax*", "severity": "downgrade" },     // reset all *syntax* rules to one lower than the original config
]
```
I.e. 

- use a single property name "severity" instead of "override" and "reset"
- rename property value "lower" to "downgrade"

I'm not sure if this configuration would make future enhancements more difficult or if it is more difficult to implement, but it looks a bit more understandable to me.

**Comment by JoshuaKGoldberg** [comment]
Aha, I like that a lot @stenzengel 😄 . Will do unless directed otherwise!

**Comment by dbaeumer** [comment]
I like that proposal as well.
