### ISSUE TITLE
how to realize the show documentation function

### ISSUE THREAD

**Issue by ooo1l** [microsoft/vscode-eslint#1200]
how to realize the show documentation function

**Comment by ooo1l** [comment]
![image](https://user-images.githubusercontent.com/50876457/110913086-a7743d00-834f-11eb-99cc-11af28191ed9.png)

in the quick fix menu，can see the show documentation。
in the source code，only find the config about show documentation，i want to know how to realize it。 please。

**Comment by dbaeumer** [comment]
The code is on the server. Start here: https://github.com/microsoft/vscode-eslint/blob/main/server/src/eslintServer.ts#L197
