### ISSUE TITLE
Minor issue (maybe fixable in docs) - eslint.runtime user confirmation

### ISSUE THREAD

**Issue by cweekly** [microsoft/vscode-eslint#1205]
FTR, at least as of v2.1.18, the `eslint.runtime` value (in user settings, not workspace settings) requires user confirmation -- by choosing the one and only avlbl option in a dropdown (something like "use VSC built-in NodeJS"). The UX is weird, and wording's confusing, but in the end it all seems to work.

IOW, my settings.json's 
`  "eslint.runtime": "/Users/cweekly/n/bin/node",` 
is the node runtime that I need, and after choosing the only option in the dropdown when prompted, it's what vscode-eslint is using. 

The docs imply workspace settings (but not user settings) should trigger that UX. 
But it's a very minor issue.
Filing in case it's helpful.

**Comment by dbaeumer** [comment]
I fixed this in 2.1.19. You shouldn't see the prompt anymore since it is a user setting in the first place and you are in full control over the setting. Please ping if you still see the prompt.
