### ISSUE TITLE
When `rulePath` is missing, error notification appears on every file edit

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/vscode-eslint#1206]
Every now and then, our custom ESLint rules directory goes missing for some reason, and fixing it would generally not be my absolute top priority that needs to interrupt everything else. Except, it is, because the extension makes it impossible to focus on anything else in VS Code until it’s taken care of:

<details>
<summary>Screen capture</summary>

![Kapture 2021-03-15 at 09 48 15](https://user-images.githubusercontent.com/3277153/111189701-999f0180-8573-11eb-9f3d-d0436e434757.gif)
</details>

**Comment by dbaeumer** [comment]
The reason for this is that the ESLint server has no idea about the severity of such an error. What we can do is to add a 'Ignore for this session' button.
