### ISSUE TITLE
qowadis

### ISSUE THREAD

**Issue by Sebastianokunkelo** [microsoft/vscode-eslint#1208]

**Comment by Sebastianokunkelo** [comment]
> _Brak podanego opvscode://vscode.github-authentication/did-authenticate?windowid=1&code=f81f417d2db4e900ddda&state=e3edc367-da91-4856-990f-69f56dece7baisu._

**Comment by dbaeumer** [comment]
Closing issue. Please provide a detailed descriptions with steps on how to reproduce if you want to report a problem.
