### ISSUE TITLE
Can't lint files in . directories.

### ISSUE THREAD

**Issue by Truedrog** [Microsoft/vscode-eslint#121]
Say I have .config dir in which i have files i want to eslint. And with this extension i cannot do this.

**Comment by dbaeumer** [comment]
@Truedrog does this work from the command line? The extension doesn't do anything special here. If you open the file in VSCode is limiting still not working?

**Comment by Truedrog** [comment]
>eslint .gaia\tasks\test.js

C:\work\test-project\.gaia\tasks\test.js
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

✖ 1 problem (0 errors, 1 warning)

I think this is the cause of my problem.

**Comment by Truedrog** [comment]
Figured out with .eslintignore 
```
!.gaia
!.gaia/**/*
```
