### ISSUE TITLE
document of `eslint.validate` is confusing

### ISSUE THREAD

**Issue by JounQin** [microsoft/vscode-eslint#1214]
It is said

> This is an old legacy setting and should in normal cases not be necessary anymore.

But actually it is required for other languages like `markdown` or `mdx`.

And it is confusing if I need to config `eslint.options#extensions` at the same time.

Related context https://github.com/mdx-js/vscode-mdx/pull/163#issuecomment-800582232

**Comment by dbaeumer** [comment]
@JounQin can you provide me with a GitHub repository showing that the validate setting is needed. Markdown for example should work out of the box. Not 100% sure about mdx.

**Comment by JounQin** [comment]
Can you try this repo?

https://github.com/webpack/webpack.js.org/pull/4326#issuecomment-800783210

**Comment by chenxsan** [comment]
@dbaeumer Hi, here's how to reproduce it.

1. Clone code from that pull request
2. Run `yarn` to install
3. Open `node.mdx`, and 
    ![image](https://user-images.githubusercontent.com/1091472/111454327-7d57bc00-874f-11eb-8120-653de32415e6.png)
    As you can see, there's no error report in vscode.
4. Now run `yarn lint-js`:
    ![image](https://user-images.githubusercontent.com/1091472/111454600-c6a80b80-874f-11eb-9cb1-8d728c288d38.png)
    Eslint does catch the error.

Now if I add `"mdx"` to `"eslint.validate"`, everything would work just fine.

**Comment by dbaeumer** [comment]
dups #1159
