### ISSUE TITLE
Failed to load the ESLint library (Yarn 2 + PnP)

### ISSUE THREAD

**Issue by ericvera** [microsoft/vscode-eslint#1215]
I've been trying to troubleshoot this for a while now with no success and saw a related issue so perhaps it is a bug or something I am missing. I think this may have worked at some point but can't remember for sure.

I keep getting the following error...

```
[Info  - 10:06:58 PM] 
Failed to load the ESLint library for the document /Users/eric/Code/project/packages/components-shared/SomeCompoment.tsx

To use ESLint please install eslint by running yarn add eslint in the workspace folder project
or globally using 'yarn global add eslint'. You need to reopen the workspace after installing eslint.

Alternatively you can disable ESLint for the workspace folder project by executing the 'Disable ESLint' command.
```

I already tried `yarn add eslint` at `/Users/eric/Code/project` and it is in the root package. I am using yarn workspaces in case it makes a difference. `yarn global add eslint` should be removed as it has been disabled on yarn 2.

Here are the settings in my `.vscode/settings.json` some of which got added through `yarn dlx @yarnpkg/pnpify --sdk vscode`.

`yarn run eslint .` works when run from  `/packages/components-shared`

```
{
    "eslint.nodePath": ".yarn/sdks",
    "eslint.packageManager": "yarn",
    "eslint.workingDirectories": ["./packages/components-shared"],
    "eslint.validate": [
      "javascript",
      "javascriptreact",
      "html",
      "css",
      "typescriptreact",
      "typescript"
    ]
}
```

**Comment by dbaeumer** [comment]
@ericvera does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by ericvera** [comment]
@dbaeumer the validation does happen correctly. I do not have a repo that can be shared for repro and it may be some time before I can take the time to create one. 

Any chance there is a guide somewhere with troubleshooting options? Debug logs?

**Comment by dbaeumer** [comment]
Which command do you use and which cwd?

**Comment by ericvera** [comment]
Found the solution so closing. 

Solution: 
 1.  Command + Shift + P
 1.  Select the `>ESLint: Select Node Path` command 
 1. and selecting `Use NODE_PATH value defined via setting .yarn/sdk`
 
My guess is that at some point either I dismissed the prompt or selected the wrong value. Setting a new project from scratch to try to repro the issue led me to the finding.

A great time saver would be for the error message of not being able to load ESLint to detect Yarn Berry and add those steps rather than `yarn global add eslint`. Which no longer works.

Anyways, thanks for the quick follow-ups!

**Comment by dbaeumer** [comment]
@ericvera there should have been a notification informing you about the confirmation need for `nodePath`. This changed lately to get it in line with VS Code's recommendation to have user approval for settings that influence code execution.

**Comment by ericvera** [comment]
@dbaeumer there was. 

Some context in case it helps:
At the time I didn't know what it was and in the middle of some work assumed it safe to dismiss. I guess by choosing the wrong option. 
It took me some time to notice as TS linting was still working. After noticing I did see references to similar issues and comments you have left on those about the new dialog but didn't completely connect the two until I tried to set everything up from scratch.
Looking at the code I saw that there are custom messages for yarn/npm/pnpm so perhaps a variant for yarn+pnp (still not sure what to call it) would simplify things if the issue keeps coming back.

Thanks again for the follow-up.

**Comment by phil-w** [comment]
I have this problem, but I don't have a command anything like:
`Use NODE_PATH value defined via setting .yarn/sdk`

What was that command supposed to do, and can I do it some other way? I'm using Yarn 3.* (berry) so this is probably the problem I'm having, but I `yarn global add eslint` as advised doesn't work, and I can't work out what it's trying to do exactly, or what failure it's getting. 

Where is this "ESLint library" supposed to be, and how can I help it find it?

**Comment by phil-w** [comment]
OK, the bit which is possibly obvious to everyone but me is...
(1) I had a .yarn/sdks directory, but it just had the scelte-language-server in it, nothing else.
(2) I read the (new since I last read it) yarn docs, which had stuff about typing: `yarn dlx @yarnpkg/sdks` so I did that.
(3) That, plus {"eslint.nodePath": ".yarn/sdks", "eslint.trace.server": "verbose",
  "eslint.packageManager": "yarn",} in settings... seemed to fix it
