### ISSUE TITLE
How to prevent linting of package.json in a monorepo ?

### ISSUE THREAD

**Issue by mapringg** [microsoft/vscode-eslint#1220]
I want to prevent eslint from formatting my package.json file. I tried creating a settings.json to direct the working directory, but that had no effect. Running eslint from inside the directory or opening the project directory directly does not format package.json file. However, eslint does not format my other .json such as tsconfig.json, so I could not understand why it is formatting my package.json.

![Screen Shot 2021-03-25 at 18 21 51](https://user-images.githubusercontent.com/15067237/112465277-1f525680-8d97-11eb-9504-ba486fddb292.png)
![Screen Shot 2021-03-25 at 18 22 39](https://user-images.githubusercontent.com/15067237/112465293-22e5dd80-8d97-11eb-90f1-16a55494d289.png)

**Comment by dbaeumer** [comment]
Sounds strange to me. Have you tried to add the package.json to the `.eslintignore` file

**Comment by mapringg** [comment]
Yes, I did try creating .eslintignore and adding package.json.

**Comment by dbaeumer** [comment]
Can you provide me with steps to reproduce or a GitHub repository I can clone?

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
