### ISSUE TITLE
Global eslint config fails to load extended configs

### ISSUE THREAD

**Issue by theetrain** [microsoft/vscode-eslint#1221]
Thank you for maintaining this extension.

## Issue

I was attempting to set up a global configuration for ESLint, that way all my projects can follow a consistent code style, but it cannot seem to read my configs. I have them installed globally.

## Configs

Globally-installed modules:

```
$ npm ls -g eslint prettier eslint-config-prettier eslint-config-standard
/Users/[redacted]/.nvm/versions/node/v12.20.1/lib
├── eslint@7.22.0 
├── eslint-config-prettier@8.1.0 
├── eslint-config-standard@16.0.2 
├── prettier@2.2.1 
└─┬ standard@16.0.3
  ├── eslint@7.13.0 
  └── eslint-config-standard@16.0.2 
```

My `~/.eslinrc.json`:

```json
{
  "extends": [
    "standard"
  ],
  "rules": {}
}
```

ESLint extension output:

```
[Error - 3:18:23 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Failed to load config "standard" to extend from.
Referenced from: /Users/[redacted]/.eslintrc.json
  Code: -32603 
(node:8306) UnhandledPromiseRejectionWarning: Error: Failed to load config "standard" to extend from.
Referenced from: /Users/[redacted]/.eslintrc.json
```

## Environment

| Item | Version |
| --- | --- |
| macOS | 10.15.7 Catalina |
| VSCode | 1.54.3 |
| ESLint VSCode extension | 2.1.19 |
| Node | 12.20.1 |
| npm | 6.14.10 |

**Comment by dbaeumer** [comment]
@theetrain does the validation happen correctly when you use eslint in the terminal. If it does which working directory do you use and is it the workspace folder you have open in VS Code. If not please consider using the `workingDirectories` setting.

If this doesn't help can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by theetrain** [comment]
Hello, I have created a repository here https://github.com/theetrain/eslint-issue-1221 

It includes an `example.js` with an input file, and respective `fixture-*.js` files with the expected formatting after running `eslint`.

>does the validation happen correctly when you use eslint in the terminal.

No, when I run `eslint example.js` I see the following output:

```
$ eslint fixture.js 

Oops! Something went wrong! :(

ESLint: 7.22.0

ESLint couldn't find the config "standard" to extend from. Please check that the name of the config is correct.

The config "standard" was referenced from the config file in "/Users/[redacted]/.eslintrc.json".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

I also tried adding `.eslintrc.json` configs to the repository root and running `eslint` in the terminal, but the above error would still show.

For `fixture-prettier-standard.js`

```json
{
  "extends": [
    "prettier",
    "standard"
  ],
  "rules": {}
}
```

For `fixture-standard.js`

```json
{
  "extends": [
    "standard"
  ],
  "rules": {}
}
```

**Comment by dbaeumer** [comment]
@theetrain thanks for the repository. 

If the validation doesn't happen correctly in the terminal then it will not work correctly in the extension either. So I recommend that you first try to get this working in the terminal. May be the ESLint stackoverflow https://stackoverflow.com/questions/tagged/eslint might be a source for some tips.

When it is working in the terminal and you still see issues in the extension, please ping and I will reopen the issue.

**Comment by theetrain** [comment]
>If the validation doesn't happen correctly in the terminal then it will not work correctly in the extension either. So I recommend that you first try to get this working in the terminal. 

Thanks for the explanation. I understand now that this extension depends on the functionality of the eslint CLI. 

With that said, I managed to come up with a workaround by adding a `~/package.json` file and installing all dependencies there. That way, `~/.eslintrc.json` could reference modules within `~/node_modules`, but I'm unsure if this is the correct way to use eslint as a 'global' user configuration.

**Comment by dbaeumer** [comment]
In general eslint is better used as a local installation and not as a global one. What is especially tricky is if a global installation wants to access local resource (e.g. node modules, ...).

**Comment by nnmrts** [comment]
I encounter the exact same problem. And of course, you can always just switch to local installations, but having a `package.json` and a `node_modules` in my deno project seems...weird. Is there any other workaround and/or motivation to fix this issue?

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by ZhangWei-KUMO** [comment]
I met same issue
