### ISSUE TITLE
Quick fix disappears

### ISSUE THREAD

**Issue by olegKusov** [microsoft/vscode-eslint#1223]
https://user-images.githubusercontent.com/28058268/112721049-e3440080-8f12-11eb-994f-f0d2a3322a05.mov

**Comment by dbaeumer** [comment]
@olegKusov any steps to reproduce. Best a GitHub repository to clone.

**Comment by olegKusov** [comment]
> @olegKusov any steps to reproduce. Best a GitHub repository to clone.

if we click quick fix and for example disable this rule for entire file. then if we want to disable it just for line we make ctrl + z and after that quick fix doesn't appear. only after saving ..

**Comment by dbaeumer** [comment]
@olegKusov to debug this I would need exact steps to reproduce. This is best provided with a GitHub repository I can clone plus a readme.md describing the steps I need to do.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
