### ISSUE TITLE
autoformatting creates a new semi colon when i save

### ISSUE THREAD

**Issue by narutopig** [microsoft/vscode-eslint#1224]
when i save (cmd + s) there is a new semicolon added to the end of my code (where there should be one)
[video](https://drive.google.com/file/d/1u5WQ9R72RrQYGfXE8lBgbOtpIGvcgG1z/view?usp=sharing)
edit: seems to be only with typescript, also using react and the typescript create-react-app template

**Comment by dbaeumer** [comment]
I can't what the video. It is some Minecraft thing :-)

I am pretty sure that you have auto fix on save enabled which fixes these errors on save. Is that the case?

**Comment by narutopig** [comment]
i probably uploaded the wrong vid sry
idk why but its fixed now lol
