### ISSUE TITLE
Eslint not working after node update

### ISSUE THREAD

**Issue by hnjoshi** [microsoft/vscode-eslint#1227]
eslint status
```
[Info  - 14:18:24] ESLint server is running.
(node:56109) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token ...
(node:56109) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:56109) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token ...
(node:56109) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): SyntaxError: Unexpected token ...
```

Node v14.16.0
eslint v7.23.0

any suggestion?

**Comment by dbaeumer** [comment]
@hnjoshi does eslint work in the terminal correctly?

**Comment by hnjoshi** [comment]
@dbaeumer Yes, it works fine in the terminal.

**Comment by hnjoshi** [comment]
![image](https://user-images.githubusercontent.com/8787607/113177457-2653eb80-9213-11eb-88ba-2411b32c9a1f.png)
The new settings are shown as "unknown configuration settings". 
old settings don't show unknown configuration nor they work.

**Comment by dbaeumer** [comment]
Do you use the `eslint.runtime` setting. If yes, you need to confirm the setting now. See https://github.com/microsoft/vscode-eslint/blob/main/README.md. To confirm the setting run the command `ESLint: Select Node Runtime`

**Comment by hnjoshi** [comment]
No I didn't use `eslint.runtime` setting.

**Comment by hnjoshi** [comment]
`.eslintrc.json`

```
{
  "root": true,
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2016,
    "sourceType": "module"
  },
  "env": {
    "browser": true,
    "node": true,
    "es6": true,
    "jest": true
  },
  "extends": [
    "airbnb",
    "prettier",
    "prettier/react",
    "plugin:jest/recommended"
  ],
  "plugins": [
    "prettier",
    "jest"
  ],
  "rules": {
    "prefer-destructuring": "off",
    "camelcase": "off",
    "import/no-named-as-default": 0,
    "react/destructuring-assignment": "off",
    "react/jsx-filename-extension": "off",
    "react/jsx-sort-props": ["error", {
      "ignoreCase": true,
      "reservedFirst": false
    }],
    "react/prefer-stateless-function": "off",
    "class-methods-use-this": "off",
    "jsx-a11y/label-has-associated-control": [ "error", {
      "required": {
        "some": [ "nesting", "id"  ]
      }
    }],
    "jsx-a11y/label-has-for": [ "error", {
      "required": {
        "some": [ "nesting", "id"  ]
      }
    }],
    "prettier/prettier": [
      "error",
      {
        "bracketSpacing": true,
        "trailingComma": "all",
        "singleQuote": true
      }
    ]
  }
}
```

**Comment by hnjoshi** [comment]
"lint": "eslint src config webpack --fix" - script in pkg json

```
$ npm run lint

> eslint src config webpack --fix


/Users/hnjoshi/repos/x-ui/src/client/components/custom-resolver/CreateCustomResolver.js
  11:10  error  'SidePanel' is defined but never used           no-unused-vars
  11:21  error  'SidePanelContainer' is defined but never used  no-unused-vars

/Users/hnjoshi/repos/x-ui/src/client/containers/CustomResolverActionHandler.js
   7:10  error  'DialogType' is defined but never used  no-unused-vars
  10:1   error  Prefer default export                   import/prefer-default-export

/Users/hnjoshi/repos/x-ui/src/client/containers/CustomResolverContainer.js
  14:10  error  'showCreateResolver' is defined but never used  no-unused-vars

✖ 5 problems (5 errors, 0 warnings)
```

linter works fine in terminal, but I don't see these errors in VS code.

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by hnjoshi** [comment]
It's not a public repository so I can't share.

**Comment by dbaeumer** [comment]
@hnjoshi can you distill one?

**Comment by kanizer** [comment]
I get the same output error - here's a [sample project](https://github.com/kanizer/eslint-extension-debug) for reference.

MacOS 11.4
Code v1.22.2
Node v14.11.0
eslint v6.5.1
ESLint plugin v1.4.10 (this is the version auto-installed; manually installed newer releases do not work?)

**Comment by hnjoshi** [comment]
My issue had got resolved after I got new laptop. So I think there was some caching problem in older setup.
I would suggest clean install / clear cache.

**Comment by kanizer** [comment]
> I would suggest clean install / clear cache

@hnjoshi Thx for the context - were you referring to the extension? VSCode?

**Comment by dbaeumer** [comment]
@kanizer can you please update to the latest VS Code (which is 1.56.0) which will update the ESLint extension to 2.1.20

The versions you are using are ~ 2 years old.

**Comment by hnjoshi** [comment]
> > I would suggest clean install / clear cache
> 
> @hnjoshi Thx for the context - were you referring to the extension? VSCode?

I was already on latest version of vs code and extension but due to caching issue I was running into eslint errors. New/Clean setup solved the issue.

Closing this issue as it can't be reproduced.

**Comment by kanizer** [comment]
> The versions you are using are ~ 2 years old.

I guess that would explain things 🤦  - I tried updating through the app menu, but downloading the current version worked as expected. Ty!
