### ISSUE TITLE
Support variable substitution to refer to workspaceFolder / rootDir in eslint.options setting

### ISSUE THREAD

**Issue by rdsedmundo** [microsoft/vscode-eslint#1231]
I'd like to configure the `eslint.options` setting to use my `.gitignore` at the root of my monorepo, unfortunately, there's no way to refer to the root directory, and because I'm making use of `eslint.workspaceDirectories`, I get errors depending on the nesting of my packages (not everything is under packages/* just), saying that the file could not be found.

Something like this:
```
  "eslint.options": {
    "ignorePath": "${workspaceFolder}/.gitignore"
  }
```

**Comment by dbaeumer** [comment]
This is best supported in VS Code itself and dups https://github.com/microsoft/vscode/issues/2809

**Comment by rdsedmundo** [comment]
I just faced this again on a repo where I have a single package that is not in a workspace and I'm referencing the ignorePath as `../../.gitignore`. 

The VSCode issue that you linked is more than 5 years old. Couldn't you reconsider opening this again? I'd be open to contributing, we can always remove our implementation here if VSCode makes it built-in in the future.

**Comment by dbaeumer** [comment]
I think it makes more sense then to contribute this to VS Code itself then having a custom implementation here in ESLint.
