### ISSUE TITLE
Not found tsconfig.json if open project on parent directory

### ISSUE THREAD

**Issue by netdjw** [microsoft/vscode-eslint#1232]
Hello,

I run into this issue when I try to change from tslint to ESLint in VSCode with an Angular project.

The project directory structure is this:
```
|- .git/
|- angular/
|  |- src/
|  `- .eslintrc.json
|- laravel/
`- other-files.txt
```

If I open VSCode like this, I get some errors on every `.ts` files with this message:

`Parsing error: Cannot read file '/home/djw/code/myproject/tsconfig.json'.  eslint`

So I need to change the `.eslintrc.json` file like this:

```json
      "parserOptions": {
        "project": [
          "tsconfig.json",
          "e2e/tsconfig.json"
        ],
        "tsconfigRootDir": "angular/",  // THIS LINE IS ADDED
        "createDefaultProgram": true
      },
```
Now the VSCode ESLint plugin works fine.

But if I try to run `ng lint` command, I get an error:

`  0:0  error  Parsing error: Cannot read file 'angular/tsconfig.json'`

Any idea how can I fix this issue?

**Comment by dbaeumer** [comment]
@netdjw I am not very familiar with `ng lint`. What you can try for VS Code is to set the `eslint.workingDirectoies` setting to `angular` to ensure the working directory is setting correctly.

**Comment by netdjw** [comment]
@dbaeumer thanks, I added this code in my project folder to this file: `.vscode/settings.json`

```json
{
    "eslint.workingDirectories": [
        "angular"
    ]
}
```

Now the error is gone.
