### ISSUE TITLE
Set runtime dynamically / to system default

### ISSUE THREAD

**Issue by JakobJingleheimer** [microsoft/vscode-eslint#1233]
ESlint is using VS Code's old, built-in version of NodeJS (v12) as provided by Electron.

I want to use the current version, which is already installed (via nvm).

As the version will change as I update to new releases, I want to specify the system's version of node (eg `which node`).

When I run the command `"ESLint: Select Node Runtime"`, the only option is VS Code's built-in.

I tried setting `"eslint.runtime": "$(which node)"` in `settings.json`, but the eslint server barfs.

P.S. I read through the README of this repo, and it provided almost no information about this.

**Comment by dbaeumer** [comment]
@JakobJingleheimer the settings are managed by VS Code and VS Code itself has no support for variables or $ evaluation. However you should be able to set the value simply to `node` which should do what you expect.

**Comment by dbaeumer** [comment]
@JakobJingleheimer can you provide me with a GitHub repository I can clone that demos this?

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by RebeccaStevens** [comment]
Using "node" doesn't work for me; I need provide the full absolute path.

Note: I'm using WSL, Ubuntu 21.04

**Comment by dbaeumer** [comment]
In WSL you need to set the setting on the WSL side as a machine setting.

**Comment by RebeccaStevens** [comment]
I'm not sure what you mean by "machine setting"

**Comment by dbaeumer** [comment]
<img width="309" alt="capture" src="https://user-images.githubusercontent.com/1931590/151532986-e593ad97-6a2f-4340-b567-c9a7dfaad8d6.png">

The WSL settings in the settings editor.

**Comment by RebeccaStevens** [comment]
That is where I set it

**Comment by dbaeumer** [comment]
Is node on your path?

**Comment by RebeccaStevens** [comment]
Hmm weird. It all seems to be working now despite me not changing any settings since yesterday.
Yesterday I was getting an alert dialog when I started vscode stating that it couldn't start the eslint server with "node" (or something like that).
Ahh, computers are weird sometimes.
