### ISSUE TITLE
eslint.probe does not appear to honor "pug"

### ISSUE THREAD

**Issue by initplatform** [microsoft/vscode-eslint#1234]
I am trying to incorporate https://github.com/unrelentingtech/eslint-plugin-pug with eslint in vscode and I keep getting:

```
ESLint is not running. By default only TypeScript and JavaScript files are validated. 
If you want to validate other file types please specify them in the 'eslint.probe' setting.
```

I add `"pug"` to `eslint.probe` and it doesn't seem to make a difference.

```json
    "eslint.probe": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "html",
        "vue",
        "markdown",
        "pug"
    ]
```

**Comment by dbaeumer** [comment]
Do you have an extension installed that adds the `pug` language id. Otherwise the ESLint extension doesn't know about pug files.

**Comment by initplatform** [comment]
I have `ditto.convert-html-to-pug`, `mrmlnc.vscode-pugbeautify` and `mrmlnc.vscode-puglint` installed. 

Not sure if they add a language id. How can I tell?

**Comment by dbaeumer** [comment]
When you open the Language Mode picker does pug show up in it?

**Comment by initplatform** [comment]
Looks like it

<img width="422" alt="Screen Shot 2021-04-26 at 4 28 16 PM" src="https://user-images.githubusercontent.com/47506789/116146416-7a37e000-a6ac-11eb-9fa6-b021cd59e715.png">

**Comment by dbaeumer** [comment]
@initplatform interesting. Can you provide me with a typical pug setup that should work best as a GitHub repository I can clone.

**Comment by initplatform** [comment]
Hi @dbaeumer, 

I started the process of making a sample repository, but then I noticed I was no longer receiving the error. 

I did update VSCode a couple of times since I first posted this, so that may be it. 🤷 

However, I am also still not seeing any linting on my pug files. Upon further inspection, it looks like `eslint-plugin-pug` doesn't actually lint pug files, it lints javascript in the script tags of pug files :/

So, looks like I will revert back to using [pug-lint](https://github.com/mrmlnc/vscode-puglint)

Thanks for helping out!

**Comment by jooohny** [comment]
Hello! Can you please help me with `eslint-plugin-pug`? It only highlights problems when eslint is run via CI, like: `./node_modules/.bin/eslint --ext .js,.pug .` But when I simply open _.pug_ files, is doesn't highlight anything and problems don't appear in  **PROBLEMS** tab of terminal.

**Comment by boompikachu** [comment]
Since TSX is `typescriptreact`:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/37561295/228610133-03782d5b-2016-4e07-8c8b-f74882f63dba.png">

Maybe try adding it as `jade`?
<img width="170" alt="image" src="https://user-images.githubusercontent.com/37561295/228610228-0880558b-6578-47f3-832f-27850efc5ca2.png">
