### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 283556284** [microsoft/vscode-eslint#1235]
- Issue Type: `Performance`
- Extension Name: `vscode-eslint`
- Extension Version: `2.1.19`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\User\AppData\Local\Temp\dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by dbaeumer** [comment]
@283556284 do you still have the profile. If yes, can you please attach it. Thanks!

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
