### ISSUE TITLE
Cant uninstall eslint or pretifier

### ISSUE THREAD

**Issue by kpetrow** [microsoft/vscode-eslint#1236]
I click uninstall extension, then prompts to reload, which i do then eslint reappears in extension list.  

![image](https://user-images.githubusercontent.com/18248938/114199277-60a74200-9911-11eb-9e3e-3f303a153edc.png)

**Comment by kpetrow** [comment]
this is maddening. eslint is squiggling everything

**Comment by dbaeumer** [comment]
Do you have an `extensions.json` in the .vscode folder that automatically installs extensions?

**Comment by kpetrow** [comment]
only a settings.json which has:
{
    "C_Cpp.errorSquiggles": "Disabled"
}

could it possibly be the sync extension resyncing?

**Comment by dbaeumer** [comment]
Are you using setting / extension sync? This could explain it?

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
