### ISSUE TITLE
Shouldn‘t fail on `"dependenciesMeta": { "core-js": { "built": false } }` in `package.json`

### ISSUE THREAD

**Issue by lensbart** [microsoft/vscode-eslint#1239]
Happens with Yarn 2 PnP as seemingly only way to manually override postinstall donation message which fails on CI unless dependency is in (git-committed) .yarn/unplugged in order to enable Zero-Installs

**Comment by dbaeumer** [comment]
@lensbart can you please provide steps on how to reproduce this best using a GitHub repository I can clone.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
