### ISSUE TITLE
.eslintrc.js does not have suggestions

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-eslint#124]
_From @isidorn on August 30, 2016 13:34_

Refs #11100
1. Simple repo, initiazlie eslint, .eslintrc.js gets created
2. Open .eslintrc.js and triggere intelli-sense -> no suggestions
3. As found while discussing with @dbaeumer the issue here is that this file is .js and not .json
4. I would expect suggestions to help me set this file up

_Copied from original issue: Microsoft/vscode#11213_

**Comment by dbaeumer** [comment]
Might be hard to achieve since we need to tell the tsserver about a d.ts eslint file under the cover. On top of this we would need to maintain such a file.

**Comment by knownasilya** [comment]
Any movement on this? Not getting any linting based on this file.

**Comment by dbaeumer** [comment]
No movement so far.

**Comment by golopot** [comment]
There is intellisense in `.eslintrc` or `.eslintrc.json`, but not in `.eslintrc.js`.

**Comment by sarpik** [comment]
Up - still needed!

Filename `.eslintrc` [is deprecated](https://eslint.org/docs/user-guide/configuring#configuration-file-formats) and `.eslintrc.js` does NOT have intelliSense.

**Comment by sarpik** [comment]
Up - still needed!

Filename `.eslintrc` [is deprecated](https://eslint.org/docs/user-guide/configuring#configuration-file-formats) and `.eslintrc.js` does NOT have intelliSense.

/cc @dbaeumer

**Comment by tvkit** [comment]
Yup, there's code assist support for JSON, but conditionals are problematic. 

Here's a default vue setup, _.eslintrc.js_,  with ENV conditionals.

```
module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: ["plugin:vue/essential", "@vue/prettier", "@vue/typescript"],
  rules: {
    "no-console": process.env.NODE_ENV === "production" ? "error" : "off",
    "no-debugger": process.env.NODE_ENV === "production" ? "error" : "off"
  },
  parserOptions: {
    parser: "@typescript-eslint/parser"
  }
};

```

**Comment by tcd** [comment]
Any update on this? 
Still looking around for a solution but it seems like this is a/the proper issue to follow.

**Comment by dbaeumer** [comment]
As I was trying to explain this is something that needs to come from the TS / JS server. Let me ping someone in the TS team if there is any way to inject a d.ts for a specific file.

**Comment by dbaeumer** [comment]
@DanielRosenwasser is there any way I can teach the TypeScript server to check a certain file using a specific d.ts. file. For example by using some sort of meta comment in the file ?

**Comment by cdbattags** [comment]
Any more updates on this?

**Comment by dbaeumer** [comment]
@DanielRosenwasser any updates on comment https://github.com/microsoft/vscode-eslint/issues/124#issuecomment-580174734

**Comment by DanielRosenwasser** [comment]
Sorry, I didn't see the original question. Today I think your best bet would be to install `@types/eslint` and use a JSDoc annotation to get completions.

```js
/**
 * @type {import("eslint").Linter.Config}
 */
const config = {
  // ...
}
module.exports = config;
```

**Comment by dbaeumer** [comment]
@DanielRosenwasser THANKS!!

Will close the issue then since there is nothing ESLint needs to do here.

**Comment by cdbattags** [comment]
I don't think this suggestion is ideal. You're saying add a JSDoc to every TypeScript file in my repo?

**Comment by cdbattags** [comment]
Ahhh, no, just the config JavaScript?

Interesting, lemme give this a try within the hour

**Comment by dbaeumer** [comment]
@cdbattags correct.

**Comment by jonaskuske** [comment]
@cdbattags Just to the `.eslintrc.js` file. Or why do you need ESLint types/autocompletion in every single file?

**Comment by cdbattags** [comment]
Might I open/add a different ticket for the long term?

Ideally I don't want to have to remember to add this annotation to each new repo/config.

I don't mind attempting the work on this.

**Comment by dbaeumer** [comment]
IMO this should be handled by the `eslint init` command. There is nothing I in the ESLint extension can do about this.
