### ISSUE TITLE
Disable files highlight in explorer

### ISSUE THREAD

**Issue by senyaak** [microsoft/vscode-eslint#1244]
Didn't find any way to disable ESLint highlighting in explorer. Did I miss it, or it is just alway on?

**Comment by dbaeumer** [comment]
@senyaak what kind of highlighting are you referring to. Can you please provide steps about how to reproduce what you are seeing including what you are actually expecting.

**Comment by senyaak** [comment]
For example I have some project. I open in in vscode and all files in the explorer are white. When I do some changes in file A.js, vcs(in my case git) make this files color in explorer green.  If Eslint find some problems in the file - it makes A.js files color=rgb(248, 128, 112). I would supress the color changing so I can see all vcs changes.
(there are also counter of the issues in the file, I would love to still have it, but not color changes)
Hope it is understandable ;)

**Comment by dbaeumer** [comment]
This is not a ESLint feature. It is a general VS Code feature and can be customized using settings. 
<img width="661" alt="capture" src="https://user-images.githubusercontent.com/1931590/117673923-8a22ea00-b1ab-11eb-8c1f-18cae8d64692.png">

**Comment by senyaak** [comment]
@dbaeumer Wrong, it is esling highlighting, which overwrite git highlighting. If I disable eslint, then I see only white + git green colors. When I enable eslint, I see white, green and the ESlint orange?`rgb(248, 128, 112)` colors. 
Also the eslint issues count in the file just can't be git feature...

**Comment by senyaak** [comment]
This is the issue, if I turn it off, the number of errors, which is placed right of the file name, will disappear too. Also it will supress other errors(for example TS errors) which I want to see. 
Looks like some design issue in vscode/plugin. I would love to configure this highlightings and other indicators  for every plugin I use. 
Good exaple: If I work on some project where a lot of eslint errors, author do not care about and do not fix them. And I have to implement some featuren. I need to see only 'real' errors and not eslint errors. Now I have to use another tool to achive that or just look over all highlited files.
But anyway thank you for the tip. At least something

**Comment by dbaeumer** [comment]
You can reconfigure rules using the `eslint.rules.customizations` setting which will support `off` soon as well

**Comment by mephitrpg** [comment]
How can I do that exactly?

**Comment by dbaeumer** [comment]
The readme in ESLint extension has an example how to use it.
