### ISSUE TITLE
Rule customizations override quiet

### ISSUE THREAD

**Issue by DaveStein** [microsoft/vscode-eslint#1246]
I have the following settings:

```js
"eslint.rules.customizations": [
{ "rule": "jest/no-focused-tests", "severity": "warn" },
],
"eslint.quiet": true
```

I'd expect my `error` to drop to `warn` and then `eslint.quiet` would make sure my editor doesn't highlight the issue anymore. 

As it stands, i can't focus a test while doing dev work without having all the UI squiggles under the code. Since `customizations` is supposed to override a rule for the editor, and I'm overriding to `warn`, I would expect `eslint.quiet` to make it hidden given that the description says `ignore warnings.`.

Is this working as intended or a bug that I have found?

**Comment by dbaeumer** [comment]
It is actually confusing that we have customizations and quite. The current idea is to deprecate quiet and to allow `off` in the customizations.

**Comment by DaveStein** [comment]
@dbaeumer i was actually surprised you didn't have `off` but didn't think to ask for it for some reason :)

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/vscode-eslint/pull/1243 for the PR. I will close the issue then and treat it as a dup of the `off` severity
