### ISSUE TITLE
Adding another Disable Rule Comment through VSCode's Quick FIx options causes the rules to be re-enabled

### ISSUE THREAD

**Issue by asingh04** [microsoft/vscode-eslint#1248]
**Problem Statement**
If a disable rule comment has already present for a particular line, and when we add another disable rule comment through vscode's quick-fix option,  a separate new comment is added below the previous one. This causes the previous rule to be re-enabled for the concerned line.
![image](https://user-images.githubusercontent.com/15160343/117317127-dbc72e00-aea6-11eb-8518-62505ad8ebc0.png)

Similar behaviour happens when `eslint.codeAction.disableRuleComment.location` has been set to `sameLine`. The new disable rule comment is appended to the existing disable rule comment present.
![image](https://user-images.githubusercontent.com/15160343/117317421-22b52380-aea7-11eb-82c4-84c49131ca23.png)

**Expected Behaviour**
If there is any preexisting disable rule comment for any particular line and another rule is being disabled for that same line, instead of creating or appending the comment, only the rule should be appended to the existing disable rule comment, separated by comma(s). Like this:
![image](https://user-images.githubusercontent.com/15160343/117317850-83446080-aea7-11eb-8417-33949fd7f207.png)

The same behavior is observed when disabling multiple rules for entire files as well, but it doesn't cause any rule to be re-enabled

I would like to work on the fix for this too.

**Comment by asingh04** [comment]
Can you assign it to me? I have started working on it

**Comment by asingh04** [comment]
Created a Pull request with the changes [#1261 ](https://github.com/microsoft/vscode-eslint/pull/1261)

**Comment by dbaeumer** [comment]
This got fixed a long time ago.
