### ISSUE TITLE
extends conflict 

### ISSUE THREAD

**Issue by jason-ivy** [microsoft/vscode-eslint#1250]
.eslintrc.js
```
module.exports = {
  extends: "eslint-config-egg/typescript",
  parserOptions: {
    project: "./tsconfig.json"
  },
  rules: {
    indent: ["error", 4]
  }
}
```

![image](https://user-images.githubusercontent.com/8363595/117445228-07ace700-af6d-11eb-82a8-a227a623f9ca.png)

after fixed it，still error

![image](https://user-images.githubusercontent.com/8363595/117445342-27440f80-af6d-11eb-933c-096e7d1fdf5d.png)

**Comment by dbaeumer** [comment]
To my knowledge you need to disabled the default eslint ident rule when using a specific typescript rule. I always do something like

```
		"indent": "off",
		"@typescript-eslint/indent": ["warn", "tab", { "SwitchCase": 1 } ]
```

This is how it is documented by the typescript-eslint plugin.

Please ping if this doesn't solve the issue.
