### ISSUE TITLE
Validation implemented in the extension instead of the server

### ISSUE THREAD

**Issue by rchl** [microsoft/vscode-eslint#1257]
I wonder why this code is in the extension rather than in the server:
https://github.com/microsoft/vscode-eslint/blob/2e0e525e6ab1cb40154ba2313ef857b58a65b1bd/client/src/extension.ts#L420-L435

It seems like it's just some simple validation that would work as well in the server.

**Comment by dbaeumer** [comment]
Currently setting validation is mostly done in the client. PR welcome to move it to the server.

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
