### ISSUE TITLE
Support ESLint module install globally or locally inside another module

### ISSUE THREAD

**Issue by qiu8310** [microsoft/vscode-eslint#1258]
ESLint is installed inside a module, for example `my-cli`, and `my-cli` can install globally or locally. so it is possible for `vscode-eslint` to load eslint module from `my-cli`.

For example add a configure: `eslint.getESLintModuleCommand=["my-cli", "get-eslint-path"]`

**Comment by dbaeumer** [comment]
The eslint extension doesn't have its own resolving rules. It is relying on what ESLint can do in the terminal on the command line. So if you can get it to work in the terminal it should also work in the extension.

 To keep things consistent I have no plans to implement any non ESLint standard resolving rules.
