### ISSUE TITLE
`eslint.validate` setting is not being respected

### ISSUE THREAD

**Issue by brc-dd** [microsoft/vscode-eslint#1259]
#### `settings.json`

```json
{
  "eslint.validate": ["typescript", "typescriptreact"]
}
```

### Behavior

![image](https://user-images.githubusercontent.com/40380293/118177688-a6938080-b450-11eb-85b1-4aff86275cde.png)

### Expected

Since, I have not specified `javascript` in the settings, it should not validate code of my configuration files like `.eslintrc.js`.

---

Also if I use a `.eslintignore` file like this:

```ignore
*
!**/*.ts
!**/*.tsx
```

The extension does not behave in expected manner. It stops validating all files. Are negated patterns not supported yet?

---

### Version Details

```txt
Name: ESLint
Id: dbaeumer.vscode-eslint
Description: Integrates ESLint JavaScript into VS Code.
Version: 2.1.20
Publisher: Dirk Baeumer
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
```

```txt
Version: 1.56.1 (system setup)
Commit: e713fe9b05fc24facbec8f34fb1017133858842b
Date: 2021-05-06T10:08:05.141Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.21343
```

```txt
"eslint": "^7.26.0"
```

**Comment by dbaeumer** [comment]
The `eslint.validate` setting is actually deprecated in favor of `probe`. Auto probing is enabled by default for JavaScript, hence the JS files are validated.

The extension doesn't do any self interpretation of the `.eslintignore` file. It is all delegated to the ESLint npm package. 

Can you reproduce the fact that the ignore file is not honored when executing ESLint in the terminal. If so can you please provide me with a GitHub repository I can clone that demos that.

**Comment by brc-dd** [comment]
@dbaeumer Thanks for responding. `eslint.probe` works as intended. Also, the `.eslintignore` thing was actually my fault. According to the `.gitignore` specs (that `eslint` > `node-ignore` follows), if the directory itself is ignored (matched by `*` in my case), then files inside it cannot be re-included. Hence, I should have used something like `*.*` to ignore the files not the directories itself.
