### ISSUE TITLE
VSCode continues to display a lint error after the source is edited

### ISSUE THREAD

**Issue by markchagers** [microsoft/vscode-eslint#1260]
Issue Type: <b>Bug</b>

Steps:
Deleberately enter an invalid import in a ts file
Change the source to correct the error

Actual result:
VSC (or ESlint?) continues to display the error, it only goes away after quitting and restarting VSC.

Expected behaviour: 
the error should not be displayed after the source is corrected

I assume this to be a problem with ESlint, but I really have no idea. I can't test this without ESlint enabled obviously.

Extension version: 2.1.20
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (13.66GB free)|
|Process Argv|--crash-reporter-id b8c9011e-fccb-4f5f-86c3-901bdabc9475|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
vscod805:30301674

```

</details>

**Comment by markchagers** [comment]
![error](https://user-images.githubusercontent.com/529428/118239464-1c700a00-b49a-11eb-883d-a88d8a3527fb.png)

**Comment by dbaeumer** [comment]
@markchagers this a a TypeScript error (noticeable through the ts in front of the error code) and not an ESLint error. Please report the problem againts TypeScript itself.
