### ISSUE TITLE
CTRL + S will fix errors, but not autosave

### ISSUE THREAD

**Issue by hasheri** [microsoft/vscode-eslint#1264]
This is my autosave and codeActionsOnSave setting:
```
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
},
"files.autoSave": "onFocusChange"
```

onFocusChange it will save the file but it will not fix errors until I press ctrl + s.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode/issues/123875
