### ISSUE TITLE
[Bug] No linting for `.ts` and `.tsx` files when using `vue-eslint-parser`

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode-eslint#1266]
Quote from [README.md](https://github.com/Microsoft/vscode-eslint#version-204):

> The 2.0.4 version of the extension contains the following major improvements:

> Improved TypeScript detection - As soon as TypeScript is correctly configured inside ESLint, you no longer need additional configuration through VS Code's eslint.validate setting. The same is true for HTML and Vue.js files.

Therefore, my config:

```json
{
  "eslint.validate": []
}
```

Repro: https://github.com/wenfangdu/vue-eslint-parser-repro

Seems when using `vue-eslint-parser`, `.ts` and `.tsx` files aren't auto-detected unless I explicitly specify:

```json
{
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ]
}
```

**Comment by dbaeumer** [comment]
This is actually by design since I didn't want to break existing users. You should simply remove the setting since it is not necessary for your setup anymore.

Let me know if everything works as expected when the setting is removed.

**Comment by wenfangdu** [comment]
I think you misunderstood the issue, pardon me if I'm wrong. My previous config `"eslint.validate": []` caused `.ts` and `.tsx` not being linted, only after using the following config, the linting took effect.

```json
{
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ]
}
```

You can try my [repro](https://github.com/wenfangdu/vue-eslint-parser-repro) with this config `"eslint.validate": []` and see if linting is on.

**Comment by dbaeumer** [comment]
I cloned the repository as is and it works for me out of the box

<img width="382" alt="capture" src="https://user-images.githubusercontent.com/1931590/120334728-2b0b4d80-c2f1-11eb-858d-1be13531bc3f.png">

**Comment by dbaeumer** [comment]
Any additional steps?

**Comment by wenfangdu** [comment]
@dbaeumer No, there's none. It's quite strange, I'm using the following as a workaround now, no problems so far:

```json
{
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ]
}
```

**Comment by dbaeumer** [comment]
That is really strange since it works for me without the `eslint.validate` setting.

**Comment by baranelitez** [comment]
@wenfangdu are you using windows by any chance? if so, can you try the same repo in another windows computer along with linux/osx? My findings are that it fails without that validate options if you use windows, whereas in linux/OSX, it works out of the box.

**Comment by wenfangdu** [comment]
> @wenfangdu are you using windows by any chance? if so, can you try the same repo in another windows computer along with Linux/OSX? My findings are that it fails without that validate options if you use windows, whereas, in Linux/OSX, it works out of the box.

@baranelitez  Yes, I'm using Windows 10.

@dbaeumer I think this might be the reason?

**Comment by wenfangdu** [comment]
@dbaeumer Sorry to bother 🙏, is it released? It's still reproducible for me.

**Comment by dbaeumer** [comment]
Only has a new insider here: https://github.com/microsoft/vscode-eslint/releases/tag/release%2F2.1.24-Insider

If you want to give it a try you can download the VSIX and install using the `Install from VSIX command` in VS Code.

**Comment by dead-claudia** [comment]
Any updates? Still reproduces for me today.
