### ISSUE TITLE
it keeps creating new entries in the formatter menu

### ISSUE THREAD

**Issue by OneOfOne** [microsoft/vscode-eslint#1268]
Simply installing the extension and setting it as the default formatter keep adding a new entry to the formatters menu every time you save.

![Screenshot_20210521_111734](https://user-images.githubusercontent.com/1080443/119168085-278ce200-ba26-11eb-88e8-89ba505b6c3a.png)

**Comment by dbaeumer** [comment]
I can't reproduce this.

<img width="511" alt="capture" src="https://user-images.githubusercontent.com/1931590/119557451-7f1dab80-bda0-11eb-853e-b9208cf94915.png">

Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
