### ISSUE TITLE
eslint problem

### ISSUE THREAD

**Issue by rjz0528** [microsoft/vscode-eslint#1269]
Getting code operation (configuration) from "'Vetur','ESLint'". Probably can verify 20 3 ten seconds. It's always like this for too long，Below is my configuration

{
"window.zoomLevel": 0,
"eslint.workingDirectories": [
    ".eslintrc.js",
    {
        "mode": "auto"
    }
],
"eslint.autoFixOnSave": true,
"eslint.validate": [
    "javascript",
    {
        "language": "vue",
        "autoFix": true
    }
],
"vue-helper.alias": {
    "@": "src"
},
"vue-helper.componentPrefix": {
    "alias": "@",
    "path": "src"
},
"editor.fontSize": 13,
"editor.tabSize": 2,
"emmet.triggerExpansionOnTab": true,
"diffEditor.ignoreTrimWhitespace": false,

// "editor.codeActionsOnSave": {
//     "source.fixAll.eslint": true
// },
"eslint.format.enable": true,
"files.associations": {
    "*.nvue": "vue"
},
"editor.minimap.enabled": true,
"workbench.iconTheme": "vscode-icons",
"[vue]": {
    "editor.defaultFormatter": "octref.vetur"
},
"git.autofetch": true,
"git.confirmSync": false,
"liveServer.settings.donotShowInfoMsg": true,
"[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
},
"vsicons.dontShowNewVersionMessage": true,
"[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
},
"workbench.startupEditor": "newUntitledFile",
"hediet.vscode-drawio.local-storage": "eyIuZHJhd2lvLWNvbmZpZyI6IntcImxhbmd1YWdlXCI6XCJcIixcImN1c3RvbUZvbnRzXCI6W10sXCJsaWJyYXJpZXNcIjpcImdlbmVyYWxcIixcImN1c3RvbUxpYnJhcmllc1wiOltcIkwuc2NyYXRjaHBhZFwiXSxcInBsdWdpbnNcIjpbXSxcInJlY2VudENvbG9yc1wiOltcIkZGRkZGRlwiXSxcImZvcm1hdFdpZHRoXCI6MjQwLFwiY3JlYXRlVGFyZ2V0XCI6ZmFsc2UsXCJwYWdlRm9ybWF0XCI6e1wieFwiOjAsXCJ5XCI6MCxcIndpZHRoXCI6ODI3LFwiaGVpZ2h0XCI6MTE2OX0sXCJzZWFyY2hcIjp0cnVlLFwic2hvd1N0YXJ0U2NyZWVuXCI6dHJ1ZSxcImdyaWRDb2xvclwiOlwiI2QwZDBkMFwiLFwiZGFya0dyaWRDb2xvclwiOlwiIzZlNmU2ZVwiLFwiYXV0b3NhdmVcIjp0cnVlLFwicmVzaXplSW1hZ2VzXCI6bnVsbCxcIm9wZW5Db3VudGVyXCI6MCxcInZlcnNpb25cIjoxOCxcInVuaXRcIjoxLFwiaXNSdWxlck9uXCI6ZmFsc2UsXCJ1aVwiOlwiXCJ9In0=",
"[jsonc]": {
    "editor.defaultFormatter": "vscode.json-language-features"
},
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
}
}

**Comment by rjz0528** [comment]
The one above is to turn off "source.fixAll.eslint": true so that it will not go back to automatic formatting

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are experiencing. This should include detailed steps on how to reproduce the issue with a description what you expect to happen.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
