### ISSUE TITLE
How to configure additional rules directory like WebStorm

### ISSUE THREAD

**Issue by ApsarasX** [microsoft/vscode-eslint#1271]
I plan to submit a pull request to the TypeScript compiler.

After following the instructions of typescript's CONTRIBUTE.md, I encountered the following problem.
![image](https://user-images.githubusercontent.com/24390069/119471142-99915e00-bd7b-11eb-8c60-8c5978e2d05f.png)

These rule files are under the `script/eslint/rules`.

In WebStorm, I can configure `additional rules directory` to solve this problem.

But in `vscode-eslint`, I cannot found similar options.

![5C0FEC5E492EB3C8EEE36C7D8C7FB059](https://user-images.githubusercontent.com/24390069/119471734-263c1c00-bd7c-11eb-9b99-db9c5b903c57.jpg)

**Comment by dbaeumer** [comment]
What happens if you validate that file in the terminal. Do you see the same error. VS Code solely relies on the mechanisms that ESLint itself when executed in the terminal provides for customization.

**Comment by ApsarasX** [comment]
When I execute eslint in the terminal, there is no error. But when I open the typescript-compiler code in vscode, a lot of red squiggles appear in the editor window. After exploring, I found that my terminal script used `--rulesdir` option of eslint, which corresponds to the `eslint.option.rulePaths` option of `vscode-eslint`. It's my bad. Sorry.

**Comment by dbaeumer** [comment]
No problem.
