### ISSUE TITLE
Require path problem

### ISSUE THREAD

**Issue by myNameIsDu** [microsoft/vscode-eslint#1272]
Just like the [question](https://github.com/eslint/eslint/discussions/14611) says

He wasn't able to find the correct path. Besides, I had two projects open in one workspace, which is not a problem when I open a project in a workspace alone

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
I would guess that you need to setup the `eslint.workingDirectories`

**Comment by myNameIsDu** [comment]
> I would guess that you need to setup the `eslint.workingDirectories`

Yes it can, but why does it need to be set when using old babel-eslint didn't have this problem when opening multiple projects in the previous IDE window

**Comment by dbaeumer** [comment]
I can't answer the questions with a steps on how to reproduce this best via a GitHub repository I can clone.

**Comment by myNameIsDu** [comment]
@dbaeumer 
You can check out this [repository](https://github.com/myNameIsDu/eslint-parser)

**Comment by dbaeumer** [comment]
The same can be reproduced in the terminal when running eslint in the workspace root:

```
codespace ➜ /workspaces/eslint-parser (main) $ ./test1/node_modules/.bin/eslint ./test1/src/index.js 

/workspaces/eslint-parser/test1/src/index.js
  0:0  error  Parsing error: Cannot find module '@babel/preset-env'
Require stack:
- /workspaces/eslint-parser/test1/node_modules/@babel/core/lib/config/files/plugins.js
- /workspaces/eslint-parser/test1/node_modules/@babel/core/lib/config/files/index.js
- /workspaces/eslint-parser/test1/node_modules/@babel/core/lib/index.js
- /workspaces/eslint-parser/test1/node_modules/@babel/eslint-parser/lib/worker/babel-core.cjs
- /workspaces/eslint-parser/test1/node_modules/@babel/eslint-parser/lib/worker/index.cjs
- /workspaces/eslint-parser/test1/node_modules/@babel/eslint-parser/lib/client.cjs
- /workspaces/eslint-parser/test1/node_modules/@babel/eslint-parser/lib/analyze-scope.cjs
- /workspaces/eslint-parser/test1/node_modules/@babel/eslint-parser/lib/index.cjs
- /workspaces/eslint-parser/test1/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /workspaces/eslint-parser/test1/node_modules/@eslint/eslintrc/lib/index.js
- /workspaces/eslint-parser/test1/node_modules/eslint/lib/cli-engine/cli-engine.js
- /workspaces/eslint-parser/test1/node_modules/eslint/lib/eslint/eslint.js
- /workspaces/eslint-parser/test1/node_modules/eslint/lib/eslint/index.js
- /workspaces/eslint-parser/test1/node_modules/eslint/lib/cli.js
- /workspaces/eslint-parser/test1/node_modules/eslint/bin/eslint.js

✖ 1 problem (1 error, 0 warnings)
```

So you need to sepcific `test` as a working directory to get the working properly in VS Code ESLint extension.

**Comment by myNameIsDu** [comment]
> The same can be reproduced in the terminal when running eslint in the workspace root:
> 
> ```
> codespace ➜ /workspaces/eslint-parser (main) $ ./test1/node_modules/.bin/eslint ./test1/src/index.js 
> 
> /workspaces/eslint-parser/test1/src/index.js
>   0:0  error  Parsing error: Cannot find module '@babel/preset-env'
> Require stack:
> - /workspaces/eslint-parser/test1/node_modules/@babel/core/lib/config/files/plugins.js
> - /workspaces/eslint-parser/test1/node_modules/@babel/core/lib/config/files/index.js
> - /workspaces/eslint-parser/test1/node_modules/@babel/core/lib/index.js
> - /workspaces/eslint-parser/test1/node_modules/@babel/eslint-parser/lib/worker/babel-core.cjs
> - /workspaces/eslint-parser/test1/node_modules/@babel/eslint-parser/lib/worker/index.cjs
> - /workspaces/eslint-parser/test1/node_modules/@babel/eslint-parser/lib/client.cjs
> - /workspaces/eslint-parser/test1/node_modules/@babel/eslint-parser/lib/analyze-scope.cjs
> - /workspaces/eslint-parser/test1/node_modules/@babel/eslint-parser/lib/index.cjs
> - /workspaces/eslint-parser/test1/node_modules/@eslint/eslintrc/lib/config-array-factory.js
> - /workspaces/eslint-parser/test1/node_modules/@eslint/eslintrc/lib/index.js
> - /workspaces/eslint-parser/test1/node_modules/eslint/lib/cli-engine/cli-engine.js
> - /workspaces/eslint-parser/test1/node_modules/eslint/lib/eslint/eslint.js
> - /workspaces/eslint-parser/test1/node_modules/eslint/lib/eslint/index.js
> - /workspaces/eslint-parser/test1/node_modules/eslint/lib/cli.js
> - /workspaces/eslint-parser/test1/node_modules/eslint/bin/eslint.js
> 
> ✖ 1 problem (1 error, 0 warnings)
> ```
> 
> So you need to sepcific `test` as a working directory to get the working properly in VS Code ESLint extension.

I think that's the way it usually works: cd test1 => ./node_modules/eslint/bin/eslint ./src (npm run lint)

The old version of babel-eslint worked, so why use it the way it is now, I don't think it conforms to normal operating practices :raising_hand:

**Comment by dbaeumer** [comment]
This is outside of my control. The extension behaves like eslint behaves on the command line sine it shares the same code.

**Comment by myNameIsDu** [comment]
> This is outside of my control. The extension behaves like eslint behaves on the command line sine it shares the same code.

Well, thank you very much for your answer
