### ISSUE TITLE
How to eslint javascript in html file for undefined variables without project?

### ISSUE THREAD

**Issue by rain1** [microsoft/vscode-eslint#1273]
Hi!

I installed vscode eslint addon. I want to eslint html file for undefined variables without having to create a project for this html file.

I added these lines to User\settings.json
```
    "eslint.validate": ["javascript", "javascriptreact", "html"],
    "extends":"eslint:recommended"
```

But it doesnt seem to care about unused variables. What should I do?

**Comment by dbaeumer** [comment]
@rain1 does validation happen correctly in the terminal?

**Comment by rain1** [comment]
How do I test it in terminal?

**Comment by dbaeumer** [comment]
Open a terminal on the workspace and type `./node_modules/.bin/eslint {file to validate}`

**Comment by rain1** [comment]
Can I tell it to use VS Code configuration? Looks like command line does not see that I have already configured it on VS Code:

> ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

**Comment by dbaeumer** [comment]
The eslint command has a `--config` option to point it to an eslint config file.

**Comment by rain1** [comment]
My VSCode config file C:\Users\Rain\AppData\Roaming\Code\User\settings.json is this:

```
{
    "workbench.colorTheme": "Visual Studio Light",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "window.title": "${dirty}${activeEditorLong}${separator}${rootName}${separator}${appName}",
    "workbench.settings.editor": "json",
    "eslint.validate": ["javascript", "javascriptreact", "html"],
    "extends":"eslint:recommended"
}
```

This is what file > Preferences > Settings edits. Is this correct configuration file given that I wish to use eslint without project? I mean I want to open any html file anywhere in the disk and have it eslinted by VSCode.

I am asking this because after running:
`eslint C:\extracted\snip\City\test.html --config C:\Users\Rain\AppData\Roaming\Code\User\settings.json`

It complained:

> Oops! Something went wrong! :(
> 
> ESLint: 7.27.0
> 
> Error: ESLint configuration in --config is invalid:
>         - Unexpected top-level property "workbench.colorTheme".
> 
>     at ConfigValidator.validateConfigSchema (C:\extracted\node\node_modules\eslint\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:273:19)
>     at ConfigArrayFactory._normalizeConfigData (C:\extracted\node\node_modules\eslint\node_modules\@eslint\eslintrc\lib\config-array-factory.js:644:19)
>     at ConfigArrayFactory._loadConfigData (C:\extracted\node\node_modules\eslint\node_modules\@eslint\eslintrc\lib\config-array-factory.js:609:21)
>     at ConfigArrayFactory.loadFile (C:\extracted\node\node_modules\eslint\node_modules\@eslint\eslintrc\lib\config-array-factory.js:475:40)
>     at createCLIConfigArray (C:\extracted\node\node_modules\eslint\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:171:35)
>     at new CascadingConfigArrayFactory (C:\extracted\node\node_modules\eslint\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:243:29)
>     at new CLIEngine (C:\extracted\node\node_modules\eslint\lib\cli-engine\cli-engine.js:563:36)
>     at new ESLint (C:\extracted\node\node_modules\eslint\lib\eslint\eslint.js:432:27)
>     at Object.execute (C:\extracted\node\node_modules\eslint\lib\cli.js:290:24)
>     at main (C:\extracted\node\node_modules\eslint\bin\eslint.js:132:52)


From that I read that it does not like to be in same configuration file with rest of VSCode options. From readme in this reposotory I did not find any better ideas. how to configure it  to run without having to create project.

**Comment by dbaeumer** [comment]
@rain1 you need to point it to your `.eslintrc.json` file. See https://eslint.org/docs/user-guide/configuring/configuration-files

**Comment by rain1** [comment]
After doing some research it looks like it's not possible to get eslint to work  with html files. 

Should I make feature request for plugin developers to make it so that vscode-eslint would auto-configure  eslint? I mean instead of every developer doing 2 months of research on their own to get eslint work with html files out of the box it would be better solution in my opinion of this plugin worked out of box.

**Comment by dbaeumer** [comment]
For me setting up ESLint with HTML files was always easy  using this plugin. Can you explain why you think this is not enough: https://github.com/BenoitZugmeyer/eslint-plugin-html

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
