### ISSUE TITLE
Link in hover item is invalid

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode-eslint#1274]
Issue Type: <b>Bug</b>

In a TypeScript project, I have this line in a file:
```ts
const path = require("path");
```
`require("path")` will have red squiggly lines under it. If I hover over the element, I get a popover describing the issue as:
> Require statement not part of import statement.eslint@typescript-eslint/no-var-requires

The last part of which is a link that, when clicked, leads to an invalid URL:
```
https://github.com/typescript-eslint/typescript-eslint/blob/v%5Bobject%20Object%5D/packages/eslint-plugin/docs/rules/no-var-requires.md
```

![image](https://user-images.githubusercontent.com/1658949/120345805-192ea800-c2fb-11eb-95bd-f0cbdefb9f91.png)

Extension version: 2.1.20
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (25.42GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (29.96GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (29.96GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (29.96GB free)|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
The version information in that link seems broken. The setup seems to depend on which version are installed. So can you please provider me with a GitHub repository I can clone that demos what you are seeing.

**Comment by oliversalzburg** [comment]
This project should show the issue in `source/test.js`: https://github.com/oliversalzburg/vscode-eslint-version-repro

I'm assuming this is possibly connected to yarn/PnP, if it hasn't come up before.

**Comment by dbaeumer** [comment]
Thanks for the test case. It has nothing to do with yarn. If that would cause problems than ESLint wouldn't work at all.

**Comment by dbaeumer** [comment]
I looked at it and I already get a broken URI from `@typescript-eslint/eslint-plugin`

<img width="831" alt="capture" src="https://user-images.githubusercontent.com/1931590/120615947-1649c980-c459-11eb-8d97-08f0b215e7ef.png">

There is nothing I can do about that. Can you please report the issue against `@typescript-eslint/eslint-plugin`
