### ISSUE TITLE
Plugin fails when specifying a different eslint config

### ISSUE THREAD

**Issue by flapjackfritz** [microsoft/vscode-eslint#1276]
When I have multiple eslint configs for multiple folders (mono repo situation), the plugin seems to fail because it thinks that there are multiple installs of the same package. While technically this is true, it shouldn't matter because the different folders have different npm modules installed, which is desirable.

So I have:
.eslintrc.js
.dev.eslintrc.js

The .dev.eslintrc.js file is a configuration I use in my IDE to have a much stricter set of rules than I use when I push code to the repo. I want a different set of rules warnings/errors than I want to stop me from pushing code.

I get the error:
[Info  - 5:20:51 pm] Plugin "react" was conflicted between "--config" and ".eslintrc.js".

I think this is incorrect because I am not even wanting to use a `.eslintrc.js` file in my VS code plugin at all - so why is it trying to use one?

I have created an example repo to show this error in the simplest way I can. This appears to only happen in windows, but function normally in OSX.

https://github.com/flapjackfritz/vscode-eslint-example-fail

**Comment by flapjackfritz** [comment]
On further investigation, it appears this configuration works just fine in the root of the project, it just doesn't work when the eslint config is in a folder, it doesn't even need multiple npm modules in the project.

**Comment by dbaeumer** [comment]
There is a setting to control which ESLint config file the extension uses. The setting is `eslint.options`. See https://github.com/Microsoft/vscode-eslint

Please let me know if this works.

**Comment by flapjackfritz** [comment]
@dbaeumer if you take a look in the repo I provided, in `.vscode/settings.json` you will see I've already configured that setting to use the `.dev.eslintrc.js` configuration -- when I turn it off, it works by going back to the base `.eslintrc.js` file, but that is not the configuration I wish to use with this plugin, I wish to use a different one.

**Comment by flapjackfritz** [comment]
In fact - if I delete the base `.eslintrc.js` file from the repo leaving just the `.dev.eslintrc.js` file, then the plugin works as expected. It seems that it only fails to work when there are multiple eslint configs in a file, and I attempt to use the one that's not default named.

**Comment by dbaeumer** [comment]
Actually it works for me as expected: 

<img width="1007" alt="capture" src="https://user-images.githubusercontent.com/1931590/121645007-0010be80-ca94-11eb-869f-a644ab1dda7a.png">

Am I missing something?

**Comment by flapjackfritz** [comment]
Yes. This issue only happens in windows, it works fine in OSX.

**Comment by flapjackfritz** [comment]
running those commands works just fine though:

![Uploading eslintrunworks.PNG…]()

**Comment by dbaeumer** [comment]
Sorry, not my day.

I have no idea why this is only happening under Windows :-). 

The error message you are seeing comes from ESLint itself and not from the extension. I tried to use `useEslintrc` which makes the error go away since the configurations aren't merged. But not sure if this result in the expected result.

**Comment by dbaeumer** [comment]
This fails deep in a eslint node module when comparing file paths. 

<img width="710" alt="capture" src="https://user-images.githubusercontent.com/1931590/121682630-9d7fe880-cabc-11eb-926f-ebcd046a8161.png">

Problem is that one has a lower case drive letter and one an upper case :-)

**Comment by flapjackfritz** [comment]
I've got the repo cloned, but I'm not entirely sure how to build and use it to try it out locally. Not sure when the next release will be.
