### ISSUE TITLE
Parsing error: This experimental syntax requires enabling one of the following parser plugins

### ISSUE THREAD

**Issue by jnaklaas** [microsoft/vscode-eslint#1277]
I use webpack + babel for building / transpiling my roots/sage project. It contains a react component, which is throwing an error when enabling the vscode-eslint plugin.

```Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript' (26:13)```

Webpack uses eslint (local) and some plugins to properly validate and transpile the code, which works just fine. When enabled, I still receive above parsing error.

I have an .eslintrc.js file 
```javascript
module.exports = {
  root: true,
  extends: ['eslint:recommended', 'plugin:react/recommended'],
  globals: {
    wp: true,
  },
  env: {
    node: true,
    es6: true,
    amd: true,
    browser: true,
    jquery: true,
  },
  parser: '@babel/eslint-parser',
  parserOptions: {
    ecmaFeatures: {
      globalReturn: true,
      generators: false,
      objectLiteralDuplicateProperties: false,
      experimentalObjectRestSpread: true,
    },
    ecmaVersion: 2017,
    sourceType: 'module',
    requireConfigFile: false,
  },
  plugins: ['import'],
  settings: {
    'import/core-modules': [],
    'import/ignore': [
      'node_modules',
      '\\.(coffee|scss|css|less|hbs|svg|json)$',
    ],
  },
  rules: {
    'no-console': 0,
    quotes: ['error', 'single'],
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'ignore',
      },
    ],
  },
};
```

**Comment by dbaeumer** [comment]
@jnaklaas what happens when you use eslint directly on the terminal. The VS Code extension tries to stay compatible with config resolving, etc. with what ESLint does in the terminal.

**Comment by dbaeumer** [comment]
What I mean don't try to run eslint through webpack.

**Comment by dbaeumer** [comment]
If you can't make eslint work in the terminal you can always run the webpack as a task in VS Code and attach a problem matcher to that task. This will capture the errors as well.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
