### ISSUE TITLE
can't load eslint localy

### ISSUE THREAD

**Issue by obhakim** [Microsoft/vscode-eslint#128]
hi,i have eslint installed locally in my project 'Meteor' i got this message: Failed to load eslint library. Please install eslint in your workspace folder using 'npm install eslint' or globally using 'npm install -g eslint' and then pre...

i want vscode detect the local version eslint.thanks

**Comment by dbaeumer** [comment]
It should. However the current available version only detects a local install version if it is installed in the workspace folder opened in VS Code. It will not detect it in parent folders. 

This will change with the next update of VS Code. Besides looking up the parent chain the extension will also provide a nodePath setting if the eslint library is installed at an unusual location.
