### ISSUE TITLE
Toggling ESLint on and off for the workspace

### ISSUE THREAD

**Issue by skanev** [microsoft/vscode-eslint#1281]
Hey.

Previous ESLint could be toggled on and off for the workspace. I found this useful, as warnings are incredibly distracting some of the time I'm writing code. To explain what I mean:

1. I decide to introduce a new function
2. I go and define it before having any callers
3. I'll add a caller in a bit, but I want to fiddle with it for a while and make sure it has the right signature
4. While this is going on, I'm keenly interested in (a) TypeScript errors, and uninterested in (b) ESLint errors. I'm getting a bunch of stuff highlighted red, however, and I have to go and check to see if it's (a) or (b), because I need to action (a) now and I'd postpone actioning (b) until I'm ready. Being able not get ESLint errors at this stage is valuable for me
5. Once I'm done and ready to test, I'd turn eslint on again and see if there is an error

In earlier version of the plugin, there was a Toggle ESLint command. I can't find it anymore. Am I missing something? If not, can it be reimplemented?

**Comment by dbaeumer** [comment]
Since VS Code now offers to enabled/disabled extensions per workspace I remove the UI around it  from the ESLint extension. This avoids shipping a duplicate feature set.

Please ping if this doesn't work for you.

**Comment by skanev** [comment]
@dbaeumer It doesn’t.

I have to reload Code to do it and there is no command ao it’s very involved.

also, I don’t need it strictly  per workspace - per file works to.

**Comment by dbaeumer** [comment]
I only removed the commands (UI), the setting is still there `eslint.enable` though deprecated. Can you let me now if the setting is in general all you need?

**Comment by skanev** [comment]
Almost.

Changing it stops new problems from appearing (which is what I want), but doesn't clear existing problems (which is also what I want). If you can de-deprecate (reprecate? heh) the setting and add back the Toggle command, to have it also clear problems, it would be perfect.

**Comment by fritzfr** [comment]
I'm also in favour of bringing this back. I always used it in the past for when I just want to read code and not have every single line underlined in red. Please bring this back.

**Comment by dbaeumer** [comment]
PR welcome :-)

**Comment by dbaeumer** [comment]
Version 2.2.0 has the setting reenabled.
