### ISSUE TITLE
After running eslint - the problems do not show up.

### ISSUE THREAD

**Issue by spetes375** [microsoft/vscode-eslint#1285]
Issue Type: <b>Bug</b>

Hello VSC - 

After installing the ESlint plugin from the market place and running eslint there are hundreds of errors picked up in my terminal (Strings must use singlequote for example) but there is not blue light bulb to fix all/anything under the Problems tab or available above in the work space. I occasionally see a yellow lightbulb but no option to fix all and only limited options.

Thank you for the help

Extension version: 2.1.23
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

**Comment by dbaeumer** [comment]
Can you please provide steps on how to reproduce what you are seeing, best by providing a GitHub repository I can clone.

**Comment by spetes375** [comment]
Hi Dirk and thank you for the assistance. 

1. Install ESLint
2. run lint command 
3. view erros in command line
4. Go to the problems tab in VS code or the file 
5. The only option via right click in the problems tab is a copy or copy message  
6. The only option via the file is a yellow light bulb that when clicking on show fixes says "Generate get and set accessors" or "Learn more about JS/TS refactorings"

**Comment by dbaeumer** [comment]
@spetes375 this works for me in my setups. So a GitHub repository I can clone is highly appreciated.

<img width="316" alt="capture" src="https://user-images.githubusercontent.com/1931590/123689835-f89f3280-d853-11eb-88d1-d13c06f9b267.png">

**Comment by spetes375** [comment]
I appreciate your help. At this point I'm thinking it may be faster to uninstall and start with a fresh install of VS Code and then a fresh install of ESLint. Do you have advice on this process or just follow the normal steps?
Thanks again.

**Comment by dbaeumer** [comment]
Just follow normal steps.

**Comment by spetes375** [comment]
I have followed the steps in the below link (including rm -rf ~/.vscode*) and reinstalled VSCode and ESlint. 

lerna run lint produces 
'error  Strings must use singlequote                    @typescript-eslint/quotes'
 
but unfortunately it looks like ESLint is not giving me the option to fix it. Note -  I haven't modified the settings for ESLint extension. Would you suggest I change something in the settings? 

[Info  - 3:56:47 PM] ESLint server is running.

![image](https://user-images.githubusercontent.com/35789681/123858745-df4cc380-d8f1-11eb-9eb4-9dff94f05945.png)



https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vscode-on-mac

**Comment by spetes375** [comment]
Just a follow up that I have tried { "mode": "auto" }  as the "eslint.workingDirectories" in the User and Workspace settings but to no avail. Thank you again for looking into this as my coworkers are enjoying ESLint. They had a permission issue in the past but it was resolved.

**Comment by dbaeumer** [comment]
@spetes375 best would be you provide me with a GitHub repository I can clone that demos what you are experience. Otherwise it is hard to tell what is going on.

**Comment by spetes375** [comment]
It is now working post reinstall. Thank and and congratulations on build an awesome tool. Thanks!
