### ISSUE TITLE
allow configuring path to eslint config for working directories

### ISSUE THREAD

**Issue by GiladShoham** [microsoft/vscode-eslint#1286]
Hi,
I have a unique use case where I have many components in my root folder, each one of these components has its own lint configuration located somewhere else (somewhere in the node_modules) let's say.
Some of the components are using the same eslint config, but I might have let's say 100 components that use 10 different eslint configs in the same project.
One solution is to create on each one of the components a eslint config which extends the real config from the node_modules, but this will make my entire project full of eslint config everywhere.
I wish to have a way, to configure for each working directory a path to its eslint config.
Something like (hasn't thought the nameing through):
```js
"eslint.workingDirectories": [
  {
    "workingDirPath": "./component-1",
    "configPath": "node_modules/eslint1/eslintrc"
  },
  {
    "workingDirPath": "./component-2",
    "configPath": "node_modules/eslint2/eslintrc"
  }
]
```
Even better, will be a way to provide for specific config all the working dir that should use it. 
something like:
```js
"eslint.workingDirectories": [
  {
    "configPath": "node_modules/eslint1/eslintrc",
    "workingDirPaths": ["./component-1", "./component-3", "./other-components/**"],
  },
  {
    "configPath": "node_modules/eslint2/eslintrc",
    "workingDirPaths": ["./component-2", "./component-4"],
  }
]
```

Thanks!

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
