### ISSUE TITLE
Add a "search paths" option

### ISSUE THREAD

**Issue by jsumners** [microsoft/vscode-eslint#1288]
Currently, this extension has a `eslint.nodePath` option that allows specifying a known directory for finding the `eslint` executable. This does not solve a very specific problem for me:

I have a project that looks like:

```
❯ tree -L 4
.
├── index.js
├── node_modules
│   └── standard
│       ├── AUTHORS.md
│       ├── CHANGELOG.md
│       ├── LICENSE
│       ├── README.md
│       ├── RULES.md
│       ├── bin
│       │   └── cmd.js
│       ├── eslintrc.json
│       ├── index.js
│       ├── node_modules
│       │   ├── eslint
│       │   ├── eslint-config-standard
│       │   ├── eslint-config-standard-jsx
│       │   ├── eslint-plugin-import
│       │   ├── eslint-plugin-node
│       │   ├── eslint-plugin-promise
│       │   ├── eslint-plugin-react
│       │   └── standard-engine
│       ├── options.js
│       └── package.json
└── package.json

12 directories, 12 files
```

Notice that the `eslint` package is in a nested `node_modules` directory. This means the VSCode extension will not find the executable and thus will not show lint errors or automatically fix errors on save within this project.

What I would like to see is an option like `eslint.searchPaths = []` which could be altered to something like:

```js
eslint.searchPaths = ['built-in', `${workspaceDir}/node_modules/standard/node_modules`]
```

Where the special "buit-in" string would include the current paths that the extension searches.

I think this issue is very similar to #1286 but not quite the same.

---

**.npmrc**
```
save-prefix=^
package-lock=false
```

**package.json**
```json
{
  "devDependencies": {
    "standard": "^16.0.3"
  }
}
```

**index.js**
```js
'use strict';

function thisFileHasLintErrors() {
return true
}

thisFileHasLintErrors()

```

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!

**Comment by jsumners** [comment]
I'm not really sure that is fair considering this issue wasn't opened on a Microsoft owned VSCode repo to start with. I think it's also described fairly well and would be easy for anyone with knowledge of the codebase to implement.
