### ISSUE TITLE
Can not read config file correctly in a subdirectory!

### ISSUE THREAD

**Issue by beginor** [microsoft/vscode-eslint#1289]
I have a `client` folder in my project, which contains all client files like ( `node_modules`,`.eslintrc.json`), project structor is

- `client/.eslintrc.json` client root eslint config, which loads `client/tsconfig.json`
- `client/projects/web/.eslintrc.json` eslint config for project `web` , which loads `client/projects/web/tsconfig.app.json`
- `client/projects/handset/.eslintrc.json` eslint config for project `handset` , which loads `client/projects/handset/tsconfig.app.json`

when I open file `client/projects/web/src/main.ts`, I got an error from eslint 

`Parsing error: Cannot read file '~/net-core-app/projects/web/tsconfig.app.json'. eslint`

But the  correct path should be `~/net-core-app/client/projects/web/tsconfig.app.json`

<img width="985" alt="Screen Shot 2021-07-02 at 07 38 03" src="https://user-images.githubusercontent.com/159065/124200681-8acf6100-db08-11eb-8dc5-4c0ead90831c.png">

And my project is here <https://github.com/beginor/net-core-app>

**Comment by dbaeumer** [comment]
@beginor  does the validation happen correctly when you use eslint in the terminal (e.g. using the workspace folder as the current cwd and executing `eslint client/projects/web/src/main.ts`. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by beginor** [comment]
The repository is here <https://github.com/beginor/net-core-app> .

The root folder of the workspaceis not a nodejs project, there is no `node_modules` in it, if I run `eslint` in the root folder, I can get the same error.

The `client` folder is an angular project, which is a nodejs project, so I run `npm run lint` at the `client` folder,  which calls will call eslint , the output is correct, the command works.

This issue only occurs in editor of vscode when I open a .ts file in the client folder .

I have just switch from tslint to eslint, since tslint is obsoleted, but this works with tslint before.

**Comment by dbaeumer** [comment]
This then sounds like a configuration problem with ESLint itself (if you see it in the terminal). Try if you can run eslint correctly when you are in the client folder. If this is the case then you need to let VS Code know about this as well using `eslint.workingDirectories`

**Comment by beginor** [comment]
Thanks you very much, eslint works as expected when I set `eslint.workingDirectories=["cients"]` in my projects.

**Comment by dbaeumer** [comment]
Closing the issue then.
