### ISSUE TITLE
Forgetting "use strict" results in the entire file being underlined

### ISSUE THREAD

**Issue by paulsmithkc** [microsoft/vscode-eslint#1290]
With the rule configuration `strict: ['warn', 'global']`

If you forget to include the `'use strict'` directive at top of the file, it highlights the entire file, rather than just the first line.

![image](https://user-images.githubusercontent.com/6501079/124312495-07783480-db35-11eb-93b2-9699628aea74.png)

Expected behavior would be to only show the error/warning on the first line.

**Comment by dbaeumer** [comment]
This is what ESLint reports (e.g. the eslint command line tool). I stayed away tweaking positions and offset I receive from ESLint and I want to keep it that way.

**Comment by paulsmithkc** [comment]
Okay, thank you. I will move this discussion over to the eslint project. 

[Issue 14782](https://github.com/eslint/eslint/issues/14782)
