### ISSUE TITLE
Unexpected top-level property "overrides[0].extends"

### ISSUE THREAD

**Issue by rencoo** [microsoft/vscode-eslint#1293]

**Comment by rencoo** [comment]
i just resolve this problem by put 'extends' property to the right place 'parserOptions'

**Comment by rencoo** [comment]
they nested extends under parserOptions.

**Comment by rencoo** [comment]
`

// .eslintrc.js
module.exports = {
   // other configs
   overrides: [
   {
      // TypeScript
      files: ["**/*.ts"],
      parser: "@typescript-eslint/parser",
      plugins: ["@typescript-eslint"],
      parserOptions: {
        sourceType: 'module',
        project: [
          "./tsconfig.eslint.json"
        ],
        tsconfigRootDir: __dirname
      },
      ecmaFeatures: {
        jsx: true
      },
      extends: [
        "plugin:@typescript-eslint/recommended"
      ],
      rules: {}
    }
   ]
}`

**Comment by rencoo** [comment]
it seems that 'extends' has been put to the wrong place, but the eslint document just told we should place it here

**Comment by dbaeumer** [comment]
@rencoo  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
