### ISSUE TITLE
eslint not working

### ISSUE THREAD

**Issue by RahulKandari-Github** [microsoft/vscode-eslint#1297]
Issue Type: <b>Feature Request</b>

Linter isn't showing error in any of the css, javascript or html files. In the last update it was working fine but the latest update doesn't highlight syntax erros. the built in linter also isn't working.

Extension version: 2.1.23
VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by dbaeumer** [comment]
@RahulKandari-Github  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by HomyeeKing** [comment]
@dbaeumer  I also met this situation, `eslint` disappear from the vscode status bar, and no red line error shows
and the project has .esintrc.js, what's the problem?

**Comment by HomyeeKing** [comment]
I guess I got the solution, eslint not auto crawl the `.eslintrc.*` config, I have to **enter the config file**  then I can set formatter to `eslint`, is that a bug

**Comment by dbaeumer** [comment]
In terms of lookup the extension works like the eslint command in the terminal. If you need to cd into a special directory in the terminal you need to let the extension know of this using `eslint.workingDirectories`

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
