### ISSUE TITLE
Ambiguous "Extension 'ESLint' cannot format x" error if eslint not installed

### ISSUE THREAD

**Issue by gpoole** [microsoft/vscode-eslint#1298]
I think that the error you get if you haven't installed eslint is a little ambiguous and making it more specific would help diagnose the problem faster.

I cloned a monorepo which has eslint as a dependency at the top level and then individual packages in subfolders. I remembered to run `npm install` in the sub-package folders but forgot to run it in the root folder. When trying to format a file I was seeing this error:

> Extension 'ESLint' cannot format '*.js'

Opening the eslint output pane I saw nothing to indicate anything was wrong, the complete output was:

> [Info  - 12:13:06 pm] ESLint server stopped.
> [Info  - 12:13:06 pm] ESLint server running in node v14.16.0
> [Info  - 12:13:06 pm] ESLint server is running.

After googling and reading issues for a while I eventually remembered what I'd forgotten to do, but a specific error indicating that eslint was not found in this case would be really helpful for spotting the problem.

**Comment by dbaeumer** [comment]
The feature has not gained any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
