### ISSUE TITLE
Extension 'ESLint' cannot format .ts

### ISSUE THREAD

**Issue by baranelitez** [microsoft/vscode-eslint#1299]
Hi. I'm having this problem where eslint cannot format TS files in my Vue project. Weird thing is, it does work correctly in Linux, and only fails to do so in Windows.

The things below applies to both my Windows and Linux systems:

- Eslint not globally installed (installed in project)
- Typescript not globally installed (installed in project)
- VSCode versions are same and all settings are synced.

The whole project structure is same. Copied and pasted (just removed and reinstalled node_modules upon switching OS). The configs are same also.

On Windows, I can lint .vue files and .js files. Just doesn't work with .ts

I've also tried adding "typescript" to probed languages list on Windows. Nothing changed. So I removed it (since my Linux system doesn't have it but succeeds in linting)

running `npx eslint .\src\main.ts --fix` in Windows does the linting. Just doesn't work when I try doing `Format Document` within vscode.

I've added `"eslint.trace.server": "verbose"` to my settings and here's what comes up:

```
[Trace - 4:54:46 PM] Received notification 'eslint/status'.
Params: {
    "uri": "file:///d%3A/programs/vue-test-2/src/test.js",
    "state": 1
}


[Trace - 4:54:46 PM] Received request 'eslint/probeFailed - (19)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/programs/vue-test-2/src/main.ts"
    }
}
```

note that it works good for the .js file, but fails for the .ts file

I'll push the project to a public repository so you can clone and check on your side, but I doubt you'll have the same issue (since it works fine on my linux system but fails on windows)

**Comment by baranelitez** [comment]
EDIT: repository is ready at https://github.com/baranelitez/eslint-vscode-troubleshooting

you can have multiple empty lines in this file between the two console.log's, and eslint will give a warning and fix them upon save:
https://github.com/baranelitez/eslint-vscode-troubleshooting/blob/main/src/test.js

https://github.com/baranelitez/eslint-vscode-troubleshooting/blob/main/src/main.ts
eslint won't give any warning for this file (only in windows). also it won't try to fix it when formatted via vscode. running `npx eslint .\src\main.ts --fix` will fix the problems.

**Comment by baranelitez** [comment]
Update:
Tried in two friends' computers. Windows and OSX. No prior VSCode or node.js installation.
OSX could show errors in ts files of this project while Windows failed to do so.

**Comment by baranelitez** [comment]
Another Update:
For whatever reason, Windows requires:
```
    "eslint.validate": [
    "typescript"
    ],
```
in settings. linux or OSX does not require this.

**Comment by dbaeumer** [comment]
Dups #1266 which I fixed today.
