### ISSUE TITLE
Disabling a line multiple times doesn't work correctly

### ISSUE THREAD

**Issue by rafaeltab** [microsoft/vscode-eslint#1305]
Hey there,

**Action**
Recently, I had to disable multiple different rules for a single line. I did this using the `CTRL + .` quick actions menu and then selecting `Disable <rulename> for this line` and then again for the next rule that needs to be disabled.

**Result**
This resulted in the following code
```ts
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
createdObj[currentObject] = val;
```

This does not even work and will still give the error for the first rule + the option to fix it again using quick actions resulting in the following:

```ts
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
createdObj[currentObject] = val;
```
(The same rule being disabled twice, but the second one still not being detected)

**Expected behavior**
```ts
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
createdObj[currentObject] = val;
```

**Comment by dbaeumer** [comment]
Got fixed in the meantime
