### ISSUE TITLE
Extension ignores eslintrc

### ISSUE THREAD

**Issue by Alterae** [microsoft/vscode-eslint#1306]
**Actual behavior:**
When I add a rule to `.eslintrc.json` (such as `"no-unused-vars": "off"`), the extension ignores this rule and still displays warnings for unused variables and function parameters.  This issue persists even after reloading the window or relaunching VS Code.  Running `eslint` via the command line behaves properly and respects the config file.

**Expected behavior:**
When I add a rule to `.eslintrc.json`, the extension should update to reflect that, properly highlighting and warning about issues, and (in this case), not displaying warnings for unused variables or function parameters.  It should show the same list of issues as running `eslint` from the command line.

**Additional info:**
- _OS version_: Windows 11 Home 21H2 (build `22000.100`)
- _WSL distro_: Ubuntu `20.04.2 LTS` (Focal Fossa)
- _VS Code version_: `1.58.2` (using the WSL remote for Ubuntu)
- _Extension version_: `2.1.23`
- _eslint version_: `7.31.0` (local install), `7.28.0` (global install)
- _Node version_: `16.4.2`

**Comment by jb-asi** [comment]
Bumped. Also occurring on macOS.

**Comment by dbaeumer** [comment]
When you run ESLint from the terminal do you change into a special directory. If so you need to let the exension know about this as well uisng the eslint.workingDirectories setting. If it works in the terminal from the workspace folder please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Alterae** [comment]
> When you run ESLint from the terminal do you change into a special directory. If so you need to let the exension know about this as well uisng the eslint.workingDirectories setting. If it works in the terminal from the workspace folder please provide me with a GitHub repository I can clone that demos what you are experiencing.

When I run ESLint from the terminal I simply run it from the root directory of the project (the same directory that VS Code is open in).

I'm not currently in a position to provide a demo repository but I will try to do so as soon as possible.

**Comment by chriskrycho** [comment]
@dbaeumer I don't *yet* have a demo repo, but I'm wondering: could this be an artifact of the workspace trust changes? The errors being reported are very clearly a case of *not* using the parser in the config: I have `@babel/eslint-parser` configured, and am seeing errors that the Babel config for the project means should *never* show up (they come from the default ESLint parser).

**Comment by chriskrycho** [comment]
Please ignore the previous: I was just invoking ESLint incorrectly.

**Comment by dbaeumer** [comment]
OK. Please ping if you have a demo repository.

**Comment by noahehall** [comment]
@dbaeumer I am experiencing the same issue: here is a link https://github.com/microsoft/vscode-eslint/issues/1316

**Comment by dbaeumer** [comment]
@noahehall commented in  your issue.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
