### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by suvamAdhikary** [microsoft/vscode-eslint#1308]
- Issue Type: `Performance`
- Extension Name: `vscode-eslint`
- Extension Version: `2.1.23`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MYPC~1\AppData\Local\Temp\dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by dbaeumer** [comment]
@suvamAdhikary do you still have the CPU profile?

**Comment by suvamAdhikary** [comment]
No, It's okay now, Thank you for the support.

**Comment by dbaeumer** [comment]
OK. Closing then.
