### ISSUE TITLE
Lint task: doesn't work without `node_modules` in workspace folder

### ISSUE THREAD

**Issue by Rabadash8820** [microsoft/vscode-eslint#1309]
I am working on a multiplayer game project, and the client- and server-side logic are included in separate root folders of my repository. Only the server-side folder contains TypeScript code, and therefore only that folder has the usual config files like `package.json` and `.eslintrc.js` file, and only that folder has `node_modules/`; there is no `node_modules/` folder at the root. The `lint whole folder` task does not work under these circumstances. Regardless of what paths I pass to the `eslint.options`, `eslint.workingDirectories`, or `eslint.lintTask.options` settings, the task always fails with:

>/usr/bin/bash: eslint: command not found
The terminal process "bash '-c', 'eslint .'" failed to launch (exit code: 127).

Looking through your source, it appears that the issue is in the [utils.findEslint](https://github.com/microsoft/vscode-eslint/blob/a0172c8645dd790df32a6c2b6436855eff470775/client/src/utils.ts#L18) function. It looks for `<rootPath>/node_modules/.bin/eslint.cmd` on win32 platforms, else `<rootPath>/node_modules/.bin/eslint` on linux, else a global `eslint`. `<rootPath>`, in turn, is apparently set to the root workspace folder in the [`FolderTaskProvider` constructor](https://github.com/microsoft/vscode-eslint/blob/a0172c8645dd790df32a6c2b6436855eff470775/client/src/tasks.ts#L15). So in my setup (repo opened under WSL2 on Windows 10, with no globally installed eslint package), the task fails b/c it can't find the local eslint in my server folder.

I considered opening a PR for this myself, but it will probably require a new config option, and that doesn't seem like my decision to make. 😛 Any other workarounds that I might've missed would be much appreciated!

**Comment by Rabadash8820** [comment]
For anyone else with this issue, my temporary workaround was to add a symlink to my local eslint with the following command:
```sh
ln --symbolic <root>/<subfolder>/node_modules/eslint/bin/eslint.js <root>/node_modules/.bin/eslint
```

**Comment by dbaeumer** [comment]
The feature has not gained any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!

**Comment by Rabadash8820** [comment]
@dbaeumer Thanks for following up. While I understand that your time is precious and you have to pick work judiciously, I feel like it might be worth keeping feature request Issues like this one open. While it may not have gotten the requisite number of likes so far, I would hope that more +1s and use cases would come in over time.
