### ISSUE TITLE
cannot find module 'uri-js'

### ISSUE THREAD

**Issue by XuetaoZhang** [microsoft/vscode-eslint#1311]
![image](https://user-images.githubusercontent.com/27532316/128282260-9a90d048-2877-4ed7-984f-65bcf71e0810.png)
What should I do?

**Comment by dbaeumer** [comment]
This looks like a general config error with ESLint? Does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
