### ISSUE TITLE
Not all file highlited

### ISSUE THREAD

**Issue by actorius** [microsoft/vscode-eslint#1312]
ESLint in VS Code not hightlight all code, look at screenshot below after 500 line no highlight
But problem window have errors below 500 line.

![image](https://user-images.githubusercontent.com/855531/128426955-316b43ed-c69f-4cd1-8054-0ea2d0e42cb9.png)

Version: 1.59.0-insider (system setup)
Date: 2021-08-04T09:44:34.203Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are experiencing. Otherwise it is hard to understand what make these errors not appear.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
