### ISSUE TITLE
Parsing error: Cannot find module 'next/babel'

### ISSUE THREAD

**Issue by rikonor** [microsoft/vscode-eslint#1313]
See https://github.com/vercel/next.js/issues/26406. Any ideas on how to resolve this?

**Comment by dbaeumer** [comment]
One reason could be the node runtime used. Can you try to use `eslint.runtime` setting to point to a local install node runtime (latest version) and see if it is working. Let me know how it goes.

**Comment by rikonor** [comment]
That did not seem to work. I did find another hint - the above issue occurs for me in a Lerna project where one of the packages is a Next project, e.g:
```
➜ git:(master) tree
.
├── lerna.json
├── package.json
└── packages
    ├── next-project
    │   ├── README.md
    │   ├── next.config.js
    │   ├── package.json
    │   ├── pages
    │   ├── public
    │   ├── styles
    └── other
        ├── README.md
        ├── package.json
        └── yarn.lock
```
vscode-eslint produces the reported issue when the root folder is viewed in the editor. If I instead open only `next-project` vscode-eslint works as expected (i.e `code next-project`).

**Comment by dbaeumer** [comment]
@rikonor have to tried to set `eslint.workingDirectories` to specify the directory layout. The setting supports an auto mode and glob patterns as well.

**Comment by rikonor** [comment]
Any idea what it should be set to based on the above `tree` output?

**Comment by dbaeumer** [comment]
`["packages/next-project", "packages/other"]

**Comment by cgestes** [comment]
Same issue here. Happy to help if possible...

**Comment by dbaeumer** [comment]
@cgestes have to tried to specify the working directories

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!

**Comment by lvegerano** [comment]
Has anyone found a solution other than removing the extension itself?

**Comment by dbaeumer** [comment]
Without a project demoing this it is hard to tell what makes this fail.

**Comment by cgestes** [comment]
> Has anyone found a solution other than removing the extension itself?

Not opening the root folder in vscode but adding individual subproject with "add folder to workspace" did the trick for me.

**Comment by merlindru** [comment]
This worked for me @cgestes Thank you!!!

**Comment by robbiedv** [comment]
> > Has anyone found a solution other than removing the extension itself?
> 
> Not opening the root folder in vscode but adding individual subproject with "add folder to workspace" did the trick for me.

bro, thank you.
I must have a global config somewhere that I couldn't find

**Comment by j3rryzh** [comment]
> > Has anyone found a solution other than removing the extension itself?
> 
> Not opening the root folder in vscode but adding individual subproject with "add folder to workspace" did the trick for me.

In my opinion, this is the best solution by far.
But if we have some setting in the project's .vscode folder, it won't take effect. Does anyone can give me some suggestion?

**Comment by AdamQuadmon** [comment]
I finally found a way to use it, this is a turborepo demo with Storybook on NextJs using ESLint Flat Config

https://github.com/AdamQuadmon/turbopandarepo
