### ISSUE TITLE
Not working on RAM disk on Windows

### ISSUE THREAD

**Issue by darky** [microsoft/vscode-eslint#1315]
1. Create RAM disk, for example, via imDisk
2. Place project on RAM disk
3. Open VSCode, add project to workspace

Error in ESLint extension logs: 👇 

(node:8956) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, realpath 'E:\dsm\dsm-backend-stocks-front-api\src\services\subscriptions\services\SubscriptionEditService.ts'
    at Function.realpathSync.native (fs.js:1787:3)
    at Function.native (electron/js2c/asar_bundle.js:5:4607)
    at c:\Users\OUT-Botvin-VV\.vscode\extensions\dbaeumer.vscode-eslint-2.1.23\server\out\eslintServer.js:1:14495
    at z (c:\Users\OUT-Botvin-VV\.vscode\extensions\dbaeumer.vscode-eslint-2.1.23\server\out\eslintServer.js:1:14555)
    at c:\Users\OUT-Botvin-VV\.vscode\extensions\dbaeumer.vscode-eslint-2.1.23\server\out\eslintServer.js:1:16827
(node:8956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 409)

**Comment by dbaeumer** [comment]
Looks like a node problem to me. `realPathSync` comes from the node FS module. One thing you can try as a workaround is to use `eslint.runtime` setting to point to the latest node version. Might be fixed there.

**Comment by darky** [comment]
Yep, seems it's node problem. Hope this will help:

https://github.com/nodejs/node/issues/6861#issuecomment-233126946

Thanks for proper aiming.

**Comment by dbaeumer** [comment]
You are welcome.
