### ISSUE TITLE
vscode-eslint not obeying eslint configuration ?

### ISSUE THREAD

**Issue by noahehall** [microsoft/vscode-eslint#1316]
I am using 
- flow-bin 0.156
- eslint 7.31
- eslint-plugin-flowtype-errors
- @babel/preset-flow

to reveal flow errors via eslint
it works perflectly on CLI, but `vscode-eslint` throws errors on flow syntax

[here are my vscode settings](https://gist.github.com/noahehall/33f60c724f51bde9afa2c2a9e540d094)

[here is the commit demoing the error  (see screenshot below for cmds](https://github.com/noahehall/nodeproto/tree/266d1121c2cd82663c93136aef9e523da5a18d8d/packages/tests)

- see below screenshot for cmds to run to validate eslint + flow work appropriately
- [but if you open up index.mjs in vscode eslint errors on flow syntax](https://github.com/noahehall/nodeproto/blob/266d1121c2cd82663c93136aef9e523da5a18d8d/packages/tests/index.mjs)
![image](https://user-images.githubusercontent.com/10324554/129464538-183cdd91-b38a-4778-960c-8a0d2596541d.png)

**Comment by noahehall** [comment]
# updates

I added some debug options to the cli script and while it did expose some errors, I am still unable to get vscode to exhibit the same behavior as running eslint via cli

- [latest commit with vscode-eslint errors](https://github.com/noahehall/nodeproto/tree/45fcfa09f8fb96ade2bebf441feef7c7457720be)
- ![image](https://user-images.githubusercontent.com/10324554/129499710-6ff3169b-7f3a-43f1-9cc9-75538dc2dd45.png)

**Comment by noahehall** [comment]
similar issue https://github.com/microsoft/vscode-eslint/issues/1272

**Comment by dbaeumer** [comment]
@noahehall this looks like a mono repository setup (e.g. when you run eslint in the terminal you cd into a specific directory). You must let the eslint extension now about this as well using the `eslint.workingDirectories` setting.

**Comment by noahehall** [comment]
awesome: will try after work and report back

**Comment by noahehall** [comment]
ty so much!
