### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Curry44424** [microsoft/vscode-eslint#1318]
- Issue Type: `Bug`
- Extension Name: `vscode-eslint`
- Extension Version: `2.1.23`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.59.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by dbaeumer** [comment]
@Curry44424 do you still have the data. Without there is little I can do.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
