### ISSUE TITLE
Crashing on vscode 1.59.1: Couldn't start client ESLint

### ISSUE THREAD

**Issue by milesj** [microsoft/vscode-eslint#1320]
After upgrading to the latest vscode version last night, the eslint extension has started hard failing with "Couldn't start client ESLint". It has the following stack trace.

```
[Info  - 11:28:51 AM] ESLint server is starting
[Info  - 11:28:51 AM] ESLint server stopped.
[Error - 11:28:51 AM] Starting client failed
TypeError: Cannot read property 'toLowerCase' of null
	at Object.e.fromString (/Users/milesjohnson/.vscode/extensions/dbaeumer.vscode-eslint-2.1.22/client/out/extension.js:1:44688)
	at R.refreshTrace (/Users/milesjohnson/.vscode/extensions/dbaeumer.vscode-eslint-2.1.22/client/out/extension.js:1:139367)
	at R.initialize (/Users/milesjohnson/.vscode/extensions/dbaeumer.vscode-eslint-2.1.22/client/out/extension.js:1:131626)
	at /Users/milesjohnson/.vscode/extensions/dbaeumer.vscode-eslint-2.1.22/client/out/extension.js:1:131226
[Info  - 11:28:51 AM] ESLint server running in node v14.16.0
```

Things I've tried:

- Restarting vscode
- Reinstalling extension
- Installing an older extension version

**Comment by milesj** [comment]
Looks like I accidentally set `"eslint.trace.server": null`, which caused this crash.

I'll leave this open as I think it is still a bug.

**Comment by dbaeumer** [comment]
@milesj which version of the ESLint extension are you using. I thought I fixed this a long time ago here: https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/common/connection.ts#L198

**Comment by dbaeumer** [comment]
I tried to reproduce and I couldn't.

**Comment by milesj** [comment]
@dbaeumer I was using the latest. Let me try and reproduce.

**Comment by dbaeumer** [comment]
Good. Let me know how it goes

**Comment by milesj** [comment]
I was able to trigger something similar to `eslint.workingDirectories: []`.

So these issues happened because I opened the settings panel and just happened to click on a setting. When you click, it instantly modifies the json file inadvertently, which is kind of annoying.

I'll close this for now.

**Comment by joshunger** [comment]
Same issue here somehow `"eslint.trace.server": null` was automatically added to `settings.json`.

```
❯ code --list-extensions --show-versions | grep eslint
dbaeumer.vscode-eslint@2.1.23
```
