### ISSUE TITLE
@typescript-eslint/no-unsafe-return rule (and only that rule) won't clear itself after code is fixed

### ISSUE THREAD

**Issue by justingrant** [microsoft/vscode-eslint#1321]
Issue Type: <b>Bug</b>

Sometimes I will fix some code but be left with a stale @typescript-eslint/no-unsafe-return ESLint error that won't go away until I close and re-open the workspace window. This now happens several times per day. If I close the code file, the error disappears from my Problems pane, but if I re-open the file the error comes back. Closing and re-opening the workspace makes it go away, until the next time it happens later in the day. 

The problem does not repro when running ESLint from the command line from my project's working directory, which is one of two directories listed in my workspace's ESLint `eslint.workingDirectories` setting. 

What's weird is that it's just this one rule that has this behavior.  Here's some example code where I'm seeing it right now:
```js
        const notFoundResult: NotFoundResult = { type: 'not found' };
        return notFoundResult;
        ^^^^^  Unsafe return of an `any` typed value.eslint@typescript-eslint/no-unsafe-return
```

In the code above, `NotFoundResult` is a type imported from another folder. If I hang the mouse over the type name, it correctly shows the type.

![image](https://user-images.githubusercontent.com/277214/130303203-be655ab1-f8c6-4cb1-b5f6-24e4d05c12ab.png)

Whenever this happens, it always shows up immediatly after I fix other real errors with nearby code. When I fix the other errors, this one sticks around and won't go away. 

When manually copy the type declaration from the other file into this one, the error also goes away.  When I remove the manual declaration, the error comes back. 

The only thing that's maybe unusual about the imported type is that it comes from a directory outside my working directory in another project's working directory that contains shared code between my projects. The import looks like this:
```
import { NotFoundResult, RedirectResult } from '@hshared/results';
```

How can I help diagnose this?  It's intermittent and goes away upon reload, I've not been able to come up with a way to build a sample repo that reliably causes the problem. 

FWIW, this is a relatively recent problem that started showing up sometime in the last 2 weeks for me, but admittedly I took a long break to work on other stuff before coming back to this project, so it could have happened any time in the last year or so. I don't believe I've seen this problem in my other TS projects. 

Extension version: 2.1.23
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id fc815e00-6664-4e31-9edb-1a84fa91e72d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464cf:30350173
bridge0723:30353136
vsdyn321cf:30354108

```

</details>

**Comment by justingrant** [comment]
Update: it goes away when I use the Restart ESLint Server command. 

Also, there are no messages in the ESLint output channel that show up when this happens.

**Comment by justingrant** [comment]
I was able to repro this again over the last two days. I'm starting to see a pattern in the reproes:
- First repro: I just finished merging a PR so I switched back to the `main` branch (which changed a bunch of files) and then did a `git pull origin` that changed the files back to what they were previously. The code hadn't changed at all, but I was left with some of these unsafe-any lint errors that automatically fixed themselves when restarting VSCode.
- Second repro: I just refactored an operation that previously took a single object and now takes an array. So I renamed some types to pluralize their names (using Rename Symbol, aka F2) and then renamed one code file. When I renamed the code file, I started seeing an "Unsafe assignment of an `any` value - eslint@typescript-eslint/no-unsafe-assignment" error inside the file that had been renamed when referring to valid code using the renamed, plural name. I saw the same behavior as noted in the OP, where IntelliSense knows that the code is valid but ESLint does not. 
![image](https://user-images.githubusercontent.com/277214/130365679-c0d99e76-14c4-4161-8691-28a80c57684f.png)

What both of these reproes have in common is that they happen immediately after file system changes: 
* Multiple files changed almost simultaneously
OR
* Files being added, removed, or renamed

This made me wonder if the problem is a race condition between file-change notifications and the extension's internal state of the types involved. 

I'll continue to observe to try to refine the pattern of these failures.

**Comment by dbaeumer** [comment]
@justingrant  When this happens can you please check what ESLint in the terminal reports. I am pretty sure that this might be releated to typescript-eslint plugin and not necessarily to the ESLint extension.

**Comment by justingrant** [comment]
> When this happens can you please check what ESLint in the terminal reports. I am pretty sure that this might be releated to typescript-eslint plugin and not necessarily to the ESLint extension.

When filing this issue I did exactly that, but the command-line ESLint returned no errors. That's why I filed this issue here instead of with typescript-eslint. From the OP: 

> The problem does not repro when running ESLint from the command line from my project's working directory, which is one of two directories listed in my workspace's ESLint `eslint.workingDirectories` setting.

One thing I didn't try was to run ESLint from other directories (e.g. my workspace root). Next time the problem reproes, I'll try that too.

If there's any other diagnostic info I should collect when the problem reproes next, let me know and I'll collect it.

**Comment by dbaeumer** [comment]
You can enable `eslint.debug: true`. This prints a lot of debug info to the ESLint output channel.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!

@justingrant please ping if you have additional info and I will reopen.

**Comment by vtgn** [comment]
> This issue has been closed automatically because it needs more information and has not had recent activity. See also our issue reporting guidelines.
> 
> Happy Coding!
> 
> @justingrant please ping if you have additional info and I will reopen.

Hello!

It happens all the time on our project too and we got a lot of them.
We must restart ESLint Server inside vscode very often to make them disappear.
I think it is a problem of refresh after the contents of the node-modules change: we use personal NodeJs libraries, and when we modify their code, we have to rebuild our micro-services depending on them to update these libraries transpiled code inside the node-modules of our micro-services. Probably Eslint become unstables at this moment.
The VsCode integrated Typescript features have the same kind of problem: underlining in red some parts of the code for no reason.

Regards.

**Comment by dbaeumer** [comment]
This sounds like a inter file dependency (a change in A makes an error on B go away or appear).

ESLint (the npm module) has no support for this since it assumes it always validates from scratch. This is nothing that can be done on type because it is by far to expensive (performance wise, battery life, ...)


What I did add for the next version of the extension is to re-lint files on focus change. I addition there is no an action to re-lint all files without restarting the server. 

The new version will come out beginning of April.

**Comment by vtgn** [comment]
> This sounds like a inter file dependency (a change in A makes an error on B go away or appear).
> 
> ESLint (the npm module) has no support for this since it assumes it always validates from scratch. This is nothing that can be done on type because it is by far to expensive (performance wise, battery life, ...)
> 
> What I did add for the next version of the extension is to re-lint files on focus change. I addition there is no an action to re-lint all files without restarting the server.
> 
> The new version will come out beginning of April.

Thank you for your explanation. I understand it is not easy to manage efficiently refreshing with this kind of tool. :/

Regards.
