### ISSUE TITLE
Could ESLint error messages be moved from a popup dialog to the status bar?

### ISSUE THREAD

**Issue by justingrant** [microsoft/vscode-eslint#1322]
When ESLint encounters an exception, it will show a popup warning box in the IDE which must be manually dismissed by the user. For example, when I typed `const` on a new line in a JS file, I got an error dialog. 

![image](https://user-images.githubusercontent.com/277214/130507411-39f225ad-a4b9-48ee-84a2-f72470fc29ca.png)

![image](https://user-images.githubusercontent.com/277214/130506065-c2dda90b-2ad3-4719-8775-d2a15bdc6d62.png)

Obviously ESLint itself or its plugins (e.g. typescript-eslint) has a bug here and shouldn't be crashing. But IMHO it's not good to subject VSCode IDE users to dialogs caused by bugs in linters that most users can't fix, especially when most of these problems fix themselves once the user edits their code to fix the problem that caused ESLint to crash. 

The same is true for "can't load config" errors as described in https://github.com/microsoft/vscode-eslint/issues/1182#issuecomment-903986943. The VSCode user can't do anything to fix someone else's code, so putting up an error box isn't helpful. 

IMHO, a better UX would be to report errors without requiring the user to dismiss them. Then, even if ESLint is temporarily broken (or broken for just one file), the developer could still keep working without interruption. 

The VSCode Prettier extension handles this nicely. Instead of a modal, it shows status using an icon in the status bar, e.g. 
![image](https://user-images.githubusercontent.com/277214/130492429-5c2968c7-ea87-4703-9ccd-98dfdce2a5ff.png) - ignored file
![image](https://user-images.githubusercontent.com/277214/130492498-268d3bd0-ffb9-470c-8212-5aed01cc856b.png) - OK
![image](https://user-images.githubusercontent.com/277214/130492636-f8542b12-6d0e-4237-bdbe-056461ae8cf6.png) - file can't be parsed

If the user wants to see details behind problems, they can click the status bar to get taken to the output pane to see details. 

Could vscode-eslint do something similar?

**Comment by dbaeumer** [comment]
The problem is that these errors usually get unnoticed and users then file issues that something is not working. If such an error occurs it usually isn't anything the extension can fix. 

In this specific case though we could ignore the error since it is not a setup problem. But sometimes hard to tell.

In general a dup of https://github.com/microsoft/vscode-eslint/issues/1238.

**Comment by justingrant** [comment]
OK, glad it's being tracked over in #1238. I'll merge this content in there.
