### ISSUE TITLE
Add .eslintcache support

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-eslint#1323]
Hi, I'm wondering if it's possible for this extension to use the `.eslintcache` in my workspace root to improve linting performance.

Given our workspace scripts and this extension already share `.eslintrc.cjs`, it seems natural to share `.eslintcache` as well. Some ways I could see it speeding up workflows:

- The cache could be primed when the dev container is built.
- As the IDE lints, it would (presumably) update parts of the cache.
- Manual runs would update the whole cache.
- The extension would show lint results faster when opening a new file.
- Lint-on-commit (with `husky` + `lint-staged`) would be significantly faster, since the cache would always be up to date.

Ideas (or reasons this won't work) welcome, thanks!

**Comment by aaronadamsCA** [comment]
Partially answering my own question, it looks like this plugin exclusively uses [`eslint.lintText`](https://eslint.org/docs/developer-guide/nodejs-api#-eslintlinttextcode-options) which according to that doc doesn't use the cache, even with `cache: true`:

> The `eslint.lintText()` method doesn't use caches even if you pass the `options.filePath` to the method.

Have you ever looked into potential performance gains from using [`eslint.lintFiles`](https://eslint.org/docs/developer-guide/nodejs-api#-eslintlintfilespatterns) along with enabling the ESLint cache?

**Comment by dbaeumer** [comment]
`eslint.lintFiles` only works on files. However the extension also validates buffers. 

I don't know if things are improved with the new ESLint class API.

**Comment by aaronadamsCA** [comment]
Right, that makes sense. And even if you were to use `eslint.lintFiles()` on save, that would only make `onSave` faster, and do nothing to improve `onType`, which is arguably where the bulk of the benefit is to be found.

Maybe an ESLint feature request could ask for `eslint.lintText()` to take a new `options.readCache`. I understand why ESLint doesn't write to the cache in this scenario, but it would seem sensible to at least read from it where possible.

The performance gain here would probably be massive, though there may also be risks/limitations I'm not considering.

**Comment by aaronadamsCA** [comment]
Filed https://github.com/eslint/eslint/issues/15463, we'll see what they have to say!

**Comment by mrmckeb** [comment]
Just a note that after heavily implementing ESLint caching across our apps, we quickly realised why this is not a good idea (in our environment).

ESLint's caching is per-file. So if a file isn't changed, it won't be re-checked.

With plugins like `eslint-plugin-import` and `@typescript-eslint/eslint-plugin`, caching means that an error introduced in file A by a change in file B won't be caught unless file A was also _changed_.

**Comment by aaronadamsCA** [comment]
That's interesting, I haven't noticed that behaviour myself.

My ESLint issue was closed, and a cursory search shows that the only mention of cache invalidation is in a comment unrelated to the code, so... yeah, that might just be a limitation of ESLint.

I'm gonna go ahead and close this issue, since there's no underlying support on the way from ESLint. Maybe one day, but for now we'll just need to focus on other types of perf improvements, I guess!
