### ISSUE TITLE
.eslintrc.cjs not respected with "eslint.workingDirectories" option?

### ISSUE THREAD

**Issue by pattrickrice** [microsoft/vscode-eslint#1324]
I have a project that uses `.eslintrc.cjs` not `.eslintrc.js` due to https://github.com/eslint/eslint/issues/12319. It seems like vscode does not identify the config; when I rename to .js extension and restart eslint server it seems to properly find the config. 

relevant deps
```json
    "@typescript-eslint/eslint-plugin": "^4.29.1",
    "@typescript-eslint/parser": "^4.29.1",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "prettier": "^2.3.2",
```

**Comment by tinynow** [comment]
@pattrickrice I am having a similar issue. Do you mind sharing how was this resolved?
