### ISSUE TITLE
Support ESLint 8 current error is doesn't export a CLIEngine

### ISSUE THREAD

**Issue by joshunger** [microsoft/vscode-eslint#1329]
Add support for ESLint 8.

The current error is 
```
[Error - 5:27:34 AM] The eslint library loaded from /Users/junger/drive/dev/public/eslint8/node_modules/eslint/lib/api.js doesn't export a CLIEngine. You need at least eslint@1.0.0
```

ESLint removed `CLIEngine` under https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0#removal-of-undocumented-apis-removal-of-cliengine-and-linter

**Comment by dbaeumer** [comment]
Dups. https://github.com/microsoft/vscode-eslint/issues/972

See also https://github.com/microsoft/vscode-eslint/issues/972#issuecomment-903573031 which points to a insider version that has support for version 8

**Comment by zhisui** [comment]
I'm having the same problem，I solved it by updating the version of vscode

**Comment by sshankhdhar** [comment]
> I'm having the same problem，I solved it by updating the version of vscode

@zhisui  Thank you so much!
Was trying to fix it from past 4 hrs
