### ISSUE TITLE
ESLint 8 UnhandledPromiseRejectionWarning: Error: Invalid Options: - Unknown options: configFile

### ISSUE THREAD

**Issue by joshunger** [microsoft/vscode-eslint#1330]
This is a minor issue, but the documentation is incorrect once eslint8 lands.

Install https://github.com/microsoft/vscode-eslint/releases/tag/release%2F2.1.24-Insider and eslint8.

configFile was removed and we're supposed to use overrideConfigFile.

Only appears to be a documentation issue on https://github.com/microsoft/vscode-eslint/blob/f90802225e6180b12c51e742bed8f002d29a13d8/README.md

**Comment by dbaeumer** [comment]
@joshunger thanks for reporting.

**Comment by dbaeumer** [comment]
The new readme point to the differences between the versions:

> `eslint.options`: options to configure how ESLint is started using the [ESLint class API](http://eslint.org/docs/developer-guide/nodejs-api#eslint-class). (If you use ESLint < v7, it will be used as an option for [CLI Engine](http://eslint.org/docs/developer-guide/nodejs-api#cliengine).) Defaults to an empty option bag
