### ISSUE TITLE
Extremely High RAM and CPU usage

### ISSUE THREAD

**Issue by MickeWest** [microsoft/vscode-eslint#1336]
Issue Type: <b>Bug</b>

With the latest version of VS Code when opening TS files the RAM fluctuates between 1.5GB and 5.5GB continually and CPU usage is very high. The culprit is the ESLint extension and was determined using the the "bisect" functionality in VS Code.
The more TS files that are open the bigger the issue but still the open files are less than 10.
Version:          Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)

Extension version: 2.1.25
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.48GB free)|
|Process Argv|C:\\Projects_QNX\\BlackFishDashboard\\BlackFishDashboard.code-workspace --crash-reporter-id 4e5e002d-46bc-4511-9ae2-6c90f297f26d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30363604
vssur157:30365996

```

</details>

**Comment by jpike88** [comment]
Yes I observed similar thing. How is it a linter can be taking more memory than my angular language service extension and typescript processes combined?

**Comment by dbaeumer** [comment]
@MickeWest when this happens can you please capture a screen shot of VS Code's process explorer window (e.g. Help -> Open Process Explorer) and attach it here.

**Comment by MickeWest** [comment]
@dbaeumer  Please find attached Memory status first of when the scenario occurs. This capture doesn't not reflect the highest memory usage. I will enable the extension again and capture what you requested. Thanks for looking into this so fast! It has been a lingering problem for a long time but with the latest release of VS Code it went exponentially worse.

`Version:          Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS Version:       Windows_NT x64 10.0.18363
CPUs:             Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)
Memory (System):  15.71GB (2.08GB free)
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              enabled_on
                  video_decode:               enabled
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    0	   152	 46408	code main
    0	    65	  9124	   window (Process Explorer)
    0	    27	 13196	   utility
    0	    71	 24776	   shared-process
    0	    43	 17088	     ptyHost
    0	     1	 17108	       "C:\Users\XXXXXX\AppData\Roaming\WatchDox\Windows Plugin\WDServiceStarter_32.exe" "C:\Users\XXXXXX~1\AppData\Local\Temp\1\WDLib_32_08232021190435.dll"
    0	     1	 17120	       "C:\Users\XXXXXX\AppData\Roaming\WatchDox\Windows Plugin\WDServiceStarter_64.exe" "C:\Users\XXXXXX~1\AppData\Local\Temp\1\WDLib_64_08232021190435.dll"
    0	    11	 17140	       "C:\Users\XXXXXX\AppData\Roaming\WatchDox\Windows Plugin\WorkspacesServices.exe"
    0	     8	 23228	       console-window-host (Windows internal process)
    0	    72	 42868	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	  9848	         C:\WINDOWS\system32\cmd.exe /c ""C:\Users\XXXXXX\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd" --status"
    0	    34	 34176	           electron_node cli.js 
    0	    57	 23292	             "C:\Users\XXXXXX\AppData\Local\Programs\Microsoft VS Code\Code.exe" --status
    0	    14	  2572	               crashpad-handler
    1	    24	 41716	               gpu-process
    2	   244	 33144	   window (kernel-regression-picker.component.ts - BlackFishDashboard (Workspace) - Visual Studio Code)
    0	    36	 10020	     searchService
    0	    41	 26104	     watcherService
    0	   152	 36720	     extensionHost
    0	    65	  9160	       electron_node main.js 
    0	   653	 13620	       electron_node tsserver.js 
    0	    46	 47496	         electron_node typingsInstaller.js typesMap.js 
    9	  2693	 14296	       electron_node eslintServer.js 
    0	    33	 22240	       "C:\Users\XXXXXX\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\XXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=36720
    0	   810	 26168	       "C:\Users\XXXXXX\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\XXXXXX\.vscode\extensions\angular.ng-template-12.2.0\server --logToConsole --ngProbeLocations c:\Users\XXXXXX\.vscode\extensions\angular.ng-template-12.2.0,c:\Projects_QNX\BlackFishDashboard\front,c:\Projects_QNX\BlackFishDashboard\back,c:\Projects_QNX\BlackFishDashboard\info,c:\Projects_QNX\BlackFishDashboard\scripts --viewEngine --tsProbeLocations c:\Users\XXXXXX\.vscode\extensions\angular.ng-template-12.2.0,c:\Projects_QNX\BlackFishDashboard\front,c:\Projects_QNX\BlackFishDashboard\back,c:\Projects_QNX\BlackFishDashboard\info,c:\Projects_QNX\BlackFishDashboard\scripts --node-ipc --clientProcessId=36720
    0	    73	 35784	       electron_node tsserver.js 
    1	   115	 47800	   gpu-process

Workspace Stats: 
|  Window (kernel-regression-picker.component.ts - BlackFishDashboard (Workspace) - Visual Studio Code)
|    Folder (info): 34 files
|      File types: pdf(8) js(5) png(4) txt(2) cfg(2) pptx(2) drawio(1) json(1)
|                  zip(1)
|      Conf files:
|    Folder (scripts): 21 files
|      File types: py(3) js(3) json(2) prettierrc(1) crt(1) rest(1)
|      Conf files: launch.json(1)
|      Launch Configs: python
|    Folder (back): 15623 files
|      File types: js(9920) md(958) json(786) ts(618) map(268) yml(114)
|                  npmignore(47) eslintrc(43) txt(39) cjs(37)
|      Conf files: package.json(623) makefile(12) tsconfig.json(6) grunt.js(3)
|                  launch.json(2) jsconfig.json(2) settings.json(2)
|                  tslint.json(2) gulp.js(1) webpack.config.js(1)
|      Launch Configs: node pwa-node
|    Folder (front): more than 27872 files
|      File types: js(8896) ts(4303) json(996) map(878) md(552) template(88)
|                  cmd(77) ps1(77) yml(50) png(32)
|      Conf files: package.json(454) tsconfig.json(10) makefile(10)
|                  launch.json(2) tslint.json(2) settings.json(1)
|                  tasks.json(1) webpack.config.js(1) gulp.js(1)
|                  grunt.js(1)
|      Launch Configs: pwa-chrome(2) firefox(2)
`

**Comment by MickeWest** [comment]
@dbaeumer Please find two screenshots attached
![ESLint_Usage_Max](https://user-images.githubusercontent.com/71844639/133270780-b5ea9b0e-f8e5-41c1-8488-3fcd0ab97442.png)
![ESLint_Usage_AfterReleaseMemory](https://user-images.githubusercontent.com/71844639/133270819-1c982297-5819-43c6-9169-75cae2d97cf2.png)
. One depicts the close to max memory usage by ESLint right before it releases the memory again and the cycle starts over to grow the memory usage. The second screenshot depicts the memory usage right after such a release of memory. This seems to point to a memory leak. If no TS files are open the issue doesn't manifest itself or very limited. When it occurs it is enough with one or a few TS files open. So ESLint does not have to be loaded down with many open files to initiate the behavior.

**Comment by jpike88** [comment]
I had a similar experience, eslint server consumes multiple GB of memory over time. Above screenshots are practically identical to what I see as well.

**Comment by dbaeumer** [comment]
Can you share the repository you are seeing this in with steps you to best reproduce it. I am pretty sure that this is caused by `@typescript-eslint/eslint-plugin` and the fact that some rules more or less require a full TS type checker run. 

Your analysis is correct that the eslint server very likely crashes (with OOM) and the extension restarts it.

Dirk

**Comment by MickeWest** [comment]
Unfortunately I cannot share this project. However, as it seems to happen to others both here and other individuals around the globe it can hopefully easily be recreated. I will copy the .eslintrc.json file here so you can see what rules we have setup. In addition, I forgot to mention that the memory increase is occurring without being in a debug session at all. No code actually running.
Besides that we do not have any odd project or rules settings in place.

```
{
    "env": {
        "browser": true,
        "node": true
    },
    "extends": [
        // "plugin:@typescript-eslint/recommended"
        // "plugin:@typescript-eslint/recommended-requiring-type-checking"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "project": "tsconfig.json",
        "sourceType": "module",
        "ecmaVersion": 2020
    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
        "@typescript-eslint/array-type": "off",
        "@typescript-eslint/consistent-type-definitions": "error",
        "@typescript-eslint/explicit-member-accessibility": [
            "off",
            {
                "accessibility": "explicit"
            }
        ],
        "@typescript-eslint/indent": "off",
        "@typescript-eslint/interface-name-prefix": "off",
        "@typescript-eslint/member-delimiter-style": [
            "off",
            {
                "multiline": {
                    "delimiter": "none",
                    "requireLast": true
                },
                "singleline": {
                    "delimiter": "semi",
                    "requireLast": false
                }
            }
        ],
        "@typescript-eslint/member-ordering": "off",
        "@typescript-eslint/no-empty-function": "off",
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/no-non-null-assertion": "error",
        "@typescript-eslint/no-parameter-properties": "off",
        "@typescript-eslint/no-unused-vars": [
            "error",
            {
                "vars": "all",
                "args": "none",
                "argsIgnorePattern": "^_"
            }
        ],
        "@typescript-eslint/no-var-requires": "off",
        "@typescript-eslint/prefer-for-of": "error",
        "@typescript-eslint/prefer-function-type": "error",
        "@typescript-eslint/quotes": "off",
        "@typescript-eslint/semi": [
            "off",
            null
        ],
        "@typescript-eslint/space-within-parens": [
            "off",
            "never"
        ],
        "@typescript-eslint/type-annotation-spacing": "off",
        "@typescript-eslint/unified-signatures": "error",
        "array-element-newline": [
            "error",
            "consistent"
        ],
        "arrow-body-style": "error",
        "arrow-parens": [
            "off",
            "as-needed"
        ],
        "camelcase": "error",
        "comma-dangle": "warn",
        "complexity": "off",
        "constructor-super": "error",
        "curly": "error",
        "dot-notation": "error",
        "eol-last": "warn",
        "eqeqeq": [
            "error",
            "smart"
        ],
        "guard-for-in": "error",
        "id-blacklist": "error",
        "id-match": "error",
        // "import/no-require": "warn",
        "import/order": "off",
        // "jsdoc/no-types": "error",
        "linebreak-style": "off",
        "max-classes-per-file": "off",
        "max-len": "off",
        "new-parens": "warn",
        "newline-per-chained-call": ["warn", { "ignoreChainWithDepth": 3}],
        "no-bitwise": "warn",
        "no-confusing-arrow": "warn",
        "no-caller": "error",
        "no-cond-assign": "error",
        "no-console": [
            "error",
            {
                "allow": [
                    "log",
                    "warn",
                    "dir",
                    "timeLog",
                    "assert",
                    "clear",
                    "count",
                    "countReset",
                    "group",
                    "groupEnd",
                    "table",
                    "dirxml",
                    "error",
                    "groupCollapsed",
                    "Console",
                    "profile",
                    "profileEnd",
                    "timeStamp",
                    "context"
                ]
            }
        ],
        "no-debugger": "error",
        "no-empty": "off",
        "no-eval": "error",
        "no-extra-semi": "off",
        "no-fallthrough": [
            "error"
        ], // { "commentPattern": "[Ff]alls?[\\s-]?[Tt]hrough"} ],
        "no-invalid-this": "off",
        "no-irregular-whitespace": "off",
        "no-multiple-empty-lines": "warn",
        "no-new-wrappers": "error",
        "no-shadow": [
            "error",
            {
                "hoist": "all"
            }
        ],
        "no-throw-literal": "error",
        "no-trailing-spaces": "warn",
        "no-undef-init": "error",
        "no-underscore-dangle": "off",
        "no-unsafe-finally": "error",
        "no-unused-expressions": "error",
        "no-unused-labels": "error",
        "object-shorthand": "error",
        "one-var": [
            "error",
            "never"
        ],
        // "prefer-arrow/prefer-arrow-functions": "error",
        "quote-props": "off",
        "radix": "error",
        "space-before-function-paren": "off",
        "spaced-comment": [
            "error",
            "always",
            {
                "markers": [
                    "/"
                ]
            }
        ],
        "use-isnan": "error",
        "valid-typeof": "off"
    },
    "overrides": [
        {
            "files": [
                "**/*.component.ts"
            ],
            "rules": {
                "@typescript-eslint/no-use-before-define": [
                    "error",
                    {
                        "classes": false
                    }
                ]
            }
        }
    ]
}
```

**Comment by dbaeumer** [comment]
@MickeWest usually something like this is highly sensitive to the version's of the npm modules, the config and the source code. I understand that you can't share the source code publicly, but could you invite me to the repository?

@jpike88 can you share anything.

**Comment by MickeWest** [comment]
@dbaeumer Hi, unfortunately I cannot invite you either as it is on a local "gitHub". I can see and understand that ESLint can be sensitive to its own config which may make it slower if too many rules or advanced rules are enabled but if the Extension is sensitive to the user's source code or npm modules then an extension which job it is to scan the User Code maybe not written correctly as there will be billions of source code variations from users. 
Something inside the Extension is grabbing more and more memory while scanning the source files. Hopefully this can be found either via a code review or setting up a project with ESLint using the settings for ESLint as provided?

**Comment by dbaeumer** [comment]
@MickeWest VS Code's eslint extension uses the ESLint npm modules and plugins to do the scanning and problem generation (the extension code itself is actually very minimal). This is why the extension is sensitive to the versions installed (it takes the npm modules that are installed in the workspace). The eslint typescript plugin is based on the side installed TypeScript npm module and the content of the tsconfig.json file. And all these npm modules can have leaks as well which might even depend on the source code scanned. 

This is why I ask for a reproducible setup because all of the above has an impact on what code is executed. 

I tried to reproduce this using your config file in my ESLint VS Code extension project which uses typescript eslint as well but wasn't able to do so.

<img width="1100" alt="capture" src="https://user-images.githubusercontent.com/1931590/133406121-afb9f080-263b-4e16-89e9-f4b70b02d018.png">

To track this down I would need a reproducible setup. Can you ZIP your workspace and upload it somewhere from where I can download it. You could send me the location by mail.

**Comment by jpike88** [comment]
Are there instructions you could provide to help us debug our eslint process internally? To have a reproducible setup is time consuming and would involve large amounts of proprietary code, so it's not feasible. It's more realistic to either:

- provide instructions on how we can help inform you about where the leak/large use is coming from (enough to get us going, I know I'm smart enough to take it from there)
- work with the eslint-typescript team to enable a debug mode that would shed light on what memory is being allocated for what what purpose over time, and we can just give you the logs

**Comment by dbaeumer** [comment]
@jpike88 from all my experiences it is easier (and faster in total time) to track down those problem with a reproducible case.  But I can understand your resistance to share the code although I can commit to not sharing the code in any form. We can even agree on a secret way to share it.

I will work on a special version of the extension (not minified, web packed, ...) and instruction how you can use it and connect a debugger/profiler to it. This will then allow to inspect what kind of memory is allocated.

**Comment by dbaeumer** [comment]
Here you go:

- download the attached zip: [vscode-eslint-2.2.0-debug.0.zip](https://github.com/microsoft/vscode-eslint/files/7170366/vscode-eslint-2.2.0-debug.0.zip)
- rename the zip to vsix
- uninstall the ESLint VS Extension
- Reload
- Run the command: 'Install from VSIX'
- Select the `vscode-eslint-2.2.0-debug.0.vsix` VSIX
- Reload
- Open the workspace that reveal the memory leak
- create a setting "eslint.server.debug.port": $port where $port is a available debugger port (e.g. 6011)
- reload the window again (the setting above is not hot)
- open a JS / TS file to trigger the ESLint extension activation
- take a tool to connect to the ESLint server. For example Chrome using `chrome://inspect/`. For more details see https://nodejs.org/en/docs/guides/debugging-getting-started/

If you a fluent with memory leak finding ignore my next bullet points. Otherwise

- When the memory consumption goes up take a memory snapshot. 
- Let the memory consumption go up further
- take another snapshot
- Compare the two snapshots using the Dev Tools

Let me know what you find out.

**Comment by dbaeumer** [comment]
If you have a certain pattern that shows the behavior I am happy to help tracing the memory allocation.

**Comment by dbaeumer** [comment]
I wanted to point out one additional thing: ESLint, all it's plugins are usually written assuming some sort of short lived processes (e.g. eslint is usually executed in a terminal runs for n seconds and stops again). So their main focus is not to be leak free :-). However starting processes on type doesn't scale so the ESLint extension keeps the ESLint `process` alive to get a decent on type experience.  Since this can cause problems the code runs in its own process (the ESLint server) and that process can be restarted without having any impact on the validation or the VS Code client itself (it is basically they way of dealing with these leaks).

I don't want to say that we should investigate and find these leaks and report them.

**Comment by MickeWest** [comment]
@dbaeumer First off, thanks for jumping on this ticket so fast and the willingness to research what is causing it!
By default, I was under the impression that ESLint only scanned and parsed files open in the editor. 
However, that does not seems to be the case. ESLint also seems to be scanning and parsing the /node_modules 
folder which is normally pretty big.
The issue seems to be resolved by adding the following ignore pattern to the .eslintrc.json file:

```
    ],
    "ignorePatterns": [
        "node_modules*/",
        "e2e/",
        "dist/"
    ],
```

Adding that ignore pattern keeps the ESLint memory usage basically constant and moderate. Sometimes users do or have to 
rename the node_modules folder when refreshing the installed modules and that just aggregates the problem as ESLint will scan 
that renamed folder too.

It may be worth having ESLint ignore that folder by default?

So with this update to the settings the issue is no longer present and this ticket can be closed.

Thanks,

    Michael

**Comment by jpike88** [comment]
@MickeWest constant and moderate, what exactly does RAM usage look like? It still would have a sizeable base level right (like around 1.5GB)?

**Comment by MickeWest** [comment]
Here is a screen shoot of the memory usage.

![ESLint_Usage_After_Fix](https://user-images.githubusercontent.com/71844639/133621032-e05dff9a-ef94-41df-855b-1c4dc43a5b96.png)

**Comment by alxpsr** [comment]
I don't know it's ok or not but eslint.server consumes ~2Gb RAM (I assume that this is not ok, but correct me if else)

![image](https://github.com/microsoft/vscode-eslint/assets/16555586/a146b43f-393c-4056-bb52-7dee02047c16)

**Comment by alxpsr** [comment]
Now it uses 4Gb Ram...How to fix that?

![image](https://github.com/microsoft/vscode-eslint/assets/16555586/150e4882-a820-4bc3-b40c-a028c45b8106)

**Comment by jpike88** [comment]
Meanwhile... using biomejs. I can't find any mention of it in the vscode process explorer, so it likely means nothing is running as an always on server. It just runs when needed.

![Screenshot 2024-04-23 at 10 17 34 AM](https://github.com/microsoft/vscode-eslint/assets/9585787/dd6cf18d-fc7f-4e1b-a316-d47f67ed71dd)
