### ISSUE TITLE
Infinity loop on format enabled

### ISSUE THREAD

**Issue by vxna** [microsoft/vscode-eslint#1337]
Honestly, as no recent `vscode-eslint` versions were published lately and it also started to happen only after VS Code 1.60.1 got released, this looks like VS Code issue, but I hasn't spotted any weird behavior with other extensions but `vscode-eslint`. 

https://user-images.githubusercontent.com/30002276/133716593-2fc790d8-db62-42cf-b158-aa140c3acc12.mp4

Steps to reproduce:

1. Use anything that has `.eslintrc`, for quick testing `next` will work best here
```sh
npx create-next-app vscode-eslint-repro
````
2. Create `.vscode/settings.json` and enable `vscode-eslint` format/debug options
```json
{
  "eslint.format.enable": true,
  "eslint.debug": true,
}
```
3. Reload VS Code window and open any js file
4. Show ESLint logs in Output channel and see that `vscode-eslint` runs in an infinity loop

Extension version: 2.1.25
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (15.98GB free)|
|Process Argv|--crash-reporter-id a77eb6ed-57ce-4c88-aefe-6c364ea456e3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3399)|
|Memory (System)|24.98GB (23.86GB free)|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@vxna followed your steps but was not able to reproduce. Any additional info:

https://user-images.githubusercontent.com/1931590/133755555-df989fa7-c0c1-4d7e-b687-41f36c273e1e.mp4

**Comment by dbaeumer** [comment]
And I can't play your screen cast. Can you upload it again?

**Comment by vxna** [comment]
> @vxna followed your steps but was not able to reproduce.

@dbaeumer are you manually running format by keypress, with `editor.action.formatDocument`? I see that timestamps are changing in your video and ESLint runs multiple times. In my case, it runs even if VS Code window is not active, but have the file opened. 

> And I can't play your screen cast. Can you upload it again?

That's quite strange as it works for me. I think you can try [direct link](https://user-images.githubusercontent.com/30002276/133716593-2fc790d8-db62-42cf-b158-aa140c3acc12.mp4) in this case.

**Comment by vxna** [comment]
Gotcha. The screencast was HEVC encoded thus not playable everywhere, here's AVC version that should work:

https://user-images.githubusercontent.com/30002276/133770937-03a7d0aa-f232-4972-9542-21f740fecb6a.mp4

**Comment by dbaeumer** [comment]
@vxna opening the file didn't trigger an infinite loop for me. 

The timestamps change since I did the following: typing in the file and pressing `Shift+Alt+F` to trigger format. None of those lead to an infinite loop either.

**Comment by vxna** [comment]
@dbaeumer that's the thing: https://github.com/microsoft/vscode/issues/126126#issuecomment-921747090

Thanks for your time!

**Comment by dbaeumer** [comment]
OK. Thanks.
