### ISSUE TITLE
Adding the fix option prevents eslint from running

### ISSUE THREAD

**Issue by dsbert** [Microsoft/vscode-eslint#134]
When first downloading this eslint plugin, I added the following to my user settings file in the hope of auto-fixing errors on save.

``` json
// Place your settings in this file to overwrite the default settings
{
    "eslint.options": {
        "fix": true
    }
}
```

However, I was never able to get eslint to actually pick up on any of my errors. After searching around for a long time, I tried deleting the options. Magically, I started seeing the linting errors.

I realize now that the plugin does not currently auto-fix errors, so my option did not actually do anything. I'm not sure why adding this option would disable linting, and there is no documentation or error message to indicate this fact.

**Comment by SuhairZain** [comment]
Hi @dbaeumer 
This is a very nice to have feature. Any updates on this?

**Comment by dbaeumer** [comment]
This got implemented and is available in the latest version of the ESLint extension. To enable you need to set the VS Code setting `eslint.autoFixOnSave: true`.

I will close the issue. Auto fix is available, but must be enabled differently since the trigger is the save action in VS Code.

**Comment by SuhairZain** [comment]
@dbaeumer 
Great. 😄
