### ISSUE TITLE
VSCode reporting error but not CLI

### ISSUE THREAD

**Issue by Trinovantes** [microsoft/vscode-eslint#1340]
Demo: https://github.com/Trinovantes/issue-vscode-eslint-vue-ts

Running:
1. `yarn install`
2. `yarn lint`

Will not produce an error as expected

However my project in VSCode is reporting an error:
![Screenshot 2021-09-21 024234](https://user-images.githubusercontent.com/458691/134123778-69eab174-52d0-4547-89ac-842adf4d5488.png)

**Comment by dbaeumer** [comment]
This error is not produced by the ESLint extension. It comes from the Vue extension. Errors produced by the eslint extension have the source eslint. See that attached screen shot:

<img width="382" alt="capture" src="https://user-images.githubusercontent.com/1931590/134177604-5a97ad74-9476-4ff6-a100-9d226b2cb7b4.png">

**Comment by dbaeumer** [comment]
Different `eslint-plugin-vue` for the error from the Vue extension and `eslint` for the error from the ESLint (this) exension.

**Comment by Trinovantes** [comment]
Thanks

I found I still had Vetur extension installed on my WSL which was conflicting with Volar (I thought I uninstalled it already but it seems I only uninstalled it locally)
