### ISSUE TITLE
How to lint remote files?

### ISSUE THREAD

**Issue by yosikawa** [microsoft/vscode-eslint#1347]
We have shared JS sources on file server like below.
Because this is the shared server, I don't want to install node_modules files here.

```
\\server\proj
  +-- file.js
  +-- ... many souce codes here

```
And eslint is installed locally.

```
C:\foo\bar
  +-- node_modules
  +-- package.json
  +-- eslintrc.json
  +-- dummy.js

```
How can I confugure to lint \\server\proj\file.js by vscode-eslint
using Node environment at C:\foo\bar ?

I tried with folowing .code-workspace configuration.
The linting works on C:\foo\bar\dummy.js but not on \\server\proj\file.js

```
{
	"folders": [
		{
			"path": "."
		},
		{
			"path": "\\\\server\\proj",
			"name": "server"
		},
	],
	"settings": {
		"eslint.nodePath": "C:\\foo\\bar",
	}
}

```
terminal output shows following message. it seems to looking for the eslintrc file.

`[Info  - 14:52:03] No ESLint configuration found in \\server\proj.
`
I also tried this setting but still not working.

```
	"eslint.workingDirectories": [
		"C:\\foo\\bar", 
		{ "directory": "\\\\server\\proj", "!cwd": true },
	]

```

**Comment by dbaeumer** [comment]
You can use `eslint.options.configFile` and specify the location of the .eslintrc file. See https://eslint.org/docs/developer-guide/nodejs-api

**Comment by yosikawa** [comment]
Sorry to bother you but how?
I'm not calling API but just using vscode editor.
vscode seems to looking for .eslintrc file for network folder \\server\proj
But how can I configure the vscode-eslint extention 
so that make it use C:\foo\bar\.eslintrc instead of  \\server\proj\.eslintrc ?
Do you mean eslint.options.overrideConfigFile ? 
Since I cannot find eslint.options.configFile in the document you designated.
And do you mean setting eslint.options.overrideConfigFile in the .eslintrc file?
But if it already read .eslintrc file, it cannot override because it is already read, right??
