### ISSUE TITLE
Support Error on Unused Disable Directive

### ISSUE THREAD

**Issue by Brian-Bartels** [microsoft/vscode-eslint#1349]
Many Large Repos only lint via node tasks or CLI, and many times it is PR policy to not have any unused disable directives. VSCode should properly show error on unused disable directives. Preferably configurable via a vscode setting.

context: https://eslint.org/docs/user-guide/command-line-interface#--report-unused-disable-directives

Happy to contribute if this feature is accepted

**Comment by Brian-Bartels** [comment]
It worked thanks!

**Comment by dbaeumer** [comment]
Things got renamed in ESLint when moving to the new API.
