### ISSUE TITLE
How do I suppress 'estraverse.Controller is not a constructor' warning?

### ISSUE THREAD

**Issue by theetrain** [Microsoft/vscode-eslint#135]
I see this every time I open a JS file:

![image](https://cloud.githubusercontent.com/assets/12798751/18457371/3ab734fc-7926-11e6-880e-d0aa579c0489.png)

Is there a setting to disable it?

**Comment by dbaeumer** [comment]
I added support in 1.0.7 to show only critical things in the message box and the rest in the output channel. 

@theetrain I was never able to reproduce this. If you still see this with 1.0.7 can you please provide me with a workspace that shows the problem.

**Comment by theetrain** [comment]
The errors appear to be gone now. I'll refer back to this issue if I ever see them again. Thank you for the fix!

**Comment by dbaeumer** [comment]
Closing then.
