### ISSUE TITLE
vscode-eslint is not showing all TS errors

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode-eslint#1353]
I recently started an React TS application and just realized that ESLint is not showing me the same errors/warnings within VSCode as it does on the command line. It seems to be basically running correctly as it does show me some errors:

![image](https://user-images.githubusercontent.com/30658772/137457388-e11e4348-37fa-401e-9794-3cadaa5bc665.png)

My config file is saved at project root within `.eslintrc.js`:

```js
/**
 * @type {import("eslint").Linter.Config}
 */
const config = {
  parser: '@typescript-eslint/parser',
  extends: [
    'plugin:react/recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react/jsx-runtime',
    'plugin:prettier/recommended', // !!! Make sure this is always the last configuration in the extends array !!!
  ],
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    '@typescript-eslint/ban-ts-comment': 'warn',
    'prettier/prettier': 'warn',
  },
  settings: {
    react: {
      version: 'detect',
    },
  },
};

module.exports = config;
```

Neither the ESLint status icon/text, nor the debug output show me any obvious warnings or errors. Is there anything special I could look out for?

# Update

I just realized that the error is shown by the plugin as well if I explicitly add `'@typescript-eslint/explicit-module-boundary-types': 'warn',` to the rules section in my config.

My main questions is now:
Why does ESLint follow different rules in the console and in the editor?

**Comment by dbaeumer** [comment]
@CombeeMike great analysis! The expectation is that the plugin behaves exactly the same way as eslint in the terminal. My guess is that some of the scripts change the config and therefore you see a different set of errors. Best would be to talk to the `create-react-app` people mentioning the difference between `npx eslint` and `npm run start/react-scripts start`.

I will close the issue for now. Please ping if the outcome points to something that can be addressed in the extension.
