### ISSUE TITLE
Can I change the version of node that the eslint server is running on?

### ISSUE THREAD

**Issue by RebeccaStevens** [microsoft/vscode-eslint#1356]
I assume I can't and it is just whatever version ships with vscode itself but I thought I'd still ask.

Why?

My in editor linting is different from my commandline linting with regard to this issue: https://github.com/import-js/eslint-plugin-import/issues/2248
This is because vscode's eslint server is running in node 14.16.0 which does not understand the "node:" protocol. It was backported to node 14 in version 14.18.0 so I need at lease that version of node to get the right linting output.

**Comment by pjchender** [comment]
The answer from @dbaeumer is correct, just add some supplement.

The setting would be like this:

```json
// settings.json
{
  "eslint.runtime": "/Users/user/.nvm/versions/node/v16.17.1/bin/node"
}
```

> If you don't know where your node binary file is, you can use `where node` to find out if you are using a Unix-like terminal.

After saving the settings, **an important thing is to restart your VSCode** (it might not be enough if you only restart the ESLint server). You should see it run on a different version after that in the VSCode. You could check it in the VSCode.

![choose node version in ESLint server](https://i.imgur.com/jYIcSP1.png)
