### ISSUE TITLE
`.eslintignore` not honored in monorepo (using glob pattern)

### ISSUE THREAD

**Issue by tassoevan** [microsoft/vscode-eslint#1359]
Just noticed that

```
  "eslint.workingDirectories": [
    {
      "directory": "packages/*",
      "changeProcessCWD": true
    },
  ],
  "eslint.onIgnoredFiles": "warn",
```

will warn that my `packages/mypackage/.myfile.js` file is **ignored**, but

```
  "eslint.workingDirectories": [
    {
      "directory": "packages/mypackage",
      "changeProcessCWD": true
    },
  ],
  "eslint.onIgnoredFiles": "warn",
```

will enable `eslint` on it, matching the behavior defined by adding `!.myfile.js` on `packages/mypackage/.eslintignore`.

**Comment by dbaeumer** [comment]
@tassoevan would you be able to provide me with a repository I can clone that demos the problem you are seeing. It is actually not clear to me from the description.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
