### ISSUE TITLE
React hook missing dependency warning (react-hooks/exhaustive-deps) not appearing

### ISSUE THREAD

**Issue by haishangfeie** [microsoft/vscode-eslint#1361]
expected：
The visual warning appeared on code as a yellow wavy line and provided an option to auto-fix dependencies.

now:
No warnings appear in the code as a yellow wavy line

version: 1.61.2 (Universal)
commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
date: 2021-10-19T15:49:28.381Z (1 周前)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by dbaeumer** [comment]
@haishangfeie does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by sklinov** [comment]
Same for me - CLI `eslint` works fine and shows warning, but the VSCode one is not showing the warning

**Comment by dbaeumer** [comment]
@sklinov this repository fails for me on the command line since it doesn't have an .eslint configuration file

```
@dbaeumer ➜ /workspaces/short-test-that-compiles (main) $ ./node_modules/.bin/eslint ./src/index.tsx 

Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /workspaces/short-test-that-compiles/src and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://eslint.org/chat/help


```

**Comment by dbaeumer** [comment]
Can you please add one so that it is self contained.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
