### ISSUE TITLE
Extension does not work with pnpm

### ISSUE THREAD

**Issue by gaussianblurs** [microsoft/vscode-eslint#1362]
Hello,
I am trying to use the eslint plugin (v2.1.20) with pnpm (v6.20.1) and nvm (v0.38.0). 

When the eslint plugin initializes, I get the following output:
```
[Info  - 10:40:02 AM] ESLint server is starting
[Info  - 10:40:02 AM] ESLint server running in node v16.13.0
[Info  - 10:40:02 AM] ESLint server is running.
/bin/sh: line 1: pnpm: command not found
Uncaught exception received.
Error: Command failed: pnpm root -g
/bin/sh: line 1: pnpm: command not found

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.get (/home/gaussian/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.1.20/server/out/eslintServer.js:1:15918)
    at /home/gaussian/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.1.20/server/out/eslintServer.js:1:17145
    at /home/gaussian/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.1.20/server/out/eslintServer.js:1:17160
```

pnpm root -g:
`/home/gaussian/.nvm/versions/node/v16.13.0/pnpm-global/5/node_modules`

which pnpm:
`/home/gaussian/.nvm/versions/node/v16.13.0/bin/pnpm`

Please help me out

**Comment by dbaeumer** [comment]
@gaussianblurs what happens when executing `which pnpm` from inside a terminal in VS Code itself. I guess that the environment is already not correct for VS Code hence the eslint server can't find it either.

**Comment by gaussianblurs** [comment]
`which pnpm`:
/home/gaussian/.nvm/versions/node/v16.13.0/bin/pnpm

**Comment by gaussianblurs** [comment]
The output is the same from the VS Code terminal:
`which pnpm`:
/home/gaussian/.nvm/versions/node/v16.13.0/bin/pnpm

**Comment by dbaeumer** [comment]
I have no idea why this is happening then. If I give you instructions would you be willing to debug this?

**Comment by gaussianblurs** [comment]
Sure, I have already tried to fix it by adding the npm global binaries to my PATH like this: `$(npm config --global get prefix)/bin` but it didn't work. Definitely looks like an env issue, but I don't know where to look.

**Comment by gaussianblurs** [comment]
Found out where the issue comes from:
 `"eslint.packageManager": "pnpm"` in the user settinggs; when I remove this line and use workspace settings, everything works.

**Comment by gaussianblurs** [comment]
I tried these settings in the settings.json file:

```
	"eslint.runtime": "/home/gaussian/.nvm/versions/node/v16.13.0/bin/node",
	"eslint.nodeEnv": "/home/gaussian/.nvm/versions/node/v16.13.0/bin"
```

But it didn't work either

**Comment by gaussianblurs** [comment]
I think I have the same issue: https://archived.forum.manjaro.org/t/intellisense-in-vscode-doesnt-function-with-nvm/132978

**Comment by dbaeumer** [comment]
OK. The post you linked is interesting. If you start VS Code from a terminal in which `which pnpm` works does it work then?

**Comment by gaussianblurs** [comment]
Yes it works with this method. Thanks for asnwering me, closing the issue.

**Comment by wsdmzy** [comment]
> Yes it works with this method. Thanks for asnwering me, closing the issue.

hi, how to solve it?

**Comment by damnhandy** [comment]
@gaussianblurs @dbaeumer While the solution works for launching VS Code from the CLI, hosted versions of VS Code still do not work. Thus, this is not a workable solution. Environments like [vscode.dev](https://vscode.dev), Coder, GitPods, etc.. don't have the ability to launch via command line. Thus, this issue should still remain open until a solution is available.

**Comment by dbaeumer** [comment]
@damnhandy do you have any steps on how to reproduce this. @gaussianblurs issue was environment related when starting from the dock. At the end I think it depends on how you setup the machine environment whether VS Code and its extensions see pnpm on the path or not. This is nothing the extension can control and adding a user setting for this seems a little odd since it is usually something the environment should provide.

**Comment by tashuo** [comment]
I get the same error output, and finally find it's the environment variable. 

My error is `Command failed: pnpm root -g`,  and i try the command `pnpm root -g` in the terminal which opened vscode(i open vscode by command `code /path/to/project`), it gets error too. Then i find i didn't set `PNPM_HOME` and `PATH` environment variable  in `~/.bash_profile` very well which courses the terminal can't find pnpm home correctly. 

So set up `PATH` of pnpm correctly，reopen vscode in the terminal will works.

**Comment by DillonB07** [comment]
Run into this issue as well. Running from terminal does help, but that **should not** be the solution to this. This appears to be a fairly common issue and really needs to be fixed :pray:

I'm on macOS Monterey and my PATH and env vars are all set properly.
