### ISSUE TITLE
Plugin unexpectedly loads eslint lib from embedded node_modules

### ISSUE THREAD

**Issue by danielrentz** [microsoft/vscode-eslint#1365]
We have a somewhat weird setup here, where one project in a monorepo contains an embedded package.json:

```
root.code-workspace
project1/
    package.json
    .eslintrc.js
    src/
project2/
    package.json
    .eslintrc.js
    src/
    test/
        package.json
        .eslintrc.js
```
One reason for that is to prevent installing the codeceptjs/puppeteer monsters in normal development mode. Sadly, this setup is given for now and cannot be changed.

The workspace config contains the recommended setup for monorepos:
```
{
    "settings": {
        "eslint.workingDirectories": [
            { "directory": "./project1", "changeProcessCWD": true },
            { "directory": "./project2", "changeProcessCWD": true }
        ]
    }
}
```

As long as the embedded `project2/test/package.json` has not been installed, everything works as expected. Opening a file from `project2/src` or `project2/test` triggers the following plugin output:
```
[Info] ESLint server is starting
[Info] ESLint server running in node v14.16.0
[Info] ESLint server is running.
[Info] ESLint library loaded from: ....../project2/node_modules/eslint/lib/api.js
``` 

However, when installing the packages of the embedded project, an outdated eslint v6.8 will be installed due to some indirect dependencies of some packages.

Restarting VSCode and opening a file from `project2/test` gives the following output:
```
[Info] ESLint server is starting
[Info] ESLint server running in node v14.16.0
[Info] ESLint server is running.
[Info] ESLint library loaded from: ....../project2/test/node_modules/eslint/lib/api.js
``` 
followed by various rule parsing errors from the (outdated) embedded eslint package.

Running eslint from command line (in the respective project roots) works in both situations.

I would expect that the plugin always tries to load eslint from the working directory roots (first?).

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that reproduces this. Otherwise hard to say what is going on.

**Comment by danielrentz** [comment]
https://github.com/danielrentz/vscode-eslint-test

README contans step-by-step instructions

**Comment by dbaeumer** [comment]
If you execute ESLint in the terminal in the test project (this is what the extension currently does) then it fails with the same error

```
➜ /workspaces/vscode-eslint-test/project1/test (main ✗) $ ./node_modules/.bin/eslint **/*.js
Error: ../.eslintrc.yaml:
        Configuration for rule "no-implicit-coercion" is invalid:
        Value {"disallowTemplateShorthand":true,"boolean":true,"number":true,"string":true} should NOT have additional properties.

    at validateRuleOptions (/workspaces/vscode-eslint-test/project1/test/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /workspaces/vscode-eslint-test/project1/test/node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/workspaces/vscode-eslint-test/project1/test/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/workspaces/vscode-eslint-test/project1/test/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/workspaces/vscode-eslint-test/project1/test/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/workspaces/vscode-eslint-test/project1/test/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at FileEnumerator._iterateFilesRecursive (/workspaces/vscode-eslint-test/project1/test/node_modules/eslint/lib/cli-engine/file-enumerator.js:396:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/workspaces/vscode-eslint-test/project1/test/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:49)
@dbaeumer ➜ /workspaces/vscode-eslint-test/project1/test (main ✗) $ 
```

**Comment by dbaeumer** [comment]
The working directory setting is a resource setting and can't be specified in a workspace file. Simply add it .vscode/setting.json to project like this and it works

<img width="800" alt="capture" src="https://user-images.githubusercontent.com/1931590/141795621-a72c207a-8326-48a7-99f0-1a008e6c8f23.png">

**Comment by danielrentz** [comment]
Ouch, thanks for investigation and clarification :)

**Comment by danielrentz** [comment]
I would like to reopen this issue. While everything works as described, things break again if the workspace file contains more folder entries.

I have committed a new testcase in the repository. If the code-workspace file contains an additional entry for the "test" folder in the `folders` array, the plugin starts to load the wrong eslint lib again:

./workspace.code-workspace
```json
{
  "folders": [
    { "path": "./project1" },
    { "path": "./project1/test" }
  ]
}
```
./.vscode/settings.json
```json
{
  "eslint.workingDirectories": ["./"]
}
```
plugin output
```
[Info  - 15:04:35] ESLint server is starting
[Info  - 15:04:35] ESLint server running in node v14.16.0
[Info  - 15:04:35] ESLint server is running.
[Info  - 15:04:37] ESLint library loaded from: ..../vscode-eslint-test/project1/node_modules/eslint/lib/api.js
[Info  - 15:04:38] ESLint library loaded from: ..../vscode-eslint-test/project1/test/node_modules/eslint/lib/api.js
[Info  - 15:04:38] ..\.eslintrc.yaml: 	Configuration for rule "no-implicit-coercion" is invalid: 	Value {"disallowTemplateShorthand":true,"boolean":true,"number":true,"string":true} should NOT have additional properties. 
```

**Comment by dbaeumer** [comment]
@danielrentz does validating in the terminal work (see https://github.com/microsoft/vscode-eslint/issues/1365#issuecomment-968941577) ?

**Comment by danielrentz** [comment]
@dbaeumer I get the same error as you mentioned when explicitly calling the "wrong" eslint lib from the test folder. However, in our project setup, it is not intended to run eslint from the "test" folder, but only from the project roots.
I hoped to be able to model this with the "workingDirectories" option, which seems to work as long as the workspace configuration does not declare subfolders to be shown in the project explorer ("folders" option).

**Comment by dbaeumer** [comment]
@danielrentz declaring subfolders should work, however the entries in the array are order specific and the first match wins. Have you tried:

```
{
  "folders": [
    { "path": "./project1/test" },
    { "path": "./project1" }
  ]
}
```

**Comment by danielrentz** [comment]
@dbaeumer Tried it, iIt does not make any difference. Are you sure your plugin uses the "folders" settings in any way? I consider the "folders" option UI-only (File Explorer), and not something that should influence the behavior of plugins.

**Comment by dbaeumer** [comment]
Sorry, I got confused. What exactly do you try to achieve with the folder setting. ESLint doesn't honor it. The eslint setting to specify working directories is: `eslint.workingDirectories`

**Comment by danielrentz** [comment]
Exactly. Back to my "I want to reopen" comment :)
The "folders" option in the code-workspace file seems to influence how the plugin loads the eslint lib although it shoud not.

- If I have an entry `"./project1/test"` in the "folders" array, then (and only then) the plugin loads eslint from `./project1/test/node_modules` when trying to lint `project1/test/index.js`.
- If I only have the entry `"./project1"` in the "folders" array, then the plugin always loads eslint from `./project1/mode_modules`.

So the bug is that the plugin somehow gets influenced by the "folders" option, i.e. where exactly the file to be linted is located according to the entries there.

**Comment by dbaeumer** [comment]
Now you have two workspace folders and both need their own version of the `.vscode/settings.json` file with a corresponding entry for the working directories.

Think about a workspace folder as something that you also can open standalone. It must function independent of other folders. They don't influence each other. 

Let me know if this helps.

**Comment by danielrentz** [comment]
Yes that seems to do the trick. I have seen the "folders" thingy just as a convenient way to define "bookmarks" for interesting places deeply inside the project, and did not expect any of these effects... So as rule of thumb to myself: If it has a package.json, it needs a vscode/settings.json too :)
