### ISSUE TITLE
Plugin takes up 98%+ CPU usage

### ISSUE THREAD

**Issue by brynley** [microsoft/vscode-eslint#1367]
As you can see from the screen shot below Code Helper (Renderer) is taking up 98%+ CPU usage, even when VSCode has been quit, causing the fans of my MacBook Pro to run at very high speeds.
![image](https://user-images.githubusercontent.com/20400802/141098241-66a3cf0f-c8e2-4331-a177-3e68b31ee005.png)

After searching for the culprit using `ps aux | grep {cpuPID}` where `{cpuPID}` is the PID of the process in activity monitor, it shows that vscode-eslint is the problem
![debug](https://user-images.githubusercontent.com/20400802/141099071-c7992fa7-579a-493a-b69b-07a938ae8cf6.png)

The only way to stop this taking up so much CPU usage for me so far, has been disabling/uninstalling the plugin. Which in the long run, isn't something I want to do as I use it daily.

**Comment by dbaeumer** [comment]
@brynley and steps on how I can reproduce this. Best would be a GitHub repository to clone.

**Comment by brynley** [comment]
Unable to give you access sadly as it is a private repo, I can tell you that it is a very large lerna based component library with 100+ components, using typescript and I'm on version `2.2.2` of vscode-eslint

**Comment by dbaeumer** [comment]
@brynley you could invite me to the repository. This avoids that you have to make it public.

**Comment by sgtoj** [comment]
This is also affect me too. It's an enterprise private reop that I cannot invite external users.

**Comment by dbaeumer** [comment]
Can any of you reproduce this consistently. If so I can give you instructions on how to debug this if you can't share the code.

**Comment by sgtoj** [comment]
I'll watch for it to happen again.

**Comment by brynley** [comment]
For the same reason as @sgtoj I can't share the repo, I can get it to happen consistently, every time I enable it, I get the same outcome

**Comment by brynley** [comment]
I am now able to isolate it to a branch which is adding a new component, works fine in master, I will update if I find the cause

**Comment by brynley** [comment]
@dbaeumer  So, I don't think this is an issue with the plugin itself, so my apologies for raising it here.

After debugging I managed to find the line of code that makes eslint infinitely loop:
![image](https://user-images.githubusercontent.com/20400802/143012334-96453dfc-d7ea-4bdf-8b41-abf96f1fb251.png)

The specific character causing the loop being the highlighted optional chaining operator, removing this stops eslint from running forever, which is what would've been causing the plugin to seem to be the issue.

The prop `cardSection` is required, so the optional chaining operator is not needed, but a very strange outcome to this indeed.

But this is an issue with eslint itself, not the vscode plugin.

@sgtoj hopefully this can help you to debug your issue too 🙏

**Comment by dbaeumer** [comment]
@brynley did you open an issue against ESLint itself (the npm module) so that this can be fixed?

**Comment by dbaeumer** [comment]
...and thanks for getting back and closing the issue.
