### ISSUE TITLE
ESLINT-error: 2 similar files - one with many errors - the other without any error

### ISSUE THREAD

**Issue by mbcodecamp1** [microsoft/vscode-eslint#1368]
Hello,
I have 2 very similar files - see attachment!
With one, ESLINT reports 65 errors (problems) - with the other none!
I have already looked at the files with a HEX editor - but I can not really see any difference!
What can be the problem then?
Many thanks in advance!
Best regards
Markus

[ESLINT-error-20211110.pdf](https://github.com/microsoft/vscode-eslint/files/7514893/ESLINT-error-20211110.pdf)

**Comment by dbaeumer** [comment]
What happens when you try to validate both files in a terminal?

**Comment by mbcodecamp1** [comment]
Hello Dirk,

it was a problem with CR LF!

I solved it with this in the .ESLINTRC-File:
rules: {
"prettier/prettier": [
"error",
{
endOfLine: "auto",
},
],
},

Thanks a lot for your help!

Grettings
Markus

**Comment by mbcodecamp1** [comment]
Dirk,
can you please help me in this case?
https://github.com/microsoft/vscode-eslint/issues/1372
Thanks a lot!
Markus

**Comment by dbaeumer** [comment]
Closing this issue then.
