### ISSUE TITLE
2.2.2 Not working: Syntax error

### ISSUE THREAD

**Issue by mbm-theman** [microsoft/vscode-eslint#1369]
Hello, I've tried this configuration on both mac & windows but I get this same syntax error:

![image](https://user-images.githubusercontent.com/93955204/141267173-039d744d-caeb-40cc-8087-89ce27147bf0.png)

![image](https://user-images.githubusercontent.com/93955204/141267473-c9aa2cb8-df24-4fba-abd4-250bbfc6011b.png)

**Comment by him0** [comment]
I'm experiencing the same problem in my environment. Node.js v12.x and this plugin v2.2.2 case this problem. https://github.com/microsoft/vscode-eslint/issues/1360.

I use this plugin with rollbacking to v2.2.1 and solving this problem.Node.js v12 is supported until 2022-04-30, so I hope it works correctly.

**Comment by mbm-theman** [comment]
> I'm experiencing the same problem in my environment. Node.js v12.x and this plugin v2.2.2 case this problem. #1360.
> 
> I use this plugin with rollbacking to v2.2.1 and solving this problem.Node.js v12 is supported until 2022-04-30, so I hope it works correctly.

I'm using ESLint v8 and that is not supported until 2.2.2, I tried manually installing 2.1.24-Insider but that didnt work either

**Comment by mbm-theman** [comment]
Removing `eslint.runtime = "node"` from my vscode settings worked.
