### ISSUE TITLE
Output panel

### ISSUE THREAD

**Issue by LeusMaximus** [Microsoft/vscode-eslint#137]
Output panel is always open after 1.0.3 update

**Comment by dbaeumer** [comment]
@LeusMaximus the output panel only opens if the plugin can't find a eslint package. And only once per workspace. Do you see a different behavior. If so could you provide steps so that I can reproduce and fix.

**Comment by Naixor** [comment]
+1

**Comment by dbaeumer** [comment]
@Naixor can you provide steps to reproduce this. As outlined in https://github.com/Microsoft/vscode-eslint/issues/137#issuecomment-246719240 this should only happens once.

**Comment by Naixor** [comment]
This always happen. I restart my vscode and then the panel open. Close it and edit my code, opened again.
<img width="986" alt="dingtalk20160920110945" src="https://cloud.githubusercontent.com/assets/5070106/18656369/2bd2eb18-7f23-11e6-96a1-4d3b6d307eeb.png">

**Comment by LeusMaximus** [comment]
Sorry did not respond earlier.
I have the same behavior like @Naixor 
Ubuntu 16.04

**Comment by dbaeumer** [comment]
@Naixor for some reason you have tracing enabled either via a workspace or a global setting. Can you please check if '"eslint.trace.server": "messages"' is set and if so delete the setting or set the value to "off".

**Comment by Naixor** [comment]
@dbaeumer Thanks.

**Comment by dbaeumer** [comment]
I will close this issue. @LeusMaximus please ping with steps if you weren't affected by the tracing settings as well.
