### ISSUE TITLE
Format CSS rules inside <style> in .vue files

### ISSUE THREAD

**Issue by seth100** [microsoft/vscode-eslint#1370]
Hi,

I configured VSCode to use `"dbaeumer.vscode-eslint` as default formatter for `js` and `vue` files:

```json
"[javascript]": {
  "editor.defaultFormatter": "dbaeumer.vscode-eslint"
},
"[vue]": {
  "editor.defaultFormatter": "dbaeumer.vscode-eslint"
},

"eslint.format.enable": true,
"eslint.validate": ["javascript", "javascriptreact", "vue", "vue-html", "html"],

"vetur.validation.template": false,
```

and when I execute the "Format Document" option it correctly formats javascript and html code, while the CSS/SCSS code inside `style` tag does not get formatted, e.g.:

```vue
<style lang="scss" scoped>

  .my-class {
      position: relative;
        color: red;
}


</style>
```

is there a way to make the formatter work as expected for style tags too?

Thanks

**Comment by dbaeumer** [comment]
@seth100 this is outside my control. Best is:

- run eslint from the terminal with `--fix` until you get the expected result
- if you can't then please file an issue against the CSS plugin that you use for formatting.

**Comment by ildar-gilmanov** [comment]
@dbaeumer , @seth100 , I have the same issue. Could you please check this ticket: https://github.com/microsoft/vscode/issues/162154

**Comment by ildar-gilmanov** [comment]
@dbaeumer , I use the `dbaeumer.vscode-eslint` for vue files and this works great for `html` and `script` sections, but it does not work for `css` (`scss`).

@aeschli had closed the https://github.com/microsoft/vscode/issues/162154 with the explanation:

> The css formatter would only be used if the language mode is CSS, LESS or SCSS.
I assume in your case it is vue. That means a formatter for vue is used. You need to install a vue extension that provides a formatter. If you already have done that and the formatter doesn't work, file an issue against the vue extension.

So, it is strange: Vue extension's developers say that the source of the issue in the CSS plugin, CSS plugin's developers say that the source of the issue in the Vue plugin.

@aeschli, @dbaeumer , could you please contact each other and solve the issue?

In any way, many thanks to you both - the plugins are great! But unfortunately they do not work correctly with `<style>` section in `.vue` files.

**Comment by dbaeumer** [comment]
I think there might be a misunderstanding here:

- this extension is about ESLint and not Vue
- if you have an ESLint plugin (a plugin for https://eslint.org/) that formats vue files including CSS sections then try the following:
  - configure the necessary eslint rules
  - format the file using the terminal using something similar to `eslint --fix ....`

If it produces the expected result then file an issue with a GitHub repository attached that I can clone that demos the failure. If not (and that is what I suspected here https://github.com/microsoft/vscode-eslint/issues/1370#issuecomment-968959099) file an issue against the CSS / VUE ESLINT plugin you use. The VS Code CSS plugin is not involved when using ESLint. @aeschli is right about that.

**Comment by ildar-gilmanov** [comment]
@dbaeumer , thank you for your response and explanation! I have created a ticket for vuejs/eslint-plugin-vue: https://github.com/vuejs/eslint-plugin-vue/issues/1997
