### ISSUE TITLE
Correct setting in VSCode for all react projects with ESLINT and PRETTIER - why is it so difficult?

### ISSUE THREAD

**Issue by mbcodecamp1** [microsoft/vscode-eslint#1372]
Hello Dirk,
I need your help!
I use the latest version of VSCode =1.62!
Why is it so difficult to configure a correct cooperation of PRETTIER and ESLINT in my create-react-app projects?
Basically I would like to have:
- autom. formatting - when I change or save the file
- I would like to accept single and double quotation marks
- also I would like to allow CR LF at the end of a line
What exactly do the files need to look like for this?
- settings.json
- .eslintrc.js
- .prettierrc
Why can't I find proper examples for this anywhere?
For a better understanding I have attached the current content of the files below - but unfortunately this is not how it currently works!
Thanks in advance!
Best regards
Markus

settings.json:
{
  "workbench.colorTheme": "Community Material Theme Darker High Contrast",
  // These are all my auto-save configs
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  // turn it off for JS and JSX, we will do this via eslint
  "[javascript]": {
    "editor.formatOnSave": false
  },
  "[javascriptreact]": {
    "editor.formatOnSave": false
  },
  // show eslint icon at bottom toolbar
  "eslint.alwaysShowStatus": true,
  // tell the ESLint plugin to run on save
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  },
  "files.autoSave": "onFocusChange",
  // Optional BUT IMPORTANT: If you have the prettier extension enabled for other languages like CSS and HTML, turn it off for JS since we are doing it through Eslint already
  "prettier.disableLanguages": ["js", "jsx", "javascript", "javascriptreact"],
  "prettier.jsxSingleQuote": true,
  "prettier.singleQuote": true,
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}

.eslintrc.js:
module.exports = {
  parser: "babel-eslint",
  env: {
    es6: true,
    node: true,
    browser: true,
  },
  parserOptions: {
    ecmaVersion: 6,
    sourceType: "module",
    ecmaFeatures: {
      jsx: true,
    },
  },
  plugins: ["react"],
  extends: [
    "react-app",
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:prettier/recommended",
  ],
  rules: {
    "prettier/prettier": [
      "error",
      {
        endOfLine: "auto",
      },
    ],
    "react/prop-types": 0,
    "react/forbid-prop-types": 0,
    "react/no-unescaped-entities": 0,
  },
};

.prettierrc:
{

}

**Comment by dbaeumer** [comment]
I am not a prettier expert. All I can recommend is to first try to get everything working in the terminal including running eslint with the `--fix` option. If this all work try to use it from the ESLint extension. This helps identify if you have a eslint / prettier config problem or a vscode eslint config problem.

I will keep this issue open in case someone else has more experiences with prettier.

**Comment by dbaeumer** [comment]
If it works in the terminal and not in VS Code eslint then file an issue here with detailed steps on how to reproduce. Best a GitHub repository to clone.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
