### ISSUE TITLE
Eslint 8 UnhandledPromiseRejectionWarning: Error: Invalid Options: - Unknown options: exclude

### ISSUE THREAD

**Issue by paritosh-34** [microsoft/vscode-eslint#1374]
My versions:
eslint version: `^8.0.1`
vscode-eslint extension version: `2.2.2`

I've tried fixing this by upgrading eslint to the latest version and also tried to downgrade my eslint version to `7.32.0`
This error still persists.

I saw this issue mentioned here: https://github.com/microsoft/vscode-eslint/issues/1330
but seems like it is still not fixed.
(I am getting `Unkown options: exclude` instead of `Unknown options: configFile`)

**Comment by dbaeumer** [comment]
@paritosh-34  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by tja4472** [comment]
I had to edit my settings.json file.

From: 
```json
{
  "eslint.options": {
    "parserOptions": {
      "ecmaVersion": 2017
    },
    "env": {
      "es6": true
    }
  }
}
```
To:
```json
{
  "eslint.options": {
    "overrideConfig": {
      "parserOptions": {
        "ecmaVersion": 2017
      },
      "env": {
        "es6": true
      }
    }
  }
}
```

**Comment by dbaeumer** [comment]
@tja4472 this is expected since the API for ESLint V8 changed. There is nothing I can do about this.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
