### ISSUE TITLE
Glob pattern doesn't work in eslint.workingDirectories

### ISSUE THREAD

**Issue by lukejagodzinski** [microsoft/vscode-eslint#1377]
Hey, I've had this issue some time ago and I've opened issue here https://github.com/microsoft/vscode-eslint/issues/745
And I just want to tell that this issue still persists. The `eslint` cli doesn't see any problems with unresolved paths but vscode extensions just pollutes IDE with errors. I had to opt-out to defining path to every single package and I just can't use `*`.

EDIT:

To be more specific. There is no problem with resolving paths to modules inside the `./packages/*` directory. But it fails to work with the aliases/paths defined inside the `./packages/*/tsconfig.json`. The eslint cli doesn't have any problems with those aliases. Aliases are only being used inside a given package. But vscode extension complains about it.

**Comment by dbaeumer** [comment]
Can you provide me with a minimal GitHub repository I can clone that demos this. I am pretty sure it has to do with the fact that paths in tsconfig.json can be relative and if the working directory is not correct then the path mapping will fail. But this is speculation until I can reproduce.

**Comment by lukejagodzinski** [comment]
@dbaeumer yep sorry, I will provide repro in a moment

**Comment by lukejagodzinski** [comment]
Ok here is a reproduction: https://github.com/lukejagodzinski/eslint-alias-bug
I've added the readme file there explaining the problem and hacky solution but I'm pasting it also here for the posterity.

**DETAILED EXPLANATION**

The problematic file is `packages/one/src/index.ts`.

When I try to import something from the `@pkg/lib` which is defined as the alias to `packages/one/src/lib` in `packages/one/tsconfig.json`, I get the following error: `Unable to resolve path to module '@pkg/lib'.eslintimport/no-unresolved`. So it's an alias used only withing a package of a monorepo.

However, when I try to import something from the other monorepo package then everything works well. In this case, I'm importing function from the `@root/shared` which points to `packages/shared/src/lib`.

In the `.vscode/settings.json` I have such a configuration:

```json
{
  "eslint.workingDirectories": [
    { "changeProcessCWD": true, "directory": "./packages/*" }
  ]
}
```

which in theory should cover both cases, but to make it work in VSCode I have to set the following `eslint.workingDirectories` rule:

```json
{
  "eslint.workingDirectories": [
    { "changeProcessCWD": true, "directory": "./packages/one" },
    { "changeProcessCWD": true, "directory": "./packages/*" }
  ]
}
```

And it's only issue in the ESLint extension for VSCode, as the `yarn lint` script is working fine and doesn't see any problem there.

**Comment by dbaeumer** [comment]
@lukejagodzinski you are using the wrong syntax. If you want to use patterns the syntax is 

{
  "eslint.workingDirectories": [
    { "pattern": "./packages/*" }
  ]
}

This is to not break previous settings that use directory. See also https://github.com/Microsoft/vscode-eslint

**Comment by dbaeumer** [comment]
Work for me after using the right syntax:
<img width="1124" alt="capture" src="https://user-images.githubusercontent.com/1931590/144063203-973f91e5-d125-452a-bbee-8040e5ff7f69.png">
