### ISSUE TITLE
eslint not showing as a formatter

### ISSUE THREAD

**Issue by danielzzz** [microsoft/vscode-eslint#1378]
hi, I am having a problem with eslint not showing as a formatter.

Version: v2.2.2
vcode: v1.62.3

First, it started showing errors that it could not be used as a formatter, then when I switched to a default js formatter, I cannot see eslint in the menu anymore. it seems like it doesn't register itself as a formatter

in the settings I have Eslint > Format > Enable set to true.

tried disabling/enabling and reinstalling.
eslint server seems to be starting correctly.

thanks, cheers
dan

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are seeing, including steps on how to reproduce it in the repository. Thanks!

**Comment by danielzzz** [comment]
hi, I am not sure what happened but I upgraded everything (vsc + extension + restored node_modules) and suddenly it started working again.
so it might have been some problem on my side maybe.. or maybe some incompatible versions.. 

thanks anyway!
dan
