### ISSUE TITLE
With yarn berry, this plugin fails to find eslint plugins

### ISSUE THREAD

**Issue by sinauq** [microsoft/vscode-eslint#1379]
Trying to run a proejct with yarn berry + eslint, this plugin keeps throwing an error in Output:

```Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js': Cannot find module '@typescript-eslint/eslint-plugin'```

I should the problem is not limited to this particular plugin. I rummaged through issues on yarn berry but couldn't find anything that solves my problem. Since I have no problem using eslint + yarn berry on Emacs, I thought maybe I should first file a bug here.

Here are the versions I use:
- eslint: 8.3.0
- yarn: 3.1.0
- @typescript-eslint/parser: 5.4.0

I have eslint-config-airbnb too (if that helps). Also checked it with eslint v7.2.0, but the problem persists.

I'd be happy to provide more information, if you need so.

**Comment by dbaeumer** [comment]
@sinauq can you please provide me with a GitHub repository I can clone that demos what you are seeing (including steps on how to reproduce). Thanks

**Comment by sinauq** [comment]
Sure I'm working on one and will send one very soon.

**Comment by sinauq** [comment]
here's the example repo you requested: https://github.com/sinauq/yarn-with-eslint

Yarn berry is included in the project, so you just have to run ```yarn```.

**Comment by dbaeumer** [comment]
Works for me without any problems

<img width="599" alt="capture" src="https://user-images.githubusercontent.com/1931590/144274169-aa889567-74f1-4f53-98e0-615c380db4cd.png">

Any additional information you can provide?

**Comment by sinauq** [comment]
Okay I found the problem. I was looking through issues and came up with a suggestion to use ```"eslint.options.resolvePluginsRelativeTo": "../../../../",```. Apparently it was not working (at least in latest version of berry).

Thank you for checking this out and helping me.
