### ISSUE TITLE
Plugin "import" was conflicted between two extended config

### ISSUE THREAD

**Issue by hmbrg** [microsoft/vscode-eslint#1380]
Hey!

I'm getting the following error when using vscode-eslint inside a monorepo: 
```
Error: Plugin "import" was conflicted between ".eslintrc.js » plugin:import/warnings" and ".eslintrc.js » ../../.eslintrc.base.js » plugin:import/warnings".
```

The error happens when opening the directory `apps/web-app` inside this monorepo: https://github.com/hmbrg/blitzjs-monorepo-example/tree/main/apps/web-app

I'm using `root: true` and my settings look like this: 
```
{
  "eslint.workingDirectories": [
    {
      "pattern": "./apps/*/"
    },
    {
      "pattern": "./packages/*/"
    }
  ]
}
```

What could be wrong here? Thanks so much in advance!

**Comment by dbaeumer** [comment]
What happens when you run eslint in the terminal in one of the working directories. If it works OK can you then please provide me with a GitHub repository I can clone that demos this. Then I can investigate.

**Comment by hmbrg** [comment]
Everything works from the terminal. The GitHub repo is linked in the issue above. Thanks for helping!

**Comment by dbaeumer** [comment]
Can you please provide exact steps on how to reproduce what you are seeing. And I looked and the repository doesn't contain a VS Code settings.json file in a `.vscode` root folder. Is it missing

**Comment by dbaeumer** [comment]
Digging around a little shows that the same error happens in the terminal: 

<img width="1008" alt="capture" src="https://user-images.githubusercontent.com/1931590/144064626-1e44c7c3-efaf-4451-b432-2517fcdc6abb.png">

Please make sure that validation happens correctly in the terminal using `./node_modules/.bin/eslint`. If you do change the working directory please make sure you have a corresponding `"eslint.workingDirectories"` entry in the settings

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
