### ISSUE TITLE
get Parsing error: The keyword 'import' is reserved

### ISSUE THREAD

**Issue by WebCaiQingChong** [microsoft/vscode-eslint#1382]
```javascript
module.exports = {
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint/eslint-plugin'],
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:import/recommended',
    'plugin:import/typescript',
    'plugin:react/recommended',
    'plugin:react-hooks/recommended',
    'plugin:react/jsx-runtime',
    'plugin:prettier/recommended',
  ],
  settings: {
    'import/resolver': {
      typescript: {
        project: 'tsconfig.json',
      },
    },
    react: {
      createClass: 'createReactClass', // Regex for Component Factory to use,
      // default to "createReactClass"
      pragma: 'React', // Pragma to use, default to "React"
      fragment: 'Fragment', // Fragment to use (may be a property of <pragma>), default to "Fragment"
      version: 'detect', // React version. "detect" automatically picks the version you have installed.
      // You can also use `16.0`, `16.3`, etc, if you want to override the detected value.
      // default to latest and warns if missing
      // It will default to "detect" in the future
      flowVersion: '0.53', // Flow version
    },
  },
  env: {
    browser: true,
    node: true,
    jest: true,
  },
  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      parserOptions: {
        project: 'tsconfig.json',
        sourceType: 'module',
        ecmaVersion: 2020,
      },
    },
  ],
}

```

this is my eslint.config.js, I had add .vscode in my project.
when use eslint V7 this is right.

**Comment by dbaeumer** [comment]
@WebCaiQingChong  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by WebCaiQingChong** [comment]
It isn't work in the termainal too. this is the git repo: [https://github.com/WebCaiQingChong/useBox](https://github.com/WebCaiQingChong/useBox)

**Comment by WebCaiQingChong** [comment]
my global eslint version is v8.2.0, my vscode-eslint version is latest v2.2.2

**Comment by dbaeumer** [comment]
It also looks like you are using a custom `eslint.config.js` config file name. You need to let VS Code know about this as well using the `eslint.options` setting. Please note that this setting is ESLint version dependent and reflects the ESLint API documented here: https://eslint.org/docs/developer-guide/nodejs-api#-new-eslintoptions

**Comment by dbaeumer** [comment]
Saw you are setting it in the settings.json however the format you use is for the new ESLint class API. You either need to use the CLIEngine options in `eslint.options` or set `eslint.useESLintClass` to true.

**Comment by dbaeumer** [comment]
Works with the `eslint.useESLintClass` setting
<img width="614" alt="capture" src="https://user-images.githubusercontent.com/1931590/144281594-4a9e5113-d07d-452c-a612-5b69f2b2e167.png">

**Comment by WebCaiQingChong** [comment]
thank you very mach,  i have a try.

**Comment by WebCaiQingChong** [comment]
it works for me,thank you very mach.
