### ISSUE TITLE
Eslint recently stopped displaying and underlining errors properly (Node)

### ISSUE THREAD

**Issue by dancherb** [microsoft/vscode-eslint#1384]
The extension has recently stopped correctly underlining and displaying error messages for errors. It still indicates that an error is happening with a tiny bit of underlining, but no message. 

This occurs in a "raw" Node project with "eslint-config-rallycoding": "^3.2.0" as a devDependency and _no other packages_ and a local .eslintrc file. Latest version of VSCode on Windows 10.

This error does not occur in Next.js or React projects.

The only thing of note in the "Output" tab under "Eslint" is a series of these:

```
(node:7388) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:7388) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:7388) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:7388) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:7388) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:7388) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:7388) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:7388) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
...
```

![eslint](https://user-images.githubusercontent.com/32280121/144793612-0c3a07d4-09e3-40ab-a803-8149f5072063.png)

**Comment by dbaeumer** [comment]
@dancherb  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
