### ISSUE TITLE
Suggested refactoring for "react-hooks/exhaustive-deps" changes "?." to "." causing breakage

### ISSUE THREAD

**Issue by robspassky** [microsoft/vscode-eslint#1386]
Issue Type: <b>Bug</b>

1. Start with code like:

```
const [object, setObject] = useState(undefined);

useEffect(() => {
      ...
    },
    [object?.name, extraVariable]
);
```

2. `extraVariable` is unneeded, so a yellow light bulb tooltip appears to perform the "react-hooks/exhaustive-deps" refactoring.

3. "Update the dependencies" automatically using the light bulb tooltip.

4. Actual result:

```
useEffect(() => {
      ...
    },
    [object.name]
);
```
The refactoring to remove `extraVariable` is correct, but the side effect that changes `object?.name` to `object.name` causes breakage because `object` will be undefined at times.

5. Expected result:

```
useEffect(() => {
      ...
    },
    [object?.name]
);
```

Extension version: 2.2.2
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.13.19-2-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|125.70GB (24.97GB free)|
|Process Argv|--no-sandbox --unity-launch /home/robc/src/core/.vscode/core.code-workspace --crash-reporter-id 1b3a87f4-7f77-414e-aaa7-267f35c25cfc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t1:30407762

```

</details>

**Comment by dbaeumer** [comment]
@robspassky does the same fix happen when you execute eslint with --fix on the command line. If so please report this to the corresponding react-hooks plugin. If not can you provide me with a Github repository I can clone that demos this?

**Comment by robspassky** [comment]
Thanks for the quick response! Let me look into getting that extra information.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
