### ISSUE TITLE
Turn off "Failed to load the ESLint library" warnings

### ISSUE THREAD

**Issue by mattfysh** [microsoft/vscode-eslint#1387]
I don't have eslint installed globally, and whenever I create a new folder for prototyping in a project that doesn't have eslint installed, I get this warning popping up. At times in the past, I've even seen this warning appear on every keystroke

Is there a way to disable it in new projects that don't use eslint? thanks!

**Comment by dbaeumer** [comment]
There is a setting `eslint.enable` which you can set to false in the workspace or globally.

**Comment by mattfysh** [comment]
@dbaeumer is there an option just to disable this popup: https://github.com/microsoft/vscode-eslint/blob/7568b4ce8413e890e5f7d99b18845ccd00fd3d1a/client/src/extension.ts#L1368-L1409

Otherwise my only recourse is to disable eslint globally, and then enable individually in the ~100 projects I have that do use eslint?

**Comment by dbaeumer** [comment]
For the extension it is very hard to decide if you don't want ESLint to run or whether something is misconfigured. This is why this message is shown ONCE for a workspace folder you open. After the first time the message should not appear again. If it does please provide me with a GitHub repository I can clone that demos this and I will have a look why this is not working for you.
