### ISSUE TITLE
ESLint: Invalid Options: - Unknown options: experimentalDecorators

### ISSUE THREAD

**Issue by Elanum** [microsoft/vscode-eslint#1389]
I've just setup a new typescript project with Next.js, but somehow i always get this error message when opening a `.tsx` fille:

<img width="461" alt="Screenshot 2021-12-15 at 09 27 50" src="https://user-images.githubusercontent.com/45352895/146150776-05547c65-4151-4f19-a7fc-eb95c268d2b1.png">

I already tried the solutions from this issue: https://github.com/microsoft/vscode/issues/28097 but it's still showing.

my `tsconfig.json`: 
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {}
  },
  "exclude": ["node_modules", "tmp"]
}
```

my `.eslintrc.json`:
```json
{
  "extends": ["airbnb", "airbnb-typescript", "plugin:prettier/recommended", "plugin:@typescript-eslint/recommended"],
  "ignorePatterns": "**/*.js",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "rules": {
    "react/react-in-jsx-scope": "off"
  }
}
```

and i also set this in my `settings.json`:
```json
{
  "js/ts.implicitProjectConfig.experimentalDecorators": true
} 
```

how can i disable this error or fix it?

**Comment by dbaeumer** [comment]
@Elanum  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Elanum** [comment]
> @Elanum does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

When i run `yarn lint` or `npx eslint .` then everything works.
Here is the branch that i created: https://github.com/Elanum/Elanum/tree/feature/nx-setup

**Comment by dbaeumer** [comment]
Works for me using the repository you provided. Any additional information you can share?

<img width="1076" alt="capture" src="https://user-images.githubusercontent.com/1931590/146188880-a1952c1f-0f49-438e-a6db-6cb5a9bf2e2b.png">

**Comment by dbaeumer** [comment]
Is there anything special in the ESLint Output channel?

**Comment by Elanum** [comment]
@dbaeumer here is my output console:
<img width="1082" alt="Screenshot 2021-12-16 at 08 26 48" src="https://user-images.githubusercontent.com/45352895/146326816-f34296c5-4184-49d9-8cdd-a553d06816e6.png">

**Comment by MrR4P70R** [comment]
Hi, I've been facing the same issue and fixed it myself because it was an user env problem.

I previously added this option "experimentalDecorators" in one of my VSCode's settings JSON file, issue was coming from there.
So be sure to check all of them : user, workspace and folder.

Search for this option in the JSON files and try to deleting it. :)

**Comment by Elanum** [comment]
> Hi, I've been facing the same issue and fixed it myself because it was an user env problem.
> 
> I previously added this option "experimentalDecorators" in one of my VSCode's settings JSON file, issue was coming from there. So be sure to check all of them : user, workspace and folder.
> 
> Search for this option in the JSON files and try to delete it. :)

Oh my god, this fixed it. Thank you so much @MrR4P70R !
