### ISSUE TITLE
Slow Lint response 

### ISSUE THREAD

**Issue by lgluigi** [microsoft/vscode-eslint#1390]
Issue Type: <b>Performance Issue</b>

After a software/ubuntu update, most of the time, lint is slowly responding, and sometimes get stuck for a couple minutes

Extension version: 2.2.2
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.11.0-41-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 3443)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|15.36GB (1.16GB free)|
|Process Argv|--unity-launch --crash-reporter-id bf87fe56-d0bb-4e1f-af84-954a7e62f580|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   142	 75024	code main
    0	    31	 75029	   zygote
    3	   126	 75061	     gpu-process
    0	    31	 75030	   zygote
    0	     0	 75032	     zygote
    1	    79	 86133	       issue-reporter
    0	    47	 75081	   utility-network-service
    1	   440	 75098	   window (● AddressUpdateDomainEventHandler.ts - cadastro-unificado-global-people-management - Visual Studio Code)
    0	   283	 75389	   extensionHost
    0	   126	 75779	     /usr/share/code/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/93b68f998eb8f05a23d3/tscancellation-15ee754a85583edee3b6.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
    0	   944	 75780	     /usr/share/code/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/93b68f998eb8f05a23d3/tscancellation-bc3b6f4d18664d55ed57.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
    0	    79	 75824	       /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/luigi/.cache/typescript/4.5 --enableTelemetry --typesMapLocation /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
    0	   598	 75978	     /usr/share/code/code --ms-enable-electron-run-as-node /home/luigi/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js --node-ipc --clientProcessId=75389
    0	   126	 75406	   shared-process
    0	    63	 75466	     ptyHost
    0	     0	 75832	       /usr/bin/bash
    0	    63	 75766	     watcherServiceParcelSharedProcess
    0	     0	 86151	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 86152	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t2:30407763
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by Parjoona** [comment]
Also got the same problem.
Happens on both Insiders and newest release of VSCode.

**Comment by lucas-giraldelli** [comment]
Yeah, I also got the same problem.
Tried fresh install of vscode (but same repos).

**Comment by lucas-giraldelli** [comment]
For me the problem was github copilot, resolved the issue deactivating him.

**Comment by dbaeumer** [comment]
Can you please enable tracing via the setting `"eslint.trace.server": "messages"` and attach the trace demonstrating the problem here. Then I can investigate and see whether this is an issue with the eslint server or VS Code itself

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
