### ISSUE TITLE
ecmaVersion 2022 is "not accepted" warning

### ISSUE THREAD

**Issue by scooper91** [microsoft/vscode-eslint#1391]
Hi!

[ESLint version 8 allows `ecmaversion` to be set to `2022`.](https://eslint.org/docs/user-guide/configuring/language-options#specifying-parser-options).

Using ESLint directly works fine (e.g. `./node_modules/.bin/eslint some/file.mjs`), but VSCode shows a warning in the `eslint` config file for the `ecmaversion" value saying `Value is not accepted. Valid values: 3, 5, 6, 2015, 7, 2016, 8, 2017, 9, 2018, 10, 2019, 11, 2020, 12, 2021, "latest".`.

Linting appears to be working correctly, but it shows as a problem in the file.

ESLint version: 8.4.1
VSCode version: 1.63.0
VSCode ESLint extension version: 2.2.2

Thanks!

**Comment by dbaeumer** [comment]
@scooper91 actually the JSON schema is maintained here: https://github.com/schemastore/schemastore/.  Best would be to give them a pull request to simply add `2022` as a value. Let me know how it goes.

**Comment by scooper91** [comment]
Thanks! The change has been merged into the project (https://github.com/SchemaStore/schemastore/commit/8709880521f3607ea2291757c492d504f708426e). It is all working in VSCode now.

Thanks for your help!
