### ISSUE TITLE
How to override .eslintrc.js in .vscode/settings.json?

### ISSUE THREAD

**Issue by isChenKan** [microsoft/vscode-eslint#1392]
just like vscode-prettier (then .prettierrc  configuration file will not be use):
```json
{
  "prettier.configPath": "./.vscode/my-prettier-settings.json"
}
```
![image](https://user-images.githubusercontent.com/26793777/146519406-12f31fb6-84d5-477b-ae69-09c5bee7a686.png)

**Comment by dbaeumer** [comment]
The the `eslint.options` setting and the documentation at https://eslint.org/docs/developer-guide/nodejs-api.

Please be aware the the properties of `eslint.options` depend on the version of ESLint you are using.
