### ISSUE TITLE
Server is sending diagnostics without a character field

### ISSUE THREAD

**Issue by ram02z** [microsoft/vscode-eslint#1393]
I'd like to preface that I am using the server packaged in https://github.com/hrsh7th/vscode-langservers-extracted. However, I thought this might still be an issue since the Neovim development team has said that LSPs should specify a column in their diagnostics.

Reference:
https://github.com/neovim/neovim/issues/16673#issuecomment-996066249
https://github.com/neovim/neovim/pull/16675

**Comment by dbaeumer** [comment]
@ram02z can you please provide me with the example code where this is happending since the npm ESLint module should have never generated this and I would like to forward the issue to the ESLint team.

**Comment by dbaeumer** [comment]
And I actually sanitize missing values to zero here: https://github.com/microsoft/vscode-eslint/blob/7568b4ce8413e890e5f7d99b18845ccd00fd3d1a/server/src/eslintServer.ts#L600

So I would really like to understand why this is happening.

**Comment by ram02z** [comment]
@dbaeumer sure. 

Here is the file: https://gist.github.com/ram02z/e85910e6b8aa1044637607c5c950f595

Here are the neovim lsp logs that have a missing column: https://gist.github.com/ram02z/b11a3bbd53211d0199a13b32ad1e7a81

**Comment by dbaeumer** [comment]
@ram02z thanks for the file. But it is not enough to reproduce this. It looks like it depends on some configuration files / plugins / eslint version. Can you provide me with a GitHub repository I can clone that demos this?

**Comment by ram02z** [comment]
@dbaeumer You were right about the error depending on configuration/plugins.

Seems like the eslint-plugin-jsdoc plugin was causing the issue when the file was opened with the following `eslintrc.json` file.
```json
{
  "parserOptions": {
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": ["jsdoc"],
  "rules": {
    "jsdoc/valid-types": 1
  }
}
```

The ESLint version is 8.6.0

**Comment by dbaeumer** [comment]
Thanks, was able to reproduce. The problem is that the jsdoc extension sets the values to `NaN` which is of type number in JS.
