### ISSUE TITLE
Extension resolves `parserOptions.project` differently from ESLint

### ISSUE THREAD

**Issue by jensmeindertsma** [microsoft/vscode-eslint#1394]
Hello all 👋
I'm building a monorepo where each package keeps it's own version of ESLint. When running ESLint from the command line things work great, but when I try to use the extension, it tries to resolve my `parserOptions.project` relative to the root of the project instead of the package root. This is a difference between ESLint and this extension. Is this intended?

**Comment by dbaeumer** [comment]
I am pretty sure that you need to specify the `eslint.workingDirectories` setting. When you run eslint from the terminal are you changing directories first?
