### ISSUE TITLE
No Babel config file detected for <filename>

### ISSUE THREAD

**Issue by sryze** [microsoft/vscode-eslint#1397]
I have a project where there is a top-level `.eslintrc.json` and another config inside a subdirectory. When I open a file located in that subdirectory, VSCode complains that ESLint can't find Babel config:

Parsing error: No Babel config file detected for path/to/files.jsx. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files.

But I do have `.babelrc` in both directories next to `.eslintrc.json`.

Here is my subdir configuration:

```
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": false
    },
    "parser": "@babel/eslint-parser",
    "parserOptions": {
        "ecmaVersion": 2018,
        "ecmaFeatures": {
            "jsx": true
        },
        "sourceType": "module"
    },
    "settings": {
        "react": {
            "version": "detect"
        }
    },
    "plugins": [
        "react"
    ],
    "extends": [
        "plugin:react/recommended"
    ],
    "rules": {
        "indent": ["warn", 4, {"SwitchCase": 1}],
        "brace-style": ["error", "1tbs"],
        "semi": ["error", "always"],
        "curly": ["error", "all"],
        "arrow-parens": ["error", "as-needed"],
        "comma-dangle": ["warn", "only-multiline"],
        "space-before-blocks": ["error", "always"],
        "space-before-function-paren": ["error", {
            "anonymous": "never",
            "named": "never",
            "asyncArrow": "always"
        }],
        "arrow-spacing": ["error", {
            "before": true,
            "after": true
        }],
        "keyword-spacing": ["error", {
            "before": true,
            "after": true
        }],
        "constructor-super": "warn",
        "valid-typeof": "warn",
        "no-const-assign": "warn",
        "no-this-before-super": "warn",
        "no-undef": "warn",
        "no-undefined": "error",
        "no-undef-init": "error",
        "no-unreachable": "warn",
        "no-unused-vars": ["warn", { "vars": "all", "args": "none"}],
        "no-invalid-regexp": "error",
        "no-multi-spaces": "warn",
        "no-multiple-empty-lines": ["warn", {"max": 1}],
        "react/prop-types": ["error", {"ignore": ["children"]}],
        "react/jsx-uses-react": "error",
        "react/jsx-uses-vars": "error",
        "react/button-has-type": "warn",
        "react/no-typos": "error",
        "react/no-array-index-key": "warn",
        "react/no-unused-state": "warn",
        "react/no-unused-prop-types": "warn",
        "react/self-closing-comp": "warn",
        "react/sort-comp": ["error", {
            "order": [
                "static-methods",
                "instance-variables",
                "lifecycle",
                "everything-else",
                "render"
            ]
        }],
        "react/void-dom-elements-no-children": "error",
        "react/jsx-pascal-case": "error",
        "react/jsx-props-no-multi-spaces": "warn",
        "react/jsx-tag-spacing": ["warn", {
            "closingSlash": "never",
            "beforeSelfClosing": "never",
            "afterOpening": "never",
            "beforeClosing": "allow"
        }]
    }
}
```

Top-level config:

```
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "parser": "@babel/eslint-parser",
    "parserOptions": {
        "sourceType": "module",
        "ecmaVersion": 2018
    },
    "rules": {
        "indent": ["warn", 4, {"SwitchCase": 1}],
        "brace-style": ["error", "1tbs"],
        "semi": ["error", "always"],
        "curly": ["error", "all"],
        "arrow-parens": ["error", "as-needed"],
        "comma-dangle": ["warn", "only-multiline"],
        "space-before-blocks": ["error", "always"],
        "space-before-function-paren": ["error", {
            "anonymous": "never",
            "named": "never",
            "asyncArrow": "always"
        }],
        "arrow-spacing": ["error", {
            "before": true,
            "after": true
        }],
        "keyword-spacing": ["error", {
            "before": true,
            "after": true
        }],
        "constructor-super": "warn",
        "valid-typeof": "warn",
        "no-const-assign": "warn",
        "no-this-before-super": "warn",
        "no-undef": "warn",
        "no-undefined": "error",
        "no-undef-init": "error",
        "no-unreachable": "warn",
        "no-unused-vars": ["warn", { "vars": "all", "args": "none"}],
        "no-invalid-regexp": "error",
        "no-multi-spaces": "warn",
        "no-multiple-empty-lines": ["warn", {"max": 1}]
    }
}
```

**Comment by dbaeumer** [comment]
You need to very likely need to configure the setting `eslint.workingDirectories`. IF you validate in the terminal do you do a chdir before? This is a good indication for specifying a working directory.

**Comment by sryze** [comment]
Got it, thank you :+1:  Adding this to my workspace settings solved the issue:

```
    "eslint.workingDirectories": [
        {"mode": "auto"}
    ],
```

**Comment by mahmoudelshawaf** [comment]
please can you tell me where you adding it in workspace settings?

**Comment by sryze** [comment]
@mahmoudelshawaf just put it inside inside `your_project_dir/.vscode/settings.json` 
https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings

**Comment by malikbendevv** [comment]
tried to add it to settings.json , but it says that this is an unknown configuration settings !!  can any one help please !

**Comment by jrtitus** [comment]
> tried to add it to settings.json , but it says that this is an unknown configuration settings !! can any one help please !

Don't forget to install the [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) in VS Code

**Comment by davonline4u** [comment]
go to your command line and type:

npm install
#the code above will install any dependency needed for your app
or
 simply create a new project or an open existing project
open the root folder of the project app
copy the babel.config file and paste into the root folder of your current project
restart your server

**Comment by joao-esteves** [comment]
> Got it, thank you +1 Adding this to my workspace settings solved the issue:
> 
> ```
>     "eslint.workingDirectories": [
>         {"mode": "auto"}
>     ],
> ```

This solves it, but it's not reasonable to ask everyone in a company to add this setting manually. Especially someone first joining a project and having to find out how to fix the linter. It should be either part of the `.eslintrc` or the default configuration value.

**Comment by larrykn** [comment]
it was really helpfull

**Comment by Ubuntufoo** [comment]
Much appreciated. It was in fact ESLint having issue. Adding the configuration above locally to project files did not do the trick, adding it globally did.

**Comment by SyedTayyabUlMazhar** [comment]
Another way to solve this is by specifying the directories explicitly like this:

`{ 
    "eslint.workingDirectories": [ "./client", "./server" ]
}`

Or you can also specify a glob pattern like this:

`{
    "eslint.workingDirectories": [{ "pattern": "./packages/**" }]
}
`

**Comment by Monstarrrr** [comment]
> > Got it, thank you +1 Adding this to my workspace settings solved the issue:
> > ```
> >     "eslint.workingDirectories": [
> >         {"mode": "auto"}
> >     ],
> > ```
> 
> This solves it, but it's not reasonable to ask everyone in a company to add this setting manually. Especially someone first joining a project and having to find out how to fix the linter. It should be either part of the `.eslintrc` or the default configuration value.

Using babel options in ``.eslintrc.json`` could work but I haven't been able to properly target the ``.babelrc`` file with it:

```json
/* .eslintrc.json */   

"parserOptions": {
  "babelOptions": {
    "configFile": "./.babelrc",
    "babelrc": true
  }
},
```

Gives me:  
> Parsing error: Cannot find module './.babelrc'

The Babel options documentation:  
https://babeljs.io/docs/options  

The Babel ESLint parser documentation:  
https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser#additional-parser-configuration

**Comment by Daniel-Damasceno** [comment]
`module.exports = {
  env: {
    browser: true,
    es2021: true,
    jest: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:react-hooks/recommended',
    'plugin:prettier/recommended',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parser: '@babel/eslint-parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  plugins: ['react', 'prettier', 'react-hooks', 'jsx'],
  settings: {
    react: {
      version: 'detect',
    },
  },
  rules: {
    'react/react-in-jsx-scope': 'off',
  },
};
`

I am add 'jsx' inside in plugins end resolved my problenm with [Parsing Error]
