### ISSUE TITLE
.eslintrc intellisense?

### ISSUE THREAD

**Issue by jwulf** [Microsoft/vscode-eslint#14]
Hi @dbaeumer,

The shape of the `.eslintrc` is known - what would be involved in adding support for intellisense for the schema when editing a `.eslintrc` file.

**Comment by egamma** [comment]
This is already in 0.10.4 :santa: 

You can now contribute a JSON schema in an extension and then you get Intellisense. The eslint extension contributes a schema for eslintrc

**Comment by jwulf** [comment]
Hi @egamma - I'm rocking 0.10.11, but I'm not seeing Clippy suggesting "jsx" as `ecmaFeature`. Pics attached:

![screen shot 2015-12-18 at 7 53 35 pm](https://cloud.githubusercontent.com/assets/406975/11894161/1f0e43c8-a5c1-11e5-8b64-00fc87457445.png)
![screen shot 2015-12-18 at 7 53 48 pm](https://cloud.githubusercontent.com/assets/406975/11894163/1ff38b4a-a5c1-11e5-98c4-827e1a45be37.png)

**Comment by jwulf** [comment]
Oh, is that VS Code 0.10.4? I'm still on 0.10.3. Guess 0.10.4 is the December release... :-)

![screen shot 2015-12-18 at 8 11 31 pm](https://cloud.githubusercontent.com/assets/406975/11894534/97ed3950-a5c3-11e5-97f8-74f5bf4ba945.png)

**Comment by egamma** [comment]
0.10.4 is the December pre-release, pls see https://github.com/Microsoft/vscode/wiki/December-Pre-Release

**Comment by jwulf** [comment]
Very cool. Thanks!
