### ISSUE TITLE
Fixed problems appear not fixed

### ISSUE THREAD

**Issue by moniuch** [microsoft/vscode-eslint#1400]
I am running a nodejs app written in TypeScript and I am experiencing an insane amount of problems.
An example would be

File without semicolons.
Adding semi rule to eslintrc.
VSCode: > ESLint: Fix all auto-fixable Problems

Result: semicolons added, but the squiggles still in place.
Only after I save the file, onSave effectively removes the squiggles
 
![image 2022-01-09 21-33-36](https://user-images.githubusercontent.com/681956/148699902-078c4bfc-7abe-49cc-bc5c-aec9888f0526.png)

Does using ESLint differ when running a Docker container? I don't have ESLint installed globally - either on my localhost or in the container.

    Plugin: v2.2.2
    "@typescript-eslint/eslint-plugin": "^5.7.0",
    "@typescript-eslint/parser": "^5.7.0",
    "eslint": "^8.5.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-unused-imports": "^2.0.0",
    "nodemon": "^2.0.15",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.4"

.eslintrc.json

```
{
  "root": true,
  "env": {
    "es2021": true,
    "node": true
  },
  "ignorePatterns": ["src/**/*.http", "**/*.js"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2021,
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint", "unused-imports"],

  "rules": {
    "semi": ["error", "always"],
    "quotes": [2, "single"],
    "unused-imports/no-unused-imports": 2,
    "@typescript-eslint/no-explicit-any": "off",
    "object-curly-spacing": ["error", "always"]
  }
}

```
Let me know if I can provide any more info?

**Comment by dbaeumer** [comment]
Do you have validate on save on for ESLint. See `eslint.run` setting?

If not can you please provider me with a GitHub repository I can clone that demos this.

**Comment by moniuch** [comment]
Thanks for getting back.
As I have been constantly experimenting with my setup (a source of a big frustration) since posting this issue, the problem described above is no longer in place. At that time the `eslint.run` setting wasn't present. I added it only now.

Now though I am at a completely different step, struggling with a different set of problems which don't belong to this ticket.

Can I ask you one question by the way: is Prettier necessary at all to achieve formatting (like converting double quotes to single)? I sometimes notice that only prettier rule fixes problems, but I would honestly hate to have to install Prettier if eslint is able to watch code style.

I would be willing to say that Prettier is yet another can of problems in the chain, if not the fact that it admittedly solves some of the formatting issues.

**Comment by dbaeumer** [comment]
No, prettier is not necessary. I do formatting solely with ESLint.
