### ISSUE TITLE
Eslint extension not working with no logs

### ISSUE THREAD

**Issue by smalllong** [microsoft/vscode-eslint#1405]
Checking the output, it's not showing whether the eslint library is loaded or not, just got stuck forever and not working. After I changed package manager to yarn, it works and shows a loaded log. After all, giving some logs in this case can be helpful.

<img width="481" alt="Screen Shot 2022-01-18 at 4 02 54 PM" src="https://user-images.githubusercontent.com/15830624/149895760-24d32897-b270-4822-9898-95a74bf0975c.png">

**Comment by dbaeumer** [comment]
@smalllong what package manager are you using normally?

**Comment by Juan-DeLeon** [comment]
I'm having this same issue. My package manager is npm and I'm running vscode with the extension installed under WSL, not sure if that has anything to do with it.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
