### ISSUE TITLE
vscode-eslint can't handle the babel-plugin-module-resolver rule

### ISSUE THREAD

**Issue by slalomzacharyd** [microsoft/vscode-eslint#1408]
I have code that uses both aliases and typescript and babel-plugin-module-resolver for when code is not going through the typescript compiler.  `vscode-eslint` doesn't seem to be applying the `babel-plugin-module-resolver` plugin.  

.eslintrc.js
```
module.exports = {
    settings: {
      'import/resolver': 'babel-module',
      react: {
        version: 'detect',
      },
    },
};
```
.babelrc.js
```
module.exports = {
      [
        'babel-plugin-module-resolver',
        {
          root,
          alias: {
            src: '.',
            ...alias,
          },
          extensions: ['.js', '.jsx', '.ts', '.tsx'],
        },
      ]
};
```

Output in vscode
```
Unable to resolve path to module 'src/pages/[redacted]'.
Unable to resolve path to module 'src/pages/[redacted]'.
Unable to resolve path to module 'src/pages/[redacted]'.
Unable to resolve path to module 'src/pages/[redacted]'.
Unable to resolve path to module 'src/pages/[redacted]'.
Unable to resolve path to module 'src/pages/[redacted]'.
```

Output in eslint
```
./node_modules/.bin/eslint applications/[redacted]/index.tsx
[no output, it all passed]
```

Expected:
`vscode-eslint` should work correctly like `eslint` and `eslint_d` with no special changes.

Actual:
`vscode-eslint` gives resolution warnings while it works everywhere else.

**Comment by dbaeumer** [comment]
@slalomzacharyd same here :-). Would you mind preparing a GitHub repository I can clone that demos this. It ensure that we will look at the same setup

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
