### ISSUE TITLE
Removing JSDoc function type mangles JavaScript inside HTML script tags

### ISSUE THREAD

**Issue by dotherightthing** [microsoft/vscode-eslint#1409]
My document consists of an HTML file containing only `<script></script>` tags, and JavaScript within those tags.

With the default (`true`) setting for `editor.codeActionsOnSave` removing the `@function` type from JSDoc comments in that JavaScript causes the JavaScript to be mangled.

## Versions

* VSCode: 1.63.2 (macOS)
* ESLint plugin: v2.2.2

## Trigger

* Removing `@function ` preceding `@function myFunctionName`

## Desired result

* A new line is inserted after `myFunctionName`

## Actual result

Random mangling of code, e.g.:

* last three letters of a JSDoc comment line appear on the next line
* closing curly brackets deleted

### Before

```html
<script>
/**
 * @function myFunction1
 * @param {Array} values - An array of values
 * @returns {Array}
 */
function myFunction1(values) {
  return values;
}

/**
 * @function myFunction2
 * @param {Array} values - An array of values
 * @returns {Array}
 */
function myFunction2(values) {
  return values;
}
</script>
```

### Action

Change `@function myFunction1` to `myFunction1` and save the document.

### After

```html
/**
 * myFunction1
 *
 * @param {Array} values - An array of values
 * @returns {Array}
 */rray}
 */
function myFunction1(values) {
  return values;
}

/**
 * @function myFunction2
 * @param {Array} values - An array of values
 * @returns {Array}
 */
function myFunction2(values) {
  return values;
}
</script>
```

### Before

```html
<script>
/**
 * @function myFunction1
 * @param {Array} values - An array of values
 * @returns {Array}
 */
function myFunction1(values) {
  return values;
}

/**
 * @function myFunction2
 * @param {Array} values - An array of values
 * @returns {Array}
 */
function myFunction2(values) {
  return values;
}
</script>
```

### Action

Change `@function myFunction2` to `myFunction2` and save the document.

### After

```html
<script>
/**
 * @function myFunction1
 * @param {Array} values - An array of values
 * @returns {Array}
 */
function myFunction1(values) {
  return va/**
 * myFunction2
 *
 * @param {Array} values - An array of values
 * @returns {Array}
 */rray}
 */
function myFunction2(values) {
  return values;
}
</script>
```

## Workaround

```
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": false
},
```

**Comment by dbaeumer** [comment]
@dotherightthing what happens when you run eslint in the terminal with the --fix option. If it works there can you please provide me with a GitHub repository I can clone that demos this. That way we ensure that we are using the exact same setup.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
