### ISSUE TITLE
Add a semicolon on a class property cause extension to gets confused on Typescript

### ISSUE THREAD

**Issue by matheus-rib** [microsoft/vscode-eslint#1411]
When you add a semicolon to a class property while you have `'@typescript-eslint/no-extra-semi'` on, it will cause to add a semi on every import statement and ESLint will act confused (saving will remove extra semi, but then it will add again). 

Since there's no ESLint rule that enforces to not use semicolon on class properties, it can cause someone else (like i did) to lose a lot of time running in circles.

# Versions
- VSCode: 1.63.2 (Ubuntu 20.04)
- ESLint plugin: v2.2.2

# Desired result
Remove the extra semi in whole file and save

# Actual result
Not removing any extra semi and saving the file with Lint issues

# Example
File with no Lint issues:
![image](https://user-images.githubusercontent.com/48499145/151688788-3913dae6-e3ef-4389-b8e5-01ec88d95125.png)

When adding a semi on any class property (e.g. on line 6):
![image](https://user-images.githubusercontent.com/48499145/151688810-632145b0-2b96-488b-96d0-5618ebe1b715.png)

**Comment by dbaeumer** [comment]
@matheus-rib does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing. This ensure that we are using the same setup in terms of eslint version, plugins, ...

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
