### ISSUE TITLE
ESLint VScode plugin not using the correct ESlint version

### ISSUE THREAD

**Issue by TomYang1993** [microsoft/vscode-eslint#1412]
I installed ESlint globally, But I still got errors from a feature deprecated in ESLint V5.

![Screen Shot 2022-01-30 at 8 08 00 PM](https://user-images.githubusercontent.com/20257736/151737658-db09c3a3-ff2b-4fb0-8873-71197d5e7010.png)
<img width="602" alt="Screen Shot 2022-01-30 at 8 09 43 PM" src="https://user-images.githubusercontent.com/20257736/151737742-b79b9d55-d532-496f-a19b-17c2806b79c0.png">

I tried in my terminal with `npx eslint somefile.js`, it's fine.

So I assume something is wrong with this ESlint extension.

macos 11.6.3
vscode 1.63.2
node 16.13.2
ESlint extension 2.2.2
ESlint 8.8.0

my eslintrc.json
![Screen Shot 2022-01-30 at 8 12 33 PM](https://user-images.githubusercontent.com/20257736/151737999-0d321c47-8370-489b-91e2-ff37d88eb624.png)

**Comment by dbaeumer** [comment]
Have you looked at the output of the ESLint channel. This will tell you which ESLint library it is using. May be there is one that the ESLint npm module finds first.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!

**Comment by dbaeumer** [comment]
Do the rules work when running ESLint in the terminal using the installed node module (not a global one)

**Comment by saerx** [comment]
Thanks for the response! 

After posting that comment, I checked and no, it doesn't seem to work in the terminal either using npx eslint

![image](https://user-images.githubusercontent.com/70779375/176873068-d546c359-bfdd-4ff3-8d22-e23aba02113c.png)
