### ISSUE TITLE
eslint create debug.log after vscode crashed

### ISSUE THREAD

**Issue by lgl017** [microsoft/vscode-eslint#1414]
After a oom chash, and reopen vscode, eslint will create debug.log when open a file(.ts or .vue) beside it.

![vscode oom](https://user-images.githubusercontent.com/27935867/152914892-d80e5b4e-330d-47e8-adcc-a8b2d33c402f.png)
![eslint](https://user-images.githubusercontent.com/27935867/152914895-c63a472b-b824-4856-8c95-4ef08842b5d6.png)

**Comment by dbaeumer** [comment]
This looks something that is done by the Electron node which I use to run the server. You can specify `eslint.runtime` to point to a different node version.

@deepak1556 have you seen something like this?

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
