### ISSUE TITLE
.prettierignore is not used when using eslint-config-prettier

### ISSUE THREAD

**Issue by EvHaus** [microsoft/vscode-eslint#1417]
When using the `vscode-eslint` extension combined with `eslint-config-prettier`, the ignore values set in `.prettierignore` are not being respected.

To reproduce this:

- Clone this repo where I've created a minimal reproduction https://github.com/EvHaus/prettier-vscode-ignore
- Install via `npm install`
- Note that running `npm run prettier` ignores `index.js`
- Note that running `npm run eslint` shows no errors
- Open `index.js` in VS Code with `vscode-eslint` installed
- Enable `"editor.formatOnSave": true` in VS Code settings
- Press Save
- BUG: The code contents get formated when they shouldn't.

Strangely the `vscode-prettier` extension doesn't have this problem, but for some reason `vscode-eslint` does.

**Comment by dbaeumer** [comment]
@EvHaus can you please add a `settings.json` file to the repository with your configuration. I guess that the formatting is actually coming from the TypeScript/JavaScript language feature and not from ESLint.

**Comment by dbaeumer** [comment]
If I add 

```json
{
	"eslint.format.enable": true,
	"editor.formatOnSave": true,
	"editor.defaultFormatter": "dbaeumer.vscode-eslint"
}
```
to the settings and saving index.js no formatting happens. So ESLint works correctly.

As said I guess that your configured formatter is TS/JS and hence that tool formats it.

**Comment by EvHaus** [comment]
Hmm. Indeed. Changing from:

```
{
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

to

```
{
  "editor.defaultFormatter": "dbaeumer.vscode-eslint"
}
```

fixed the issue for me. Unfortunately, now it means that Prettier doesn't work on any project or file which doesn't ESLint doesn't support (such as `package.json`).

Is there no way in VSCode to have it run ALL formatters rather than only choosing one?
