### ISSUE TITLE
vscode-eslint plugin not using the newest eslint

### ISSUE THREAD

**Issue by 4MOR3** [microsoft/vscode-eslint#1420]
**vscode-eslint: v2.2.2**

when using `#` to declare more than one private function in class like pic below: 
<img width="173" alt="Screen Shot 2022-02-15 at 10 00 04 AM" src="https://user-images.githubusercontent.com/39641565/153978333-4d4002d2-5c3f-44da-9e5d-b13742d311c7.png">

the error message is :`Duplicate name ''.eslint[no-dupe-class-members](https://eslint.org/docs/rules/no-dupe-class-members)`

<img width="501" alt="Screen Shot 2022-02-15 at 10 00 33 AM" src="https://user-images.githubusercontent.com/39641565/153978391-eaeff525-f47f-4f75-9277-7c71b1cee088.png">

 **What did you expect to happen?**
The method `#obliqueView` should not be flagged for anything

**Comment by IllusionMH** [comment]
From README:
> The extension uses the ESLint library installed in the opened workspace folder. If the folder doesn't provide one the extension looks for a global install version. If you haven't installed ESLint either locally or globally do so by running npm install eslint in the workspace folder for a local install or npm install -g eslint for a global install.

Looks like ESLint version in your project doesn't support this syntax.

**Comment by dbaeumer** [comment]
@4MOR3 have you checked which version of the ESLint library the extension is using. You can check by looking into the ESLint output channel. One of the first entries prints the path to the loaded library.

**Comment by 4MOR3** [comment]
it's the problem with my ESLint version. i've been using vue-cli, new project is vue3 so everything is ok, but this vue2 app's  ESLint's version is 6.7.2 , sorry for my carelessness
