### ISSUE TITLE
ESLint Crashes in a monorepo

### ISSUE THREAD

**Issue by samuelhulla** [microsoft/vscode-eslint#1422]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.64.2 (Universal) [LTS] ✅ 
- OS Version: OS: Darwin arm64 21.3.0

## Issue description 📔 

Hey, I've got a monorepo set up with multiple eslint configurations, however since the latest update I am unable to get my local vscode build of ESLint to work 

- *Anecdotally, the same configuration does work on WebStorm my colleagues are using*, which makes me presume this is an issue with vscode eslint detecting incorrect configuration in the monorepo.
- Running the react application via `yarn start` does run on node correctly, including ESLint warning and Errors. They just fail to compile inside VSCode.

The repo directory is set up in the following way:

```
.eslintrc
package.json
src/
   -- files
web/
   .eslintrc
   .packagejson
   -- files
```

However since the latest merge I can't get my ESLint to run locally in VSCode. Producing the following error:

> Error - 11:59:38 AM] Error: Plugin "@typescript-eslint" was conflicted between ".eslintrc#overrides[0]" and "../.eslintrc#overrides[0]".
    at mergePlugins (/Users/samuel/Coding/staffers/web/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1673:19)
    at createConfig (/Users/samuel/Coding/staffers/web/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1776:9)
    at ConfigArray.extractConfig (/Users/samuel/Coding/staffers/web/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1952:33)
    at CLIEngine.isPathIgnored (/Users/samuel/Coding/staffers/web/node_modules/eslint/lib/cli-engine/cli-engine.js:991:18)
    at CLIEngine.executeOnText (/Users/samuel/Coding/staffers/web/node_modules/eslint/lib/cli-engine/cli-engine.js:900:38)
    at ESLint.lintText (/Users/samuel/Coding/staffers/web/node_modules/eslint/lib/eslint/eslint.js:607:23)
    at /Users/samuel/.vscode/extensions/dbaeumer.vscode-eslint-2.2.1/server/out/eslintServer.js:1:178563
    at Ce (/Users/samuel/.vscode/extensions/dbaeumer.vscode-eslint-2.2.1/server/out/eslintServer.js:1:184511)
    at /Users/samuel/.vscode/extensions/dbaeumer.vscode-eslint-2.2.1/server/out/eslintServer.js:1:178521
    at /Users/samuel/.vscode/extensions/dbaeumer.vscode-eslint-2.2.1/server/out/eslintServer.js:1:179798

## What I tried 🔎 

 - Setting the parameter `"root": true` in the base `.eslintrc` in the project
 - Changing the working directory settings to
 
```bash
# .vscode/settings.json
{
  "eslint.workingDirectories": [
    "web",
    "src",
  ]
}
```

- Adding detection mode to auto in global vscode settings

```bash
# Code/User/settings.json
{
   ...
   "eslint.workingDirectories": [{ "mode": "auto" }]
}
```

However none of these helped and I still keep getting the error. Any idea how should i continue?

**Comment by dbaeumer** [comment]
The crash happens in the ESLint npm library itself. What happens when you try to lint the file in a terminal using the workspace folder as the current working directory?

**Comment by samuelhulla** [comment]
Hey @dbaeumer.

The one in `web/package.json` is  defined as 

`eslint --ext .jsx,.js,.ts,.tsx src/`

The repo is managed by `yarn`, so `yarn eslint --ext .jsx,.js,.ts,.tsx src/` returns similar error as mentioned above

```bash
yarn eslint --ext .jsx,.js,.ts,.tsx src/                               2 ✘  23s   12:24:29  
yarn run v1.22.17
warning ../../package.json: No license field
$ /Users/samuel/Coding/staffers/web/node_modules/.bin/eslint --ext .jsx,.js,.ts,.tsx src/

Oops! Something went wrong! :(

ESLint: 8.8.0

ESLint couldn't determine the plugin "jsx-a11y" uniquely.

- /Users/samuel/Coding/staffers/web/node_modules/eslint-plugin-jsx-a11y/lib/index.js (loaded in ".eslintrc » @webscopeio/eslint-config » eslint-config-airbnb » /Users/samuel/Coding/staffers/web/node_modules/eslint-config-airbnb/rules/react-a11y.js")
- /Users/samuel/Coding/staffers/node_modules/eslint-plugin-jsx-a11y/lib/index.js (loaded in "../.eslintrc » @webscopeio/eslint-config » eslint-config-airbnb » /Users/samuel/Coding/staffers/node_modules/eslint-config-airbnb/rules/react-a11y.js")

Please remove the "plugins" setting from either config or remove either plugin installation.

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not entiely sure, why it conflicted with different eslint plugin now instead of `@typescript-eslint` regardless, it seems there are troubles deciding between directories in the source application in `src/` and the web application `web/src`

```
npx eslint .
```

Returns the same result.

Running `yarn start` which is equivalent to `craco start` runs correctly and displays eslint errors and warnings

```bash
# ... skipped some warnings here for text clarity

src/staffers/api/storage/getPath.ts
  Line 76:3:  Expected no linebreak before this expression  implicit-arrow-linebreak

src/util/flatMap.ts
  Line 15:5:  Expected no linebreak before this expression  implicit-arrow-linebreak

src/util/index.ts
  Line 24:5:  Expected no linebreak before this expression  implicit-arrow-linebreak
  Line 43:3:  Expected no linebreak before this expression  implicit-arrow-linebreak

8 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in src/components/badges/Badge.tsx
  Line 4:9:  Don't use `Function` as a type. The `Function` type accepts any function-like value.
It provides no type safety when calling the function, which can be a common source of bugs.
It also accepts things like class declarations, which will throw at runtime as they will not be called with `new`.
If you are expecting the function to accept certain arguments, you should explicitly define the function shape  @typescript-eslint/ban-types

src/components/checkbox/CustomCheckbox.tsx
  Line 19:5:  Missing an explicit type attribute for button  react/button-has-type

src/components/companiesOverview/CompanyItemMin.tsx
  Line 35:22:  Unexpected require()  global-require

Search for the keywords to learn more about each error.

webpack 5.68.0 compiled with 1 error and 11 warnings in 52792 ms
No issues found.
```

**Comment by dbaeumer** [comment]
@samuelhulla the extension depends on vanilla ESLint npm module. So if an error shows up when running `eslint` in a terminal it will show up in VS Code itself. There is nothing I can do to prevent this.

All I can recommend is to report this against ESLint itself using the terminal command as an example. I know a lot about ESLint but I am not very familiar with how they resolve plugins and disambiguate them.

I will close the issue since IMO there is nothing that can be done in the extension. Please ping if I am missing something
