### ISSUE TITLE
Starting client failed - on ready failed

### ISSUE THREAD

**Issue by imjonlam** [microsoft/vscode-eslint#1423]
Hello, we recently updated our ESLint version from `7.32.0` to `8.8.0`.
In doing so we had to move our `runtime` setting from `eslint.options` to `eslint.runtime`
After this change we got the error.

The only thing that works is if we set `eslint.runtime` to "node" but ideally that's not what we want.

Full post here: https://stackoverflow.com/questions/71089277/eslint-vs-code-starting-client-failed-on-ready-failed

Nothing has changed besides bumping the version of ESLint and its dependencies.
Node version: `v14.18.3` (upgrading to latest did not fix this issue)

Thanks!

**Comment by dbaeumer** [comment]
The problem here is that the `options` settings have change in ESLint itself from version 7 to 8. For example `config` is now `overrideConfig`. I will add something to the readme to make this more clear. See https://eslint.org/docs/developer-guide/nodejs-api#-new-eslintoptions

**Comment by dbaeumer** [comment]
Added this to the readme:

Be ware that the ESLint npm module changed how options are interpreted. It also changed the names of certain options. If you used `eslint.options` to pass special options to the ESLint npm module you might need to adapt the setting to the new [form](https://eslint.org/docs/developer-guide/nodejs-api#-new-eslintoptions)

**Comment by imjonlam** [comment]
The `options` did change, that is correct. We had changed `config` to `overrideConfig` like you mentioned previously.

The issue is that when we changed `eslint.options: { runtime: ... }` to `eslint.runtime` as suggested in `v2.1.17`: that is when the error is received:
https://github.com/Microsoft/vscode-eslint/blob/HEAD/CHANGELOG.md

**Comment by dbaeumer** [comment]
Hmm, there was never a `eslint.options: { runtime: ... }` option? So this had never an impact and didn't select a node runtime.
