### ISSUE TITLE
IntelliSense for .eslintrc.yml?

### ISSUE THREAD

**Issue by AncientSwordRage** [microsoft/vscode-eslint#1424]
Is this possible?

I'm currently using [this](https://gist.github.com/alefteris/39c9cfe3a6baa9fc5acf) but would prefer autocompletion.

**Comment by dbaeumer** [comment]
This should actually come from a plugin that supports YAML files and not from the ESLint plugin itself. For JSON files the extension relies on a JSON plugin as well. Have you tried https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml. What you would need to do so is to point to a schema using the `yaml.schemas` setting.

**Comment by rchl** [comment]
I think that .eslintrc.yaml should work with that server without any extra configuration since the server automatically loads schemas from schema-store.

**Comment by AncientSwordRage** [comment]
I checked, and I already had it installed. 

![image](https://user-images.githubusercontent.com/5961746/162164418-d5de97bf-eaa6-4dd0-8143-e9cac6f22d6c.png)

![image](https://user-images.githubusercontent.com/5961746/162164179-432a5762-ae29-4544-9c26-cc70f84f84b1.png)

What next?

**Comment by rchl** [comment]
I don't think that schemas include all individual rules, just general eslint settings.

In any case, that's not an issue in this server.

**Comment by dbaeumer** [comment]
I will close the issue since no work is planned in this extension to provide the requested feature. As said should come from a YAML plugin.
