### ISSUE TITLE
Use of environment variables in options values

### ISSUE THREAD

**Issue by mjochum** [microsoft/vscode-eslint#1425]
We have an ESLint setup which uses a *custom ESLint plugin* that we would like to share across multiple projects.

Having the plugin already pre-installed as a dependency of a `GLOBAL_PACKAGE` which all users have by default, we can configure `.vscode/settings.json` to use a shareable config file (that `extends` and loads the plugin from that location): 
```json
"eslint.options": {
    "overrideConfigFile": "${PATH_TO_GLOBAL_PACKAGE}/shareableConfigFile"
}
```

Now, if the users also want to *check in* these user settings for a given project, `PATH_TO_GLOBAL_PACKAGE` may differ across their environments and I'm wondering whether it would be possible to get this from a variable?

I understand that we have the following constraints:

- VSCode only allows the use of environment variables in `launch.json` and `task.json`
- ESLint's option `overrideConfigFile` must be of type `string | null`, so `${PATH_TO_GLOBAL_PACKAGE}` would have to be interpreted *before* it gets passed on the ESLint library.

Do you think this would be possible or could you maybe recommend a workaround? Otherwise, I would also be willing to do a feature contribution (with your guidance) if such cases could be supported.

**Comment by dbaeumer** [comment]
This should come from VS Code. See https://github.com/microsoft/vscode/issues/2809 for the feature request there.
