### ISSUE TITLE
ESLint is ignoring changes across TypeScript projects

### ISSUE THREAD

**Issue by ftlPhysicsGuy** [microsoft/vscode-eslint#1427]
## The Setup
I have a typescript project (using Node.js and VSCode on macOS) with sub-projects for `server`, `client`, and `common` code.  Until recently, I kept all the typescript code for those sub-projects in one source folder (ugh!).  I have now changed my folder structure to separate the sub-projects like so:

```
src/
    client/
        index.ts
        [many .ts files]
        tsconfig.json
    common/
        index.ts
        [many .ts files]
        tsconfig.json
    server/
        index.ts
        [many .ts files]
        tsconfig.json
    tsconfig.json
tsconfig.json
```

The `client` and `server` index.ts files export from ../common/index, the src/tsconfig.json file uses "references" to provide paths to the `server`, `client`, and `common` src folders, and the tsconfig.json files under each sub-project extends the src/tsconfig.json file.

Both the `server` and `client` projects transpile and run just fine, but I'm having the following problem with ESLint:

## The Problem
When I change a file in the `common` directory and then make use of that change in one of the files under the `server` or `client`, ESLint ignores the change I made in the file under the `common` directory and claims that my changes in the `server` or `client` are unsafe references to an "any" type value.  The code still runs just fine, but ESLint is holding on to some cached version of the files in the common directory and ignoring the changes I made.

For example: Say I have a common class called `Player` and I add a method to that class called `GetState()`.  Then I go to a class in the client (let's call it `PlayerViewBinder`) and within it I make a call to `player.GetState()`.  ESLint complains that this is an `Unsafe call of an 'any' typed value.` I can right click on the `GetState()` call and say "Go to Definition," and VSCode knows exactly where that new method it is, but ESLint doesn't see it.

The only way I've found to clear that issue is to transpile the server, quit VSCode, and restart VSCode.

## The ESLintrc File
I can run ESLint manually to get the same results using the following command: ./node_modules/eslint/bin/eslint.js . --ext .ts

My .eslintrc.json file looks like this:

```
{
    "env": {
        "browser": true,
        "es6": true
    },
    "ignorePatterns": ["webpack.config.js", "src/misc/*"], 
    "parser": "@typescript-eslint/parser",
    "plugins": [
        "eslint-plugin-import",
        "eslint-plugin-jsdoc",
        "eslint-plugin-prefer-arrow",
        "@typescript-eslint",
        "@typescript-eslint/tslint"
    ],
    "parserOptions": {
        "project": ["./src/tsconfig.json", "./src/common/tsconfig.json", "./src/server/tsconfig.json", "./src/client/tsconfig.json"],
        "sourceType": "module"
    },
    "overrides": [
        {
            "files": ["*.ts"],

            "extends": [
                "plugin:@typescript-eslint/recommended",
                "plugin:@typescript-eslint/recommended-requiring-type-checking"
            ]
        }
    ],
    "rules": {
        "@typescript-eslint/no-unused-vars":  [
            "error",
            {
                "vars": "all",
                "args": "none",
                "ignoreRestSiblings": false
            }
        ],
        "@typescript-eslint/unbound-method": [
            "error",
            {
                "ignoreStatic": true
            }
        ]
    }
}
```

## The tsconfig.json files

Starting at the top level (same directory as src) I have the following tsconfig.json files

/tsconfig.json
```
{
    "compilerOptions": {
        "target": "es2017",
        "lib": [
            "es6",
            "dom",
            "es2017.object",
            "es2017"
        ],
        "module": "commonjs",

        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "strict": true,
        "noUnusedLocals": true,
        "esModuleInterop": true,

        "rootDir": ".",
        "outDir": ".",              // if out path = src path, nothing is emitted
        "resolveJsonModule": true,
        "composite": true
    },
    "files": [  ],
    "references": [             // references all the projects
        { "path": "./src/common" },
        { "path": "./src/server" },
        { "path": "./src/client" },
    ],
}
```

/src/tsconfig.json
```
{
    "compilerOptions": {
        "target": "es2017",
        "lib": [
            "es6",
            "dom",
            "es2017.object",
            "es2017"
        ],
        "module": "commonjs",

        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "strict": true,
        "noUnusedLocals": true,
        "esModuleInterop": true,

        "rootDir": ".",
        "outDir": ".",                  // if out path = src path, nothing is emitted
        "resolveJsonModule": true,
        "composite": true
    },
    "files": [  ],
    "references": [             // references all the projects
        { "path": "common" },
        { "path": "server" },
        { "path": "client" },
    ],
}
```

/src/common/tsconfig.json
```
{
    "extends": "../tsconfig.json",

    "include": [
        "./*.ts",
    ],

    "compilerOptions": {
        "target": "es2017",
        "lib": [
            "es6",
            "dom",
            "es2017.object",
            "es2017"
        ],
        "module": "commonjs",

        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "strict": true,
        "noUnusedLocals": true,
        "esModuleInterop": true,

        "rootDir": ".",
        "outDir": "../../build/common",
        "sourceMap": true,
        "composite": true,
    },
}
```

/src/server/tsconfig.json
```
{
    "include": [
        "./*.ts",
    ],

    "compilerOptions": {
        "target": "es2017",
        "lib": [
            "es6",
            "dom",
            "es2017.object",
            "es2017"
        ],
        "module": "commonjs",

        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "strict": true,
        "noUnusedLocals": true,
        "esModuleInterop": true,

        "rootDir": ".",
        "outDir": "../../build/private",
        "sourceMap": true,
        "composite": true,
    },
    "references": [
        { "path": "../common" }
    ],
}
```

/src/client/tsconfig.json
```
{
    "include": [
        "./*.ts",
    ],

    "compilerOptions": {
        "target": "es2017",
        "lib": [
            "es6",
            "dom",
            "es2017.object",
            "es2017"
        ],
        "module": "commonjs",

        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "strict": true,
        "noUnusedLocals": true,
        "esModuleInterop": true,

        "rootDir": ".",
        "outDir": "../../build/public",
        "sourceMap": true,
        "composite": true,
    },
    "references": [
        { "path": "../common" }
    ],
}
```

## The Closing
I'm assuming that I'm doing something wrong, but if its a bug...

Let me know if there is any other info that would be helpful and thank you for any help you can provide.

**Comment by dbaeumer** [comment]
This can depend on many things and without a GitHub repository I can clone that demos this in a minimal setup hard to tell. The most likely case is that the tsconfig.json files don't reference each other (e.g. client -> common and server -> common). You might look here for an example: https://github.dev/microsoft/vscode-languageserver-node/blob/309dd5172f2bc63be834eedf2832b9f99a908ad3/client/tsconfig.json#L1

**Comment by ftlPhysicsGuy** [comment]
Thanks for the comment, @dbaeumer.

Looking at the example you provided, the references in my tsconfig.json files look very similar.  I'll add them to my original post for more info.  I'll also see if I can create a very small example of the issue to make available on GitHub.

**Comment by ftlPhysicsGuy** [comment]
I have created a small project that seems to demonstrate the issue:

[ESLintTest.zip](https://github.com/microsoft/vscode-eslint/files/8129304/ESLintTest.zip)

It contains only 2 sub-projects (`common` and `server`), and each of those contain only one .ts file ("TestState.ts" for `common` and "DummyServer.ts" for `server`).

The included tsconfig.json files are nearly identical to the ones in my actual project.

The node modules to be installed (via `npm install`) are for typescript, ts-node, eslint, and some eslint plug-ins.

Everything needed to demonstrate the issue is in the enclosed folder, including the following readme file:

readme.txt
```
This is a test project intended to demonstrate issues with ESLint not recognizing cross-project changes.

The demonstration was originally performed using VSCode 1.64.2 on macOS 12.2.1

Demonstration
==============
Follow these steps to demonstrate the issue:

0. Prerequisite: You must have npm installed for any of this to make much sense :)
1. In a terminal window, change directory to the enclosed directory and run the following:
   > npm install
2. Open the workspace file (ESLintTest.code-workspace) in VSCode
3. Make sure the Problems panel is showing in VSCode (View > Problems)
4. Open the ./src/server/DummyServer.ts file in VSCode
    a.  You should note in the Problems panel that ESLint is showing 4 problems in the
        DummyServer.ts file:
       * Unsafe assignment of an `any` value.
       * Unsafe construction of an any type value.
       * Invalid type "any" of template literal expression.
       * Unsafe member access .stateLength on an `any` value.
    b. Inspecting the code, you should be able to determine that none of those errors are valid:
        i.  The errors seem related to ESLint not seeing the code being referenced in the
            `common` project.
    c. Note that VSCode can follow the references:
        i.   Right-click on the text "TestState" on line 8 of DummyServer.ts
        ii.  From the dropdown menu, select "Go To Definition"
        iii. Note that VSCode jumps to the definition in the ./src/common/TestState.ts file.
5. Show that the code runs just fine as well:
    a. From the "Run and Debug" sidebar of VisulStudio, select "Launch Program" at the top.
    b. In the Debug Console (near the Problems
[readme.txt](https://github.com/microsoft/vscode-eslint/files/8129298/readme.txt)
 panel), note that the correct text has been
       written to the console (This is a test: 5)
6. Quit VSCode, then restart the ESLintTest.code-workspace workspace
    a. The errors should now be gone.
    b. However, making any changes in TestState.ts (e.g., adding a property) and referencing those
       changes in DummyServer.ts (e.g., accessing the new property) should cause ESLint to again
       complain of "bogus" errors.  To Demo this:
        i.   Insert this property at line 12 of TestState.ts (and save the changes):
             public four = 4;
        ii.  Change line 16 of DummyState.ts to the following:
             console.log(`This is a test: ${tmpServer.testState.stateLength + tmpServer.testState.four}`);
        iii. ESLint will see the reference to "four" as an invalid use of type "any".
             Again, VSCode has no problem making the connection via the references.


Hopefully someone can tell me what I'm doing wrong here.  It seems to have something to do with
ESLint needing to have the code transpiled to the .js files before it will recognize the
cross-project code, but I don't know what to do to make it act property.
```

**Comment by ftlPhysicsGuy** [comment]
So, I posted a working example of my issue a couple of weeks ago and haven't gotten any responses.  Can anyone else verify they see the same issue when using my example?  Am I doing something wrong or is this a bug?  Thanks.

**Comment by GraemeF** [comment]
I haven't tried in VSCode but I'm seeing a similar issue in Webstorm (in my project, haven't tried your repro project). Maybe this issue should be reported to the ESLint repo?

**Comment by romainlp** [comment]
@ftlPhysicsGuy Do you have the `gitlens` extension installed? I had similar issue and noticed that if i remove gitlens, it works well.

**Comment by dbaeumer** [comment]
This is not a problem with the ESLint extension but the ESLint and the TypeScript plugin itself. Running ESLint in the terminal produces:

```
./node_modules/.bin/eslint src/server/DummyServer.ts

/ESLintTest/src/server/DummyServer.ts
   8:9   error  Unsafe assignment of an `any` value                  @typescript-eslint/no-unsafe-assignment
   8:26  error  Unsafe construction of an any type value             @typescript-eslint/no-unsafe-call
  16:32  error  Invalid type "any" of template literal expression    @typescript-eslint/restrict-template-expressions
  16:32  error  Unsafe member access .stateLength on an `any` value  @typescript-eslint/no-unsafe-member-access

✖ 4 problems (4 errors, 0 warnings)
```

which are the exact same error.

Running the project and then running eslint in the terminal again makes the errors got away as well.

I recommend that you report the bug against the typescript eslint plugin since there is little I can do in the extension to fix this.

**Comment by ftlPhysicsGuy** [comment]
I posted the issue to [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint), and it turns out that they do not support project references.  [See this link](https://github.com/typescript-eslint/typescript-eslint/issues/2094)
