### ISSUE TITLE
Wierd linting bug

### ISSUE THREAD

**Issue by Xenfo** [microsoft/vscode-eslint#1429]
When I open a file in the `packages/checkbox` directory on initial load, then ESLint works fine from what I can tell. If I open a file from `scripts` on initial load, there is an ESLint error as shown in the video. Everything works fine in CMD.

Repo: https://github.com/flux-ui/flux-ui/tree/feat/checkbox-variants
Example: https://user-images.githubusercontent.com/46873232/156261140-671c1d0b-2509-4006-9ecf-21072a7ca29f.mp4

**Comment by dbaeumer** [comment]
Is there anything special in the ESLint output channel?

**Comment by dbaeumer** [comment]
I tried to reproduce this but couldn't. Can you please provide me with steps to do so. And I noticed that you have a working directories setting but scripts is not listed.

**Comment by dbaeumer** [comment]
OK. I can reproduce now, but I have no good explanation for why this is happening. Very likely an issue of some caching in the eslint module.

**Comment by dbaeumer** [comment]
I digged a little bit around and it looks like a setup problem (very likely on your end). If I change `useUuid` in file `use-uuid.ts` for `useUuid$$` and run `npm run build` I get

<img width="839" alt="capture" src="https://user-images.githubusercontent.com/1931590/157035186-7f5d013c-6d10-46ad-a0d0-743b37ffd4db.png">

which give the same errors whithout TypeScript complaining about that `useUuid` is not a know identifier which IMO should be the case.

**Comment by Xenfo** [comment]
With $$ at the end it works fine.

Branch: https://github.com/Xenfo/flux-ui
Run: https://github.com/Xenfo/flux-ui/runs/5449584111?check_suite_focus=true

Could it be the experimental feature I have enabled for Typescript ESLint in my foot config?

**Comment by dbaeumer** [comment]
Actually what I meant is only changing `useUuid` to `useUuid$$` in `use-uuid.ts`. In this case I would expect that the TS compiler reports an error in checkbox.ts which it doesn't and ESLint still reports the error (even in the terminal). This indicates that the TS configuration isn't setup correctly resulting in TypeScript ESLint not working correctly either.
