### ISSUE TITLE
Doesn't detect eslint on $PATH

### ISSUE THREAD

**Issue by Kyuuhachi** [microsoft/vscode-eslint#1430]
If eslint is installed via a distro package manager (here Arch's pacman/yay), the language server can't find the executable unless npm is also installed, even though it is available on `$PATH`.

Tested on neovim (0.7.0+dev+1130+g11f7aeed7-1) using nvim-lspconfig (ec7119b), with `vscode-langservers-extracted` (4.1.0-1) and `eslint` (8.10.0-1).

**Comment by dbaeumer** [comment]
This is by design. The extension doesn't execute the eslint command it loads its library and keeps it in memory to speed up validation on typing.
