### ISSUE TITLE
eslint.codeActionsOnSave.rules not working

### ISSUE THREAD

**Issue by bengry** [microsoft/vscode-eslint#1431]
I've tried to use `eslint.codeActionsOnSave.rules` as documented to remove some rules from being ran while saving, but it seems like it doesn't work.

I tried using this in both the User settings and the Workspace settings (ideally this would be in the workspace so I can share it with my team).

doesn't work:
```json
"settings": {
  "eslint.codeActionsOnSave.rules": [
    "!import/no-extraneous-dependencies",
    "*"
  ],
}
```

works:
```json
"settings": {
  "eslint.options": {
    "overrideConfig": {
        "rules": {
			"import/no-extraneous-dependencies": "off",
         }
    }
  }
}
```

I verified this by adding this line to `node_modules/eslint-plugin-import/lib/rules/no-extraneous-dependencies.js`'s `create` method:
```js
require('fs').writeFileSync('/tmp/eslint-run.txt', 'import/no-extraneous-dependencies ran!', 'utf8');
```

In the `eslint.codeActionsOnSave.rules`'s case the file is being created on every file save, while in the `eslint.options.overrideConfig.rules` it isn't.

The disadvantage of this workaround of course is that now in VS Code I get no indicator that this rule has been violated, even though I just want it to not block my file saves.

I'm using:
`dbaeumer.vscode-eslint` @ 2.2.2
`eslint` @ 8.9.0

**Comment by dbaeumer** [comment]
This works for me:
![cast](https://user-images.githubusercontent.com/1931590/157030624-74a05d71-fb0a-4967-bd32-b02ef0ad145b.gif)


Could you please provide me with a GitHub repository I can clone that demos what you are seeing. That ensures that we are looking at the exactly same setup.

**Comment by bengry** [comment]
Thanks @dbaeumer - here's a repo with a reproduction https://github.com/bengry/vscode-eslint-code-actions-on-save-repro

Clone it, run `npm install` and save `second.js` (or `first.js`) while looking at `cycle-run.txt` - every time you save a line gets added to it.

![screencast 2022-03-07 14-51-00](https://user-images.githubusercontent.com/260431/157038098-8295a121-9dfa-4790-b7c6-77a80b8d1df5.gif)

**Comment by remcohaszing** [comment]
I also just ran into this issue when adding a new rule to prevent from being autofixed. I have the following config:

```jsonc
{
  // …
  "eslint.codeActionsOnSave.rules": [
    "!no-debugger",
    "!jest/prefer-todo",
    "*"
  ],
  // …
}
```

I’ve been excluding `no-debugger` succesfully for a while now, but `jest/prefer-todo` is still being auto fixed. Also when `!no-debugger` is removed, `jest/prefer-todo` is still being autofixed. Maybe it doesn’t work for plugin rules?

**Comment by bengry** [comment]
> I was able to reproduce. The problem is that this is fixed in the pre-release version which I used to test it the first time.
> 
> The pre-release version this is fixed in is `2.2.3`. I plan to ship a new final version end of March / beginning of April

Are you sure it's fixed in `2.2.3`? I just tried it there with the same repo I linked above and it still reproduces:

![screencast 2022-03-14 13-11-39](https://user-images.githubusercontent.com/260431/158161085-828c35ac-43e9-4118-9636-d2f1ecbd6ce0.gif)

**Comment by dbaeumer** [comment]
Here is what I have tested and see

- remove the setting from the settings file
-  open `second.js` 
- Without typing press Ctrl+S => entry in the `cycle-run.txt`
- add the setting to the settings file again
- open `second.js`
- Without typing press Ctrl+S => no entry in `cycle-run.txt`

If you type into a JS file it is immediately validated (without waiting for a save) and hence the cycle run is executed. The setting is only honor when you actually save the file.

**Comment by remcohaszing** [comment]
This appears to have been fixed when using `editor.codeActionsOnSave` `source.fixAll`, but not when `editor.formatOnSave` is `true`.

https://user-images.githubusercontent.com/779047/158379081-7b947c01-188f-44e6-9d4a-f645271be032.mp4

These are the settings used:

```json
{
  "eslint.codeActionsOnSave.rules": ["!no-debugger", "!jest/prefer-todo", "*"],
  // "editor.formatOnSave": true,

  "[javascript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll": true
    },
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
}
```

This is the code I used to test (`foo.test.js`):

```js
it('foo', () => {});

debugger;

const a = 'foo' + asd;
```

The repository that was used for the recording can be found [here](https://github.com/remcohaszing/eslint-config).

**Comment by cdpark0530** [comment]
@remcohaszing Indeed `"editor.formatOnSave": true` ignores opt-in list of `eslint.codeActionsOnSave.rules`.

The opt-in feature only plays with this `.vscode/settings.json` on `dbaeumer.vscode-eslint 2.2.3`, `"eslint": "^8.13.0"`.
```
{
  "[javascript]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  },
  "[typescript]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  },
  // "editor.formatOnSave": true,
  "editor.formatOnPaste": false,
  "editor.formatOnType": false,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
  },
  "eslint.format.enable": true,
  "eslint.useESLintClass": true,
  "eslint.codeActionsOnSave.rules": [
    "semi", // example
  ],
}
```

**Comment by kirill-develops** [comment]
hey mate, Trying to get ESLINT to auto fix certain issues, but not all.

for example, I'd like it to handle arrow function formating, and spaces, and semicolans and quotes 

` "eslint.codeActionsOnSave.rules": [
    "*semi*",
    "*jsx-quotes*"
  ],`

**Comment by cdpark0530** [comment]
@kirill-develops I found [a solution](https://stackoverflow.com/a/71836561/10694438) for that.

**Comment by kirill-develops** [comment]
> @kirill-develops I found [a solution](https://stackoverflow.com/a/71836561/10694438) for that.

@cdpark0530 Legend mate! exactly what i was looking for!

**Comment by kirill-develops** [comment]
@cdpark0530 for whatever reason it's not actually doing anything on save and i have `editor.FormatOnSave: false`

any ideas?

**Comment by cdpark0530** [comment]
@kirill-develops everything I know about this matter is in that answer. Make sure that your plugin is version 2.2.3, and your eslint config is correct(by checking if there is any error message in eslint plugin console)
