### ISSUE TITLE
using React.Children.toArray for arrays and es-lint still asking for key prop

### ISSUE THREAD

**Issue by jayant246** [microsoft/vscode-eslint#1433]
As react docs suggest,  **React.Children.toArray(children)** Returns the children opaque data structure as a flat array with keys assigned to each child. But Es-Lint still suggest to add key prop.
Docs link - https://reactjs.org/docs/react-api.html#reactchildrentoarray
PFA screenshot:
![Screenshot from 2022-03-11 15-47-30](https://user-images.githubusercontent.com/43151324/157848143-643f81c0-f58c-4648-b2ce-f00f9c1f7228.png)

**Comment by dbaeumer** [comment]
Does the validation happen correctly when you use eslint in the terminal. And can you please show me the full error in the problems view.

If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
