### ISSUE TITLE
Unable to resolve path to module "@/..."

### ISSUE THREAD

**Issue by I2olanD** [microsoft/vscode-eslint#1437]
Hey,

we're currently using a monorepo (yarn workspaces) but using single eslint file with following structure:

```
root/  
  packages/  
    package-a/  
    package-b/
  utils/  
    eslint-config/  
      index.js  
.eslintrc.js  
```

eslintrc.js in the root is basically exporting the contents of utils/eslint-config/index.js. Running the linter via cmd works fine, but the extension is unable to resolve webpack import aliases.

**Comment by dbaeumer** [comment]
When you run ESLint on the command line do you change directory into one of the package directories. If so you need the ESLint extension know about this using the `eslint.workingDirectories` setting. 

If you execute the command in the workspace folder root and everything works there can you please provider me with a GitHub repository that demos this that I can clone.
