### ISSUE TITLE
"Extension 'ESLint' is configured as formatter but it cannot format 'Typescript'-files

### ISSUE THREAD

**Issue by caiqalmeida** [microsoft/vscode-eslint#1439]
Hey, I'm having this problem when ESLint don't format my Typescript code. 
I've already installed previous versions, reinstalled my vs code and I keep getting this error message.

My ESLint configs on vs code :

`
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "eslint.alwaysShowStatus": true,
"[javascript]": {
  "editor.defaultFormatter": "dbaeumer.vscode-eslint"
},
"[typescript]": {
  "editor.defaultFormatter": "dbaeumer.vscode-eslint"
},
  "eslint.validate": [
    "javascript",
    "typescript",
    "html",
],
"eslint.format.enable": true,
"editor.formatOnSave": true,
"editor.defaultFormatter": "dbaeumer.vscode-eslint",
`

<img width="1264" alt="Screen Shot 2022-03-26 at 01 04 21" src="https://user-images.githubusercontent.com/30331581/160241135-24fe67e4-2808-4be5-98f8-e05a371c4f4f.png">

Has anyone else had this problem? I saw some similar problems on google, but nothing that solves mine.

My notebook is a MacBook Air M1.

**Comment by dbaeumer** [comment]
Without a reproducible case (e.g. a GitHub repository to clone) hard to tell why it is not working.

**Comment by caiqalmeida** [comment]
I have trouble in any project with typescript, not one in specific. 
But if you want i can create one, no problem.

**Comment by dbaeumer** [comment]
Yes please.

**Comment by caiqalmeida** [comment]
I was creating an example: https://github.com/caiqalmeida/eslint-typescript-example and it appeared to update eslint to version 2.2.2, looks like it's fixed !

Sorry for bothering, appreciate your atention !
