### ISSUE TITLE
The Extention uses ESLint installed as dependency of a dependency instead of a root dependency

### ISSUE THREAD

**Issue by saelfaer** [Microsoft/vscode-eslint#144]
The documentation tells us  (currently i'm at 1.0.6 of the vscode-eslint extension)

"The extension uses the ESLint library installed in the opened workspace folder. If the folder doesn't provide one the extension looks for a global install version."

but I notice the following behavour:

ESLINT not globally installed on my pc

`npm list` in the project folder:

```
...
├─┬ eslint@3.5.0
...
├─┬ grunt-sass-lint@0.1.2
│ └─┬ sass-lint@1.9.0
│   ├─┬ eslint@2.13.1
...
```

package.json

```
...
dependencies: {
...
    "eslint": "^3.0.0",
...
}
```

In Visual Studio Code's internal terminal window, execute:

```
sander@vagrantbox $ eslint -v                                                                            
v2.13.0                                                                                                                                       
sander@vagrantbox $ ./node_modules/eslint/bin/eslint.js  -v                                              
v3.5.0                                              
```

this leads me to believe, the exposed eslint version prefers the dependency of a dependency over the one specified as root dependency.

**Comment by dbaeumer** [comment]
No, it shouldn't. The extension is not coupled to the terminal. You can enable tracing to see what module will be resolved. Set the setting `"eslint.trace.server": "messages"`. This should print the resolve module path in the ESLint Output panel. If it resolves the wrong one please let me know.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
