### ISSUE TITLE
Cannot find module './App.vue' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by CRC32EX** [microsoft/vscode-eslint#1440]
# Steps to reproduce this issue

1. Init Vue3 project
```
npm init vue@latest
```
![image](https://user-images.githubusercontent.com/25629617/160763495-cc6832d3-bebf-4e73-b03a-64678957cf87.png)

2. Install modules
```
npm install
```

3. Open VSCode

4. Error
```
Cannot find module './App.vue' or its corresponding type declarations.ts(2307)
```

![image](https://user-images.githubusercontent.com/25629617/160763573-3dd47680-9704-4940-aecd-3400c1c9b0d2.png)

# Environment
|#|Version|
|:--|:--|
|OS|Windows 11 64bit|
|VSCode|1.65.2 (user setup)|
|VSCode ESLint Extension|2.2.2|

```
$ node --version
v16.14.2
```

**Comment by dbaeumer** [comment]
This error doesn't come from eslint. It comes from TypeScript  as you can see from the prefix `ts(2307)`. ESLint errors have a prefix that starts with `eslint`.

**Comment by CRC32EX** [comment]
Solved.
I'm create `src/shims-vue.d.ts`

```typescript
declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent
  export default component
}
```


![image](https://user-images.githubusercontent.com/25629617/161054801-86c85747-28b3-421a-8dc1-2c7e2d32b486.png)
