### ISSUE TITLE
A weird one package.json error

### ISSUE THREAD

**Issue by wChenone** [microsoft/vscode-eslint#1442]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/37658262/161204010-5cb12cdc-6d1e-4f8c-b622-983abe4b5e8d.png">

some projects  report  errors，and some projects are normal

**Comment by dbaeumer** [comment]
@wChenone  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by wChenone** [comment]
> does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing

hi，I reinstalled vscode today, and then the error disappeared. Next time I meet you, I will provide a GitHub repository.

**Comment by wChenone** [comment]
> @wChenone does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

hi，Now I have a problem again. As long as I npm install, I will make a mistake.
 The address ：  https://github.com/wChenone/testPackageERR

**Comment by dbaeumer** [comment]
@wChenone I can't reproduce this. Any additional steps I need to take:

![capture](https://user-images.githubusercontent.com/1931590/161490683-4825cfcb-e27e-44ad-9ae1-574d751c1653.png)

**Comment by wChenone** [comment]
> @wChenone I can't reproduce this. Any additional steps I need to take:
> 
> ![capture](https://user-images.githubusercontent.com/1931590/161490683-4825cfcb-e27e-44ad-9ae1-574d751c1653.png)

<img width="676" alt="image" src="https://user-images.githubusercontent.com/37658262/161686316-3fd50454-990e-4126-9459-6bced8858476.png">

<img width="263" alt="image" src="https://user-images.githubusercontent.com/37658262/161686518-15ff8cc1-2047-4d97-9160-558ac0cf6aae.png">

This is mine, do not need any settings, pull down the install, just like this, I am using the vscode insiders version

**Comment by dbaeumer** [comment]
@sandy081 can you please give this a try under Mac. Might be path related. Steps are here: https://github.com/microsoft/vscode-eslint/issues/1442#issuecomment-1086583188

**Comment by sandy081** [comment]
I can't repro too.

**Comment by dbaeumer** [comment]
@sandy081 thanks

@wChenone we can't reproduce this neither on Mac nor on Linux. As asked earlier: does the validation happen correctly when using eslint in a terminal for that file?

**Comment by wChenone** [comment]
@sandy081   
My computer is also mac.  When you use eslint on this file in the terminal, it also reports an error.      
![image](https://user-images.githubusercontent.com/37658262/161946039-bf239973-0e20-4d6d-9157-7a8ed16da523.png)

**Comment by dbaeumer** [comment]
@wChenone then this is a general setup problem with ESLint and not with the VS Code eslint extension. All I can recommend is to find help with that in a public ESLint forum or at their repository.
