### ISSUE TITLE
Allow specifying nearest config directory as working directory

### ISSUE THREAD

**Issue by ocket8888** [microsoft/vscode-eslint#1448]
Currently, I can specify that the eslint working directory should be
- workspace folder
- linted file directory
- "auto" inferred (the meaning of which is not very clear)
- specific sets of directories or directory globs

Consider a layout for an Angular project that uses Nightwatch for end-to-end testing. Nightwatch uses property names for some configuration options that need to be quoted like e.g. `ms:edgeOptions`. I want to enforce that code we write in typescript uses `camelCase` properties, but the `nigtwatch.conf.js` file (which needs to be JS not TS for reasons I don't understand - but at least that makes the pathspec easy to wildcard) needs to relax that constraint.

So, the directories look like
```
- nightwatch/
    - nightwatch.conf.json
    - .eslintrc.json
    - tsconfig.e2e.json
    - globals/
        - globals.ts
    - page_objects/
        - a-page.ts
    - tests/
        - page.spec.ts
- angular.json
- .eslintrc.json
- tsconfig.json
- package.json
- node_modules/...
- src/
    - app/
        - app.component.ts
    - index.html
```
... where `nightwatch/.eslintrc.json` extends the root `.eslintrc.json`.

And I have a workspace open to the root of this project. To get the Typescript ESLint plugin parser working, I have `overrides[0].parserOptions.project` set to `["tsconfig.e2e.json"]`. Running ESLint manually from within the `nightwatch/` directory picks up all the proper rules and lints appropriately. Running ESLint manually from the project root properly uses the nightwatch config for that directory and the root config for everything else. The ESLint VSCod(e/ium) plugin, however, fails to lint any files under `nightwatch/` because
```
Parsing error: Cannot read file '/path/to/project/root/tsconfig.e2e.json'.
```
(also fwiw `ng lint` works exactly correctly as well).

That's because - I assume - the plugin is trying to run ESLint from the project root but specifying the configuration file as the one in the directory it's trying to lint. As a manual ESLint command, it would look like `npx eslint -c ./nightwatch/.eslintrc.json ./nightwatch `. That command fails with the same messages that the plugin gives me.

Instead, ESLint should allow me to configure it to use the directory containing the `.eslintrc.json` file it's using as the working directory.

Interestingly, in both "location" and "auto" modes, if I change the `nightwatch/.eslintrc.json`'s `overrides[0].parserOptions.project` to `["nightwatch/tsconfig.e2e.json"]`, first of all it starts to successfully lint files under `nightwatch/` - but then if I change that property _back_ to just `["tsconfig.e2e.json"]` it'll keep successfully linting those files. I have no idea why it can "fix" itself like this and only after I manually intervene.

**Comment by dbaeumer** [comment]
> Instead, ESLint should allow me to configure it to use the directory containing the .eslintrc.json file it's using as the working directory.

I am not sure if this will be possible since the working directory is the starting directory from which eslint (the npm module) will search for the `.eslintrc.json` file. Without that starting directory it will very likely not work at all.
