### ISSUE TITLE
a error in the package.json

### ISSUE THREAD

**Issue by czmecho** [Microsoft/vscode-eslint#145]
![](http://ww1.sinaimg.cn/large/7df5111fgw1f879la5vz3j20ct0by0ty.jpg)
![](http://ww4.sinaimg.cn/large/7df5111fgw1f879laadn8j20iz09edgx.jpg)

**Comment by unional** [comment]
The same issue observed "Parsing error: Unexpected token :"
It happens on some project but not others. Don't know what is the cause yet.

**Comment by dbaeumer** [comment]
This was a problem when all files got validated. I addressed it with 1.0.7.
