### ISSUE TITLE
Possible Bug: eslint installation from parent folder prioritized over eslint.nodePath

### ISSUE THREAD

**Issue by thomasobrien99** [microsoft/vscode-eslint#1451]
Hello, thanks for this great extension. Curious about what I suspect may be a bug, but could also just be a misunderstanding:

Our project is setup with a traditional yarn project at the root of the repo, and one using `pnp` as a child, eg something like:
```
repo-root/
  node_modules/
    eslint/
  project_a/
  project_b/
  ...
  project-using-pnp/
    .yarn/
      sdks/
      cache/
        eslint/
```

(The reason for this is that we'd like to incrementally adopt PnP if possible, while leaving the existing projects more or less alone)

I'm trying to get vscode-eslint working in the `project-using-pnp`, and have the `.vscode/settings.json` file:
```
{
  "eslint.nodePath": ".yarn/sdks",
  "eslint.packageManager": "yarn",
  "eslint.trace.server": "messages",
  "eslint.validate": [
    "vue",
    "html",
    "javascript",
    "typescript",
    "javascriptreact",
    "typescriptreact"
  ],
  "search.exclude": {
    "**/.yarn": true,
    "**/.pnp.*": true
  },
  "typescript.enablePromptUseWorkspaceTsdk": true,
  "typescript.tsdk": ".yarn/sdks/typescript/lib"
}
```

But when the server starts I get the message(s):

```
...
[Trace - 2:48:00 PM] NODE_PATH value is: /Users/computer5709/Desktop/repo-root/project-using-pnp/.yarn/sdks
[Trace - 2:48:00 PM] Received notification 'window/logMessage'.
[Info  - 2:48:00 PM] ESLint library loaded from: /Users/computer5709/Desktop/repo-root/node_modules/eslint/lib/api.js
[Trace - 2:48:01 PM] Received notification 'textDocument/publishDiagnostics'.
...
```

My expectation is that since the `NODE_PATH` refers to the sub-project installation of eslint, that's where the ESlint Library should be loaded from, not the parent folder node_modules.

This results in `eslint`/`vscode-eslint` not being able to resolve the plugins in the sub-project. (as well as just running the wrong copy of eslint)

_However_, if I delete the `node_modules` folder from the `repo_root`, and re-open VSCode, the extension works fine, which makes me think that the configuration (as far as the .vscode/settings.json) is set up correctly, it's just that `vscode-eslint` is finding the parent `node_modules/eslint` installation and using that if it can, rather than the one specified by `nodePath`

It might also be that this is expected behavior. I notice in the docs where `nodePath` is mentioned, it's used 'if an installed ESLint package can't be detected', and so if this _is_ intended behavior, I'm not really sure how to get around it other than to make eslint a dependency of all the subprojects individually (which is not desirable).

Any insights anyone can share would be appreciated, and happy to provide more information if I can!

Possibly related: https://github.com/microsoft/vscode-eslint/issues/156

**Comment by dbaeumer** [comment]
This is how node works. The NODE_PATH is used to find globally installed node modules. Node in general always starts from the file already running and searches from that point up the directory chain by looking for a node_modules folder. Only if this fails the NODE_PATH is considered. So, what you see is correct.

**Comment by thomasobrien99** [comment]
Thanks for the response @dbaeumer. I feel like this _could_ still be prioritized over node's own default resolution? Although I guess that's not the intention.

So my understanding from this is that it's not possible for this extension to use the eslint version in the sub-project (unless it's in an actual node_modules folder) if there is an installation of eslint in a node_modules folder somewhere up the file tree.

**Comment by dbaeumer** [comment]
> So my understanding from this is that it's not possible for this extension to use the eslint version in the sub-project (unless it's in an actual node_modules folder) if there is an installation of eslint in a node_modules folder somewhere up the file tree.

That is correct. That is how NodeJS works.
