### ISSUE TITLE
.eslintignore not working in a multi-root workspaces

### ISSUE THREAD

**Issue by WangLeto** [microsoft/vscode-eslint#1452]
I use root folder as a workspace, with eslint config file under it, and the subfolder `packages` as another workspace. Then I found that eslintignore fails to work in subfolder workspace when I open project as mutli-root workspaces.

The problem is ever mentioned in issue #428. 
There is a [demo project](https://github.com/WangLeto/eslint-multi-root-workspaces) that reproduces it.

This is how I write my workspace file:
```json
{
  "folders": [
    {
      "path": "."
    },
    {
      "path": "packages/"
    }
  ],
  "settings": {
    "files.exclude": {
      "packages": true,
    },
    "eslint.workingDirectories": [
      ".",
      "packages/"
    ]
  }
}

```

And how my projects looks like:
```
├── eslint-test.code-workspace
├── index.js
├── node_modules
├── package.json
├── packages
│   └── demo
│       ├── package.json
│       └── src
├── pnpm-lock.yaml
└── pnpm-workspace.yaml
```

**Comment by dbaeumer** [comment]
ESLint (the npm package) only honors the ignore file in the current working directory. It doesn't look up the parent chain like it does for the .eslintrc file

```
/workspaces/eslint-multi-root-workspaces/packages (master ✗) $ ../node_modules/.bin/eslint --ext js .

/workspaces/eslint-multi-root-workspaces/packages/demo/src/index.js
  1:1  error  This line has a length of 27. Maximum allowed is 25  max-len

✖ 1 problem (1 error, 0 warnings)
```

This is how ESLint works.

**Comment by WangLeto** [comment]
Thank you for reply, currently I added `.vscode/settings.json` setting workingDirectories to the subfolder as a workaround, like #428 did.
