### ISSUE TITLE
eslint Server sendDiagnostics

### ISSUE THREAD

**Issue by spf-oss** [microsoft/vscode-eslint#1461]
Whether the frequency of eslint diagnosis sending is too frequent and will be sent all the time during continuous input. Should it be controlled?

**Comment by dbaeumer** [comment]
You can partly control it by switch to validate on save. There is some debounce logic on the client to wait some time before requesting diagnostics. Currently there are no plans to add additional control over this.

**Comment by spf-oss** [comment]
Is it better to do this, because continuous notification will cause performance loss.

[code](https://github.com/vuejs/vetur/blob/84dbc419938f60c5bd6e168d98cf076b1d5e001e/server/src/services/vls.ts#L660)

**Comment by dbaeumer** [comment]
I do this already since all requests on the server are buffer and only executed if the document didn't change. So validations will be dropped on frequent editing.
