### ISSUE TITLE
Eslint extension can't detect PNPM new global store location

### ISSUE THREAD

**Issue by harisraharjo** [microsoft/vscode-eslint#1462]
After I update my pnpm to version 7.0.0, eslint extension could not work and giving me this `Uncaught exception received.
Error: Command failed: pnpm root -g at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.get (.....)`. Probably it's because pnpm changes it's global store [location](https://github.com/pnpm/pnpm/releases/tag/v7.0.0)

**Comment by dbaeumer** [comment]
@harisraharjo 

can you run `pnpm root -g` in a command prompt and let me know the outcome.

**Comment by harisraharjo** [comment]
I did that yesterday and if I remembered correctly it tells me to run `pnpm setup`. Right now if I run `pnpm root -g` it gives me the _new_ pnpm store location but the extension still doesn't work

**Comment by doubleplusc** [comment]
I've encountered the same issue on Linux.
```
Error: Command failed: pnpm root -g
/bin/sh: line 1: pnpm: command not found
    at checkExecSyncError (node:child_process:835:11)
    at execSync (node:child_process:909:15)
    at node:electron/js2c/asar_bundle:5:12692
    ...
```
Running `pnpm root -g` in the command prompt gives me
/home/doubleplusc/.local/share/pnpm/global/5/node_modules

I set eslint.nodeEnv to the string above but the error persists.

Seems like the plugin does not have access to the pnpm command. In the VSCode terminal and a standalone terminal, I can run pnpm just fine.

**Comment by dbaeumer** [comment]
How do you install `pnpm` ?

**Comment by harisraharjo** [comment]
Via corepack

**Comment by harisraharjo** [comment]
Strangely, it works after I shut down my laptop. For people who encountered this issue, try to _shut_ _down_ your machine. I will close this issue for now
