### ISSUE TITLE
Rule object not being cleared between lint checks

### ISSUE THREAD

**Issue by NedWilbur** [microsoft/vscode-eslint#1469]
I have custom ESLint rules, which I configure in the `.settings.json` via `"eslint.options": { "rulePaths": ["packages/tools/src/eslint-rules"] }`. These rules work as expected when manually running ESLint. 

One of these rules (below) is checking for a unique value. Each time it comes across the value, it stores it in an object. If the value already exist within this object, it throws a lint error.

custom rule:
```js
//------------------------------------------------------------------------------
// Rule Definition
//------------------------------------------------------------------------------
const foundKeys = Object.create(null);

/**
 * @type {import('eslint').Rule.RuleModule}
 */
module.exports = {
  meta: {
    type: 'problem', // `problem`, `suggestion`, or `layout`
    docs: {
      description: 'Validate all e2e-test have a single JIRAKEY meta tag',
      category: 'Possible Errors',
      recommended: false,
    },
    fixable: null, // Or `code` or `whitespace`
    schema: [], // Add a schema if the rule has options
    messages: {
      duplicate: "Non-unique JIRAKEY meta tag '{{ jirakey }}'",
    },
  },

  create(context) {
    let key;

    //----------------------------------------------------------------------
    // Public
    //----------------------------------------------------------------------
    return {
      Identifier: function (node) {
        // Get nodes with JIRAKEY
        const jiraKeys = context
          .getAncestors()
          .filter(n => n.type === 'CallExpression')
          .filter(n => n.arguments[0].value === 'JIRAKEY');

        key = jiraKeys[0].arguments[1].value;

        // Check if duplicate
        if (foundKeys[key]) {
          context.report({ node, messageId: 'duplicate', data: { jirakey: key } });
        } else {
          foundKeys[key] = key;
        }
      },
    };
  },
};
```

However, when `vscode-eslint` is linting a file I am working in, each time I type the value that should be unique, it is adding the value to the `foundKeys` object. As I continue typing, `foundKeys` is never cleared, and therefore it finds it as a duplicate despite it not. The below example is 100% a unique value, but since it scanned the file more than once, it now thinks it is a duplicate.

![image](https://user-images.githubusercontent.com/19377058/168141302-7e0a25c0-39ea-49e3-a7c7-67a25b1736ad.png)

Any advice on how to avoid this? Is there any way to clear an object such as `foundKeys` each time `vscode-eslint` runs on the file? Any examples of checking for unique values within a file with `vscode-eslint`? 

Note, the same behavior occurs when `const foundKeys = Object.create(null);` is within the `create` function.

Thank you in advance!

**Comment by dbaeumer** [comment]
You need to scope the `foundKeys` value to something reasonable (e.g. file, node location)...

The problem is that the eslint extension to support validating on type keeps the ESLint parser alive and reuses it. Other I would need to spawn a new process while typing which doesn't scale at all.

The reason why it is working in ESLint is that it does spawn a new process on every time you run it in the terminal.

Does this help?

**Comment by NedWilbur** [comment]
@dbaeumer Yes this confirms what I suspected, but not really sure how to create a rule like this that works with a persistent parser. I could make the rule scoped to only the file/node, but then the rule does not work properly when run across multiple files (these values need to be unique across the entire repo).

Is there anyway to have the extension simply not use this specific rule? If I move this specific rule to another folder and not include it in the `eslint.options": { "rulePaths": ...`, I will get an error at 1:1 stating the rule cannot be found since it is still defined in the `package.json`.

Or alternatively, is there a way to somehow detect from the rule that it is the extension running the rule versus when running it manually/directly?

**Comment by rchl** [comment]
There is hundreds or thousands of rules across various eslint plugins and I've never noticed this problem with any rules that I'm using. Are you sure that you are using the eslint API correctly in your rule? Maybe ask in eslint developer forum or something for a possible solution?

**Comment by dbaeumer** [comment]
You can control which rules the extension uses. See https://insiders.vscode.dev/github/microsoft/vscode-eslint/blob/aa5170003e195ca25c4f19c275b29a641ea7b23c/README.md#L232
