### ISSUE TITLE
ESLint extension refreshes in seconds

### ISSUE THREAD

**Issue by danim47c** [microsoft/vscode-eslint#1470]
![CleanShot 2022-05-21 at 09 29 43](https://user-images.githubusercontent.com/48626234/169641081-cab8be20-52e4-43a8-b719-639828a8103d.gif)

**Comment by danim47c** [comment]
> @danim47c can you please explain what the screen cast is showing. It has a very low resolution, and I am not able to read anything.

Yes, sorry for that. Here I've recorded a video so you can see properly whats going on.

https://user-images.githubusercontent.com/48626234/169839824-fbad7f82-395a-42c3-8ac1-917c5115d23b.mp4

**Comment by dbaeumer** [comment]
That looks indeep wired. Can you provide me with a GitHub repository that demos that.

**Comment by danim47c** [comment]
Thanks for your help but magically it fixed. I don't realized what it have changed, I hope I don't face this problem again.
