### ISSUE TITLE
packageManager set to pnpm will not work

### ISSUE THREAD

**Issue by Dunqing** [microsoft/vscode-eslint#1474]
I see the following error in eslint output
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/29533304/170914075-f6390b03-fd38-4130-a461-5c43844302cd.png">

After some investigation, I found out why. when my workspace already has `pnpm` installed and typing `pnpm root -g` in terminal will receive `Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.`.

When `pnpm` is not installed in my workspace, it works.

**Comment by dbaeumer** [comment]
See my last comment in https://github.com/microsoft/vscode-eslint/pull/1475.

Closing.
