### ISSUE TITLE
Indentation issue with commented lines

### ISSUE THREAD

**Issue by pasan-pwl** [microsoft/vscode-eslint#1476]
There is an indentation issue with comment lines. To give an clear idea please take look on the following screenshot with descriptions.

In my VS code I have configured to Auto saved with ESLint formatting.

In here I have two commented lines of code. (line 49 and 50) with proper indentation.
![Screenshot 2022-05-30 at 14 49 06](https://user-images.githubusercontent.com/96760254/170960738-31f8f917-79a3-43a7-87ce-8194c5697084.png)

And then when I save the page, starting from line 47 to 57 (the code block which contains the commented code) indentation become like the below screenshot.
![Screenshot 2022-05-30 at 14 53 00](https://user-images.githubusercontent.com/96760254/170961215-201ae26a-3f26-4546-8e7f-eb26af6c4349.png)

Even after the fixing these issue, it continuously happens.

**Comment by dbaeumer** [comment]
@pasan-pwl does the fixing happen correctly when you use eslint in the terminal (e.g. with the --fix option). If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!
