### ISSUE TITLE
Extension doesn't parse TS configuration glob properly

### ISSUE THREAD

**Issue by rafawendel** [microsoft/vscode-eslint#1478]
After exhaustive testing and comparison, I noticed when I use a globstar in my `tsconfig.json` file to match all files, despite my CLI Eslint + `@typescript-eslint/parser` parsing normally such configuration, VSCode ESLint server still will throw an error with the following:

```text
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided.
```

The error goes away when my `tsconfig.eslint.json` explicitly includes the file, e.g.: `".eslintrc.js"`. Again, the CLI does not throw it with the globstar, but it does throw if I remove it.

My `tsconfig.eslint.json`:
```json
{
  "compilerOptions": {
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "target": "es5",
    "jsx": "react-jsx",
    "allowJs": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strict": true,
    "strictNullChecks": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
  },
  "include": ["src", ".storybook/**/*.js", "*.js"]
}
```

My `.eslintrc.js` (simplified):
```js
module.exports = {
  env: {
    browser: true,
    es2021: true,
    jest: true,
  },
  extends: ['plugin:react/recommended', 'airbnb', 'airbnb-typescript'],
  plugins: ['react', 'import'],
  rules: {},
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    project: './tsconfig.eslint.json',
    ecmaVersion: 13,
    sourceType: 'module',
  },
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
        project: './tsconfig.eslint.json',
      },
    },
  },
};
```

**Comment by dbaeumer** [comment]
When you validate in the terminal do you do a `chdir` into a special directory. If so you need to let the extension know about these working directories using the `eslint.workingDirectories` setting.

If you don't can you please provider me with a GitHub repository I can clone that demos the behavior.

**Comment by dbaeumer** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!
