### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rejakazi02** [microsoft/vscode-eslint#1480]
- Issue Type: `Bug`
- Extension Name: `vscode-eslint`
- Extension Version: `2.2.2`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by dbaeumer** [comment]
@rejakazi02 do you still have the data. Without it hard to act on.

**Comment by dbaeumer** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!
