### ISSUE TITLE
Formatting on save with ESLint extension is adding extra backslash characters

### ISSUE THREAD

**Issue by jgoux** [microsoft/vscode-eslint#1482]
Hello,

I'm not sure if the issue is from the extension or VSCode itself, but in doubt, I also link to the issue here.

I explained everything with a repro: https://github.com/microsoft/vscode/issues/152395

The version of the extension I used  are:
- v2.2.2
- v2.2.3

**Comment by dbaeumer** [comment]
I commented on the vscode issue. Let's continue the discussion there.
