### ISSUE TITLE
Disable auto fix

### ISSUE THREAD

**Issue by TheDirigible** [microsoft/vscode-eslint#1484]
There seems to be no way to disable auto fixing.  I don't want invisible code changes happening, and the default should be OFF, as it is in regular eslint.
From the eslint docs:
  options.fixTypes (("directive" | "problem" | "suggestion" | "layout")[] | null)
  Default is null. 
From your docs:
  [none. you have no docs]
But it seems you only support "all" and "problem".

**Comment by dbaeumer** [comment]
Autofix is off by default but integrated into the VS Code settings. Do you have any of the VS Code settings enabled like `editor.codeActionsOnSave` or format on save. If not, can't you please provide me with a GitHub repository I can clone that demos what you are seeing.

**Comment by TheDirigible** [comment]
If it's off by default, maybe the problem is that the settings page is confusing?

It says:
Eslint › Code Actions On Save: Mode
and the only options are "all" and "problems"

I see no settings to enable or disable autofix.  Searching for "autofix" in settings finds nothing.
There is this one:
Eslint › Format: Enable
I'm afraid to enable that since maybe that means auto fixing?  Better descriptions would really be helpful.

Just the act of creating a "getting started" page is a good practice for seeing things from a user's eyes.

**Comment by dbaeumer** [comment]
The setting is either `editor.codeActionsOnSave` `eslint.autoFixOnSave`. See also: https://github.com/microsoft/vscode-eslint#version-204

**Comment by TheDirigible** [comment]
Great thanks.

**Comment by dbaeumer** [comment]
Closing the issue. Please ping if you thing there is still something to do.
