### ISSUE TITLE
Incorrect `process.execPath` in VSCode-ESLint

### ISSUE THREAD

**Issue by B2o5T** [microsoft/vscode-eslint#1485]
Related https://github.com/B2o5T/graphql-eslint/issues/1091

I use some package [sync-fetch](https://github.com/larsgw/sync-fetch/blob/aa8d8d018c4da0b6dc7a768d693e13b3217617e4/index.js#L41) that has `process.execPath` statement.
Via terminal everything works fine, `process.execPath` equals `/Users/dimitri/.nvm/versions/node/v16.14.2/bin/node`.
BUT something strange happens while execution via VSCode-ESLint as `process.execPath` equals `/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper`.

VSCode-ESLint v2.2.2

**Comment by dbaeumer** [comment]
By default the ESLint extension uses the node version that ships with VS Code. If you want to use another node version you can use the `eslint.runtime` setting to control it
