### ISSUE TITLE
some eslint error occur when I use remote ssh extension， Parsing error: "parserOptions.project"

### ISSUE THREAD

**Issue by linzhefeng** [microsoft/vscode-eslint#1487]
I found the totally same issue [#1075](https://github.com/microsoft/vscode-eslint/issues/1075#issue-706249970)，but it seems was not solved

**Comment by linzhefeng** [comment]
give a ssh extension absolute path, it works for me

**Comment by xiaxzp** [comment]
> give a ssh extension absolute path

Facing the same error, how was it fixed exactly?

**Comment by xiaxzp** [comment]
found that caused by typescrpt resolver resolving different paths and fixed by using { "project": [absolute path] } in related ts parser config.

**Comment by xitice** [comment]
@linzhefeng  hello！ I meet the same problem, can you tell me the detailed solution about "give a ssh extension absolute path"？
