### ISSUE TITLE
"Failed to load plugin" message pops up on every keypress

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-eslint#149]
Testing https://github.com/Microsoft/vscode/issues/12602

In my eslintrc.json, I have 

``` javascript
    "plugins": [
        "nonexistent-plugin"
    ],
```

There is no relevant output in the eslint Output stream

![sep-27-2016 13-57-59](https://cloud.githubusercontent.com/assets/323878/18891520/6fa58eda-84ba-11e6-94c4-ad52f07ec5e2.gif)

**Comment by dbaeumer** [comment]
Fixed with 1.1.0
