### ISSUE TITLE
Resolve plugins in monorepo project

### ISSUE THREAD

**Issue by suhith42** [microsoft/vscode-eslint#1496]
I have the following folder structure

```
/.vscode
.../setting.json
/linter
.../node_modules <== contains eslint and plugins
.../package.json
/project-a
.../eslintrc.json
/project-b
.../eslintrc.json
```

setting.json
```
{   
        "eslint.nodePath": "./ci/js/eslint/node_modules" 
 }
```

project-a .eslintrc.json
```
{
 "extends": [
        "plugin:vue/recommended",
        "../lint/node_modules/eslint-config-standard/.eslintrc.json"
    ],
}
```
Eslint output

> [Info  - 11:46:43 PM] ESLint server is starting
> [Info  - 11:46:43 PM] ESLint server running in node v16.13.0
> [Info  - 11:46:43 PM] ESLint server is running.
> [Info  - 11:46:45 PM] ESLint library loaded from: /home/User/main-project/lint/node_modules/eslint/lib/api.js
> [Info  - 11:46:45 PM]  Failed to load plugin 'vue' declared in 'project-a/.eslintrc.json': Cannot find module 'eslint-plugin-vue' Require stack: - /home/User/main-project/project-a/__placeholder__.js Referenced from: /home/User/main-project/project-a/.eslintrc.json

Eslint works fine from CLI when used with `--resolve-plugins-relative-to`, but I cannot find a similar functionality to resolve plugin paths in the vscode extensions

**Comment by dbaeumer** [comment]
@suhith42 have a look to `eslint.workingDirectories` setting. To find out how to best use the setting try running eslint from a terminal. If you need to `cd` into a directory to make it work correctly in the terminal then that directory is a good candidate for a working directory for this extension.

I will close the issue. Please ping if it doesn't help.

**Comment by suhith42** [comment]
Thanks for your response @dbaeumer!
I added the eslint containing directory to `eslint.workingDirectories`, 
```
{
    "eslint.nodePath": "./linter/node_modules",
    "eslint.workingDirectories":[
        {
            "directory":"./linter",
            "changeProcessCWD": true
        }
    ]
}
```
but still getting the same error.
I reproduced the error in this repo https://github.com/suhith42/eslint-reproduce. It would be great if you could have a look please.

**Comment by suhith42** [comment]
@dbaeumer  package.json and eslintrc files are inside the relevant directories.
package.json with Eslint is present inside `linter` directory and eslintrc files are in `project-a` and `project-b` are inside those directories respectively.

**Comment by dbaeumer** [comment]
The correct setup for this layout is:

```
{
    "eslint.nodePath": "./linter",
    "eslint.workingDirectories":[
        "./project-a",
        "./project-b"
    ]
}
```

However linting in the terminal fails as well (with the same error as it does in VS Code). It results in:

```
project-a (master ✗) $ ../linter/node_modules/.bin/eslint index.js

Oops! Something went wrong! :(

ESLint: 8.19.0

ESLint couldn't find the plugin "eslint-plugin-import".

(The package "eslint-plugin-import" was not found when loaded as a Node module from the directory "/workspaces/eslint-reproduce/project-a".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-import@latest --save-dev

The plugin "eslint-plugin-import" was referenced from the config file in ".eslintrc » ../linter/node_modules/eslint-config-standard/.eslintrc.json".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

I recommend that you try to get linting working in the terminal. If it does things are mostly OK in the extension then as well.

I will close the issue. Please ping if you still think this is an issue with the extension.

**Comment by suhith42** [comment]
Linting works fine in terminal. You just have to run eslint from linter directory.
```
cd linter
yarn lint-project-a
```
Output
![image](https://user-images.githubusercontent.com/61136112/177463253-c25e8856-004b-4740-9abe-f1822fd65e1a.png)

**Comment by dbaeumer** [comment]
I would actually not recommend such a setup since eslint resolves some of its configuration files (e.g. ignore files) relative to the working directory and not the location where the file to be linted is. What You can do is using the following setup:

```
{
    "eslint.nodePath": "./linter",
    "eslint.workingDirectories":[
        "./project-a",
        "./project-b"
    ],
    "eslint.options": {
        "resolvePluginsRelativeTo": "../linter/node_modules"
    }
}
```

That at least makes sure you start in the correct working directory. But limits the working directories to be siblings of the linter folder.

**Comment by suhith42** [comment]
That works! Thanks a lot for your time
