### ISSUE TITLE
Some custom options being ignored 

### ISSUE THREAD

**Issue by ricmed205** [Microsoft/vscode-eslint#15]
In my settings.json I have: 

"eslint.options": {
    "envs": ["es6", "node"],
    "indent": [2, 2],
    "curly": [2, "multi"]
  }

The envs option is considered but not the rest. 
If I place a comment within the file like 

/* eslint indent: [2, 2] */

the option does get considered in the file.

EDIT: Nevermind. Found out in eslint docs that rules must me placed inside a property "rules".

**Comment by egamma** [comment]
Closing per latest comment from @ricmed205
