### ISSUE TITLE
eslintrc.json errors should be marked as errors in Output channel, not warnings

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-eslint#150]
![image](https://cloud.githubusercontent.com/assets/323878/18891666/24f6e7a2-84bb-11e6-8976-f97d1b1759d9.png)

Since these things prevent linting from happening at all, seems like they should be marked as errors, not warnings.

**Comment by dbaeumer** [comment]
This requires work in the language server side first to avoid that the output window steels focus.

**Comment by dbaeumer** [comment]
Fixed with 1.1.0
