### ISSUE TITLE
Add autocomplete for more methods and more smarter the autocomplete

### ISSUE THREAD

**Issue by COD3BREAK3R** [microsoft/vscode-eslint#1500]
The extension is very poor for autcomplete, beacuse not know how to autcomplete in too many cases, like: example.getElemen (expecting: getElementById(); or another), example.redu (expecting: reduce(); ), etc

**Comment by dbaeumer** [comment]
This extension is for linting source code. It doesn't provide any auto complete functionality. Please report your issue to the corresponding language extension.

**Comment by COD3BREAK3R** [comment]
> This extension is for linting source code. It doesn't provide any auto complete functionality. Please report your issue to the corresponding language extension.

ok I understand but I didn't find any extension that explicitly says: autocomplete for javascript, if you can what extension does it I will appreciate it.

**Comment by dbaeumer** [comment]
VS Code should do auto complete in JS files out of the box. If you have issues please report them in the VS Code repository.
