### ISSUE TITLE
120GB Memory is used when using `worker_threads` in plugin 😭

### ISSUE THREAD

**Issue by JounQin** [microsoft/vscode-eslint#1503]
![image](https://user-images.githubusercontent.com/8336744/180011718-69445336-c9b7-4534-978f-b1e3d8052625.png)

I just got crazy about this

Reproduction: https://github.com/un-ts/yocto-ttl-cache

Open any `.ts` or `.json`, `.md` file (make sure `eslint.validate` and `eslint.options#extensions` configured first).

The memory and threads are just growing up in `Activity Monitor.app`

https://github.com/un-ts/synckit is used by many ESLint plugins, and it just runs well with ESLint cli.

**Comment by EdisonSu768** [comment]
<img width="871" alt="企业微信截图_24f02306-3d5a-4ad8-878c-802736f4a7b1" src="https://user-images.githubusercontent.com/11643492/180022971-d1834f9a-e8ee-485c-9e49-b9a15738d2dc.png">
I also got this. But after eslint server got EAGAIN error, the memory of vscode looks good.I wish the screenshot can make some help to debug.

**Comment by JounQin** [comment]
Thanks @EdisonSu768 for debugging and fixing this at https://github.com/mdx-js/eslint-mdx/pull/412!
