### ISSUE TITLE
Bug: Disabling rule with VSCode context menu broken when there is description

### ISSUE THREAD

**Issue by ilyub** [microsoft/vscode-eslint#1505]
Reproduction:

1.
Disable some rule in VSCode:
![image](https://user-images.githubusercontent.com/70687432/180875163-e0696b8f-5df7-471a-91c1-0e4603653a94.png)
```ts
// eslint-disable-next-line rule1
```

2.
Add comment
```ts
// eslint-disable-next-line rule1 -- This rule is disabled because ...
```

3.
Disable another rule:
```ts
// eslint-disable-next-line rule1 -- This rule is disabled because ..., rule2
```

**Comment by MariaSolOs** [comment]
I think that we can close this issue now...?

**Comment by dbaeumer** [comment]
Correct. Thanks for pointing out.
