### ISSUE TITLE
Color Parenthesis and Brackets

### ISSUE THREAD

**Issue by RoyKM** [microsoft/vscode-eslint#1507]
Hi, I didn't see an area to send suggestions to the developer, so I'm posting it here.  I've had an error several times where I am missing a parenthesis or bracket.  If you had an option to color parenthesis ( ) and brackets { } so that nested sets were a different color, and perhaps highlight when one is missing, that'd help a LOT.

**Comment by MariaSolOs** [comment]
That doesn't sound like something that ESLint can do. However, I use (and love) [this extension](https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets) that provides exactly that functionality.

**Comment by RoyKM** [comment]
Thank you!

[signature_288837778]


Roy Mathur
Technology Solutions
Cell: 703-297-0424
Hours: Mon-Fri 7am-3:30pm
Email: ***@***.******@***.***>
Team Email: ***@***.******@***.***>




Sensitivity: General/Internal

**Comment by dbaeumer** [comment]
@MariaSolOs thanks for jumping in.

Bracket pair colorization is now available out of the box in VS Code.
