### ISSUE TITLE
To set eslint.nodePath is invalid  in Remote - WSL

### ISSUE THREAD

**Issue by Jackllllll** [microsoft/vscode-eslint#1508]
In window, this is valid, but this config is invalid   in Remote - WSL eslint plugin ! why ?

**Comment by dbaeumer** [comment]
This works for me. Please note that the `eslint.nodePath` must either be set as a workspace setting or as a WSL setting. The Windows user setting will not be honored.

<img width="451" alt="capture" src="https://user-images.githubusercontent.com/1931590/182857375-6f2fdf9e-6db6-4b2d-a87c-b4a6090190f5.png">

**Comment by Jackllllll** [comment]
Got it. Thanks!
