### ISSUE TITLE
Standalone linting

### ISSUE THREAD

**Issue by erosman** [microsoft/vscode-eslint#1509]
I am new to VS Code. HTMLHint extension shows hints live without a need to run a separate process.

I have used ESLint in browser environment (Web or browser extension) and both show hints live.

I installed ESLint extension and it seems that it requires `nmp`, `node.js` & running a separate process to check the syntax.

Doesn't ESLint run automatically like HTMLHint or Spell checker extensions?
How can syntax errors and/or suggestions be shown in VS Code?

**Comment by dbaeumer** [comment]
Setup ESLint for the project (https://eslint.org/) and then install the extension. If you then open a JS, ... file linting should happen automatically.

**Comment by dbaeumer** [comment]
Yes, it requires at least `npm`. node.js is required if you use it in the terminal but not with the extension since VS Code ships with a node runtime.

**Comment by erosman** [comment]
Thank you. I run a test and it seems it requires a config file for the project in the project folder and for each file.
My set-up (webextension development) is different and I avoid additional files in the directory.

Can it have a general standard confg file for all the projects/extensions, instead of per-document config?

**Comment by dbaeumer** [comment]
It does not. For setup details for ESLint please see https://eslint.org/
