### ISSUE TITLE
Add a link to ES Lint rule page. 

### ISSUE THREAD

**Issue by waderyan** [microsoft/vscode-eslint#151]
![image](https://cloud.githubusercontent.com/assets/2449568/18892422/4bb3768c-84be-11e6-9fd4-74037e60ae0f.png)

**Comment by darkred** [comment]
Related/duplicate: https://github.com/Microsoft/vscode/issues/11847

**Comment by thibaudcolas** [comment]
I gave this a shot at https://github.com/Microsoft/vscode-eslint/pull/562, along with the VS Code PR https://github.com/Microsoft/vscode/pull/61436, and for `vscode-languageserver` at https://github.com/Microsoft/vscode-languageserver-node/pull/432.

Feedback welcome! See https://github.com/Microsoft/vscode/issues/11847#issuecomment-431680393 for further details.

**Comment by dbaeumer** [comment]
Ships since quite some time.
