### ISSUE TITLE
Change Request: Suggestion to update disable message from UX POV

### ISSUE THREAD

**Issue by krunalbad** [microsoft/vscode-eslint#1513]
### ESLint version

v7.5.0

### What problem do you want to solve?

I have a suggestion to update the disable camelCase message

### What do you think is the correct solution?

while disabling camelcase eslint gives the below message
`// eslint-disable-next-line camelcase`
but it should `// eslint-disable-next-line camelCase`

See below image from VSCode:
![Screenshot 2022-08-19 at 5 54 55 PM](https://user-images.githubusercontent.com/45413622/185617749-d45cd2f7-057b-4d83-9b14-e54c7974a67e.png)

**Comment by dbaeumer** [comment]
@krunalbad this is the rule ID from the ESLint npm module (https://eslint.org/docs/latest/rules/camelcase). 

I saw that you opened a issue against ESLint and it is the right location for this sort of feature request.
