### ISSUE TITLE
eslint works with workingDirectories `mode: auto` but not with specifying path

### ISSUE THREAD

**Issue by kara-todd** [microsoft/vscode-eslint#1516]
When using VSCode at the project root level, I get the below error and cannot use tailwind intellisense or other auto complete functions. However, if I open VSCode in the sub directory `./react-client` **both** intellisense works and the error goes away. If I change the `workingDirectories` setting from `["./react-client"]` to `[{ mode": "auto" }]` the error goes away, but my intellisense still does not work.

Other things I've tried: 
- reinstalling the eslint and tailwind CSS intellisense packages
- restarting VSCode
- changing the "!cwd" value
- uninstall and reinstalling `node_modules`

```
Parsing error: Cannot find module 'next/babel'
Require stack:
- app/react-client/node_modules/next/dist/compiled/babel/bundle.js
- app/react-client/node_modules/next/dist/compiled/babel/eslint-parser.js
- app/react-client/node_modules/eslint-config-next/parser.js
- app/react-client/node_modules/@eslint/eslintrc/dist/eslintrc.cjseslint
```

#### `.vscode/settings.json` with error

```JSON
{
  "eslint.workingDirectories": ["./react-client"],
}
```

#### `.vscode/settings.json` with no error, but no intellisense

```JSON
{
  "eslint.workingDirectories": [{ "mode": "auto" }],
}
```

#### Directory structure:

```
| .vscode
| -- settings.json
| react-client
| -- .eslintrc.json
| -- .prettierrc.json
| -- jsconfig.json
| -- package.json
```

#### .eslintrc.json
```
{
  "root": true,
  "extends": ["eslint:recommended", "next/core-web-vitals", "prettier"],
  "env": {
    "es2020": true
  },
  "settings": {
    "import/resolver": {
      "node": {
        "moduleDirectory": ["node_modules", "."]
      }
    }
  },
  "parserOptions": {
    "project": ["./jsconfig.json"]
  },
  "rules": {
    "no-unused-vars": ["error", { "ignoreRestSiblings": true }],
    "import/no-unused-modules": [
      1,
      {
        "unusedExports": true,
        "missingExports": true
      }
    ]
  },
  "plugins": ["testing-library"],
  "overrides": [
    // Only uses Testing Library lint rules in test files
    {
      "files": [
        "**/__tests__/**/*.[jt]s?(x)",
        "**/?(*.)+(spec|test).[jt]s?(x)"
      ],
      "extends": ["plugin:testing-library/react"]
    },
    {
      "files": ["pages/**/*.js"],
      "rules": {
        "import/no-unused-modules": [
          1,
          {
            "unusedExports": false,
            "missingExports": true
          }
        ]
      }
    }
  ]
}
```

VSCode version:
```
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0
```

`dbaeumer.vscode-eslint v2.2.6`

**Comment by dbaeumer** [comment]
When you talk about intellisense which file types do you mean (e.g. JavaScript, ...) This extension only provides intellisense for eslintrc files. So, a problem about intellisense must be reported to a specific extension.

If you provide me with a GitHub repository, I can clone that demos the problem I can havea look at the specific ESLint problem.

**Comment by kara-todd** [comment]
Thank you for your response... I was starting to create a minimal repo for this... and then today it just started working again. Seemingly without any changes on my end...

I'm going to close this as it must be something local to my machine. If I run into it again and can nail down a more exact repo-case.

 Sorry for the "ghost bug" :)
