### ISSUE TITLE
Configure where eslint configs are

### ISSUE THREAD

**Issue by jrock2004** [microsoft/vscode-eslint#1523]
Is there a way to configure where the eslint configs are located? I npm install my configs and want to configure to point to them

**Comment by MariaSolOs** [comment]
Haven't tried it, but I'm pretty sure you can achieve this by using the [`eslint.options` setting](https://github.com/microsoft/vscode-eslint/blob/4b92c12af15d41f76417bde9571cb56f08ec3d0f/package.json#L92-L96) to specify an [`overrideConfigFile`](https://eslint.org/docs/developer-guide/nodejs-api#eslint-class):
![image](https://user-images.githubusercontent.com/62502207/189251828-3ed26dd1-d04e-49ac-81ef-8237d5abe44d.png)

**Comment by dbaeumer** [comment]
@jrock2004 @MariaSolOs answer is the way to go. Please note that the config value depends on the version of ESLint you are using. The `overrideConfigFile` is only available for verisons >= 8.0. 

@MariaSolOs thanks for providing the answer

I will close the issue. @jrock2004 please ping if this doesn't help.

**Comment by jrock2004** [comment]
Will try this out and let you guys know

**Comment by jrock2004** [comment]
@MariaSolOs question in my package.json I have the following

```
{
  ...
  "eslintConfig": {
    "extends": "@mycompany: my-shareable-config",
  }
  ...
}
```

So should the value for `overrideConfigFile` be `./package.json` or do I need to point it to node modules folder where the config is npm installed?

@dbaeumer if we are not on 8.0, does that mean there is no way to configure it?

**Comment by MariaSolOs** [comment]
@jrock2004 okay I think you're talking about 2 different things here.

You should use `overrideConfigFile` if you want ESLint to use a file that it wouldn't automatically discover with its [cascading files mechanism](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#cascading-and-hierarchy). Depending on the complexity of the problem, you can also use a file path in the `extends` property of your `.eslintrc` (e.g.: `"extends": "../folder-with-eslint-stuff/.eslintrc.json"`.  

From your last comment it seems like this isn't your case. What you have instead looks like a [shareable configuration package](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#using-a-shareable-configuration-package). If such package was created following the [ESLint docs](https://eslint.org/docs/latest/developer-guide/shareable-configs), you wouldn't need to use `overrideConfigFile` and instead you can just have:
```
{
  ...
  "eslintConfig": {
    "extends": "my-config" // This is assuming that the package's name is @mycompany: eslint-config-my-config
    // From the docs: "Make sure the module name begins with eslint-config-, such as eslint-config-myconfig."
  }
  ...
}
```

**Comment by jrock2004** [comment]
@MariaSolOs So it does not. But maybe that because we are on version 7.x ?

**Comment by MariaSolOs** [comment]
> @MariaSolOs Maria Solano FTE So it does not. But maybe that because we are on version 7.x ?

It does not what? 

Shareable configs have been supported by ESLint for a very long time (definitely in version 7.x). Did you make sure that it follows all of the ESLint specs for it?

**Comment by dbaeumer** [comment]
@jrock2004 no, even in older version of eslint you can configure this. However the property name to use changed. It 8 >= it is `overrideConfigFile`. I an older version this name is different (if I remmember correctly it was `configFile`)
