### ISSUE TITLE
NODE_PATH not being set for Workspaces

### ISSUE THREAD

**Issue by Jomik** [microsoft/vscode-eslint#1524]
I keep getting this error in my yarn berry workspaces repo.
```
[Trace - 3:42:13 PM] NODE_PATH value is: /Users/.../.local/share/nvm/v16.14.2/lib/node_modules
Uncaught exception received.
Error: spawn /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```
`eslint.nodePath` has been set both in the [.vscode/settings.json](
https://github.com/Jomik/screeps-ai/blob/e91bbc94b5cf523cfc1331922f0d8a15c43afa29/.vscode/settings.json#L6) file and in the [screeps-ai.code-workspace](https://github.com/Jomik/screeps-ai/blob/e91bbc94b5cf523cfc1331922f0d8a15c43afa29/screeps-ai.code-workspace#L45) file.

**Comment by MariaSolOs** [comment]
Why you want to set your `node` path to that? You don't have `node` inside `.yarn/sdks`.

**Comment by Jomik** [comment]
I will test that, but sadly not a solution, as that path has no relation to the project and these settings should be committed.
It is yarn berry that automatically set that setting when installing the vscode sdk.
I should add that `yarn eslint .` works perfectly fine.

**Comment by Jomik** [comment]
But I guess my actual question is, why does it seem like `NODE_PATH` does not contain the `.yarn/sdks` from my settings? I assume that the Trace shows the actual value of `NODE_PATH`?

**Comment by Jomik** [comment]
Further investigation of the traces seems to show that the working directory is being set to the file in my `packages/*` dir, and not by the `.eslintrc` that has `root: true`.
```
        "nodePath": "../../.yarn/sdks",
        "workspaceFolder": {
            "name": "Bot",
            "uri": "file:///Users/<snip>/projects/private/screeps/screeps-ai/packages/bot"
        },
```

**Comment by Jomik** [comment]
I think the issue might be that my `packages/bot` contains a `package.json` ?

**Comment by Jomik** [comment]
> Why you want to set your `node` path to that? You don't have `node` inside `.yarn/sdks`.
> 
> Never mind I'm silly, I had not read what the setting is for. So I might be wrong but given that the path is appended to `NODE_PATH` and not `cwd`, maybe try setting `eslint.nodePath` relative to `/Users/.../.local/share/nvm/v16.14.2/lib/node_modules`?

Relative paths do not work. Also, I believe that `NODE_PATH` is a list of paths to check for node binaries, right?

**Comment by MariaSolOs** [comment]
@Jomik Oh I know, you haven't set `eslint.workingDirectories`.

**Comment by Jomik** [comment]
That sounds right, but what am I supposed to set the working directory as?
I have _one_ eslintrc in the root of my project.
Do I simply have to create multiple eslintrc files, for each package?
That is a bit of a pain, as I then also need to add all the eslint dependencies in each package.

**Comment by Jomik** [comment]
I have opened [a PR in my repo](https://github.com/Jomik/screeps-ai/pull/7), that seems to fix eslint.
But it is really not too pretty I think :/
Each package declares a .eslintrc and its depedencies (which is fine).
But the root package also needs `eslint` as a package dependency, which is odd.
And especially this configuration in `code-workspace` is odd.
```json
    "eslint.nodePath": "../../.yarn/sdks",
    "eslint.workingDirectories": ["packages/*"],
```

**Comment by MariaSolOs** [comment]
@Jomik you do not need to create separate `.eslintrc` configs, nor install the dependencies per workspace. Take a look at the [monorepo instructions from `typescript-eslint`](https://typescript-eslint.io/docs/linting/typed-linting/monorepos), and you can also take a look at this `yarn` monorepo I have with a shared linting configuration: https://github.com/MariaSolOs/paradeigma

The main points are:
- Make sure that your code workspace has the right `nodePath` and `workingDirectories` (it seems like this is already the case for your repo).
- Create a `tsconfig.eslint.json` file that includes your `.eslintrc.js` and has `noEmit` set to true (following the `typescript-eslint` instructions). 
- Your `.eslintrc.js` file should include all of your `tsconfig`s in `parserOptions.projects`.

**Comment by MariaSolOs** [comment]
As for running `eslint` as a `yarn` script inside a workspace, you can use [this handy trick](https://yarnpkg.com/getting-started/qa/#how-to-share-scripts-between-workspaces) so that you can use the dependency installed at the root.

**Comment by Jomik** [comment]
I have played with this some more, and I cannot actually get eslint to run on my typescript files when following the comment from Maria above.
It does not seem to find the files, or if it actually runs against the file, it complains about missing parser services.
If anyone has the spare time and willingness to try it out in my repo, I would love to figure out what I am missing.

I would like a single eslint config in the root, and a separate tsconfig for each package.

**Comment by Jomik** [comment]
@MariaSolOs Sorry, I should have pushed.
Funny thing - I must have missed something before, as I just recreated it and now it seems to work :)
I moved my [repo to GitLab](https://gitlab.com/Jomik/screeps-ai/-/merge_requests/12), as I wanted to play around with that provider a bit.
Guessing I cannot keep my `.eslintrc.yml` though, as I need `__dirname`? :(

Thank you!

**Comment by MariaSolOs** [comment]
@Jomik those are great news! Enjoy your new squiggles :)
Not sure if you can make YAML work but yeah I would suggest using `.eslintrc.js`. For IntelliSense you can add type annotations to the exported object.

**Comment by Jomik** [comment]
> For IntelliSense you can add type annotations to the exported object.
Yah, for some reason I have to declare the object to a variable, and then export it for that to work 🤷‍♂️
