### ISSUE TITLE
Can't get ESlint to work, I always get the error "ESLint is not running. By default only TypeScript and JavaScript files are validated."

### ISSUE THREAD

**Issue by mamutthe** [microsoft/vscode-eslint#1525]
I can't get ESlint to work in any project I try, it was actually working in my project before I reinstalled vscode. When I run the "ESlint: Restart ESlint server" it returns me the following error: _"ESLint is not running. By default only TypeScript and JavaScript files are validated. If you want to validate other file types please specify them in the 'eslint.probe' setting"_  ps: I'm actually trying to edit a .ts file.

I tried a couple of solutions I found online but none of them actually worked. Thanks in advance!

![Captura de tela 2022-09-12 211457](https://user-images.githubusercontent.com/86917624/189780555-5f041c0b-5804-41df-af07-32911318cf6e.png)

This is my **.eslintrc.json** file:
```json
{
  "root": true,
  "env": {
    "browser": true,
    "commonjs": true,
    "es2021": true
  },
  "extends": "standard-with-typescript",
  "overrides": [],
  "parserOptions": {
    "ecmaVersion": "latest"
  },
  "rules": {}
}
```
This is my **settings.json** file
```json
{
  "eslint.format.enable": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "liveServer.settings.donotShowInfoMsg": true,
  "editor.fontSize": 20,
  "editor.minimap.enabled": false,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "liveServer.settings.donotVerifyTags": true,
  "editor.inlineSuggest.enabled": true,
  "glassit.alpha": 220,
  "terminal.integrated.gpuAcceleration": "off",
  "code-runner.runInTerminal": true,
  "github.copilot.enable": {
    "*": true,
    "yaml": false,
    "plaintext": false,
    "markdown": false,
    "c": false,
    "go": true,
    "html": false,
    "javascript": false
  },
  "C_Cpp.updateChannel": "Insiders",
  "editor.formatOnSave": true,
  "bracketPairColorizer.depreciation-notice": false,
  "workbench.iconTheme": "vscode-icons",
  "vsicons.dontShowNewVersionMessage": true,
  "emmet.triggerExpansionOnTab": true,
  "editor.linkedEditing": true,
  "files.associations": {
    "*.js": "javascript"
  },
  "window.zoomLevel": -1,
  "json.schemas": [],
  "eslint": "eslint --ignore-path .gitignore .",
  "eslint.alwaysShowStatus": true,
  "eslint.debug": true,
  "remote.SSH.defaultExtensions": ["gitpod.gitpod-remote-ssh"],
  "eslint.packageManager": "yarn",
  "eslint.trace.server": "off",
  "eslint.workingDirectories": [],
  "eslint.nodePath": "C:\\Program Files\\nodejs",
  "eslint.enable": true,
  "eslint.probe": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "html",
    "vue",
    "markdown",
    "json"
  ],
  "eslint.validate": [
    { "language": "javascript", "autoFix": true },
    { "language": "typescript", "autoFix": true }
  ]
}
```

**Comment by MariaSolOs** [comment]
Is ESLint installed in your workspace/folder or globally?

**Comment by MariaSolOs** [comment]
Also your settings seem to be a bit all over the place. Try removing all of the `eslint` prefixed settings and slowly add them as needed. 

I'm pretty sure some of them are not defined correctly. AFAIK you can't lint JSON so don't include it in languages to probe. Also you don't seem to have the right parser for linting TypeScript, make sure to check out the `typescript-eslint` docs for instructions. And what is that `eslint` setting for...?

**Comment by mamutthe** [comment]
It worked!!! I replaced every config I had for brand new config and it work, thanks!

**Comment by dlibis** [comment]
@mamutthe thank you for opening this issue, ive had issues as well for months. reseting the config worked 🙏
