### ISSUE TITLE
ESLint autofix malfunction when using class with implements syntax

### ISSUE THREAD

**Issue by stegano** [microsoft/vscode-eslint#1536]
ESLint Autofix malfunction when using class with implements syntax

If you use class with implements syntax as shown below and press Cmd + S to run ESLint autofix, it will be inserted repeatedly even though the constructor implementation source code already exists.

```ts
// sample.ts

interface ITest {
  constructor(a: number): void;
}

class Test implements ITest {
  // `Cmd + S` → auto generated.. → Okay
  constructor(a: number) {
    throw new Error("Method not implemented.");
  }
  // `Cmd + S` → auto generated again.. why? 😭
  constructor(a: number) {
    throw new Error("Method not implemented.");
  }
}

```

https://user-images.githubusercontent.com/11916476/195529548-8a09e330-7cbf-4b8e-8e1e-6c5e1277bbc5.mp4

**Comment by MariaSolOs** [comment]
This is coming from the TypeScript auto-fixes, not the linting ones.

If you have the [`typescript-eslint`](https://typescript-eslint.io/) plugins in your `.eslintrc` configuration, you should see the following error when defining the interface, which suggests that [you aren't defining the constructor correctly in the interface](https://github.com/typescript-eslint/typescript-eslint/blob/v4.32.0/packages/eslint-plugin/docs/rules/no-misused-new.md):
![image](https://user-images.githubusercontent.com/62502207/195748902-59c73622-fb3c-4d40-96c0-8f377d34c212.png)

Okay so now if you instead trigger the quick actions from the squiggle under `Test`, you will see the following:
![image](https://user-images.githubusercontent.com/62502207/195749244-ce6ed19d-7d40-4a31-8670-895c6340213b.png)
The auto fix that you're seeing corresponds to implementing the interface (which is coming from TypeScript, not ESLint), but that doesn't solve the fact that you have an invalid constructor signature:
![image](https://user-images.githubusercontent.com/62502207/195749464-351a8501-fe40-4713-a2f3-d9ba4de83727.png)

**Comment by stegano** [comment]
Hi @MariaSolOs  
Thanks for your reply 😀
Close the issue
