### ISSUE TITLE
Which code formatters do you use?

### ISSUE THREAD

**Issue by doox911** [microsoft/vscode-eslint#1539]
Which code formatters do you use?

I am so sorry, but I can't find this information from this repository.

**Comment by dbaeumer** [comment]
ESLint style rules.

**Comment by doox911** [comment]
> So it's a linter, not a formatter.

**Comment by dbaeumer** [comment]
Yes.

**Comment by doox911** [comment]
> ESLint style rules.

**Comment by doox911** [comment]
> Yes.

So it's a linter, not a formatter.

**Comment by doox911** [comment]
> Yes.

Physically, how do you edit files? What's under the hood?

**Comment by dbaeumer** [comment]
VS Code's fix all on save infrastructure.

**Comment by doox911** [comment]
> VS Code's fix all on save infrastructure.

That is, it does the plugin format eslint rules into the rules of the regular vscode formatter? And Vscod has own formatter?
