### ISSUE TITLE
Add a status indication on how long the ESLint validation took. That is especially helpful for fix on save

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-eslint#1542]
See https://github.com/microsoft/vscode-eslint/issues/1538?notification_referrer_id=NT_kwDOAB15RrI0NjIyNDEyMTczOjE5MzE1OTA&notifications_query=repo%3Amicrosoft%2Fvscode-eslint#issuecomment-1290394217

**Comment by Dimava** [comment]
> Honestly, being able to see ESlint badge in the bottom bar saying "linting (pass 4)" atfer 2s lag would be good enough solution to one half of a problem
It would easily solve the "why is ESLint does not work", by showing user that the linter is actually working, and that the problem is on the user's side (too many rules, slow rules, etc)

**Comment by dbaeumer** [comment]
We should reference https://github.com/microsoft/vscode-eslint/issues/1344 in the indicator.

**Comment by Skylerspencer** [comment]
I really need someone physically in saltlake to help me any  ideas
