### ISSUE TITLE
Added "eslint.useESLintClass": true causing eslint to fail to format ts files

### ISSUE THREAD

**Issue by sunyayue** [microsoft/vscode-eslint#1548]
![image](https://user-images.githubusercontent.com/68684132/200733980-1ce3c62c-06d0-4e38-bc29-f40fdd5e2eef.png)

**Comment by sunyayue** [comment]
> 你使用的是哪个版本的 ESLint。
> 
> 最好能给我提供一个 GitHub 存储库，我可以克隆那个演示。否则我可能会开始使用不同的配置和版本，然后你会这样做。

v2.2.6

**Comment by sunyayue** [comment]
> Which version of ESLint are you using.
> 
> It would be best if you could provide me with a GitHub repository, I can clone that demos that. Otherwise I might start using different configs and versions then you do.

v2.2.6

**Comment by dbaeumer** [comment]
It is not about the extension. It is about you eslint npm config and all the configuration files around it, including the eslint plugins. That is why I asked you to please provide me with a GitHub repository I can clone since these configurations can be very sophisticated.

**Comment by sunyayue** [comment]
I created a new project and found that this configuration does not affect the normal use of eslint, so close this issue first, and will continue to pay attention to related issues in the future.
