### ISSUE TITLE
Provide command to open all files with errors

### ISSUE THREAD

**Issue by carlin-q-scott** [Microsoft/vscode-eslint#155]
I started implementing a new style for my project and after running auto fix on all files I still have quite a few files with errors in them. It would be awesome if I had a way to quickly open each file, fix the issues manually, save, and then move onto the next one.

I can probably achieve this through a custom browserify tranformer running after eslintify but it would be awesome if such functionality was baked into this extension.

I already tried using this [custom formatter for eslint](https://www.npmjs.com/package/eslint-friendly-formatter) made for sublime but the integrated console in VSCode doesn't pick up the file links.

**Comment by dbaeumer** [comment]
I marked this as a dub of #91. If the extension would lint all files all problems would show up in eslints problem view and the files could be opened from there.
