### ISSUE TITLE
VSCode constantly showing Saving code actions

### ISSUE THREAD

**Issue by harshanooka** [microsoft/vscode-eslint#1551]
Type: <b>Bug</b>

Install the extension and make changes to `.ts` files

Extension version: 2.2.6
VS Code version: Code 1.73.0 (Universal) (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:38:50.881Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No
Connection to 'SSH: dev-dsk-hnooka-2c-e787708f.us-west-2.amazon.com' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|12, 16, 12|
|Memory (System)|16.00GB (0.85GB free)|
|Process Argv|--crash-reporter-id 7500aa39-2afe-41d9-9334-a0a2f53ed386|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: dev-dsk-hnooka-2c-e787708f.us-west-2.amazon.com' could not be established  Canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30602488
gswce2:30605431
3d0df643:30604793
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by dbaeumer** [comment]
Please follow the steps outlined here https://github.com/microsoft/vscode-eslint/issues/1344 to further diagnose this. 

If you can't solve this following the provided steps, please provide me with a Github repository I can clone that demos what you are seeing.

**Comment by dbaeumer** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!
