### ISSUE TITLE
eslint cant analyze large files fully

### ISSUE THREAD

**Issue by maliknajjar** [microsoft/vscode-eslint#1552]
eslint is not analyzing the whole file .. I think it has a limit on the number of lines it can analyze.
It works fine when I tested in the beginning of the file .. but when I do the same thing at the end of the file it doesn't show me the warnings.
I tried to search on this problem but did not find anything useful.
![image](https://user-images.githubusercontent.com/59079190/201320636-689e6d0b-725f-458e-8e45-54d2f48b03e9.png)

Thanks

**Comment by MariaSolOs** [comment]
Is the behaviour any different if you run ESLint from the terminal?

**Comment by maliknajjar** [comment]
it works fine and it analyzes all the file when using the ESLint form the terminal
![image](https://user-images.githubusercontent.com/59079190/201611767-726e261c-292d-46c5-af52-1d292275b7a6.png)

**Comment by dbaeumer** [comment]
I think you are hitting VS Code 1000 errors limit per file (see https://github.com/Microsoft/vscode/issues/52736 and related issue). Is this the case for you? If so, there is nothing the VS Code extension can do about it.

**Comment by maliknajjar** [comment]
yes .. I think I hit 1000 errors limit
Thanks for helping

**Comment by dbaeumer** [comment]
Closing the issue then since this is controlled by VS Code.
