### ISSUE TITLE
@mickaelistria pourriez-vous expliquer dans quelles situations le languageId est nul ou non défini puisque selon le protocole, cela ne devrait jamais se produire.

### ISSUE THREAD

**Issue by carbondamien13** [microsoft/vscode-eslint#1561]
@mickaelistria could you explain in which situations the languageId is null or not set since according to the protocol this should never happen.

_Originally posted by @dbaeumer in https://github.com/microsoft/vscode-eslint/issues/1553#issuecomment-1314951364_

**Comment by dbaeumer** [comment]
@carbondamien13 could you please explain why you opened this issue?

**Comment by dbaeumer** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!
