### ISSUE TITLE
Force relint dependant files

### ISSUE THREAD

**Issue by A-Shleifman** [microsoft/vscode-eslint#1565]
I wrote an [ESLint plugin](https://www.npmjs.com/package/eslint-plugin-export-scope) that allows to "scope" exports. For example:

```ts
/** @scope .. */
export default '';
```

would only be importable within the parent directory and all subdirectories.

When I change the `@scope` declaration I want all `imports` (or whole files) referring to this export to be relinted to display/hide errors based on the updated declaration. Is there a way to force `vscode-eslint` extension to relint files?

**Comment by dbaeumer** [comment]
This is currently not possible sine ESLint itself nor the extension has a dependency graph. We would need to re-validate all files which can be quite expensive. So, the answer is no and there are actually no plans right now to add this. IMO something like this should be maintained by ESLint itself.
