### ISSUE TITLE
ESLint server crashed

### ISSUE THREAD

**Issue by smietanka** [microsoft/vscode-eslint#1571]
Hello I am facing with issue about ESLint server. It cannot be run in Visual Studio Code in 1.61.2 version, ESLint extension v2.2.2 .

While opening solution I've got in output such errors: 
```
[Info  - 11:39:03 AM] ESLint server is starting
[Info  - 11:39:06 AM] ESLint server running in node v14.16.0
[Info  - 11:39:06 AM] ESLint server is running.
AssignProcessToJobObject: (6) The handle is invalid.

[Info  - 11:39:07 AM] Connection to server got closed. Server will restart.
[Info  - 11:39:07 AM] ESLint server stopped.
[Info  - 11:39:07 AM] ESLint server is starting
[Info  - 11:39:10 AM] ESLint server running in node v14.16.0
[Info  - 11:39:10 AM] ESLint server is running.
AssignProcessToJobObject: (6) The handle is invalid.

[Info  - 11:39:11 AM] Connection to server got closed. Server will restart.
[Info  - 11:39:11 AM] ESLint server stopped.
[Info  - 11:39:11 AM] ESLint server is starting
[Info  - 11:39:14 AM] ESLint server running in node v14.16.0
[Info  - 11:39:14 AM] ESLint server is running.
AssignProcessToJobObject: (6) The handle is invalid.

[Info  - 11:39:14 AM] Connection to server got closed. Server will restart.
[Info  - 11:39:14 AM] ESLint server stopped.
[Info  - 11:39:14 AM] ESLint server is starting
[Info  - 11:39:16 AM] ESLint server running in node v14.16.0
[Info  - 11:39:16 AM] ESLint server is running.
AssignProcessToJobObject: (6) The handle is invalid.

[Info  - 11:39:17 AM] Connection to server got closed. Server will restart.
[Info  - 11:39:17 AM] ESLint server stopped.
[Info  - 11:39:17 AM] ESLint server is starting
[Info  - 11:39:21 AM] ESLint server running in node v14.16.0
[Info  - 11:39:21 AM] ESLint server is running.
AssignProcessToJobObject: (6) The handle is invalid.

[Error - 11:39:22 AM] Connection to server got closed. Server will not be restarted.
[Info  - 11:39:22 AM] ESLint server stopped.
```

and it crash because of 5 retries.

**Comment by dbaeumer** [comment]
Might be a problem if the node runtime in your setup. Can you point to a local node version using `eslint.runtime` setting?

**Comment by smietanka** [comment]
@dbaeumer 
This is the output when I changed `eslint.runtime` to `v18.12.1` - currently installed version of node on my local computer.
```
[Info  - 12:12:45 PM] ESLint server is starting
[Info  - 12:12:45 PM] ESLint server stopped.
[Error - 12:12:45 PM] Starting client failed
Launching server using runtime v18.12.1 failed.
[Error - 12:12:45 PM] On ready failed
Launching server using runtime v18.12.1 failed.
```

**Comment by dbaeumer** [comment]
What happens when you run ESLint in the terminal? This looks like a setup problem with ESLint itself

**Comment by smietanka** [comment]
When I type `npx eslint` in command line, then nothing happen (no error, not output). 
But when I type `eslint src/**/*.ts{,x} --quiet` then it looks like normally I've got a list of errors based on my rules. I don't know but it looks like ESLint is working itself but the server cannot be run in Visual Studio Code

**Comment by dbaeumer** [comment]
@smietanka can you provide me with a GitHub repository I can clone that demos the crash?

**Comment by smietanka** [comment]
Unfortunetly I can not share this code, but just right now I tried to do this with an empty project.
So I just create `npx create-react-app sample-app` and then `npm init @eslint/config` after complete setup of eslint I just restarted my Visual Studio Code and the same error happen.

This is my `settings.json`
```
{
    "update.mode": "none",
    "workbench.colorTheme": "Default Dark+",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "files.autoSave": "afterDelay",
    "explorer.confirmDelete": false,
    "eslint.format.enable": true,
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {  
        "source.fixAll": true
    },
    "liveServer.settings.donotShowInfoMsg": true,
    "[typescriptreact]": {
        "editor.defaultFormatter": "dbaeumer.vscode-eslint"
    },
    "eslint.alwaysShowStatus": true,
    "eslint.runtime": "v18.12.1"
}
```

**Comment by dbaeumer** [comment]
@smietanka the `eslint.runtime` setting must point to a node executable and not a node version. If node is on the path then simple `"eslint.runtime": "node"`

**Comment by smietanka** [comment]
@dbaeumer Cool! Thank you I didn't catch this now the server is running OK :)

**Comment by dbaeumer** [comment]
OK. Great. Will close the issue then.

**Comment by raulnazil** [comment]
nfo  - 12:14:08 AM] ESLint server is starting.
[Info  - 12:14:10 AM] ESLint server running in node v20.14.0
[Info  - 12:14:10 AM] ESLint server is running.
[Info  - 12:14:17 AM] ESLint library loaded from: C:\Users\Administrator\ProjectAkhir\node_modules\eslint\lib\api.js
[Error - 12:14:18 AM] Calculating config file for file:///c%3A/Users/Administrator/ProjectAkhir/.expo/types/router.d.ts) failed.
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript-eslint' imported from C:\Users\Administrator\ProjectAkhir\eslint.config.mjs
    at packageResolve (node:internal/modules/esm/resolve:861:9)
    at moduleResolve (node:internal/modules/esm/resolve:934:18)
    at defaultResolve (node:internal/modules/esm/resolve:1164:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36)
