### ISSUE TITLE
eslint.options.overrideConfigFile、eslint.options.overrideConfig not work 

### ISSUE THREAD

**Issue by RichieChoo** [microsoft/vscode-eslint#1577]
## env
Version: 1.69.2 (Universal)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 20.5.0

## vscode-eslint version
v2.2.6

## Expected
`eslint.options.overrideConfigFile`、`eslint.options.overrideConfig.rules` should  work，see detail at https://eslint.org/docs/latest/developer-guide/nodejs-api#-new-eslintoptions
<img width="748" alt="image" src="https://user-images.githubusercontent.com/17178139/211571054-f98fefc6-bcc6-4c81-939b-f2fff6fffd38.png">

## But
`eslint.options.overrideConfigFile`、`eslint.options.overrideConfig.rules` not work 
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/17178139/211570769-eddf955f-f703-4a1d-bd70-06967d751d1d.png">
but `eslint.options.configFile`、`eslint.options.rules` work , 
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/17178139/211570595-a180f851-d8b7-499d-b1c3-b4c8ff8c1ff0.png">
 
## Other
And the `configFile` and `rules`   should be removed in eslint
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/17178139/211569743-6ddd40db-4e1f-4448-ab25-9dfebdfaa60c.png">

Anyone who can help me？Thanks very much !

**Comment by dbaeumer** [comment]
Could you please provide me with a GitHub repository I can clone that demos this. That ensures that we are looking at the same setup in terms of options and eslint, plugin versions.

**Comment by RichieChoo** [comment]
## demo 
https://github.com/RichieChoo/vscode-eslint-demo

**Comment by RichieChoo** [comment]
> Could you please provide me with a GitHub repository I can clone that demos this. That ensures that we are looking at the same setup in terms of options and eslint, plugin versions.

Demo: https://github.com/RichieChoo/vscode-eslint-demo

**Comment by RichieChoo** [comment]
@dbaeumer Could you please help me to find  the reason

**Comment by dbaeumer** [comment]
@RichieChoo the reason is the ESLint version you are using. The new `overrideConfig` option is only available since version `8.x` but you are requiring `7.32.0`

The ESLint npm package changed naming around this for version 8.x in a breaking way. Hence clients need to adopt to this.

**Comment by dbaeumer** [comment]
I will close the issue. Please ping if this doesn't help.
