### ISSUE TITLE
eslint.config.js: Configuration file only detected at root of workspace

### ISSUE THREAD

**Issue by kiriDevs** [microsoft/vscode-eslint#1578]
I read through the thread in #1518 because I was looking for support for the new `eslint.config.js`. After switching to the pre-release of the extension and setting `eslint.experimental.useFlatConfig` to `true` in my workspace settings, the whole thing seemed to work... more than before, I guess. Ok, seriously, thanks for adding this and publishing it, and so quickly at that.

But, turns out: The extension only recognizes an `eslint.config.js` file if it's at the root of the workspace (as in, the folder that is opened in VSCode). With the issues there still are with watching the config file, I understand that this might be an issue (as in: not feasibly possible at the moment). However, because I didn't see any mention of this particular point in that thread, I was unsure if this was known, and just wanted to make sure.

I hope this will be possible again in the final release, I can see this being a blocker for monorepos and similar workplace scenarios.

EDIT: It only *automatically* recognizes an `eslint.config.js` file if it's at the root of the workspace. If I manually specify `eslint.options.overrideConfigFile` it uses it just fine.

**Comment by MariaSolOs** [comment]
@kiriDevs Did you set `eslint.workingDirectories` accordingly? There's more information about the setting in the [README](https://github.com/microsoft/vscode-eslint#settings-options).

**Comment by kiriDevs** [comment]
No, I hadn't. Just set it to `{ "mode": "auto" }` and that actually achieves the behavior I expected. Reading the part about it in the README, it does make sense that it doesn't work without changing it. I had just kind of assumed I didn't need to because it worked out of the box when using `.eslintrc.*` files (somehow, since apparently that shouldn't be the case with `{ "mode": "location" }` as the default value.

Thanks for the hint @MariaSolOs
