### ISSUE TITLE
VSCode locked up and freezing after a while.

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode-eslint#1584]
https://github.com/microsoft/vscode/issues/171691

I'm pretty certain the culprit is eslint. pls look at the files I attached to that issue to see if it makes sense to you

**Comment by jpike88** [comment]
Workaround: switch to Rome instead. Zero slowdowns, zero CPU overhead!

**Comment by dbaeumer** [comment]
I commented on the VS Code issue. I will close this one.
