### ISSUE TITLE
Confused by `ms` in language status

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-eslint#1589]
For https://github.com/microsoft/vscode/issues/171965

![Screenshot 2023-01-24 at 9 49 48 AM](https://user-images.githubusercontent.com/12821956/214369658-263a00d0-7606-4cb9-9544-411ed56824e2.png)

With the language status item, I was initially confused by the `[Xms]`. Could we label the number so it is clearer what it means. Maybe `Ran eslint in Xms`?

**Comment by mjbvz** [comment]
Also noticeable when the eslint item is pinned:
![Screenshot 2023-01-24 at 10 05 52 AM](https://user-images.githubusercontent.com/12821956/214372884-79b69d27-d6ed-4ba9-8bb7-8490e0737824.png)

When pinned though, my proposal for `Ran eslint in Xm` is likely too long. Maybe just `ESLint`?

**Comment by dbaeumer** [comment]
Good ideas. Will look what I can do about it.

**Comment by dbaeumer** [comment]
I did some improvements. The timing is now shown in details with a better description. That avoid that it is visible when the item is pinned.

**Comment by dbaeumer** [comment]
Available in 2.3.5 pre-release.
