### ISSUE TITLE
When fixing error, ESLint issue is not updating

### ISSUE THREAD

**Issue by khrome83** [Microsoft/vscode-eslint#16]
I had a LF expected but was CRLF. When I updated the file to be correct, the errors were not resolved. I had to close out VS Code and reopen to update the ESLint error reporter. 

This was on Windows 10, version 0.10.5 of VS Code.

**Comment by dbaeumer** [comment]
I can't reproduce this using VSCode 0.10.6 and the latest eslint extension. If you still see this, please ping and provide steps how to reproduce.
