### ISSUE TITLE
Extension failes with `Command failed: pnpm root -g`

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode-eslint#1600]
Type: <b>Bug</b>

## Summary
eslint extension fails to run node if both pnpm and node is installed via [asdf](https://asdf-vm.com/).

## Solution
manually setting node path, for example `"eslint.runtime": "/home/scarf/.asdf/shims/node"` works.

## How to Reproduce 
1. install [pnpm](https://github.com/jonathanmorley/asdf-pnpm) and [node](https://github.com/asdf-vm/asdf-nodejs) with asdf.'
2. setup eslint.
3. extension fails because node inside `asdf-pnpm` script is not found:
```ts
[Error - 오후 6:27:27] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Command failed: pnpm root -g
/home/scarf/.local/share/pnpm/pnpm: 16: exec: node: not found

  Code: -32603 
Uncaught exception received.
Error: Command failed: pnpm root -g
/home/scarf/.local/share/pnpm/pnpm: 16: exec: node: not found

    at checkExecSyncError (node:child_process:848:11)
    at execSync (node:child_process:922:15)
    at node:electron/js2c/asar_bundle:5:12704
    at Object.get (/home/scarf/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:25051)
    at e.get (/home/scarf/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:25160)
    at /home/scarf/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:19727
```

content of `/home/scarf/.local/share/pnpm/pnpm`:
```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/scarf/.local/share/pnpm/global/5/.pnpm/node_modules"
else
  export NODE_PATH="$NODE_PATH:/home/scarf/.local/share/pnpm/global/5/.pnpm/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/global/5/node_modules/pnpm/bin/pnpm.cjs" "$@"
else
  exec node  "$basedir/global/5/node_modules/pnpm/bin/pnpm.cjs" "$@" # line 16
fi
```

Paths:
```sh
scarf@HP15 ~/r/iso8601 (meta ±)> which node
/home/scarf/.asdf/shims/node
scarf@HP15 ~/r/iso8601 (meta ±)> which pnpm
/home/scarf/.asdf/shims/pnpm
scarf@HP15 ~/r/iso8601 (meta ±)> echo $PATH | grep .asdf
/home/scarf/.asdf/shims (...more)
bash
scarf@HP15:~/repo/iso8601$ echo $PATH | grep .asdf
(...more):/home/scarf/.asdf/shims:(...more)
```

Extension version: 2.4.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:29:17.766Z)
OS version: Linux x64 5.19.0-29-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics (8 x 2039)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|30.72GB (21.01GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by MariaSolOs** [comment]
@scarf005 You should also include the extension settings you're using.

**Comment by MariaSolOs** [comment]
So the error is coming from here:
https://github.com/microsoft/vscode-eslint/blob/52e2d43ad2e2c99727cba92ec13157aab6d4cffb/server/src/eslint.ts#L1148

I'm not familiar with `asdf` but from your output of `which node` it seems like it changes the location of `node`, and hence why the `execAsync` fails (and which also explains why setting `eslint.runtime` fixes the issue). That being said, this doesn't feel like a bug but the intended behavior, but I'll let @dbaeumer decide.

**Comment by scarf005** [comment]
what i find it weird is that pnpm in `pnpm root -g` works wheras `node` wouldn't when both their path is modified (i.e $HOME/.asdf/shims). shouldn't pnpm also fail?

**Comment by scarf005** [comment]
> You should also include the extension settings you're using.

does it mean `eslint.*` on `settings.json`? it's
```json
{
  "eslint.format.enable": true,
  "eslint.packageManager": "pnpm"
}
```

**Comment by dbaeumer** [comment]
The reason for this is very likely the starting point of VS Code. When you start it from a console window that has the paths setup correctly does it fail as well?

**Comment by Deckluhm** [comment]
> The reason for this is very likely the starting point of VS Code. When you start it from a console window that has the paths setup correctly does it fail as well?

I confirm that it seems to fix the problem.

I usually start my VS Code (which is configured to be opened "blank") and then open a recent project I have been working on, using `Ctrl+R`.

If I do open a folder using `code ~/path/to/project`, it works well (and no longer have the `pnpm root -g` error).

Thanks a lot!

**Comment by ivan2214** [comment]
I had the same problem, and what I did was to add the PNPM installer's location to the environment variables in the PATH, and that resolved the issue.

**Comment by scarf005** [comment]
> I had the same problem, and what I did was to add the PNPM installer's location to the environment variables in the PATH, and that resolved the issue.

```sh
$ echo $PATH | rg -i pnpm
... /home/scarf/.local/share/pnpm ...
```

I haven't used eslint extension for months, but I recently need to use it and to my surprise it just worked. Seems like I'd indeed added pnpm install location to PATH earlier. Closing as the suggested solution seems to work and I can't reproduce the problem now.
