### ISSUE TITLE
Monorepo and `"eslint.workingDirectories": [{ "mode": "auto" }]`

### ISSUE THREAD

**Issue by mamionga** [microsoft/vscode-eslint#1604]
I have a monorepo project with two folders: `backend` and `web`. ESLint alternates between the two folders, If I'm on a backend file and restart the server the error goes away but now shows up in my `.vue` files. If I go to a .vue file and restart the server the error goes away but now shows up on my `backend` `.ts` files.

<img width="1040" alt="Screen Shot 2023-02-09 at 1 10 28 PM" src="https://user-images.githubusercontent.com/13022799/217913836-38723bea-5d3a-40cf-b87a-c8f60e03a502.png">

Thanks, been struggling with this for a long time now.

**Comment by dbaeumer** [comment]
Can you please provider me with a GitHub repository I can clone that demos that in a small sample setup. It is hard to tell why this is not working without being able to reproduce this.

**Comment by mamionga** [comment]
I've set up [this repo](https://github.com/mamionga/SST-Path-Test) which is a stripped out version of the project. You can take a look at `web/src/App.vue` and `backend/src/api/user/get.ts` but... it actually works on that one!

The full project has the exact same configuration but a lot of extra endpoints and components. Could it be too many files for the `[{mode: auto}]` to handle?

**Comment by mamionga** [comment]
Ok, I've added some more frontend components and now it's not working if you go inside `web/src/components/contest/manage/manageContest.vue` for example and `backend/src/api/user/get.ts` one of them will not work, if you restart the ESLint server while on the backend the backend will work but not the front and vice-versa.

Just in case, these are my extensions.
<img width="479" alt="Screen Shot 2023-02-10 at 9 40 28 AM" src="https://user-images.githubusercontent.com/13022799/218132801-88132854-6d22-4f0a-879b-388129234cac.png">

**Comment by mamionga** [comment]
looks like `plugin:import/recommended` is the culprit of this

**Comment by hchatel** [comment]
Hi @mamionga !
I face the exact same problem on my monorepo.
Can you share more details about your solution ?

**Comment by mamionga** [comment]
Sure, this is my plugin list:

```
"extends": [
    "plugin:vue/essential",
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/typescript"
  ],
```

I used to have `import/recommended` and after removing it everything worked just fine. I'm not sure if that's helpful enough!

**Comment by hchatel** [comment]
It doesn't seem to help in my case, there was no `import/recommended` in my project..
But thank you for your reply !

**Comment by mamionga** [comment]
Oh, then check your workingDirectories, try setting them manually instead of using auto or see if any other plugins are the cause. I had to debug it by making a new project and adding stuff one at a time until it broke.

**Comment by yqkqknct** [comment]
For those who also encounter this is fixed by https://github.com/import-js/eslint-import-resolver-typescript/issues/217 and should be good in 3.5.4
