### ISSUE TITLE
vscode-eslint v2.4.0 not working at all

### ISSUE THREAD

**Issue by keremcanb** [microsoft/vscode-eslint#1608]
I was using VS Code 1.75.1 (user setup) with vscode-eslint 2.4.0 on Windows 10 and I noticed that vscode-eslint wasn't working at all. I checked output tab to see if there were any errors logged, but ESLint entry was missing. But I could run ESLint from command line without any problems. 

First I thought this might be related to the new version of VS Code so downgraded it to November version, but it was the same. Then I downgraded vscode-eslint to version 2.3.5, and everything returned back to normal. Now there is an ESLint entry again at the output tab, server started without a problem and ESLint library got loaded. So I disabled extension auto update from VS Code settings and will continue to use 2.3.5 until there is a fix.

**Comment by dbaeumer** [comment]
@keremcanb can you please provide me with a GitHub repository I can clone that demos what you are seeing. Without steps on how to reproduce this it is very hard to tell why it is not working for you.

**Comment by belaczek** [comment]
For us it stopped working too. It only starts working after I duplicate the list of values from `eslint.probe` to `estlint.validate` setting. Yet the documentation says this should not be necessary 🤔

**Comment by dbaeumer** [comment]
@belaczek can you please provide me wit a Github repository I can clone that demos this. I can not reproduce the issue locally and without steps it is very hard to tell what is going on.

You can also enable tracing using the following two settings:

```
	"eslint.trace.server": "messages",
	"eslint.debug": true,
```

May be this gives additional insides.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
