### ISSUE TITLE
Autofix doesn't handle cursor/selection correctly

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-eslint#161]
Testing https://github.com/Microsoft/vscode/issues/14319 .

Repro steps:
1. Turn on eslint rule `curly` as `warn`.
2. Insert following code into the editor, put cursor just after the semicolon.
   
   ```
   if (foo) foo++;
   ```
3. Save
### Expected

The content is changed to `if (foo) {foo++;}` and the cursor is after `}`
### Actual

The content is fixed correctly while both `;` and `}` are selected.

![screen shot 2016-10-25 at 10 21 38 am](https://cloud.githubusercontent.com/assets/876920/19696635/d9175f0e-9a9c-11e6-83fe-aa82837136d8.png)
### Note

This issue won't happen if you already put cursor elsewhere.

**Comment by dbaeumer** [comment]
I checked this and the edit actually looks ok to me:

```
[Trace - 12:12:32 PM] Received response 'textDocument/willSaveWaitUntil - (14)' in 1ms.
Result: [
    {
        "range": {
            "start": {
                "line": 2,
                "character": 10
            },
            "end": {
                "line": 2,
                "character": 16
            }
        },
        "newText": "{foo++;}"
    }
]
```

Moving to VS Code since this is nothing ESLint can fix.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode#19828
