### ISSUE TITLE
Lintining and fixing stopped working

### ISSUE THREAD

**Issue by OlkaB** [microsoft/vscode-eslint#1612]
Type: <b>Bug</b>

Hello,
Second day in a row the VSC lintning & automated fixing does not work at all on file saving (.vue). All I'm getting is constant prompt:
```
Saving '{fileName}': Getting code actions from ''Vetur', 'ESLint''
```
which never resolves. I need to constantly click 'cancel' on it to allow file to be saved. 

Extension version: 2.4.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.60GB (4.03GB free)|
|Process Argv|--crash-reporter-id 1b6b6d54-a926-42bf-bf54-02b9f0b5ea5e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
This could be both the `Vetur` extension or `ESLint` since both seem to participate in save. Could you disable one of them and see if you can still reproduce this. If you can with ESLint enabled can you please add tracing by adding the following settings:

```
	"eslint.trace.server": "messages",
	"eslint.debug": true,
```

and then attached the output from the ESLint output channel here. That will help to understand why ESLint is taking so long.

**Comment by OlkaB** [comment]
Hi @dbaeumer,
Thank you for your response. Indeed this is an issue generated by Vetur - I've downgraded to previous version (0.36.1) and all works fine.
If above answer is not satisfying, please let me know and I will upgrade again and will post the messages generated by the settings you've posted.

**Comment by dbaeumer** [comment]
@OlkaB thanks for getting back. All I can recommend is to report the issue against Vetur.
