### ISSUE TITLE
VS Code Eslint does not show up in Output

### ISSUE THREAD

**Issue by raygig** [microsoft/vscode-eslint#1617]
I have installed eslint and the eslint extension and ran the following command successfully 

```
.\node_modules\.bin\eslint --debug
```

Is a log that shows the Eslint Extension startup process which calls eslint from the command line?

I have this same configuration working on another project with the exact same settings. The Eslint Extension must be failing but there is no logs to help determine what is going on during the start server process.

**Comment by dbaeumer** [comment]
The ESLint output channel is under Menu > View > Output and then in the Output Channel select `ESLint` from the drop down.

You can enrich the output by using the following two settings:

```
	"eslint.trace.server": "messages",
	"eslint.debug": true,
```

Does this work for you?

**Comment by raygig** [comment]
I figured it out. The issue was ESLint doesnt start until you open a file type that is monitored with EsLint. Other extensions that run servers in the background start as soon as VS code opens. 

I would suggest to create a setting that specifies when the ESLint server starts. Options could be 1. Start ESLint server when any monitored file is opened. 2. Start ESLint server when VS Code starts. At least with this setting someone who is not sure how the server starts there is some documentation and something searchable to give them more information of how it works.

**Comment by dbaeumer** [comment]
Actually, such a setting exists on language mode id. Check the setting `eslint.probe`. 

I am not sure why we should start the ESLint server when VS Code starts. That is against the recommendations of VS Code.

I will close the issue. Please ping if you disagree.

**Comment by Redskinsjo** [comment]
me neither. eslint select value doesn't show up when i open the output select although i have the icon of eslint ( { } ) in the status bar that alerts `No Schema Validationno JSON schema configured` when i click
