### ISSUE TITLE
Show error status in the gutter (feature request)

### ISSUE THREAD

**Issue by rswerve** [Microsoft/vscode-eslint#162]
This is wonderful extension, and the integrated autofix makes it better than the Sublime equivalent, but one valuable feature is to have an indicator in the gutter for lines that are in the "warn" or "error" state, so that the user can see in the file itself what needs attention, rather than referencing back and forth from the list of issues.

<img width="236" alt="eslintgutter" src="https://cloud.githubusercontent.com/assets/8964335/19700560/6aeb6216-9abd-11e6-846a-f0f1646c1d88.png">

It looks like VS Code supports gutter decorators:  http://code.visualstudio.com/docs/extensionAPI/vscode-api#DecorationRenderOptions

Thanks for all the hard work.

**Comment by dbaeumer** [comment]
This should happen in VS Code itself to make this consistent with other errors and warnings. It dups https://github.com/Microsoft/vscode/issues/3915
