### ISSUE TITLE
import/no-unused-modules disables VS Code error & warning highlights

### ISSUE THREAD

**Issue by a-lukianenko** [microsoft/vscode-eslint#1622]
Hi! 👋 

I'm trying to use `import/no-unused-modules` as part of Next.js project. Here is what happens:

- `Next.js 12.3.4`
- `eslint-plugin-import 2.26.0`

ESLint config snippet
```js
 'import/no-unused-modules': [
            'error',
            {
                unusedExports: true,
                ignoreExports: [
                    '**/__mocks__/*',
                    '**/__stories__/*',
                    '**/__tests__/*',
                    '**/*.d.ts',
                    'config/**/*',
                    'lib/**/*',
                    'routes/**/*',
                ],
          },
  ],
```

**Before enabling `import/no-unused-modules`**:
| File with highlights from `VSCode` 👍  | ESLint output 👌  |
| ---- | ----- |
| <img width="872" alt="Screenshot 2023-03-14 at 11 43 20" src="https://user-images.githubusercontent.com/46814181/224944709-9b8f4432-d711-4c24-b85a-5f2d6775fc79.png"> |  <img width="1045" alt="Screenshot 2023-03-14 at 11 34 29" src="https://user-images.githubusercontent.com/46814181/224944844-dbf17f3d-6d2f-47f4-86c0-c1a18c21565a.png"> |

**After enabling `import/no-unused-modules`**:
| File has no highlights from `VSCode` 👎  | ESLint output still 👌  |
| ---- | ----- |
| <img width="871" alt="image" src="https://user-images.githubusercontent.com/46814181/224946155-9de5eb7d-cb28-4836-aba6-7493d0a0334b.png"> |  <img width="1042" alt="image" src="https://user-images.githubusercontent.com/46814181/224946569-4d366626-64b3-4665-a257-6fdc09119107.png"> |

**Comment by dbaeumer** [comment]
Without a Github repository I can clone and steps to reproduce hard to tell why this is not working. My guess is a missing `eslint.workingDirectory` setting. When running in a terminal do you `chdir` into a sub folder. If yes you need to specify such a working directory via `eslint.workingDirectory`,

**Comment by a-lukianenko** [comment]
Hi @dbaeumer ! 👋 

Thanks for the hint: seems like setting `"eslint.workingDirectories": [{ "mode": "auto" }]` has solved the issue, I'm still testing but here are the results:

| VSCode ESLint error report | ESLint terminal output |
| - | - |
| <img width="853" alt="image" src="https://user-images.githubusercontent.com/46814181/225297616-aa6d2c3b-926a-4a9b-bdcc-de58520cc500.png"> | <img width="900" alt="image" src="https://user-images.githubusercontent.com/46814181/225297683-8ac1de98-249b-432f-b15b-6106fe8533e2.png"> |

Let me test this setup more and tomorrow I will confirm by closing the Issue!

**Comment by a-lukianenko** [comment]
Hi @dbaeumer! 👋 

I confirm settings `eslint.workingDirectories` fixes the issue. Closing as not planned.

Thank you, have a beautiful day! 😊
