### ISSUE TITLE
IntelliSense suggestions on eslintrc file

### ISSUE THREAD

**Issue by hindicator** [microsoft/vscode-eslint#1623]
Hi,

Correct me if I'm wrong, 
regarding eslintrc config, specifically `eslintrc.json` ,
this extension is responsible for autocomplete and suggestions for intelli-sense ?

How it's implemented ?

I'm using `@typescript-eslint` plugin and wondered how it's possible to achieve this with the plugin(or plugins) as well.

Also [see this](https://github.com/typescript-eslint/typescript-eslint/issues/6764).

**Comment by dbaeumer** [comment]
The extension doesn't do anything special here. VS Code itself can validate json files using a JSON schema. All that the extension does is link aeslintrc.json file to a corrsponding scheme.

**Comment by marekdon** [comment]
So with the new flat config, this feature is no longer available? Before when I hovered on a rule, I could see its description etc, now, there is nothing
