### ISSUE TITLE
No nullish coalescing assignment operator

### ISSUE THREAD

**Issue by joakim-ronning** [microsoft/vscode-eslint#1624]
![image](https://user-images.githubusercontent.com/84327473/227985891-9e4d3575-b876-453b-baff-b865d77b39ff.png)

using the following code: 
```
let x;
x ??= 1;
 ```
 results in a `Parsing error: Unexpected token =`
 
 Nullish Coalescing Assignment operator was added in ECMAScript 2020 and can be found [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment) 

Currently using `"eslint": "^8.36.0"` with
```
"parserOptions": {
  "ecmaVersion": 2020
}
 ```

**Comment by dbaeumer** [comment]
@joakim-ronning  does the validation happen correctly when you use eslint in the terminal?

**Comment by joakim-ronning** [comment]
@dbaeumer Yes: ` 150:7  error  Parsing error: Unexpected token =`

ran `npx eslint ./`

**Comment by dbaeumer** [comment]
Then this is a more general problem with ESLint. I would suggest to report the problem there since there is nothing I can do about it in the extension.

**Comment by joakim-ronning** [comment]
Thanks Dirk, I'll do that

**Comment by edemuck4timbuktu** [comment]
@joakim-ronning A workaround is to use the extention `@typescript-eslint/eslint-plugin`. 
.eslintrc:
```js
{
    extends: [
        "plugin:@typescript-eslint/recommended",
      ],
}
```
This is working with eslint `8.X.X` and @typescript-eslint/eslint-plugin  `5.X.X`.
