### ISSUE TITLE
"Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser..." for no apparent reason

### ISSUE THREAD

**Issue by DanielGiljam** [microsoft/vscode-eslint#1645]
# Brief description

The VSCode ESLint plugin throws

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages/query-core/src/infiniteQueryBehavior.ts.
The file must be included in at least one of the projects provided.
```

even when everything seems to be correctly configured (`pnpm test:eslint` command runs just fine).

# How to reproduce

1. Use VSCode with an empty profile.
2. Clone the [Tanstack Query](https://github.com/TanStack/query) repo into a [Node.js & TypeScript Dev Container](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/typescript-node).
3. Install the VSCode ESLint plugin.
4. Open a terminal and run `pnpm install`.
5. Open any TypeScript file, e.g. `packages/query-core/src/infiniteQueryBehavior.ts`.
6. See red squiggly line in the beginning of the first line.

<img width="1413" alt="CleanShot 2023-04-28 at 10 30 39@2x" src="https://user-images.githubusercontent.com/33825175/235088480-4d714ee2-8575-4ca6-9d14-6ee9cdd38ac0.png">

**Comment by dbaeumer** [comment]
The reason for this is that the auto detection of the ESLint plugin detects a TypeScript setup with proper ESLint plugins and wants to lint TS files. You can disable this by only list the language IDs you want to validate in the `eslint.validate` setting.

If you want to validate TS files with ESLint then this error message is expected since the same happens when running ESLint in the terminal:

```
./node_modules/.bin/eslint packages/query-core/src/infiniteQueryBehavior.ts

/workspaces/query/packages/query-core/src/infiniteQueryBehavior.ts
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages/query-core/src/infiniteQueryBehavior.ts.
The file must be included in at least one of the projects provided

✖ 1 problem (1 error, 0 warnings)
```
