### ISSUE TITLE
'Unable to resolve path to module' for local modules

### ISSUE THREAD

**Issue by John-H-Smith** [microsoft/vscode-eslint#1649]
I have created a own local module, lets say it's called 'test1'.
If I want to include it in my second application ('test2'), this extension shows the error `Unable to resolve path to module 'test1'.eslint(import/no-unresolved)`. In the package.json, it's included like that:

```
"dependencies": {
    "test1": "file:../test1"
  },
```

But as I have eslint installed on the project to and am running `npx eslint`, it runs without any errors. 
Also, the code I am executing from that module is running fine.
So I assume that the extension does not handle local modules correctly.

Both are written in typescript btw.

**Comment by dbaeumer** [comment]
@John-H-Smith can you please provide me with a Github repository I can clone that demos that. Otherwise it is very hard to say why it is not working.

**Comment by John-H-Smith** [comment]
I cannot reproduce it anymore.
