### ISSUE TITLE
func-call-spacing error?

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode-eslint#165]
I have an Angular controller which is wrapped in an IIFE.  When I use VSCode's "format code" command, it adds a space between the function and parens, which is correct:

`_this.deploy = function () {...}`

But "format code" does this to the end if the IIFE, which is equally ok but eslint flags it as an error:

![screen shot 2016-11-03 at 10 54 56 am](https://cloud.githubusercontent.com/assets/835148/19971303/03256204-a1b5-11e6-8918-e2ee8610e8f3.jpg)

Can this be remedied via settings, or is this a bug?

**Comment by dbaeumer** [comment]
@smlombardi you need to file this against vscode (https://github.com/Microsoft/vscode). Thanks.
