### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by gernotpokorny** [microsoft/vscode-eslint#1650]
I provided a [Testrepo ](https://github.com/gernotpokorny/eslint-testrepo-codeaction-failed)where it is pretty easy to reproduce this error within the Output of Eslint within Visual Studio Code.

1. `npm i`
2. Open `foo.json`
3. Go to the Eslint Output within Visual Studio Code

That's it.

```
[Info  - 1:13:01 AM] ESLint server is starting.
[Info  - 1:13:02 AM] ESLint server running in node v16.17.1
[Info  - 1:13:02 AM] ESLint server is running.
[Info  - 1:13:04 AM] ESLint library loaded from: C:\Home\tmp\eslint\node_modules\eslint\lib\api.js
[Error - 1:13:12 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Invalid regular expression: //** eslint-disable-next-line/: Nothing to repeat
  Code: -32603 
```

What is the reason for this error?

I cannot find any regular expression that looks like the one within the error message, not even within `node_modules`.

**Comment by MariaSolOs** [comment]
This was fixed in #1611, but I think that there hasn't been a release since then.

**Comment by dbaeumer** [comment]
Dups #1611 

Will look into creating a new pre-release this week

**Comment by gernotpokorny** [comment]
Thank you very much

**Comment by dbaeumer** [comment]
Published pre-release 2.4.1

**Comment by passbyval** [comment]
I was also experiencing this issue. The pre-release fixed it. Thanks @dbaeumer!

**Comment by gernotpokorny** [comment]
When can we expect this to be released?

**Comment by dbaeumer** [comment]
2.4.2 got released today.
