### ISSUE TITLE
Reduce extension restarts for typescript monorepos?

### ISSUE THREAD

**Issue by qpwo** [microsoft/vscode-eslint#1654]
In a typescript monorepo with `typescript-eslint`, I have to restart the eslint extension every time I make a change in a dependency. Otherwise, false errors remain and/or true errors don't appear.

(Running eslint in the command line always gives correct info.)

Unfortunately, I don't know what causes this or how to fix it.

Here's a minimal repo to demonstrate: https://github.com/qpwo/eslint-vscode-monorepo-issue-example

Here's a video:

https://github.com/qpwo/eslint-vscode-monorepo-issue-example/assets/10591373/4bea3b36-9e29-49c9-8fef-935d9ee69601

I could not find any related issues.

Any ideas?

**Comment by qpwo** [comment]
Couple more notes:

1. If I'm not running tsc in watch mode then sometimes bad errors won't go away. (I assume this is unrelated and/or unfixable.)
2. Only making an issue for this because some people on my team don't figure out how to make the extension work in our monorepo so disable it.
3. Incredible extension overall

**Comment by dbaeumer** [comment]
The `typescript-eslint` plugin has issues with project references, especially the once only specified in the tsconfig.json file (see. https://github.com/typescript-eslint/typescript-eslint/issues/2094). Usually it is enough to update the parseProject property in the eslint config files as well. However when using project references you need to duplicate them on that property.

Are you doing this in your setup?

**Comment by dbaeumer** [comment]
Looked at the example and it looks like this could be the problem. Here is how I setup thinks to overcome that problem in typescript-eslint

<img width="804" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/1931590/6876e754-bbc0-4d41-9125-cf8e0eed4560">
