### ISSUE TITLE
"Initializing JS/TS language features" status message repeatedly appearing when opening a TS file

### ISSUE THREAD

**Issue by daedam** [microsoft/vscode-eslint#1656]
Type: <b>Bug</b>

## Steps to reproduce

1. With the ESLint extension enabled, open a project with TypeScript code
2. Open a TypeScript file in an editor window
3. The status message "Initializing JS/TS language features" blinks repeatedly in the bottom status area. Although the language server seems to be working correctly, the message appears and disappears, with a frequency of approximately 1 second on then 1 second off.

## Expected result

The message appears once when the project is loading and does not flash repeatedly. This appears to be the behavior when the ESLint extension is disabled.

## Notes

When I used the "Extension bisect" tool, the problem only appeared when the ESLint extension was enabled. The repeated blinking of this status message creates a distracting effect.

Extension version: 2.4.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.84GB (7.58GB free)|
|Process Argv|. --crash-reporter-id 2bcc76d7-dfba-45dc-be80-d8e8c0b532de|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
pythongtdpath:30739704
pythonnosmt12:30757131

```

</details>

**Comment by daedam** [comment]
Specifically, I first noticed this when opening a new SharePoint SPFx "Application Customizer" project scaffolded using the @microsoft/sharepoint Yeoman generator.

**Comment by dbaeumer** [comment]
@daedam any additional steps or a GitHub repository that I can clone that demos this. I tried to reproduce but wasn't able to do so:

![cast](https://github.com/microsoft/vscode-eslint/assets/1931590/fb7aeda1-5591-45e7-a7f8-57ea670dd642)

And from a VS Code API perspektive the ESLint extension has actually no means to influence the appearance of the TypeScript status bar item.

**Comment by daedam** [comment]
Hi @dbaeumer. Thanks for looking into this and for the additional info. I am experiencing this problem when opening a brand new SharePoint Framework (SPFx) project scaffolded using the `@microsoft/sharepoint` Yeoman generator on Node 16.20 (note that SPFx requires Node 16). Here are the setup steps I used:

```sh
nvm use 16
npm install --global yo @microsoft/generator-sharepoint@1.17.3
yo @microsoft/sharepoint
# use default values and select Extension > Application Customizer
```

I committed this project with no changes to [daedam/spfx-eslint-test](https://github.com/daedam/spfx-eslint-test).

To confirm the behavior, I created a new empty VS Code profile with nothing but the ESLint extension installed. I observed the behavior was happening even in this minimal profile when opening src/extensions/helloWorld/HelloWorldApplicationCustomizer.ts:

https://github.com/microsoft/vscode-eslint/assets/1699551/35622927-04ac-442d-b544-e9d09ec6c523

I then tried uninstalling the ESLint extension, and the problem went away:

https://github.com/microsoft/vscode-eslint/assets/1699551/9360182c-1073-433c-98a9-8fd0d007582f

I'm not sure if this is actually being caused by the extension or if it has something to do with the extension in combination with the other configurations that are being scaffolded into the project by the Yeoman generator. From what I can tell, it doesn't seem to actually affect the ability to work with the project or use TS/JS Intellisense in VS Code, but the flashing indicator is very distracting.

**Comment by dbaeumer** [comment]
Actually I can not reproduce this behavior. What version of VS Code are you using. I know that there is a change with the status bar item in VS Code which might have caused stuff like that. But that is going to get addressed.


https://github.com/microsoft/vscode-eslint/assets/1931590/7fbdc28c-e188-4385-8a28-2e84b51369bb

**Comment by daedam** [comment]
Okay, thanks for trying. Maybe there is something strange going on with my machine. I'll try another machine and follow up. I am using the latest version of VS Code (1.79), but it was happening on 1.78 as well.

**Comment by dbaeumer** [comment]
Let me know how it goes. And try the latest insider as well if you can.

**Comment by daedam** [comment]
Hi @dbaeumer. I was able to get a new machine up and running, and I am not seeing the same behavior so far on the test repository I sent you while running the latest release build of VS Code. Perhaps there was something about the hardware or software configuration on my older machine that was causing it. In any event, I think you can probably close this issue as not being reproducible. Thanks again for your time and support!

**Comment by dbaeumer** [comment]
@daedam thanks for getting back to me. I will close the issue. If you see it again, ping and we can re-open it.
