### ISSUE TITLE
ESLint autofix doesn't work

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-eslint#1657]
- Open the vscode-remote-ssh repo
- Run "ESLint: Fix all auto-fixable problems"
- Nothing happens, I see this in the output

```
[Info  - 3:47:30 PM] ESLint server is starting.
[Info  - 3:47:31 PM] ESLint server running in node v16.17.1
[Info  - 3:47:31 PM] ESLint server is running.
[Info  - 3:47:39 PM] ESLint library loaded from: /Users/roblou/code/vscode-remote-ssh/open-ssh-remote/node_modules/eslint/lib/api.js
[Error - 3:48:30 PM] Failed to apply command: eslint.applyAllFixes
[Error - 3:50:55 PM] Failed to apply command: eslint.applyAllFixes
```

**Comment by dbaeumer** [comment]
Only happens if there are no problems to fix.

**Comment by roblourens** [comment]
I think at this moment I did have a problem that I was able to fix with a quick action

**Comment by gurlivleenkainth2000** [comment]
The latest version of eslint extension (v3.0.8) in VS Code is not working so i have downgrade the version to last stable version which is 5 months released (v2.4.4).

Getting this error  message "command 'eslint.executeautofix' not found" when trying to run eslint auto-fix command from  vs code command pallete and also tried this command "npx eslint --fix" it also didn't work for me.

**Comment by dbaeumer** [comment]
@gurlivleenkainth2000 I tested it locally and it works for me in my test setup. Can you please provide me with a GitHub repository with a minimal setup I can clone that demos what you are experiencing.

**Comment by cuvar** [comment]
Hi @dbaeumer, I'm experiencing the same issue as mentioned by @gurlivleenkainth2000 in the last comment. Here's a repo for repro: [link](https://github.com/cuvar/vscode-eslint-autotfix). This issue only occurs with the newest version 3.0.8

**Comment by dbaeumer** [comment]
The was a problem with that version on VS Code 1.87. To use the latest version of the extension you need at least 1.90.0
