### ISSUE TITLE
editor.action.formatDocument vs ESLint rules

### ISSUE THREAD

**Issue by czak** [Microsoft/vscode-eslint#166]
I sometimes use `editor.action.formatDocument` (<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>F</kbd>) after cutting/pasting.
I also use ESLint to detect (among others) formatting issues.

I notice these two aren't agreeing on correct formatting.
Here's a demo of <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>F</kbd> introducing ESLint warnings:

![vscode-eslint-format](https://cloud.githubusercontent.com/assets/14021/20003971/ba60eb8a-a289-11e6-8593-fde86bbfc1f3.gif)

Is there a way to make `formatDocument` (or `formatSelection`) respect my ESLint formatting rules?

**Comment by dbaeumer** [comment]
@czak not that I am aware of. To get this working you would need to file an issue against VS Code since the JS/TS formatter would have to respect this.
