### ISSUE TITLE
Support for Globally installed Plugins

### ISSUE THREAD

**Issue by ackava** [microsoft/vscode-eslint#1660]
When trying to use `@typescript-eslint/typescript-eslint`, plugin fails to load when using eslint from global installation.

If there is a simple flag, `useGlobal` in `vscode-eslint` , that will automatically set `--resolve-plugins-relative-to` to the global npm packages.

eslint packages are nearly 100+ MB where else project dependencies are hardly 5 mb, the problem is vscode is also very bulky as it needs to track all the node_modules folders.

**Comment by ackava** [comment]
@dbaeumer

I forgot to mention it in the original issue that `eslint.options` is not working. It is not passing the parameter to eslint and eslint still fails to load plugins.

**Comment by dbaeumer** [comment]
Actually I tested it and setting the value allows me to resolve plugins from different locations and makes the resolving fail when I point it to something that has no plugins installed.

```
	"eslint.options": {
		"resolvePluginsRelativeTo": "../.."
	}
```

You might want to enable `eslint.debug` to see from where it tries to load the plugins.

**Comment by ackava** [comment]
@dbaeumer Loading plugins from relative is not same as loading from the global install. The problem is, we cannot provide platform independent way of global modules location. I can set it to an absolute location, and there are many ways to do it, but it fails on cross platform scenario. Half of developers are on mac and half of them are on windows. The only option we have is to use local installation, which is very heavy.

**Comment by dbaeumer** [comment]
It was not clear to me from the description and `--resolve-plugins-relative-to` pointed me to a wrong direction. 

The underlying issue though you want to see resolved is: https://github.com/microsoft/vscode/issues/2809.

We better solve that issue instead of adding a `useGlobal` setting to the extension.
