### ISSUE TITLE
ESLint extension conflicts/not synced with eslint CLI command

### ISSUE THREAD

**Issue by jeniabrook** [microsoft/vscode-eslint#1669]
It appears that the ESLint extension is not picking up the warning that is displayed in the terminal when running the CLI command.

![Screenshot 2023-06-22 at 12 02 56](https://github.com/microsoft/vscode-eslint/assets/11990241/26fecfdf-6400-43ca-9b94-40a698e1d6a4)

As you can see, running the `lint` command reveals warnings that are not shown in VSCode.

After running the `--fix` flag:
![Screenshot 2023-06-22 at 12 05 02](https://github.com/microsoft/vscode-eslint/assets/11990241/c254fe10-f531-4f9d-813f-3996c2987b33)

VSCode is displaying the same warning as the one shown in the terminal. However, the terminal indicates that everything is fine. After saving the file, VSCode undoes the fix that was applied via the eslint CLI.

Worth to mention that this is a monorepo, with a shared eslint-config, each package has its own `.eslintrc.json` that extends the shared eslint-config.

The linting works well (all other rules applied correctly) except for this issue that I've stumbled upon.

**Comment by jeniabrook** [comment]
Found the problem :)
I needed to add this to my setting.json:

```json
"eslint.workingDirectories": [
    { "pattern": "./apps/*/" },
    { "pattern": "./packages/*/" }
  ]
```

**Comment by fkworld** [comment]
I solve this problem with settings `"eslint.runtime": "node"`.

I guess that the 2 different versions of Node have caused the differences in eslint extension and cli.

### My system node verison
18.19.0

### Without settings `"eslint.runtime": "node"`

eslint extension node version: 20.16.0
![Image](https://github.com/user-attachments/assets/33829a29-b75e-44e1-8952-8d9b760c6f4d)

eslint extension: has error
![Image](https://github.com/user-attachments/assets/24539f83-66b5-4a19-8c41-a868d2847567)

eslint cli: no error
![Image](https://github.com/user-attachments/assets/7cb56d13-3de8-4562-a373-14730928b0d1)

### With settings `"eslint.runtime": "node"`

NOTICE: After add settings `"eslint.runtime": "node"`, need **restart vscode**, restart eslint server not working.

eslint extension node version: 18.19.0
![Image](https://github.com/user-attachments/assets/08e05b09-f07a-4e9b-8ae5-ba58a7967a4f)

eslint extension: no error
![Image](https://github.com/user-attachments/assets/a850f488-06c4-4847-9763-6d057aa88acd)

eslint cli: no error
