### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Bhabatosh077** [microsoft/vscode-eslint#1670]
- Issue Type: `Performance`
- Extension Name: `vscode-eslint`
- Extension Version: `2.4.2`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.79.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/BHABAT~1/AppData/Local/Temp/dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by dbaeumer** [comment]
@Bhabatosh077 do you still have the CPU profile at file:///c%3A/Users/BHABAT~1/AppData/Local/Temp/dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt. Without it is is very hard to tell what is going on.
