### ISSUE TITLE
ESLint server stopped in VSCode DevContainer

### ISSUE THREAD

**Issue by ArnaudDusseldorp** [microsoft/vscode-eslint#1672]
Using this extenstion, ESLint stop working: With the following error:
[Info  - 8:46:46 AM] ESLint server is starting.
[Info  - 8:46:47 AM] ESLint server running in node v16.17.1
[Info  - 8:46:48 AM] ESLint server is running.
[Info  - 8:46:50 AM] ESLint library loaded from: /workspaces/xxx/node_modules/eslint/lib/api.js

<--- Last few GCs --->

[652:0x4e60de0]    28495 ms: Scavenge (reduce) 2045.3 (2082.5) -> 2045.0 (2082.5) MB, 5.4 / 0.0 ms  (average mu = 0.437, current mu = 0.389) allocation failure 
[652:0x4e60de0]    29260 ms: Mark-sweep (reduce) 2047.2 (2084.0) -> 2046.7 (2084.3) MB, 716.5 / 0.0 ms  (+ 306.8 ms in 80 steps since start of marking, biggest step 5.2 ms, walltime since start of marking 1117 ms) (average mu = 0.293, current mu = 0.192) 

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb02960 node::Abort() [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
 2: 0xa18149 node::FatalError(char const*, char const*) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
 3: 0xcdd22e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
 4: 0xcdd5a7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
 5: 0xe94c15  [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
 6: 0xea48dd v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
 7: 0xea75de v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
 8: 0xe68852 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
 9: 0xe6316c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
10: 0xe63245 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
11: 0x10cbace v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
12: 0x10cbb83 v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
13: 0x11d7cb5 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
14: 0x15d54f9  [/vscode/vscode-server/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node]
[Info  - 8:47:17 AM] Connection to server got closed. Server will restart.

How to extend the memory of NODE.JS running in a DevContainer?

**Comment by dbaeumer** [comment]
There is a setting that you can use to control the heap size for the ESLint server. It is `eslint.execArgv` and the documentation shows how to increase the heap size (https://github.com/microsoft/vscode-eslint/blob/main/README.md).
