### ISSUE TITLE
ESLint shows false errors for several seconds/minutes while "lagging" behind latest input

### ISSUE THREAD

**Issue by dancherb** [microsoft/vscode-eslint#1676]
While typing code - for example, in the middle of a word or line - ESLint will show an error. For example, for the following input:

`const { name } =`

However, when I've finished typing this line a fraction of a second later, the error from ESLint sometimes persists and it shows a false positive. This can last for several seconds to several minutes while ESLint appears to "catch up" or stop freezing. A perfectly fine line will show with an error, for example:

`const { name } = req.body`

This currently makes ESLint unusable, as you're never sure when an error is actually being shown and when you can actually trust ESLint. 

This error appeared to start in the last couple weeks (late June).

Appreciate any help!

**Comment by dbaeumer** [comment]
@dancherb without steps on how to reproduce this very hard to say. Would you be able to destille steps in a GitHub repository I can clone?

What we can try as well is to see if enabling debugging on eslint itself will help. You can do so by `"eslint.debug": true` in the settings. This will print debug information into the ESLint output console. When the hang happens can you capture the trace?

**Comment by dancherb** [comment]
I tried various solutions suggested in GitHub/StackOverflow threads describing the issue, and found that installing typescript as a dev dependency (even if my project doesn't use typescript) seems to have resolved the issue

**Comment by dbaeumer** [comment]
Closing the issue then.
