### ISSUE TITLE
eslint error on big json file (nextjs)

### ISSUE THREAD

**Issue by LupuC** [microsoft/vscode-eslint#1677]
How can I disable ESlint for a specific .json file in nextjs app?
I've tried to create a file .eslintignore, to add in .eslintrc.json, in tsconfig.json and none of them seems to work. The error is:
```bash
./folder/jsonfile.json:1:2754821
Type error: Property value can only be string literal, numeric literal, 'true', 'false', 'null', object literal or array literal.
```
The json is in format:
```json
{"idlist":{"ids":[
{"id":1234,"name":"name here"},
{"id":234,"name":"name here"},
{"id":552,"name":"name here"}
```

and I import it inside a page, like this:
```js
import idlist from "@/folder/jsonfile.json"
```

Note that the file is pretty big (like 8MB of data).

edit, what I have tried:

.eslintignore with:

```
folder/*.json
folder/**.json
folder/
folder/jsonfile.json
/folder/
/folder/jsonfile.json
folder/*
folder/**

```

adding ```/* eslint-ignore */``` at the top of the json file

adding to package.json eslint like here https://eslint.org/docs/latest/use/configure/ignore

**Comment by MariaSolOs** [comment]
Are you sure that error is coming from ESLint? It looks like it's from the JSON language server because of an invalid value according to the document's schema...

**Comment by LupuC** [comment]
yes, it is from ESLint when I try to build a nextjs app. Couldn't it be because the json file is too big? (like 8mb of data)

**Comment by dbaeumer** [comment]
@LupuC does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by LupuC** [comment]
so, basically, if I ran `pnpm run lint` i had no errors.. that makes me think it wasn't from the lint... but when I ran `pnpm run build`, the linting process was being stopped with the error from above. Anyways, I moved the json to the api, and now everything works perfect! Thank you for wanting to help me.

**Comment by dbaeumer** [comment]
Great to hear you got it working. I will close the issue.
