### ISSUE TITLE
eslint options to resolve extends config and parser paths

### ISSUE THREAD

**Issue by navateja-alagam** [microsoft/vscode-eslint#1678]
Hi, I have a use-case to resolve the third party packages of extend configs, plugins, parser etc. used in my`.eslintrc.json` file from a different resolution path than the VSCode's workspace 'node_modules'.

our .eslintrc.json config looks something like below:
```
    plugins: [
        '@sfdc-internal/lwc-core',
        'eslint-comments',
    ],
    extends: [
        '@salesforce/eslint-config-lwc/recommended',
        '@locker/eslint-config-locker/base',
    ],

    parser: "@babel/eslint-parser",
```

I found an option for plugins i.e., via `resolvePluginsRelativeTo` from the [list of eslint options ](https://eslint.org/docs/latest/integrate/nodejs-api#parameters) available for vscode-eslint.  But don't see a way to modify the resolve path for the config from `extends` and `parser` configurations from above.

changes in settings.json:
```
{
    ...otherSettings,
    "eslint.options": {
        "resolvePluginsRelativeTo": "<some_other_path_where_plugins_can_be_resolved>"
    }
}
```

The above changes helps me to resolve the `plugins` config to point to the other path I mentioned in settings.json however looking for an option to modify 'extends & parser' configs too.

**Comment by dbaeumer** [comment]
How do you achieve this when running eslint from the terminal. The extension only offers features that are also available in eslint itself.

**Comment by navateja-alagam** [comment]
Ah, gotcha.  I'll check with [ESLint](https://github.com/eslint/eslint).  Thanks for the prompt reponse.
