### ISSUE TITLE
ESLint Not Working 

### ISSUE THREAD

**Issue by egucciar** [Microsoft/vscode-eslint#168]
I've been working with a few people using this extension and it's inexplicably "not working" in two people's code editors (It was working then it stopped). We went through basic steps, reinstalling, restarting, enabling/disabling, and nothing seems to work. But I'm not sure what other troubleshooting steps I could take to "force" it to work? Please let me know.

EDIT: 5 other people using the same project and it works fine, so thats why its in explicable
EDIT2: "not working" - no linter errors are appearing even though we know they should be

**Comment by dbaeumer** [comment]
@egucciar There is a ESLint output channel. You can open it using Vies > Output and the switch to the ESLint channel using the drop down (you need to open a JS file first to activate ESLint). Is there any error information in the channel.

If not you can enable eslint tracing using `"eslint.trace.server": "verbose"`. This will print a verbose log to the output channel. Can you attach the log here?

**Comment by dbaeumer** [comment]
Closing the issue. Will reopen when the requested information is available.
