### ISSUE TITLE
Eslint did not prompt

### ISSUE THREAD

**Issue by MsBeiBei** [microsoft/vscode-eslint#1681]
I am trying to use eslint. config.js to configure the rules. In package. json, I used type: "module", but vscode eslint did not give me any prompt. Using the command line actually takes effect, and I don't know how to do it to be prompted

![image](https://github.com/microsoft/vscode-eslint/assets/133855318/b2299953-0461-44a8-b26e-7b7fdc539101)

"eslint": "^8.45.0",
 "eslint-plugin-vue": "^9.15.1"

vs-code eslint v2.4.2 

The relevant code can be viewed here
https://github.com/MsBeiBei/ANADI.git
script\copyright

**Comment by MsBeiBei** [comment]
![image](https://github.com/microsoft/vscode-eslint/assets/133855318/d510beba-f090-43a8-97c2-b72f2400bf16)

**Comment by dbaeumer** [comment]
You need to configure eslint in the workspace since npx only installs it for single runs. You best follow the steps for the normal ESLint setup here: https://eslint.org/
