### ISSUE TITLE
Remote Extension Host closing on Github Codespaces

### ISSUE THREAD

**Issue by josephzidell** [microsoft/vscode-eslint#1682]
Thank you for creating this wonderful extension. I've been using it on VS Code for a long time, and I love it. It's really useful.

Recently I began using Github codespaces, and found that the Remote Extension Host kept on closing, to the point that VS Code was unusable.

Things I've tried:
- Having no extensions enabled. VSCode works fine.
- Enabling only this extension. Breaks.
- Enabling a different extension (tried several, one by one as well as together). VSCode works fine.
- Restarting the Extension Host (multiple times). Same issue
- Restarting the codespace. Same issue
- Rebuilding the codespace. Same issue

If there's anything I can do to provide more info, please let me know.

Thanks for maintaining this extension. 🍻

**Comment by dbaeumer** [comment]
Do you have any steps to reproduce this. Could I clone the code space ?

And anything special in the `Extension Host (Remote)` output channel.

**Comment by josephzidell** [comment]
Sure, you can clone the codespace. It's an open source repo. https://github.com/josephzidell/joelang

I didn't notice anything special in that output channel.

**Comment by josephzidell** [comment]
It seemed to happen more in the browser. I'll try to get a screen video recording
