### ISSUE TITLE
ES Lint not working properly with enters and if else

### ISSUE THREAD

**Issue by abhinavjain1607** [Microsoft/vscode-eslint#169]
This was the piece of code before:
**The if else is not aligned properly**

if(this.props.selected) {
	image = LeadsSelectedImages[this.props.action.actionKey];
}
else {
	image = LeadsNotSelectedImages[this.props.action.actionKey];
}

## After linting, it comes to this.
Here, the tabs before else is not proper. Please look after this :)

if (this.props.selected) {
	image = LeadsSelectedImages[this.props.action.actionKey];
}		else {
	image = LeadsNotSelectedImages[this.props.action.actionKey];
}

**Comment by abhinavjain1607** [comment]
The else in the comment is not what came after linting: 
It was like  [tab][tab]else
the tabs were taken from the next line

**Comment by dbaeumer** [comment]
@abhinavjain1607 can you share a workspace / git repository showing the behavior. Do you have auto fix on save enabled ?

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
