### ISSUE TITLE
Support probing for .graphql files

### ISSUE THREAD

**Issue by pn-wiseverge** [microsoft/vscode-eslint#1692]
node version: v18.17.0
eslint extension version: v2.4.2

VSCode Eslint configs:
```
{
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
    "eslint.enable": true,
    "eslint.format.enable": true,
    "files.insertFinalNewline": true,
    "eslint.probe": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "html",
        "vue",
        "markdown",
        "graphql"
    ],
    "eslint.debug": true,
    "[graphql]": {
        "editor.defaultFormatter": "dbaeumer.vscode-eslint"
    },
}
```

`.graphqlconfig`
```
{
  "name": "GraphQL Schema",
  "schema": ["./src/graphql/**/*.graphql"]
}
```

`.eslintrc.cjs`
```
module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:import/typescript',
    'plugin:prettier/recommended',
    'prettier',
  ],
  overrides: [
    {
      files: ['.eslintrc.{js,cjs}'],
      env: {
        node: true,
      },
      parserOptions: {
        sourceType: 'script',
      },
    },
    {
      files: ['*.graphql'],
      extends: ['plugin:@graphql-eslint/schema-recommended'],
      parserOptions: {
        schema: './src/graphql/schema.graphql',
      },
    },
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint', 'import', 'prettier'],
  rules: {},
};
```

### Problem
If I run `yarn eslint .` I get graphql errors. But VSCode do not show those errors on `.graphql` files.

`yarn eslint .` result:
```
yarn lint
yarn run v1.22.19
$ yarn eslint .
$ [PROJECT_FOLDER]/node_modules/.bin/eslint .

[PROJECT_FOLDER]/src/graphql/models/book.graphql
  1:6  error  Description is required for type "Book"  @graphql-eslint/require-description
  4:3  error  Replace `···id:·ID!` with `id:·ID!⏎`     prettier/prettier
  5:1  error  Delete `·`                               prettier/prettier

[PROJECT_FOLDER]/src/graphql/schema.graphql
  3:6  error  Description is required for type "Query"  @graphql-eslint/require-description

✖ 4 problems (4 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

VSCode graphql file (left) and typescript file (right) with working ESLint extension:
![Screenshot 2023-08-01 at 13 33 34](https://github.com/microsoft/vscode-eslint/assets/95299737/047edc80-7ae3-4102-b52f-94f9f9f30bfc)

Reproducible code: https://github.com/pn-wiseverge/vscode-eslint-graphql-test

**Comment by dbaeumer** [comment]
The reason for this is that there is no probing support for `graphql`. You can however force the validation by adding the following setting:

```
    "eslint.validate": [
        "graphql"
    ]
```

**Comment by pn-wiseverge** [comment]
> The reason for this is that there is no probing support for `graphql`. You can however force the validation by adding the following setting:
> 
> ```
>     "eslint.validate": [
>         "graphql"
>     ]
> ```

Between all the tries I did, I messed with `eslint.validate` with current languages and `graphql` and it didn't worked. But just `grapgql` in it did the trick! Many thanks 💪

**Comment by unicornware** [comment]
@dbaeumer 

does updating `eslint.validate` only work when using actual graphql files (`*.(gql|graphql)`)?

i'm using [`gql` from `graphql-tag`][1] and this workaround does not seem to apply.

[1]: https://github.com/apollographql/graphql-tag

**Comment by dbaeumer** [comment]
@unicornware you need to add the `language id` that is associated with file type to the `eslint.validate` section. I actually don't know if this is the same one for your file type. Do you use an extension to support these files. They usually tell you which language id they associated with it.

**Comment by vdhpieter** [comment]
> The reason for this is that there is no probing support for `graphql`. You can however force the validation by adding the following setting:
> 
> ```
>     "eslint.validate": [
>         "graphql"
>     ]
> ```

@dbaeumer I added this to my config but I still don't see errors/warnings in my `.graphql` file. Any idea how to troubleshoot this?

**Comment by dbaeumer** [comment]
@vdhpieter do you have an extension installed that contributes the `graphql` language ?

**Comment by vdhpieter** [comment]
@dbaeumer yes, this one: https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql

**Comment by dbaeumer** [comment]
Can you provide me with a GitHub repository I can clone with a minimal setup that demos this. Then I can have a look.
