### ISSUE TITLE
VSCode isn't recognizing my angular global

### ISSUE THREAD

**Issue by zachlysobey** [Microsoft/vscode-eslint#17]
This is starting to drive me a bit nuts.

v 0.10.11

![screen shot 2016-01-05 at 11 50 37 am](https://cloud.githubusercontent.com/assets/1310403/12121293/8a05872e-b3a2-11e5-89de-d37ac687cd7f.png)

.eslintrc
```json
...
"globals": {
    "angular": false
}
```

**Comment by egamma** [comment]
There is also built-in JavaScript linter. You can disable it as follows:
```json
	"javascript.validate.enable": false
```
