### ISSUE TITLE
${env:HOME} environment variable not recognized

### ISSUE THREAD

**Issue by diamond-fish** [microsoft/vscode-eslint#1701]
I have this setting:

```
    "eslint.options": {
        "overrideConfigFile": "${env:HOME}/.eslintrc.json"
    },
```

However, ESLint extension for VS Code doesn't seem to recognize this environment variable because I see this in the output log:

```
Uncaught exception received.
Error: Cannot read config file: C:\path\to\current\working\directory\${env:HOME}\.eslintrc.json
Error: ENOENT: no such file or directory, open 'C:\path\to\current\working\directory\${env:HOME}\.eslintrc.json'
```

The `HOME` environment variable points to `%USERPROFILE%/home`.

My setup:
- ESLint for VS Code v2.4.2.
- ESLint v8.47.0

UPDATE: The error above went away after changing the `overrideConfigFile` value to an absolute path, so this appears to confirm that VS Code variables are not supported in `overrideConfigFile`.

**Comment by dbaeumer** [comment]
VS Code has currently no support to resolve variable in settings hence they don't work in ESLint either. VS Code has an issue to provide that support. 

I will close the issue since it makes not much sense to implement a custom support for ESLint.
