### ISSUE TITLE
.eslintrc file external to project

### ISSUE THREAD

**Issue by maraisr** [Microsoft/vscode-eslint#171]
I have a npm repo package that contains all my linting configs, styleint, eslint etc... It would be kinda nice to be able to set a config in my current workspace to grab the config from a file you can specify. 

Something like 

```json
"eslint.configFile": "./node_modules/code-standards/eslint/.eslintrc"
```

**Comment by tajinderbirdi** [comment]
You can do this with something like:

`"eslint.options": {
    "configFile": "C:/mydirectory/eslintrc"
}`

And you can apply any of the other settings as defined in the CLIEngine
http://eslint.org/docs/developer-guide/nodejs-api#cliengine

**Comment by maraisr** [comment]
Thanks @tajinderbirdi appreciate your feedback. Do you think we can add this into the `readme.md`?

**Comment by dbaeumer** [comment]
@tajinderbirdi thanks for pointing this out. Added your example to the readme.md
