### ISSUE TITLE
Yarn PnP with vscode-eslint set to flat config not producing errors or outputs

### ISSUE THREAD

**Issue by Swiftwork** [microsoft/vscode-eslint#1710]
### Steps to reproduce

1. `yarn init -2`
1. `yarn add -D eslint`
1. add extensions `vscode-eslint`
1. `yarn dlx @yarnpkg/sdks vscode`
1. set `"eslint.experimental.useFlatConfig": true` in `.vscode/settings.json`
1. create `eslint.config.js` file with basic rules
1. create `test.js` file breaking rules
1. `yarn dlx eslint .` observe errors
1. `vscode-eslint` only outputs

   ```
   [Info  - 20:04:53] ESLint server is starting.
   [Info  - 20:04:53] ESLint server running in node v18.15.0
   [Info  - 20:04:53] ESLint server is running.
   ```
### Reproduction

https://github.com/Swiftwork/eslint-flat-pnp-test

### Versions

```
eslint: 8.50.0
yarn: 3.6.3
eslint-yarn-sdk: 8.50.0-sdk
vscode-eslint: 2.4.2
```

**Comment by dbaeumer** [comment]
The reason for this is that flat config is still experimental and loading eslint requires to load `eslint/use-at-your-own-risk`. See the eslint package.json

```
  "exports": {
    "./package.json": "./package.json",
    ".": "./lib/api.js",
    "./use-at-your-own-risk": "./lib/unsupported-api.js"
  },
```

However the `yarn dlx @yarnpkg/sdks vscode` doesn't seem to set this up correctly hence the eslint extension doesn't find `eslint/use-at-your-own-risk`.

There is nothing the extension can do about it. You might want to consider open an issue against yarn.

**Comment by Swiftwork** [comment]
@dbaeumer Thanks. I thought that might be the case. Also found this https://github.com/yarnpkg/berry/pull/5471 for future reference.
