### ISSUE TITLE
vue+vite+ts 使用vscode 的 eslint插件初始化eslint生成文件后出现错误

### ISSUE THREAD

**Issue by shuaidaipeng** [microsoft/vscode-eslint#1715]
Parsing error: import_typescript.default.isTokenKind is not a function

![image](https://github.com/microsoft/vscode-eslint/assets/45552232/e1954f84-371c-4ae8-8d52-572efab94765)
![image](https://github.com/microsoft/vscode-eslint/assets/45552232/683ec335-484d-4781-b0bc-7862c6ebb945)

**Comment by dbaeumer** [comment]
Does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by shuaidaipeng** [comment]
刚刚我重新生成了初始项目，发现我的初始项目是js语法不是ts ，而eslint选择了ts语法，大概率是因为这个原因导致报错了
