### ISSUE TITLE
Lightbulb/autofix not appearing for all linting errors

### ISSUE THREAD

**Issue by jhjdesigns** [Microsoft/vscode-eslint#172]
I've noticed that the lightbulb is no longer showing up for some errors. A week ago, it was popping up for everything, now it's only showing up for certain errors. Specifically, I'm not seeing it for comma-dangle or padded-blocks. Is this a bug, or is there some new setting I'm missing?

**Comment by dbaeumer** [comment]
@jhjdesigns no new setting and it works for me. Can you share the project or a reproducible setup so that I can investigate.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
