### ISSUE TITLE
Unknown options: Cannot add eslint rules in vscode setting.json

### ISSUE THREAD

**Issue by xuyaqist** [microsoft/vscode-eslint#1722]
When I tried to add eslint rules in vscode setting.json, it will gives this error. 
```
[Error - 09:57:50] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Invalid Options:
- Unknown options: eslint.options
  Code: -32603 
Uncaught exception received.
Error: Invalid Options:
- Unknown options: eslint.options
```

My setting.json:

```
  "eslint.options": {
    "lines-between-class-members": [
      "error",
      "always"
    ]
  },
```

p.s
1. when I cover "lines-between-class-members" with "rules", it's also not working.
2. when I cover "rules" with "overrideConfig", it's also not working.

**Comment by dbaeumer** [comment]
The `eslint.options` setting is not meant to allow to add rules. They still need to  be defined in the normal eslint config files. The option setting is to pass options to the linter that are typically passed on the command line. See here for valid values: https://eslint.org/docs/latest/integrate/nodejs-api#-new-eslintoptions
