### ISSUE TITLE
vscode fails to load the semistandard library

### ISSUE THREAD

**Issue by dhowe** [microsoft/vscode-eslint#1723]
Get "Failed to load the semistandard library." error when trying to use the 'vscode-semistandard' extension: https://marketplace.visualstudio.com/items?itemName=flet.vscode-semistandard

It remains after following instructions and installing npm globally (version 8.19.1) install

```
[Info  - 16:15:48] Failed to load the semistandard library.
To use semistandard in this workspace please install semistandard using 'npm install semistandard' or globally using 'npm install -g semistandard'.
You need to reopen the workspace after installing semistandard.
```

vscode:
```
Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 20.6.0
```

**Comment by dbaeumer** [comment]
@dhowe please report the problem against the developer of the semistandard extension. This repository is for issues with the ESLint extension.
