### ISSUE TITLE
color control characters visible

### ISSUE THREAD

**Issue by davidcoleman007** [microsoft/vscode-eslint#1726]
Type: <b>Bug</b>

when we are hovering over a highlighted lint error, on windows, i see these bash control characters in my error readout, as though they were escaped instead of parsed as colors.

we should show these colors and not the codes.

![image](https://github.com/microsoft/vscode-eslint/assets/41075/0a962f9a-1b72-47c1-a852-f18192c886bd)

Extension version: 2.4.2
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11980HK @ 2.60GHz (16 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (36.18GB free)|
|Process Argv|. --crash-reporter-id d8d9b7bf-ea05-4e4f-bddd-e38795583b25|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2cf:30871583
pyreplss1:30865275
pythoncet00cf:30874137
pythontbext0:30864172

```

</details>

**Comment by dbaeumer** [comment]
@davidcoleman007 can you provide me with a GitHub repository I can clone and steps how to reproduce this?

**Comment by davidcoleman007** [comment]
This only seems to happen on windows, when integrated with git bash. It appears that we get the control chars from stdout rendered as text and not colors.

This occurs pretty frequently for some internal repos I work with here at Adobe, I can try to construct a public repo that will produce it reliably but i do not have one available to share.

If there's some code path where these chars should have been handled and colorized in the tooltip, then maybe a quick fix can be to strip them out if they are not colorized correctly... then we can at least read the text...

**Comment by dbaeumer** [comment]
Are you running an ESlint validate task as well?

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
