### ISSUE TITLE
Error: Cannot read config file: X:\package.json

### ISSUE THREAD

**Issue by jaganathanb** [Microsoft/vscode-eslint#173]
I am using eslint with VS Code
* **ESLint Version:** 3.10.2
* **Node Version:** 5.4.1
* **npm Version:** 3.3.12
* **VS Code Version:** 1.7.2

**What parser (default, Babel-ESLint, etc.) are you using?** Default

**Please show your full configuration:**
.eslintrc from [here](https://gist.github.com/cletusw/e01a85e399ab563b1236)

**What did you do? Please include the actual source code causing the issue.**
Nothing. Installed eslint and using with VS Code.

**What did you expect to happen?**
It should lint the js file.

**What actually happened? Please include the actual, raw output from ESLint.**
Its not linting the js file.
```
[Info  - 11:36:58 AM] ESLint server is running.
[Info  - 11:37:00 AM] ESLint library loaded from: X:\path-to-source\Source\node_modules\eslint\lib\api.js
[Error - 11:37:03 AM] Cannot read config file: X:\package.json Error: Cannot read config file: X:\package.json Error: Unexpected token : in JSON at position 9

```
ESLint looks for `package.json` at root of the drive `X:`. But it should look at `X:\path-to-source\Source`.

**Comment by dbaeumer** [comment]
@jaganathanb what happens if you run eslint from a terminal on your source code. ESLint (the limiting tool itself and not the extension) walks up the directory chain to look for configuration files. Since eslint configuration can be put inot package.json files it looks into those as well and fails to read it in your case. This is standard eslint behavior. Have you checked the package.json file. Does it have invalid tokens

**Comment by jaganathanb** [comment]
Thanks for the update. It seems to be eslint issue. I could not run it from CLI.

```
$ eslint app/**
Cannot read config file: X:\package.json
Error: Cannot read config file: X:\package.json
Error: Unexpected token :
SyntaxError: Cannot read config file: X:\package.json
Error: Cannot read config file: X:\package.json
Error: Unexpected token :
    at Object.parse (native)
    at loadJSONConfigFile (A:\Users\aaa\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:120:21)
```

**Comment by dbaeumer** [comment]
Closing then since there is nothing the extension can do about it other than surfacing the issue.
