### ISSUE TITLE
Warning in default ESLint settings: Null must be declared as a valid type

### ISSUE THREAD

**Issue by padamson** [Microsoft/vscode-eslint#174]
From [Microsoft/vscode#2856](https://github.com/Microsoft/vscode/issues/2856).

I have a warning in the status bar.

![eslint_warning](https://cloud.githubusercontent.com/assets/5460406/20625673/d8e8d72a-b2e2-11e6-8ee8-f34e3e034a07.jpg)

To fix this, add 'null' as valid type of the setting
e.g.

```
"eslint.nodePath": { 
          "type": ["string", "null"], 
          "default": null, 
          "description": "A path added to NODE_PATH when resolving the eslint module." 
      },
```

**Comment by dbaeumer** [comment]
Fixed in next version.
