### ISSUE TITLE
There are some issues with the rules @stylistic/arrow-parens and @stylistic/space-before-function-paren when running in the ESLint plugin for VSCode 

### ISSUE THREAD

**Issue by helloskynet** [microsoft/vscode-eslint#1745]
with the rules @stylistic/arrow-parens and @stylistic/space-before-function-paren in ESLint Plugin for VSCode

Origin Code
```js
// index.js
const m = async (id) => {
  return await Promise.resolve(id)
}
console.log(m)
```
Result
```js
const m = asyncid => {
  return await Promise.resolve(id)
}
console.log(m)
```

async (id) ------> asyncid

It' Ok with `eslint --fix index.js`，

Reproduction

https://stackblitz.com/~/github.com/helloskynet/eslint-p

![ezgif-2-1d87c08cb8](https://github.com/eslint-stylistic/eslint-stylistic/assets/15828275/2d0a0eb4-47fc-4530-a718-ebacb8b3fe49)

**Comment by dbaeumer** [comment]
Fixed
