### ISSUE TITLE
Why not integrate version 2.4.2 into the main branch?

### ISSUE THREAD

**Issue by sochi419** [microsoft/vscode-eslint#1746]
I am using version `2.4.2` of ESLint, but version `2.4.2` is not included in the release notes of the main branch. Is there a reason for this?

# main branch
<img width="1059" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/a4503b52-bad1-4521-9a91-63d2b8477b7a">

There is no mention of version `2.4.2` in the release notes for the main branch.

# `release/2.4.2 branch`
<img width="1038" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/8957401f-7f29-4b3e-a31f-b896cb6624f9">

The release notes for the `release/2.4.2` branch have information about version `2.4.2.`
Why not merge the `release/2.4.2` branch into the main branch?

**Comment by dbaeumer** [comment]
Fixed in main.

**Comment by sochi419** [comment]
Thank you.
