### ISSUE TITLE
ESLint client: couldn't create connection to server.

### ISSUE THREAD

**Issue by chrispalmo** [microsoft/vscode-eslint#1754]
# Issue Summary for vscode-eslint

## Error Description
While using the ESLint extension in VSCode, the following errors are encountered:

- ESLint server starts and stops immediately.
- Error message: "couldn't create connection to server."
- Issue with launching server using runtime node: "Error: spawn node ENOENT."

```
[Info  - 12:28:41] ESLint server is starting.
[Info  - 12:28:41] ESLint server stopped.
[Error - 12:28:41] ESLint client: couldn't create connection to server.
Launching server using runtime node failed. Error: spawn node ENOENT
[Error - 12:28:41] Starting the server failed.
Launching server using runtime node failed. Error: spawn node ENOENT
[Info  - 12:28:41] PATH environment variable is: /usr/bin:/bin:/usr/sbin:/sbin
```

## Diagnostic Information
- MacOS Sonoma 14.2 (23C64), Apple M1 Max
- Node.js version: v18.18.2
- Location of Node.js: `/Users/cp/.npm/bin/node`

## Steps Taken to Resolve
1. **Node.js Installation Verification:** Confirmed Node.js is installed and accessible via PATH.
2. **Updated PATH Variable:** Verified Node.js path is included in the system's PATH.
3. **VSCode Settings for ESLint:**
   - Tried various configurations for `eslint.nodePath` including empty, specific path and null.
4. **Reinstall ESLint Extension:** Uninstalled and reinstalled the ESLint extension without resolution.
5. **Check and Update Node Version:** Using `n`, updated and verified the Node version.
6. **ESLint Runtime Path Setting:** Attempted setting `eslint.runtime` to the path of the Node executable.
7. **User Settings Configuration:** Tested with different configurations in VSCode user settings.
8. **Permissions Check:** Verified permissions for Node binary and relevant directories.
9. **Direct Execution in VSCode Terminal:** Confirmed ability to run Node via VSCode terminal.
10. **Setting `eslint.runtime` to Null:** Tried explicitly setting `eslint.runtime` to null.
11. **Permissions and Configuration:**
  - Explored the possibility of permission issues with the Node binary and relevant directories.
  - Checked and confirmed proper read/write/execute permissions.
  - VSCode user configuration was modified and tested in various states, including removing all properties, without resolving the issue.

## Additional Context
- The Node.js installation was managed using `n` (version 8.2.0).
- Fresh installation of VSCode
- Potential issues with permission settings or VSCode user configuration were discussed but remain unresolved.

## Conclusion
The issue seems to be a complex interaction between the VSCode ESLint extension, Node.js installation, and possibly VSCode's access to system variables or user settings. Despite multiple troubleshooting steps, the problem persists, indicating a need for direct intervention or guidance from the VSCode or vscode-eslint development team.

**Comment by tomasz-clipchamp** [comment]
I had the same issue, I managed to fixed it.

The problem is that ESLint does not use the terminal of your default choice and rather is using cmd (on windows/WSL), so while I was using node with Bash/Git for Windows via NVM. cmd didn't have access to node command

hence you get `spawn node ENOENT` error, as the default ESLint terminal doesn't recognize `node` command

The fix was really simple, you can do 1 of the 2 solutions:

1. install of node.exe via installation file rather than just using NVM
2. update PATH environment to point to .nvm/xxx folder where node command exist

please let me know if that works for you

**Comment by dbaeumer** [comment]
Alternatively you can start VS Code from a command prompt which setups NVM correctly. And another question is why do you need a special node version to be used. Does the default provided by VS Code not work for you?

@chrispalmo let me know if that helps.

**Comment by chrispalmo** [comment]
Just updated diagnostic info -- I’m using a Mac, MacOS Sonoma 14.2 (23C64), Apple M1 Max.

**Comment by chrispalmo** [comment]
> why do you need a special node version to be used

I don't, any version that works will do

> Does the default provided by VS Code not work for you?

I don't quite understand what "default provided by VS Code" means. Does vscode ship with a builtin node runtime? If so, the extension doesn't seem to be finding it (it seems to be looking in `/usr/bin:/bin:/usr/sbin:/sbin`).

I don't necessarily need a special version.  use `n` to manage node installations, and they live in `/Users/cp/.npm/bin/node`

**Comment by dbaeumer** [comment]
@chrispalmo you somewhere set `eslint.runtime` to `node` which then force the client to look for that executable to launch the server. Simply remove that setting and the extension will use the node version that ships with VS Code.

**Comment by chrispalmo** [comment]
In system `Terminal` app:

```
cp ~  $ which node
/Users/cp/.npm/bin/node
```

In file `~/Library/Application Support/Code/User/settings.json`:

1. comment out all existing settings
2. add `"eslint.runtime": "/Users/cp/.npm/bin/node",`

Result same as before (on restarting VSCode and opening a project):

<img width="470" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/34981948/dc4e99de-7a7f-4114-b4c7-65889e410cf5">

```
[Info  - 11:10:07] ESLint server is starting.
[Info  - 11:10:07] ESLint server stopped.
[Error - 11:10:07] ESLint client: couldn't create connection to server.
Launching server using runtime node failed. Error: spawn node ENOENT
[Error - 11:10:07] Starting the server failed.
Launching server using runtime node failed. Error: spawn node ENOENT
[Info  - 11:10:07] PATH environment variable is: /usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by dbaeumer** [comment]
Something seems of with your settings. If you setup a `eslint.runtime` and that runtime isn't found then it should print that path in the output channel and not simply `node`. In the screen shot below I set `eslint.runtime` to `/tmp/node` and here is what is printed to the output channel

```
[Info  - 10:48:59 AM] ESLint server is starting.
[Info  - 10:48:59 AM] ESLint server stopped.
[Error - 10:48:59 AM] ESLint client: couldn't create connection to server.
Launching server using runtime /tmp/node failed. Error: spawn /tmp/node ENOENT
[Error - 10:48:59 AM] Starting the server failed.
Launching server using runtime /tmp/node failed. Error: spawn /tmp/node ENOENT
[Info  - 10:48:59 AM] PATH environment variable is: <remove due to PII>
```

**Comment by chrispalmo** [comment]
Got it. 

Someone added `"eslint.runtime": "node"` to the repo root level `.vscode/settings.json`, and this was taking precedence over user settings. Interesting that this wasn't reportedly causing any issues for other devs.

Deleting the property from `.vscode/settings.json` resolved the issue.

Thanks Dirk for helping me figure this out :)

**Comment by chrispalmo** [comment]
The bit I still don't understand, which stopping me from arriving at a long term solution fix (that doesn't involve breaking the plugin for for every other dev working on the project) is why `"eslint.runtime": "node"` doesn't resolve as expected:

In both the system terminal, and in the vscode terminal:
```
$ which node
/Users/cp/.npm/bin/node
$ node -v
v18.18.2
```

Whereas directly setting
```
"eslint.runtime": "/Users/cp/.npm/bin/node"
```

Works fine.

**Comment by chrispalmo** [comment]
The bit I still don't understand, which stopping me from arriving at a long term solution fix (that doesn't involve breaking the plugin for for every other dev working on the project) is why `"eslint.runtime": "node"` doesn't resolve as expected:

In both the system terminal, and in the vscode terminal:
```
$ which node
/Users/cp/.npm/bin/node
$ node -v
v18.18.2
```

Setting `"eslint.runtime": "node"` is having issues, whereas directly setting
```
"eslint.runtime": "/Users/cp/.npm/bin/node"
```

Works fine.

**Comment by chrispalmo** [comment]
related: https://github.com/microsoft/vscode-eslint/issues/1233#issuecomment-815521280

**Comment by chrispalmo** [comment]
As I seem to be the only person in the org experiencing this issue, the workaround I have been using is to delete `.vscode/settings.json` from `.vscode/settings.json`, and then `git update-index --assume-unchanged .vscode/settings.json`. This help prevent me from accidentally committing the change in unrelated prs, however can can make switching between branches tedious because I still need to remember to go back and manually revert the change before changing branches - so not a great long-term solution.

With my limited understanding of how vscode plugins work, I'm unsure if it would make sense for me to also open an issue with https://github.com/microsoft/vscode. Thoughts @dbaeumer?

**Comment by dbaeumer** [comment]
@chrispalmo can you try to start VS Code from a terminal where `which node` resolve to a node version. Looks like VS Code doesn't source the environment correctly which results in not finding node on the PATH.

**Comment by chrispalmo** [comment]
Running `code` from from a terminal with `node` in the PATH resolved the issue. Thanks @dbaeumer!

**Comment by karlhorky** [comment]
This crash is reproducible now for me every time that VS Code restarts to upgrade itself:

1. Update appears in VS Code
2. Select "Restart to Update" from the menu
3. ESLint crashes with the following `ENOENT` error 💥

```
Starting the server failed. Launching server using runtime node failed. Error: spawn node ENOENT

ESLint client: couldn't create connection to server. Launching server using runtime node failed. Error: spawn node ENOENT

Unable to resolve your shell environment in a reasonable time. Please review your shell configuration and restart.
```

ESLint Output logs show:

```
2025-10-16 11:48:25.322 [info] ESLint server is starting.
2025-10-16 11:48:25.322 [info] ESLint server stopped.
2025-10-16 11:48:25.322 [error] ESLint client: couldn't create connection to server.
Launching server using runtime node failed. Error: spawn node ENOENT
2025-10-16 11:48:25.322 [error] Starting the server failed.
Launching server using runtime node failed. Error: spawn node ENOENT
2025-10-16 11:48:25.322 [info] PATH environment variable is: /usr/bin:/bin:/usr/sbin:/sbin
```

`Terminal.app` shows a much longer `PATH`:

```bash
$ echo $PATH
/Users/k/Library/pnpm:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:...
```

Restarting via `code .` on the command line / terminal works, but it's annoying and time consuming that the ESLint crashes every time an update comes in for VS Code.


@dbaeumer should this issue be revisited and reopened? Do you think this missing `PATH` is a bug in VS Code itself?

---

<details>

<summary>Relevant settings in `settings.json`</summary>

```json
{
  "eslint.runtime": "node",
  "terminal.integrated.defaultProfile.osx": "zsh",
  "terminal.integrated.scrollback": 100000
}
```

</details>

**Comment by karlhorky** [comment]
Hm, digging in to this a bit, maybe it's a slow initialization of `zsh` during VS Code update or some race condition, just from reading into the last error message again, the docs and a few issues:

```
Unable to resolve your shell environment in a reasonable time. Please review your shell configuration and restart.
```

- https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails
- https://github.com/microsoft/vscode/issues/108003
- https://github.com/microsoft/vscode/issues/106783
- https://github.com/microsoft/vscode/issues/113869
- https://github.com/microsoft/vscode/issues/138182

When I set a shell environment resolution timeout of 30 seconds in my `settings.json` and launch VS Code from the Dock, the error message doesn't appear:

```json
{
  "application.shellEnvironmentResolutionTimeout": 30
}
```

Maybe this should be in the docs, I've added a PR:

- https://github.com/microsoft/vscode-eslint/pull/2087
