### ISSUE TITLE
vs code task "lint whole folder" never linting second folder in vs-code workspace

### ISSUE THREAD

**Issue by bonham** [microsoft/vscode-eslint#1758]
### Setup and summary
I have a typescript project with  vs-code workspace with 'client' and 'server' as folders.
folder structure
```
./myproject.code-workspace

./server/node_modules/...
./server/eslintrc.cjs
./server/.vscode/settings.json
./server/.vscode/tasks.json
...

./clientnode_modules/...
./client/eslintrc.cjs
./client/.vscode/settings.json
./client/.vscode/tasks.json
...
```
I like to use task 'eslint: lint whole folder' for both, client and server directory. however when running the task for server folder, always the client folder is linted.

### Details
./client/.vscode/tasks.json
```
{
  "version": "2.0.0",
  "tasks": [
    .... other config
    },
    {
      "type": "eslint",
      "problemMatcher": ["$eslint-stylish"],
      "label": "eslint: lint whole folder client",
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
  ]
}
```
./server/.vscode/tasks.json
```
{
  "version": "2.0.0",
  "tasks": [
    ... other config
    {
      "type": "eslint",
      "problemMatcher": ["$eslint-stylish"],
      "label": "eslint: lint whole folder server",
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
  ]
}
```
Now trying to run the server part manually:

Ctrl-shift-P: Run Task -> "Eslint: lint whole folder server" -> Enter

![grafik](https://github.com/microsoft/vscode-eslint/assets/2823246/fa27e54f-e509-4d2f-8ec2-aaf64c0cf536)

Yielding this output:

```
Executing task in folder c%3A%5CUsers%5CMichael%5Cmyproject%5Cclient: node_modules\.bin\eslint.cmd . 

C:\Users\Michael\myproject\client\src\components\Myfile.ts
  44:5   warning  Unsafe assignment of an `any` value                  @typescript-eslint/no-unsafe-assignment
  72:7   warning  Unsafe assignment of an `any` value                  @typescript-eslint/no-unsafe-assignment
```

However, I am expecting the server folder to be linted , not the client folder

vs-code eslint v2.4.2
vs code 1.85.1

**Comment by bonham** [comment]
adding tar attachment with settings files for workspace , client , server

[myproject.tar.zip](https://github.com/microsoft/vscode-eslint/files/13761561/myproject.tar.zip)

**Comment by bonham** [comment]
maybe similar to #633

**Comment by dbaeumer** [comment]
Actually it is a dup of #633. However as a work around you can configure a shell task that runs eslint.  See https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks

Closing as dup.
