### ISSUE TITLE
How to Automatically Re-Execute a Specific Rule on Tab Activation in VSCode

### ISSUE THREAD

**Issue by SyMind** [microsoft/vscode-eslint#1759]
# Background

I've created an ESLint custom rule to enforce the use of decorators from `class-validator` in DTO (Data Transfer Object) classes. The rule works by first identifying DTO classes referenced within controller classes. For example, in the `UserController`, the `GetUserRequest` class is identified as a DTO as shown below:

```js
// userController.ts
import { GetUserRequest } from './dto';

@Controller()
class UserController {
  @Get('/user')
  getUser(req: GetUserRequest) {
    // Function body
  }
}
```

After such a determination is made, I intend the rule to actively check the `GetUserRequest` class within `dto.ts` for the appropriate use of decorators.

# Problem

The issue arises under the following scenario:

1. The `GetUserRequest` class already exists within `./dto.ts`.
2. I add code to `UserController.getUser()` to use the `GetUserRequest` DTO.
3. When I return to the `dto.ts` file tab in VS Code, the custom rule does not re-trigger to recheck the file for decorator use.

Currently, the re-evaluation of the file doesn't seem to occur when the tab regains focus in VSCode. I'm looking for a way to ensure the rule re-runs in such cases to verify the enforcement of decorators in the DTO definition.

**Comment by dbaeumer** [comment]
This is currently not possible. But we could add an option to retrigger validation on focus again.

**Comment by SyMind** [comment]
@dbaeumer What will this API be designed to look like? Do you have any ideas?

**Comment by dbaeumer** [comment]
The extension would need to listen to editor focus gain / loss and then send a custom message to the ESLint server to re-lint the current file.

**Comment by dbaeumer** [comment]
Retriggering validation on focus change got added with the new pull model.
