### ISSUE TITLE
[Question] Why isn't `mode: auto` the default for `workingDirectories`?

### ISSUE THREAD

**Issue by MangoMarcus** [microsoft/vscode-eslint#1760]
I'm working on a monorepo workspace where `package.json` and `jsconfig.json` are located in a subdirectory. I was getting very confused by errors raised by `eslint-plugin-import`, which weren't raised when running eslint via the command line.

I eventually realised it's because the vscode eslint plugin uses the workspace root as the working directory, not the js root. This then breaks the alias paths configured with `eslint-import-resolver-alias`, and is fixed by setting `workindDirectories` to `[{ "mode": "auto" }]`.

I'm wondering why this isn't the default behaviour as it seems more intuitive?

The readme does mention unexpected results when using this option, is there any info what these might be?

> [{ "mode": "auto" }] (@since 2.0.0): instructs ESLint to infer a working directory based on the location of package.json, .eslintignore and .eslintrc* files. This might work in many cases but can lead to unexpected results as well.

Thanks

**Comment by dbaeumer** [comment]
ESLint resolves configuration files relative to the current working directory. Chaning the working dir therefore can lead to unexpected results (for example a different `.eslintignore` file is used). To be on the save side with that it is best to explicitly list the working directories or use patterns to do so.

Hope that helps.
