### ISSUE TITLE
Update deprecated Files API's

### ISSUE THREAD

**Issue by yuriy-yarosh** [microsoft/vscode-eslint#1762]
`resolveGlobalYarnPath` and `resolveGlobalNodePath` `uriToFilePath` in [Flies](https://github.com/microsoft/vscode-languageserver-node/blob/main/server/src/node/files.ts#L196) had been deprecated and are using no longer available CLI commands.

`vscode-languageserver-node` dev replied in [#1391](https://github.com/microsoft/vscode-languageserver-node/issues/1393)  that it's the "client responsibility" to figure package manager things out.

**Comment by dbaeumer** [comment]
That is partly done for new package managers.

**Comment by dbaeumer** [comment]
This is done for new package managers and when possible we rely on the VS Code commands for this now.
