### ISSUE TITLE
Flat config not resolving to correct tsconfig

### ISSUE THREAD

**Issue by ArrayKnight** [microsoft/vscode-eslint#1765]
My team has identified a difference in behavior between the VSCode ESLint extension (v2.4.2) and the ESLint CLI (v8.54.0), where the extension fails to correctly resolve the desired tsconfig file based on rules set in multiple / extended ESLint flat configs. I've created an example repo with a stripped down version: https://github.com/ArrayKnight/eslint-flat-config

You can follow the instructions in the README.md to see the difference in behavior. This behavior happens on both Windows VSCode (v1.84.2) and MacOS VSCode (v1.85.1)

The behavior was found because we have two versions of our tsconfig, one for the the build and one for linting. The build version excludes all non-deliverable code files such as tests and stories. However, the lint version includes these files for overall project code quality. Because of this issue, the build version of the tsconfig is being referenced for files that the build version excludes. Which results in the error:

> Parsing error: ESLint was configured to run on <tsconfigRootDir>/apps/foo/src/index.test.ts using parserOptions.project: /users/[user]/code/eslint-flat-config/apps/foo/tsconfig.json However, that TSConfig does not include this file. Either:
> 
> Change ESLint's list of included files to not include this file
> Change that TSConfig to include this file
> Create a new TSConfig that includes this file and include it in your parserOptions.project See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-fileeslint

However, if you run the lint command in the CLI, all files are correctly linted with the expected configs and rules.

We also considered switching the tsconfig versions around to have the lint version be the main version and creating a build specific version, however, this is an issue with NextJS (due to not being able to set a custom tsconfig path): https://github.com/vercel/next.js/discussions/23972

**Comment by dbaeumer** [comment]
Actually I don't know what `npx turbo run lint --cache-dir=./.npm` does under the hood but running eslint directly on the command line prints the same error message than the extension:

```
./node_modules/.bin/eslint apps/foo/src/index.test.ts 

/workspaces/eslint-flat-config/apps/foo/src/index.test.ts
  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/apps/foo/src/index.test.ts` using `parserOptions.project`: <tsconfigRootDir>/apps/foo/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file

✖ 1 problem (1 error, 0 warnings)
```

The extension doesn't know about any scripts in package json. If you want to run these scripts for validation you need to configure a corresponding task in the task system.

What seems to make this work is to set `apps/foo/src` as a working directory for eslint (see setting `eslint.workingDirectories`) since it makes it find the right config file.

I will close the issue. In general, the extension will work correctly if eslint works correctly on the command line as well (without any helper scripts)
