### ISSUE TITLE
RFE: Use ESLint extension as an indenter

### ISSUE THREAD

**Issue by CendioOssman** [microsoft/vscode-eslint#1768]
Not sure what's possible with vscode extensions, but would it be possible to have this extension take control over indenting rules in vscode? I saw the setting to take over as formatter, but that doesn't affect vscode's automating indentation rules.

Primarily, this would help me work around that vscode has no flexibility in how multi-line arguments are indented:

https://github.com/microsoft/TypeScript/issues/11629

**Comment by dbaeumer** [comment]
No this is currently not possible. Major reason is that VS Code doesn't offer API to plugin custom indenters. 

I will close the issue since there is nothing the extension can do about this right now.

**Comment by CendioOssman** [comment]
That's a shame. Thank you for your prompt feedback, though!
