### ISSUE TITLE
`CHANGELOG.md` not updated, changes not showing in VSCode

### ISSUE THREAD

**Issue by voxpelli** [microsoft/vscode-eslint#1772]
Since the `CHANGELOG.md` hasn't been updated on the last couple of releases those changes hasn't either been highlighted in the changelog within VSCode.

Apparently the `README.md` has been updated with release notes instead, but would be great to get these mirrored in the `CHANGELOG.md` as well (or to have the `CHANGELOG.md` removed or changed to point to the `README.md`)

Context: I right now had a hard time finding what was new in the latest version as the changelog was outdated, there were no new GitHub release, only when checking the release commit did I realize that it was actually added to the readme

If you find it bothersome to do manually, then I would suggest adding something like https://github.com/google-github-actions/release-please-action

**Comment by dbaeumer** [comment]
I updated the chnage log file and will make sure I keep it up to date for new releases

https://insiders.vscode.dev/github/microsoft/vscode-eslint/pull/1776
