### ISSUE TITLE
Use flat config not working in 2.4.4 but 2.4.2 and below

### ISSUE THREAD

**Issue by linlinyang** [microsoft/vscode-eslint#1782]
My vscode extension setting:
``` json
"eslint.validate": [
    "javascript",
    "typescript",
    "vue"
  ],
"eslint.experimental.useFlatConfig": true
```
My eslint.config.js:
``` js
export default [{
  rules: {
   'array-callback-return': ['error', {
      checkForEach: true
    }],
    semi: "error"
  },
  files: ["**/*.[mj]s"],
}]
```

And my demo code in  demo.js file
```
// map must be return
// and semi needed
// but no error hint
const foo = [1, 2, 3].map(val => {})
```

My vscode info:

Version: 1.81.0 (user setup)
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044

Name: ESLint
ID: dbaeumer.vscode-eslint
Description: Integrates ESLint JavaScript into VS Code.
Version: 2.4.4
Author: Microsoft

**Comment by dbaeumer** [comment]
I did a mistake when releasing 2.4.4 in terms of pre-req of the right VS Code version. For 2.4.4 you need VS Code 1.82 or above. See https://github.com/microsoft/vscode-eslint/issues/1777

I am closing as dup of https://github.com/microsoft/vscode-eslint/issues/1777
