### ISSUE TITLE
ESLint does not appear in the vs code output view and does not work anymore

### ISSUE THREAD

**Issue by Chreggii** [microsoft/vscode-eslint#1784]
In the vs code output view ESLint disappeared:

<img width="188" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/34272764/d9ff26a9-f31c-4635-9b47-c7b84fdc4b91">

Furthermore,  when I try to run the command `ESLint: fix all auto-fixable Problems` is get the following message:

<img width="344" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/34272764/ecd54959-be3d-410e-9a24-a1877d92e4bf">

ESLint Extension version: `v2.4.4`
Vs code version: `1.86.1`

**Comment by dbaeumer** [comment]
That is very strange. Are you sure you are on `1.86.1`. I made some mistakes with 2.4.4 documented here: https://github.com/microsoft/vscode-eslint/issues/1777

If you are on 1.86.1 can you craft a GitHub repository I can clone that demos this.

**Comment by Chreggii** [comment]
Thanks for your answer. I was able to fix it.

Somehow the following configuration was missing or is now required:

```
"eslint.validate": ["javascript", "typescript"]
```

**Comment by Louies89** [comment]
> Thanks for your answer. I was able to fix it.
> 
> Somehow the following configuration was missing or is now required:
> 
> ```
> "eslint.validate": ["javascript", "typescript"]
> ```

Thank god finally, this helped
