### ISSUE TITLE
Feature request: option to relint files on tab focus change

### ISSUE THREAD

**Issue by nebrius** [microsoft/vscode-eslint#1789]
When using rules such as [import/no-unused-imports](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unused-modules.md), I frequently encounter stale lint errors in files. This happens of course because the lint error isn't caused by code within the file with the error, but because of what other files are doing, which I get is tricky to solve in a general way.

However, I find that by far the most common workflow that triggers the no-unused-imports rule is when I define an export in one file first (triggering the rule here) and then hopping to another file and adding the import (which fixes the rule). However, since I haven't reedited or saved the original file, when I switch back to the tab the error is still there.

Here's a video showing the workflow I'm describing:

https://github.com/microsoft/vscode-eslint/assets/1141386/cc171a87-9715-4686-b5f6-a2f034804515

The current "hack" is to add a space and delete it to force trigger relinting of the file so it can resync. If we could have linting run whenever tab focus changes though then I think we could mitigate what IME is the most common source of these "synchronization" issues.

**Comment by dbaeumer** [comment]
Got implemented and will ship in next release

**Comment by nebrius** [comment]
Thank you @dbaeumer, my org is really going to appreciate this update!
