### ISSUE TITLE
ESLint cannot understand templates

### ISSUE THREAD

**Issue by Arackow** [Microsoft/vscode-eslint#179]
When using a template heavy language like Django, ESLint wont work on the HTML files because it sees the template markers of {{ }} and {% %} as general errors and wont lint the rest of the file. I don't know if there is a way to trick the language server to ignore them or not but it makes the plugin useless for templated languages.

**Comment by dbaeumer** [comment]
@Arackow the HTML validation is contributed through https://github.com/BenoitZugmeyer/eslint-plugin-html. Please open a issue there.
