### ISSUE TITLE
Eslint flat config with esm cannot import from local

### ISSUE THREAD

**Issue by linlinyang** [microsoft/vscode-eslint#1790]
// eslint.config.js
```js
export default [{
  files: ["**/*.?([cm])[jt]s"],
    rules: {
      semi: "error"
  }
}]
```
It will work fine. But:
In config.js file, the same folder
```js
// config.js
export default [{
  files: ["**/*.?([cm])[jt]s"],
    rules: {
      semi: "error"
  }
}]
```
And then import it
```js
// eslint.config.js
import configs from './config'
// import configs from './config.js' failed too.
export default configs
```
**Eslint will work failed.**

// package.json
```json
{
  "name": "eslint-flat-config",
  "version": "1.0.0",
  "private": true,
  "packageManager": "pnpm@8.14.1",
  "description": "The flat config for eslint",
  "type": "module",
}
```
Link to Minimal Reproducible Example
https://stackblitz.com/edit/vitejs-vite-ehy9uw?file=eslint.config.js

Name: ESLint
ID: dbaeumer.vscode-eslint
desc: Integrates ESLint JavaScript into VS Code.
Version: 2.4.2
Author: Microsoft

**Comment by dbaeumer** [comment]
Can you please provide me with a minimal GitHub repository I can clone that demos that.

**Comment by austonpramodh** [comment]
I am having kinda similar issue.

i am trying to import `eslint-preset.js` into `eslint.config.js`.

It fails with error when I use `import eslintPreset from './eslint-preset';` but it works when I use `import eslintPreset from './eslint-preset.js';`

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/project/sandbox/eslint-preset' imported from /project/sandbox/index.js
    at new NodeError (node:internal/errors:406:5)
    at finalizeResolution (node:internal/modules/esm/resolve:233:11)
    at moduleResolve (node:internal/modules/esm/resolve:845:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  url: 'file:///project/sandbox/eslint-preset',
  code: 'ERR_MODULE_NOT_FOUND'
}


code sandbox :- `https://codesandbox.io/p/devbox/sxynrp`

**Comment by jaydenseric** [comment]
@austonpramodh 

> It fails with error when I use `import eslintPreset from './eslint-preset';` but it works when I use `import eslintPreset from './eslint-preset.js';`

That's functioning as expected. Real ESM both in web browsers and in Node.js requires a fully specified import path, including the file extension (in your case `.js`). See:

https://nodejs.org/api/esm.html#mandatory-file-extensions

@linlinyang your example has a similar problem and is missing the `.js` file extension in the import path:

```diff
 // eslint.config.js
- import configs from './config'
+ import configs from './config.js'
```

Note that you should only use `.js` for ESM modules if your package.json has a `type` field set to `"module"`, see:

https://nodejs.org/api/packages.html#type

A better practice is to use `.mjs` to hold ESM, e.g:

```js
// eslint.config.mjs
import configs from './config.mjs'
```
