### ISSUE TITLE
"Unable to resolve path to module" in monorepo

### ISSUE THREAD

**Issue by marioromanepam** [microsoft/vscode-eslint#1798]
Hi, I'm using this extension for my Typescript projects and so far it works great, but I have a problem when using it in monorepos, specifically when I try to import modules from other packages of the repo. For every import, I get error messages like this one:

![Unable to resolve path to module](https://github.com/microsoft/vscode-eslint/assets/151534595/8230f963-defd-4939-927a-fd5a68fc07fe)

Running eslint from command line does not return errors, so I guess it's a problem of this extension, but I'm not sure if it is a bug or a wrong configuration by my side. I created a minimal example in this repo so you can test it and check what is the problem: https://github.com/marioromanepam/vscode-eslint-issue As you can see, in .vscode/settings.json I specified the two working directories, and, except for this problem, I think it works correctly (you can try removing the `eslint-disable-next-line no-console` from src/index.ts in @app/example-app).

If you need more information, please tell me. Thank you!

**Comment by dbaeumer** [comment]
Actually it doesn't work for me neither when using eslint on the command line in the terminal. Doing

```
cd src/apps/exampleApp/
../../../node_modules/.bin/eslint src/index.ts
```

Results in quite some errors and exceptions as well.

Even running `yarn lint` in the root produces some exceptions.

Anything I am missing.

In general the ESLint extension doesn't know about special setups like Lerna. If you need to lint your files via these special commands you can always use tasks.

**Comment by marioromanepam** [comment]
I think the problem is that you have to run `yarn build` before running the linter, in order to create the dist directory in src/context/exampleContext and be able to import the package (sorry, I forgot to include a README in the repo). Here's a video showing the issue just after cloning the repository:

[vscode-eslint-issue video](https://github.com/microsoft/vscode-eslint/assets/151534595/c935465b-251b-407f-8837-8b4b8fd3b9b3)

Please tell me if you have any other problem reproducing the issue. Thanks!

**Comment by dbaeumer** [comment]
Still getting exceptions when running it in the terminal:

![Image](https://github.com/microsoft/vscode-eslint/assets/1931590/d7b2be4c-f825-422c-8354-46fdfb4012fc)

There must be something different as well.

**Comment by marioromanepam** [comment]
Sorry for not answering earlier. We found that running eslint with Node 16 was not throwing errors, but with Node 18 and 20 we could reproduce the same error. It was caused by a bad exports configuration in '@context/exampleContext' package.json: https://github.com/marioromanepam/vscode-eslint-issue/commit/5c0081e7a671d0a8573bc328cdd9fab6c182cb10

Thank you for your help!
