### ISSUE TITLE
Add support for 'fix' from eslint rules to automatically fix eslint errors that are reported.

### ISSUE THREAD

**Issue by jeromu** [Microsoft/vscode-eslint#18]
When writing eslint rules, you can have an optional 'fix' that will automatically patch your code.  It would be great for vscode-eslint to support that.

**Comment by dbaeumer** [comment]
Cool idea.

**Comment by dbaeumer** [comment]
This is available in the latest eslint although with only one pass of fixes. For the n pass case a issue exists.
