### ISSUE TITLE
Typing into .eslintrc.json config with auto save enabled shows annoying warning

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-eslint#180]
Testing: https://github.com/Microsoft/vscode/issues/16497

![image](https://cloud.githubusercontent.com/assets/900690/21005706/22bece42-bd36-11e6-974e-5d2569cfc3fe.png)

**Comment by dbaeumer** [comment]
@bpasero the design around this is as follows:

- such a dialog should show up only once. The reason why I show it is that a broken config file can result in errors appear / disappear or in stale validation.
- when you continue typing in the file the error should not be shown again. 

This was the best compromise I could find between informing the user about validation issues and not being to spamy. 

If you have ideas for improvements I am open to changes.
