### ISSUE TITLE
Run eslint then I got some code error, but vscode didn't give me any tips.

### ISSUE THREAD

**Issue by wenghongtian** [microsoft/vscode-eslint#1801]
Run eslint then I got some code error, but vscode didn't give me any tips.
How to resolve it?

I expected vscode can give me the error code tips.

<img width="1205" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/132538473/e8d394db-a595-4b11-a260-567f2319b2af">

**Comment by dbaeumer** [comment]
Do you have the eslint extension install and setup. If so anything special in the ESLint Output channel?

**Comment by wenghongtian** [comment]
Oh thanks. I found something wrong in my eslint config file.
