### ISSUE TITLE
file lock on *.win32-x64.msvc.node prevents package updates/install

### ISSUE THREAD

**Issue by S-p-Ace** [microsoft/vscode-eslint#1806]
Type: <b>Bug</b>

same as #1421 but with `npm ci` in an nx workspace.

with powertoys file locksmith I can see that the file is locked when the extension is enabled.
`npm ci` runs successful again after ending the process or disabling the extension.

related issues I could find:
https://github.com/nrwl/nx-console/issues/1863

Extension version: 2.4.4
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.67GB (34.04GB free)|
|Process Argv|--crash-reporter-id 2696605e-e343-4768-b5c1-c362626fe437|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30981708
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by dbaeumer** [comment]
As explained in #1421 the eslint server is kept alive for performance reasons when VS Code is running. If Node iself or one of its modules keeps a lock on these files there is little I can do as a developer of the extension. 

I will close the issue since I have no plans to implement a mode that supports process spawning.
