### ISSUE TITLE
Feature request: show notification when ESLint fails to load

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode-eslint#1807]
The status of ESLint is indicated in the status bar by the tiny `x` symbol:

<img width="132" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/921609/ccff441e-256b-460c-b98d-ec8533f6c5f4">
<br/>
<br/>

This is very difficult to spot. I want to be alerted as soon as there's an issue. Could we send a notification when ESLint fails to load?

For context, I encounter these errors quite frequently because my ESLint config depends on custom rules that need to be built prior to ESLint running. A notification would serve as a useful reminder that I need to build my custom lint rules.

**Comment by dbaeumer** [comment]
We had notifications in the past and move to language status since notifications are annoying if you open workspaces where you can't fix this. So if we bring notifications back it has to go behind a setting.

**Comment by U-4-E-A** [comment]
> We had notifications in the past and move to language status since notifications are annoying if you open workspaces where you can't fix this. So if we bring notifications back it has to go behind a setting.

In terms of notifying, I find the way `prettier` does it more than suffices to draw the person's attention to the fact there is an issue, which can then be debugged in output.

![image](https://github.com/microsoft/vscode-eslint/assets/36660386/0080d01e-ef6f-494c-95b4-45a6246c18e3)

**Comment by dbaeumer** [comment]
VS Code's recommendation for something like this is to use a language status. 

![Image](https://github.com/microsoft/vscode-eslint/assets/1931590/f84aa35f-1b27-4863-9bbd-555d51b61095)

If every extension has its own status indicator this will look very crowded.

**Comment by U-4-E-A** [comment]
The user can select which indicators they wish to see? I would also consider eslint - along with prettier - to be perhaps the 2 most import for a developer to be able to monitor while working.

Also a split between soft errors (current file not included) and hard errors (eslint crashing/failing to configure) would very helpful.

**Comment by dbaeumer** [comment]
Yes, the user can ping the ESLint indicator to the status line.

**Comment by dbaeumer** [comment]
I will close the issue since ESLint follows the recommended VS Code standard.

**Comment by dudeofawesome** [comment]
For those wondering, as @dbaeumer alluded to, you can pin the ESLint language status to the status bar, which would look like this when there is an error:

![Image](https://github.com/user-attachments/assets/d9808704-0fca-4720-a8f4-f1e55cf9b196)

You do this by clicking on the `{}` icon, and clicking on the `📌` next to ESLint

![Image](https://github.com/user-attachments/assets/773d2332-1b69-4be5-90ae-4720b81f0f60)
