### ISSUE TITLE
ESLint: show quick fixes for entire line

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-eslint#182]
Testing: https://github.com/Microsoft/vscode/issues/16497

It seems that today I only see quick fix light bulb when being exactly at the location of the warning or error. I think a nicer model would be to show all warnings and errors of the line you are in and offer quick fixes for each.

**Comment by dbaeumer** [comment]
@bpasero I like the idea, however this is how code actions currently work. I will open a issue in vscode world

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/issues/16911

**Comment by dbaeumer** [comment]
Closing as upstream.
