### ISSUE TITLE
Eslint server could not found config file.

### ISSUE THREAD

**Issue by tzcodingjs** [microsoft/vscode-eslint#1822]
develop enviroment:
vscode: 1.88.0
nodejs: 18.19.1
vscode-eslint: 2.4.4

When open project with vscode always show error:

![issue](https://github.com/microsoft/vscode-eslint/assets/29053523/0c60c794-b9ee-4e30-8965-ed012a07dc94)

**Comment by alfjesus** [comment]
Upgrade your `vscode-eslint` to `v3.0.5 (pre-release)`. This solved it for me 🙂. It seems that the current stable version can't handle eslint's new flat config file...

**Comment by dbaeumer** [comment]
That is correct. 2.4.4. has limited support for flat configs. @tzcodingjs do things work for you with 3.05 pre-release?

**Comment by tzcodingjs** [comment]
> Upgrade your `vscode-eslint` to `v3.0.5 (pre-release)`. This solved it for me 🙂. It seems that the current stable version can't handle eslint's new flat config file...

Thanks! But it's not worked.

**Comment by dbaeumer** [comment]
That is strange. Can you provide me with a GitHub repository I can clone with a minimal setup that demos this.

**Comment by tzcodingjs** [comment]
> That is strange. Can you provide me with a GitHub repository I can clone with a minimal setup that demos this.

This project https://github.com/Chanzhaoyu/chatgpt-web

**Comment by dbaeumer** [comment]
@tzcodingjs can you please provide me with a repository with a minimal setup. This looks like a normal development repository.

**Comment by Hoody91** [comment]
> Upgrade your `vscode-eslint` to `v3.0.5 (pre-release)`. This solved it for me 🙂. It seems that the current stable version can't handle eslint's new flat config file...

This worked fine for me, although I did have to restart vscode multiple time before it started working.

**Comment by ShravanSunder** [comment]
I had this issue with eslint v9.  rolling back to 8.5x fixed this for me.  I'm not using flat config, but the old config

**Comment by dbaeumer** [comment]
@ShravanSunder can you please provide me with a GitHub repository I can clone with a minimal setup that demos this.

I do have a test case for 9.0 with the old rc based config and the works for me: https://github.com/microsoft/vscode-eslint/blob/553e632fb4cf073fce1549fb6c3c1b5140a52ebb/playgrounds/9.0/rc/package.json#L1

So I would be interested to understand why this fails for you.

**Comment by dotspencer** [comment]
Downgrading to eslint version `8.57.0` resolved the issue for me

**Comment by ShravanSunder** [comment]
As of right now, eslint v9, old eslint config and vscode are incompatible.

**Comment by dbaeumer** [comment]
@ShravanSunder @dotspencer do you have a GitHub repository I can clone that demos thus. 

And did you both use the pre-release version of ESLint (3.0.5)

**Comment by sydneytan** [comment]
> Upgrade your `vscode-eslint` to `v3.0.5 (pre-release)`. This solved it for me 🙂. It seems that the current stable version can't handle eslint's new flat config file...

it worked! thanks so much.

**Comment by tayloraleach** [comment]
I see the same error returning to a project that I have not opened in a while ...

![image](https://github.com/microsoft/vscode-eslint/assets/25046653/37fed222-d113-4cfd-8be5-7ae236a16d44)

I am **not** using the new flat config:
`"eslint": "^8.38.0"`

What I have tried:
- Updating to the latest vscode-eslint version (3.0.10) as well as downgrading to others such as 2.4.4.
- Uninstalling and reinstalling the extension
- Restarting VS code multiple times. 
- Disable flat config in vs code extension settings
- Updating VS code to the latest version. 

I do not have eslint installed globally and my project is not inside another project on my system

Absolutely maddening.

**Comment by dbaeumer** [comment]
@tayloraleach what happens when you run ESLint in the terminal from the `node_modules` folder. If that works, could you please provide me with a GitHub repository I can clone that demos what you are seeing.

**Comment by spro** [comment]
@dbaeumer here's a fresh repo created with `npx create-next-app@13.3` which has a minimal `.eslintrc.json` - https://github.com/spro/nextjs-13.5.6-eslint

I see the same issue as described. Downgrading to 2.4.4 does not work, but 2.2.6 is fine.

**Comment by dbaeumer** [comment]
@spro 

Thanks for the repository. But it works for me:

![Image](https://github.com/user-attachments/assets/9e6b39c2-2e95-4703-ae9a-6d09c5069fc4)

Any additional steps / setup?

**Comment by spro** [comment]
By comparing your output to mine I think I found the issue. I was seeing this:

```
[Info  - 1:24:33 PM] ESLint server is starting.
[Info  - 1:24:33 PM] ESLint server running in node v20.9.0
[Info  - 1:24:33 PM] ESLint server is running.
[Info  - 1:24:34 PM] ESLint library loaded from: /Users/sean/Projects/nextjs-13.5.6-eslint/node_modules/eslint/lib/unsupported-api.js
[Info  - 1:24:34 PM] ESLint version 8.57.0 supports flat config without experimental opt-in. The 'eslint.experimental.useFlatConfig' setting can be removed.
2024-06-28T20:24:34.008Z eslint:flat-eslint Searching for eslint.config.js
[Error - 1:24:34 PM] Calculating config file for file:///Users/sean/Projects/nextjs-13.5.6-eslint/pages/index.tsx) failed.
Error: Could not find config file.
```

I had ignored the mention of "'eslint.experimental.useFlatConfig' setting can be remove", but after looking for that in my settings.json and removing it, the latest version is working as expected.

**Comment by dbaeumer** [comment]
Good to hear you got it working.

**Comment by buihuytuyen** [comment]
remove config useFlatConfig in setting!

**Comment by gruijter** [comment]
Where can I find this setting file? I'm going crazy right now :( . My projects all use a local .eslintrc file with the configuration. But the linter stopped working on all my projects recently.

**Comment by nasserakhter** [comment]
After v9 .eslintrc.js no longer works. So it will give a config not found, because technically, it was not found.

You have to either migrate all your configs to eslint.config.js (which includes all extended configs as well)

or downgrade to v8 of eslint.

Downgrading also lets you stay on the stable version of the eslint vscode plugin.

**Comment by dbaeumer** [comment]
You can also force v9 to use the old config file by setting `eslint.useFlatConfig` to false. But please note that this only works for v9. The next version of eslint (v10) will have the old config file format removed.

**Comment by masterkain** [comment]
remove from your vscode config: `"eslint.experimental.useFlatConfig": true`

had the same issue with .eslintrc.json / next 14

**Comment by dherault** [comment]
For me the issue was that I installed some dependency (react-email) that use eslint v9 (instead of v8).
Use `npm list eslint` to view the faulty dependencies and update `overrides` in package.json to fix it.

**Comment by rashgaroth** [comment]
i have fixed this issue by downgrading these `devDepedencies`

- `eslint` from version `9.*` to version `8.*`
- `@typescript-eslint/eslint-plugin` from version `^8.* to `^7.*`
- `@typescript-eslint/parser` from version `^8.* to `^7.*`

**Comment by rharkor** [comment]
Any solution yet ? Because I encounter the problem with next15

**Comment by dbaeumer** [comment]
@rharkor any repository you can share with a minimal setup demoing what you are seeing?

**Comment by Badisi** [comment]
For me, the error occurs when using workspaces in VSCode.

Consider the following project structure:

```
+ my-project/
    + resources/
    + backend/
    + frontend/
        + src/
        + eslint.config.mjs
        + package.json  <-- { "scripts": { "lint": "eslint ." } }
```

My ESLint configuration file is technically at the root of the frontend project.
So, when using the command line and running `npm run lint` inside `/my-project/resources/frontend`, it works as expected.
ESLint's flat config locates the configuration file in the root directory where the command is executed.
Similarly, if I open the `frontend` folder in VSCode, linting works fine on files inside that folder.

However, for convenience, I usually open the entire `my-project` folder in VSCode.
And this is where the error occurs, as the ESLint extension looks for the config in the `my-project` root and therefore cannot find the configuration file.

---

From ESLint's perspective, the config file is correctly located at the root of the frontend project.
Running ESLint from the command line works as expected since it’s executed from this root.

However, with the ESLint extension in VSCode, the process is less straightforward.
Since VSCode is used to browse files, the exact location where the command should run isn’t always clear.
I've seen the setting `workingDirectories` but it implies that I always remember to open my project from the proper folder, otherwise it won't work.
Instead, the extension could search up the directory tree (from the current opened file) and find the nearest config file, but I understand it could affect performances...

**Comment by dbaeumer** [comment]
@Badisi very likely `eslint.workingDirectories` is your friend. Simply add `"./frontend"` as a value.

**Comment by dbaeumer** [comment]
@berkerdemirer does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone with a minimal setup that demos what you are experiencing.

**Comment by OahMada** [comment]
https://stackoverflow.com/a/79126876/5800789 this worked for me.

**Comment by dbaeumer** [comment]
This issue covers a lot of different cases with flat config files and we worked on making the flat config out of the box with eslint 9.x.

If you still see issues, please open a new report with detailed steps on how to reproduce. Best is a GitHub repository I can clone with a minimal setup.
