### ISSUE TITLE
Parsing error: __classPrivateFieldGet(...).at is not a function | After upgrading to newest version of Typescript & Eslint

### ISSUE THREAD

**Issue by AntonyTsy** [microsoft/vscode-eslint#1828]
Getting an error at the top of every open TS file. I have tried reloading the VSCode window and cleaning/reinstalling package dependencies.

`Parsing error: __classPrivateFieldGet(...).at is not a function`

![Screen Shot 2024-04-10 at 2 47 14 PM](https://github.com/microsoft/vscode-eslint/assets/150283311/06a4f89e-6897-4ff7-badb-b7b06bccf24c)

Node Version: `18.19.0`
TypeScript Version: `5.4.3`
Package version: `Latest`

#### Package.json
```json
    "eslint-plugin-mocha": "^10.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-import": "^2.29.1",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "@typescript-eslint/eslint-plugin": "^7.5.0",
    "@typescript-eslint/parser": "^7.5.0",
    "typescript-eslint": "7.5.0"
```

**Comment by dbaeumer** [comment]
Does validation happen correctly in the terminal? If so can you please provide me with a GitHub repository I can clone with a minimal setup that demos what you are seeing

**Comment by AntonyTsy** [comment]
The project is a mono-repo for a testing framework with lerna, mocha & typescript. I am using nvm as my node package mangager.

Since the repo belongs to the company I work for I will not be able to share the code but when I get some down time I will create & share a minimal reproducible example from my personal GH. Thanks for agreeing to take a look will be able to get to this at some point tonight.


Eslint is working from the terminal as well as with husky on commit hooks
![Screen Shot 2024-04-11 at 9 39 08 AM](https://github.com/microsoft/vscode-eslint/assets/150283311/b7b6b10a-4d68-47c2-9cac-a9b239acf42f)

**Comment by AntonyTsy** [comment]
After spending a bit more time digging I found the issue. It was not recognizing my node path correctly. Setting these two configurations with absolute paths solved the issue for me
```ts
"eslint.runtime": "/Users/name/.nvm/versions/node/v18.19.1/bin/node",
"eslint.nodePath": "/Users/name/.nvm/versions/node/v18.19.1/bin/node"
```
![Screen Shot 2024-04-11 at 10 01 14 AM](https://github.com/microsoft/vscode-eslint/assets/150283311/18ac238d-9bde-402a-bbc4-2603f3534432)

**Comment by Alanrah** [comment]
I had this problem when I was using nodejs 16.0.0, upgraded to nodejs 18.12.0 and the problem disappeared
