### ISSUE TITLE
Sorting is bugged

### ISSUE THREAD

**Issue by garysassano** [microsoft/vscode-eslint#1833]
I have the following imports:

![image](https://github.com/microsoft/vscode-eslint/assets/10464497/22d33f9c-4d1e-44f1-9dbb-3037ff04293d)

I press `Ctrl+S` to save the file and this is what I get:

![image](https://github.com/microsoft/vscode-eslint/assets/10464497/71c7f20e-f9ee-4b18-9f7d-e9f10e40fc75)

This is my `settings.json`:

```json
"[typescript]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.organizeImports": "explicit",
  },
},
```

**Comment by dbaeumer** [comment]
@garysassano doe fix work correctly for you in the terminal using `eslint --fix`. If so, can you please provide me with a GitHub repository I can clone with a minimal setup that demos what you are seeing.

**Comment by garysassano** [comment]
Had to change the `codeActionOnSave` block:

```json
"[typescript]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit"
  },
},
```

I wrongly assumed that it would be possible to only apply eslint rules related to imports instead of fixing all, but it's not actually feasible.
