### ISSUE TITLE
.vscode/settins.json set eslint.nodePath, Failed to load the ESLint library

### ISSUE THREAD

**Issue by njzzzz** [microsoft/vscode-eslint#1838]
![image](https://github.com/microsoft/vscode-eslint/assets/41502851/2462fe9e-d168-4ead-a6fb-522dc59b59c8)
I installed eslint@4.19.1 in my workspace, but  it can't be loaded.

![image](https://github.com/microsoft/vscode-eslint/assets/41502851/caeb95d5-87a4-472c-bcc1-9b04cef1a826)
![image](https://github.com/microsoft/vscode-eslint/assets/41502851/11a891d9-e65c-43fb-bf6a-20da4b0bbab7)

**Comment by dbaeumer** [comment]
Hard to say without being able to reproduce this. Can you please provide me with a GitHub repository I can clone with a minimal setup that demos this?

**Comment by njzzzz** [comment]
> Hard to say without being able to reproduce this. Can you please provide me with a GitHub repository I can clone with a minimal setup that demos this?

Thanks for the reply!  I created a repo, link: https://github.com/njzzzz/vscode-eslint-load-error

**Comment by dbaeumer** [comment]
Works for me:

![Image](https://github.com/microsoft/vscode-eslint/assets/1931590/9382beb7-a0c2-477c-b0bd-a277a8f5fa7b)

Anything I am missing?

**Comment by njzzzz** [comment]
> Works for me:
> 
> ![Image](https://private-user-images.githubusercontent.com/1931590/328788791-9382beb7-a0c2-477c-b0bd-a277a8f5fa7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTkyNjMsIm5iZiI6MTcxNTE1ODk2MywicGF0aCI6Ii8xOTMxNTkwLzMyODc4ODc5MS05MzgyYmViNy1hMGMyLTQ3N2MtYjBiZC1hMjc3YThmNWZhN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDkwMjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTU1ZmYyNWJjYmNhOWI2ZWE5NGZhYTJiZjI5ZTM4NzYyMDQ4MmMxNmZmZjUxMjhmOTIxODk0MTM1YzM1ZGIxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1_JnfITytgQtqf3Rr7yMq0S9Yj3ZsmjH0ytYqfwFmlg)
> 
> Anything I am missing?

I completely removed VSCode, reinstalled it, deleted the redundant configurations, and resolved the issue; it might have been influenced by WSL or other extensions
