### ISSUE TITLE
vscode-eslint 1.2.0 has not appeared

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode-eslint#184]
In [the release note of VSCode 1.8](http://code.visualstudio.com/updates/v1_8#_linter-extensions), it has the notation about `eslint.validate` option.
But it seems to not be published.

![image](https://cloud.githubusercontent.com/assets/1937871/21210615/e2dfa73a-c2bf-11e6-9251-f7ee9adf58f4.png)

**Comment by dbaeumer** [comment]
Done. I wanted to do some final testing on the final VS Code 1.8 version.
