### ISSUE TITLE
Bug: When "Open Workspace from File" eslint complains that it cannot find imports, when "Open from Folder" the same code, no issues

### ISSUE THREAD

**Issue by GeorgeWL** [microsoft/vscode-eslint#1847]
Bit of an odd error, seems to be related to if the .eslintrc has a `parserOptions.project`, as when I change from 

## BROKEN

<details>
<summary>.eslintrc with relative paths </summary>

folders renamed but same structure

```json
"parserOptions": {
    "ecmaVersion": 2020,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true,
      "generators": true,
      "experimentalObjectRestSpread": true
    },
    // 'project' required for the no-floating-promises rule,
    "project": [
      "./a/tsconfig.json",
      "./b/tsconfig.json",
      "./c/tsconfig.json"
    ]
  },
```
</details>

## WORKS

<details>
<summary>.eslintrc with glob path</summary>

folders renamed but same structure

```json
"parserOptions": {
    "ecmaVersion": 2020,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true,
      "generators": true,
      "experimentalObjectRestSpread": true
    },
    // 'project' required for the no-floating-promises rule,
    "project": [
      "**/tsconfig.json"
    ]
  },
```
</details

then I no longer see the error, but I'm not sure if that's a bit of a hacky workaround?

### vscode Workspace file

<details>
<summary>repo-name.code-workspace file</summary>
folders renamed but same structure

```json
{
  "folders": [
    {
      "name": "root folder",
      "path": ".."
    },
    {
      "name": "A",
      "path": "../a"
    },
    {
      "name": "B",
      "path": "../b"
    },
    {
      "name": "C",
      "path": "../c"
    },
    {
      "name": "cypress",
      "path": "../cypress"
    }
  ],
  "settings": {
    "jest.disabledWorkspaceFolders": [
      "root folder",
      "cypress"
    ],
  },
}
```
</details>

**Comment by dbaeumer** [comment]
To my knowledge typescript eslint doesn't support glob patterns for projects. If you think they should be supported please file an issue against the typescript eslint repository.

**Comment by GeorgeWL** [comment]
> To my knowledge typescript eslint doesn't support glob patterns for projects. If you think they should be supported please file an issue against the typescript eslint repository.

that's the thing, it only works with the globs, but that feels like a hack.

**Comment by GeorgeWL** [comment]
the specific error it gives is that if I use "Open Workspace from File" with the relative paths config linked in the issue, then entering any of the JS or TS files in the monorepo gives this error:

> Parsing error: Cannot read file '`FILEPATH`\a\`FOLDER`\tsconfig.json'

**Comment by GeorgeWL** [comment]
my only thought, maybe it's that I include the root folder in there, which includes all the other workspaces, I'm going to see locally if that's true then if it's still an issue I'll get you a minimal setup

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
