### ISSUE TITLE
Consistent creation of zombie processes by vscode-eslint extension

### ISSUE THREAD

**Issue by tategotoazarasi** [microsoft/vscode-eslint#1855]
**Environment:**

- Operating System: Arch Linux
- VSCode Version: 1.89.1
- vscode-eslint Version: 2.4.4
- ESLint Version: 9.4.0

**Issue Description:** The vscode-eslint extension consistently leaves behind a zombie process specifically `[npm config get ] <defunct>` every time VSCode is closed. This issue occurs every time without exception, leading to additional wait times during system shutdown as the process is awaited to terminate.

**Steps to Reproduce:**

1. Open VSCode with the vscode-eslint extension enabled.
2. Close VSCode.
3. Check for zombie processes using `ps -aux | grep defunct` and observe the `[npm config get ] <defunct>` zombie process.

A zombie process `[npm config get ] <defunct>` remains each time VSCode is closed. The parent process typically is `/opt/visual-studio-code/code /home/username/.vscode/extensions/dbaeumer.vscode-eslint-2.4.4/server/out/eslintServer.js --node-ipc --clientProcessId=94143`

Killing the parent process results in the zombie being reattached to systemd, remaining as a defunct process. This causes significant delays during system shutdown due to the wait for this process to terminate.

**Comment by dbaeumer** [comment]
I tried to reproduce this but I am not able to do so. 

@tategotoazarasi are you still seeing this?

**Comment by tategotoazarasi** [comment]
> I tried to reproduce this but I am not able to do so.
> 
> [@tategotoazarasi](https://github.com/tategotoazarasi) are you still seeing this?

I had disabled the extension after encountering this issue. After enabling it again, I found that the problem no longer occurs.
