### ISSUE TITLE
Is it possible to pass parameters to the format?

### ISSUE THREAD

**Issue by VictorAugustoqwe** [microsoft/vscode-eslint#1857]
I would like to "Format document With: " to execute something like the eslint cli:
--fix --fix-type layout
(to fix only the layout rules)
or
--fix --quiet 
(to fix only the warnings)
Is this currently possible?

**Comment by dbaeumer** [comment]
You can use `eslint.options.fixtypes` VSCode setting with the values documented here: https://eslint.org/docs/latest/integrate/nodejs-api#-new-eslintoptions
