### ISSUE TITLE
Files are not analized when opened

### ISSUE THREAD

**Issue by Ptitet** [microsoft/vscode-eslint#1858]
When i open a new file in VSCode, it is not analyzed by ESLint. I have to manually do `ctrl+shift+p` then type `ESLint: Revalidate all open files` for ESLint to analyze them. When i run `npx eslint .` in the console, ESLint directly report all the problems.

Once a file is analyzed, i can make mistakes and they will by instantly detected, but not if the file is freshly open and i have not manually run the revalidation.

I'm using Bunjs latest version, Linux Mint 21, and ESLint uses nodejs v21

**Comment by dbaeumer** [comment]
Which version of ESLint Extension and VS Code are you using. I tried this on latest and validation works for me as expected.

**Comment by Ptitet** [comment]
I'm using ESLint pre-release (3.0.7) and VSCode 1.90.0.
Unfortunately the issue seems to be gone now that i reopened VSCode, so i cannot provide more information.
I think we can close the issue for now, I think is is an "edge edge case" happening only when my potato laptop is overwhelmed.
