### ISSUE TITLE
"eslint.options.fixTypes" Not Working in "Format Document with: ESLint"

### ISSUE THREAD

**Issue by VictorAugustoqwe** [microsoft/vscode-eslint#1860]
I'm trying to fix only the layout problems in my files. 
My settings.json contains:
`"eslint.format.enable": true,
    "eslint.options": {
      "fixTypes": ["layout"]
    }`

However, when I Format Document with ESLint it fix all problem types.
I believe this issue is related to the extension because both the CLI option and instantiating the class work correctly.

I've created a simple repository to reproduce the behavior: 
https://github.com/VictorAugustoqwe/eslintErrorRep

**Comment by dbaeumer** [comment]
The reason is that the eslint extension uses `lintText` instead of `lintFiles` to be able to lint unsaved files which seems to not honor the options correctly.

**Comment by dbaeumer** [comment]
I opened an issue against eslint: https://github.com/eslint/eslint/issues/18732

**Comment by dbaeumer** [comment]
The issue got fixed upstream.
