### ISSUE TITLE
How Can I Display All ESLint Errors and Warnings for All Files in VSCode?

### ISSUE THREAD

**Issue by jon9090** [microsoft/vscode-eslint#1865]
I use this extension for VSCode, and it displays all the warnings and errors when I open a file.

However, is there a way to display all the errors and warnings across all the files in the project as identified by ESLint? I don't want to open each file individually to check for errors. 

Also, using the terminal to copy file paths and locate them in the VSCode editor is not efficient.

<img width="679" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/74149517/5bf21e76-c9d4-4db5-a454-7d94b4015b55">

**Comment by dbaeumer** [comment]
The extension has support to lint all files using a task. See the setting: `eslint.lintTask.enable`. It still requires to run the task manually since ESLint itlself has no support for file watching.

**Comment by paulintheuk86** [comment]
This did not answer the question at all.

**Comment by max-nextcloud** [comment]
Works for me:
* set eslint.lintTask.enable to `true`.
* set eslint.lintTask.command to `npx eslint`.
* triggerd `run Task` and picked eslint task.

Linter runs and highlights all issues in the file list. I can move to the next issue with `Go to next problem in files command`.
