### ISSUE TITLE
Support ESLint module install globally via yarn

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-eslint#187]
Need to add yarn's global module install location to the NODE_PATH when resolving the node module. Something comparable to `npm config get prefix`

**Comment by WoodyWoodsta** [comment]
For those wondering, a workaround on Linux is to set the following:
```json
eslint._legcyModuleResolve: true, 
eslint.nodePath: "/your/home/dir/.config/yarn/global/node_modules/"
```

**Comment by idibidiart** [comment]
Doesn't work on Mac

**Comment by dbaeumer** [comment]
Does anyone know how to determine the global module location for yarn. I tried `yarn config get prefix` and `yarn config list`but nothing contains the global install location.

**Comment by dbaeumer** [comment]
Under Windows is seems to be `~\AppData\Local\Yarn\config\global\node_modules`.

**Comment by eduedix** [comment]
yarn global bin?

**Comment by dbaeumer** [comment]
`yarn global bin` prints the same as `npm config get prefix` however this is not the location yarn installs global npm modules. I am still a little lost here.

**Comment by eduedix** [comment]
https://github.com/yarnpkg/yarn/issues/2652

**Comment by dbaeumer** [comment]
@eduedix thanks for opening the yarn issue.

**Comment by reybango** [comment]
@dbaeumer I reached out to the FB team and pointed them at this issue. Hoping they'll jump in and help.

**Comment by dbaeumer** [comment]
@reybango thanks. I retested this today and yarn still doesn't provide me with command to find the global node modules install location.

**Comment by BYK** [comment]
Added a PR here: https://github.com/yarnpkg/yarn/pull/4522

**Comment by BYK** [comment]
Released Yarn 1.1.0 with this PR merged.

**Comment by dbaeumer** [comment]
@BYK Thanks!

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode-eslint/blob/master/README.md#settings-options how to enable this.

**Comment by marswong** [comment]
Indeed, there is nothing to do with `yarn`, just add `"eslint.packageManager": "yarn"` to your vscode settings and it would fix at all :)
