### ISSUE TITLE
Not work of "source.fixAll.eslint": "explicit"  on v3.0.10

### ISSUE THREAD

**Issue by seepine** [microsoft/vscode-eslint#1877]
.vscode/settings.json
```json
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit"
},
```

vscode version 1.84.0

**Comment by dbaeumer** [comment]
@seepine I tried to reproduce this but it works for me. See screen cast. Could you share a GitHub repository I can clone with a minimal setup that reproduces what you are seeing.

https://github.com/user-attachments/assets/5d0874ed-e2e1-4f09-aed8-344691bbdc36

**Comment by dbaeumer** [comment]
If you use prettier and yarn pnp you might be affected by: https://github.com/yarnpkg/berry/issues/6335
