### ISSUE TITLE
`eslint.execArgv` Configuration is Not Working

### ISSUE THREAD

**Issue by Zzzen** [microsoft/vscode-eslint#1881]
I have added the following configuration to my .vscode/settings.json file:
```json
"eslint.execArgv": ["--max_old_space_size=8192"],
```

Additionally, I modified `eslint/lib/api.js` to log `execArgv` for verification purposes. However, the `max_old_space_size` setting does not appear in the logs, indicating that it is not being applied.

![image](https://github.com/microsoft/vscode-eslint/assets/6630042/58fdb9b0-b704-4aa1-bc34-7a3192c68cb4)
![image](https://github.com/microsoft/vscode-eslint/assets/6630042/561e3b62-4c5b-4536-bbda-76241b68b714)

**Comment by dbaeumer** [comment]
@Zzzen you might need to use a custom NodeJS version using the `eslint.runtime` setting. Reason is that VS Code ships with a compact heap for NodeJS which limits the `max_old_space_size` to 4GB.

**Comment by dbaeumer** [comment]
Let me add something to the settings doc to make that more clear.

**Comment by dbaeumer** [comment]
Added this to the docs, settings description.
