### ISSUE TITLE
Should plugins still have `eslint.experimental.useFlatConfig` in their settings?

### ISSUE THREAD

**Issue by predragnikolic** [microsoft/vscode-eslint#1886]
Should this line be changed?
https://github.com/microsoft/vscode-eslint/blob/7b17139064014e339aae78f33b6dde2f84fe815e/server/src/eslint.ts#L915
to use optional chaining `eslint.experimental?.useFlatConfig` or something else?

----

Now that 3.0.10 is out,
I am migrating LSP-eslint for Sublime Text to support ESLint 9 flat config.

In that process, I've removed the `eslint.experimental.useFlatConfig` in favor of `eslint.useFlatConfig`,
and when I did that,
I started to get errors like `Cannot read properties of undefined (reading 'useFlatConfig')`:
```
LSP-eslint (4) (duration: 1ms): {'code': -32603, 'message': "Request textDocument/codeAction failed with message: Cannot read properties of undefined (reading 'useFlatConfig')"}
```

Should plugins have `eslint.experimental.useFlatConfig` and `eslint.useFlatConfig` in their settings?
Or should plugins only have `eslint.useFlatConfig` in their settings?

**Comment by dbaeumer** [comment]
I think it should be OK to make it optional in the ESLint server code. For sublime text: since you never had that setting I wouldn't introduce it. You can set it to `false` when ask for the configuration. That should made it work for now.
