### ISSUE TITLE
excess spaces when "Fix this prefer-template problem"

### ISSUE THREAD

**Issue by Rwing** [Microsoft/vscode-eslint#189]
```
let a = 'a';
let b = 'b' + a;
```
fixed
```
let a = 'a';
let b = `b${  a}`;
```

**Comment by dbaeumer** [comment]
@Rwing does this happen as well when running eslint --fix on the command line. Might be a multi pass problem as well.

**Comment by Rwing** [comment]
so, how to fix?

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode-eslint/issues/154 if it works when executing eslint from a command line with --fix

**Comment by jameswomack** [comment]
@dbaeumer I see the same issue and it is present even when running `--fix`, regardless of the amount of passes used. It happens with `3.1.x`, `@latest` as well as `github:eslint/eslint#indent-rewrite`.

**Comment by dbaeumer** [comment]
If it is even present when running eslint in a terminal with --fix then this looks like a eslint problem to me and an issue needs to be opened here: https://github.com/eslint/eslint

**Comment by jameswomack** [comment]
@dbaeumer true / agreed. FWIW I learned of a rule called template-curly-spacing that solves this.

**Comment by dbaeumer** [comment]
I will close the issue then. Either follow up on https://github.com/eslint/eslint or #154
