### ISSUE TITLE
Add support for ESLint feature flags

### ISSUE THREAD

**Issue by nzakas** [microsoft/vscode-eslint#1895]
In ESLint v9.6.0, we added the ability to specify feature flags in ESLint. While there aren't any currently active feature flags, there will be in the coming months. Feature flags only work when using flat config files, and can be specified by passing `flags` into the `ESLint` constructor like this:

```js
const eslint = new ESLint({
     flags: ["some_flag"]
});
```

It would be great to have an option in vscode-eslint that would allow users to specify which flags they'd like to enable.

**Comment by dbaeumer** [comment]
Makes sense. Just to be sure the type of the `flags` property is `string[]`.

**Comment by nzakas** [comment]
That's correct.

**Comment by dbaeumer** [comment]
Actually. It is already supported. There is a `eslint.options` settings that is already passed into the ESLint class. You can simply add a `flags` property to it and it should work.

@nzakas let me know if this works for you.

**Comment by nzakas** [comment]
Ah nice! Yup, that should work. Thanks.
