### ISSUE TITLE
ESLint is preventing my files from being saved

### ISSUE THREAD

**Issue by eianc** [microsoft/vscode-eslint#1902]
Initially I thought that [GitHub Copilot is causing the issue](https://github.com/microsoft/vscode-copilot-release/issues/1378), however I discovered that it's the ESLint extension from VS Code.

When I have the ESLint extension enabled in VS Code, the files are not saving. Whenever I try to save a file, the file doesn't save and after a few seconds a notification similar with this shows up and nothing happens, it just hangs.
![Screenshot 2024-07-12 at 14 35 56](https://github.com/user-attachments/assets/99fb2c5f-72f9-4877-8621-bc7fdfcaabe5). 
I used to be able to save the file by cancelling the notification, however now that doesn't seem to work anymore and I can't save any files. Restarting VS Code doesn't help.

In VS Code user configuration I have the following:

```
 "editor.codeActionsOnSave": {}
 ```
 I tried different settings but none of them seem to make any difference. 

I'm on:

macOS: Sosoma version 14.5

VS Code
Version: 1.91.1 (Universal)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z (2 days ago)
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 23.5.0

 ESLint version 3.0.10 (I tried with the pre-release version 3.0.11 however that did not help)

**Comment by Mletter1** [comment]
So this is kinda weird but cycle through the `disable -> restart extensions -> enable` for the eslint extension. for whatever reason this fixes it for me like 1 out of every 5 cylces. I'm wondering if another extension like eslint-prettier or something is clashing with this one. 
<img width="332" alt="image" src="https://github.com/user-attachments/assets/cbbedfb9-3c16-4fa0-a4cd-2b31ed0a1e0e">

**Comment by eianc** [comment]
I only have the ESLInt extension enabled, I disabled all the other extensions and I still get the issue

**Comment by dbaeumer** [comment]
I tried to reproduce this with an empty `editor.codeActionsOnSave` configuration but wasn't able to do so. @eianc could you please provide me with a GitHub repository I can clone that contains a minimal setup that demonstrates the problem.

**Comment by eianc** [comment]
It's happening on a monorepo setup with Lerna, I don't get the issue on other codebases that I'm working on. I did not have time to investigate if it's a codebase setup that is causing the issue or something else. A colleague of mine just got the same issue on the same codebase with a new Mac, using Ubuntu or Windows doesn't cause the issue.
I'll try to make time at the weekend to investigate the setup.

**Comment by dogyeong** [comment]
@eianc 
check the eslint runtime. I downgraded node version 20 → 18 and it works.

**Comment by A5rocks** [comment]
I'm not sure if I'm running into this exactly, but I made a somewhat minimal reproducer: https://github.com/A5rocks/repro-eslint-vscode

I reproduced in node v18.15.0 and v20.13.1, and this reproducer worked for someone else (so hopefully it's not just a user settings thing).

**Comment by dbaeumer** [comment]
@A5rocks you are affected by https://github.com/yarnpkg/berry/issues/6335 (e.g. a problem with yarn and synckit)

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by chstappert** [comment]
Issue is still there since 1.99.1 Update.
