### ISSUE TITLE
Show the light bulb icon regardless of cursor position in the current line

### ISSUE THREAD

**Issue by Yohanna** [Microsoft/vscode-eslint#191]
It'd be nice to show the light bulb icon while the cursor is at any position in the line. Currently it's only displayed when the cursor is placed on the first letter of the underlined word.

![image](https://cloud.githubusercontent.com/assets/6926228/21473211/102887aa-cace-11e6-994d-8c433136210f.png)

![image](https://cloud.githubusercontent.com/assets/6926228/21473221/5a5bafc8-cace-11e6-8c4e-282c321ec8e1.png)

**Comment by dbaeumer** [comment]
This has to be fixed in VS Code itself and there is an open issue in VS Code to address this. 

@jrieken do you have the issue number handy.

**Comment by sshmyg** [comment]
+1

**Comment by sshmyg** [comment]
@dbaeumer What's status of an issue?

**Comment by dbaeumer** [comment]
@sshmyg things got polish for this in VS Code and we are working on more polish for the next release. If you take latest insider you can see the changes already in.

**Comment by sshmyg** [comment]
Thnks for an info.
