### ISSUE TITLE
eslint 一旦出现 error，输出日志显示 Error 时，代码编辑器爆红会消失

### ISSUE THREAD

**Issue by huxinfeng** [microsoft/vscode-eslint#1910]
eslint 一旦出现 error，输出日志显示 Error 时，代码编辑器爆红会消失，我是从 2.4.2 版本升级过来（这个版本正常），最新版本会有这个问题；请看图

https://github.com/user-attachments/assets/9c764f02-56fa-44c8-97ed-5467360ae60d

**Comment by alex-kinokon** [comment]
#1807?

**Comment by dbaeumer** [comment]
@huxinfeng 

Thanks for creating this issue!

Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.

In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
