### ISSUE TITLE
ESLint affects quick fix options

### ISSUE THREAD

**Issue by FanetheDivine** [microsoft/vscode-eslint#1925]
I suppose to import the component but just options about eslint were provided
![屏幕截图 2024-09-02 134729](https://github.com/user-attachments/assets/3808b577-6903-4958-9758-89f01c46a3e6)
When I disable options below, there is no options in quick fix
![● settings json - sophicloud安装包webui - Visual Studio Code  管理员  2024_9_3 9_44_12](https://github.com/user-attachments/assets/7cf6a255-572c-4ec0-8305-beeb866d9829)

**Comment by dbaeumer** [comment]
There reason for this is very likely that the TS server can't find the corresponding import. This is nothing that is done by ESLint in this setup. Can you please open a corresponding issue against VS Code.
