### ISSUE TITLE
Lint with typescript config file `eslint.config.{m,c}ts`

### ISSUE THREAD

**Issue by plbstl** [microsoft/vscode-eslint#1927]
With the release of https://eslint.org/blog/2024/08/eslint-v9.9.0-released/#experimental-typescript-configuration-files, please how would I go about having vscode-eslint load the eslint typescript config file?

`--flag unstable_ts_config` works when using with the CLI.

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/vscode-eslint/issues/1917#issuecomment-2280349929

Closing as dup.
