### ISSUE TITLE
Don't lint deleted files

### ISSUE THREAD

**Issue by paulober** [microsoft/vscode-eslint#1930]
Currently if you delete files locally and they are still open in VS Code. Their names will be strikethrough and red. But if you want to debug your project it will say failed because it detected errors. And in the Problems panel there are multiple errors shown by eslint concerning the deleted files.

**Comment by dbaeumer** [comment]
There is a setting in VS Code that deleted files will close automatically when they are unchanged. If that setting is enabled ESLint extension will not validate the file anymore.
