### ISSUE TITLE
How to configure eslint for a mono repo ? 

### ISSUE THREAD

**Issue by SummySumanth** [microsoft/vscode-eslint#1934]
I have a mono repo, having both frontend and backend in same repository, I want to specify eslint config in respective folders and have those apply in their directory itself (backend config in backend and frontend config in frontend), but eslint plugin in vscode keeps picking `.eslintrc.json` file instead of `eslint.config.js`, how to fix this ?

`my project structure is as following`

```
/.vscode
  └── settings.json
/app
  └── .vite
/backend
  └── eslint.config.js
  └── (files)
/frontend
  └── eslint.config.js
  └── (files)
  ```
  
 `./vscode/settings.json`
  ``` json
  {
    "eslint.workingDirectories": [
        {
            "directory": "../frontend",
            "changeProcessCWD": true,
            "overrideConfigFile": "./../frontend/eslint.config.js"
        },
        {
            "directory": "../backend",
            "changeProcessCWD": true,
            "overrideConfigFile": "./../backend/eslint.config.js"
        }
    ],
}
  ```
  
  `Error in vscode plugin output`
  ```
  [Error - 02:13:46] Request textDocument/diagnostic failed.
  Message: Request textDocument/diagnostic failed with message: Cannot read config file: /project/backend/.eslintrc.json
Error: ENOENT: no such file or directory, open '/project/backend/.eslintrc.json'
  Code: -32603 
  
  ```

_Originally posted by @SummySumanth in https://github.com/eslint/eslint/discussions/18958_

**Comment by dbaeumer** [comment]
"overrideConfigFile" can't be specified on a working directory.

From how I understand your setup a working directory configuration like `["./frontend", "./backend"]` should work

If not please provide me with a GitHub repository I can clone with a minimal setup that demos what you are seeing.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
