### ISSUE TITLE
Eslint working directories use vscode variables

### ISSUE THREAD

**Issue by Judimax** [microsoft/vscode-eslint#1935]
I have an angular library monorepo where each project (component lib) contains tsconfig.lib.json and not tsconfig.json 
can we have something like so I dont have to manually specify the path because the relative path may be different for my coworkers
```
{
  "eslint.workingDirectories": [
    { "mode": "auto" },
    "${workspaceFolder}/angular-libraries",
  ]
}

```

**Comment by dbaeumer** [comment]
Simply use `"./angular-libraries"`. This will make it relative to the workspace folder.
