### ISSUE TITLE
Potential bug in ./server/eslint.ts:864 for determining workspaceFolder

### ISSUE THREAD

**Issue by esmuellert** [microsoft/vscode-eslint#1939]
https://github.com/microsoft/vscode-eslint/blob/b8734bc05119619447a5caf8af0d082cffdec9bb/server/src/eslint.ts#L864
As above, this line uses `inferFilePath` which defined in `eslintServer.ts`:120: 
https://github.com/microsoft/vscode-eslint/blob/b8734bc05119619447a5caf8af0d082cffdec9bb/server/src/eslintServer.ts#L119

The function only works for file but not folder, so for `workspaceFolder` it always return `undefined`, which means `workspaceFolderPath` is always empty? I am using the server with other editor and the workspace directory is always wrong, so I am trying to figure out the reason.

**Comment by dbaeumer** [comment]
> The function only works for file but not folder

Not sure what you mean by this. the check `uri.scheme === 'file'` tests for the `file` schema which includes files and folders. It doesn't test for file versus folder.

**Comment by esmuellert** [comment]
![Image](https://github.com/user-attachments/assets/7e0f383e-deed-47e2-bc1b-165e5459cbe3)
See screenshot. The `scheme` was resolved to `c` for a folder, so it wasn't recognized

**Comment by dbaeumer** [comment]
This is not a valid file URI for a folder path on Windows. How do you construct that URI. The scheme needs to be `file` not `C` and C must be part of the path. The usually look something like this: `file:///C:/Documents/Foo`

**Comment by dbaeumer** [comment]
I will close the issue since this doesn't seem to be a bug in the ESLint server. Please ping if you think otherwise.

**Comment by esmuellert** [comment]
Thanks for the explanation. It's true that I used a wrong uri format, and it works after using the correct one
