### ISSUE TITLE
Incorrect suggestion by ESLint for string replace regex

### ISSUE THREAD

**Issue by linju-json** [microsoft/vscode-eslint#1941]
ESLint is suggesting an incorrect replacement for a valid regex in string replacement. The original code replace(/[\[\]]/g, '') which correctly replaces all occurrences of '[' and ']' in a string is being suggested to be changed to replace(/[[\]]/g, ''). However, this latter expression is an incorrect regex as it causes a syntax error and cannot perform the intended replacement. This seems to be a bug in ESLint's rule or analysis.

**Comment by dbaeumer** [comment]
@linju-json please file rules issues against https://github.com/eslint/eslint. This repository is about the ESLint integration into VS Code is uses the ESLint npm package under the hood.

Please ensure that the error is actually coming from ESLint and not TypeScript, which has a regexp diagnostic as well by running ESLint in the terminal.
