### ISSUE TITLE
Eslint "Warning" Takes over Typescript "Error"

### ISSUE THREAD

**Issue by egucciar** [microsoft/vscode-eslint#1944]
![Image](https://github.com/user-attachments/assets/723fed76-d615-4ee2-bc42-515676581f5a)

In this image above, there is both an eslint warning and a TS error
however, my IDE shows "Yellow" squiggly & yellow in the header/sidebar
making me think there is no TS error

**Comment by dbaeumer** [comment]
TS reports unused locals as warnings as well and it is to my knowledge not configurable

![Image](https://github.com/user-attachments/assets/e54c9d9b-f8b6-47c1-8472-6bc172eac8a5)


Please ping if you see these errors as error.
