### ISSUE TITLE
Extension Process Interval Issue and Busy Cursor Bug with ESLint

### ISSUE THREAD

**Issue by kokororin** [microsoft/vscode-eslint#1952]
The extension process repeatedly calls the following command:

`Code.exe -e "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});" ""`

Additionally, my mouse cursor is continuously in the busy state when the ESLint extension in VSCode is enabled. Disabling ESLint resolves this issue.

![Image](https://github.com/user-attachments/assets/dbfd416b-a6aa-4888-b8bc-e295e8b91360)

**Comment by dbaeumer** [comment]
@kokororin can you provide me with a GitHub repository I can clone with a minimal setup that demos that. The process does some module resolving and should actually only happen once. So there is something special with your setup which I would like to understand.

**Comment by kokororin** [comment]
@dbaeumer Here is a minimal repo: https://github.com/kokororin/eslint-cursor-reproduction

Please refer to the README.md for reproduction steps. Additionally, it's worth mentioning that this issue does not occur when I downgrade VSCode to version 1.93. It only appears in versions above 1.93.

**Comment by dbaeumer** [comment]
I can't reproduce this:

![Image](https://github.com/user-attachments/assets/3f66ff18-7d90-40f1-a603-7e6c49a1b377)

Is there anything special in the ESLint Output view?

**Comment by kokororin** [comment]
@dbaeumer This issue can be reproduced on all my Windows machines. When I set "eslint.debug": "true", the output becomes abnormal, continuously logging without stopping. Please refer to the provided screenshots and log files. If I use VSCode 1.93, the output behaves normally, logging only a few times before stopping. I suspect this might be the root cause of the issue.

![Image](https://github.com/user-attachments/assets/c7b70e16-734c-4183-99b3-5a9919895856)
[eslint-output.log](https://github.com/user-attachments/files/17853999/eslint-output.log)

**Comment by dbaeumer** [comment]
I tried again with a fresh install of VS Code and unable to reproduce. I have currently no idea what is going on especially since the client doesn't show any messages, that the server crashed.

![Image](https://github.com/user-attachments/assets/a1dddfc4-5bc6-4c88-bfbd-a7c7c4e7e0d1)

**Comment by dbaeumer** [comment]
What is strange with the log is the fact that it doesn't contain any information about how long liniting took which is an indication that the linting didn't finish.

**Comment by kokororin** [comment]
After I switched my ESLint config to flat, the problem disappeared.
