### ISSUE TITLE
setting eslint.runtime=node behaves unexpectedly

### ISSUE THREAD

**Issue by runspired** [microsoft/vscode-eslint#1953]
The expectation would be to use the project's node version, available as the `node` executable accessible from the project root. Instead, it loads the system's node version, which is often a different node version for folks using a toolchain manager such as nvm or volta.

**Comment by dbaeumer** [comment]
Actually dups #1727

**Comment by runspired** [comment]
@dbaeumer it doesn't duplicate #1727 because that ticket is saying merely that the default value for `eslint.runtime` should be changed to "node", this ticket is pointing out that the node version resolved by `eslint.runtime=node` is in fact wrong.

**Comment by runspired** [comment]
@thernstig its quite pretty simple:

- the project uses node 22.3
- system has node 18
- vscode has node 20

When not specifying `eslint.runtime`, vscode-eslint boots with the version from vscode.
When specifying `"estlin.runtime": "node"`, vscode-eslint boots with the version from system.

In neither case does it use the version from the project.

**Comment by dbaeumer** [comment]
I will add that to #1727
