### ISSUE TITLE
Enable automatic eslint config searching

### ISSUE THREAD

**Issue by aspirisen** [microsoft/vscode-eslint#1957]
Hello, currently if eslint config is not in the root you have to set `eslint.workingDirectories` property and list all folders with eslint configs.
It would be much easier if vscode could automatically find appropriate esling config, something like typescript does when searching for tsconfig.
Thanks.

**Comment by aspirisen** [comment]
I would like to avoid changing vscode config since it can be under gitignore and there can be different configs per each developer

**Comment by dbaeumer** [comment]
You can add this to the user settings. If nothing else is specified the user settings will be used.

**Comment by aspirisen** [comment]
But developers need to change these settings, and they should know that they have to to do that to make eslint work on their local env. It would be good if eslint could just work out of the box without additional knowledge sharing. 
If eslint vscode extension already have automatic config searching ability then maybe it worth to enable it by default and then no additional changes from users will be required.

**Comment by dbaeumer** [comment]
The automatic config searching has drawbacks as well since eslint is very sensitive to the current working directory (to pick the right config file eslint must run in the right working directory). To not surprise anybody we decided to make this explicit.

**Comment by aspirisen** [comment]
I thought that the logic of where you can put eslint config is pretty much the same as in typescript. That's why I supposed that automatic esling config is possible because typescript somehow manage it, even with several configs with different nesting and cwd
