### ISSUE TITLE
Using local eslint, not global

### ISSUE THREAD

**Issue by BasixKOR** [Microsoft/vscode-eslint#197]
I installed eslint in global and local workspace. but I want to use local eslint in this extension. Is there any options about it?

**Comment by dbaeumer** [comment]
ESLint always prefers a local installed version over a global installed one. Can you provide a workspace that demonstrate the problem since I am not able to reproduce this locally.

**Comment by BasixKOR** [comment]
Well.. It was just my mistake. Sorry!

**Comment by fedegos** [comment]
I'm having the same problem. The eslint command in the terminal is running from global location, not local. I'm using vscode version 1.10.2 and eslint extension 1.2.8.

**Comment by dbaeumer** [comment]
The eslint command in the terminal is honor your path setting which very likely point to the global one. You can always run the local one using `.\node_modules\.bin\eslint`

**Comment by fedegos** [comment]
Thanks! That worked.

I defined the following task for running eslint:

```
{
    "version": "0.1.0",
    "command": "cmd",    
    "isShellCommand": true,
    "args": [ "/C" ],
    "tasks": [
        {
            "taskName": "eslint",
            "suppressTaskName": true,
            "args": [
                "${workspaceRoot}/node_modules/.bin/eslint ."                  
            ],            
            "problemMatcher": [
                "$eslint-stylish"   
            ]
        }
    ]
}
```

Could you confirm if this is correct? I couldn't find any documentation on creating a task for this extension.

**Comment by dbaeumer** [comment]
I updated the doc to provide an example for an eslint task. It looks like this

```
{
	"version": "0.1.0",
	"windows": {
		"command": ".\\node_modules\\.bin\\eslint"
	},
	"linux": {
		"command": "./node_modules/.bin/eslint"
	},
	"osx": {
		"command": "./node_modules/.bin/eslint"
	},
	"isShellCommand": true,
	"args": ["*.js"],
	"showOutput": "silent",
	"problemMatcher": "$eslint-stylish"
}
```
