### ISSUE TITLE
.eslintignore is completely ignored

### ISSUE THREAD

**Issue by cubodehelio** [Microsoft/vscode-eslint#198]
* vscode-eslint: v1.2.3
* eslint: v3.15.0
* vscode v1.9.0
* linux mint 17

The `.eslintignore` file is in the root of the project. `eslint` cli is installed in the workspace and works as expected running `node_modules/.bin/eslint .` but the VSC extension keeps linting all directories including the ignored once and even **node_modules**!

.eslintignore
```txt
public/*
build/*
```

**Comment by dbaeumer** [comment]
I can reproduce this. With the fix I did now an .eslintignore file in the build directory is honored but not a single global one anymore. Need to investigate.

**Comment by dbaeumer** [comment]
I will revert the fix with setting the cwd for now since I think this broke quite some use cases which worked before.
