### ISSUE TITLE
Is there a way to show the error on status bar?

### ISSUE THREAD

**Issue by matheusrocha89** [Microsoft/vscode-eslint#199]
The eslint plugin on vim have a nice feature that if your cursor is on the line of a eslint error it shows the error on status bar, this plugin can do this too?

**Comment by dbaeumer** [comment]
This should be a general concept in VS Code IMO and not implemented by the extensions. I opened https://github.com/Microsoft/vscode/issues/20183

**Comment by matheusrocha89** [comment]
My bad, I thought it was a plugin feature because the vim mode plugin shows which "mode" I am using (Normal, Insert, Visual)
