### ISSUE TITLE
Doesn't support globally installed eslint plugins

### ISSUE THREAD

**Issue by zaggino** [Microsoft/vscode-eslint#2]
I have a plugin specified in my `.eslintrc`:
```
plugins: 
  - "babel"
```
and installed this plugin globally
```
npm install -g eslint-plugin-babel
```
but Code doesn't seem to be able to use it:
![image](https://cloud.githubusercontent.com/assets/1067319/11287220/27077432-8f6e-11e5-9515-f84e42e1139c.png)

**Comment by ksmithbaylor** [comment]
This also seems to be the case for locally-installed eslint plugins (specified in the `package.json` dependencies, not installed with the `-g` flag).

**Comment by nizmow** [comment]
I also get exactly the same problem with the react eslint plugin, was going crazy thinking it was just me. Would be nice to see this supported. I'm going to see if I can do a PR for it sometime soon.

**Comment by dbaeumer** [comment]
@nizmow locally installed plugins should work now. There is a test repository referenced by #9 which uses a react plugin and that now works with the latest eslint extension published (0.10.10). The problem in that case was that the plugin was writing to stdio which is not supported in a electron env. I will look into global plugins as well.

**Comment by dbaeumer** [comment]
Global installed plugins still don't work.

**Comment by dbaeumer** [comment]
Interestingly using a local installed eslint with a global install plugin on a command line isn't working either. 

![capture](https://cloud.githubusercontent.com/assets/1931590/12720303/6d19cb8a-c8fa-11e5-8078-0f98629cf184.png)

**Comment by dbaeumer** [comment]
Since the vscode-eslint extension is using the available eslint api there is nothing I can do to make this work.
