### ISSUE TITLE
Don't lint git diff.

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/vscode-eslint#200]
![2017-02-08 15_51_07](https://cloud.githubusercontent.com/assets/15059605/22727967/7cd8ce30-ee16-11e6-9913-9d99563d0ea5.gif)

**Comment by dbaeumer** [comment]
This actually requires work in VS Code.

**Comment by sgal** [comment]
@dbaeumer Is there any issue in VSCode repo that could be linked here? I'm having similar issue and it's super annoying singe it's a tooltip error that comes from above (using ES6 modules and babel).

![image](https://cloud.githubusercontent.com/assets/2971261/23397799/5134d434-fd9a-11e6-8c69-ba7d7a43c075.png)

**Comment by dbaeumer** [comment]
The discussion in VS Code takes place here: https://github.com/Microsoft/vscode/issues/20859
