### ISSUE TITLE
baseDir should be an absolute path

### ISSUE THREAD

**Issue by stephen-hardy** [Microsoft/vscode-eslint#202]
When opening a JavaScript file hosted on SharePoint, accessed on Windows via WebDav, I get the following error on load and every time I type:

"baseDir should be an absolute path"

I don't think I saw this before v1.2.4. Everything was working well, until a couple days ago. Is this a configuration issue?

**Comment by dbaeumer** [comment]
ESLint has no configuration property baseDir, but TypeScript has which provides the JS smartness in VS Code.

Does this happen if you disable ESLint for the workspace? Which version of VS Code are you using?

**Comment by stephen-hardy** [comment]
Hi, thanks for the reply!

I just updated to 1.9.1 this morning, and the issue persists. I'm still getting to know VSCode, having switched from Sublime, but I don't believe I can disable ESLint for the workspace because I'm not opening a folder - just a file. However, I tried disabling the extension altogether. When I did that, the error went away. When I re-enabled the extension, it came back.

I used to get errors and warnings, but now it is just 0 and 0. And, the "ESLint" on the right side in the status bar is greyed out. When I open the OUTPUT for ESLint I see:

[Info  - 9:57:31 AM] ESLint server is running.
[Info  - 9:57:33 AM] ESLint library loaded from: C:\Users\v-sthard\AppData\Roaming\npm\node_modules\eslint\lib\api.js

Also, it may be worth noting that this started happening days after I upgraded to v1.9.0 of VSCode. It worked well for a number of days, then stopped with the last two updates to ESLint.

Let me know if I can provide any other logs or diagnostic information.

Thanks,
Stephen

**Comment by dbaeumer** [comment]
@stephen-hardy can you provide me a little more information about you setup:

- which eslint version do you have installed
- how does your eslintrc file look like
- can you provide me with the content of the JS file you are validating

And could you enable eslint tracing to get more information. To do so please set the user settings `"eslint.trace.server": "verbose"` and attach the output of ESLint channel here.

**Comment by dbaeumer** [comment]
@stephen-hardy I think I know what is going on. How does the path of the file look like. Is it a UNC path or is the server directory mounted as a drive letter?

**Comment by dbaeumer** [comment]
In noder `path.isAbsolute('\\192.168.1.2\folder\test.txt')`evaluates to true. But I guess that the path you are using is not consider an absolute path hence resulting in an exception in this piece of ESLint code from `path-util.js`:

```js
function getRelativePath(filepath, baseDir) {
    let relativePath;

    if (!path.isAbsolute(filepath)) {
        filepath = path.resolve(filepath);
    }
    if (baseDir) {
        if (!path.isAbsolute(baseDir)) {
            throw new Error("baseDir should be an absolute path");
        }
        relativePath = path.relative(baseDir, filepath);
    } else {
        relativePath = filepath.replace(/^\//, "");
    }
    return relativePath;
}
```

The change in ESLint that causes the problem is: 
```js
		} else if (!workspaceRoot) {
			let dirname = path.dirname(file);
			if (dirname) {
				newOptions.cwd = dirname;
			}
		}
```

**Comment by stephen-hardy** [comment]
Correct, the file does have a UNC path:

\\microsoft.sharepoint.com@SSL\DavWWWRoot\teams\...

I'm currently on version 1.2.5, and a blank js file will cause the error.

**Comment by dbaeumer** [comment]
Thanks. What is wired is that `path.isAbsolute('\\microsoft.sharepoint.com@SSL\DavWWWRoot')` evaluates to true. @stephen-hardy can you sent me the full path to my MS email address. Then I can have a look and see why this fails.

**Comment by stephen-hardy** [comment]
Done!

Using a mapped drive works, just in case anybody is looking for a workaround. But then, unfortunately, TypeScript breaks (I opened the issue referenced directly above). So, if you want TypeScript you can open the file directly (as of VSCode 1.9.1), or if you want ESLint you can map a drive.

**Comment by dbaeumer** [comment]
OK. The underlying problem is that 
`path.dirname('\\microsoft.sharepoint.com@SSL\DavWWWRoot\teams\myteam\myFile.js')` returns `\\` which is clearly not the directory containing the file. Need to see how I best handle this.

@stephen-hardy what error do you get with TS on a mapped network drive.

**Comment by stephen-hardy** [comment]
Best described here: https://github.com/Microsoft/TypeScript/issues/13997

**Comment by stephen-hardy** [comment]
Also, just wanted to confirm that this is fixed. Finally, TypeScript and ESLint working using the same method. :) Thanks for all your help!
