### ISSUE TITLE
Move the 'Release Notes' inside the separate 'Changelog' tab

### ISSUE THREAD

**Issue by darkred** [Microsoft/vscode-eslint#204]
Currently the 'Release Notes' for every version of the extension
is listed inside the 'Details' tab of the Extensions view (Ctrl+Shift+X):
![2017-02-10_144024](https://cloud.githubusercontent.com/assets/723651/22827158/0e86a0e4-ef9f-11e6-88e9-50ded861b3b6.jpg)

I'd suggest moving them inside the separate 'Changelog' tab:
![2017-02-10_144213](https://cloud.githubusercontent.com/assets/723651/22827185/26f2ae5c-ef9f-11e6-916c-8b47690820fd.jpg)

As you may see from the 1st screenshot, the Release Notes currently appear near the bottom of the initially visible part of the Details view (in my 1920x1200 display)
therefore they are not very discoverable.

<br>

The above will be possible by moving the 'Release Notes' part in the extension package  
from inside `eslint/README.md` to a seperate `eslint/CHANGELOG.md`.
_The extra "Changelog" tab was added in VSCode in v1.6._

**Comment by darkred** [comment]
I've made this pull request: #205.

**Comment by dbaeumer** [comment]
Thanks for the PR. Merged.
