### ISSUE TITLE
Eslint not using Package.json config 

### ISSUE THREAD

**Issue by afaayerhan** [Microsoft/vscode-eslint#207]
to reproduce this problem just download this boilerplate which configures eslint in package.json no eslintrc  https://github.com/react-boilerplate/react-boilerplate everything works fine in comand line and in webstorm but in vscode it does not it just lebels errors based on config that i don't know where the are coming from

**Comment by dbaeumer** [comment]
This works for me. I cloned the repository run npm install. Here is what I get. I honors the package.json config and even hot updates as expected. ESLint extension version is 1.2.6

![cast](https://cloud.githubusercontent.com/assets/1931590/23360734/6e174080-fced-11e6-89ae-a2a13a519858.gif)

Any additional information?

**Comment by carlosvillu** [comment]
hi @dbaeumer 
I have the same issue, but using the key `eslintConfig` in the package.json.

The config file is ignored :(

![captura de pantalla 2017-03-02 a las 10 33 54](https://cloud.githubusercontent.com/assets/179462/23501424/176319b4-ff34-11e6-94a6-0c95383cb4f2.png)

Thx!

**Comment by dbaeumer** [comment]
@carlosvillu that looks different than the one reported from @afaayerhan 

Can you please open a new issue with steps to reproduce. Best would be a GitHub repository I could clone.

**Comment by n0f3** [comment]
@carlosvillu I seem to be having the same issue where a eslint doesn't load locally and I have to specify it every time in the workspace settings. is that also what you're experiencing?

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
