### ISSUE TITLE
Info, warning, or error?

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-eslint#211]
This happened when I deleted `node_modules`.

![image](https://cloud.githubusercontent.com/assets/22350/23514706/68b7ca38-ff68-11e6-89df-97863f41ee0c.png)

```
Cannot read config file: /Users/joao/Work/vscode/node_modules/eslint/conf/eslint-recommended.js Error: ENOENT: no such file or directory, open '/Users/joao/Work/vscode/node_modules/eslint/conf/eslint-recommended.js' Referenced from: /Users/joao/Work/vscode/src/.eslintrc
```

IMO this shouldn't be anything. It should be silent.

**Comment by dbaeumer** [comment]
These messages are now all put into the ESLint output channel.
