### ISSUE TITLE
doesn't fix errors correctly first time

### ISSUE THREAD

**Issue by lukejpreston** [Microsoft/vscode-eslint#213]
I have `"eslint.autoFixOnSave": true` and if the file has multiple eslint errors, nested as in example then it will fix it a little but still be incorrect. Then to get around this problem you have to introduce a new error and save again. Atom solves this by running lint every time you save, maybe this should do it as well but I feel it should keep trying on auto save until the file looks the same as it did previous fix (i.e. something which can not be auto fixed)

here is an example save -> still wrong -> change file by adding a space -> less wrong -> repeat until correct

![mar-09-2017 15-16-39](https://cloud.githubusercontent.com/assets/4129128/23756480/b2947606-04db-11e7-84cf-cea6ef6a9c79.gif)

**Comment by dbaeumer** [comment]
Dups #154
