### ISSUE TITLE
differentiate between syntax errors and style errors

### ISSUE THREAD

**Issue by gilesbradshaw** [Microsoft/vscode-eslint#217]
Could you underline proper syntax errors in say red and style errors in a different colour like yellow?

That would be massively helpful as the red underline pops up for example when you declare a parameter and before you use it.

**Comment by dbaeumer** [comment]
This is something you can control in your .eslintrc. For every check you can define whether it will be an error or a warning. We render warnings with a green underline but are considering to change this to yellow.
