### ISSUE TITLE
Make linting error indicator configurable

### ISSUE THREAD

**Issue by nerdbeere** [Microsoft/vscode-eslint#218]
Hi there,

it would be super cool if I could change how the error is displayed.
Currently I'm using the theme "One Monokai Theme" and the error for me is almost invisible.

<img width="329" alt="screen shot 2017-03-17 at 12 15 17" src="https://cloud.githubusercontent.com/assets/423218/24040963/bfbbbd4a-0b0b-11e7-80be-015035728081.png">

Feature request:
Let the user choose a background and a foreground color for the character

Example from IntelliJ:
<img width="303" alt="screen shot 2017-03-17 at 12 22 27" src="https://cloud.githubusercontent.com/assets/423218/24041151/6afc4eae-0b0c-11e7-9160-658d07d354de.png">

**Comment by alexgorbatchev** [comment]
I would like to second this request. No lint issues is a pre-commit hook on the project I'm working on. It would be ideal for me to highlight whole line in bright red or something equally as obvious.

**Comment by dbaeumer** [comment]
@nerdbeere @alexgorbatchev please open an issue against VSCode (https://github.com/Microsoft/vscode). The ESLint simply creates diagnostic object with a severity. The extension doesn't have any logic in terms of colors.
