### ISSUE TITLE
ESLint not loading local config unless you specify nodePath local

### ISSUE THREAD

**Issue by n0f3** [Microsoft/vscode-eslint#220]
Hello,
not sure if this is intended behavior, but I have a globally installed instance of eslint and when I try to install eslint locally and load it from my local folder, ESLint in vscode will always prioritize the global installation found under %USERPROFILE%/AppData/Roaming/npm.

I have installed Node using the regular windows install:

- Node version 6.9.1
- npm version 4.4.1
- eslint global version 3.17.1
- eslint local version 3.12.2

In order to override that behavior I have to include "eslint.nodePath": "./node_modules" in the settings of each workspace that I want to load eslint locally, or I have to uninstall the global eslint instance, which is not desired.

Is this a known issue? Or is it something with my configuration?

**Comment by dbaeumer** [comment]
This works for me without a problem. ESLint extension always prefers a local install eslint over a global one. Can you share a reproducible case (a git repository) that demos the behaviour?

**Comment by n0f3** [comment]
Hi @dbaeumer it seems to happen for create react app applications, but it's been documented to be a problem within eslint itself. We can probably close this, I'll open up another issue if I see more weird behaviours. Thanks for the reply!
