### ISSUE TITLE
ESLint auto fix on save

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode-eslint#221]
Hello,

ESLint auto fix on save not working if you're using `"files.autoSave": "afterDelay"`. Only works if you're pressing `CTRL + S`. It will be very good if it will work with `files.autoSave` setting without pressing `CTRL + S`.

VS Code: 1.10.2
OS: Linux Ubuntu 16.04
ESLint installed localy: 3.18.0
ESLint plugin: 1.2.7

**Comment by svipben** [comment]
Sorry, my fault, just read the docs and found this:

> eslint.autoFixOnSave - enables auto fix on save. Please note auto fix on save is only available if VS Code's files.autoSave is either off, onFocusChange or onWindowChange. It will not work with afterDelay.

**Comment by dbaeumer** [comment]
I will close. The afterDelay will cause problems with both the user typing and eslint computing fixes. This is why this can only be trigger using Ctrl+S in this case.
