### ISSUE TITLE
Link to specific eslint rule in tooltip

### ISSUE THREAD

**Issue by edwinwright** [Microsoft/vscode-eslint#223]
I'm coming from Atom and have found that having a link to the specific failing eslint rule (http://eslint.org/docs/rules/) in the tooltip has been very useful.

If you're not familiar with the ruleset being enforced, then having a reference to hand helps explain what you're doing wrong. Useful for new starters to the dev team or when implementing a third party configuration.

![eslint-rule-link](https://cloud.githubusercontent.com/assets/1699539/24354710/d208e75c-12ea-11e7-905f-bb5ad24940a1.png)

**Comment by dbaeumer** [comment]
Good idea and we have a issue for this in VS Code repository since the support needs to be enabled there first. See https://github.com/Microsoft/vscode/issues/11847
