### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by Rojoss** [Microsoft/vscode-eslint#224]
Every time I type and/or save a file I get the following message which is quite frustrating.
![image](https://cloud.githubusercontent.com/assets/1093861/24407650/d7ed9a96-13cb-11e7-8a94-9ff906dd3bf7.png)

I disabled all extensions then it went away, so I re-enabled them till I found out that it was  eslint.
I've done some research and found that it might be related to ``eslint.nodePath`` setting.
However, I'm not entire sure what to put there I tried several things and none fix the issue.

None of the eslint settings have been modified in vscode.
This is our ``package.json`` file: https://gist.github.com/Rojoss/416dd4474ccbdd7d1cc2237b6e124214

If you need any other information let me know would love to see this fixed.

**Here is the full stack trace from the console.**
```
messageService.ts:126 Cannot read property 'type' of null
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
(anonymous function) @ mainThreadMessageService.ts:64
n.Class.derive._oncancel @ winjs.base.raw.js:1641
t.showMessage @ mainThreadMessageService.ts:34
t.$showMessage @ mainThreadMessageService.ts:28
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by dbaeumer** [comment]
I thought I fixed this a while ago. Which version of ESLint extension and VS Code are you using?

Can you share the whole project? Would help to investigate why you see this.

**Comment by Rojoss** [comment]
Ugh, I didn't get a notification for this so I'm sorry for the extremely late reply.

**ESLint** version is ``3.19.0``
**VSCode** is the latest version ``1.11.2``

I'm not really able to share the project as it's private for work.
If it's really needed I could probably set up a repo with a similar project to reproduce the issue.

Hopefully I'll be able to receive notifications next time.

**Comment by dbaeumer** [comment]
@Rojoss you need to update the ESLint VS Code extension as well (1.2.8 is latest).

Will close if you can still reproduce the error on latest setup.

**Comment by ylg** [comment]
Since this has been happening for us from 1.11.2 through 1.2.11, @Rojoss' silence likely didn't mean "fixed". If more help is needed with reproduction steps, let me know.
