### ISSUE TITLE
Static property initializers linting error

### ISSUE THREAD

**Issue by fsmaia** [Microsoft/vscode-eslint#226]
By using ESLint with `babel-eslint` I'm getting `no-undef` errors when using [static property initializers](https://babeljs.io/docs/plugins/transform-class-properties/).

My `.eslintrc` is setting `babel-eslint` properly and `.babelrc` is also well configured.

When running ESLint from CLI these errors aren't listed.

**Comment by dbaeumer** [comment]
@fsmaia can you share a workspace that demos the problem ?

**Comment by fsmaia** [comment]
Sorry, it was solved when I bumped all versions in package.json. Probably it was a conflict between versions.

**Comment by dbaeumer** [comment]
Thanks.
