### ISSUE TITLE
Linting not running on jsx files

### ISSUE THREAD

**Issue by cdb** [Microsoft/vscode-eslint#227]
It may be something in my setup, but AFAIK nothing has changed. Linting has stopped running on JSX files, where I am pretty sure it did in the recent past (I got a VSCode update recently)

When I run `./node_modules/.bin/eslint --ext .js,.jsx src test` locally it finds issues in .jsx files, however not within the VSCode "Problems" tab

I went into my VSCode settings and have added ```    "eslint.options": {
      "extensions": [".jsx", ".js"]
    }``` and that isn't helping either.

Am I doing it wrong?

**Comment by Venryx** [comment]
Does putting this in your settings.json file help? (it worked for me, to enable in typescript (ts/tsx) files)

```
"eslint.validate": [
		"javascript",
		"javascriptreact",
		"typescript",
		"typescriptreact"
		//{"language": "html", "autoFix": true},
	]
```

**Comment by dbaeumer** [comment]
The default `"eslint.validate"` value is `["javascript", "javascriptreact"]` so out of the box jsx files should be validated. However if you specify  `"eslint.validate"` in your settings you need to list all languages you want to validate.

**Comment by dbaeumer** [comment]
I tested this with VS Code 1.11 and ESLint 1.2.8 and it works as expected.

Will close the issue. @cdb if you still see problems here can you please provide a workspace I can use to reproduce this.

**Comment by cdb** [comment]
FWIW, I found out the issue...my `*.jsx` files were being classified as `JSX` instead of `Javascript React`, I believe due to another extension I had added. I removed the extension (but was also fixed by just adding 'jsx' to the  `eslint.validate` settings as you had suggested @dbaeumer - thanks!

Had a fun time learning how to run an extension in the Extension Development Host and debug it along the way, which was fun :)

**Comment by dbaeumer** [comment]
Cool. Then you are all set to write your first extension and publish it to the market place :-)

**Comment by touzoku** [comment]
@dbaeumer I would like to reopen the issue.

I'm authoring a plugin for Visualforce (Salesforce flavor of JSP pages). VSCode Visualforce plugin adds `Visualforce (visualforce)` language support, so I have configured eslint plugin like follows:
```json
{
    "eslint.options": {
        "extensions": [
            ".page",
            ".js"
        ]
    },
    "eslint.validate": [
        "javascript",
        "visualforce"
    ],
    "eslint.autoFixOnSave": true
}
```

This configuration works for linting as expected — the editor highlights the issues correctly, but autofixing does not work: neither on save, nor explicitly through running "Fix all auto-fixable problems".

![screen shot 2017-07-26 at 16 49 07](https://user-images.githubusercontent.com/1285662/28610409-3555504c-7223-11e7-9b00-5a324b07ae15.png)

If I manually specify the language as Javascript in the editor — both linting and fixing start to work but the linter starts interpreting HTML tags as JSX, which is not desired (notice the presence of the yellow lightbulb and an extra highlight under `<apex:page>`).

<img width="793" alt="screen shot 2017-07-26 at 16 57 33" src="https://user-images.githubusercontent.com/1285662/28610522-94f43216-7223-11e7-96ed-274041ea17d0.png">

Running `./node_modules/.bin/eslint --ext page --fix fixme.page` manually works as expected.

How to convince your plugin to autofix visualforce language with `.page` extension?

**Comment by dbaeumer** [comment]
@touzoku See my comments in https://github.com/Microsoft/vscode-eslint/issues/271
