### ISSUE TITLE
Eslint not working for version 0.22.1 

### ISSUE THREAD

**Issue by danpaz** [Microsoft/vscode-eslint#23]
Just noticed my eslint rules in .eslintrc are not being recognized when using eslint version 0.22.1. Worked fine when I upgraded to 1.9.0. Any ideas what might cause this?

**Comment by dbaeumer** [comment]
Frankly speaking I never tried using older versions of eslint. The eslint extension is using eslint as a library calling some of its public API. According to the ESLint documentation the API we are using is only available from 1.0.0 on forward.
