### ISSUE TITLE
ESLINT configuration declared in package.json is not recognised

### ISSUE THREAD

**Issue by anilreddykatta** [Microsoft/vscode-eslint#230]
In `create-react-app` which adds `eslintConfig` to `package.json` is not recognised. When I create  `.eslintrc` with exact configuration it works. 

[https://github.com/facebookincubator/create-react-app/issues/1955](https://github.com/facebookincubator/create-react-app/issues/1955)

**Comment by dbaeumer** [comment]
See my comments in facebookincubator/create-react-app#1955

**Comment by dbaeumer** [comment]
@anilreddykatta I will close the issue. The work should happen in `create-react-app`.
