### ISSUE TITLE
"Cannot read config file..." error when editing eslintrc.json

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-eslint#232]
AutoSave is on

As soon as i start editing `.eslintrc.json` i get an info popup message that i have to constantly dismiss.  I know its not valid, i'm not done editing :).

![image](https://cloud.githubusercontent.com/assets/1487073/25558248/8a0a7a0e-2cd7-11e7-9272-98aaf2c7b45c.png)

**Comment by dbaeumer** [comment]
Instead of showing a message I should report a problem marker.

**Comment by Dogyunjeong** [comment]
I have the same error.  I used Vue-cli and generated project folder with eslint option.

There is '.eslintr.js' file and vscode show the same info message.

**Comment by dbaeumer** [comment]
Actually this got fixed a while ago. The message is now presented in the output window without bringing the window to front. As soon as the file is valid again files get revalidated.

**Comment by dbaeumer** [comment]
@Dogyunjeong if you still see the dialog can you please provide a GitHub repository I can clone that demos the behavior with steps on how to reproduce.
