### ISSUE TITLE
"Path must be a string. Received undefined" on unsaved files

### ISSUE THREAD

**Issue by ProLoser** [Microsoft/vscode-eslint#233]
I repeatedly see this error on every keypress when working with unsaved files that don't exist on disk. Are you not sending a blob of the current session (and not just what's saved to disk)? Perhaps new editor panels that are unsaved (aka: `Untitled-*` files) should be ignored until they are saved to disk and renamed?

**Comment by dbaeumer** [comment]
This is a problem with older eslint npm modules. Please update to a newer version of eslint (https://www.npmjs.com/package/eslint) not ESLint VS Code extension. 

![cast](https://cloud.githubusercontent.com/assets/1931590/25944416/823d23ec-3643-11e7-8bcc-e96d0c3f1068.gif)
