### ISSUE TITLE
[eslint] Parsing error: Unexpected token

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-eslint#234]
_From @AkashiX on May 4, 2017 14:14_

- VSCode Version: 1.11.1
- OS Version: Win 10

I get this error when using async/await keywords to declare a function, what's matter? by the way, I had installed eslint plugin inside Vscode.

_Copied from original issue: Microsoft/vscode#25896_

**Comment by mjbvz** [comment]
@AkashiX What version of eslint are you using? Can you share some example code?

**Comment by dbaeumer** [comment]
This error usually indicates a problem with your ESLint config file like .eslintrc.json.

I am closing the issue. Please share and example if the explanation is not solving your problem.
