### ISSUE TITLE
Lint problems don't show up in editor.

### ISSUE THREAD

**Issue by chenxsan** [Microsoft/vscode-eslint#236]
I'm running VSCode insider 1.13.0 on macOS 10.12.4.

![vscode-eslint](https://cloud.githubusercontent.com/assets/1091472/25839964/799fe4d6-34cc-11e7-898a-66da54669b03.gif)

As you can see in the gif, when we have `Unexpected token (4, 1)`, there's no red mark inside the editor as other ranges.

**Comment by dbaeumer** [comment]
This is a problem of the editor partly understandable.

Since line 4 has no character but eslint reports an error on [4,1] there is no character to underline. Moving to VS Code to discuss whether we can do something in the editor about it.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode#26446
