### ISSUE TITLE
Error: Cannot find module 'array-union' 

### ISSUE THREAD

**Issue by Irnis18** [Microsoft/vscode-eslint#237]
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: OSX - macOS Sierra - iMac

Vcode:  Developer toggle developer tools - Console:
 `messageService.ts:126 Cannot find module 'array-union'e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] Sumary:`

I don't get this when i disable eslint on vscode. I get a popup every time i enter a file .js file on my project, except one of them.
<img width="1037" alt="screen shot 2017-04-21 at 13 04 31" src="https://cloud.githubusercontent.com/assets/21169278/25274956/1b7ae866-2693-11e7-946e-d72ffc93c5dc.png">
i don't have a clue why this pops up, the array-union is in the node_modules. I am using react and redux in my project. i don't know what more information is needed so please tell if there are anything.

**Comment by dbaeumer** [comment]
@Irnis18 can you share your workspace.

I looks like ESLint can't find 'array-union' which it needs to validate js files. What happens if you run eslint form the terminal with the JS file that produces the error from your workspace folder?

**Comment by Irnis18** [comment]
Basically it happens to every .js files on my project, when i try running eslint with the js file in the terminal, nothing happens. I just did eslint  filename.js on one random js file in my project. So everytime i enter a js file in that project i get the Error Cannot find module 'array-union'. @dbaeumer, tell me if it didn't make sense.

**Comment by dbaeumer** [comment]
@Irnis18 it does make sense but I still can't reproduce this. There is one additional thing to consider. ESlint itself and the plugins it used must both be either installed globally or locally. The VS Code ESLint extension prefers a local install eslint over a global one. Could it be that you have eslint installed in your workspace but not the array-union plugin and that when you execute eslint in the terminal you use the global one. You can always try in the workspace something like `./node_modules/.bin/eslint` to use the local one from the terminal.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
