### ISSUE TITLE
Settings to override which eslint installation is used

### ISSUE THREAD

**Issue by TheMaxMarchuk** [Microsoft/vscode-eslint#243]
Since I'm using eslint for vscode I like to keep my eslint installation and plugins installed globally. Sometimes when I'm working on a project that has a local installation of eslint, I want to be able to configure vscode to use the global installation instead, that way all of my plugins can be installed globally instead of locally. An example use case would be when working on projects created with create-react-app, which have a package called react-scripts installed which depends on eslint and runs it (with very specific configuration) before the project is ran through webpack. It would be very useful for vscode, in that situation, to ignore the local installation and use the global one instead. That way it would be possible to separate custom linting in the editor, and other linting at build time.

It would be nice for us to be able to specify something like `{ eslint.useInstallation: 'global' }`
Alternatively it might be a better idea to allow users to specify a direct path to the eslint installation, much like the `eslint.nodePath` option. However this setting would stop the extension from looking in other locations for an installation. In any event, I think an option along the lines of `{  eslint.pathOverride: 'path/to/eslint/bin'}` would be very useful.

**Comment by dbaeumer** [comment]
@TheMaxMarchuk this option exists: it is eslint.nodePath. If set the extension will prefer it over a local or global install eslint.

Please give it a try. If it doesn't help you please ping in this issue.
