### ISSUE TITLE
Identify target file in error message

### ISSUE THREAD

**Issue by CodeCharm** [microsoft/vscode-eslint#249]
First, I'll admit that I'm not 100% sure that an error message I saw came from this extension.

But I'm about 95% sure it did.

The error message looks like this:
![screenshot](https://i.stack.imgur.com/LThSY.png)

Notice that the error message gives me absolutely no idea which file had the problem that it's reporting. It doesn't even tell me what line the message is from, but even a file name would be a big step forward.

Furthermore, I think it would be a great idea if the error message was prefaced or suffixed with an indicator that it came from this extension or from eslint. I have a lot of extensions because I do much more than just JavaScript/ECMAScript development.

**Comment by dbaeumer** [comment]
@CodeCharm this looks like an exception that is throw by an eslint plugin. Can you reproduce this? If so does it happen when you run eslint from the terminal as well. Is the error message more descriptive in this case?

**Comment by CodeCharm** [comment]
@dbaeumer Ever since I fixed up some launch settings in VSCode, I have not been reproducing this. I had been relying on a gulp task to run eslint. Some of the plugins are from a pregenerated template that was given to me from other in-house assets. Just glancing inside node_modules, it looks like I have the eslint-plugin-angular and eslint-plugin-react plugins. I'm not using react, but it's a dependency of something-something-deep-in-the-I-don't-care.

But I don't need help fixing this particular error, if that's what you're after...? What I was really trying to address is that it would have been a lot more helpful if I had known at least one bit more of information, and possibly two more.

The first most helpful thing might already be addressed by an upcoming feature-request in VSCode: https://github.com/Microsoft/vscode/issues/21302 -- knowing which VSCode extension generated this message. For someone new to angular/eslint/gulp/etc. like me, anonymously-sourced messages are hateful little things.

The second bit of information that would be more helpful would have been an indication of which file was being examined. Perhaps that's not available if you're just spawning out to eslint and this is all you get back. But context matters for error messages, and this one is annoyingly ambiguous.

So, I'm floating the idea that this could be a feature request. Is it realistic, or not so much?

**Comment by dbaeumer** [comment]
I agree that having an indication in the message that hints to the fact that it comes from the ESLint extension will be very help. I accept this as a feature request.

**Comment by CodeCharm** [comment]
Cool! I haven't looked into the code -- is it a big lift to get the filename integrated into the error message?

**Comment by dbaeumer** [comment]
No, should not be too complicated. The code is here: https://github.com/Microsoft/vscode-eslint/blob/master/eslint-server\src\server.ts#L803
