### ISSUE TITLE
Illegal token "http" in template string

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode-eslint#25]
![image](https://cloud.githubusercontent.com/assets/3254987/12684612/baaed1f2-c674-11e5-8a95-235953a4440a.png)

The link is in blue because I am pressing [ctrl]+[cmd]+[shift] to get the screenshot. Normally it looked like this:
![image](https://cloud.githubusercontent.com/assets/3254987/12684661/f5879804-c674-11e5-87ae-bddf845561ae.png)

Validated it is eslint extension issue.
Redirect from https://github.com/Microsoft/vscode/issues/2556

**Comment by dbaeumer** [comment]
@unional which version of eslint are you using?

**Comment by unional** [comment]
0.10.11 extension

**Comment by unional** [comment]
@dbaeumer do you need other info?

**Comment by mysticatea** [comment]
@unional I guess he is asking the version of eslint you are using, not extension. From me, do you get the same result when you use CLI?

**Comment by dbaeumer** [comment]
I can't reproduce this. I tried with VSCode Insider 0.10.15 and eslint 2.7.0. Please ping if you still see the issue and provide me with the eslint version. I suspect a config issue in eslint with template strings which is a new JS concept.

![capture](https://cloud.githubusercontent.com/assets/1931590/14508120/59d74b88-01c6-11e6-8eb3-4ba46d340105.png)

**Comment by unional** [comment]
I think it has been fixed since then. Thanks!
