### ISSUE TITLE
Error: Cannot find module 'locate-path'

### ISSUE THREAD

**Issue by mcmunder** [Microsoft/vscode-eslint#253]
### my setup and config:

vscode: 1.13.1
vscode-eslint: 1.2.11
ESlint version: 4.0.0
Node version: 8.1.2
npm version: 5.0.3
parser: babel-eslint

.eslintrc.json:
```
{
  "extends": [
    "standard",
    "standard-react"
  ],
  "parser": "babel-eslint",
  "plugins": [
    "promise",
    "import"
  ],
  "rules": {
    "object-curly-spacing": 2,
    "import/no-unresolved": 2,
    "import/named": 2,
    "import/namespace": 2,
    "import/default": 2,
    "import/export": 2
  },
  "env": {
    "browser": true,
    "jest": true
  }
}
```
Please be aware that this is in a create-react-app project so I do not know what other (eslint) magic might be going on behind the scenes.

### issue
I am opening a new file in vscode and editor throws an error:
`Error Cannot find module 'locate-path'`

Hope this is enough information to get an idea what might be the issue...

Getting the same error in Atom with the eslint plugin by the way with a bit more of a stack trace:
`[Linter] Error running ESLint Error: Cannot find module 'locate-path' linter-registry.js [sm]:137`

**Comment by sseiber** [comment]
I just started getting this error:
I had a sub-package in my project that used `eslint-plugin-import`
If I cd into that sub-package and `npm ls locate-path` it returned:
```
└─┬ eslint-plugin-import@2.6.1
  └─┬ read-pkg-up@2.0.0
    └─┬ find-up@2.1.0
      └── locate-path@2.0.0
```
When I did it from the root of my project I got:
```
└── (empty)
```

This fixed it and restored the dependency:
`npm uninstall --save-dev eslint-plugin-import`
`npm install --save-dev eslint-plugin-import`

**Comment by dbaeumer** [comment]
@mcmunder is this still an issue for you. If so can you provide a GitHub repository that demos the problem with steps to reproduce.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
