### ISSUE TITLE
'Fix all auto-fixable problems' added a comma an end of params Incorrectly

### ISSUE THREAD

**Issue by liangzr** [Microsoft/vscode-eslint#258]
before:
```
const foo = (
  propA => (
  ),
  propB => {
  }
);
```
after:
```
const foo = (
  propA => (
  ),
  propB => {
  },     //here is not allowed
);
```
auto-fix always add this comma, that can make mistake under node 6.+ LTS (node 8.+ seems all right)

**Comment by liangzr** [comment]
>JavaScript has allowed trailing commas in array literals since the beginning, and later added them to object literals (ECMAScript 5) and most recently (ECMAScript 2017) to function parameters.
ref: [Trailing commas](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas)

it does as a new feature in ECMAScript 2017，but I can not use it in production env with node LTS

**Comment by dbaeumer** [comment]
The plugin applies the auto fixes provided by the eslint node module. Can you please file the issue here: https://github.com/eslint/eslint. Thanks!
