### ISSUE TITLE
Configuration error: Configuration for rule "indent" is invalid: Value "error" must be an enum value. 

### ISSUE THREAD

**Issue by EthanNYT** [Microsoft/vscode-eslint#259]
eslint installed version is 4.2.0
eslint plugin version is 1.2.11
pc is running OSX 10.12.5

I created a local eslint.json file using `eslint --init`

Now I receive this error when opening vscode:

>Configuration for rule "indent" is invalid: Value "error" must be an enum value. 

What is the correct format for the config file, if it is not the one generated by eslint itself?

**Comment by dbaeumer** [comment]
@EthanNYT I can not reproduce this. Can you provide your `eslint` config file.

**Comment by mehas** [comment]
@dbaeumer Thank your for responding, updating to ESLint 5.3.0 appears to have solved the issue, please close it.

**Comment by EthanNYT** [comment]
@dbaeumer Thank your for responding, updating to ESLint 5.3.0 appears to have solved the issue, please close it.

**Comment by dbaeumer** [comment]
@EthanNYT  Thanks. Closing.
