### ISSUE TITLE
"Failed to load eslint library" not expected on project not using eslint

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode-eslint#26]
I uses eslint on one project so installed it locally along with this plugin.

When I open another project not using eslint I get this annoying error. 

The error make no sense unless you install eslint globally. I always install all dependencies locally, not globally as that makes config easier to repro - just run `npm install`

**Comment by dbaeumer** [comment]
A workaround for now is to disable eslint globally in the user settings and enable it in the workspace settings you want. I like the idea to be smarter here and only prompt once and then activate eslint only if a eslint is found (locally or globally).

**Comment by SteveALee** [comment]
Ah, good idea. Will try. Thanks.

**Comment by mikekidder** [comment]
Thanks, I forgot the options between User/Workspace settings myself.  Prevents having to install globally.  Its a good workaround for now.  

Think Atom IDE plugin for ESLint is automatic; disabled when doesn't find an .eslintrc.* file.

**Comment by dbaeumer** [comment]
This got addressedin latest versions. ESLint no logs to the output and only shows the output once per workspace. After that it is quite.
