### ISSUE TITLE
path of debugging if it does not lint

### ISSUE THREAD

**Issue by toyflish** [Microsoft/vscode-eslint#260]
Hi,
I have eslint installed globally and in my project.
I have an .eslintrc in my folder.
i have installed eslint extension to vscode.
I have it enabled in the preferences.
```
// Controls whether eslint is enabled for JavaScript files or not.
  "eslint.enable": true,

  // A path added to NODE_PATH when resolving the eslint module.
  "eslint.nodePath": null,

  // Uses the legacy module resolving.
  "eslint._legacyModuleResolve": false,

  // The eslint options object to provide args normally passed to eslint when executed from a command line (see http://eslint.org/docs/developer-guide/nodejs-api#cliengine).
  "eslint.options": {},

  // Traces the communication between VSCode and the eslint linter service.
  "eslint.trace.server": "off",

  // Run the linter on save (onSave) or on type (onType)
  "eslint.run": "onType",

  // Turns auto fix on save on or off.
  "eslint.autoFixOnSave": false,

  // 
  "eslint.workingDirectories": [],

  // An array of language ids which should be validated by ESLint
  "eslint.validate": [
    "javascript",
    "javascriptreact"
  ],
```

I start my vscode in the same directory I have my .eslintrc but it in vscode it does not lint.
When I lint from commandline it works.

Where do I start debugging?

regards Kai

**Comment by RealBlazeIt** [comment]
Have you found a fix for this issue?

**Comment by toyflish** [comment]
I found out it was actually just not linting my .vue files from vuejs framework. I fixed it by changing  my vscode preferences to:
```
{
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "vue"
    ]
}
```

now when I edit my .vue-files I have the linting-hints in my prolbems-tab but the bulb showing on the line I only have in the .js files.

**Comment by dbaeumer** [comment]
To enable the bulb you need to tell the extension to compute auto fixes for vue files by doing:
```
{
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        {
            "language":  "vue",
            "autoFix": true
         }
    ]
}
```

**Comment by toyflish** [comment]
thanks, even the autofix is pretty cool!
