### ISSUE TITLE
[object Object]: ESLint configuration is invalid: - Unexpected top-level property "ecmaFeatures".

### ISSUE THREAD

**Issue by XaveScor** [Microsoft/vscode-eslint#261]
eslint version is 4.1.1
I have valid config and can run eslint from terminal. My config: https://gist.github.com/XaveScor/90a24430aeac9b6c7b4241e27647c7a8
Error in subject

**Comment by RealBlazeIt** [comment]
Exact same issue^

**Comment by VapidSlay** [comment]
I have the same problem

**Comment by hornydevil** [comment]
yeee, same here 😩

**Comment by Lyroo** [comment]
Same Problem here

**Comment by sosspyker** [comment]
I have a typescript project with: 
default tsconfig.json file - no references to eslint.
package.json file: No reference to eslint - only dependency is the typescript package.
I do not have .eslintrc.json or eslintDefaults.json files in my typescript project.

However I did install npm install -g eslint when VSCode started complaining about eslint with install suggestion.
For some reason the ESLint server is running for my project - not sure why??
The output tab in ESLint terminal window shows the following:

[Info  - 10:08:30 AM] ESLint server is running.
[Info  - 10:08:31 AM] ESLint library loaded from: C:\Users\[currentuser]\AppData\Roaming\npm\node_modules\eslint\lib\api.js

Having same exact error every time I run below from terminal:
node myJavascript.js

**Comment by Aladdin-ADD** [comment]
it is related to [ eslint@4.0.0 breaking change.](http://eslint.org/docs/user-guide/migrating-to-4.0.0#-unrecognized-properties-in-config-files-now-cause-a-fatal-error)

linking: https://github.com/eslint/eslint/issues/8867

**Comment by XaveScor** [comment]
I found error. plugin tries open config from my home directory. I deleted it and eslint works now. Please add logs about some events.

**Comment by kristajg** [comment]
I was have identical problems, and uninstalling the `prettier` extension made everything better. I also uninstalled / reinstalled eslint @ v1.2.11 and that is fine.  Prettier seemed to be the issue in my case, if any of you have that installed as well.

**Comment by Aladdin-ADD** [comment]
>(refs eslint/tsc-meetings#51 (comment))

>Starting in 4.0.0, ESLint has been throwing a fatal error when encountering unexpected config file properties, including `ecmaFeatures`. However, many old configs still have the top-level `ecmaFeatures` option, which has had no effect since ESLint 1.x. This commit updates ESLint to emit a warning when it encounters a config with `ecmaFeatures`, rather than throwing an error.

**Comment by Aladdin-ADD** [comment]
will fixed in `eslint@4.4.0`.

**Comment by dbaeumer** [comment]
I will close the issue then. Please ping if you disagree.

**Comment by dbaeumer** [comment]
And thanks for the investigation.
