### ISSUE TITLE
I cant't use it~

### ISSUE THREAD

**Issue by ycjcl868** [Microsoft/vscode-eslint#262]
![image](https://user-images.githubusercontent.com/13595509/28164026-feab0ca8-67ff-11e7-9cfd-cc0ed34487e2.png)

**Comment by Aladdin-ADD** [comment]
what about using cli?

I guess it is related to eslint -- it disable jsx by default. you can enable it like this:
```json
{
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        }
    },
}
```

**Comment by ycjcl868** [comment]
I use cli like this but ~
```bash
$ node_modules/.bin/eslint xxx.jsx
```
it display:  
`error  Parsing error: Unexpected token <`


I enable it you mentioned, `token <` problem solved.  But it occurred a new question. 

![image](https://user-images.githubusercontent.com/13595509/28297566-41ed59b8-6ba1-11e7-8a48-65106b5bb4cf.png)

**Comment by Aladdin-ADD** [comment]
arrow function is a ES6 feature. you should also enable it.

ref: http://eslint.org/docs/user-guide/configuring#specifying-parser-options

**Comment by ycjcl868** [comment]
I set up `.eslintrc` before like this: 

```json
  "parserOptions": {
    "ecmaVersion": 2017,
    "sourceType": "module",
    "ecmaFeatures": {
        "jsx": true
    }
  }
```

but it error as again

**Comment by Aladdin-ADD** [comment]
as far as I can see, it is your syntax error(not eslint's). would you change `=` to `:`?

**Comment by ycjcl868** [comment]
`handleClick = () => ` is ES6 arrow function , to bind this .

**Comment by dbaeumer** [comment]
@Aladdin-ADD thanks for your support here.

@ycjcl868 the eslint extension basically surfaces the errors greated by eslint in VS Code. So if an error exist when running eslint in a terminal then it is usually not a problem of this extension and should be better discussed in the corresponding eslint GitHub repository.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
