### ISSUE TITLE
How to use my own rules when using the "Create eslintrc.json file" command?

### ISSUE THREAD

**Issue by mikevaleriano** [Microsoft/vscode-eslint#264]
Is there a template somewhere? I couldn't find it in the extension directory.

I just want to paste my own eslintrc file on top of it, as I have a standard one that is used by 99% of my projects.

Thanks.

**Comment by dbaeumer** [comment]
This is currently not supported.

**Comment by Hirse** [comment]
@mikevaleriano For your use case it might make more sense to [publish your configuration and import it as a dependency to your project](https://eslint.org/docs/developer-guide/shareable-configs). That way, they also stay up-to-date.

Slightly related: https://github.com/Microsoft/vscode-eslint/pull/423

**Comment by dbaeumer** [comment]
I agree with @Hirse 

OK to close?

**Comment by mikevaleriano** [comment]
Yes, I've been doing something similar, but linking that way is faster and more maintainable. Thanks.
