### ISSUE TITLE
ESLint is not showing not working in VS Code.

### ISSUE THREAD

**Issue by RealBlazeIt** [Microsoft/vscode-eslint#265]
I have ESLint installed as a developer dependency in the project and I do not have it installed globally. I have the VS Code ESLint extension enabled. 

In order to ensure my rules actually work, I have tested running ESLint via command line on my source directory and everything worked fine, errors were detected. 

All my `User Settings`/`Workspace Settings` have been untouched, and all the ESLint default settings are still the same as ones here: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint.

This is what my `.eslintrc.json` looks like:

     {
       "env": {
         "node": true,
         "es6": true
       },
       "extends": "eslint:recommended",
       "parserOptions": {
         "ecmaVersion": 2017
       }
     }

This file is placed in the main directory of the project, along side the `package.json` and the `src/` directory.

I have tried adding the following setting to my VS Code `User Settings`: 
`"eslint.workingDirectories": ["./src"]` with no success.

Many other people have downloaded the exact same package as I did, and have successfully enabled ESLint in VS Code. What am I missing?

**Comment by imdanielpiva** [comment]
Hello, there. I've been facing the same problem, isn't there any solution or explanation for this yet?
