### ISSUE TITLE
Linting doesn't update after ESLint package upgrade

### ISSUE THREAD

**Issue by benblank** [microsoft/vscode-eslint#268]
Linting doesn't update when upgrading ESLint (as it does when editing a file or `.eslintrc`).  This can be worked around by disabling and re-enabling linting on the workspace, but having it update automatically would be quite nice.

Operating System: macOS 10.12.5
VS Code version: 1.14.1
vscode-eslint version: 1.2.11
System `node --version`: 8.1.2
System `npm --version`: 5.0.3

Steps to reproduce:

1. Create a new folder.
2. In the terminal, cd into the folder and `npm init`.
3. Accept all defaults.
4. `npm install --save-dev eslint@~4.0.0`
5. `node_modules/.bin/eslint --init`
6. Accept all defaults.
7. Open the folder created in step 1 in VS Code.
8. Create a new file named "index.js".
9. Enter the text `process.stdout.write("foo\n");` into "index.js" and save the file.
10. Observe that the token "process" is marked with an ESLint error.
11. Open the file ".eslintrc.js".
12. Change the word "browser" to "node" and save the file.
13. Back in "index.js", observe that there are no longer any ESLint errors.  (Linting updates after a config change.)
14. Back in ".eslintrc.js", add a new key-value pair `"getter-return": "error"` to the "rules" section.
15. Back in "index.js", observe that the entire file is marked with an ESLint error.  ("getter-return" is not a rule known to ESLint@4.0.0.)
16. Back in the terminal, `npm install --save-dev eslint@~4.2.0`.
17. Back in "index.js", observe that the ESLint error still exists.  (Linting does **not** update after a package upgrade.)
18. Open the command palette and select "ESLint: Disable ESLint for this workspace".
19. Observe that the ESLint error no longer appears.  (Of course.)
20. Open the command palette and select "ESLint: Enable ESLint for this workspace".
21. Observe that the ESLint error is still absent.  (ESLint@4.2.0 *does* know the rule "getter-return".)

**Comment by dbaeumer** [comment]
This will be very hard to archive in a general case since the VS Code API doesn't allow to listen to file events outside the workspace folder. I will close the issue as out of scope however I am willing to help on a PR if someone is willing to work on one

**Comment by dbaeumer** [comment]
We closed this issue because we don't plan to address it in the foreseeable future. You can find more detailed information about our decision-making process here. If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our roadmap and issue reporting guidelines.

Thanks for your understanding and happy coding!
