### ISSUE TITLE
Error seen when running `eslint` in command line but not in VSCode

### ISSUE THREAD

**Issue by wontoncc** [Microsoft/vscode-eslint#270]
I use `eslint-plugin-flowtype-errors` to integrate flow into eslint. Errors can be got from flow typecheck when running eslint in terminal, but nothing shows up in VSCode.
And it is even more puzzled that errors other than those from flow can be detected and displayed as usual...

Any thoughts on what's wrong here?

**Comment by dbaeumer** [comment]
Actually no. Would you be able to share a setup that I can copy / clone. Then I can have a look and understand why this doesn't work.

**Comment by wontoncc** [comment]
https://github.com/wontoncc/bug-test
A minimal project to reproduce the situation. And I'm on Windows 10, if that matters.

```
.\node_modules\.bin\eslint app.js
```
should get errors from locally installed flow, but no errors in VSCode.

**Comment by dbaeumer** [comment]
@wontoncc are you using yarn to install the npm modules. If so this is very likely a dup of: https://github.com/Microsoft/vscode-eslint/issues/187

**Comment by dbaeumer** [comment]
Using npm shows:

<img width="465" alt="capture" src="https://user-images.githubusercontent.com/1931590/29022366-61e0f748-7b69-11e7-97d2-5a7032de0ba4.png">

**Comment by wontoncc** [comment]
Yes, I tried to use `yarn` in the test repo but no luck since my project I'm working on is managed by npm. And the output of ESLint shows that the library is loaded:
![snipaste_20170807_191922](https://user-images.githubusercontent.com/993963/29024626-8a919f76-7ba5-11e7-97dd-0af4e5f6b22f.png)
![snipaste_20170807_191947](https://user-images.githubusercontent.com/993963/29024629-8e4d21a8-7ba5-11e7-83b5-d0deb9d3db73.png)
Tried using globally installed `flow-bin` and `eslint` with related plugins just now and get the same result.

**Comment by wontoncc** [comment]
Reinstall VSCode(64bit) and finally find that I accidentally installed the 32bit version of VSCode.
Now it's working. Thank you for your aid!

Maybe a tip may help other people like me?
