### ISSUE TITLE
Autofixing for extensions other than ".js" and ".jsx" does not work

### ISSUE THREAD

**Issue by touzoku** [Microsoft/vscode-eslint#271]
I'm authoring a plugin for Visualforce (Salesforce flavor of JSP pages). VSCode Visualforce plugin adds `Visualforce (visualforce)` language support, so I have configured eslint plugin like follows:
```json
{
    "eslint.options": {
        "extensions": [
            ".page",
            ".js"
        ]
    },
    "eslint.validate": [
        "javascript",
        "visualforce"
    ],
    "eslint.autoFixOnSave": true
}
```

This configuration works for linting as expected — the editor highlights the issues correctly, but autofixing does not work: neither on save, nor explicitly through running "Fix all auto-fixable problems".

![screen shot 2017-07-26 at 16 49 07](https://user-images.githubusercontent.com/1285662/28610409-3555504c-7223-11e7-9b00-5a324b07ae15.png)

If I manually specify the language as Javascript in the editor — both linting and fixing start to work but the linter starts interpreting HTML tags as JSX, which is not desired (notice the presence of the yellow lightbulb and an extra highlight under `<apex:page>`).

<img width="793" alt="screen shot 2017-07-26 at 16 57 33" src="https://user-images.githubusercontent.com/1285662/28610522-94f43216-7223-11e7-96ed-274041ea17d0.png">

Running `./node_modules/.bin/eslint --ext page --fix fixme.page` manually works as expected.

How to convince your plugin to autofix visualforce language with `.page` extension?

**Comment by dbaeumer** [comment]
You need to opt into autofixing per file type. For visualforce something like
```
"eslint.validate": [
    "javascript",
    { 
	"language" : "visualforce",
	"autoFix": true
    }
]
```

**Comment by touzoku** [comment]
@dbaeumer I have the following configuration, still no reaction from VSCode.
```json
{
    "eslint.options": {
        "extensions": [
            ".page",
            ".js"
        ]
    },
    "eslint.validate": [
        "javascript",
        {"language": "visualforce", "autofix": true}
    ],
    "eslint.autoFixOnSave": true
}
```

**Comment by dbaeumer** [comment]
Does that work in a terminal using ESLint command line tool.

**Comment by touzoku** [comment]
@dbaeumer yes, see the comment above

> Running `./node_modules/.bin/eslint --ext page --fix fixme.page` manually works as expected.

**Comment by dbaeumer** [comment]
@touzoku I am not a page / visualforce file expert. Do you have a visual force plugin installed to get support for it?
