### ISSUE TITLE
How do I disable warning and error which wouldn't break code?

### ISSUE THREAD

**Issue by eromoe** [Microsoft/vscode-eslint#274]
Hi, 

I only want `vscode-eslint` tell me where has syntax error , such as `function not found`  or something else which make my code broken. 

Others like below are really annoying:

![image](https://user-images.githubusercontent.com/3938751/29108622-64588d6a-7d12-11e7-9328-6f26b8f0c1af.png)

![image](https://user-images.githubusercontent.com/3938751/29108613-5a9ef340-7d12-11e7-9c13-618e78ab98e0.png) 

 I don't understand why it treat `alert` and `console` as  warnings, warnings like this would not break my code.

I see there is a config parameter use to `autofix` error, but I don't tend to fix error like 
```
[eslint] 'select' is defined but never used. (no-unused-vars)
```
In another word, I only want it auto fix error like `wrong indent` ,` space is require` , `need add {} `  , `need add ; after xx`  or something similar. 

So I wonder how to achieve my purpose ?

**Comment by dbaeumer** [comment]
The ESLint extension only 'surfaces' functionality from the eslint module (https://github.com/eslint/eslint) so such a configuration has to be defined in the eslint config file. Have you tried to setup eslint accordingly in the eslintrc.json file?

**Comment by eromoe** [comment]
Nope, I don't know much about eslint,  after some researching, I found settings in package.json 

```
  "eslintConfig": {
    "parser": "babel-eslint",
    "extends": "airbnb",
    "env": {
      "browser": true,
      "node": true,
      "jest": true,
      "es6": true
    },
    "plugins": [
      "redux-saga",
      "react",
      "jsx-a11y"
    ],
    "parserOptions": {
      "ecmaVersion": 6,
      "sourceType": "module",
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "rules": {
      "arrow-parens": [
        "error",
        "always"
      ],
      "arrow-body-style": [
        2,
        "as-needed"
      ],
      "comma-dangle": [
        2,
        "always-multiline"
      ],
      "import/imports-first": 0,
      "import/newline-after-import": 0,
      "import/no-dynamic-require": 0,
      "import/no-extraneous-dependencies": 0,
      "import/no-named-as-default": 0,
      "import/no-unresolved": 2,
      "import/prefer-default-export": 0,
      "indent": [
        2,
        2,
        {
          "SwitchCase": 1
        }
      ],
      "jsx-a11y/aria-props": 2,
      "jsx-a11y/heading-has-content": 0,
      "jsx-a11y/href-no-hash": 1,
      "jsx-a11y/label-has-for": 2,
      "jsx-a11y/mouse-events-have-key-events": 2,
      "jsx-a11y/role-has-required-aria-props": 2,
      "jsx-a11y/role-supports-aria-props": 2,
      "max-len": 0,
      "newline-per-chained-call": 0,
      "no-confusing-arrow": 0,
      "no-console": 0,
      "no-use-before-define": 0,
      "prefer-template": 2,
      "class-methods-use-this": 0,
      "react/forbid-prop-types": 0,
      "react/jsx-first-prop-new-line": [
        2,
        "multiline"
      ],
      "react/jsx-filename-extension": 0,
      "react/jsx-no-target-blank": 0,
      "react/require-extension": 0,
      "react/self-closing-comp": 0,
      "redux-saga/no-yield-in-race": 2,
      "redux-saga/yield-effects": 2,
      "require-yield": 0,
      "import/no-webpack-loader-syntax": 0
    },
    "settings": {
      "import/resolver": {
        "webpack": {
          "config": "./internals/webpack/webpack.prod.babel.js"
        }
      }
    }
  },
```

So, does this mean I have to know  every rule  and decide to turn on or off ?

**Comment by dbaeumer** [comment]
@eromoe can you please provide a GitHub repository I can clone that demos the issue with steps how to reproduce?

**Comment by eromoe** [comment]
@dbaeumer  It is much better after  remove `"extends": "airbnb",  `  .

**Comment by dbaeumer** [comment]
@eromoe good to hear. I will close the issue then.
