### ISSUE TITLE
Nested .eslintrc files not detected

### ISSUE THREAD

**Issue by ankit-m** [Microsoft/vscode-eslint#275]
I have a file structure which looks like this:

    -- folder1
    -- folder2
    -- folder3
    -- client
      |-- **
      |-- .eslintrc (1)
    -- .eslintrc (2)
     

The plugin only detects the (2) .eslintrc. I have set the working directory to `"./client". The (1) .eslintrc file is supposed to add extra rules for client code.

**Comment by dbaeumer** [comment]
This works for me. Can you provide a cloneable GitHub repository that reproduce the problem ?

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
