### ISSUE TITLE
Is there any config to avoid autofix for some specific rules?

### ISSUE THREAD

**Issue by yvesyao** [Microsoft/vscode-eslint#276]
After I updated eslint to v4, everytime when I saved my file with `debugger;` line to debug my code, the autofixer will  always 'help' me to remove my debugger line.

Is there anyway to tell the autofixer not to fix `no-debugger` errors when I'm saving files?

Thank you!

**Comment by dbaeumer** [comment]
No, this is currently not possible. Closing as dup of #208
