### ISSUE TITLE
minimap

### ISSUE THREAD

**Issue by JStiller** [Microsoft/vscode-eslint#279]
It would be nice if i could configure the minimap. Because i would like to have the same behaviour as the default minimap of vscode.

![unbenannt](https://user-images.githubusercontent.com/646868/29495271-4c7fa964-85bc-11e7-880b-8289d06f1a09.PNG)

**Comment by dbaeumer** [comment]
Since ESLint is an VS Code extension this should work by simply configuring the minimap in VS Code. Please add more details if this doesn't help solving your problem.

**Comment by JStiller** [comment]
Hello,
i made another gif. This time an animated one, to pin out the different behavior. While the standard minimap doesnt take the whole height of the screen, the minimap of eslint does. This leads to the problem, that those minimap, visually doesnt match the same. 

![screen](https://user-images.githubusercontent.com/646868/30272703-18702d7e-96f6-11e7-9ff5-f3a80ce34231.gif)

Does that gif made the issue more understandable?

**Comment by dbaeumer** [comment]
As said the minimap feature comes for VS Code itself. The ESLint extension can't control the minimap. The feature you are describing can be control via the VS Code editor setting `"editor.scrollBeyondLastLine": false`
