### ISSUE TITLE
Numerous "definition for rule" errors

### ISSUE THREAD

**Issue by jmfgdev** [Microsoft/vscode-eslint#280]
I get 3 errors like this one for every file I work on:

severity: 'Warning'
message: 'Definition for rule 'react/jsx-sort-prop-types' was not found (react/jsx-sort-prop-types)'
at: '1,1'
source: 'eslint'

Any idea how to fix this?

**Comment by dbaeumer** [comment]
I would suspect a missing eslint plugin. Do you have repository I could clone that demos this.

**Comment by jmfgdev** [comment]
yeah sure give https://github.com/freilabs/amidabot.js/ a clone, I personally get errors on it

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
