### ISSUE TITLE
vscode-eslint doesn't work on .vue files

### ISSUE THREAD

**Issue by pwicks86** [Microsoft/vscode-eslint#281]
I've got an app with some .vue files in it and I've installed the official vue eslint plugin, so when I run on the command line, eslint provides useful output for these files. In vscode, the eslint plugin appears to only work for .js files, despite eslint being configured to work correctly for .vue files.

**Comment by dbaeumer** [comment]
You need to tell the ESLint extension to validate vue files. To do add the following to your VS Code settings.

```
"eslint.validate": [
	"javascript", {
		"language": "vue",
		"autoFix": true
	}
]
```
