### ISSUE TITLE
eslint.autoFixOnSave doesn't always fire on save

### ISSUE THREAD

**Issue by jdb8** [Microsoft/vscode-eslint#283]
I have `eslint.autoFixOnSave` set to true in my settings, but I've been able to get into a weird state where the command palette 'fix all fixable problems' command works, but hitting save doesn't appear to do anything. I also have `eslint.run` set to `true`, so errors are correctly highlighted - some of which are fixable and should be caught on save.

Could this possibly be caused by hitting save too early after reloading, before the eslint server is active? If I reload and wait long enough, things seem to get back to normal, but if I hit cmd+s too quickly it appears to break the fix-on-save behaviour for the rest of the session, across all files.

I tried looking into this myself but couldn't find any logs (and my knowledge of debugging third-party extensions is currently lacking).

EDIT: additionally, for context, I'm loading my project over sshfs - I noticed that unmounting and re-mounting the volume without reloading vscode seems to trigger this issue. Unsure if there are other causes at this point.

**Comment by dbaeumer** [comment]
@jdb8 autofix on save will only work if the eslint server is up and running. However you can always trigger the auto fix on save even with automatic save on by pressing Ctrl+S manually. 

Please be aware of the following from the ESLint extension doc:

>eslint.autoFixOnSave - enables auto fix on save. Please note auto fix on save is only available if VS Code's files.autoSave is either off, onFocusChange or onWindowChange. It will not work with afterDelay.

If this doesn't solve your problem please provide a repository I can clone which demos your problem.

**Comment by jdb8** [comment]
Hi @dbaeumer! Thanks for responding.

In my case, I believe the eslint server *is* up and running, because running the explicit 'fix all fixable problems' command via cmd+p works correctly. What doesn't work is the hook to autoFixOnSave when I hit cmd+s. I'd imagine that if the server was down, the former would also not work.

I can confirm that I have `"files.autoSave": "off",` (the default). I don't think this is a repository specific problem: rather, once it stops working in my editor, it ceases to work across all open folders. As such, I don't think I'm able to provide you a reproducible repo :(

If you can point me in the direction of logs or debug output from the extension, or lines of code that specifically enable this autoFixOnSave behaviour, I could try dig in and better describe the exact failure mode here.

**Comment by dbaeumer** [comment]
@jdb8 you can enable tracing to see if the will save request is sent to the server. To do so set the `"eslint.server.trace": "messages"` options. When you have gathered the trace please post it here.
