### ISSUE TITLE
Fix all auto-fixable problems needs multiple runs to fix everything

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-eslint#287]
https://github.com/Microsoft/vscode/issues/33261

1. `git clone https://github.com/gwtw/js-avl-tree`
2. `eslint --init`
3. Select standard JS
4. Open avl-tree.js, you should see a lot of errors, in particular extra semi colon errors
5. Run fix all auto-fixable problems via command palette
6. Notice that semi colons are still present at the end of function definitions:

![image](https://user-images.githubusercontent.com/2193314/29833117-363eac42-8c9f-11e7-8e52-f532e29270cd.png)

Running the command again will fix these problems.

**Comment by dbaeumer** [comment]
Dups #154
