### ISSUE TITLE
How do you enable linting on other file extensions than .js?

### ISSUE THREAD

**Issue by everystone** [Microsoft/vscode-eslint#29]
VSCode only supports JSX syntax on files with .jsx extension, but vscode-eslint only runs on files with .js ext. Are there any way of setting which file extensions to lint?

Cheers

**Comment by egamma** [comment]
>VSCode only supports JSX syntax on files with .jsx extension,

Not anymore ::-): if you enable Salsa, please see the release notes https://code.visualstudio.com/Updates#_javascript-salsa-preview

You can still use eslint for linting. The vscode-eslint extension supports linting of .jsx files. You need to do is to enable the rule in the `.eslintrc`
```json
{
    "ecmaFeatures": {
        "jsx": true,
        ...
    }
    ...
}
```

**Comment by everystone** [comment]
Here is my .eslintrc

    {
      "extends": "airbnb",
      
      "rules": {
        "prefer-template": 0
      },
      "plugins": ["react"],
      
      "ecmaFeatures": {
        "jsx": true
      }
    }

I still don't get any linting on jsx files, and the documentation for the js-is-isx extension states that

    Notice when you install this extension you will
    loose all the existing language support provided for .js 
Which is not really what I am after, I guess it's not possible at the moment

**Comment by egamma** [comment]
>Notice when you install this extension you will loose all the existing language support provided for .js 

This is no longer the case when you enable Salsa. Salsa understands jsx constructs in the .js files as described in the release notes (not sure how I can make this more clear than it is written now). When you enable Salsa all the js-is-jsx extension does is to enable the jsx coloring for js files. I will update the description of js-is-jsx. Thanks for pointing this out.

I will verify the eslint later, but in the implementation of vscode-eslint the javascriptReact language mode is enabled.

**Comment by everystone** [comment]
Ah I see, thank you for explaining. I will try out Salsa.
