### ISSUE TITLE
Activating extension `dbaeumer.vscode-eslint` failed: vscode_languageclient_1.ProposedProtocol is not a function.

### ISSUE THREAD

**Issue by chenxsan** [Microsoft/vscode-eslint#291]
I'm trying to run the source code on my computer, only got this:

<img width="1915" alt="screen shot 2017-09-09 at 5 20 02 pm" src="https://user-images.githubusercontent.com/1091472/30238901-3a84420c-9583-11e7-945f-3eb83ccc115b.png">

And I checked repo https://github.com/Microsoft/vscode-languageserver-node/tree/master/client, there is no `ProposedProtocol` exported.

1. Node.js - 8.4.0
2. npm - 5.4.1
3. VSCode - 1.16.0

Any idea?

**Comment by dbaeumer** [comment]
We had some last minute changes in the LSP API that the ESLint extension needed to adopt.
