### ISSUE TITLE
Getting “ESLint: Error:No ESLint configuration found" 

### ISSUE THREAD

**Issue by PrasannaGumpalli** [Microsoft/vscode-eslint#296]
Hi,
I tried running a project developed using webdriverIO framework. But wasn’t able to run the project due to “ESLint: Error:No ESLint configuration found” . Please can you help me why I’m receiving this error message ?.

Thank you.

Prasanna

**Comment by dbaeumer** [comment]
That means that you haven't configured ESLint. You can either run the command `ESLint: Create .eslintrc.json file` from within VS Code or execute eslint --init in a terminal on the workspace folder.
