### ISSUE TITLE
.eslintignore ignored when vscode is loaded

### ISSUE THREAD

**Issue by jas99** [Microsoft/vscode-eslint#297]
Attached below is screenshot of vscode 1.6 where for abt first minute; after vscode starts .eslintignore file is not working. After few seconds like maybe 1 minute, everything works fine. If I reload the vscode instead of restarting the program there is still no issue.

![screenshot 12](https://user-images.githubusercontent.com/1231593/30430787-f3f6c63e-9979-11e7-850d-21143ba6c353.png)

Thx

**Comment by dbaeumer** [comment]
@jas99 can you provide me with steps to reproduce this. I am not able to do so. Best would be:

- a GitHub repository to clone
- your env: which npm version, ...

**Comment by jas99** [comment]
https://gitlab.com/lesson/meteor_react_score_keep
```
Windows 10
VScode x64 1.16.1
```
```
{ npm: '5.3.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.5.0',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.14.1',
  v8: '6.0.287.53',
  zlib: '1.2.11' }
```
```
yarn versions v1.0.1
{ http_parser: '2.7.0',
  node: '8.5.0',
  v8: '6.0.287.53',
  uv: '1.14.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
Done in 0.03s.
```

**Comment by jas99** [comment]
Let me know if more info is required

Thx

**Comment by dbaeumer** [comment]
I lately fixed problems with the current working directory which resulted in problems where the .eslintignore will not work correctly. Do you still see the problem?

**Comment by jas99** [comment]
I will chk and post back, 
Thx

**Comment by dbaeumer** [comment]
OK. Thanks.
