### ISSUE TITLE
A wrong error shows in vscode.

### ISSUE THREAD

**Issue by poppinlp** [Microsoft/vscode-eslint#302]
![image](https://user-images.githubusercontent.com/1970625/30791943-0fe4fdd4-a17c-11e7-8672-98293c3a39ec.png)
In this image you could see a error which is `Missing semicolon`. But there is a semi for sure.
I have tried to remove other code. It not work. So this error is really produced by this code.
I have tried autofix by eslint but it not work( just add one more semi and this error is still there).

I make a test on eslint online demo and it won't show that error for same code. You could see that test [here](https://eslint.org/demo/#eyJ0ZXh0IjoiZXhwb3J0IGRlZmF1bHQgYXN5bmMgKCkgPT4ge1xuXHRjb25zdCBhcGkgPSAoKSA9PiBuZXcgUHJvbWlzZShyZXNvbHZlID0+IHJlc29sdmUoKSk7XG5cdGNvbnN0IHJlcyA9IGF3YWl0IGFwaSgpO1xuXG5cdHJldHVybiByZXM7XG59OyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OCwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnNvbGUiOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUta2V5cyI6Miwibm8tZHVwbGljYXRlLWNhc2UiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZW1wdHkiOjIsIm5vLWV4LWFzc2lnbiI6Miwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjoyLCJuby1leHRyYS1zZW1pIjoyLCJuby1mYWxsdGhyb3VnaCI6Miwibm8tZnVuYy1hc3NpZ24iOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjIsInNlbWkiOjIsInNlbWktc3R5bGUiOjIsInNlbWktc3BhY2luZyI6Mn0sImVudiI6eyJicm93c2VyIjp0cnVlLCJlczYiOnRydWV9fX0=).
So i guess it maybe a plugin bug and open a issue here.
Want some help. Thanks. :)

eslint: 4.7.2
vscode-eslint: 1.3.2
vscode: 1.16.1
eslint config: [eslint-config-handsome](https://github.com/poppinlp/eslint-config-handsome)
system: macos 10.12.6

**Comment by dbaeumer** [comment]
Can you share a GitHub workspace that demos the behavior I can clone. That will help understanding this. And can you please let me know what the error exactly is (e.g. hover over it and send me a screenshot).

**Comment by poppinlp** [comment]
You could clone [this repo](https://github.com/poppinlp/vscode-eslint-issue-demo) and install dependencies. Then open it in vscode with eslint plugin and you'll see this:

![image](https://user-images.githubusercontent.com/1970625/30851661-e32643e0-a26e-11e7-8176-283b04774397.png)

**Comment by dbaeumer** [comment]
You get the same error message when executing ESLint from a terminal without VS Code.

![capture](https://user-images.githubusercontent.com/1931590/31079632-8fc8d5e2-a786-11e7-8ad7-1f07cff3c96d.png)

Please report the issue against ESLint itself since there is little the ESLint extension can do to fix this.
