### ISSUE TITLE
The 'initialize' request has a pretty long response time

### ISSUE THREAD

**Issue by datoml** [Microsoft/vscode-eslint#303]
Hello,

I have a really strange behavior when starting vs code with the eslint extension.
The request to initialize ESLint takes about 190039ms.

Here's the trace log from VSCode.

```
[Trace - 08:19:20] Sending request 'initialize - (0)'.
[Trace - 08:22:30] Received response 'initialize - (0)' in 190039ms.
[Info  - 08:22:30] ESLint server is running.
[Trace - 08:22:30] Sending notification 'initialized'.
[Trace - 08:22:30] Sending notification 'textDocument/didOpen'.
[Trace - 08:22:30] Received request 'client/registerCapability - (0)'.
[Trace - 08:22:30] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
[Trace - 08:22:30] Received request 'client/registerCapability - (1)'.
[Trace - 08:22:30] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
[Trace - 08:22:30] Received request 'workspace/configuration - (2)'.
[Trace - 08:22:30] Sending response 'workspace/configuration - (2)'. Processing request took 1ms
```

Is this a problem with the extensions or do I have a problem inside my dev environment?
Thank you in advance.

**Comment by dbaeumer** [comment]
Which version of ESLint are you using?. 

In general ESLint needs to find and load the ESLint npm module. If you have a lot of plug-ins installed this might take some time.

Since ESLint 1.3.1 the discovery of the ESLint npm module happens when a file gets validated the first time.

**Comment by datoml** [comment]
I am using version 1.3.2 of the extensions and ESLint 3.19.0.
The package is installed in the local node_modules folder.

**Comment by dbaeumer** [comment]
This is strange then. The only thing ESLint 1.3.2 does in the initialize is to get the global npm configuration by executing `npm get config prefix`. If you type this is into a terminal does it take long to respond?

**Comment by datoml** [comment]
You in the VSCode terminal?
When I execute the `npm get config prefix` the response is undefined and takes about 1 sec or so.

**Comment by dbaeumer** [comment]
Thanks. The fact that it is undefined is strange. Do you have any global npm modules installed ?

**Comment by datoml** [comment]
Nothing special tbh.
Only create-react-app, rimraf and typescript.
I also tried Atom and there the eslint server is starting within seconds.

**Comment by dbaeumer** [comment]
Actually this doesn't mean that the server actually needed so much time. The extension host is single threaded (node) and if another extension blocks the event loop the response can't be processed. Do you have any additional plugins installed. Does this repro with only having ESLint extension enabled?

**Comment by datoml** [comment]
I also tried with only ESLint extensions enabled and the same effect.
Do I have any chance to debug it?

**Comment by dbaeumer** [comment]
Yes, you can do the following which would be highly appreciated:

- clone this repository
- run npm install
- run npm run compile
- open vscode
- in extension.ts change line https://github.com/Microsoft/vscode-eslint/blob/master\client\src\extension.ts#L361 to 
```
		debug: { module: serverModule, transport: TransportKind.ipc, options: { execArgv: ["--nolazy", "--inspect-brk=6010"], cwd: process.cwd() } }
```
- got the the debug viewlet
- select the Launch Extension configuration and start debugging (F5)
- open the workspace that shows the behavior in the started VS Code instance. You might see a warning that a local ESLint version overrides the installed one
- select the Attach to Server Launch config
- Press F5
- set a breakpoint here https://github.com/Microsoft/vscode-eslint/blob/master\server\src\server.ts#L596
- press continue in the Server attach debugging session.
- step through the initialize code. Do you see any unexceptional?

**Comment by datoml** [comment]
I tried to do npm install but it seems like the proxy wont let me install vscode.

```
> client@1.3.0 postinstall C:\Git\vscode-eslint-master\client
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.16.0
Error installing vscode.d.ts: Error: connect ETIMEDOUT xx.xx.xx.xx:xxxx
```

Where do I have to add the proxy to make it work?

**Comment by dbaeumer** [comment]
This is really strange since the vscode.d.ts file is fetched from our GitHub repository an it looks like you were able to clone this repository. Do you need to configure proxies to access GitHub?

**Comment by datoml** [comment]
I have set up a http.proxy for git and I was able to clone the repo. Unfortunately npm install isnt working.

**Comment by dbaeumer** [comment]
@datoml sorry for the late response. Was out of office. How does npm install fail ?

**Comment by datoml** [comment]
Still the same problem :(.

```
> cd client && npm install && cd ../server && npm install && cd ..


> client@1.3.0 postinstall c:\Git\vscode-eslint-master\client
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.16.0
Error installing vscode.d.ts: Error: connect ETIMEDOUT 40.83.182.206:443
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@1.3.0 postinstall: `node ./node_modules/vscode/bin/install`
```

**Comment by dbaeumer** [comment]
You could copy the file by hand from https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts into the client/node_modules/vscode location. You also need to remove the `"postinstall"` script from the client's package.json file to make npm install run successful.

**Comment by datoml** [comment]
Ok. I got it running ... kind of :).
This is what I got for now. But node is unable to connect.
![eslint-extension-debug](https://user-images.githubusercontent.com/10552487/31893848-e7b9eca0-b80c-11e7-8ca4-432deaf8d5c9.PNG)

**Comment by dbaeumer** [comment]
Do you have a firewall that blocks port 6010. The debugger fails to connect to that port for the server?

**Comment by datoml** [comment]
Only the windows firewall afaik. But it seems like it tries to connect to an external ip again as you can see on the second screenshot. Or does this have nothing to do with the problem?

**Comment by dbaeumer** [comment]
Sorry my mistake. The is something broken with the client install. It can't find the vscode-languageclient libraries hence the server will not start. Can you switch to the client folder open the package.json file and remove the postinstall script and then run npm install. This should install the missing npm modules.

**Comment by datoml** [comment]
Hey. The postinstall script was already removed. I ran npm install again but nothing changed. Still got this error when launching the extension in debug mode.
![eslint-extension-debug-3](https://user-images.githubusercontent.com/10552487/32159168-97cdfef8-bd4c-11e7-8713-4e35c8473f78.PNG)

**Comment by dbaeumer** [comment]
@datoml how does the folder `eslint\client\node_modules` look for you. It should contain these modules besides a lot of others.

<img width="379" alt="capture" src="https://user-images.githubusercontent.com/1931590/32363272-cc482daa-c06e-11e7-8eff-8ec73b56979d.png">

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by datoml** [comment]
Sorry for answering so late. Had to do some work on other projects.
They folder contains everything in your screenshot.

I think the problem is with our corporate proxy.

**Comment by dbaeumer** [comment]
There is one other idea I have which could make this slow. Can you run the following command on your machine and see how long it takes: `npm config get prefix`

**Comment by datoml** [comment]
I took about 1 - 2 seconds.

**Comment by dbaeumer** [comment]
Actually I am running out of ideas. Does this reproduce for you on other machines as well. The initialize call of the ESLint server simply returns a JSON structure. So it might be starting up the service. Do you see slow down with other things in VS Code. For example HTML, JSON or TS support.

**Comment by datoml** [comment]
The funny thing is that the Linter in Atom editor for instance runs without any problems.
The TSLint for VSCode also has nor problems. I think we can close it for now and I try to make some tests if I have some time :).

**Comment by dbaeumer** [comment]
Sorry to hear. If you need additional help tracking this down then please ping me. I still don't get why you can't compile the eslint extension yourself. That would definitely ease tracking this down.
