### ISSUE TITLE
Indent option MemberExpression does not support "off"

### ISSUE THREAD

**Issue by trs** [Microsoft/vscode-eslint#304]
ESLint now defaults the `MemberExpression` option of the `indent` rule to `1`.
It also gives the option to set it to `"off"` to ignore this option (https://eslint.org/docs/rules/indent).

Unfortunately, this is viewed as an invalid type and gives the error:
`Configuration for rule "indent" is invalid: 	Value "off" is the wrong type.`

The configuration I am using looks like this:
```
"indent": [
    "error",
    2,
    {
        "SwitchCase": 1,
        "MemberExpression": "off"
    }
],
```

**Comment by dbaeumer** [comment]
The ESLint extension doesn't do any interpretation of the configuration. It is passed to the ESLint npm module. What happens if you run ESLint from a terminal on that project give the same configuration?

**Comment by trs** [comment]
Yeah you're right, nothing to do with this extension.

Looks like this was confusion between versions 3 and 4. Gave an error with 3, but not with 4.
Thanks
