### ISSUE TITLE
Does not work with eslint installed globally

### ISSUE THREAD

**Issue by igorvisi** [Microsoft/vscode-eslint#305]
Visual studio code  1.16.1
OS: Arch Linux

**Comment by dbaeumer** [comment]
@igorvisi this works for me. Are you using yarn to install eslint globally. If so, yarn is currently not supported.

If you use npm can you provide a setup that shows the problem. And does `npm config get prefix` return the right installation location?

**Comment by igorvisi** [comment]
I'm using nvm . It can be the source of problems ?

the resultat of  **npm config get prefix** is :
/home/visi/.nvm/versions/node/v8.1.2

**Comment by dbaeumer** [comment]
And ESLint is installed under /home/visi/.nvm/versions/node/v8.1.2

**Comment by igorvisi** [comment]
Yes It is .

**Comment by dbaeumer** [comment]
Hard to say why this is failing then. It works for me using nvm as well.

Can you enable tracing to see where the extension actually tries to find the node modules. `"eslint.trace.server": "verbose"` and append the trace here.

**Comment by igorvisi** [comment]
I only installed globally which normally works
