### ISSUE TITLE
ESLint JSON schema contribution should work on .eslintrc.json

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-eslint#31]
As per http://eslint.org/docs/user-guide/configuring

**Comment by egamma** [comment]
Adding more info, the eslint JSON schema is currently only associated with .eslintrc. The .eslintrc (which can be either yml or json) has been deprecated in favor of .eslintrc.json.

**Comment by joaomoreno** [comment]
Thanks. I also forgot to assign it...

**Comment by dbaeumer** [comment]
This got fixes.
