### ISSUE TITLE
File path resolved incorrectly when using mono repo structure

### ISSUE THREAD

**Issue by scholtzm** [Microsoft/vscode-eslint#310]
Seems like certain file paths are resolved incorrectly when using the following mono repo structure:

```
root
\--- packages
     \--- stand-alone-pkg-1
     \--- stand-alone-pkg-2
     \--- stand-alone-pkg-3
```

Here's a screenshot from a simple example project:

<img width="1302" alt="screen shot 2017-10-06 at 09 17 26" src="https://user-images.githubusercontent.com/2640934/31267287-db064b9a-aa77-11e7-8a06-5daba906b45a.png">

If I open the package directly:

<img width="696" alt="screen shot 2017-10-06 at 09 18 58" src="https://user-images.githubusercontent.com/2640934/31267316-f0e87e60-aa77-11e7-84cd-9393d393dd65.png">

Same issue applies to .eslintignore:

<img width="1062" alt="screen shot 2017-10-06 at 09 44 34" src="https://user-images.githubusercontent.com/2640934/31268078-057d6b9e-aa7b-11e7-9977-4d78b61b1bf0.png">

I can provide the files if necessary.

btw. if I open the project in Atom, it will lint the files correctly.

**Comment by dbaeumer** [comment]
@scholtzm can you provide a GitHub repository I could clone. That will ease tracking this down.

**Comment by scholtzm** [comment]
@dbaeumer Here's the code from screenshots: https://github.com/scholtzm/vscode-eslint-issue-310

**Comment by dbaeumer** [comment]
@scholtzm thanks. You need to let ESLint know which working directories you have. The reason is that ESLint resolves the ignore file locally to the current working directory which in your case is the folder which contains the packages folder. The documentation is here: https://github.com/Microsoft/vscode-eslint/blob/master/README.md

In the example you provide and entry like this is necessary:

```
	"eslint.workingDirectories": [
		"./packages/foobar"
	]

```

**Comment by scholtzm** [comment]
@dbaeumer Thank you for your response. I did not know about that setting.

I tried placing it inside workspace config and it seems to solve the issue but only partially:

![image](https://user-images.githubusercontent.com/2640934/31546482-d3286492-b023-11e7-9553-9e1c3aaad1bc.png)

**Comment by dbaeumer** [comment]
@scholtzm a little bit more tricky since the path in .eslintrc is relative. You can either make it absolute or ask ESLint to actively perform cwd operations using the following settings:

```
{
	"eslint.workingDirectories": [
		{
			"directory": "./packages/foobar",
			"changeProcessCWD": true
		}
	]
}
```

**Comment by scholtzm** [comment]
And it works 👍 Thanks
