### ISSUE TITLE
VSCode hangs or freezes when eslint is installed

### ISSUE THREAD

**Issue by peltsi212** [Microsoft/vscode-eslint#313]
VSCode Version: Code 1.15.1 (41abd21, 2017-08-16T17:16:27.618Z)
OS Version: Linux x64 4.4.0-93-generic (Ubuntu 16.04 LTS)
Extensions:
Extension | Author (truncated) | Version
-- | -- | --
vscode-eslint | dba | 1.2.11

When eslint is disabled there is no problem
Related issue in vscode is 35475

steps to Reproduce:

25 Aug 2017

I cannot say exact pattern what to do to repeat freeze.
I am editing .js file which contains es2017 javascript code
Freezing happens after many hours of editing.
Freezing have happened know 3 times.
If I remember correctly freezing happens when I switch back from other program.
I was not doing anything special just editing file.
During freeze I cannot move cursor with cursor key.
If I click with mouse, the cursor is not moved to point where I click.
Only place which shows some reaction is that I can click menu and then menu dropdown appears.
If select action like Command Palette nothing happens.
This is so for all menu items.
One exception is Help About. It shows information of visual studio code version.
If I click x to close VSCode application, that works.

2 Oct 2017

Use vscode long time like two days and let it running over night.
I cannot say exact pattern what to do to repeat freeze.
I am editing .js file which contains es2017 javascript code
Freezing happens after many hours of editing.
Freezing have happened know 4 times.
If I remember correctly freezing happens when I switch back from other program.
I was not doing anything special just editing file.
During freeze I cannot move cursor with cursor key.
If I click with mouse, the cursor is not moved to point where I click.
I have many files open.
Tabs for 7 files are visible.
If I click tab, then file name is updated in same area where menu is located.
However tab do not change to that one I click.
I can click menu and then menu dropdown appears.
If select action like Command Palette nothing happens.
This is so for almost all menu items.
One exception is Help About. It shows information of visual studio code version.
Second exception is Help Report issues is also working.
If I click x to close VSCode application, that works.

This same thing happened earlier with VSCode 1.14.2

8 Oct 2017 this happened again.

Result and symptoms are same as before.
Now I have
VSCode Version: Code 1.16.1
I was editing a .js file.
I was writing text. Then I Copied a line in file with Ctrl+C and CTRL+V
Freezing happened when I tried to change copied line.
Vs Code was running over night.
I worked with VS code in the morning about 10 minutes before freeze.

**Comment by dbaeumer** [comment]
@peltsi212 ESLint validation happens in its own process which can't freeze the editor itself. How many ESLint errors do you usually have in our JS files ?

**Comment by dbaeumer** [comment]
I also added a comment to #35475

**Comment by peltsi212** [comment]
It varies. Normally 0 -30 errors per file and about 10 files open.
no-undef and no-unused-vars are typical errors.

Javascript is for Node 8 and contains ecmascript 2017 async and await .

**Comment by peltsi212** [comment]
I have .eslintrc.js in project root.
Content is
module.exports = {
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 2017,
    },
    "env": {
        "es6": true,
        "node": true,
        "browser": true
    }
};

**Comment by dbaeumer** [comment]
@peltsi212 thanks for the information. When the hang appears do you have high CPU load ?

**Comment by dbaeumer** [comment]
@peltsi212 can you please add the information to https://github.com/Microsoft/vscode/issues/35475. It is very unlikely that this is only caused by the ESLint extension so we should continue the discussion in the VS Code core system.
