### ISSUE TITLE
Dynamic change of .eslintrc file rules

### ISSUE THREAD

**Issue by i328638** [Microsoft/vscode-eslint#315]
When changing the .eslintrc file that exist in the project the validation does not changing respectively. 
In the server it seems that on DidChangeWatchedFilesNotification supposed to handle this situation and validate all the open files again with the new rules, but it doesn't work for me. 
Am I missing something?

**Comment by dbaeumer** [comment]
This works for me:

![cast](https://user-images.githubusercontent.com/1931590/31817652-4ad1c36e-b595-11e7-991d-6c38a4a2c0a8.gif)

Can you provide a GitHub repository that I can clone to reproduce your behavior.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
