### ISSUE TITLE
Can't get child create-react-app to eslint correctly

### ISSUE THREAD

**Issue by PaddyMann** [Microsoft/vscode-eslint#318]
I have a structure like:

```
+-- api
|   +-- test.js
+-- app
|   +-- node_modules
|   |   +-- eslint
|   +-- test.js
+-- node_modules
|   +-- eslint
+-- node_modules
+-- .eslintrc
```

The `app` folder was created by [create-react-app](https://github.com/facebookincubator/create-react-app) which sets up `eslint`.

Until recently, everything worked great. The rules were picked up from my base `.eslintrc` config and applied through the `api` and `app` directories.

Since the end of the week, something's changed and the eslint rules _are_ being applied in `api` but _are not_ being applied in `app`. 

I've played with various config options and cannot find anything to fix this. 

If I delete the `eslint` directory from `app/node_modules` then linting starts working as expected in `app`. But this unfortunately isn't a solution - `create-react-app` will always install `eslint`.

Is this a (new?) bug in the extension? Is there some config that should address this?

**Comment by dbaeumer** [comment]
Can you provide me with a GitHub repository to clone. That would help tracking it down.

What very likely will help is the `eslint.workingDirectories` setting for ESLint extension. See https://github.com/Microsoft/vscode-eslint/blob/master/README.md

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.

**Comment by robsonpeixoto** [comment]
@dbaeumer 
```
npm install -g create-react-app
create-react-app my-app
cd my-app/
code .
```

And edit any `src/registerServiceWorker.js` file, will show the warning:
```
[Warn  - 3:20:31 PM] 
No ESLint configuration (e.g .eslintrc) found for file: /Users/robinho/code/my-app/build/service-worker.js
File will not be validated. Consider running 'eslint --init' in the workspace folder manhattan
Alternatively you can disable ESLint by executing the 'Disable ESLint' command.
```

**Comment by robsonpeixoto** [comment]
My bad, after this step the lint will work: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#displaying-lint-output-in-the-editor
