### ISSUE TITLE
Feature request: clear errors/warnings on type

### ISSUE THREAD

**Issue by halvardos** [microsoft/vscode-eslint#319]
When i have  ` "eslint.run": "onSave"` set, i would prefer it if errors were cleared from the workspace when i start typing.

The reason why I have ` "eslint.run": "onSave"` set is that I get distracted by a lot of error signals in the editor and just want them shown when i press save.

For me this makes it harder to isolate one thing to work on, if there are multiple errors in the open file.

The proposed change would be similar to how SublimeLinter with eslint works.

Thanks for an awesome editor :)

**Comment by halvardos** [comment]
Maybe this is the wrong place for this, as this might be handled by the editor? That problems are underlined until they are fixed?

Even a line that is changed is now marked as a problem until I hit save again.

**Comment by dbaeumer** [comment]
No it is the right place and a valid feature request. Are you willing to work on it?
