### ISSUE TITLE
Plugin looking for .eslintrc for non-existent file

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode-eslint#320]
I see the following warning on my ESLint log:
```
No ESLint configuration (e.g .eslintrc) found for file: c:\Users\me\My Projects\database2\.scripts\migrate.js.git
```
I have no idea how it came up with the `migrate.js.git` filename. The `.eslintrc` is located in the `database2` folder.

**Comment by dbaeumer** [comment]
This should be fixed. Which version of VS Code are you running ?

**Comment by oliversalzburg** [comment]
I ran into it in 1.17.1. Haven't confirmed with 1.17.2

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
