### ISSUE TITLE
.eslintrc.js no longer loaded

### ISSUE THREAD

**Issue by philipithomas** [Microsoft/vscode-eslint#321]
I've been using the VueJS Webpack starter kit, which uses a `.eslintrc.js`. This past week, it has stopped being loaded. Reviewing the documentation, it looks like this extension seeks and `.eslintrc.json` file instead of `.js`, and this has broken compatibility. 

Will `.js` configuration files still be supported? If not, is there a migration guide?

**Comment by dbaeumer** [comment]
@philipithomas all valid ESLint configuration formats are supported and a .eslintrc.js file works for me. Can you provide me with a GitHub repository that I can clone that demos the problem?

**Comment by philipithomas** [comment]
@dbaeumer It's a private repo. I just validated that the `.eslintrc.js` file hasn't changed in 3 months, but it stopped being loaded in the last week or two. 

When I go to VScode and try to run "ESLint: Fix all auto-fixable problems", it says `ESLint is not validating any files yet.`. What debugging tools do I have to specify a file, view a loaded file, see error logs, etc?

**Comment by philipithomas** [comment]
@dbaeumer I created a new repo using the VueJS Webpack starter template and their ESLint config, and it has the same issue:

https://github.com/philipithomas/vue-eslint-demo

(Source repo - https://github.com/vuejs-templates/webpack)

When I open the workspace in VSCode, then open `src/components/HelloWorld.vue` and run `Eslint: Fix all auto-fixable problems`, it says `ESLint is not validating any files yet.` There is an `.eslintrc.js` file in the root.

**Comment by dbaeumer** [comment]
This is not an .eslintrc.js issue. You need to tell the ESLint extension to validate vue files. Out of the box on JS files are validated. See the config setting: `eslint.validate` here: https://github.com/Microsoft/vscode-eslint

I will close the issue. @philipithomas please ping if using this setting didn't fix your problem.
