### ISSUE TITLE
Feature request: Ability to set babel-eslint environment variable BABEL_ENV

### ISSUE THREAD

**Issue by tranquille** [microsoft/vscode-eslint#324]
Hi, 

in my project I use babel with different environments and our linting is only working with a correctly set BABEL_ENV variable. Unfortunately there is no possibility to configure any Environment Variable for the eslint process in vscode. Or am I missing something?

Do someone know a workaround for this kind of problem? Or would it be possible to add a configuration for environment variable for the eslint process in vscode?

**Comment by dbaeumer** [comment]
@tranquille this is currently not possible.

However you can start VS Code from a terminal and setup the env in the terminal before. The env then travels down to the eslint process.

**Comment by tranquille** [comment]
@dbaeumer thanks for your fast reply. With the workaround to start VS Code from the command line it's working like expected. 

I will give it a shot to create a pull request for this feature. :-)
