### ISSUE TITLE
Linting breaks when using a Mixin in React

### ISSUE THREAD

**Issue by ItsNoHax** [Microsoft/vscode-eslint#326]
Please let me know how I can provide more information to debug this issue.

Basically at work we have a React-Native mobile app that still uses a couple mixins.

I've been noticing my linting start like lagging behind and eventually just stops working in these files.

**Comment by dbaeumer** [comment]
The first thing you can do it to enable tracing and attach a trace here. This will help identify if this is a problem in ESLint or somewhere else. To enable tracing add the setting `"eslint.trace.server": "messages"` to your workspace settings.

**Comment by ItsNoHax** [comment]
![selection_007](https://user-images.githubusercontent.com/4223434/32366125-113fb500-c07d-11e7-9b9f-060a319b9bd0.png)

ESLint stops working till I restart VSCode, the trace doesn't really say anything. What else can I do to help you debug this?

**Comment by dbaeumer** [comment]
Can you provide me with an example that demos the problem. Best would be a GitHub repository to clone.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
