### ISSUE TITLE
"indent" rules not being applied in function params

### ISSUE THREAD

**Issue by tsteuwer-accesso** [Microsoft/vscode-eslint#329]
We have the "recommended" rules as well as the following specific rules on indent:

```
"indent": ["error", "tab"]
```

It works everywhere except function parameters. For instance:

```
angular
   .module('some-module')
   .controller('SomeController', function(
     myParam1,
     myParam2,
           myParam3
                          myParam4
   ) {
      // code goes here
   });
```

`myParam3` and `myParam4` should be aligned with `myParam1` and 2. However, this doesn't work in VS. If you run eslint on the file itself in commandline, it shows the errors.

**Comment by dbaeumer** [comment]
This works for me:

<img width="334" alt="capture" src="https://user-images.githubusercontent.com/1931590/32363138-041b8e12-c06e-11e7-879f-f910698a378a.png">

Please provide a GitHub repository I can clone with steps to reproduce.

**Comment by tsteuwer-accesso** [comment]
Before you close this, can you please tell me what version of VS code, what version of ES lint you are using? We just had 8 people try and all have the same issue. So it can't just be only you who it works for unless this got resolved at a specific version in VSCode or eslint.

**Comment by dbaeumer** [comment]
@tsteuwer-accesso 

- ESLint extension 1.4.2
- eslint npm module: 4.9.0

If you can reproduce this with a different setup can you please check if the error is correctly reported in a terminal. If yes, please provide me with a GitHub repository I can clone to reproduce this.

**Comment by tsteuwer-accesso** [comment]
Thanks bud. Yes, I did have them check the terminal to see if running it there reported the errors and it did. Just not in VSCode. When they get in I'll have them take a look.

**Comment by dbaeumer** [comment]
When executing in the terminal do you use a global installed eslint. Could that one be different from the one installed into your workspace ?

**Comment by tsteuwer-accesso** [comment]
We thought that too and had them uninstall the global version and the issue persists. I use Vim but the rest of the guys are in VSC. So, I'll update this when they get in. Again, thanks so much for the help.

**Comment by dbaeumer** [comment]
Do all of you use npm or yarn. If you use yarn you need to use some special configs.
