### ISSUE TITLE
[feature request] mark errors in gutter

### ISSUE THREAD

**Issue by koulmomo** [Microsoft/vscode-eslint#33]
It would be good if the extension would mark the line at which errors occur along with **JUST** where it exactly occurs (this could just be a mark in the gutter at the line the error occurs).

This would make it easier to quickly scan through files.

Current:
![screen shot 2016-02-24 at 3 33 41 pm](https://cloud.githubusercontent.com/assets/983861/13304835/0b1d6436-db0c-11e5-9e9b-f259b464f353.png)

Suggested (taken from sublime):
<img width="842" alt="screen shot 2016-02-24 at 3 33 32 pm" src="https://cloud.githubusercontent.com/assets/983861/13304848/20c26958-db0c-11e5-94cc-c4a141720410.png">

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode#3915
