### ISSUE TITLE
Not working on new install

### ISSUE THREAD

**Issue by Jamstah** [Microsoft/vscode-eslint#330]
I installed the eslint module and opened up a javascript file, expecting it to "Just Work" as I have an eslint rc file and eslint installed globally.

I got no highlighting even when making obvious error, so I check the command palette and tried Enable ESLint, and got "command 'eslint.enable' not found"

I'm not sure where to go next...

**Comment by maksimkurb** [comment]
Have the same trouble. Attached logs in #331. It looks like that author published plugin that is not built successfully

**Comment by dbaeumer** [comment]
Looking into it. Worked for me locally :-(

**Comment by phi2039** [comment]
PR Created #332

**Comment by dbaeumer** [comment]
I don't know what happened but somehow the vsix didn't include the generated JS file. I made a new vsix and published it and controlled that the file is in. Sorry for that.

**Comment by dbaeumer** [comment]
@phi2039 the compile error was not the source of this. But thanks anyways.

**Comment by phi2039** [comment]
No worries. Just glad to have it resolved. :-)

**Comment by maksimkurb** [comment]
Maybe there is a typo?
```diff
-"vscode:prepublishs": "cd client && npm run update-vscode && cd .. && npm run compile",
+"vscode:prepublish": "cd client && npm run update-vscode && cd .. && npm run compile",
```

**Comment by dbaeumer** [comment]
@maksimkurb very good catch! Thanks a lot. This explains it. I compiled by hand and pushed a new version.

**Comment by dbaeumer** [comment]
Tested 1.4.2 and it works.

**Comment by Jamstah** [comment]
Super fast resolution, thank you, glad to know it wasn't just me :)
