### ISSUE TITLE
Unable to find package.json

### ISSUE THREAD

**Issue by chipit24** [Microsoft/vscode-eslint#337]
When I open a module in VS code, eslint complains about all my import statements:

```
file: 'file:///Users/.../myApp/src/app/components/Component.js'
severity: 'Error'
message: 'Resolve error: Error: ENOENT: no such file or directory, open './package.json' (import/namespace)'
at: '1,1'
source: 'eslint'

file: 'file:///Users/.../myApp/src/app/components/Component.js'
severity: 'Error'
message: 'Resolve error: Error: ENOENT: no such file or directory, open './package.json' (import/no-extraneous-dependencies)'
at: '1,1'
source: 'eslint'
```

And in the output window for eslint I see the following:
```
ESLint server is running.
ESLint library loaded from: /Users/.../myApp/src/node_modules/eslint/lib/api.js
Failed to load .env.undefined.
Failed to load .env.undefined.
Failed to load .env.undefined.
Failed to load .env.undefined.
...
```

I can't reproduce this issue when I run eslint from the command line. When I run `eslint ./app/**/*.js` from the terminal, I see no lint errors (I only see the `Failed to load .env.undefined.` error). This issue also persists if I disable all extensions except for ESLint. So this seems to be a problem with VS code and this plugin.

**Comment by dbaeumer** [comment]
@chipit24 do you work in a multi folder setup where the package.json & eslint configuration is in one of the subfolders. Then you need to confugre eslint using the workingDirectories setting. See here for an example: https://github.com/Microsoft/vscode-eslint#settings-options

If this doesn't address your problem please provide a GitHub repository demoing the problem that I can clone with steps on how to reproduce.

**Comment by chipit24** [comment]
Thanks. I had the exact same issue as described in https://github.com/Microsoft/vscode-eslint/issues/196, and using `changeProcessCWD` as you suggested there has worked for me. The problem stems from `eslint-import-resolver-webpack`.

**Comment by dbaeumer** [comment]
@chipit24 currently not. Only if you start code from a terminal and set the env inside the terminal. The eslint server will then inherit the env.

I will close the issue. Please ping if you disagree.
