### ISSUE TITLE
Plugin working incorrectly in Pug templates

### ISSUE THREAD

**Issue by believer-ufa** [Microsoft/vscode-eslint#338]
- VSCode Version: 1.17.2
- OS Version: Arch Linux, latest

Steps to Reproduce:

1. run `npm install --save-dev eslint-plugin-pug`
2. set VSCode config option:

    ```
    "eslint.validate": [ { "language" : "pug" } ]
    ```

2. create some Pug template with `script` tag
3. create an error in JS code inside that tag
4. see what VSCode incorrectly highlighting that error

Example on screenshot:

![image](https://user-images.githubusercontent.com/801727/32525297-9e05e498-c445-11e7-98ac-be47c4af1c2a.png)

In this example all file is fine, i just added `function ss() {}` string and you see what is going.

Please fix :) Thanks for you work and have a nice day!

**Comment by believer-ufa** [comment]
If we running `eslint` from command line, everything is fine:

```bash
roman@believer-pc hqa]$ eslint component.jade 

/.../component.jade
  132:18  warning  'ss' is defined but never used  no-unused-vars

✖ 1 problem (0 errors, 1 warning)
```

**Comment by dbaeumer** [comment]
@believer-ufa can you please provide me with a GitHub repository I can clone with steps to reproduce this.

In general the eslint plugin takes the error ranges reported by eslint npm mdoules and maps them to the VS Code editor. So I suspect that these errors have ranges that result in the shown squiggles. The command line ESLint tool only prints parts of the ranges.

**Comment by believer-ufa** [comment]
@dbaeumer here's what you asked for )

https://github.com/believer-ufa/vscode-eslint-pug

**Comment by dbaeumer** [comment]
@believer-ufa thanks, but the pug file is not linting at all. Do you have an additional plugin installed ?

**Comment by believer-ufa** [comment]
Sorry, i think what is small problem in `.vscode/settings.json` file, i [fixed it](https://github.com/believer-ufa/vscode-eslint-pug/commit/0b590e39f5ecc73b71f49a6e61e59e7bf88432ec#diff-5b46cfda0ddaed371f52aa24ea2b0b2a) now. 

Please do next again:

1. Clone [this repo](https://github.com/believer-ufa/vscode-eslint-pug) to your computer
2. Open VS Code
3. Install [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
4. Run `npm install` to install `eslint-plugin-pug` dependency
5. Open folder with cloned project in VS Code (vscode need to read settings in this folder)
6. Open `index.pug` template and check js error's highlighting in it

**Comment by dbaeumer** [comment]
This still doesn't work for me. I can validate test.js file but no pug files.

![capture](https://user-images.githubusercontent.com/1931590/32721715-b4221550-c867-11e7-9b09-8fb9f8bd83f2.png)

**Comment by believer-ufa** [comment]
I dont know.. Maybe you need to install `eslint` and `eslint-plugin-pug` globally.

Try to run on you machine:

```bash
npm install -g eslint eslint-plugin-pug
```

And also try to set VS Code configuration in you user params:

```json
    "eslint.validate": [
        { "language" : "pug" },
        "html",
        "javascript",
        "javascriptreact"
    ],
```

And make sure what your ide using project's [.eslintrc.js](https://github.com/believer-ufa/vscode-eslint-pug/blob/master/.eslintrc.js).

I really dont know what also can affect this behaviour.

**Comment by dbaeumer** [comment]
Do you have any file extension mapping for pug defined ?

**Comment by believer-ufa** [comment]
Sorry, i dont understand you question, can you explain?

I checked it again and saw that it works only with next settings:

```
    "eslint.validate": [
        { "language" : "jade" },
    ]
```

Not `pug` as i think before.. Linting works only with `jade`.

Let me explain: i started use VS Code just few days ago, i almost do not configured my VS Code. Just installed few extensions for linting.

You can look at my screenshot with installed extensions in my ide.

![screenshot_20171115_011647](https://user-images.githubusercontent.com/801727/32802680-b4942ab4-c9a2-11e7-947a-d4283eb15cb7.png)

**Comment by dbaeumer** [comment]
Using Jade I can reproduce this. The error I get back from ESLint looks like this:

<img width="279" alt="capture" src="https://user-images.githubusercontent.com/1931590/32826142-9038119a-c9e7-11e7-8966-1118ac5e4ba1.png">

I simply take this information and transform it to a VS Code diagnostics. Since the value reported from ESLint spawns multiple lines it does the same in VS Code

If you think it is a problem then please report it to ESLint (https://github.com/eslint/eslint) directly or to the pug plugin.
