### ISSUE TITLE
Incorrect comments tip for `rules` options

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [Microsoft/vscode-eslint#339]
![image](https://user-images.githubusercontent.com/12682063/32530403-f9dfae6a-c478-11e7-995f-ba917ce63b27.png)

![image](https://user-images.githubusercontent.com/12682063/32530521-872e217a-c479-11e7-8d44-7800a69fbb2d.png)

![image](https://user-images.githubusercontent.com/12682063/32530436-1e9bf0ce-c479-11e7-907b-384c57527d76.png)

It's obviously that, the comments tip only works while the value of the option was array. But in most time, the value is only a string or a number, and it doesn't work.

**Comment by dbaeumer** [comment]
This is not a problem of the ESLint extension itself. If is a schema problem for the .eslintrc.json file which is maintained here: http://json.schemastore.org/eslintrc. Please file the report there.

**Comment by zhengxiaoyao0716** [comment]
@dbaeumer Thanks, but I think this is a problem of your extension.
The `.eslintrc.json` file has nothing wrong, for a rule option, it given the right description.
But the extension parsed it incorrect if the value of the option is not an array, and it should only parsed correctly while the value we wrote is an array.

**Comment by dbaeumer** [comment]
@zhengxiaoyao0716 my extension is not parsing that file. It is the eslint npm module that does the parsing. So it is either a schema problem or a eslint npm module problem. What happens if you execute eslint from a terminal.

**Comment by zhengxiaoyao0716** [comment]
@dbaeumer Well, I'm sorry, I found that the tip of the `.eslintrc` file was not support by this extension, instead support by `JSON` parser.
![image](https://user-images.githubusercontent.com/12682063/32546731-fd65749c-c4ba-11e7-8f37-8c3533133d45.png)
