### ISSUE TITLE
Extension not loading plugin correctly

### ISSUE THREAD

**Issue by anacierdem** [Microsoft/vscode-eslint#340]
Currently the plugin only runs eslint on js files and disregards the html plugin. I am using smarty tpl files and want to lint them in editor.

This was working properly approx. 1 week ago. Now there is a problem with eslint html plugin not loading. The extension reads and applies google style but not consider the plugin somehow. This means that the configuration is read properly but I'm not sure what is causing this issue.

The package.json on workspace root;

```
{
  "name": "..",
  "version": "1.0.0",
  "description": "..",
  "main": "",
  "author": "..",
  "license": "..",
  "devDependencies": {
    "eslint": "^4.10.0",
    "eslint-config-google": "^0.9.1",
    "eslint-plugin-html": "^3.2.2"
  }
}
```

.eslintrc.json on workspace root;

```
{
    "extends": "google",
    "plugins": [
        "html"
    ],
    "settings": {
        "html/html-extensions": [".tpl"]
    },
    "rules": {
      "no-var": "off",
      "prefer-rest-params": "off",
      "prefer-spread": "off"
    }
}
```
Invoking eslint from command line works fine;

`./node_modules/.bin/eslint ./test.tpl`

**Comment by dbaeumer** [comment]
Have you enabled html linting via the eslint settings. See here: https://github.com/Microsoft/vscode-eslint#settings-options section about `eslint.validate`.

If yes can you please provide a GitHub repository I can clone that demos the problem with steps to reproduce.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
