### ISSUE TITLE
Unable to open file when using remote eslint output

### ISSUE THREAD

**Issue by krewmarco** [Microsoft/vscode-eslint#343]
I have a docker container running node, and I use VSCode to edit files from another machine.  I created a task to run "gulp serve" on my container which produces eslint output:

```
        {
            "taskName": "Gulp Serve",
            "type": "shell",
            "command": "ssh marco@10.42.0.1 'docker exec hgfyeoman gulp serve'",
            "showOutput": "silent",
            "problemMatcher": "$eslint-stylish"
        }
```

This works, and now I get notifications in the Problems window, and also on my source code.  However, when I click on the problem notification, the file can't be found and I get this message:

"Unable to open 'index.constants.js': File not found (file:///app/src/app/index.constants.js).

This is because /app is the path on the remote server, and not on my local vscode workspace path.  How do I map the paths from my remote server to my local directory in the problems window?

**Comment by dbaeumer** [comment]
This is currently not possible. 

Please open an issue against vscode itself since this is a problem with the task execution engine in vscode.
