### ISSUE TITLE
Possible to disable linting in <script> tags in html?

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode-eslint#344]
I currently have some inline JS which is rendered using Jinja. Is it possible to disable linting inside html files?

Adding inline comments like `/* eslint-disable */` doesn't work, nor does adding `**/*.html` to .eslintignore.

**Comment by dbaeumer** [comment]
I guess the errors you see come form the JS support inside VS Code. Can you show me a hover of one of the errors.

**Comment by ivancuric** [comment]
Oh wow, my bad. It was `"html.validate.scripts": true` in VSCode.
Sorry!
