### ISSUE TITLE
ESLint doesn't show up

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode-eslint#346]
![image](https://user-images.githubusercontent.com/30043375/32771915-f86348b8-c92c-11e7-9d93-0c40f7433176.png)

As you can see there's no ESLint, but that empty square takes place (look at my cursor). I have installed ESLint, but I can't see it. I'm using VS Code with multiple workspaces and this problem occurred after VS Code 1.18 and multiple workspaces. As you can see I can see Prettier, but in the left there's space for ESLint which is disappeared. 

P.S. ESLint works fine :)

**Comment by dbaeumer** [comment]
This is on purpose. The ESLint (as with TSLint) status bar icon will only show if there is an error since it didn't convey any information in the non error case.
