### ISSUE TITLE
Cannot find module 'eslint-config-react' Referenced from: /opt/projectFolder/.eslintrc

### ISSUE THREAD

**Issue by zymr-keshav** [Microsoft/vscode-eslint#347]
system information
 - Mac OS High Sierra 10.13.1
 - VS code 1.18

**package.json**

```
 "dependencies": {
    "bootstrap": "^3.3.7",
    "history": "^4.7.2",
    "jquery": "^3.2.1",
    "less": "^2.7.3",
    "path": "^0.12.7",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-redux": "^5.0.6",
    "react-redux-form": "^1.16.0",
    "react-router-dom": "^4.2.2",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.0.2",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-es2015-destructuring": "^6.23.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-register": "^6.26.0",
    "css-loader": "^0.28.7",
    "eslint": "^4.10.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-airbnb-standard": "^1.6.5",
    "eslint-plugin-flowtype": "^2.39.1",
    "eslint-plugin-html": "^3.2.2",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.5",
    "html-webpack-plugin": "^2.30.1",
    "less-loader": "^4.0.5",
    "postcss-loader": "^2.0.8",
    "style-loader": "^0.19.0",
    "svg-inline-loader": "^0.8.0",
    "uglifyjs-webpack-plugin": "^1.0.1",
    "url-loader": "^0.6.2",
    "webpack": "^3.8.1",
    "webpack-dev-server": "^2.9.4"
  }
```

**.eslintrc**

```
{
    "parser": "babel-eslint",
    "extends": ["react"],
    "plugins": [
        "react", "html"
    ],
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
     "parserOptions": {
        "ecmaVersion": 6,
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "sourceType": "module"
    },
    "settings": {
        "html/html-extensions": [".html"]
    },
    "rules": {
        "react/jsx-uses-react": "error",
        "jsx-a11y/href-no-hash": 0,
        "jsx-a11y/anchor-is-valid": 0,
        "no-console": 0,
        "react/jsx-uses-vars": "error",
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "off",
            "single"
        ]

    }
}
```

**.babelrc**

```
{
"presets": [ "env", "react" ],
"plugins": ["transform-es2015-destructuring", "transform-object-rest-spread"],
"sourceMaps": true,
"retainLines": true
}
```

whenever I open any *.js* or *.jsx* file in vscode it gives an error on top

> Cannot find module 'eslint-config-react' Referenced from: /opt/projectFolder/.eslintrc

Do not understand why it is giving this error , already added too many plugins by looking into various solutions but still not able to resolve it.

**Comment by dbaeumer** [comment]
Does this work when validating in a terminal ?

**Comment by zymr-keshav** [comment]
this is working fine when validation with the terminal.

**Comment by dbaeumer** [comment]
Do you have nested folders in your project (e.g. client & server) each using a different configuration? Then this might need a `eslint.workingDirectory` setting

**Comment by zymr-keshav** [comment]
yes. I have following folders structure in my project
.

> ├── README.md
> ├── build
> ├── gulpfile.js
> ├── node_modules
> ├── package.json
> ├── src
> │   ├── App
> │   ├── HomePage
> │   ├── LoginPage
> │   ├── RegisterPage
> │   ├── _actions
> │   ├── _components
> │   ├── _constants
> │   ├── _helpers
> │   ├── _reducers
> │   ├── _services
> │   ├── assets
> │   ├── index.html
> │   ├── index.jsx
> │   ├── logo.svg
> │   ├── scripts
> │   ├── service-worker.js
> │   ├── styles
> │   └── sw.js
> ├── webpack.config.js
> └── yarn.lock
>

**Comment by dbaeumer** [comment]
Have you tried to use the settings `eslint.workingDirectory` described here https://github.com/Microsoft/vscode-eslint#settings-options to specify the working directories to be validate.

Can you please provide a self contained GitHub repository that demos the problem with steps on how to reproduce. Then I can have a look. But without this it is very hard to tell why it is not working.
