### ISSUE TITLE
Plugin spawning many Code Helper processes, using tons of CPU

### ISSUE THREAD

**Issue by kaustubhpixvana** [Microsoft/vscode-eslint#348]
VS Code version: 1.18.0
OS version: macOS High Sierra 10.13.1
Plugin version: 1.4.3

Since the new Visual Studio update, I'm experiencing a huge amount of slowness when enabling the eslint plugin for vscode. Whenever I open more than one file, a bunch of 'Code Helper' processes spawn, essentially slowing vscode to a crawl and slowing my whole machine down.

<img width="1165" alt="screen shot 2017-11-15 at 5 07 38 pm" src="https://user-images.githubusercontent.com/31014125/32868512-813b1ba2-ca27-11e7-8bc0-97dbfb28edfb.png">

I've tried uninstalling all extensions, and only using this one, and still experience the slowdown. Also tried using the new vscode insiders build and still having issues. 

Here are my settings for vscode:
<img width="618" alt="screen shot 2017-11-15 at 5 08 31 pm" src="https://user-images.githubusercontent.com/31014125/32868554-bd235eea-ca27-11e7-9bc2-dbf894303ac5.png">

**Comment by dbaeumer** [comment]
Can you please provide the full command line of some of these CodeHelper processes?

**Comment by kaustubhpixvana** [comment]
Sure, almost all of them either look like this:

`/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/kaustubh/Studio-UI/node_modules/inspectpack/lib/daemon/worker.js {"cache":{"cls":"NoopCache"}}`

or they look like this:

`/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=E21F7DA3984385D12F8083391FD04A8A --lang=en-US --app-path=/Applications/Visual Studio Code.app/Contents/Resources/app --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,3553;3,14,34037;3,15,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,3553;4,14,34037;4,15,34037 --service-request-channel-token=E21F7DA3984385D12F8083391FD04A8A --renderer-client-id=6`

**Comment by dbaeumer** [comment]
Both of these processes have nothing to do with the ESLint extension. The second one is a VS Code renderer the first one I actually don't know. I guess it is started by another extension. Please file the issue regarding the renderer against VS Code itself (if there are more than open VS Code windows because there is one per open VS Code window) and for the other one I advice that you check the additional extensions you have installed to find the one that is starting these processes.
