### ISSUE TITLE
eslint-plugin-vue work on html files but does not work on vue files

### ISSUE THREAD

**Issue by luoxlgh** [Microsoft/vscode-eslint#349]
vscode user config is:
  "javascript.validate.enable" : false,

    "eslint.options": {
        "configFile": "E:/code-style/src/eslint/.eslintrc",
        "plugins": ["vue"]
    },
    "eslint.validate": [
        "javascript",
        "html",
        "vue"
    ]

.eslintrc:

`{

    "extends": [
        "./index.js", 
        "plugin:vue/recommended"
    ],
    "plugins": [
        "vue"
    ],
    "rules": {
        "vue/return-in-computed-property": [2],
        "vue/no-duplicate-attributes": [2],
        "vue/attribute-hyphenation": [2, "always"]
    }
}`

 there are two same files named 1.html and 1.vue, but only the html file throw errors.
![image](https://user-images.githubusercontent.com/11803544/32883611-d91db818-caf2-11e7-9a18-c54abd8e527f.png)

**Comment by dbaeumer** [comment]
Can you please provide a GitHub repository I can clone that demos the behavior with steps on how to reproduce. I am not able to reproduce this locally with my test bed.

**Comment by luoxlgh** [comment]
GitHub repostory is https://github.com/vusion/code-style/tree/develop。
It works on .vue file in cli, but weird in VSCode(version 1.17.1)。

![image](https://user-images.githubusercontent.com/11803544/32999549-e4cb8e4a-cddd-11e7-8984-91256326eaaa.png)

**Comment by dbaeumer** [comment]
@luoxlgh I cloned the provided branch that the branch has no `eslintrc.json` file. Can you please provide an example an I clone and easily reproduce the problem with.

**Comment by luoxlgh** [comment]
Sorry for wasting your time.
https://github.com/vusion/code-style/tree/feature/vsCode-test

clone this repository and `npm run test`。 The result is:
![image](https://user-images.githubusercontent.com/11803544/33054029-ca6bf452-ceb1-11e7-8fa9-834d03df70db.png)

But VSCode does not report bugs in vue file

**Comment by dbaeumer** [comment]
You have no configured VS Code to validate vue files. There is no settings file. See here on how to enable ESLint parse for other file types than JS.

**Comment by dbaeumer** [comment]
https://github.com/Microsoft/vscode-eslint#settings-options

**Comment by dbaeumer** [comment]
This works for me after I install the Vetur extension which adds the vue language mode and adding this to the settings. 
```
{
	"eslint.validate": [
		"javascript",
		"javascriptreact",
		"vue"
	]
}
```

If you don't want to install Vectur you can also define vue as a language mode using the association settings. However I would recommend to use the Vectur extension.
