### ISSUE TITLE
ESLint won't load

### ISSUE THREAD

**Issue by Alonski** [Microsoft/vscode-eslint#351]
Starting up VSCode I noticed today that ESLint stopped working.
The ESLint Button on the Bottom Right next to Select End Of Line Sequence Buttons is missing.

Looking at the Output from ESLint shows me:
[Info  - 12:23:18 PM] ESLint server is running.
[Info  - 12:23:27 PM] ESLint library loaded from: C:\Users\Alon\Documents\Project\node_modules\eslint\lib\api.js

After that nothing.

Please tell me what else is needed to help debug this.

Here is my VSCode Info:
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.18.0
project-manager|ale|0.23.0
ember-related-files-windows|Alo|1.1.0
Handlebars|and|0.2.0
solidity-extended|bea|3.0.2
htmltagwrap|bra|0.0.5
path-intellisense|chr|1.4.2
vsc-ember-frost|cie|0.0.2
code-paredit|clp|0.1.1
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
vscode-gist|dba|1.0.0
vscode-npm-script|eg2|0.3.3
vscode-ember|emb|0.1.1
prettier-vscode|esb|0.24.0
tortoise-svn|fan|0.1.1
vsc-ember-cli|fel|0.3.3
beautify|Hoo|1.1.1
fuse-vscode|iGN|0.0.1
continuum|jam|1.2.0
vscode-stylefmt|mrm|2.5.0
EmberES6Snippets|pha|2.2.0
fuseautocomplete|Qua|1.0.15
vscode-icons|rob|7.18.1
code-settings-sync|Sha|2.8.6
stylelint|shi|0.30.0
slack|soz|0.0.13
code-spell-checker|str|1.4.12
sort-lines|Tyr|1.3.0
vscode-open-in-github|ziy|1.3.0

**Comment by george-norris-salesforce** [comment]
@Alonski can you please share how you fixed? I am having the same issue. Thanks

**Comment by Alonski** [comment]
I think if I remember correctly I ended up nuking my node modules folder and npm installing :)

**Comment by dbaeumer** [comment]
Just to clarify: we change the status button so that it only shows if there are errors. There were to many status button down there :-)
