### ISSUE TITLE
autoFixOnSave alternates between correct and wrong indentation

### ISSUE THREAD

**Issue by dj-hedgehog** [Microsoft/vscode-eslint#354]
I have quite strange error. I set `eslint.autoFixOnSave` to `true`. When I save a file once it formats my code successfully:

![image](https://user-images.githubusercontent.com/7140800/33176185-7836f5fc-d05e-11e7-802b-083591a901c4.png)

When I save it again it messes up the indentation.

![image](https://user-images.githubusercontent.com/7140800/33176226-9d8798ca-d05e-11e7-864b-ba160f684dca.png)

When I save a 3rd time it fixes the indentation again as in screenshot 1 and so on.

How can this happen?
This is my `.eslintrc.json`:

```
{
  "extends": "prettier",
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 2017
  },
  "env": {
    "es6": true,
    "node": true
  },
  "plugins": [
    "prettier"
  ],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "semi": false,
        "printWidth": 120
      }
    ]
  }
}
```

*Edit:* I recorded a video with the strange behaviour:

![eslint-problem](https://user-images.githubusercontent.com/7140800/33177813-43a1a160-d064-11e7-82cb-9656dc78dc7d.gif)

**Comment by dbaeumer** [comment]
@dj-hedgehog do you have any other extension installed (especially one of the other prettiers out there)?

**Comment by dbaeumer** [comment]
If not can you provide me with a GitHub repository that demos the behavior with steps on how to reproduce.

**Comment by arenddeboer** [comment]
I had the same issue with "JavaScript Standard Style" and ```"editor.formatOnSave": true,``` in workspace settings. This resulted in the formatters competing to format the document ( I suppose), which might give you this behavior.
Setting ```"editor.formatOnSave": false,``` solved it for me.

**Comment by dj-hedgehog** [comment]
@arenddeboer You were actually right but it was a little bit hidden. In my global settings I did not have `editor.formatOnSave` but someone from my team commited the `.vscode/settings.json` file which contained `editor.formatOnSave = true`. Since I removed it everything has been working butter smooth.
