### ISSUE TITLE
.eslintrc is invalid: - Unexpected top-level property "rulePaths"

### ISSUE THREAD

**Issue by rojasmi1** [Microsoft/vscode-eslint#355]
Recently I came across the following issue:

`.eslintrc is invalid: - Unexpected top-level property "rulePaths".`

After taking a look at the ESLint documentation that appears to be a valid config option: [https://eslint.org/docs/developer-guide/nodejs-api#cliengine](https://eslint.org/docs/developer-guide/nodejs-api#cliengine)

I tried the following and nothing worked:

- Re-installing the extension
- Removing global esling module and installing again (version 4)
- Installing version 3.19.0
- Switching to node 6.11.0

Anyone having the same problem? Any clue on how to solve it?

Thanks in advance.

**Comment by dbaeumer** [comment]
@rojasmi1 does that same error appear when running eslint in a terminal directly ?
