### ISSUE TITLE
Whitespace inserted with unicode BOM

### ISSUE THREAD

**Issue by aaayushsingh** [microsoft/vscode-eslint#356]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.12.12-custom
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
python|ms-|0.8.0
cpptools|ms-|0.14.2
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Launch VS Code and create a new JavaScript file
2. use VSCode to insert BOM.
3. run `eslint filename.js` this will throw illegal whitespace error on 1:1

if we copy BOM and paste it into file using normal text editor, no irregular whitespace error is thrown by linter

Reproduces without extensions: No (since eslint is disabled)

**Comment by dbaeumer** [comment]
@aaayushsingh can you please file the issue against VS Code directly since the ESLint extension is not involved in this using the same steps as provided here.

**Comment by bpasero** [comment]
As reported in https://github.com/Microsoft/vscode/issues/39258#issuecomment-348209471 it looks like a quick fix was used to "fix the bom" issue. That quick fix is not from VS Code.

**Comment by dbaeumer** [comment]
@bpasero thanks. I interpreted use `VSCode to insert BOM` as your save with BOM action.

**Comment by dbaeumer** [comment]
API request is: https://github.com/Microsoft/vscode/issues/39558

**Comment by aaayushsingh** [comment]
Apparently vscode removes BOM from file before loading it into memory. That could be a reason why vscode-eslint can't detect BOM and double BOM is inserted on saving.

**Comment by dbaeumer** [comment]
Exactly. This is what I was trying to say. However to find that out I need the API request.

**Comment by andrewmiller1** [comment]
It might be possible to use https://github.com/owent-contrib/vscode-clang-format-provider/commit/86e773b4acce9e14b8610d2576c11fb56de43433 as inspiration for a workaround

**Comment by dbaeumer** [comment]
@andrewmiller1 the ESLint extension depends on the ESLint module (https://github.com/eslint/eslint) for this. The reason why this fails right now is that the checking happens in memory to get validation on type and not only on save. The content in memory doesn't have a BOM hence ESLint complains correctly about it.

**Comment by dbaeumer** [comment]
The corresponding VS Code issue https://github.com/microsoft/vscode/issues/39558 which I need to address this got closed as out of scope. Will close this one as well since there is nothing I can do without the additional API.
