### ISSUE TITLE
Not working for .jsx file extension

### ISSUE THREAD

**Issue by ex90rts** [Microsoft/vscode-eslint#357]
VS Code@1.18.0
Eslint Extension@1.4.3

Not working for .jsx file extension, event added following configuration:
```
"eslint.options": {
  "extensions": [".js", ".jsx"]
}
```

And I tried to update the "eslint.validate" configuration, add "jsx" as a language type, and the lint is working normal (javascriptreact is useless):
```
"eslint.validate": [
  "javascript",
  "javascriptreact",
  "jsx"
],
```

**Comment by dbaeumer** [comment]
@ex90rts can you please provide a GitHub repository I can clone that demos your problem with steps to reproduce.

JSX support works for me and I am not sure I fully understand your problem from the issue description.
