### ISSUE TITLE
Pull .eslintrc file from remote location

### ISSUE THREAD

**Issue by jgardner04** [Microsoft/vscode-eslint#358]
I use multiple computers with VS Code and use the a sync settings command to push my configuration between computers via a GitHub Gist. I would love the ability to do this with my .eslintrc file as well. I can envision a scenario where teams would want to share a file and this would be a way they could centralize that file.

**Comment by dbaeumer** [comment]
You can use the `eslint.options` to control this. The possible properties are the command line argument available to eslint.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode-eslint#settings-options
