### ISSUE TITLE
ESlint extension should be used without npm modules

### ISSUE THREAD

**Issue by OshotOkill** [microsoft/vscode-eslint#36]
As vscode is gonna deprecate its internal validator, it's inconvenient to implement eslint-extension with downloading eslint(npm modules) every time and in every project folder. 

I'd recommend vscode-eslint to be more easier to use by embed completely with the latest build of eslint or providing a way to config eslint-options globally in user-settings rather than creating an .eslint repeatedly.

**Comment by egamma** [comment]
@OshotOkill 

You can install eslint globally using 'npm install -g eslint' and vscode-eslint will pick it up. 

Also eslint supports a [cascading lookup](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) so you only have to define a .eslintrc.json file once in a parent folder and it will be picked up.

Is this sufficient for you?

**Comment by OshotOkill** [comment]
@egamma Thanks.

**Comment by craxal** [comment]
I've had some trouble getting the extension to work with a globally installed eslint. Restarting VS Code a few times seemed to due the trick.

I agree that having to install the NPM package yourself seems a little weak sauce to me, even if it is installed globally. It would be nice if I could install the extension and just see things start working.

**Comment by paror** [comment]
Why Linting Javascript Out-of-the-box when you install ESlint extension is not possible? Thats not convenient for new users and for users who can't use npm for security reason.

**Comment by evanwarner** [comment]
Agreed that it seems like an unnecessary requirement to have users also install eslint globally on their own. I've never had an editor extension that didn't install itself with all dependencies included.

**Comment by nemchik** [comment]
I would much rather ESLint be bundled with the extension than having to install it globally. I believe the VSCode TSLint extension already does this. https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin

**Comment by jonkri** [comment]
I'm teaching web design and JavaScript. From my perspective, it would be great if students starting out with JavaScript could get the hints of ESLint without having to install NodeJS.

**Comment by dbaeumer** [comment]
A PR to contribute an action / command is still very welcome.

**Comment by dbaeumer** [comment]
I am closing the issue. Instead of adding this to the eslint extension a better approach would be to have an extension that prereqs this one and guides the user through a possible ESLint setup. This leave this extension somehow light weight and clean.
