### ISSUE TITLE
.eslintrc.json: ESLint configuration is invalid: - Unexpected top-level property "overrides"

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode-eslint#360]
Im am getting this error in VSCode:

> .eslintrc.json: ESLint configuration is invalid: - Unexpected top-level property "overrides"

I don't get the error when running ESLint from the terminal.

This appears to be a valid top-level property according the [ESLint's documentation page](https://eslint.org/docs/user-guide/configuring#example-configuration).

Here is my .eslintrc.json

```json
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": false,
        "node": true,
        "jquery": true
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "sourceType": "script"
    },
    "globals": {
        "angular": true,
        "jQuery": true,
        "$": true
    },
    "rules": {
        "no-const-assign": "error",
        "no-this-before-super": "error",
        "no-undef": "error",
        "no-unreachable": "error",
        "no-unused-vars": "error",
        "constructor-super": "error",
        "valid-typeof": "error"
    },
    "overrides": [
        {
            "files": ["editor/test/**/*Spec.js"],
            "globals": {
                "describe": true,
                "spyOn": false,
                "expect": false
            }
        }
    ]
}
```

I am using the following versions:

ESLint `4.12.1`
Node `7.8.0`
VSCode Insiders
ESLint VSCode plugin `1.4.3`

**Comment by dbaeumer** [comment]
This works for me without problems. Only difference is that I use Node 8.9.1. I do have eslint installed locally.

<img width="1135" alt="capture" src="https://user-images.githubusercontent.com/1931590/33619153-bcd01c36-d9e4-11e7-8d62-97acba0409b5.png">

**Comment by dbaeumer** [comment]
Any other information to reproduce this?
