### ISSUE TITLE
'Fix all auto-fixable Problems' fixes problems one at a time.

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode-eslint#362]
<img width="299" alt="screen shot 2017-12-10 at 5 33 38 pm" src="https://user-images.githubusercontent.com/1499188/33804899-92e9e614-ddd0-11e7-9c1f-b2793c61698f.png">
<img width="306" alt="screen shot 2017-12-10 at 5 33 55 pm" src="https://user-images.githubusercontent.com/1499188/33804900-98bbbaae-ddd0-11e7-90b0-d9bbe64ed628.png">
<img width="291" alt="screen shot 2017-12-10 at 5 34 13 pm" src="https://user-images.githubusercontent.com/1499188/33804905-a2416d80-ddd0-11e7-8f8a-d814621214fe.png">

**Comment by ravshansbox** [comment]
The same problem with 'autoFixOnSave' feature.

**Comment by ravshansbox** [comment]
But calling `eslint --fix` fixes all at once.

**Comment by dbaeumer** [comment]
Dups #154
