### ISSUE TITLE
Not following config file for .vue files

### ISSUE THREAD

**Issue by limeandcoconut** [Microsoft/vscode-eslint#364]
When linting `.vue` files I don't seem to have the rules from my config file. I can get an error for `no-multiple-empty-lines` right at the start of a script tag, like so:

<img width="277" alt="screen shot 2017-12-14 at 8 13 59 pm" src="https://user-images.githubusercontent.com/14302276/34026629-37ef3d10-e10c-11e7-9f4e-d2b4c5435375.png">

but no other errors at all.  As you can see I'm not getting errors for mixed operators or `no-new`.
 I've read every related issue I can find and tried file associations for both `html` and `vue` but can't seem to get anything working.

settings

```js
"eslint.run": "onType",
    "eslint.autoFixOnSave": true,
    "eslint.options": {
        "configFile": "/Users/jacob/Sites/eslintrc.js",
        "extensions": [
            ".html",
            ".js",
            ".vue",
            ".jsx"
        ]
    },
    "files.associations": {
        "*.vue": "html"
//        "*.vue": "vue"
    },
    "eslint.validate": [
        "vue",
        {
            "language": "html",
            "autoFix": true
        },
        {
            "language": "vue-html",
            "autoFix": true
        },
        {
            "language": "vue",
            "autoFix": true
        },
        {
            "language": "javascript",
            "autoFix": true
        },
        {
            "language": "javascriptreact",
            "autoFix": true
        }
    ],
```

eslintrc.js
```js
'use strict'

module.exports = {
    extends: 'brian',
    parser: 'vue-eslint-parser',
    plugins: [
        'html',
        'vue',
    ],
}
```

versions 

```
vue-eslint-parser@2.0.1-beta.2 
eslint@4.10.0 
eslint-config-brian@1.0.1 
eslint-plugin-html@3.2.2 
eslint-plugin-vue@2.1.0
```

**Comment by dbaeumer** [comment]
What happens if you execute eslint directly in the terminal.

If it works there can you please provide a GitHub repository that demos the problem with steps how to reproduce.

**Comment by limeandcoconut** [comment]
It seems to work fine in the terminal (though I'm not intimately familiar with the cli).

Heres my [repo](https://github.com/limeandcoconut/vue-g). It's a slightly modified `electron-vue` boilerplate. 

The file I'm attempting to lint is `./src/renderer/App.vue` roundabouts `line 15` where the script tag starts.

Should reproduce if you:

1. clone
2. `yarn`
3. `yarn global add vue-eslint-parser@2.0.1-beta.2 eslint@4.10.0 eslint-config-brian@1.0.1 eslint-plugin-html@3.2.2 eslint-plugin-vue@2.1.0`
4. mimic my user settings (mentioned above) 
5. create an `eslintrc.js` to mimic mine (also above)

It's a pretty strict set of rules so you should get errors for indentation (spaces, 4) and semicolons (never) at least.

Am I sense?
Thanks

**Comment by dbaeumer** [comment]
Running yarn install prints
```
warning " > eslint-loader@1.9.0" has unmet peer dependency "eslint@>=1.6.0 <5.0.0".
```

In general eslint and all plugins must be either installed globally or locally. This is a limitation ESLint itself.

Following this advice made linting work for me. If you still have problems please provide a self contained example demoing the problem.
