### ISSUE TITLE
Expected indentation of 2 spaces but found 0 - Shows error but does not fix it!

### ISSUE THREAD

**Issue by fleumari** [Microsoft/vscode-eslint#366]
https://i.gyazo.com/415a5bc10c34f450fabca3e8563dffd4.png

I'm using the default settings & auto-generated settings from vuejs.

**Comment by dbaeumer** [comment]
What happens if you execute ESLint in a terminal. If everything works there please provide me with a GitHub repository I can clone that demos the behavior with steps to reproduce.
