### ISSUE TITLE
Issue with VSCode's latest version.

### ISSUE THREAD

**Issue by Khachatour** [Microsoft/vscode-eslint#369]
Hey there folks!
Am I the only who is experiencing problems with this plugin and VSCode's latest version ? 
My current version is `1.19.0`.

Thanks in advance, for any kind of response!

**Comment by dbaeumer** [comment]
Can you provide a GitHub repository I can clone that demos your problems. Then I can investigate.

**Comment by Khachatour** [comment]
@dbaeumer Yes mate, I think [this](https://github.com/Khachatour/dc-heroes) one can help you

**Comment by dbaeumer** [comment]
Trying to run npm install on that repro produces:

```
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE checkout fbce4b9e478f808634a98dac48901ec6ed4ee9fd
npm ERR! fatal: reference is not a tree: fbce4b9e478f808634a98dac48901ec6ed4ee9fd
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dirkb\AppData\Roaming\npm-cache\_logs\2017-12-21T09_03_18_122Z-debug.log
```

for me. 

Can you provide me with a more self contained repository that demos this. And what exactly is not working for you.

**Comment by Khachatour** [comment]
All the others are private repositories, so I think now, but problem is auto fix on save. What you think ?

**Comment by dusty** [comment]
I'm also having a problem with eslint.autoFixOnSave not working.  However, I found that if I disable editor.formatOnSave that it starts working again.

**Comment by Khachatour** [comment]
After a while I've switched to Prettier, I've tried disabling `editor.formatOnSave` nothing happened, so I've switched!
