### ISSUE TITLE
The linter is not picking up project's eslintrc files

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-eslint#37]
I have a folder structure like this:

```
| ParentProject
---| JSProject1
    ---| .eslintrc
---| JSProject2
    ---| .eslintrc
--- somefile.go
--- server.go
```

The parent project is golang, and has several child folders each being a ES6 project. Now, each project has it's own `.eslintrc` file, and a local installation of `eslint` in it's node_modules folder. VSCode doesn't seem to pick up the config files when I have opened a file in the child folders. This works flawlessly and very fast in Atom.

**Comment by dbaeumer** [comment]
I tested the .eslintrc that it is correctly picked up in my use case. However what is not working is to use the local eslint (e.g.JSProject1, JSProject2).

**Comment by kumarharsh** [comment]
Yes, I realised later that I had to necessarily add the `jsconfig.json` alongside each of my `.eslintrc` file, then it started picking it up. But yes it's not picking up the local `eslint` package itself.

**Comment by dbaeumer** [comment]
No, the 'javascript.validate.enable' setting is a VSCode core setting and has nothing to do with the eslint extension.

This issue actually dups #32

**Comment by qinershi** [comment]
I have the same problem too, and it works before I update "vscode-eslint" ext, now I have tried some ways but none is working. By the way, when I run "eslint" in the command line, error shows correctly, What is happening? Any help would be appreciated.

**Comment by dbaeumer** [comment]
@qinershi could you share a workspace that shows the behavior ?

**Comment by qinershi** [comment]
@dbaeumer I don't kown what  to share, everything seems normal :(
Here is my project, see if it helps

| project
---| web
    ---| js
    ---| css
    ---| html
    --- sever.py
--- .eslintrc
--- .gitignore

by the way, my project is not using npm, so I don't have a local node_moduels with eslint, I use the global one

**Comment by dbaeumer** [comment]
@qinershi now I am a little puzzled. From this statement https://github.com/Microsoft/vscode-eslint/issues/37#issuecomment-254756599  I had the impression it is not working. Could I clone your project from GitHub to see if I can reproduce this. In my examples eslint correctly refers to the correct .eslintrc files.

**Comment by qinershi** [comment]
@dbaeumer It works after I reinstall the vscode and eslint ext, thanks all the same

**Comment by dbaeumer** [comment]
OK. I will close the issue then.

**Comment by dbaeumer** [comment]
Issue was closed.
