### ISSUE TITLE
Local .eslintrc file is not loading?

### ISSUE THREAD

**Issue by svictoreq** [Microsoft/vscode-eslint#371]
**Extension version**: 1.4.3

I installed eslint in all my projects locally. And during the installation, I selected that I was not using React. The extension worked fine so far, but now every time I open a JS file, I get an error saying that the React module can not be found. 
This is the output that I get:
```
[Info  - 3:45:44 PM] ESLint server is running.
[Info  - 3:45:53 PM] ESLint library loaded from: c:\Users\svict\Dropbox\Development\Practices\element-creator\node_modules\eslint\lib\api.js
[Error - 3:46:03 PM] 
Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Happened while validating c:\Users\svict\Dropbox\Development\Practices\element-creator\src\app.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-react' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-react' isn't installed correctly.

Consider running eslint --debug c:\Users\svict\Dropbox\Development\Practices\element-creator\src\app.js from a terminal to obtain a trace about the configuration files used.
```
![image](https://user-images.githubusercontent.com/29575744/34226892-8f9e8cc0-e5a1-11e7-896a-991bf0d9d101.png)

This happened to me a while ago, but it stopped happening.
I think it may be happening because it's not loading the local file. 

I haven't use any extension settings.

**Comment by dbaeumer** [comment]
@svictoreq what happens if you run eslint in the terminal. E.g.:
```
eslint --debug c:\Users\svict\Dropbox\Development\Practices\element-creator\src\app.js
```

If this works without problems can you please provide me with a GitHub repository I can clone that demos the behavior. Then I will investigate and see what causes this.

**Comment by svictoreq** [comment]
When I run the command you gave me, it returns that `eslint` is not found. But when i run `.\node_modules\.bin\eslint --debug c:\Users\svict\Dropbox\Development\Practices\element-creator\src\app.js` It returns this:

```
  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +0ms
  eslint:ignored-paths Looking for ignore file in C:\Users\svict\Dropbox\Development\Practices\element-creator +0ms
  eslint:ignored-paths Could not find ignore file in cwd +1ms
  eslint:cli-engine Linting complete in: 12ms +0ms
```

**Comment by dbaeumer** [comment]
@svictoreq can you please provide me with a GitHub repository I can clone that demos the behavior. Then I will investigate and see what causes this.

**Comment by svictoreq** [comment]
@dbaeumer I'm sorry for the delay, this is the repo https://github.com/svictoreq/element-creator

**Comment by svictoreq** [comment]
Hey @dbaeumer I cloned the repo again into my computer, and it worked fine.
I don't know if the problem is due to the fact that I created the repository on a Linux machine, and copied it to a Windows machine -with the node_modules directory included- with a USB flash drive. Could it be because of that?

**Comment by dbaeumer** [comment]
@svictoreq no I don't think so. I would rather say it is a setup of the Linux machine that makes it fail. 

I cloned the repository and it failed for me due to 

```
No ESLint configuration (e.g .eslintrc) found for file: p:\mseng\VSCode\Playgrounds\bugs\element-creator\src\app.js
File will not be validated. Consider running 'eslint --init' in the workspace folder element-creator
Alternatively you can disable ESLint by executing the 'Disable ESLint' command.
```

After creating an .eslintrc.json file everything worked for me as expected.

**Comment by svictoreq** [comment]
Then should we consider this as a closed issue? Because I have been using the extension daily and it has worked correctly, even in projects used in both systems.

**Comment by dbaeumer** [comment]
Great. Closing then.
