### ISSUE TITLE
Since upgrading to VSCode 1.19.1 I get "babel-eslint" module not found

### ISSUE THREAD

**Issue by JonathanGes** [Microsoft/vscode-eslint#372]
I'm using airbnb's config. If i install babel-eslint, i get errors in different rules on airbnb's config file.
Does this make sense? I didn't have this issue with the previous version of VSCode.

**Comment by dbaeumer** [comment]
May be VS Code now includes a schema for airbnb config files. Are the errors valid. Can you provide information about the kind of errors.

The ESLint extension itself doesn't do anything special with airbnb config files. So if there needs to be fixed something it has to happen in VS Code.
