### ISSUE TITLE
Support overriding ESLintRC config in plugin eslint.options

### ISSUE THREAD

**Issue by blackbetty** [Microsoft/vscode-eslint#373]
For highlighting purposes, I would like to be able to set rules as warnings that are set as errors in my organization's `.eslintrc`. Is this possible?

**Comment by dbaeumer** [comment]
You can use `eslint.options` settings which accepts all the command line option eslint provides (https://eslint.org/docs/user-guide/command-line-interface). However I have never tried to override rules with it so I am not sure whether it will work
