### ISSUE TITLE
Failed to load the ESLint library for the document when eslint is installed by yarn

### ISSUE THREAD

**Issue by joshunger** [microsoft/vscode-eslint#374]
I'm seeing Failed to load the ESLint library for the document when eslint is installed by yarn.  I have configured the following -

```
🐍 $ yarn global add eslint
yarn global v1.1.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["eslint@^4.14.0"] is trying to unpack in the same destination "/Users/junger/Library/Caches/Yarn/v1/npm-eslint-4.14.0-96609768d1dd23304faba2d94b7fefe5a5447a82" as pattern ["eslint@^4.0.0"]. This could result in a non deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "eslint@4.14.0" with binaries:
      - eslint
✨  Done in 2.59s.
~/.config/yarn/global
🐯 $ ls -la /usr/local/bin/eslint
lrwxr-xr-x  1 junger  admin  75 Dec 19 15:29 /usr/local/bin/eslint -> ../../../Users/junger/.config/yarn/global/node_modules/eslint/bin/eslint.js
~/.config/yarn/global
```

To find the node path I did -
```
🐮 $ which node
/Users/junger/.nvm/versions/node/v8.9.3/bin/node
```

And then in `settings.json` set the following

```
"eslint.nodePath": "/Users/junger/.nvm/versions/node/v8.9.3/bin/node",
```

Then I receive this error message -
```
[Info  - 06:27:58] 
Failed to load the ESLint library for the document /Users/junger/dev/stanley/shedview/configurator/src/middleware/analytics-middleware.js

To use ESLint please install eslint by running 'npm install eslint' in the workspace folder stanley
or globally using 'npm install -g eslint'. You need to reopen the workspace after installing eslint.

Alternatively you can disable ESLint for the workspace folder stanley by executing the 'Disable ESLint' command.
```

Is yarn installation of eslint supported?

**Comment by joshunger** [comment]
Argh looks like this setting fixed it -

```
"eslint.packageManager": "yarn",
```

Maybe it could just autodetect / try both?

**Comment by dbaeumer** [comment]
This is only a problem if yarn is used to install eslint globally. If installed locally it works regardless whether yarn or npm is used. 

I will close the issue since most of the time eslint is installed locally. Please ping if you disagree.

**Comment by joshunger** [comment]
@dbaeumer Do you have usage data that backs this up?  And would you accept a PR to fix?

**Comment by dbaeumer** [comment]
We always try hard to avoid global dependencies and from all the issue I got so far most people install eslint locally to their project. The only thing they might have outside of the project is a global eslint configuration file. PRs are always welcome. I will reopen the issue.

**Comment by joshunger** [comment]
Yeah same here.  👍

**Comment by joshunger** [comment]
@dbaeumer how about just a documentation hint in the error message?  That'd be a good start.  I can make the change if you want.

**Comment by dbaeumer** [comment]
Tweaking the error message is definitely a first good step.

**Comment by maranomynet** [comment]
Since installing eslint globally is a valid option, it would make sense to automatically look for both npm and yarn global installs, and thus do away with the need to fiddle with settings.

**Comment by joshunger** [comment]
@dbaeumer can you approve my PR?

**Comment by dbaeumer** [comment]
Done. I am very busy with work in VS Code itself. So sorry for the delay.

**Comment by dbaeumer** [comment]
Keeping the issue open for the PR to auto detect this.

**Comment by mohsinhijazee** [comment]
Someone stumbling upon this problem in 2021:
Add following to `.vscode/settings.json`

```
 "eslint.nodePath": ".yarn/sdks",
 "npm.packageManager": "yarn",
```
And also, add `@yarnpkg/sdks` to your dependencies 

```
yarn add @yarnpkg/sdks --dev
```
And then:
```
yarn sdks vscode vim
```

Should wrap the ESLint with `pnp.js` supplied properly. Please restart VS code afterwards.

**Comment by DiskCrasher** [comment]
More info about configuring VSCode using `@yarnpkg/sdks` can be found on Yarn's [website](https://yarnpkg.com/getting-started/editor-sdks).
