### ISSUE TITLE
spread operators are not working in vscode

### ISSUE THREAD

**Issue by ahhmarr** [Microsoft/vscode-eslint#375]
all the other validations are working fine except spread operator 

my code 

`config.params = { ...config.params, ...credentials };`

vscode settings
>"javascript.format.enable": true,
  // Use 'prettier-eslint' instead of 'prettier'. Other settings will only be fallbacks in case they could not be inferred from eslint rules.
  "eslint.autoFixOnSave": true,
  "editor.tabCompletion": true,
  "editor.formatOnSave": true,
  "prettier.eslintIntegration": true

package.json file

>"devDependencies": {
    "@ meteorjs/eslint-config-meteor": "^1.0.5",
    "babel-eslint": "^8.0.3",
    "babel-jest": "^21.2.0",
    "babel-plugin-lodash": "^3.3.2",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "enzyme": "^3.2.0",
    "eslint": "^4.13.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-import-resolver-meteor": "^0.4.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-meteor": "^4.1.6",
    "eslint-plugin-react": "^7.5.1",
    "jest": "^21.2.1",
    "prettier-eslint": "^8.6.2"
  },

.eslintrc
>{
  "rules": {
    "no-console": 0,
    "key-spacing": [
      "error",
      {
        "align": "colon"
      }
    ]
  },
  "parser": "babel-eslint",
  "plugins": ["meteor"],
  "extends": [
    "eslint:recommended",
    "plugin:meteor/recommended",
    "plugin:react/recommended"
  ],
  "parserOptions": {
    "ecmaVersion": 6,
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  },
  "globals": {
    "Promise": true,
    "console": true,
    "window": true,
    "confirm": true,
    "process": true,
    "document": true,
    "SyncedCron": false
  }
}

.babelrc file contents

>{
  "presets": ["env", "react"],
  "plugins": ["lodash", "transform-object-rest-spread"]
}

**Comment by dbaeumer** [comment]
@ahhmarr what happens if you validate the file in the terminal. Does it work correctly. If so can you please provide a GitHub repository I can clone that demos the behavior.

**Comment by ahhmarr** [comment]
I'll create a repo which reproduces the issue

**Comment by ahhmarr** [comment]
https://github.com/ahhmarr/vscode-rest-operator-eslint-issue

**Comment by dbaeumer** [comment]
Very strange. This works for me without any problems. Any additional information?

<img width="983" alt="capture" src="https://user-images.githubusercontent.com/1931590/34713556-f2f5df46-f526-11e7-8d1b-ca6e5bb257d9.png">
