### ISSUE TITLE
How to lint only concrete file in project.

### ISSUE THREAD

**Issue by mkurayan** [Microsoft/vscode-eslint#376]
I work on old project were we do not use eslint. 
But I want to use it for new JS files which I going to add into the project.

How I can setup eslint only to check concrete file?
Is there any short key for that?
(Previously I used Sublime+JSHint there was very useful short key for validation)

**Comment by dbaeumer** [comment]
You can add a .eslintignore file and list the old files you don't want to validate.

**Comment by mkurayan** [comment]
Well this is not a validation per request, when you can control when it happens, but still thanks for you attention and advice.
