### ISSUE TITLE
Indent SwitchCase being ignored

### ISSUE THREAD

**Issue by findoo** [Microsoft/vscode-eslint#379]
VS Code version: Version 1.19.1
OS Version: Mac OSX 10.12.6
ESLint Version: 4.12.0
VSCode-eslint version: 1.4.3

Config - 
```
{
    "extends": ["eslint:recommended"],
    "rules": {
        "indent": [
            "error",
            4,
            { "SwitchCase": 1 }
        ]
    }
}
```

Code -
```
export const exampleReducer = (state = [], action) => {
    switch (action.type) {
        case 'Foobar':
            return '';
        default:
            return state;
    }
};
```

Running eslint in the console gives me no warnings, but VS code flags up an error with indentation - 

> [eslint] expected indentation of 4 spaces but found 8. (indent)

**Comment by dbaeumer** [comment]
@findoo I can't reproduce this using the latest version of eslint with the above same code. Can you provide me with a GitHub repository I can clone that demos the behavior.

**Comment by findoo** [comment]
Thanks for your response @dbaeumer. I've created a repo which has this behaviour - https://github.com/findoo/eslint-bug

**Comment by dbaeumer** [comment]
Very strange. This works for me without any problems.

<img width="834" alt="capture" src="https://user-images.githubusercontent.com/1931590/34712398-0245d180-f523-11e7-81c7-b4a5719d8386.png">

**Comment by dbaeumer** [comment]
I hardly believe that this is Mac specific, but @sandy081 can you please clone the above repository and see if this works for you. Will take ~ 2 minutes :-)

**Comment by ericvincent83** [comment]
I just reproduced the exact same behaviour as @findoo on my mac with the above repository
The version of my tools matches his.

**Comment by findoo** [comment]
@dbaumer here's the output from the eslint channel
```
[Info  - 09:13:33] ESLint server is running.
[Info  - 09:13:34] ESLint library loaded from: /Users/fsmith/nucl-workspace/workspace/eslint-bug/node_modules/eslint/lib/api.js
```

**Comment by dbaeumer** [comment]
I ran `npm install` in the cloned repository and it installed ESLint 4.15.0 for me. Is this the version you are using as well?

**Comment by findoo** [comment]
Yeah 4.15.0. Has same behaviour with 4.12.0 as well from when I originally posted.

**Comment by ericvincent83** [comment]
I got ESLint 4.15.0 from yarn install instead of npm install

**Comment by sandy081** [comment]
@dbaeumer I do not see any ESLint problems

<img width="1016" alt="screen shot 2018-01-09 at 14 56 32" src="https://user-images.githubusercontent.com/10746682/34724213-5baf058c-f54d-11e7-991e-0d916f754683.png">

**Comment by dbaeumer** [comment]
Thanks @sandy081. I am a little lost here. We can't reproduce this on Windows nor on Mac. Anything you can think of that is special with our machines / setup ?

**Comment by findoo** [comment]
Nevermind, was a sneaky user setting overriding the .eslintrc rule 🤦
Closed.
