### ISSUE TITLE
VSCode Problems does not show updated ESLint errors

### ISSUE THREAD

**Issue by hanxue** [Microsoft/vscode-eslint#381]
When ESLint first runs, the errors are displayed in the `Problems` window. Subsequent errors for the file are not shown. 

How do I see the updated ESLint errors?

![kapture 2018-01-04 at 16 58 53](https://user-images.githubusercontent.com/760008/34556259-a0490ee4-f170-11e7-8891-585c5aa27679.gif)

See the video above. I saved the file at the end before right-clicking, but the Problems below does not get updated.

**Comment by dbaeumer** [comment]
This works for me without any problems. Can you please provide a GitHub repository that demos the behavior with steps to reproduce?

Do you have any additional extension installed beside the ESLint extensions?
