### ISSUE TITLE
Error: Cannot find module 'circular-json'

### ISSUE THREAD

**Issue by Mr-NVR** [Microsoft/vscode-eslint#384]
ESLint 1.4.3, vscode 1.19.1

Haven't used vscode in a while due to the holidays.  Started it today and received:
> Error: Cannot find module 'circular-json'

Tried:
>grep -nr 'circular-json' ~/.vscode/extensions/

but grep returned nothing.  Disabled extensions and the error went away.  Began re-enabling and restarting one-by-one and the error returned after enabling and restarting dbaeumer.vscode-eslint.

**Comment by dbaeumer** [comment]
The ESLint extension itself doesn't depend on `circular-json`. So this will very likely come in by an ESLint plugin. What happens when you run eslint from the terminal in the project. Do you see a comparable error. If not can you please provide a GitHub repository that demos the problem.

**Comment by Mr-NVR** [comment]
Thanks.  

Wasn't able to nail down which extension had the dependency so "npm uninstall"ed all eslint dependencies, then followed amackintosh's recommendations here: https://github.com/airbnb/javascript/issues/1589 and added the following to the .eslintrc.json.

```
"rules": {
      "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
    }
```

So strange that it showed up the day I returned from winter break.

**Comment by dbaeumer** [comment]
Do I understand correctly and everything is working again ?
