### ISSUE TITLE
lint not working on eslint-plugin-vue@4.x

### ISSUE THREAD

**Issue by jasonxia23** [Microsoft/vscode-eslint#385]
JavaScript in script tag linted uncorrectly.
```vue
<template>
  working fine
</template>
<script>
  /* eslint-disable eqeqeq */
  if ('1' == 1) {}
</script>
```
No error throws.

**Comment by dbaeumer** [comment]
Have you enabled vue linting as described here: https://github.com/Microsoft/vscode-eslint#settings-options. The setting is `eslint.validate`.

If yes can you please provide me with a GitHub repository I can clone that demos the behavior.

**Comment by jasonxia23** [comment]
@dbaeumer 

**repo**
https://github.com/jasonxia23/vscode-eslint-vue

---
**`yarn run lint`**
```
yarn run v1.2.1
warning package.json: No license field
$ eslint --ext vue,js ./

/Users/xiadayu/my/vscode-eslint-vue/main.js
  1:7  error  Expected '===' and instead saw '=='  eqeqeq

/Users/xiadayu/my/vscode-eslint-vue/main.vue
  2:13  error  Duplicate attribute 'name'           vue/no-duplicate-attributes
  6:11  error  Expected '===' and instead saw '=='  eqeqeq
```

---
**behavior in vscode**
![image](https://user-images.githubusercontent.com/15098719/34774303-c6faf376-f649-11e7-87a7-f64d7b36963d.png)

**Comment by dbaeumer** [comment]
As said in my previous comment you need to enable vue validation in the eslint.validate settings. Something like:
```
{
	"eslint.validate": [
		"javascript",
		"javascriptreact",
		"vue"
	]
}
```

<img width="232" alt="capture" src="https://user-images.githubusercontent.com/1931590/34817810-4e94313e-f6b9-11e7-9314-db815cab6959.png">

**Comment by jasonxia23** [comment]
I have enable vue validation in the eslint.validate settings.
```
"eslint.validate": ["javascript", "javascriptreact", "html", "vue"]
```
My VSCode version is 1.18.0.

**Comment by dbaeumer** [comment]
If you use "vue" as the file type you need to have the Vectur extension installed as well. This is all I did to get your GitHub repository to work correctly.

**Comment by jasonxia23** [comment]
I cloned my repo and opened it in VSCode. It is OK now. Don't know the reason. Thanks  anyway for your patience.
