### ISSUE TITLE
issues with webpack.config.js syntax

### ISSUE THREAD

**Issue by itajaja** [Microsoft/vscode-eslint#386]
my webpack.config.js syntax is not compatible with node 7 which I think is the version of node shipped in vscode that this plugin uses. What that means is that with the `eslint-import` plugin and `"import/resolver": "webpack"` vscode-eslint doesn't work correctly. Is there a way to specify a different node runtime?

**Comment by dbaeumer** [comment]
No, this is currently not possible. Dups  #345
