### ISSUE TITLE
Creating and extending custom rules in eslint.

### ISSUE THREAD

**Issue by dashokkumar93** [Microsoft/vscode-eslint#388]
In my code i wrote on VS Code(Containing eslint) most of the cases where a line containing a string.
like the below one.
```
var temp = "Stackoverflow";
var other=temp+" javascript";
```

I need an auto-fix option in es-lint such that it adds a (a static) comment at the end of line for the lines containing string on VS Code. like this
```
var temp = "Stackoverflow";//Custom comment
var other=temp+" javascript";//Custom comment
```
Is there any way of achieving this on VSCode?

**Comment by dbaeumer** [comment]
No. Such a customizable auto fix support has to come from ESLint itself since VS Code is only leveraging the default ESLint npm auto fix support.
