### ISSUE TITLE
Do not run eslint when there is no eslint configuration for the workspace

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-eslint#39]

**Comment by glebec** [comment]
"For the workspace" meaning that project directory? It sounds like you're suggesting that it not use a global config file. In which case I would disagree.

BTW, ESLint 3 now throws an error if there is no config (local or global).

Any reason to keep this open?

**Comment by dbaeumer** [comment]
The ESLint 3 point is new and we need to tackle this. Need to understand the impact.

**Comment by dbaeumer** [comment]
Address this for ESLint 1.0.7.
