### ISSUE TITLE
It always get broken each time eslint gets updated.

### ISSUE THREAD

**Issue by seancheung** [Microsoft/vscode-eslint#393]
[Extension version] 1.4.4
[Global eslint version] 4.15.0
[VSCode version] 1.19.2
[Node version] 7.9.0
[OS] Windows 10 x64

![image](https://user-images.githubusercontent.com/5442563/34970039-0515b1ca-faad-11e7-8d8c-17a466085d02.png)
![image](https://user-images.githubusercontent.com/5442563/34970044-0c775e96-faad-11e7-829c-19e210809ec9.png)

**Comment by dbaeumer** [comment]
This works for me without any problems. Is there anything special you can think of. After the update does the extension exist correctly in `~/.vscode/extensions`

**Comment by dbaeumer** [comment]
@sandy081 FYI. Anything you can think of breaking an extension on update.

**Comment by martin-eq** [comment]
Had the same issue just now. I uninstalled the extension, installed again and it's working now. Not sure why it broke.

**Comment by seancheung** [comment]
Hmm thanks @dbaeumer  @martin-eq 
I deleted ~/.vscode/extensions and reinstalled it from scratch(actually from settings-sync) and now it works!
Don't know why.

**Comment by seancheung** [comment]
I remembered that it happened once  on my mac and the solution was also a re-installation.

**Comment by sandy081** [comment]
@dbaeumer No clue.

@seancheung It would be helpful to know the steps you followed to get this issue which might give us some hint.

Thanks.
