### ISSUE TITLE
IntelliSense for .eslintrc.js?

### ISSUE THREAD

**Issue by mcdado** [Microsoft/vscode-eslint#394]
I love the fact that the JSON configuration file gets IntelliSense autocompletion.
I image it must be harder, but would it be possible to add the same support to `.eslintrc.js`?

My configuration looks something like this:
```
module.exports = {
  extends: [
    'eslint:recommended',
    // 'airbnb-base'
  ],
  parserOptions: {
    ecmaVersion: 6,
  },
  rules: {
  ""
  }
};
```

I prefer to use the `.js` format for various reasons, the fact that it is legal to use comments. I'm not sure it's a thing, but can one use conditionals and other logic in .eslintrc.js? That would make it much more powerful than plain JSON.

See also:
https://github.com/Microsoft/vscode-eslint/issues/14
https://github.com/davidtheclark/cosmiconfig/issues/20

**Comment by dbaeumer** [comment]
Dups #124.
