### ISSUE TITLE
Eslint.options Env doesn't apply on Node LTS

### ISSUE THREAD

**Issue by Katherraptor** [Microsoft/vscode-eslint#395]
We just updated our node version to LTS and this caused my `eslint.options` `"env": { "es6": true }` value to be disregarded. If I set the `env` value directly in my `.eslintrc.something.json` (specified in `eslint.options` `configFile` which does seem to be working) it works as my `env` flag in `eslint.options` was previously working before this update. But the `env` CLI command from `eslint.options` is not being respected. I was able to recreate this with a 1 file project.

![screen shot 2018-01-19 at 11 35 51 am](https://user-images.githubusercontent.com/8049079/35168302-4c80939c-fd0d-11e7-971d-dc9354c0e71d.png)
(note the eslint error on "const")

![screen shot 2018-01-19 at 11 36 34 am](https://user-images.githubusercontent.com/8049079/35168424-c0bf5180-fd0d-11e7-8624-6fec313e5268.png)
(note error repaired by adding `env` object to `.eslintrc.something.json` specified as `configFile` in `eslint.options`)

**Comment by dbaeumer** [comment]
@Katherraptor the eslint server is running on the node version that ships with VS Code. So updating your node version shouldn't have any affect. Can you provide me with a GitHub repository that demos this?

**Comment by Katherraptor** [comment]
Repo:
https://github.com/Katherraptor/VscodeEslintTest

Current setup errors on `const`
