### ISSUE TITLE
WSL integration

### ISSUE THREAD

**Issue by genna87** [Microsoft/vscode-eslint#397]
ESLint extension doesn't seems to work if ESLint is installed on the Windows Subsystem for Linux

The only way to make it work is to install Node.js and ESLint for Windows too?

**Comment by dbaeumer** [comment]
That is true and to make the extension work in WSL works needs to happen in VS Code itself. See all the issues we have in vscode repository labeled with WSL.

I will close the issue since this is something that should be solved in VS Code in a more general way than only in this extension.
