### ISSUE TITLE
it takes ages for eslint to load:

### ISSUE THREAD

**Issue by husayt** [Microsoft/vscode-eslint#402]
> [Info  - 13:58:04] ESLint server is running.
> [Info  - 14:01:16] ESLint library loaded from: d:\mycode\bir\node_modules\eslint\lib\api.js

It takes about 3 minutes for eslint to load in VS code 1.18.1

What could be cauisng this?

**Comment by dbaeumer** [comment]
Actually I have no idea. What happens if you run eslint from within a terminal on that project. Does it take a long time to start as well?
