### ISSUE TITLE
UnhandledPromiseRejectionWarning when renaming .eslintrc.json

### ISSUE THREAD

**Issue by basickarl** [Microsoft/vscode-eslint#403]
```
(node:15794) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: noConfigReported.has is not a function
(node:15794) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

While eslint is active, renaming the .eslintrc.json file results in the above error. No try catch and helpful error mesage (.eslintrc.json cannot be found for example).

**Comment by basickarl** [comment]
@notlaforge Care to leave a comment for the close?

**Comment by basickarl** [comment]
@dbaeumer Care to leave a comment for the close?

**Comment by basickarl** [comment]
@dbaeumer I see what you did there, nice.

**Comment by dbaeumer** [comment]
Problem was that I converted Object to Map a while ago and forgot to places when the .eslintrc file changes.
