### ISSUE TITLE
multiple shelljs_ files opens

### ISSUE THREAD

**Issue by Andy-QT** [Microsoft/vscode-eslint#404]
Only with extension active,  VSCode opens multiple files by it self:
1x EXEC-CHILD.JS in .\node_modules\shelljs\src\exec-child.js
Multiple times SHELLJS in .\AppData\Local\Temp\shelljs_c1c7b5c58ea0568d229c

SHELLJS contains: 
{
"command":"svn info",
"execOptions":{
  "silent":true,
  ..,
  "stderrFile":".\\AppData\\Local\\Temp\\shelljs_2550622ccfa1212e1894"
}

![vscode_eslint_openfiles](https://user-images.githubusercontent.com/2870154/35632231-646d7d4c-06a6-11e8-8ce2-1a6da1aef784.jpg)

Versioninfo:
![vscode_eslint](https://user-images.githubusercontent.com/2870154/35632201-567b3774-06a6-11e8-8624-d9102a8e5a9a.jpg)

node version: 8.9.4
npm version: 5.5.1

npm packages version:
"eslint": "4.16.0",
"eslint-import-resolver-webpack": "0.8.4",
"eslint-loader": "1.9.0",
"eslint-plugin-flowtype": "2.42.0",
"eslint-plugin-import": "2.8.0",
"shelljs": "0.8.1",

VSCode output is not very detailed:
![vscode_eslint_error](https://user-images.githubusercontent.com/2870154/35632936-59de35d6-06a8-11e8-8051-1155f8a0ae6c.jpg)

thx,
Andi

**Comment by dbaeumer** [comment]
@Andy-QT that is really strange since the ESLint extension does do anything with shelljs. Do you have a repository I can clone that demos this?

**Comment by Andy-QT** [comment]
@dbaeumer i don not have a repository.
CLI has no errors
![eslint_cli](https://user-images.githubusercontent.com/2870154/35700906-9baff3f4-0794-11e8-8424-4e4661ac7b30.jpg)

I have made a screen record of VSCode (.avi), maybe it is helpful.
[VSCode_eslint_error.zip](https://github.com/Microsoft/vscode-eslint/files/1687060/VSCode_eslint_error.zip)

Is it possible to clear VSCode cache or anything else?

**Comment by Andy-QT** [comment]
@dbaeumer We have found the error. 
It was an error with a relative path. 

Eslint in CLI had no errors because we started it in the project root folder with .eslintrc.json

The question is, which path is used in VSCode? 
I could not find any information in the VSCode output console.

**Comment by dbaeumer** [comment]
If a path is relative it will be treated relative to a workspace folder. How did the path look like and how did the workspace folder path look like
