### ISSUE TITLE
Add Command to create a YAML configuration

### ISSUE THREAD

**Issue by Hirse** [Microsoft/vscode-eslint#409]
The extension currently has a command to `Create '.eslintrc.json' file`, but I would prefer to use `.eslintrc.yml`.

Is it possible to add a command that generates a YAML configuration with the same content?

**Comment by dbaeumer** [comment]
No. The provided PR has some comments which didn't get attention. I am still happy to accept a PR here.

**Comment by Hirse** [comment]
Your single comment was to "not do this", so I am confused how you are "happy to accept a PR here".

Regardless, I have updated the PR to address your concerns.

**Comment by dbaeumer** [comment]
@Hirse sorry wasn't clear on my end. I would accept a PR that runs `--init` as a task.

**Comment by dbaeumer** [comment]
Reopening.
