### ISSUE TITLE
Why do I get linter errors with an arrow function?

### ISSUE THREAD

**Issue by pierznj** [Microsoft/vscode-eslint#412]
I have an eslint error showing at this line:

    locBase.forEach((l) => {

which highlights the > character as unexpected. In my (user) settings I have:

    	"eslint.options" : {
		"ecmaFeatures": {
			"arrowFunctions": true,

No workspace settings. It's just the first instance of an arrow function operator that gets highlighted. Why do I see this error?

**Comment by dbaeumer** [comment]
As described in the README (https://github.com/Microsoft/vscode-eslint )the eslint.options property is for CLI options which have a different structure than the .eslintrc* file. I would recommend that you add a .eslintrc.json file to the project and configure ESLint there. You can create on with eslint --init.
