### ISSUE TITLE
"Format Document" command should use ESLint

### ISSUE THREAD

**Issue by WraithKenny** [microsoft/vscode-eslint#417]
There didn't seem to be any mention of this functionality, except a by implication in "formatOnSave" issues.

VSCode has a JavaScript formatter, but ESLint should replace it, not use a secondary one with a different conflicting command.

**Comment by David-Else** [comment]
Yes! Please just build this into VS Code! There is literally no point in having a crummy linter that no body uses built into VS Code and the good one that everyone uses as a plugin!

VS Code is advertised as having linting built in, this is a perfect opportunity to simplify and save time and effort for the user while eliminating the need for maintaining multiple plugins (bits of VS Code). Please hurry this along and add it to the next insiders! :)

**Comment by moltar** [comment]
I can't believe this is not a thing. I was so sure that it is how the extension is supposed to work that I spent an hour reading the README, code and VS Code settings to understand why it is not working. Only to realize, via this issue, that there is no actual support for this yet. I think it's a must-have feature.

**Comment by Hirse** [comment]
You can run ESLint in `--fix`-mode with the `"eslint.executeAutofix"` command. If you re-map that to the _format_-shortcut, it comes pretty close to this request. 😄

**Comment by nschurmann** [comment]
@Hirse excellent!, how to do that also on save? 😄

**Comment by schmic** [comment]
@nschurmann I think you have to disable `editor.formatOnSave` and do it manually before you save. Otherwise the default formatter will overwrite what eslint "fixed".

**Comment by nevercast** [comment]
tslint hooks in to vscode's Format Document functionality by providing a language formatter, eslint should do the same if it is not already.

**Comment by simkessy** [comment]
If I run `eslint . --fix` which is suppose to lint my entire directory, it works but if I open the files and save them, formatting is changed, but my eslint-config is suppose to use the prettier plugging, so I'm not really sure why I'm getting different formatting between linting and formatting on save.

**Comment by regalstreak** [comment]
`File > Preferences > Keyboard Shortcuts > edit keybindings.json`

```
// Place your key bindings in this file to overwrite the defaults
[
    ...

    {
        "key": "ctrl+alt+l (or whatever)",
        "command": "eslint.executeAutofix"
    }
]
```

**Comment by WraithKenny** [comment]
The key-bind workaround does seem like it comes sorta close, but ... it hardly seems right. It's only in a very narrow case that it works as expected. It's not just the key-bind that is the expectation, but the command, which can be called via other code, tasks, or other extensions.

**Comment by ianwremmel** [comment]
> It's only in a very narrow case that it works as expected

agreed. prettier, as an example, is able to format while typing and work with other formatters to arrive at a stable final result. because eslint has its own format command that mostly only runs on save, `format document` and `eslint fix` fight eachother. Moreover, `eslint fix` seems to need to be run multiple times to get the same result that the running `eslint --fix` from the command line would produce (which, arguably, is probably a different bug; i mention it here because solving it feels like a probably side effect of using the formatter api).

**Comment by smokku** [comment]
`"eslint.autoFixOnSave": true,` works for me.

**Comment by WraithKenny** [comment]
Yes, 1 thing of the many involved works with a setting, but none of the other important things work.

**Comment by yukal** [comment]
It should be an automatic mechanism accepting the .eslintrc.json from the root directory of the project. As example: settings from the .vscode/*

**Comment by beeplin** [comment]
yes, I strongly agree that vscode-eslint should be able to bind to `shift-alt-f` (format).

**Comment by TomaszWaszczyk** [comment]
CTRL + SHIFT + P then >Eslint: Fix all auto-fixable Problems.

Here more productive tips for programmer: https://github.com/TomaszWaszczyk/keyboard-shortcuts-productive-hacks

**Comment by edarioq** [comment]
Like others have said, the easiest fix is to install Prettier from the VS Extension Marketplace. Create a `prettierrc`file, copy and paste the following:

```
{
    "trailingComma": "es5",
    "tabWidth": 2,
    "semi": true,
    "singleQuote": true
  }
```

Works well with Airbnb eslint rules.

**Comment by aMarCruz** [comment]
Also there's a [eslint-plugin-prettierx](https://www.npmjs.com/package/eslint-plugin-prettierx) with more options than the default Prettier ones (I'm the author).

For example, this is an .eslintrc.json with the "default" preset:

```json
{
  "root": true,
  "plugins": ["prettierx"],
  "extends": [
    "eslint:recommended",
    "plugin:prettierx/default"
  ]
}
```

It works like any other ESLint plugin, it can be used with the VS Code ESlint or in the command line with `eslint --fix`.

The plugin includes [Prettierx](https://www.npmjs.com/package/prettierx), no need to install Prettier nor the VS Code Prettier extension, and it is not recommended as Prettier (w/o "x")  is not compatible with ESLint.

I am using it with `"eslint.autoFixOnSave": true` in 2 medium sized projects without any issues.

**Comment by SzHeJason** [comment]
https://github.com/ryuta46/vscode-multi-command
```
// settings.json
{
 "multiCommand.commands": [
    {
      "command": "multiCommand.formatAndfix",
      "sequence": [
        "eslint.executeAutofix",
        "workbench.action.files.save",
        "editor.action.formatDocument"
      ]
    }
  ]
}

```

```
// keybindings.json
{
    "key": "shift+alt+f",
    "command": "multiCommand.formatAndfix",
    "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly"
  }
```

**Comment by linkdesu** [comment]
> `"eslint.autoFixOnSave": true,` works for me.

You need to install ESLint plugin first, then this will work really well.

**Comment by qguv** [comment]
A couple things I'd like to point out here:

- binding to the built-in VS Code formatter is a single function call and is done by other projects such as [Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) [(registration code)](https://github.com/HookyQR/VSCodeBeautify/blob/6dfff2f014acb7358ef67aadc77bc0aa8f255e7e/extension.js#L90-L97) and [typescript-language-features](https://github.com/Microsoft/vscode/tree/master/extensions/typescript-language-features) [(registration code)](https://github.com/microsoft/vscode/blob/d52846203f9f7db0626188ae50934f098b943897/extensions/typescript-language-features/src/features/formatting.ts#L89-L102)
- other extensions integrate with formatters registered in this way, such as [VSCodeVim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) which binds `=` to call the default formatter registered with VS Code
- if there's more than one formatter available for a file, VS Code will prompt you the first time to choose a default, which will then be saved in settings:

![VS Code prompt asking to choose the default formatter](https://user-images.githubusercontent.com/553637/60169584-44ebae00-9807-11e9-82db-0c733021405a.png)
![VS Code showing all formatters for the filetype](https://user-images.githubusercontent.com/553637/60169590-47e69e80-9807-11e9-8af3-25c5a97eec33.png)
![some lines from a VS Code settings file showing that the chosen formatter is now saved as the language default](https://user-images.githubusercontent.com/553637/60169736-8d0ad080-9807-11e9-928e-702d8746551f.png)

- when the default formatter and ESLint disagree on how a file should be formatted, any extension that triggers the default formatter on save (like VSCodeVim) will introduce linting errors every time the file is saved, which is also annoying and would be fixed by registering ESLint's auto-fix functionality as a proper formatter

**Comment by electric-skeptic** [comment]
With ESLint's existing level of integration, and the fact that .eslintrc is increasingly ubiquitous, this seems so close to being perfect and harmonious.
Format Document's old js-beautify does a great job of making something mangled into something quite readable, but with hardly any configurability exposed it's frustrating that this helpful formatter is always going to fight our linter.

**Comment by AndreyPatseiko** [comment]
I use in default react native project this settings.
Install `yarn add --dev eslint @react-native-community/eslint-config`.
`.eslintrc.js`

    module.exports = {
       root: true,
       extends: "@react-native-community",
       rules: {
            "prettier/prettier": 0,
             "jsx-quotes": ["error", "prefer-double"]
       }
    };

then  [open short keys JSON](https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization) **not default**
And set `keybindings.json`:

    [
        {
            "key": "cmd+s",
            "command": "workbench.action.files.saveAll"
        },
       {
           "key": "shift+alt+f",
           "command": "eslint.executeAutofix",
       },
    ]

**Comment by WraithKenny** [comment]
There's an Extension API, which means that extensions may trigger code to Format Document, or execute code on Format Document, and simply doing a key-bind or on-save is ***completely irrelevant*** to the issue.

**Comment by WraithKenny** [comment]
The patch on the other hand looks great!

**Comment by jgwinner** [comment]
This really needs to be "Fixed". Basically, the defaults on loading VSCode should 'just work'. Instead, every time you edit a file, all hell breaks loose. This is annoying and you lose productivity this way. 

I should be coding, not getting irritated and surfing the web on an ocean of orange underlines.

**Comment by dbaeumer** [comment]
This will be available in the next version. Please see https://github.com/microsoft/vscode-eslint/issues/815 if you want to help test this.

**Comment by alamothe** [comment]
@dbaeumer Thanks so much for working on this!

Ideally, the formatter should only fix **formatting** rules, not code smells. The problem with auto-fixing on format is that it changes what the code does, and  can sometimes produce a bug.

Can you please consider using `--fix-type layout` as documented by ESLint CLI for formatting? This setting should only apply formatting rules.

**Comment by dbaeumer** [comment]
@alamothe  I created https://github.com/microsoft/vscode-eslint/issues/828 to track this. Please note the the fixType option is already supported however can not be separately be controlled for the formatting.

**Comment by dbaeumer** [comment]
Fixed in 2.0.4. See `eslint.format.enable`.

**Comment by joaohenriquef** [comment]
`eslint.format.enable` had no effect here. Had to switch back to v1.9

**Comment by dbaeumer** [comment]
@joaohenriquef did you have another JavaScript formatter set as a default formatter. Then the eslint one will not win. To force the use of the eslint one you need to configure: `"[javascript]": { "editor.defaultFormatter": "dbaeumer.vscode-eslint" }`.  In total

```json
	"eslint.format.enable": true,
	"[javascript]": { "editor.defaultFormatter": "dbaeumer.vscode-eslint" }
```

**Comment by dbaeumer** [comment]
@joaohenriquef if you execute Format Document With from the context menu which opens do you get presented ?

**Comment by joaohenriquef** [comment]
@dbaeumer I'm not sure about what happened, ESLint wasn't showing up on that list, even after reinstalling the extension and double checking that the formatter was enabled in settings.

Now, trying to replay this bug I upgraded it again but somehow everything worked fine, maybe I missed something. Thanks for your help and quick reply!

**Comment by dbaeumer** [comment]
@joaohenriquef no problem. You are welcome.

**Comment by joaohenriquef** [comment]
Same problem reappeared, I haven't changed any settings. Any ideas?

![Screen Shot 2019-12-19 at 14 47 07](https://user-images.githubusercontent.com/14077663/71196345-a3ea2700-226e-11ea-9238-b26797c33034.png)
![Screen Shot 2019-12-19 at 14 48 08](https://user-images.githubusercontent.com/14077663/71196346-a3ea2700-226e-11ea-9836-984fb80c899e.png)

**Comment by dbaeumer** [comment]
@joaohenriquef did you open a TS / JS file before. ESLint is only registered inside VS Code for a formatter if a corresponding file is open.

**Comment by HuangHongRui** [comment]
```
// vscode config >  setting.json
// 新增
  "[javascript]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
```

<br/>or</br>


![image](https://user-images.githubusercontent.com/26321899/71761058-8620f100-2f01-11ea-8446-ccf789bb8b44.png)

![image](https://user-images.githubusercontent.com/26321899/71761077-d13b0400-2f01-11ea-9e80-eab4c72d3211.png)

**Comment by paulbargaoanu** [comment]
@joaohenriquef, I'm having the same issue. 

Working on a React Native project, VS Code sees the `.js` files I am working on as 'Javascript' language mode, I've enabled ESLint as a formatter in VS Code's settings, both in the workspace and User (global) settings. Still can't see ESLint as an option for a formatter. 
I've also tried manually setting `"[javascript]": { "editor.defaultFormatter": "dbaeumer.vscode-eslint" }` and after doing so and attempting to format a file/selection, I get the 'ESLint cannot format [filename.js]'.
I'm running mac OS Catalina, latest version of VS Code and`"eslint": "5.16.0"` within the workspace. 
Any help or tips would be greatly appreciated.

**Comment by pruett** [comment]
Might be worth mentioning:

If you do have the Prettier extension installed, you may have to add the following to your `settings.json` in order for `ESLint` to appear as a formatter:

```json
  "prettier.disableLanguages": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ]
```

**Comment by paulbargaoanu** [comment]
> Might be worth mentioning:
> 
> If you do have the Prettier extension installed, you may have to add the following to your `settings.json` in order for `ESLint` to appear as a formatter:
> 
> ```json
>   "prettier.disableLanguages": [
>     "javascript",
>     "javascriptreact",
>     "typescript",
>     "typescriptreact"
>   ]
> ```

This was it! Now I can format in VS Code using ESLint.

Thank you so much!

**Comment by pruett** [comment]
@paulbargaoanu Glad that helped!
