### ISSUE TITLE
[Feature request] Add link to github page for the hover box

### ISSUE THREAD

**Issue by hidingmode** [Microsoft/vscode-eslint#418]
I think it will be nice to have some clickable links from the hover box linking to the github page of the error message like in this case, there should be link to https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/valid-v-bind.md

![image](https://user-images.githubusercontent.com/7817101/36846504-e1794144-1d95-11e8-8fc2-8e280fa0b74d.png)

**Comment by vzvu3k6k** [comment]
#562 will solve this issue.

**Comment by dbaeumer** [comment]
Agree. Marking as dup.

**Comment by dbaeumer** [comment]
Ths dup is https://github.com/Microsoft/vscode-eslint/issues/151
