### ISSUE TITLE
Javascript Formatter mistakes < in Flow's Generics for a Binary Operator

### ISSUE THREAD

**Issue by cjduncana** [Microsoft/vscode-eslint#419]
- ESLint Version: 1.4.7
- VSCode Version: 1.20.1
- OS Version: 10.11.6

# Steps to Reproduce:

1. Enable the following setting: `javascript.format.insertSpaceBeforeAndAfterBinaryOperators`
2. Write the following code:
```js
// @flow

const middle: number = 5;

export function range(beggining: number): number => Array<number> {
  return function _range(end: number): Array<number> {
    return [beggining, end];
  };
}
```
3. Format document.

## Expected

The code in the page to stay the same.

## Actual

```js
// @flow

const middle: number = 5;

export function range(beggining: number): number => Array < number > {
  return function _range(end: number): Array<number> {
    return [beggining, end];
  };
}
```

Notice how the formatter changed the Generic in line 5. Eventhough the type is identical to the one in line 6, the formatter treats it differently.

By flipping the setting, that problem is solved, but another one emerges:

```js
// @flow

const middle: number=5;

export function range(beggining: number): number => Array<number> {
  return function _range(end: number): Array<number> {
    return [beggining, end];
  };
}
```

The equal sign in line 3 has the surrounding spaces removed, so flipping the setting is not a desired solution.

**Comment by cjduncana** [comment]
Putting parentheses around the type (`(Array<number>)`) solves the issue, but I still find it odd that the formatter treats the same type differently.

**Comment by dbaeumer** [comment]
@cjduncana this repository is about the VS Code ESLint extension. The JavaScript formatter is provided by VS Code itself. Please file the issue here: https://github.com/Microsoft/vscode

**Comment by cjduncana** [comment]
The reason why I posted the bug here is because the formatting only occurs when this plug in is enabled. Should I still report the bug in the other repo?

**Comment by dbaeumer** [comment]
Hmm, that is strange. When you disable the VS Code formatter what happens then? Have you enabled any ESLint auto fixing?

**Comment by cjduncana** [comment]
If I set `"javascript.format.enable": false`, then no formatting happens. It technically fixes the problem, but then you lose the benefit of VSCode's auto-formatter.

**Comment by cjduncana** [comment]
I can't share the repo. It is private, but the code snippet above reliably demonstrate the issue.
