### ISSUE TITLE
[feature request] lint file with extension other than *.js

### ISSUE THREAD

**Issue by txchen** [Microsoft/vscode-eslint#42]
Currently the plugin only watch js files: `documentSelector: ['javascript', 'javascriptreact'],`

It would be nice if we can lint other file types, like *.html. eslint has many plugins that can support extracting javascript from other format, like html.

Atom's eslint plugin, has this option:

![image](https://cloud.githubusercontent.com/assets/713074/13513166/f413f2fc-e153-11e5-9dfc-fe6b69d408db.png)

**Comment by Gheoan** [comment]
+1. I would like to use this plugin with typescript `.ts`  files now that there is a [typescript eslint parser](https://github.com/eslint/typescript-eslint-parser).

**Comment by txchen** [comment]
webcomponents like vue, riot, or polymer, their comp files all includes javascript. FYI.

**Comment by mrmckeb** [comment]
I've created a PR that addresses the `.ts` and `.tsx` issue, if the approach I provided gets approved, I'll add `.html` too (in the same way). Are there any other formats that are missing?

**Comment by CalebKester** [comment]
Would love to have this in .vue files

**Comment by dbaeumer** [comment]
OK. This was quite some work and basically required to change a lot of things in the LSP as well as the implementation of the ESLint extension. So I would like to find volunteers to test this before I publish this in the market place.

Attached a zip that can be installed using vscode command line installer. For example to install the version in VS Code stable download the attached file and rename it to `vscode-eslint-1.2.0.vsix` (it is currently named zip since github doesn't handle vsix files) and run from a terminal:

`code-insiders --install-extension ./vscode-eslint-1.2.0.vsix`

to install it in VS Code stable use

`code --install-extension ./vscode-eslint-1.2.0.vsix`

To control the file types to be validated use the new settings `eslint.validate`. For example to validate JS and HTML use the following value:

```json
"eslint.validate": [
	"javascript", "javascriptreact", "html"
]
```

Please note that you need to configure ESLint accordingly as well to make this work. The extension will not automatically install eslint plugins. So you need to have a 

```json
    "plugins": [
        "html"
    ]
```

section in the ESLint configuration file and need to install `eslint-plugin-html` as well.

[vscode-eslint-1.2.0.zip](https://github.com/Microsoft/vscode-eslint/files/630866/vscode-eslint-1.2.0.zip)

**Comment by dbaeumer** [comment]
One additional note: due to https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/38 auto fix is not available for files other than JS.

**Comment by dbaeumer** [comment]
Actually dups #21.

**Comment by er1x** [comment]
It works like a charm for me (VS Code 1.7.2, Win10). Using in .vue files, as easy as adding .vue extension to eslint.validate (had eslint-plugin-html installed previously):

```js
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "html",
        "vue"
    ]
```
Thank you @dbaeumer ! 😄

**Comment by sebastiandedeyne** [comment]
Gave it a spin on VSC 1.7.2, OSX Sierra, works like a charm!

**Comment by MauroJr** [comment]
I tested here on VSC 1.7.2, Linux Debian 64 bits, works perfectly!!! Thanks a lot!!! Great job!!!

**Comment by linx4200** [comment]
still not working on .we files.  `.we` is the extension for [Weex](https://alibaba.github.io/weex/) file.

**Comment by kevinongko** [comment]
Tested on VSC 1.7.2 OSX Sierra, works on .vue files 👍

**Comment by sz332** [comment]
Tested on VSC 1.7.2, Windows 7 64 bit, works on .html files. When can we expect an official plugin update?

**Comment by sebastiandedeyne** [comment]
Having issues with the `no-console` rule though, it always highlights the everything before the line that contains the error (this in is a `.vue` file)

<img width="740" alt="screen shot 2016-12-12 at 15 25 19" src="https://cloud.githubusercontent.com/assets/1561079/21102679/6e66ee8c-c07f-11e6-931d-ff6dcdac3094.png">

**Comment by dbaeumer** [comment]
@sz332 in the next days.
@sebastiandedeyne what errors do you get when executing this n the terminal. The ESLint extension simply takes the error range it receives from ESLint and the corresponding plugin.

**Comment by sebastiandedeyne** [comment]
Running eslint:

```
13:9  error  Unexpected console statement  no-console
```

In the editor:

![screen shot 2016-12-13 at 13 31 59](https://cloud.githubusercontent.com/assets/1561079/21140484/96a0f992-c138-11e6-912f-0e50c6ee3eeb.png)

**Comment by jtmthf** [comment]
Tested on VSC 1.7.2 OSX Sierra, with the graphql plugin and it worked well. Only requirement was that a language service for graphql needed to be installed so that the language id could be picked up.

**Comment by Gheoan** [comment]
@sebastiandedeyne That might be a bug in `vscode`.

**Comment by dbaeumer** [comment]
@sebastiandedeyne very strange. Do you have a project / sample you can share. Helps understanding what is going wrong

@sz332 release eslint 1.2.1 today.

**Comment by dbaeumer** [comment]
For those that helped me testing please uninstall and reinstall the eslint plugin since the plugin will not update itlsef anymore if directly installed from a vsix. For the details see https://github.com/Microsoft/vscode/issues/17290.

I apologize for the inconvenience this causes.

**Comment by molant** [comment]
@dbaeumer testing on Windows 10 with insider 1.11 and TypeScript and seems to be working fine. What else is needed to have this in the official release?

**Comment by dbaeumer** [comment]
@molant nothing. I simply forgot to close the issue.

**Comment by molant** [comment]
It wasn't working with the latest version of the plugin and that's how I end up in this issue. Is it going to be available in the next one or is there something broken with my current configuration?
Thanks!

**Comment by dbaeumer** [comment]
@molant it should work with the latest version, however you need to configure this. Please see: "vs/editor/contrib/format/browser/formatActions":["Made 1 formatting edit on line {0}","Made {0} formatting edits on line {1}","Made 1 formatting edit between lines {0} and {1}","Made {0} formatting edits between lines {1} and {2}","Format Document","Format Selection"]

**Comment by rohmanhm** [comment]
Same issue here, anyone will help?
https://github.com/octref/vetur/issues/115

**Comment by codeofsumit** [comment]
ESlint autofix doesn't seem to work for me.

**Comment by KevinNTH** [comment]
@codeofsumit Hi,

```JSON
"eslint.validate": [
        "javascript",
        "javascriptreact",
        { "language": "vue", "autoFix": true },
        { "language": "html", "autoFix": true }
    ]
```

refered here #185

**Comment by prograhammer** [comment]
Hey guys,

With the latest version of VS Code, I'm still not able to lint Vue files. If you pull down this simple example here: https://github.com/prograhammer/hello
Then `npm install` and you'll see linting works perfectly for .js but not for .vue. For example, add some extra spaces after a brace `{` in `doc.js`. Works perfectly. Now try the same in `app.vue`. No error.

Here's my settings.json:

```
// Place your settings in this file to overwrite the default settings
{
    "[javascript]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": true,
        "eslint.options": {
            "extensions": [".html", ".js", ".vue", ".jsx"]
        },
        "eslint.validate": [
            {
                "language": "html",
                "autoFix": true
            },
            {
                "language": "vue",
                "autoFix": true
            },
            {
                "language": "javascript",
                "autoFix": true
            },
            {
                "language": "javascriptreact",
                "autoFix": true
            }
        ]
    }
}
```

**Comment by prograhammer** [comment]
Solved! My settings.json was incorrect. Updated to be like this now:

```
// Place your settings in this file to overwrite the default settings
{
    "[javascript]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": true
    },
    "[vue]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": true
    },
    "eslint.options": {
        "extensions": [".html", ".js", ".vue", ".jsx"]
    },
    "eslint.validate": [
        {
            "language": "html",
            "autoFix": true
        },
        {
            "language": "vue",
            "autoFix": true
        },
        {
            "language": "javascript",
            "autoFix": true
        },
        {
            "language": "javascriptreact",
            "autoFix": true
        }
    ]
}
```

Works beautifully!

**Comment by danielo515** [comment]
I'm still experiencing this problem. Is any official solution?

**Comment by Likivik** [comment]
Linting for vue started working for me with setup from the comment above: https://github.com/Microsoft/vscode-eslint/issues/42#issuecomment-318859607
Thanks, @prograhammer.

**Comment by xcatliu** [comment]
Please note that `eslint.validate` accept all types in vscode, including `"typescript"` and `"typescriptreact"`

![image](https://user-images.githubusercontent.com/5453359/30246249-33f4e6cc-9627-11e7-9774-e431404568ab.png)

You can add settings below to support [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser)

```json
"eslint.validate": [ "javascript", "javascriptreact", "html", "typescript", "typescriptreact" ]
```
