### ISSUE TITLE
[Feature Request]: Option to auto fix all _indent_ problems on save

### ISSUE THREAD

**Issue by ea2973929** [microsoft/vscode-eslint#420]
Today there is an option to auto fix all errors on save and on type. I'm not always convinced that the eslint fix is the best one in all cases so I usually leave this off.

However, I am confident that eslint can fix all my _indentation_ and as such could be used as a nice auto-indent complement to VSCode.

So this request is to add the possibility to auto indent using eslint and leave the rest of the problems for manual fixing.

The best way to provide this would probably be to use the built in formatting support in vscode so that you could configure it something like:

```
    "[javascript]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.formatOnPaste": true
    }
```
And hook it up with the "Format Document"-command.

**Comment by dbaeumer** [comment]
I am marking this as out-of-scope. What is still something we work on is to allow using eslint as a formatter and on format on save.
