### ISSUE TITLE
"Failed to load the ESLint library"

### ISSUE THREAD

**Issue by ris58h** [Microsoft/vscode-eslint#421]
Hi!
I have ESLint installed globally and .eslintrc.json in my home dir. 
VSCode (Version 1.20.1) is installed with snap.
I use NVM.
`which node`
`/home/ris/.nvm/versions/node/v9.6.1/bin/node`

`which npm`
`/home/ris/.nvm/versions/node/v9.6.1/bin/npm`

`which eslint`
`/home/ris/.nvm/versions/node/v9.6.1/bin/eslint`

`printenv NODE_PATH` or 'echo $NODE_PATH' is empty BUT when I set `"eslint.trace.server": "verbose"` I got `[Trace - 2:27:54 PM] NODE_PATH value is: /usr/local/lib/node_modules`

I've already checked similar issues but can't figure out the solution.

**Comment by dbaeumer** [comment]
What is the output of running `npm config get prefix` in a terminal ?

**Comment by ris58h** [comment]
@dbaeumer  Never mind. It's just started working. I don't know the reason.

**Comment by ris58h** [comment]
@dbaeumer I found out that it's a project (folder) related issue. When I open different folder in VS Code ESLint starts without any problem.

`npm config get prefix` gives me `/home/ris/.nvm/versions/node/v9.6.1`

When I set `eslint.trace.server` to `verbose` I still get `[Trace - 7:08:40 PM] NODE_PATH value is: /usr/local/lib/node_modules` (`eslint.nodePath` is `null` for both user and workspace settings).

Maybe there is some value cached by VS Code or ESLint?

**Comment by dbaeumer** [comment]
We don't cache any of these values. You even get a new server on a new workspace folder Window. Can you think of any difference between the two projects? Is `npm config get prefix` the same for both projects?

**Comment by ris58h** [comment]
`npm config get prefix` is the same for both projects.

I opened another (3rd) project and it has the same issue. So I deleted `node_modules` for working project (I believe there was some implicit eslint dependency/config) and found out that it's a global problem with my environment.

I fully reinstalled the extension and ESLint but still get the error.

Running `eslint path_to_file` from console works fine.

**Comment by dbaeumer** [comment]
This is very strange. Under `/home/ris/.nvm/versions/node/v9.6.1/lib/node_modules` is there an eslint folder containing the eslint npm package ? And just to double check. Are you using yarn ?

**Comment by ris58h** [comment]
There is ESLint (package.json shows me 4.8.12). I do not use yarn. Those projects are simple web-extensions without any package manager.

**Comment by ris58h** [comment]
I have to add that I missed some important trace message:
`[Trace - 11:49:49 PM] 'npm config get prefix' value is: /usr/local`
`[Trace - 11:49:49 PM] NODE_PATH value is: /usr/local/lib/node_modules`
but `npm config get prefix` from VS Code terminal is still `/home/ris/.nvm/versions/node/v9.6.1`
Seems like it's a VS Code problem.

**Comment by dbaeumer** [comment]
How do you start VS Code? Can you start it from the terminal where `npm config get prefix` prints the correct value. Then everything is fine I guess. I suspect that when VS Code is started using some dock icon then the environment is not set correctly (e.g.the .bashrc usually doesn't do all things when not in interactive mode). This is nothing VS Code not ESLint can fix. It is how shells / *nix behaves.

**Comment by ris58h** [comment]
You are right. It works when I start it from console.
Thank you for your time!
