### ISSUE TITLE
[eslint] Casing of {add node package} does not match the underlying filesystem. (import/no-unresolved)

### ISSUE THREAD

**Issue by PolGuixe** [Microsoft/vscode-eslint#422]
The linter doesn't seem to be able to resolve the node modules I have installed.

Do I need to add any configuration parameter? 

In the project, I am using VS-code the project the node_modules folder is in `project_folder/node_modules`.

**Comment by PolGuixe** [comment]
@dbaeumer I found the cause of the problem. 

We decided to change the name of the project from "RandomProjectName" to "randomprojectname". 

However, I didn't change the workspace path.... :( and this was causing the issue....

**Comment by clive107** [comment]
@PolGuixe I had the same issue with you. This solved my issue.
