### ISSUE TITLE
Config should check parent folders, even in multi-root workspaces.

### ISSUE THREAD

**Issue by WraithKenny** [Microsoft/vscode-eslint#428]
```
{
	"folders": [
		{
			"path": "folder"
		},
		{
			"path": "folder/subfolder"
		}
	]
}
```
Where `folder` contains the .eslintignore, package.json, etc.

When this ***isn't*** opened as a Multi-root Workspace, VSCode-ESLint will correctly find the config in it's parent `folder` when linting files within `folder/subfolder`. 

However, when opened as a Multi-root Workspace, it seems to stop checking at `folder/subfolder` and is prevented from checking it's parent (as eslint would normally do).

I've looked for issues regarding this, but those all seem to be concerned with non-nested paths. 

The only workaround I've found is to create `folder/subfolder/.vscode/settings.json` with the following:
```
{
	"eslint.workingDirectories": [
		"../"
	]
}
```
This seems...weird to have to do.

**Comment by dbaeumer** [comment]
@WraithKenny can you provide me with a GitHub repository I can clone that demos what you are seeing to ensure I have the same understanding about what is not working. I am not sure what you mean about config (e.g .eslintrc.* files, .eslintignore, ...)

**Comment by WraithKenny** [comment]
I don't know what happened, but it seems to work just fine now. :-/ loosing my mind I guess
