### ISSUE TITLE
[Feature Request]:Can choose to perform the check with the command

### ISSUE THREAD

**Issue by freedom5566** [Microsoft/vscode-eslint#429]
If I don't install eslint,can I want to use docker to build eslint command-line check code style.

e.g.

`docker --rm -ti $PWD:/usr/src/app eslint app.js`

Add vscode settings `eslint.checkcli:"docker --rm -ti $PWD:/usr/src/app eslint app.js"`

of course，`eslint.checkcli` Default is close.

**Comment by dbaeumer** [comment]
No, this is not possible through ESLint. However you could create a VS Code task that does this.

See: https://code.visualstudio.com/docs/editor/tasks
