### ISSUE TITLE
Rule for `import/no-extraneous-dependencies` being ignored

### ISSUE THREAD

**Issue by gregbty** [Microsoft/vscode-eslint#433]
We have the following snippet below in our ESLint config. Running lint directly yields no errors while the plugin does. The configuration is valid according to: [import/no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md#importno-extraneous-dependencies-forbid-the-use-of-extraneous-packages). We are using ESLint `4.18.2`.

<img width="513" alt="screen shot 2018-03-21 at 1 43 32 pm" src="https://user-images.githubusercontent.com/680484/37727304-de56d06c-2d0d-11e8-9bf0-625548c35004.png">

```json
    "import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": [
          "**/*.test.js",
          "**/*.tests.js",
          "**/*.stories.js",
          ".storybook/**/*.js"
        ]
      }
    ]
```

**Comment by dbaeumer** [comment]
Can you provide me with a GitHub respository I can clone that demos the behaviour?

**Comment by gregbty** [comment]
Here is a repo: https://github.com/gregbty/vscode-eslint-issue-433.

**Comment by dbaeumer** [comment]
@gregbty thanks. Unfortunately I can't run `yarn install` on the project. It results in 
```
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "@storybook/addon-links" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Any hint?

**Comment by gregbty** [comment]
It looks like it didn't find a lockfile when you ran the command, but it's definitely there: https://github.com/gregbty/vscode-eslint-issue-433/blob/master/yarn.lock. Maybe try re-pulling and trying again?

**Comment by dbaeumer** [comment]
@gregbty I deleted the yarn.lock file. If it is present yarn does nothing on my machine. No `node_modules` folder after running and no error message. `npm`fails as well with some strange SHA error message.

**Comment by dbaeumer** [comment]
@gregbty no I am not. I can't run yarn nor npm on the cloned GitHub repository successfully (e.g. in a way that a complete `node_modules` folder exists afterwards)

**Comment by gregbty** [comment]
Any other way to get you a repro?

**Comment by dbaeumer** [comment]
Can you try this on a different machine and see if you can use yarn or npm to install. Can anyone else provide a repro I can use that is cloneable and installable.
