### ISSUE TITLE
vscode giving error for file ignored in eslintignore

### ISSUE THREAD

**Issue by techsin** [Microsoft/vscode-eslint#434]
```
/frontend
    /src
        - .eslintrc
        - .eslintignore
        /lib
            - jquery.js
/backend
    -.eslintrc
    -.eslintignore


```

**frontend/src/.eslintrc**

```
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 2017,
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
        "no-console": "off"
    }
}
```

**frontend/src/.eslintignore**
`lib/*`

Workspace settings: 

```
{
    "editor.insertSpaces": false,
    "eslint.workingDirectories": [
        "./backend/",
        "./frontend/src/"
    ]
}
```

# Error:

9 errors with jquery.js (of course its minified file)

**Comment by dbaeumer** [comment]
@techsin since lib is a sibling of src you (to my knowledge) can't exclude lib that way. 

What happens if you run eslint from a terminal in the src directory ?

**Comment by techsin** [comment]
ok sorry /lib is inside /src

**Comment by techsin** [comment]
now errors only appear when you select the minified itself after few seconds but as soon as you select another file errors disappear.

**Comment by dbaeumer** [comment]
I don't think that this has anything to do with the number of files to got through. An example demoing this is still highly appreciated.
