### ISSUE TITLE
Only show problems from tab that currently has the focus

### ISSUE THREAD

**Issue by doberkofler** [Microsoft/vscode-eslint#435]
The VS Code eslint plugin shows all problems in the `Problems` pane but it would be very useful to only see (and concentrate on) the problems in the file currently working on.
Is there a way to do so and if not, could an option be added to configure this?

**Comment by dbaeumer** [comment]
This is something that should be supported by VS Code (e.g filter the problems view based on the active editor) instead of adding an option to the ESLint extension which makes it very specific to ESLint. I am closing the issue. Please file a corresponding feature request against VS Code.

**Comment by doberkofler** [comment]
I opened a new request but was wondering, if only checking the current file might not also improve the overall performance of the eslint plugin?

**Comment by dbaeumer** [comment]
ESLint only check the current file you are typing in. However the VS Code guideline is generate errors for all files that are open. This is why as long as a file is open and errors where detected they are shown in the problems view. When you close a file they are cleared. In this regard ESLint extension tries to be a good extension.
