### ISSUE TITLE
Strange errors

### ISSUE THREAD

**Issue by renaudtertrais** [Microsoft/vscode-eslint#439]
Hello,

I have a strange behaviour. Sometimes Eslint highlight wrong errors (not present when using the cli). It feels like little glitches: 
![image](https://user-images.githubusercontent.com/5002260/38021697-e345b2e4-327d-11e8-9907-19f2b7a56dba.png)

![image](https://user-images.githubusercontent.com/5002260/38021738-f62838b4-327d-11e8-8fe6-849f8a4ef420.png)

For example, here there are not even the corresponding error lines:

![image](https://user-images.githubusercontent.com/5002260/38021460-330e764a-327d-11e8-86ee-1ef4807b6198.png)

Any ideas ?

**Comment by dbaeumer** [comment]
These errors don't come from the ESLint extension. They come from the build in JS support. You can see this by the`[js]` prefix. ESLint errors are prefix with `[eslint]`.

Please report the issue directly to VS Code.
