### ISSUE TITLE
eslint server takes ~3-5 minutes until available

### ISSUE THREAD

**Issue by schmic** [Microsoft/vscode-eslint#440]
I don't know since when this is a problem but the start of the eslint server takes between 3-5 minutes here.

```
[Info  - 10:12:55] ESLint server is running.
[Info  - 10:16:05] ESLint library loaded from: d:\Workspaces\xxx\xxx-client\node_modules\eslint\lib\api.js
```

I just upgraded from eslint 3.x to 4.19.1, which didn't help.

Any information I can provide to hunt that down?

**Comment by dbaeumer** [comment]
I have another report about slow startup times, but I was never able to reproduce this. If I give you instructions how to compile ESLint form source would you be willing to debug / profile this to see where the time is spent. Do you see CPU load during this time ?

If you run ESLint on the same project from the command line (terminal) do you see slow start up as well?

**Comment by schmic** [comment]
If I run ESLint by hand it works flawless and instantly.
There is a short CPU spike for ~2-3 seconds.

Sure you can provide information to gather more data!

**Comment by dbaeumer** [comment]
Let use first enable some logging. For the workspace you see this can you set the following option: `"eslint.trace.server": "verbose"` and paste the output from the ESLint output channel here.

**Comment by schmic** [comment]
I had to obfuscate the output a bit ...

```
[Trace - 09:30:39] Sending request 'initialize - (0)'.
Params: {
    "processId": 56720,
    "rootPath": "c:\\Users\\myUserName\\Workspace\\myProjectName\\myProjectName-client",
    "rootUri": "file:///c%3A/Users/myUserName/Workspace/myProjectName/myProjectName-client",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ]
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ]
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            }
        }
    },
    "initializationOptions": {
        "legacyModuleResolve": true,
        "nodePath": null,
        "languageIds": [
            "javascript",
            "javascriptreact"
        ],
        "workspaceFolders": [
            "[object Object]"
        ]
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///c%3A/Users/myUserName/Workspace/myProjectName/myProjectName-client",
            "name": "myProjectName-client"
        }
    ]
}


[Trace - 09:30:39] Received response 'initialize - (0)' in 235ms.
Result: {
    "capabilities": {
        "textDocumentSync": {
            "openClose": true,
            "change": 1,
            "willSaveWaitUntil": true,
            "save": {
                "includeText": false
            }
        },
        "codeActionProvider": true,
        "executeCommandProvider": {
            "commands": [
                "eslint.applySingleFix",
                "eslint.applySameFixes",
                "eslint.applyAllFixes",
                "eslint.applyAutoFix"
            ]
        }
    }
}


[Info  - 09:30:39] ESLint server is running.
[Trace - 09:30:39] Sending notification 'initialized'.
Params: {}


[Trace - 09:30:39] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/myUserName/Workspace/myProjectName/myProjectName-client/myProjectName-mobile/gulpfile.js",
        "languageId": "javascript",
        "version": 1,
        "text": "/* eslint angular/json-functions:0 */\nvar gulp = require('gulp'); // CONTENT OF FILE CUT OUT //"
    }
}


[Trace - 09:30:39] Received request 'client/registerCapability - (0)'.
Params: {
    "registrations": [
        {
            "id": "cfbbb9c3-f7fd-4093-b106-e8064ca946c1",
            "method": "workspace/didChangeConfiguration",
            "registerOptions": {}
        }
    ]
}


[Trace - 09:30:39] Sending response 'client/registerCapability - (0)'. Processing request took 1ms
No result returned.


[Trace - 09:30:39] Received request 'client/registerCapability - (1)'.
Params: {
    "registrations": [
        {
            "id": "dbe68a83-4906-4166-a7af-7e84d30c008b",
            "method": "workspace/didChangeWorkspaceFolders",
            "registerOptions": {}
        }
    ]
}


[Trace - 09:30:39] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
No result returned.


[Trace - 09:30:39] Received request 'workspace/configuration - (2)'.
Params: {
    "items": [
        {
            "scopeUri": "file:///c%3A/Users/myUserName/Workspace/myProjectName/myProjectName-client/myProjectName-mobile/gulpfile.js",
            "section": ""
        }
    ]
}


[Trace - 09:30:39] Sending response 'workspace/configuration - (2)'. Processing request took 1ms
Result: [
    {
        "validate": true,
        "packageManager": "npm",
        "autoFix": true,
        "autoFixOnSave": false,
        "options": {},
        "run": "onType",
        "nodePath": null,
        "workspaceFolder": {
            "name": "myProjectName-client",
            "uri": "file:///c%3A/Users/myUserName/Workspace/myProjectName/myProjectName-client"
        }
    }
]


[Trace - 09:33:49] 'npm config get prefix' value is: D:\Dev\NodeJS
[Trace - 09:33:49] NODE_PATH value is: D:\Dev\NodeJS\node_modules
[Trace - 09:33:50] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "ESLint library loaded from: c:\\Users\\myUserName\\Workspace\\myProjectName\\myProjectName-client\\node_modules\\eslint\\lib\\api.js"
}


[Info  - 09:33:50] ESLint library loaded from: c:\Users\myUserName\Workspace\myProjectName\myProjectName-client\node_modules\eslint\lib\api.js
The rule `angular/service-name` will be split up to different rules in the next version. Please read the docs for more information
[Trace - 09:33:51] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Users/myUserName/Workspace/myProjectName/myProjectName-client/myProjectName-mobile/gulpfile.js",
    "diagnostics": [
        {
            "message": "'log' is assigned a value but never used. (no-unused-vars)",
            "severity": 1,
            "source": "eslint",
            "range": {
                "start": {
                    "line": 14,
                    "character": 4
                },
                "end": {
                    "line": 14,
                    "character": 7
                }
            },
            "code": "no-unused-vars"
        }
    ]
}


[Trace - 09:33:51] Received notification 'eslint/status'.
Params: {
    "state": 1
}
```

**Comment by drw112** [comment]
I have exactly the same output as @schmic .  At about 3 minutes and 10 seconds after the project has started ESLint will start reporting errors in my files.  I compared my verbose output to his and it looks nearly identical.

**Comment by dbaeumer** [comment]
@schmic thanks for the trace. The normal startup of the server is as expected however querying the node / npm configuration seems to take a long time on your machine. I believe you are hitting a known problem with `npm config get prefix` (see https://github.com/npm/npm/issues/14458).

@schmic  and @drw112 to confirm this can you please both open a terminal and then run `npm config get prefix` in the terminal and let me know how it performs.

**Comment by dbaeumer** [comment]
Another thing you can do is the following: set the eslint setting nodePath to the value where you global node modules are installed e.g to the value returned from `npm config get prefix`. @schmic in your case `"eslint.nodePath"="D:\\Dev\\NodeJS\\node_modules"`

**Comment by drw112** [comment]
For me `npm config get prefix` returns in <1 second.  

If I set ```eslint.nodePath``` to the value returned by `npm config get prefix` in my VSCode user settings it has no noticeable impact on load time. Still ~3 minutes.

**Comment by dbaeumer** [comment]
@drw112 in our trace is there also a big time gap before you see `npm config get prefix` in the log?

**Comment by schmic** [comment]
```
% time npm config get prefix
D:\Dev\NodeJS

real    0m1,859s
user    0m0,015s
sys     0m0,076s
```

ESLint is installed in my project (top-level node_modules folder), not globally. Though entering the path to it doesn't help.

Might this be a problem with sitting behind a proxy? Having one configured? ... ?

**Comment by drw112** [comment]
I am also behind a proxy and have one configured in npmrc.

**Comment by schmic** [comment]
What I know is that our firewall drops connections instead of rejecting them.
So if a process tries to connect to the outside world without using the configured proxy it results in a (30s?) timeout error, multiply that 5-6 tries ...

Mine is set in the environment (http_proxy/https_proxy) not .npmrc

**Comment by dbaeumer** [comment]
Would one of you be able to debug this if I give you instruction on how to do so? They are:

- clone this repository
- cd into the directory
- npm install
- npm run compile
- open the workspace with VS Code.
- go to client\src\extension.ts
- on line 361 change inspect to inspect-brk
- Run Task > npm run watch:client
- open debug panel and select Lanuch Extension. Press the run button
- in the start Code instance select the workspace the makes the eslint server crash
- go back to the Code instance that contains the eslint code
- debug panel
- select Attach to server and press the run button. This should break in electronForkStart.js
- open server/src/eslintServer.ts
- set a breakpoint in resolveSettings
- press continue
- step through the resolveSettings and see if there is any noticable delay.

Thanks!

**Comment by drw112** [comment]
It seems to be taking a very long time on line 310
`		_globalNpmPath = Files.resolveGlobalNodePath(trace);`

in the globalNpmPath function

It does eventually return the right path for the _globalNpmPath variable.

Looking in files.js it seems to be taking forever on the spawnSync command

Eventually stdout comes back with the npm folder in my roaming profile (Windows)


I see these log lines in the Debug Console

`
[dbaeumer.vscode-eslint] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'eslint._legacyModuleResolve', provide the URI of a resource or 'null' for any resource.
extensionHostProcess.js:494
[dbaeumer.vscode-eslint] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'eslint.nodePath', provide the URI of a resource or 'null' for any resource.
extensionHostProcess.js:494
`

**Comment by dbaeumer** [comment]
The `Files.resolveGlobalNodePath(trace)` call at the end call `npm config get prefix` :-). May be it is a problem when executed from within node.

Thanks for the debug output. This is caused on the client and has no impact on the server startup. I will look into this.

**Comment by dbaeumer** [comment]
Can you take this little program and execute it in node

```
var cp = require('child_process');

console.log(cp.spawnSync('npm.cmd', ['config', 'get', 'prefix'], {
	encoding: 'utf8'
}).stdout);
```

How long does it take ?

**Comment by drw112** [comment]
About 3 minutes 😄 

PS R:\> node test.js
C:\Users\[username]\AppData\Roaming\npm

**Comment by schmic** [comment]
Thanks @drw112 for helping out with those infos.

```
~/Workspace % time node foo.js
D:\Dev\NodeJS


real    3m9,346s
user    0m0,015s
sys     0m0,016s
```

**Comment by dbaeumer** [comment]
Frankly speaking I have no idea why spawning a shell and running `npm config get prefix` takes 3 minutes on your systems. Interestingly both see ~3 minutes so it looks like node is waiting for something and then times out. Could you change the simple program to for example execute 'dir' / 'ls' to see whether it is a spawn problem or a problem of npm

**Comment by schmic** [comment]
```
~/Workspace % time node foo.js
birt-engine  foo.js  xyz


real    0m0,452s
user    0m0,015s
sys     0m0,015s
```

**Comment by schmic** [comment]
The problem is spawning `npm.cmd`.
That alone takes ~3 minutes here with no other arguments

**Comment by schmic** [comment]
As I said, I'm behind a proxy / firewall.

I've set http_proxy & https_proxy environment variables which npm respects when installing modules. If I switch into our guest wlan and execute the little program from above it works instantly.

```
~/Workspace % time node foo.js
D:\Dev\NodeJS


real    0m1,563s
user    0m0,015s
sys     0m0,015s
```

As I said our firewall drops instead of rejecting connections so they end up in a timeout, multiply that 30s timeout by 6 and you get the 3 minutes waiting time.

Is there an update check or something?

**Comment by dbaeumer** [comment]
What I don't get is when you execute `npm get config prefix` in the terminal directly it is instant. If launched from another node process it is not. Spawn inherits the environment from the parent process so the https_proxy environment variables should be setup as well.

**Comment by schmic** [comment]
Some more information.

I run Windows 7 here, running git-bash.exe, usually. In that environment we have that problem. If I execute the same thing from a dos-prompt it works as it should ...

**Comment by schmic** [comment]
If I start VS Code by double-clicking the .exe:
```
[Info  - 11:02:14] ESLint server is running.
[Info  - 11:02:17] ESLint library loaded from: c:\Users\userNameWorkspace\xxx\xxx-client\node_modules\eslint\lib\api.js
The rule `angular/service-name` will be split up to different rules in the next version. Please read the docs for more information
```

**Comment by schmic** [comment]
foo.js
```
var cp = require('child_process');
console.log(cp.spawnSync('foo.cmd', [], {
        encoding: 'utf8'
}).stdout);
```

foo.cmd
```
npm.cmd config get prefix
```

Executing:
```
~/Workspace % time node foo.js

C:\Users\gissr\Workspace>npm.cmd config get prefix
D:\Dev\NodeJS


real    0m1,211s
user    0m0,000s
sys     0m0,015s
```

**Comment by dbaeumer** [comment]
@schmic great.

@drw112 what's about you?

**Comment by drw112** [comment]
I did a bit more testing. The files provided by  @schmic don't have a noticeable effect on my execution time.  Which I thought was odd.  So, I borrowed a spare machine and installed Node 8.11.1 on it.  The execution time running with the external foo.cmd and with the args are both very fast ~1 second.

So this doesn't seem to have anything to do with the proxy but rather how my Node environment is setup on this particular machine.

**Comment by drw112** [comment]
It looks like this issue is already being talked about here: https://github.com/npm/npm/issues/19756

**Comment by schmic** [comment]
Good morning.

```
~/Workspace % time node foo.js
D:\Dev\NodeJS


real    3m9,323s
user    0m0,000s
sys     0m0,031s
```

```
~/Workspace % export NO_UPDATE_NOTIFIER=1 && time node foo.js
D:\Dev\NodeJS


real    0m1,091s
user    0m0,016s
sys     0m0,000s
```

Works for me.

**Comment by dbaeumer** [comment]
@schmic & @drw112 thanks a lot for the great analysis of the problem.
