### ISSUE TITLE
Bug with custom alias in Webpack (Mono-Repo with Multiple Apps)

### ISSUE THREAD

**Issue by kamalbennani** [Microsoft/vscode-eslint#441]
Following https://github.com/Microsoft/vscode-eslint/issues/405 I am facing exactly the same problem where my project is composed of a several applications and each them might define a "custom" webpack configuration which extends a common configuration which is defined in the root of the project.
```
/
apps/
- app1/
  webpackConfig.js  <-- specific to app1
  .eslintrc
- app2/
  webpackConfig.js  <-- specific to app2
  .eslintrc
- app3/
  webpackConfig.js <-- specific to app3
  .eslintrc
webpack.config.js <-- common configuration
```
A custom webpack configuration looks like so:
__apps/app1/webpackConfig.js__
```JS
export function (baseConfig) => {
 newConfig = baseConfig
 // Some custom manipulation
 ....
 return newConfig
}
```

**Note that the common webpack configuration is responsible for determining which webpack configuration to load based on the application name**.
So for instance, to run the `app1`, we execute the following command :
```SH
webpack-dev-server  --config webpack.config.js --env app1
```

the eslint configuration might look like this:
__apps/app1/.eslintrc.js__
```JS
const path = require('path');
module.exports = {
  settings: {
    'import/resolver': {
      webpack: {
        config: path.resolve(__dirname, '../../webpack.config.js'),
        env: 'app1'
      }
    }
  },
};
```
When running the linter in CMD it works without throwing any error, but in the IDE it shows that all my imports are wrong.
**Note that I am using alias resolver in the root webpack config and also in the other app's configuration**

**Comment by dbaeumer** [comment]
@kamalbennani can you please provide a GitHub repository I can clone that demos the behaviour. Please note that if you have a mono repository you need to configure roots using the `eslint.workingDirectories` as described here: https://github.com/Microsoft/vscode-eslint
