### ISSUE TITLE
eslint Javascript, new exponent operator doesn't work.

### ISSUE THREAD

**Issue by Leeoku** [Microsoft/vscode-eslint#445]
Delete

**Comment by Leeoku** [comment]
I believe the linter is not accepting ** as exponent in JS, used in VSCODE

> Error received: Parsing error: Unexpected token *

Current Code:

```
function square(num) {
  return Math.pow(num,2);
}
```

Code that works:

```
function square(num) {
  return Math.pow(num,2);
}

```

**Comment by dbaeumer** [comment]
Does this validate correctly when running ESLint from the terminal.

**Comment by Leeoku** [comment]
i installed eslint from terminal and set up a config file. Running my file still errors
https://i.imgur.com/tvDm2vn.png

**Comment by dbaeumer** [comment]
@Leeoku then this is a problem with eslint npm module itself. Can you please report the error here: https://github.com/eslint/eslint
