### ISSUE TITLE
code -add and workingDirectories

### ISSUE THREAD

**Issue by jake-lambert-volusion** [Microsoft/vscode-eslint#448]
I work with a large number of repos. As a workflow, I have a primary workspace and frequently add and remove folders depending on the set of issues I am working on.

I frequently `code -add ./whatever-i-just-cloned`. From what I can tell, `vscode-eslint` does not lint `whatever-i-just-cloned` unless I add it to `eslint.workingDirectories` in my workspace settings.

In a multi-root workspace, is it possible for me to configure vscode-eslint and/or vscode itself in such a way that it will automatically detect my eslint config in any of the roots?

Thank you for a great product!

**Comment by dbaeumer** [comment]
Actually that should work. The ESLint extension listen to workspace folder changes and validates them as soon as they are added to VS Code. But you need to open a folder to get the validation to work and eslint must be configured correctly for the folder you added (e.g. the folder needs to validate using ESLint when you open just this folder)

**Comment by jake-lambert-volusion** [comment]
I think my problem was that I don't use global eslint and was doing `code -add` before `npm install`. 

Thank you @dbaeumer!
