### ISSUE TITLE
Error when validating package.json with comments.

### ISSUE THREAD

**Issue by telemmaite** [Microsoft/vscode-eslint#451]
Looks like this issue is back.
https://github.com/Microsoft/vscode-eslint/issues/141

I have a package.json generated from ExtJS Sencha command, which is non standard JSON with comments inside. VS Code keeps pinging that there is an error, **even though I have explicitly set** 
`
    "eslint.validate": [
        "javascript",
        "javascriptreact"
    ]
`

> MY LOG xxx\..\..\package.json
[Error - 4:27:25 PM] ESLint stack trace:
[Error - 4:27:25 PM] SyntaxError: Unexpected token / in JSON at position 7
    at JSON.parse (<anonymous>)
    at new IgnoredPaths (C:\Users\xx\AppData\Roaming\npm\node_modules\eslint\lib\ignored-paths.js:176:55)
    at CLIEngine.executeOnText (C:\Users\xx\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:601:28)
    at validate (C:\Users\xx\.vscode\extensions\dbaeumer.vscode-eslint-1.4.8\server\out\eslintServer.js:586:26)
    at resolveSettings.then (C:\Users\xx\.vscode\extensions\dbaeumer.vscode-eslint-1.4.8\server\out\eslintServer.js:517:13)
    at <anonymous>

`MY LOG` is console.log added by me in. 
> C:\Users\xx\AppData\Roaming\npm\node_modules\eslint\lib\ignored-paths.js line 173.

**Comment by telemmaite** [comment]
Yes the error that is triggered is because JSON.parse cannot handle the comment (checked that myself).
I am perfectly fine with this. 
All I want to configure **vscode-eslint** to scan **only .js** files and **exclude any .json** files such as **package.json**.

I dont understand how to properly exclude .json files. I though `"eslint.validate": [ "javascript", "javascriptreact" ]` which are defaults should do that ?

**Comment by dbaeumer** [comment]
@telemmaite ESLint is not validating the `package.json` file. The ESLint npm module reads the `package.json` file NOT to validate it. It reads it to check if the package.json contains any ESLint configuration options. See here why: https://eslint.org/docs/user-guide/configuring. The section of interest is labeled `Or in a package.json file`

**Comment by telemmaite** [comment]
Thanks a lot for the clarification! I created a .eslintignore file and added the package.json with comments inside. Now I am no longer spammed by the popup message.
