### ISSUE TITLE
ESLint extension missing 'javascript' tag

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-eslint#453]
https://github.com/Microsoft/vscode-docs/issues/1420 noted that ESLint is not displayed in the query of popular JavaScript extensions on the languages/javascript topic.
The Marketplace query is simply searching for "javascript". 
Adding a 'javascript' tag to package.json should help users find this JavaScript extension.

**Comment by dbaeumer** [comment]
@gregvanl where do I add this tag. All I have is a `"categories"` field?

**Comment by gregvanl** [comment]
Looking at the tagging source code in vsce, I think the easiest way is to add "JavaScript" to the extension description.
How about changing the description to: "Integrates the ESLint JavaScript Linter into VS Code"?
You can also add a keyword to package.json but having a better description is probably a good thing.

**Comment by dbaeumer** [comment]
Changed the description as recommended.
