### ISSUE TITLE
Option to disable highlighting in overview ruler (scroll bar gutter)

### ISSUE THREAD

**Issue by josephtannenbaum** [Microsoft/vscode-eslint#454]
Sometimes the green labelling of lines in the overview ruler (scroll bar gutter) is visually disruptive, it would be nice to turn it off via a `eslint.enableOverviewRulerHighlighting` type setting.

If the option exists already, it should be in the readme!

Example:

![screen shot 2018-04-17 at 5 10 17 pm](https://user-images.githubusercontent.com/28641/38897516-419fed70-4262-11e8-9b9d-b5c8c0d50cf7.png)

**Comment by dbaeumer** [comment]
This is nothing ESLint controls. The overview ruler is managed by VS Code itself. I checked the VS Code options and couldn't find one. Please open a feature request here: https://github.com/Microsoft/vscode
