### ISSUE TITLE
The ESLint server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by gufonsecaa** [Microsoft/vscode-eslint#458]
I tried to install the ESLint extension but when I open a file ".js" show this error "The ESLint server crashed 5 times in the last 3 minutes. The server will not be restarted".

Info:
Version VSCode: 1.22.2
Architecture: x64

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode-eslint/issues/437.

@gufonsecaa Please see the steps around debugging. So far I was not able to understand why this happens on a handful of machines.
