### ISSUE TITLE
Add syntax highlighting for .eslintignore file

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode-eslint#459]
Please add syntax highlighting for .eslintignore files, mostly so comments are highlighted.

I don't know if it should just use the `Shell script` format, or the same one as used in .gitignore files, etc.?

**Comment by dbaeumer** [comment]
Actually VS Code has no syntax coloring for .gitignore. Or do you see that colored ?

**Comment by garyking** [comment]
I'm using the [gitignore](https://marketplace.visualstudio.com/items?itemName=codezombiech.gitignore) extension for gitignore files, so perhaps the eslint ext could do the same and color eslintignore files the same way?

**Comment by Hirse** [comment]
@dbaeumer, can we close this one now?

**Comment by dbaeumer** [comment]
Yes, we can. thanks for pinging.
