### ISSUE TITLE
How do I get this plugin to work?

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-eslint#46]
I have gone through the (scant) documentation like ten times, but I still fail to understand how I am supposed to get this plugin to work.

Other editors like Sublime and Atom *just work* when they find an `.eslintrc` file in a parent of my current folder in the workspace, and pickup the `eslint` and `babel-eslint` packages from the workspace's `node_modules` folder.

With vscode, I'm completely bamboozled as to what I have to do.

From what I can understand in the fragmented documentations, I added a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson) file in my workspace. I also tried to add the `eslintrc` rules directly into the my Workspace settings in the [`eslint.options` object](https://github.com/Microsoft/vscode-eslint/tree/master/eslint#configuration-options).

And still, when I write bad code, this is what I get:

```
(options.globals || []).reduce is not a function
```

How can I figure what is going wrong from that? Where is this error coming from? Is there a guide anywhere which lays down what all *exact* steps have to be taken to get this working?

**Comment by dbaeumer** [comment]
Here is what works for me

* either install eslint globally or locally into your workspace folder using npm
* create a .eslintrc file using eslint --init

If this doesn't work can you share the workspace that shows the broken bahavior.

**Comment by kumarharsh** [comment]
For the life of me, I can't get it to reproduce that error today :disappointed: I'll update the issue if I *do* get this error again. Maybe that update to 0.10.10 fixed it, but I can't say for sure. Thanks for replying nonetheless, and I apologize for that rather sarcastic tone.
