### ISSUE TITLE
Add option to set --no-color

### ISSUE THREAD

**Issue by marekkaczkowski** [Microsoft/vscode-eslint#460]
Due to Windows problems with ANSI color codes it would be nice to have an option to disable it:

`eslint.noColor: Boolean`

Output in popover:
![ansi-vscode-eslint_042518_022945_pm](https://user-images.githubusercontent.com/273831/39245830-1bac8a40-4895-11e8-8485-b163583fda17.jpg)
Raw text:
```
[eslint]
Parsing error: Unexpected token

[0m[31m[1m>[22m[39m[90m 1 | [39m[36mimport[39m en[33m-[39mus from [32m'./en-US'[39m[0m
[0m [90m   | [39m         [31m[1m^[22m[39m[0m
[0m [90m 2 | [39m[36mimport[39m pl from [32m'./pl'[39m[0m
[0m [90m 3 | [39m[0m
[0m [90m 4 | [39m[36mexport[39m [36mdefault[39m {[0m
import en
```

Ref: Same issue in vscode-jest https://github.com/jest-community/vscode-jest/issues/279

**Comment by dbaeumer** [comment]
@marekkaczkowski did you run a task to get these errors? Can you provide me with a GitHub repository that I can clone that demos this. I have never seen this. The ESLint extension actually doesn't spawn any external terminal processes. It uses the ESLint npm module directly so it should never receive ANSI control characters

**Comment by marekkaczkowski** [comment]
Got it! `parser: 'babel-eslint'` is causing this issue. W can close it.
