### ISSUE TITLE
Add setting "don't show autofixable errors"

### ISSUE THREAD

**Issue by Herteby** [Microsoft/vscode-eslint#461]
It's kind of distracting to see errors about autofixable things.
It'd be awesome if there was a setting to not show them, and just fix them with autoFixOnSave!
Looking at the ESLint API, message objects have a "fix" property if they are fixable, so you could probably just filter them by that.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode-eslint/issues/267
