### ISSUE TITLE
ESLint server stopped.

### ISSUE THREAD

**Issue by gufonsecaa** [Microsoft/vscode-eslint#467]
The ESLint is not working in my computer. 
That is the VSCode output log.

[Trace - 14:05:41] Sending request 'initialize - (0)'.
Params: {
    "processId": 15636,
    "rootPath": "c:\\Projects\\gonode\\snippetfy",
    "rootUri": "file:///c%3A/Projects/gonode/snippetfy",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ]
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ]
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            }
        }
    },
    "initializationOptions": {
        "legacyModuleResolve": false,
        "nodePath": "C:/Users/Gustavo/node_modules",
        "languageIds": [
            "javascript",
            "javascriptreact"
        ],
        "workspaceFolders": [
            "[object Object]"
        ]
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///c%3A/Projects/gonode/snippetfy",
            "name": "snippetfy"
        }
    ]
}

[Trace - 14:05:41] Received response 'initialize - (0)' in 223ms.
Result: {
    "capabilities": {
        "textDocumentSync": {
            "openClose": true,
            "change": 1,
            "willSaveWaitUntil": true,
            "save": {
                "includeText": false
            }
        },
        "codeActionProvider": true,
        "executeCommandProvider": {
            "commands": [
                "eslint.applySingleFix",
                "eslint.applySameFixes",
                "eslint.applyAllFixes",
                "eslint.applyAutoFix"
            ]
        }
    }
}

[Info  - 14:05:41] ESLint server is running.
[Trace - 14:05:41] Sending notification 'initialized'.
Params: {}

[Trace - 14:05:41] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Projects/gonode/snippetfy/index.js",
        "languageId": "javascriptreact",
        "version": 1,
        "text": "const express = require('express');\nconst bodyParser = require('body-parser');\nconst nunjucks = require('nunjucks');\nconst path = require('path');\nconst routes = require('./app/routes');\n\nconst app = express();\n\napp.use(express.static(path.resolve('app', 'public')));\n\nnunjucks.configure(path.resolve('app', 'views'), {\n  autoescape: true,\n  express: app,\n});\n\napp.set('view engine', 'njk');\napp.use(bodyParser.urlencoded({ extended: false }));\n\napp.use('/', routes);\n\napp.listen(3000);\n"
    }
}

[Trace - 14:05:41] Received request 'client/registerCapability - (0)'.
Params: {
    "registrations": [
        {
            "id": "e931dc64-4c93-4996-9626-2b688205013d",
            "method": "workspace/didChangeConfiguration",
            "registerOptions": {}
        }
    ]
}

[Trace - 14:05:41] Sending response 'client/registerCapability - (0)'. Processing request took 1ms
No result returned.

[Trace - 14:05:41] Received request 'client/registerCapability - (1)'.
Params: {
    "registrations": [
        {
            "id": "2131cefe-5f02-496c-bc54-c2784324ea4a",
            "method": "workspace/didChangeWorkspaceFolders",
            "registerOptions": {}
        }
    ]
}

[Trace - 14:05:41] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
No result returned.

[Trace - 14:05:41] Received request 'workspace/configuration - (2)'.
Params: {
    "items": [
        {
            "scopeUri": "file:///c%3A/Projects/gonode/snippetfy/index.js",
            "section": ""
        }
    ]
}

[Trace - 14:05:41] Sending response 'workspace/configuration - (2)'. Processing request took 1ms
Result: [
    {
        "validate": true,
        "packageManager": "npm",
        "autoFix": true,
        "autoFixOnSave": false,
        "options": {},
        "run": "onType",
        "nodePath": "C:/Users/Gustavo/node_modules",
        "workspaceFolder": {
            "name": "snippetfy",
            "uri": "file:///c%3A/Projects/gonode/snippetfy"
        }
    }
]

[Info  - 14:05:41] Connection to server got closed. Server will restart.
[Info  - 14:05:41] ESLint server stopped.
[Trace - 14:05:43] Sending request 'initialize - (0)'.
Params: {
    "processId": 15636,
    "rootPath": "c:\\Projects\\gonode\\snippetfy",
    "rootUri": "file:///c%3A/Projects/gonode/snippetfy",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ]
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ]
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            }
        }
    },
    "initializationOptions": {
        "legacyModuleResolve": false,
        "nodePath": "C:/Users/Gustavo/node_modules",
        "languageIds": [
            "javascript",
            "javascriptreact"
        ],
        "workspaceFolders": [
            "[object Object]"
        ]
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///c%3A/Projects/gonode/snippetfy",
            "name": "snippetfy"
        }
    ]
}

[Trace - 14:05:43] Received response 'initialize - (0)' in 105ms.
Result: {
    "capabilities": {
        "textDocumentSync": {
            "openClose": true,
            "change": 1,
            "willSaveWaitUntil": true,
            "save": {
                "includeText": false
            }
        },
        "codeActionProvider": true,
        "executeCommandProvider": {
            "commands": [
                "eslint.applySingleFix",
                "eslint.applySameFixes",
                "eslint.applyAllFixes",
                "eslint.applyAutoFix"
            ]
        }
    }
}

[Info  - 14:05:43] ESLint server is running.
[Trace - 14:05:43] Sending notification 'initialized'.
Params: {}

[Trace - 14:05:43] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Projects/gonode/snippetfy/index.js",
        "languageId": "javascriptreact",
        "version": 1,
        "text": "const express = require('express');\nconst bodyParser = require('body-parser');\nconst nunjucks = require('nunjucks');\nconst path = require('path');\nconst routes = require('./app/routes');\n\nconst app = express();\n\napp.use(express.static(path.resolve('app', 'public')));\n\nnunjucks.configure(path.resolve('app', 'views'), {\n  autoescape: true,\n  express: app,\n});\n\napp.set('view engine', 'njk');\napp.use(bodyParser.urlencoded({ extended: false }));\n\napp.use('/', routes);\n\napp.listen(3000);\n"
    }
}

[Trace - 14:05:43] Received request 'client/registerCapability - (0)'.
Params: {
    "registrations": [
        {
            "id": "8974fdda-d89c-4f46-bd32-389965aad9c0",
            "method": "workspace/didChangeConfiguration",
            "registerOptions": {}
        }
    ]
}

[Trace - 14:05:43] Sending response 'client/registerCapability - (0)'. Processing request took 1ms
No result returned.

[Trace - 14:05:43] Received request 'client/registerCapability - (1)'.
Params: {
    "registrations": [
        {
            "id": "11ce622d-d605-4250-a906-d4e1a5b389d9",
            "method": "workspace/didChangeWorkspaceFolders",
            "registerOptions": {}
        }
    ]
}

[Trace - 14:05:43] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
No result returned.

[Trace - 14:05:43] Received request 'workspace/configuration - (2)'.
Params: {
    "items": [
        {
            "scopeUri": "file:///c%3A/Projects/gonode/snippetfy/index.js",
            "section": ""
        }
    ]
}

[Trace - 14:05:43] Sending response 'workspace/configuration - (2)'. Processing request took 0ms
Result: [
    {
        "validate": true,
        "packageManager": "npm",
        "autoFix": true,
        "autoFixOnSave": false,
        "options": {},
        "run": "onType",
        "nodePath": "C:/Users/Gustavo/node_modules",
        "workspaceFolder": {
            "name": "snippetfy",
            "uri": "file:///c%3A/Projects/gonode/snippetfy"
        }
    }
]

[Info  - 14:05:43] Connection to server got closed. Server will restart.
[Info  - 14:05:43] ESLint server stopped.

**Comment by dbaeumer** [comment]
@gufonsecaa this sounds like a dup of https://github.com/Microsoft/vscode-eslint/issues/437 however your report has more details. Is this reproducible for you even on a different machine using the same setup. If so, can you provide me with a GitHub repository I can clone that demos this.
