### ISSUE TITLE
Feature Request: "Global Rule Severity" Setting

### ISSUE THREAD

**Issue by ashrafhadden** [microsoft/vscode-eslint#468]
**Issue**
Most ESLint Shared Configs (ex. [AirBnB](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb), [StandardJS](https://github.com/standard/eslint-config-standard)) use "error" as their default rule severity. I use large eslint-config's through VSCode and prefer to have all of my ESLint Problems (VSCode's "Problems" Window under View menu) show up as warnings since they are almost all style-related. This allows me to keep all of my _actual_ error Problems (i.e. syntax errors) separate from my style Problems. Currently I have to find and replace all "error" with "warn" in my eslint-config's or maintain massive .eslintrc files to override all the "error"'s.

**Proposed Solution**
Add a "Global/Maximum Severity" option in VSCode Settings that overrides all other rule severities.

**Related Issue**
I wasn't sure which repo was more relevant to this issue so I also posted in [vscode](https://github.com/Microsoft/vscode/issues/49788)'s repo.

**Comment by dbaeumer** [comment]
This is the right repository for this.

**Comment by lolmaus** [comment]
Two years into this, any champion willing to make another attempt?
