### ISSUE TITLE
There are garbled characters in the eslint error message

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode-eslint#469]
Issue Type: <b>Bug</b>

![eslint](https://user-images.githubusercontent.com/24318019/40042621-9f8e99ce-5854-11e8-8b7f-a07f369d079f.png)
The correct error message is:
![subl](https://user-images.githubusercontent.com/24318019/40042690-d194756a-5854-11e8-89b5-6a36db3820cf.png)
 

Extension version: 1.4.8
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by dbaeumer** [comment]
Are you using any special ESLint parser. 

Could you provide me with a GitHub repository I can clone that demos this?

**Comment by shizengzhou** [comment]
When using globally installed ESLint, the issuse appears.
[demo](https://github.com/shizengzhou/demo.git)

**Comment by dbaeumer** [comment]
@shizengzhou can you please provide me with a self contained example (e.g. a package.json file which installs all necessary dependencies). Your example depends on more than a gloablly installed ESLint. A self contained example in addition ensures we are using the same versions.

**Comment by shizengzhou** [comment]
When using locally installed ESLint, there is no issue.
My globally installed packages:
![npm](https://user-images.githubusercontent.com/24318019/40109960-5601e724-5931-11e8-8d43-06fc33917dc8.png)

**Comment by dbaeumer** [comment]
I can't reproduce this: 

<img width="988" alt="capture" src="https://user-images.githubusercontent.com/1931590/40112276-c1f27128-5905-11e8-92ca-cad8a2dc9737.png">

Any additional steps?

**Comment by shizengzhou** [comment]
I update my eslint, babel-eslint and eslint-config-alloy, now there is no issue.
