### ISSUE TITLE
Real-time check failure

### ISSUE THREAD

**Issue by YlinOu** [Microsoft/vscode-eslint#470]
Issue Type: <b>Bug</b>

Real-time check failure

Extension version: 1.4.8
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

**Comment by dbaeumer** [comment]
@YlinOu can you please provide more details about the problem you are seeing.
