### ISSUE TITLE
Error with 'Cannot find module 'espree' (undefined:undefined)'

### ISSUE THREAD

**Issue by SamStonehouse** [Microsoft/vscode-eslint#471]
When using the vscode plugin I get the following errors in any file which imports 'point', a simple local file which I can provide if required, it simply exports a class definition as default and that's it (no other exports).

`Parse errors in imported module './point': Cannot find module 'espree' (undefined:undefined) (import/no-named-as-default-member)

The vscode eslint plugin shows no errors for the actual point file.

When running eslint from the command line in my project I get no errors.

I can update my .eslintrc to add `'import/no-named-as-default-member': 'off'` and the problem goes away but I thought I'd bring it up here as it seems a little unusual.

vscode-eslint version - 1.4.9
eslint version: 4.19.1

**Comment by dbaeumer** [comment]
@SamStonehouse can you provide me with a GitHub repository I can clone that demos this ?

**Comment by SamStonehouse** [comment]
I'll try to reproduce on a repository I can share, give me some time

**Comment by flpStrri** [comment]
I am facing the same issue here. You can check my repo: https://github.com/flpStrri/Lilium

**Comment by dbaeumer** [comment]
@flpStrri I cloned the repository but I don't see any errors. Any additional steps.

**Comment by flpStrri** [comment]
Nope, It was simply there, I will check It out again and push a commit there if needed.

**Comment by dbaeumer** [comment]
Still not able to reproduce.

**Comment by flpStrri** [comment]
@dbaeumer it was long ago, I also don't see the error anymore. :/

**Comment by progmax** [comment]
Getting this error... What data is needed?
