### ISSUE TITLE
Nested .eslintrc

### ISSUE THREAD

**Issue by MundakaZgz** [Microsoft/vscode-eslint#472]
Hello,

I am having issues in my project with nested .eslintrc files.

I have a big project and each module has its own linting rules but all modules share some common rules configured in a .eslintrc file placed on the root of the project (eg. use sigle quotes).

When I run the eslint script it correctly evaluates the rules needed for each file but the plugin tells me that my strings should be double quoted. This makes me thing that the nesting is not supported/resoved.

Any ideas?

Thanks!

**Comment by dbaeumer** [comment]
@MundakaZgz can you provide me with a GitHub repository I can clone that demos this. Since the ESLint extension is based on the ESLint npm module to read .eslintrc files all the features from ESLint standalone should be supported as well.

**Comment by MundakaZgz** [comment]
I have tried to reproduce it in a smaller project so I can share it with you but it is not happening there. I'll recheck what could be happening in my other project as I think it is misconfigured.
Thanks!!
