### ISSUE TITLE
error ‘Parsing error: Unexpected token =>’ with eslint default config

### ISSUE THREAD

**Issue by bi-kai** [Microsoft/vscode-eslint#475]
My config file is `.eslintrc.js` with context like this:
```javascript
    "env": {
        "es6": true,
        "node": true
    },
```

my code:
```javascript
router.get('/', async (ctx, next) => {
    let res = await delay(10000);
    console.log(res);

    ctx.response.type = 'html';
    ctx.response.body = `this is the home page.`;
});
```

I found out it's because of `async/await`, not a error of arrow function itself.
**My question is how to support es7 with eslint on vsc?**

**Comment by bi-kai** [comment]
@dbaeumer hi, i can run it in terminal, and got the same error:
![image](https://user-images.githubusercontent.com/15070379/40607163-490c9812-629a-11e8-9712-fc5b47c8590b.png)

I know it's not a error of `vs code` and `ESlint plugins in vsc`, I just don't know how to fix this with eslint configuration, and i haven't found it yet.

**Comment by dbaeumer** [comment]
@bi-kai I know what it is. It is a bug in VS Code itself and I fixed it for the next VS Code release. Dups https://github.com/Microsoft/vscode-eslint/issues/436
