### ISSUE TITLE
Doesn't run. No message or anything at all

### ISSUE THREAD

**Issue by iamdevlinph** [Microsoft/vscode-eslint#479]
VS Code Version: 1.23.1
node -v:  8.11.1
npm -v: 6.0.1

My **.eslintrc.js**
```
module.exports = {
  "extends": "airbnb",
  "rules": {
    "react/prefer-stateless-function": 0,
    "react/jsx-filename-extension": 0,
    "import/no-extraneous-dependencies": 0, // to allow the convenience package
    "jsx-a11y/anchor-is-valid": 0,
    "react/forbid-prop-types": 0, // for object prop type,
    "import/prefer-default-export": 0,

    "max-len": ["error", {
      "code": 120
    }],
  },
  "globals": {
    "document": true
  },
  "parser": "babel-eslint"
};
```

I have added the following lines to my user settings:
```
"eslint.trace.server": "messages",
"eslint.alwaysShowStatus": true,
"eslint.enable": true
```

But I dont see the eslint icon in the status bar nor the eslint output.

![image](https://user-images.githubusercontent.com/19337229/40723379-66bc174e-6451-11e8-94da-bc7d741c095e.png)

![image](https://user-images.githubusercontent.com/19337229/40723387-6bfb63ae-6451-11e8-9130-bbe310bfda63.png)

It was working fine before and just now it isn't working any more.

I also have eslint installed locally instead. But before I had eslint installed globally and it was just working fine.

I also tried reinstalling the extension, didn't help either.

**Comment by dbaeumer** [comment]
Looks really strange. One thing: the ESlint extension only contributes a status bar icon / output channel if you have opened a JS file. Looks like your current file is a JavaScript React file. Have you configured ESLint extension to validate those ?

**Comment by iamdevlinph** [comment]
My ESLint rules are just default. And the weird thing is that it has been working before and there was no changes on my repo or any of my configuration. It just didn't work out of the blue.

I will try to replicate the issue on another machine.

**Comment by iamdevlinph** [comment]
This will be the [repo](https://github.com/codesandcoffees/react-kit) I will be testing out.

And 2 machines:
1. Home
2. Office

This issue was opened on the home machine.

**Comment by iamdevlinph** [comment]
**Home Machine**. ESLint not working

1. **No ESLint** in the output window
2. **No ESLint** text on the status bar
3. **No error was reported** when I removed the semi colon of the same file

![image](https://user-images.githubusercontent.com/19337229/40791096-35bc5d6a-6529-11e8-804f-4632401142ec.png)

**Comment by iamdevlinph** [comment]
I also tried disabling all other extensions and only run ESLint but still no luck

![image](https://user-images.githubusercontent.com/19337229/40873530-46c28bf4-6694-11e8-9a04-61dab02640b5.png)

@dbaeumer any other way that I can try to debug this? My last resort is to reinstall vscode but I'd rather not reach that point.

**Comment by iamdevlinph** [comment]
I also found these in the **Log (Extension Host)**
![image](https://user-images.githubusercontent.com/19337229/40873570-44eb8e74-6695-11e8-8be1-e62cc009c2e4.png)

**Comment by iamdevlinph** [comment]
Reinstalled vscode without deleting the extensions. ESLint still doesn't run

**Comment by iamdevlinph** [comment]
It works now.

Completely removed everything and reinstalled. But kinda annoying to go through setting up again just to fix eslint
