### ISSUE TITLE
Feature Request: Use .gitignore as .eslintignore

### ISSUE THREAD

**Issue by magnusriga** [Microsoft/vscode-eslint#480]
In eslint via command line, we can use .gitignore as .eslintignore:

`eslint --ignore-path .gitignore`

It would be awesome if we could somehow set this extension to do the same.

**Comment by dbaeumer** [comment]
This is possible. The extension has a setting options that should support that. 

```
	"eslint.options": {
		"ignore-path": ".gitignore"
	}
```

Does that work for you?

**Comment by magnusriga** [comment]
@dbaeumer I added that to User Settings in Visual Studio Code, but it did not work unfortunately. Tried restarting as well, but no luck.

**Comment by magnusriga** [comment]
@dbaeumer I fixed it by adding the following code to User Settings:

`"eslint.options": { "ignorePath": ".gitignore" }`

As seen [here](https://eslint.org/docs/developer-guide/nodejs-api#cliengine) the right property key was `ignorePath`, not `ignore-path`.

Thanks for the help!

**Comment by dbaeumer** [comment]
@magnusriga sorry for not providing the right key.
