### ISSUE TITLE
Add support for FileSystemProvider

### ISSUE THREAD

**Issue by ryansully** [microsoft/vscode-eslint#481]
I started using an extension that leverages FileSystemProvider to access remote files over SFTP, and noticed that linting doesn't work for any remote files.

I was wondering if support for remote files needs to be added to the ESLint extension or to the extension using FileSystemProvider, or perhaps to VS Code itself?

**Comment by dbaeumer** [comment]
This is currently not possible and will not be easy to achieve. Major reason for this is that the ESLint npm module we use is rely on a local file system (for example it looks for .eslintrc, package.json, .eslintignore) files which in our case are not locally available.

I will keep the item around however addressing it would either require work in VS Code or in dependent npm modules.
