### ISSUE TITLE
Feature request: Suppress warning CodeAction

### ISSUE THREAD

**Issue by Aliaksei-Martinkevich** [Microsoft/vscode-eslint#483]
Proposal: Add CodeActions to suppress warning/error. I think about following options:

- Disable current warning in this file - adds comment at the top of the file `/** eslint-disable ${rule} */`
- Disable current entry of the warning - adds comment `// eslint-disable-line ${rule}` or `// eslint-disable-next-line ${rule}` (probably option in config)
- Disable all entries of the warning in the file - add comment to each warning of such type

Working with eslint you have to disable warnings from time to time. The most annoying part is copying eslint rule name. This feature should help to do it faster and without selecting text from popup.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode-eslint/issues/245
