### ISSUE TITLE
NOT ignoring node_modules by default

### ISSUE THREAD

**Issue by felipevignon** [Microsoft/vscode-eslint#486]
Issue Type: <b>Bug</b>

Recently eslint started linting files inside my node_modules folder, which docs say it shouldn't do by default.
This started happening recently, possibly after some extension or VScode update

Extension version: 1.4.12
VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:37:01.579Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (0.19GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by dbaeumer** [comment]
I don't know about anything that has changed here. What happens if you run ESLint on a file in the node_modules in the terminal?

**Comment by felipevignon** [comment]
this stopped happening (out of nowhere like it did when it started). if it happens again I'll investigate further and repost
