### ISSUE TITLE
ESLint error on import statement

### ISSUE THREAD

**Issue by jaeseok-park** [Microsoft/vscode-eslint#489]
Hi.
I'm using vscode-eslint plugin on my React project.

When I add a new import statement, vscode-eslint displays the below error messages.
![import-error2](https://user-images.githubusercontent.com/8565274/41716017-1630452a-7590-11e8-97c2-a52f335e084b.PNG)
I cannot find the exact English error message, but they mean,
1. 'import ... =' can be used in only .ts file.
2. '=' is required.

And the source file is as below:
![import-error1](https://user-images.githubusercontent.com/8565274/41716094-5348d5d0-7590-11e8-9526-e9abbcf7520d.PNG)
Of course, this source codes can be built and works well.
How can I solve this issue?

P.S. When I restart VSCode, this error messages are cleaned.

**Comment by ravshansbox** [comment]
Can you provide your `.eslintrc*` file?

**Comment by jaeseok-park** [comment]
Thank you for your reply.
I thought that it was caused by vscode-eslint at that time.
But, now, I think it is caused by VSCode.
