### ISSUE TITLE
plugin not working with symlinked js files

### ISSUE THREAD

**Issue by kdong007** [Microsoft/vscode-eslint#492]
I have a directory outside of my project directory and it is symlinked into the project.

When I do 'eslint .' it checks all linked sources. But in VSC there it won't work. Only the non-symlinked files gets checked

**Comment by kdong007** [comment]
looks like when linting external files. it tries to use global eslint instead of current project's eslint. is there some way to enforce use local eslint?

**Comment by dbaeumer** [comment]
This works for me using a simple file link under Windows. See screen shot. Can you provide me with a GitHub repository to clone and instructions which OS you are using.

![capture](https://user-images.githubusercontent.com/1931590/42384588-b6cdd168-813a-11e8-9731-4d3b8ac06a00.png)
