### ISSUE TITLE
Create new ESLint configuration uses wrong workspace folder

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-eslint#493]
- I have two workspace folders, one of them has ESlint installed
- Use the `Create new ESLint configuration` command
- it runs `eslint --init` in the terminal, but the terminal happens to point be in the wrong workspace folder

-> should prompt, or even detect which workspace folder has eslint

**Comment by dbaeumer** [comment]
@aeschli I tried to reproduce this and wasn't able to do so. The command is executed in the correct workspace folder for me in a local setup.

**Comment by dbaeumer** [comment]
@aeschli ping.

**Comment by dbaeumer** [comment]
Closing. Please ping if you can still reproduce.
