### ISSUE TITLE
Do not open output window every time a project/file opened without eslint installed/configured locally/globally.

### ISSUE THREAD

**Issue by ravshansbox** [microsoft/vscode-eslint#495]
Do not open output window every time a project/file opened without eslint installed/configured locally/globally. That's very annoying.

**Comment by dbaeumer** [comment]
This should only happen once per workspace. The second time the Output windows should not come to front. If you see a different behaviour can you please provide steps on how to reproduce.

Or are you asking for a switch to always suppress the Output.

**Comment by ravshansbox** [comment]
Yes, you are right, it shows once for project, it would be nice if we can suppress this behavior globally somehow.

**Comment by dbaeumer** [comment]
Would be a good candidate for a PR.

**Comment by raiskila** [comment]
This seems like a good idea. Personally I don't have eslint globally installed at all, causing vscode-eslint to nag about this every time I open a new JS project that doesn't have eslint locally set up.

**Comment by dbaeumer** [comment]
I will still accept a PR if someone wants to work on it.
