### ISSUE TITLE
Contribute ´Fix all autofixable problems´ as code action of type source

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-eslint#497]
Code Actions can now be shown in the Source menu opened from the ContextMenu>Source..., see the screen shot below.

To make a code action appear in the source menu it needs to be contributed with the type: `CodeActionKind.Source`.

In vscode-tslint the fix all action is contributed both as a QuickFix and a Source action kind so that the action appears in both the quick fix menu (as it did before) and the Source menu.

![image](https://user-images.githubusercontent.com/172399/42181993-1fb61a1a-7e3d-11e8-95fc-bea43e1cfb17.png)

**Comment by dbaeumer** [comment]
I tried to add this but it is more complicated than adding an additional CodeAction to the result. 

See https://github.com/Microsoft/vscode/issues/53525 for the discussion.

**Comment by dbaeumer** [comment]
Got addressed a long time ago :-)
