### ISSUE TITLE
How to use linting in visual studio code?

### ISSUE THREAD

**Issue by abhilashsajeev** [Microsoft/vscode-eslint#5]
How should I enable this in visual studio code. I did'nt see any shortcuts.

**Comment by egamma** [comment]
https://code.visualstudio.com/Docs/languages/javascript#_javascript-linters-eslint-jshint

**Comment by abhilashsajeev** [comment]
Yes sorry for that but for eslint the plugin support does not seem to work. I 've tried with esline-plugin-react.

**Comment by ksmithbaylor** [comment]
:+1: on the plugin support. Is there any way to tell vscode-eslint where my plugin lives? It's installed under node_modules from my package.json. This is also with eslint-plugin-react.

**Comment by egamma** [comment]
If I understand you correctly you want to use a particular eslint plugin (eslint-plugin-react), but this doesn't seem to work or you haven't found a way to configure the vscode-eslint extension to use this plugin?

**Comment by abhilashsajeev** [comment]
It shows the plugin not found message. But my plugin is installed in npm

**Comment by dbaeumer** [comment]
Duplicates #2
