### ISSUE TITLE
`eslint` stop work on vscode 1.24.1

### ISSUE THREAD

**Issue by githoniel** [Microsoft/vscode-eslint#500]
log is below, check after save is no use now

restart vscode or computer is no use, only reinstall vscode and restart my computer works. But after restart my computer again, it broken again......

```
// log {eslint}
[Info  - 10:27:49] ESLint server is running.
// log{extension host}
[2018-07-06 10:28:01.837] [exthost3] [error] [onWillSaveTextDocument] dbaeumer.vscode-eslint
[2018-07-06 10:28:01.837] [exthost3] [error] Error: timeout
	at Timeout._onTimeout (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:682:762)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by dbaeumer** [comment]
Does this happen on every workspace you try to use eslint on. Does this also happen when you disabled auto fix on save.

To better understand what is happening can you enable tracing and attach the output here. To enable tracing use the following setting:

```
"eslint.trace.server": "verbose"
```

**Comment by dbaeumer** [comment]
The log looks pretty normal to me and the server is running and returning response as expected.

If you can reproduce this can you provide me with a GitHub repository I can clone that demos this?

**Comment by githoniel** [comment]
sorry my project is private and huge, so it's had to provide.
It occurs in all my project, node、electron and web. I think it is not relate to specified project.
reinstall the `eslint` plugin when occur will make it work.
still had this problem in vscode 1.25.1

**Comment by dbaeumer** [comment]
Does it fail right from the beginning or stop after some time. In the example above does `git/pos-communicate/src/stateSwitch/client/serial/client.js` have eslint errors?
