### ISSUE TITLE
Add link to the online help of the rule

### ISSUE THREAD

**Issue by markusr** [Microsoft/vscode-eslint#504]
It would be good to have a direct web-link to the eslint online help (within the tooltext).

It can always be to ```https://eslint.org/docs/rules/{RuleName}```

#### Example

![grafik](https://user-images.githubusercontent.com/1866703/42560769-c02bd078-84f7-11e8-91c8-694180c9519c.png)
----

[eslint] 'next' is defined but never used. [(no-unused-vars)](https://eslint.org/docs/rules/no-unused-vars)

**Comment by dburles** [comment]
Just came here to look for or create this issue!

**Comment by beforan** [comment]
I believe this is blocked by Microsoft/vscode#11847 but once that is done, it should be pretty easy to implement in here?

**Comment by dbaeumer** [comment]
@thibaudcolas correct. Thanks!

Closing as dup #151
