### ISSUE TITLE
Render `meta.docs.url` as a hyperlink in error message

### ISSUE THREAD

**Issue by alex-saunders** [Microsoft/vscode-eslint#505]
Hi,

Sorry if this has been asked before, I've been struggling to find an answer. 

Does `vscode-eslint` currently support displaying the `meta.docs.url` (or any sort or URL) in error message outputs? I'd like to point users to more information in my error messages but the `meta.docs.url` doesn't seem to be included in the output and if I manually type in a URL, it comes out as plain text, rather than a hyperlink.

I think Atom Linter has support for this, so I'm wondering whether `vscode-eslint` implements such functionality?

**Comment by dbaeumer** [comment]
@alex-saunders you are talking about errors you are producing. Are you adding this to the error message. Can you give me an example how you include the `meta.docs.url`

**Comment by alex-saunders** [comment]
@dbaeumer I spoke with people in the eslint gitter and managed to resolve this, so closing the issue.

**Comment by dbaeumer** [comment]
Cool. May I ask what the resolution is?
