### ISSUE TITLE
There no whole directory scanning even "eslint.provideLintTask" = true.

### ISSUE THREAD

**Issue by evgygor** [Microsoft/vscode-eslint#506]

**Comment by evgygor** [comment]
Works well for opened js files, but doesn't scan the whole directory
My config:

eslintrc.json
```
{
  "extends": "airbnb-base"
}
```

vscode settings.json

```
{
  "eslint.enable": true,
  "eslint.packageManager": "yarn",
  "eslint.options": {
    "configFile": ".eslintrc.json"
  }
}

```

**Comment by dbaeumer** [comment]
If you set `"eslint.provideLintTask": true` there is a task in the Task > Run Task that lints the whole folder.

![capture](https://user-images.githubusercontent.com/1931590/42664694-e4702156-85f0-11e8-81df-3346506cff5b.png)

I am closing the issue. Please ping if you think there is something to do on the ESLint side.

**Comment by evgygor** [comment]
I mean not a manual task running, I'm talking about a process when eslint always scans whole project directory, signs the issues in the files and list them in the "Problems" view.

**Comment by dbaeumer** [comment]
Then it is a dup of: https://github.com/Microsoft/vscode-eslint/issues/91 Help is welcome.
