### ISSUE TITLE
Provide diagnostics information in quick fixes

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-eslint#509]
A light bulb will be shown in Problems view if there are quick fixes available for a problem. 

![image](https://user-images.githubusercontent.com/10746682/42762255-1ed868ae-8910-11e8-8228-71af43d203a6.png)

For performance reasons, quick fixes check is done by

- Getting the quick fixes for the complete file
- Check if there is a quick fix for the given diagnostic

So, it is necessary that the extension should provide the diagnostics in the quick fixes. See [CodeAction.diagnostics](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2029)

Otherwise, light bulb indicator is not shown, but the quick fixes are shown in the context menu.

![image](https://user-images.githubusercontent.com/10746682/42762273-29ff8f96-8910-11e8-8c91-d087239ab8fa.png)

So, please provide diagnostics in quick fixes so that the light bulb can be shown for your diagnostics in Problems view.

https://github.com/Microsoft/vscode/issues/52627

**Comment by dbaeumer** [comment]
I started looking into this and it is basically `blocked` by https://github.com/Microsoft/vscode/issues/53525.

**Comment by dbaeumer** [comment]
To be precise: the first part is blocked. Providing the diagnostics in the code action is not. However I currently don't know the diagnostic for fixes so I would need to add this information back.
