### ISSUE TITLE
Option to not lint Untitled files

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode-eslint#510]
Please add an option to not lint Untitled files. The only extension setting I have is `"eslint.run": "onSave"`. 

When I open a new untitled file, change it to JavaScript language, and paste some code in, then this ext lints the pasted code. But it doesn't re-lint when I make changes, due to my setting. Therefore, I'd like an option to completely disable linting in Untitled files. Untitled files aren't even "saved" yet, so it doesn't really make sense to lint them on paste.

Thanks!

**Comment by dbaeumer** [comment]
Makes sense. It will be re-linted when run is `onType`. 

PR welcome.
