### ISSUE TITLE
eslint command line works, eslint vscode extension warns for named arguments

### ISSUE THREAD

**Issue by mikemaccana** [Microsoft/vscode-eslint#511]
eslint vscode warns that named arguments are not defined:

![image](https://user-images.githubusercontent.com/172594/43584600-b7cb5cc2-965a-11e8-986d-4f055270aa8c.png)

But on the shell, eslint is fine:

![image](https://user-images.githubusercontent.com/172594/43584613-c4ee977a-965a-11e8-990d-39b0697e9dd9.png)

I have explicitly copied the config into vscode to try and fix this behavior:

    "eslint.options": {
        "env": {
            "browser": true,
            "commonjs": true,
            "node": true,
            "mocha": true,
            // yes, despite parserOptions.ecmaVersion we still need this otherwise Promise is flagged.
            "es6": true
        },
        "extends": "eslint:recommended",
        "parserOptions": {
            "ecmaVersion": 2018
        },
        "globals": {
            "mixpanel": true,
            "serverVars": true,
            "avkind": true,
            "kind": true,
            "Stripe": true,
            // Last two are from DigiCert site seal
            "__dcid": true,
            "__Cascade": true
        },
        "plugins": [
            "must-use-await"
        ],
        "rules": {
            "indent": [
                "error",
                "tab",
                {"SwitchCase": 1}
            ],
            "must-use-await/must-use-await": 1, // 1 warn, 2 error
            "linebreak-style": "off",
            "quotes": "off",
            "no-console": "off",
            "semi": "off",
            "no-unused-vars": "off",
            "no-debugger": "off"
        }
    }

How can I get vscode-eslint not to flag named arguments? Thanks!

**Comment by dbaeumer** [comment]
@mikemaccana can you please provide me with a GitHub repository I can clone that demos this. Then I can have a look and see why the extension behaves differently than the eslint running in the terminal.
