### ISSUE TITLE
How to disable eslint from linting <style> parts of VueJS?

### ISSUE THREAD

**Issue by marbuser** [Microsoft/vscode-eslint#512]
I'm not sure if I'm posting this in the right place, but I'm using eslint + prettier and I want them to ignore the `<style>` tags in a vuejs components so that I can use Stylelint instead for those parts.

As you can see below, stylelint itself works fine. However, upon correcting this I get an eslint warning.

![image](https://user-images.githubusercontent.com/34422459/43634136-ea7ffc3e-973d-11e8-9baa-811bb93a173c.png)

![image](https://user-images.githubusercontent.com/34422459/43634181-01c4fc78-973e-11e8-9612-85645c5b3225.png)

My ESLint Config:
```
module.exports = {
  root: true,
  env: {
    node: true
  },
  'extends': [
    'plugin:vue/strongly-recommended',
    '@vue/airbnb',
    '@vue/prettier'
  ],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'vue/require-default-prop': "off",
    'no-shadow': "off",
    'no-param-reassign': "off"
  },
  parserOptions: {
    parser: 'babel-eslint'
  }
}
```

**Comment by dbaeumer** [comment]
@marbuser The eslint extension used the ESLint npm module to do the actual validation. So if the feature is available in ESLint itself (https://eslint.org/) then it is available in the extension as well. If not, please file a feature request against ESLint.
