### ISSUE TITLE
Global plugins aren't loaded in projects created with create-react-app

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode-eslint#514]
I have an ESLint global config file, located at `/Users/gary/.eslintrc.json`, with some plugins installed globally.

I create a new project with `npx create-react-app test-react-app`. I open it in Code. I get the following error:

```
[Info  - 21:28:44] ESLint server is running.
[Info  - 21:28:46] ESLint library loaded from: /Users/gary/Projects/cra-test/node_modules/eslint/lib/api.js
[Error - 21:28:46] 
Failed to load plugin filenames: Cannot find module 'eslint-plugin-filenames'
Happened while validating /Users/gary/Projects/cra-test/src/App.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-filenames' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-filenames' isn't installed correctly.

Consider running eslint --debug /Users/gary/Projects/cra-test/src/App.js from a terminal to obtain a trace about the configuration files used.
```

This is because CRA installs it's own copy of ESLint, yet it doesn't appear in `package.json`, so presumably it's part of one of the included scripts.

Please make this extension only use a local installation of ESLint if it explicitly appears in package.json, otherwise use the global installation, for global plugins, etc. 

I've set the following for now: `"eslint.nodePath": "/usr/local/lib/node_modules"`.

**Comment by fform** [comment]
After way to much debugging, I stumbled on this issue too. I was able to run eslint from the command line without errors but it was complaining in VSCode. 

I was also having an issue where
- eslint was installed globally
- made react native app with CRNA and ejected it
- made configuration with some plugins, installed them locally
- installed eslint locally and saved to package
- command line output was correct at this point but VSC wouldn't start using the local eslint
- setting `eslint.nodePath` to force path and it works

**Comment by pkhodaveissi** [comment]
True and thank you for `"eslint.nodePath": "/usr/local/lib/node_modules"` tip
