### ISSUE TITLE
Unmatched eslint rules show up as (null) in tooltip

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-eslint#52]
There is a bug in this plugin, which shows `null` in the error rule if no rule matches. This is a little misguiding, and also gives an impression that the plugin is not working...

Compare these images:

![Matched a rule](https://cloud.githubusercontent.com/assets/172399/13848259/4972d788-ec51-11e5-8193-a64b646b2548.png)

![Didn't match a rule](https://cloud.githubusercontent.com/assets/172399/13848320/84fc02ca-ec51-11e5-8b29-e513e63045c6.png)

**Comment by egamma** [comment]
@dbaeumer I was suspecting this is eslint behaviour ,but it is vscode-eslint. At
https://github.com/Microsoft/vscode-eslint/blob/master/eslint-server/src/server.ts#L50 it should check whether there is a ruleId, which it is in the case of a parsing error.
