### ISSUE TITLE
eslint server crashed

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode-eslint#520]
Just like in #437, I get the server crashed error. Here's an excerpt of the verbose logging information (some parts removed, let me know if they're necessary). I'm using the latest 1.4.12 version and the latest version of eslint.

```
[Trace - 10:16:21 AM] Sending request 'initialize - (0)'.

[Trace - 10:16:22 AM] Received response 'initialize - (0)' in 64ms.

[Info  - 10:16:22 AM] ESLint server is running.
[Trace - 10:16:22 AM] Sending notification 'initialized'.
Params: {}


[Trace - 10:16:22 AM] Sending notification 'textDocument/didOpen'.

[Trace - 10:16:22 AM] Received request 'client/registerCapability - (0)'.

[Trace - 10:16:22 AM] Sending response 'client/registerCapability - (0)'. Processing request took 1ms
No result returned.


[Trace - 10:16:22 AM] Received request 'client/registerCapability - (1)'.


[Trace - 10:16:22 AM] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
No result returned.


[Trace - 10:16:22 AM] Received request 'workspace/configuration - (2)'.


[Trace - 10:16:22 AM] Sending response 'workspace/configuration - (2)'. Processing request took 1ms


[Trace - 10:16:22 AM] 'npm config get prefix' value is: /home/user/npm
[Info  - 10:16:22 AM] Connection to server got closed. Server will restart.
[Info  - 10:16:22 AM] ESLint server stopped.
```

**Comment by dbaeumer** [comment]
@rightaway I assume you are running on VS Code 1.26. Do you have `eslint.nodePath` set? We are aware of an issue were the ESLint server crashes (Electron / Node problem) if the eslint.nodePath points to a non existing directory.

**Comment by rightaway** [comment]
Yes I'm on 1.26. The setting I have is `"eslint.nodePath": "~/npm/lib/node_modules"` and that directory does exist, e.g. there's `~/npm/lib/node_modules/eslint/bin/eslint.js`.

**Comment by dbaeumer** [comment]
@rightaway can you try to make the path absolute and see if that helps.

**Comment by rightaway** [comment]
That works thank you! Maybe not a bad idea to allow `~`, as that was working up until recently. Otherwise we can close this issue.

**Comment by dbaeumer** [comment]
I have a fix for this. Will publish a new version next week.

**Comment by dbaeumer** [comment]
Got delivered with 1.5.0
