### ISSUE TITLE
Linting by Resolving Functions from Multiple Files in Project

### ISSUE THREAD

**Issue by hellofolks** [Microsoft/vscode-eslint#521]
In  `index.html`:

```
<script src="scriptA.js"></script>
<script src="scriptB.js"></script>

<!-- and other scripts -->
```

In  `scriptA.js`:

```
function foo() {

}

// and many other functions
```

In  `scriptB.js`:

```
foo();
// and calling many others from scriptA
```

While editing the  `scriptB.js`  **eslint**  gives  `'foo' is not defined`  _error_. And in  `scriptA.js` it gives `never used` _error_. There should be a solution for these errors rather than specifying globals in files. Think that you have 50 global functions in `scriptA.js` and defining all of them as globals is burden. As editor has a Project feature, it can resolve functions. It is simple as if `.eslintrc` exists than it can check `.html file` with a parameter or automatically. Than it can resolve scripts and orders so `eslint` in **VS Code** can be smarter. Thanks.

**Comment by dbaeumer** [comment]
@hellofolks what happens in this case if you use eslint directly in a terminal. The ESLint extension is based on the eslint npm module and so far I stayed aways from adding features on top of the eslint npm module since it will be confusing if things behave differently whether you lint in the editor or in the terminal for example in a build script.

**Comment by hellofolks** [comment]
@dbaeumer Yes also this is an issue. html script resolving feature can be added on the VSCode side but in the future updates of the ESLint, it can give problems. It will be better to ask this feature to ESLint itself. Thanks.

**Comment by hellofolks** [comment]
@dbaeumer https://github.com/eslint/eslint/issues/10774#issuecomment-414707193 :/

**Comment by dbaeumer** [comment]
@hellofolks thanks. Any reason why you reopened this?

**Comment by hellofolks** [comment]
@dbaeumer Thanks for caring. It was for letting you know the situation at ESLint repo. Probably in the future they will lose their fixedness due to new needs. Regards.

**Comment by hellofolks** [comment]
@dbaeumer I found [this](https://www.npmjs.com/package/eslint-plugin-html) for achieving this mission. Can we implement **VSCode's** ESLint Plugin to support this feature?
Regards.

**Comment by dbaeumer** [comment]
@hellofolks this is fully support since the ESLint extension uses the ESLint npm module under the cover. So you can use any eslint plugin that works with the normal eslint.

BTW: you don't need to reopen an issue when you comment. We usually react on comments in closed issues as well.
