### ISSUE TITLE
Can't start ESLint: Cannot find module 'semver'.

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-eslint#523]
Version: 1.27.0-insider
Commit: 00649474f2e43a84c61ddbbbc356060257328372
Date: 2018-08-20T05:18:15.557Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

ES Lint 1.4.13

On activation the ESLint extension prints the error:

Activating extension 'dbaeumer.vscode-eslint' failed: Cannot find module 'semver'.

**Comment by dbaeumer** [comment]
Thanks. Fixed and published a new version.
