### ISSUE TITLE
Strange behavior for fix on save

### ISSUE THREAD

**Issue by jondot** [Microsoft/vscode-eslint#524]
Hi,
Tested on vscode and insiders, with latest eslint.

The behavior I'm observing is that it takes *two* saves of a document to get the extension to autofix properly. Running the `eslint` from the command line fixes on the first (and only) run.

I know eslint has a concept of number of iterations but going through eslint's code and vscode-eslint's code didn't bring up anything about a difference in number of iterations.

Also tried to isolate it to conflicting extensions - but it looks like something is odd with vscode-eslint.
Can't really put the actual source.

This is what's being autofixed (a simplified bogus example of the real source), using airbnb + prettier (try [this configuration](https://www.npmjs.com/package/goddamn-javascript-eslint)):

```
const funky = () => {
  let foo = 0;

  if (true) {
    return 1;
  }

  else {

    for (i = 0; i < foo; i++) {
      foo = 1
    }
    return 1;
  }
};
```

First run:

```
const funky = () => {
  let foo = 0;

  if (true) {
    return 1;
  }

  

    for (i = 0; i < foo; i++) {
      foo = 1
    }
    return 1;
  
}
```
Second, and final run

```
const funky = () => {
  let foo = 0

  if (true) {
    return 1
  }

  for (i = 0; i < foo; i++) {
    foo = 1
  }
  return 1
}

```

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode-eslint/issues/154.
