### ISSUE TITLE
autoFixOnSave does not work for test files

### ISSUE THREAD

**Issue by MartinCerny-awin** [Microsoft/vscode-eslint#525]
I am using eslint with eslint-config-prettier. Everything works correctly for normal javascript files, but auto save doesn't work for jest test (.spec.js) files.

User settings:
```
// Enable/disable default JavaScript formatter (For Prettier)
"javascript.format.enable": false,
// Disable default VSCode formatting for JavaScript
"editor.formatOnSave": false,
// Enable ESLint (with Prettier plugin) to format code on save
"eslint.autoFixOnSave": true,
```

.eslintrjc:

```
module.exports = {
  extends: [
    "plugin:prettier/recommended",
    "prettier/react"
  ]
}
```

**Comment by dbaeumer** [comment]
Can you fix them when you execute eslint directly in the terminal with the --fix option.

If yes, can you provide me with a GitHub repository I can clone that demos the behavior?

**Comment by crabicode** [comment]
@dbaeumer my bad :( it seemed the project contained `.eslintignore`. It works perfectly. @MartinCerny-awin make sure `.eslintignore` does not include `**/*.spec.js` and vscode will autoFixOnSave. Cheers!

**Comment by MartinCerny-awin** [comment]
It looks like the problem could be solved by restarting VS Code. I do not have spec files in .eslintignore

I am closing the issue for now. If I encounter the problem again I would reopen it.
