### ISSUE TITLE
TypeError: pluginName.match is not a function

### ISSUE THREAD

**Issue by JingLi-kooboo** [Microsoft/vscode-eslint#526]
I tried to manage vue with eslint, but vscode-eslint return an error.
![image](https://user-images.githubusercontent.com/20513064/44377106-fd80fb00-a52d-11e8-9eaf-72adedf1b3f0.png)
vscode-eslint version - 1.4.14
eslint version: 5.4.0

**Comment by dbaeumer** [comment]
@JingLi-kooboo this looks like a problem with ESLint itself of one of its plugins. What happens if you execute eslint directly in the terminal. Does this error show up as well?

**Comment by JingLi-kooboo** [comment]
Thank you for your reply. No problem at the terminal.
![bd5v_29p 9na oxj 61q 9](https://user-images.githubusercontent.com/20513064/44446456-80ca4b80-a617-11e8-99c1-47319302d028.png)
Should be wondering why this pluginName is undefined 
![7 l76 x59c 40 o76z 2e](https://user-images.githubusercontent.com/20513064/44446582-04843800-a618-11e8-9b85-683aa3b8e995.png)

**Comment by dbaeumer** [comment]
Actually I am a little lost since the exception is happing in ESLint code not mine. How does your configuration look like. Looks like you specify a plugin name that is not a string and therefore has no match method.

**Comment by JingLi-kooboo** [comment]
Sorry, I found the problem, which was caused by the misplacement of the configuration item.
![image](https://user-images.githubusercontent.com/20513064/44507030-9dc85280-a6db-11e8-95b3-0feb0e8b0331.png)
