### ISSUE TITLE
No quickfix and no lightbulb in vscode v1.26

### ISSUE THREAD

**Issue by macbielecki** [Microsoft/vscode-eslint#528]
After updating vscode to version 1.26 no yellow lightbulb is present when eslint reports errors and no quick fix options are visible in the editor in vue project:
With eslint extension enabled though, I see the red underline and eslint's tooltip with error message:

![image](https://user-images.githubusercontent.com/29729527/44592009-91b5c100-a7bf-11e8-8b64-088cba3bb8e0.png)

But there is no lightbulb and no options when I hit ctrl+.:

![image](https://user-images.githubusercontent.com/29729527/44592021-9d08ec80-a7bf-11e8-93e2-0d7257e4e021.png)

This is a .vue file and this feature was working fine before I updated to VSCodeUserSetup-x64-1.26.0.

**Comment by dbaeumer** [comment]
This works for me with a normal JS file (see screen shot). Can you provide me with a GitHub repository I can clone that demos this for vue.

<img width="226" alt="capture" src="https://user-images.githubusercontent.com/1931590/44645481-0a8f6580-a9d8-11e8-986c-0ce2ae43ed8b.png">

**Comment by macbielecki** [comment]
Sure. Doesn't work in a very first vue repo I found - here's a link to a fork I made:
https://github.com/macbielecki/vue-realworld-example-app

![image](https://user-images.githubusercontent.com/29729527/44647754-3f52eb00-a9df-11e8-830b-2ab21a855fe6.png)

But there's no lightbulb and when I click `ctrl+.` I see:
![image](https://user-images.githubusercontent.com/29729527/44647856-95c02980-a9df-11e8-90e1-ee9b9c9ae44a.png)
For the eslint plugin to work I have the following config:
```
"eslint.validate": [
    "javascript",
    "javascriptreact",
    "vue"
  ],
  "eslint.enable": true
```

**Comment by dbaeumer** [comment]
To get light bulbs in vue you need to tell the extension that quick fixes for vue should be computed. To do so cahneg the `"vue"` entry to:

```
{ "language": "vue", "autoFix": true }
```

I am closing the issue. Please ping if this doesn't fix it.

**Comment by macbielecki** [comment]
It works, thank you.
