### ISSUE TITLE
Add support for `pnpm`

### ISSUE THREAD

**Issue by ExE-Boss** [Microsoft/vscode-eslint#529]
[`pnpm`](https://pnpm.js.org) is the third largest node package manager, which uses symlinks, hardlinks and isolated trees, which prevents packages from using packages which they haven’t declared in their dependencies.

I believe that as it’s the third largest, it should also be supported in the `eslint.packageManager` configuration key.

## See also:
- https://www.kochan.io/nodejs/why-should-we-use-pnpm.html
- https://medium.com/pnpm/flat-node-modules-is-not-the-only-way-d2e40f7296a3

/cc @zkochan

**Comment by dbaeumer** [comment]
@ExE-Boss would you be willing to contribute this. I have no expierences with pnpm and I am sure things will again be different.

**Comment by dbaeumer** [comment]
Closing. See https://github.com/Microsoft/vscode-eslint/pull/572
