### ISSUE TITLE
Option to globally ignore dirs

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode-eslint#531]
If I open an old version of a file I have in Git, using `git show <sha>:file.js | code -`, then the file is opened in Code, and exists in `/private/var/`. This file gets linted on opening, and since it's not in the project's dir, none of my ESL rules apply. So the file usually has hundreds of error.

Please allow us to ignore folders like `/private/var` for applying ESL rules.

**Comment by dbaeumer** [comment]
This should already be possible using the `"eslint.options"` setting in user settings using either the `ignorePath` or `ignorePattern` porperty as documented here https://eslint.org/docs/developer-guide/nodejs-api

Can you give this a try?

**Comment by garyking** [comment]
I tried `ignorePattern` with dozens of variations (`private`, `/private`, `/private/var`, etc.). Only `private` would ignore the file, but that would mean that any path that includes `private` would not be linted. I actually tried these in the `eslint` CLI, so the problem seems to be from ESLint itself.

**Comment by dbaeumer** [comment]
I see the point that this feature makes sense when VS Code is opened in file mode (no folder) or files are opened that are outside the folder.
