### ISSUE TITLE
"eslint"."autoFixOnSave" ignores ECMA version

### ISSUE THREAD

**Issue by mobal** [Microsoft/vscode-eslint#534]
When I enable this feature the IDE ignores my `.eslintrc.json` configuration. I have the following:

```
{
    "env": {
        "browser": true,
        "es6": false
    },
    "extends": "google",
    "parserOptions": {
        "ecmaVersion": 5,
        "sourceType": "module"
    },
    "rules": {
        "no-var": 0
    }
}
```
Every save replaces every `var` to `let`.

**Comment by dbaeumer** [comment]
The autofix on save is based on the eslint npm modules. Does this work when running ESLint from a terminal?
