### ISSUE TITLE
Optional chaining barks an error ...

### ISSUE THREAD

**Issue by ryanpcmcquen** [Microsoft/vscode-eslint#535]
![screenshot 1536181169](https://user-images.githubusercontent.com/772937/45120760-efc59b00-b113-11e8-9e39-b26fb6c3948a.png)

I thought this may have been tied to this issue (https://github.com/babel/babel-eslint/issues/511), but it does not happen in Atom's `eslint` package (https://github.com/AtomLinter/linter-eslint).

**Comment by dbaeumer** [comment]
This error doesn't come from ESLint. It has `[ts]` in front. You can disable JS/TS checking using the TS language server in VS Code. 

I am closing the issue. If you think this is a bug in VS Code please report the issue in the vscode repository.

**Comment by ryanpcmcquen** [comment]
@dbaeumer, that sounds totally reasonable ... _but_, I have this in my user settings:

```
"typescript.validate.enable": false,
```

And if I uninstall this extension the error goes away.

**Comment by dbaeumer** [comment]
This is very wired since the error clearly has `[ts]` in its message. If it would be an eslint generated messages it would be `[eslint]`. Can you provide me with a GitHub repository I can clone that demos this?

**Comment by dbaeumer** [comment]
The @ryanpcmcquen I see the errors but they clearly come from the TS compiler. They are still there even if I disable ESLint for that workspace. Please report the problem aginst the TS support in VS Code.

**Comment by dbaeumer** [comment]
<img width="899" alt="capture" src="https://user-images.githubusercontent.com/1931590/45349809-97c6e280-b5b2-11e8-910c-d12c51d8545a.png">

**Comment by ryanpcmcquen** [comment]
Thanks @dbaeumer. Will do.
