### ISSUE TITLE
Avoid on-undef and no-unused-vars on vanillaJS project with <script src="file.js"> tags

### ISSUE THREAD

**Issue by crinitic** [Microsoft/vscode-eslint#536]
My project is based on an index.html calling various .js files declaring different classes, but it seems eslint is not able to parse across files referenced by <script src="xxx.js"> tags.

My scenario:
index.html
`
    <script src="/js/layout/header.js"></script>
    <script src="/js/layout/layout.js"></script>
`
header.js
`
    class Header {
    // I get a no-unused-vars because Header is declared but not used in header.js 
}
`

layout.js
`
    class Layout {
         constructor() {
               this.header = new Header(); // I get a no-undef error because eslint doesn't find header.js
         }
     }
`

Is there a config change I can do so that eslint parses all definitions and usages through <script src=""> on index.html ?

**Comment by dbaeumer** [comment]
The ESLint extension uses the ESLint npm module provided by the ESLint community. If this is possible when executing eslint from a shell then it should work in the extension as well. If not, it will not work in the extension and so far I stayed away from adding features on top of the normal eslint behavior.

**Comment by crinitic** [comment]
Ok thanks, I guess it is lack of knowledge on my side, or a feature request for eslint. Will check there directly :)
