### ISSUE TITLE
React Improved support for Fragment

### ISSUE THREAD

**Issue by such** [Microsoft/vscode-eslint#537]
Hello,

Is this extension supposed to support the newish React [fragment syntax](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html)?
```
<>
</>
```

My eslint version (`5.5.0`) supports it and `eslint .` yields no error when I use it but the extension somehow reports a parsing error.
```
Parsing error: Unexpected token

   5 |   render() {
   6 |     const filters = (
>  7 |       <>
     |        ^
```
I don't have eslint installed globally so I'm pretty sure the correct version is used.
I'm using the `babel-eslint` parser (v8.2.5). Removing it does not help.

**Comment by dbaeumer** [comment]
The ESLint extension using the ESLint npm module that is also used when linting in a terminal. So yes, if it works there it should work in the extension as well. Can you provide me with a GitHub repository I can clone that demos this.

**Comment by such** [comment]
Hello,
My bad, another version of eslint had sneaked in a subdirectory of my project. It works fine indeed with ESlint 5+.
Thanks.
