### ISSUE TITLE
off produces warning in .eslintrc: Incorrect type. Expected one of integer, array

### ISSUE THREAD

**Issue by ianwremmel** [Microsoft/vscode-eslint#538]
Similar to https://github.com/Microsoft/vscode-eslint/issues/72, the `off` value for a rule produces a warning, but `warn` and `error` do not:

<img width="574" alt="screen shot 2018-09-08 at 10 51 24 am" src="https://user-images.githubusercontent.com/1182361/45257084-2d653680-b355-11e8-80e0-31439bb64dcb.png">

Wrapping in quotes `"off"` doesn't help.

I looked at the schema referenced in #72 and it looks like it should work, but I'm not very familiar with how the schema works.

**Comment by ianwremmel** [comment]
Moving to the array form does make the warning go away.

```yaml
rules:
  no-console:
    - off
```

**Comment by dbaeumer** [comment]
Actually this looks like a Yaml file and I have no idea how the schema validation works for Yaml files. This is not controlled by the ESLint.

@aeschli do you know how Yaml validation comes into the VS Code system?

**Comment by aeschli** [comment]
@dbaeumer There's an [extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) that does that

**Comment by dbaeumer** [comment]
@aeschli  thanks

@ianwremmel are you using that extension ?

**Comment by ianwremmel** [comment]
yep, i am using that extension. It's hard to tell which extension is producing the validation error, but rewriting in JSON does seem to make the error go away.

**Comment by dbaeumer** [comment]
OK. I will close the issue then since there is nothing I can do to fix this in the ESlint extension.
