### ISSUE TITLE
Eslint will enter error state and needs restart vscode.

### ISSUE THREAD

**Issue by xpol** [Microsoft/vscode-eslint#539]
After I fixed the eslint error, the it will, sometimes, still have old error there, and only restart can fix this.

![screen shot 2018-09-10 at 11 54 42 am](https://user-images.githubusercontent.com/20248/45275676-91703200-b4f0-11e8-841e-21adc98b0cce.png)

*Note: in the image above, I have already fixed the `Radio` by change it to `Select`, but the old error still exists and can fix until restart vscode*

**Comment by dbaeumer** [comment]
@xpol if this happens can you enable tracing to see if the server is still responding to validation request. To enable it add the setting `"eslint.trace.server": "verbose"` and provide the Output of the ESLint output channel.

Are you able to reproduce this. I would appreciate a GitHub repository I can clone then.
