### ISSUE TITLE
not work in .vue file,but other that working other files.

### ISSUE THREAD

**Issue by CG-man** [Microsoft/vscode-eslint#540]
not work
![tim 20180910162728](https://user-images.githubusercontent.com/12809498/45285808-a5c72580-b516-11e8-81a9-99db0a6d86ed.png)

working
![tim 20180910162747](https://user-images.githubusercontent.com/12809498/45285830-b5df0500-b516-11e8-93cc-af2079b2064e.png)

![tim 20180910162738](https://user-images.githubusercontent.com/12809498/45285864-cee7b600-b516-11e8-8814-f75ced807287.png)

WTF?!?!

**Comment by dbaeumer** [comment]
Have you enable eslint checking for vue files. You need to do this using the settings described here: https://github.com/Microsoft/vscode-eslint The setting is `eslint.validate`.

Please ping if you have this setting already enabled and provide a GitHub repository I can clone that demos the problem. Thanks.
