### ISSUE TITLE
4 minute delay between ESLint server start and library loaded in Visual Studio Code

### ISSUE THREAD

**Issue by himhimlo** [Microsoft/vscode-eslint#542]
Hi,

this is very annoying and it should be grateful if there is any solution. Thank you.

Description
ESlint is only available after 3~4min after I open the Visual Studio Code. I did not see any high CPU usage during this time. Inspecting the ESlint output can see the delay is between ESlint server start and the library loaded.

Configuration:
OS: Microsoft Windows 10 Pro
ESLint Version: 3.19.0
Node Version: 8.11.1

What did you expect to happen?
I expected ESLint should run in seconds.

What actually happened? Please include the actual, raw output from ESLint.
`[Info  - 3:33:58 PM] ESLint server is running.`
`[Info  - 3:37:08 PM] ESLint library loaded from: d:\...\node_modules\eslint\lib\api.js`

**Comment by dbaeumer** [comment]
@himhimlo usually ESLint starts in seconds for me. Can you try to run the following command in a terminal and let me know how long it takes for the command to finish: `npm config get prefix`

**Comment by himhimlo** [comment]
@dbaeumer 
npm config get prefix = C:\Users\ASUS\AppData\Roaming\npm
And every time I open VS Code, the ESLint library is loaded 2-3min after the ESLint server is running
[Info  - 11:30:06 AM] ESLint server is running.
[Info  - 11:33:21 AM] ESLint library loaded from: d:\...\node_modules\eslint\lib\api.js
