### ISSUE TITLE
Eslint server crashes all the time

### ISSUE THREAD

**Issue by moimael** [Microsoft/vscode-eslint#543]
Hi,

Since a couple of week I cannot get my eslint to work in visual studio. It works perfectly fine on the command line.

I get this error everytime:

```
Info  - 4:15:35 PM] Connection to server got closed. Server will restart.
[Info  - 4:15:35 PM] ESLint server stopped.
[Info  - 4:15:35 PM] ESLint server stopped.
[Info  - 4:15:36 PM] ESLint server running in node v8.9.3
[Info  - 4:15:36 PM] ESLint server is running.
[Info  - 4:15:38 PM] ESLint library loaded from: /home/mlavault/Development/portal/node_modules/eslint/lib/api.js
/usr/share/code/code[28829]: ../../vendor/node/src/async-wrap.cc:357:void node::SetupHooks(const FunctionCallbackInfo<v8::Value> &): Assertion `env->async_hooks_init_function().IsEmpty()' failed.
 1: node::Abort() [/usr/share/code/libnode.so]
 2: 0x7f28358d0c04 [/usr/share/code/libnode.so]
 3: 0x7f28358baf45 [/usr/share/code/libnode.so]
 4: 0x7f283533487a [/usr/share/code/libnode.so]
 5: 0x7f28351ada4c [/usr/share/code/libnode.so]
 6: 0x7f28351ad144 [/usr/share/code/libnode.so]
 7: 0x18313668463d
[Error - 4:15:43 PM] Connection to server got closed. Server will not be restarted.
[Info  - 4:15:43 PM] ESLint server stopped.
```

I'm on an up to date Fedora 28 distribution.

Thanks !

**Comment by dbaeumer** [comment]
Looks like your setup doesn't like the node version VS Code ships with. You can configure using a different node runtime using the setting `eslint.runtime` and the PR here: https://github.com/Microsoft/vscode-eslint/pull/516/files

Let me know if this fixes the issue.

**Comment by moimael** [comment]
I'm not sure how to check that but this might be relevant:

```
  "extends": ["airbnb", "prettier", "prettier/react",  "plugin:testcafe/recommended"],
  "parser": "babel-eslint",
```
For the record, my colleague who is on MacOS had the exact same issue as me. Seems like the node version shipped with vscode is broken for eslint.

**Comment by dbaeumer** [comment]
It is not broken in general. It depends on what kind of plugins you install into eslint. If they have native code this code is compiled against a node version which might no match what is shipped in Electron. 

There is little the eslint extension can do to fix. If something like this happens all the user can do point to the node version that is available on the system. This is possible via `eslint.runtime`. Any objection to close the issue.

**Comment by moimael** [comment]
I agree, this can't be fixed in the extension and the `eslint.runtime` escape hatch is an acceptable solution.

Yeah you can close this, thanks !

**Comment by dbaeumer** [comment]
Thanks. Closing then.
