### ISSUE TITLE
How to distinguish undefined variate in the NodeJs environment?

### ISSUE THREAD

**Issue by osramywj** [Microsoft/vscode-eslint#544]
How to distinguish undefined variates in the NodeJs environment?
There is no difference with other variates!

![image](https://user-images.githubusercontent.com/26902133/45619288-4edbc600-baab-11e8-8616-e3e90b2a830e.png)

**Comment by dbaeumer** [comment]
@osramywj can you please provide more details about what your issue is with the ESLint extension. If you have a general question about how to configure ESLint then this is better ask on StackOverflow.
