### ISSUE TITLE
No ESLint configuration (e.g .eslintrc) found for file... -  Set eslint config in file comment instead of jsonrc file

### ISSUE THREAD

**Issue by giorgio79** [Microsoft/vscode-eslint#547]
JSHint extension settings enable us to add

`/*jshint esversion: 6 */

In the js file. Could we do the same with eslint instead of having to create a separate file?`

**Comment by dbaeumer** [comment]
Such a support must come from the ESLint npm module. The ESlint extension doesn't add any features on top of the normal ESLint. It only integrates ESLint into VS Code. Having the feature in ESLint npm will also ensure that it works correctly when executing eslint on the command line. 

Can you please file the request here: https://github.com/eslint/eslint

Please ping if I misunderstood your request.

**Comment by giorgio79** [comment]
Thx. Discussion with ESLint opened https://github.com/eslint/eslint/issues/10877

**Comment by platinumazure** [comment]
ESLint maintainer here :smile:

Hi @giorgio79, I took a look at the documentation here and it looks like there is an `eslint.options` configuration setting which takes options that go to CLIEngine.

Try adding the following option there:

```json
{
    "useEslintrc": false
}
```

That should allow you not to use a config file, and then you can just use the configuration comments (as we discussed in the ESLint issue).

I don't think anything needs to be done either on the ESLint or vscode-eslint side.

**Comment by dbaeumer** [comment]
@platinumazure thanks for clarifying this.
