### ISSUE TITLE
Fix all autofix problems could be improved

### ISSUE THREAD

**Issue by chemzqm** [Microsoft/vscode-eslint#548]
The fix for all aotufix problems now drop the overlap fixes, so it requires run multiple times to fix all fixable problems sometimes.

The `Linter` of eslint module could be used to get result of fixed code and then calculate the required `textEdit` for fix all autofix problems, instead calculate from each of the fixes. 

I've implemented it in my fork https://github.com/neoclide/coc-eslint/blob/master/src/server/util.ts

**Comment by dbaeumer** [comment]
@chemzqm any objection to mark this as a dup of https://github.com/Microsoft/vscode-eslint/issues/154
