### ISSUE TITLE
Hidden files (prefixed with a dot) are ignored

### ISSUE THREAD

**Issue by chipit24** [microsoft/vscode-eslint#550]
I noticed this when making changes to my `.eslintrc.js` file. ESLint errors will not show up in hidden files (files prefixed with a dot).

If I have a file, `test.js`, with ESLint errors, they are displayed in my editor with a squiggly underline, and in the problems tab. If I re-name the file to `.test.js`, the VS Code ESLint extension seems to ignore it completely.

**Comment by dbaeumer** [comment]
This is standard eslint behavior. If elint is executed in the terminal you get:

![capture](https://user-images.githubusercontent.com/1931590/46522409-f8c89a00-c882-11e8-9ade-c337bd0b9c62.png)

I will close the issue since the extension tries to stick with the normal ESLint behaviour.

**Comment by dbaeumer** [comment]
Reopening: we do should make sure that the warning is shown in the problem panel. But we will still not validate the file.

**Comment by leoselig** [comment]
Isn't the underlying problem that we `.eslintignore` is not honored? See https://github.com/eslint/eslint/issues/8429#issuecomment-355967308 – hidden files (leading `.`) can be opted into by negated globs.

**Comment by dbaeumer** [comment]
@leoselig the .eslintignore` is honored. If you think otherwise can you provide me with a GitHub repository I can clone that demos what you are seeing?

**Comment by leoselig** [comment]
@dbaeumer Yes, I can do. And it's good that I did because I discovered that it's specifically realted to nested or non-top-level `.eslintignore` setups.
See my repro repo (_\*pun\*_) here: https://github.com/leoselig/repro-vscode-eslint-ignorefiles

**Comment by dbaeumer** [comment]
@leoselig this is actually expected since eslint ignores them as well if you run the command from the workspace root `.\node_modules\.bin\eslint --ext=js .\packages\pkg1\`

```
ESLint: 5.9.0.
All of the files matching the glob pattern ".\packages\pkg1\" are ignored.

If you don't want to lint these files, remove the pattern ".\packages\pkg1\" from the list of arguments passed to ESLint `.

If you do want to lint these files, try the following solutions:

* Check your .eslintignore file, or the eslintIgnore property in package.json, to ensure that the files are not configured to be ignored.
* Explicitly list the files from this glob that you'd like to lint on the command-line, rather than providing a glob as an argument.
```

The reason for that is that the eslint ignore file look up is not relative to the file it is relative to the current working directory in ESLint. So you need to tell the ESLint extension in this setup what the working directories are. If you add this to the settings:

```
{
	"eslint.workingDirectories": [
		{ "directory": "packages/pkg1", "changeProcessCWD": true }
	]
}
```

The file is validated correctly

![capture](https://user-images.githubusercontent.com/1931590/51734333-81628480-2084-11e9-855a-958106e8d491.png)

**Comment by leoselig** [comment]
@dbaeumer Got it. Wow, this is messy. So for our case the conflict actually is that on CI/via our scripts we are running ESLint in each workspace package (monorepo) but in VSCode it is a single ESLint instance running on the root.
Thanks for clarifying. We'll try to figure something out.

**Comment by dbaeumer** [comment]
@leoselig simply configure the `"eslint.workingDirectories"` for each workspace package and it should work as expected.

**Comment by leoselig** [comment]
@dbaeumer I should have been more clear about what issue I still have with this. We are working in quite a large mono repository where packages tend to come (and even go) **quite** frequently. Therefore I dislike maintaining a list of `
eslint.workingDirectories` but a glob does not seem to work at the moment.

**Comment by gernotpokorny** [comment]
Why such complicated logic? Why not just respect `.eslintignore` for the current directory and sub-directories? I mean currently you cannot open a folder with many sub-folders without maintaining this list.

**Comment by nevir** [comment]
It's probably worth opening this on the eslint repo. The logic appears to be here:

https://github.com/eslint/eslint/blob/ca3b2a62c9e829dc4534bca3643d6bc729b46df0/lib/cli-engine/config-array/ignore-pattern.js#L136-L170

**Comment by dbaeumer** [comment]
Just as a pointer: the upcoming ESLint version has two improvements here:

- a auto setting to infer the working directories
- glob pattern support (e.g. `/packages/*/`). So for large mono repositories you very likely only need one entry :-)

**Comment by dbaeumer** [comment]
Since quite some time there is a setting `"eslint.onIgnoredFiles": "warn"` to enable / disable the warning in the extension.
