### ISSUE TITLE
adding support for portable mode (feature request) 

### ISSUE THREAD

**Issue by glachancecmaisonneuve** [Microsoft/vscode-eslint#551]
Would it be possible to add vscode's [EnvironmentService.getUserDataPath()](https://github.com/Microsoft/vscode/blob/0c2388a00830063966adeeff97a62b0c0e583966/src/vs/platform/environment/node/environmentService.ts#L94) in the chain of possible locations for finding a valid configuration file?  ```EnvironmentService.getUserDataPath()``` will point to the correct location for vscode user data directory, in portable mode or regular mode, according to circumstance (you can detect portable mode with the presence of process.env['VSCODE_PORTABLE']).

You would be the best judge for how high it should sit in the chain of possible locations, my personal opinion would be it should be picked up **instead** of $HOME/eslinrc, if it exists.  That would mean that while in portable mode, you don't have a home, or rather your home is inside the vscode folder.

**Comment by glachancecmaisonneuve** [comment]
Researching this further, you may want to look at EnvironmentService.appSettingsHome() instead of the base directory ```EnvironmentService.getUserDataPath()````.  That's where the snippets file, the settings file and other config files are going to reside.

**Comment by dbaeumer** [comment]
@glachancecmaisonneuve can you explain fir which files this should be considered. Are you talking about a `.eslintrc` file ? The extension itself has no logic about .eslintrc file locations. It used the ESLint npm module to find them (https://github.com/eslint/eslint). 

You can always point to a specific configuration file using the `eslint.options` setting which supports eslint command line options.

**Comment by glachancecmaisonneuve** [comment]
I'll try out eslint.options and close if it can use environment variables, wich is a possible approach to portability.  I'll come back with my findings and close if it's doable.
