### ISSUE TITLE
Late response

### ISSUE THREAD

**Issue by VenkattaPidikiti** [Microsoft/vscode-eslint#554]
- Extension Name: vscode-eslint
- Extension Version: 1.6.0
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 9801,
		"activateCallTime": 6,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by dbaeumer** [comment]
I am not able to reproduce this. I see code loading times around 100ms. In your case the extension got activated six times which results in a code loading time of 1600ms which I agree is still bad. Do you have any steps on how to reproduce this?
