### ISSUE TITLE
Disappears rule suggestion after upgrade 1.6.1

### ISSUE THREAD

**Issue by maxbax** [Microsoft/vscode-eslint#559]
After last upgrade to version 1.6.1 of your plugin in Microsoft code when appear an error disappears the suggestion code to skip. For example with airbnb linter code shows the "[eslint] Unexpected dangling '_' in '__SOME_VARIABLE__'.". Before the upgrade the linters showed me "[eslint] Unexpected dangling '_' in '__SOME_VARIABLE__'. **(no-underscore-dangle)**" very usefull to force validation online (with "// eslint-disable-line no-underscore-dangle").
Any ideas how to return to that suggestion?
Thanks

**Comment by dbaeumer** [comment]
@maxbax this is caused by a bug in VS Code and got already fixed. If you need this urgent you can use VS Code insider release.
