### ISSUE TITLE
Cannot find module 'eslint-plugin-javascript'

### ISSUE THREAD

**Issue by axy541877028** [Microsoft/vscode-eslint#563]
Vscode output：
[Info  - 4:38:33 PM] ESLint server stopped.
[Info  - 4:38:33 PM] ESLint server running in node v8.9.3
[Info  - 4:38:33 PM] ESLint server is running.
[Info  - 4:38:35 PM] ESLint library loaded from: /Users/liulu/Documents/work/printer/node_modules/_eslint@5.7.0@eslint/lib/api.js
[Error - 4:38:35 PM] 
Failed to load plugin javascript: Cannot find module 'eslint-plugin-javascript'
Happened while validating /Users/liulu/Documents/work/printer/src/view/toprinted.vue
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-javascript' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-javascript' isn't installed correctly.

Consider running eslint --debug /Users/liulu/Documents/work/printer/src/view/toprinted.vue from a terminal to obtain a trace about the configuration files used.

**Comment by dbaeumer** [comment]
@axy541877028 have you tried fixing this by trying the provided solutions? If so can you provide me with a GitHub repository that demos this?
