### ISSUE TITLE
Triggered eslint rule name is no more available in the tooltip

### ISSUE THREAD

**Issue by fedulovivan** [Microsoft/vscode-eslint#568]
- VSCode Version: 1.28.2
- OS Version: Ubuntu 16.04 LTS
- eslint: 4.6.1
- vscode-eslint extension: 1.6.1

Steps to Reproduce:

1. Write any code which has any linting problem
2. Hover problem element, see the tooltip contents.

Previously triggered rule name was available, but currently, it's not (only validation message itself):

![screenshot from 2018-10-31 10-56-45](https://user-images.githubusercontent.com/752105/47773984-cc2a6580-dcfc-11e8-980a-db39bf466cd1.png)

**Comment by dbaeumer** [comment]
This is actually caused by a bug in VS Code and is already fixed in Insider and will be available again with the next VS Code update.
