### ISSUE TITLE
Regression: Rule ID has disappeared from the popup.

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode-eslint#570]
![image](https://user-images.githubusercontent.com/1937871/47849254-439ee880-de14-11e8-998f-400e9be68258.png)

This change happens at d98bfd60fcbb1be6112bcd6b1e9a4fc9eab318f9.

It's inconvenient to me if I cannot check the rule ID in the popup.
Because we use the rule ID to disable rules with `eslint-disable` directives.
I don't want to open problems tab to check it since I have opened terminal pane always...

**Comment by dbaeumer** [comment]
This is actually a bug in VS Code. Code now renders the diagnostic code (which is the rule id) consistently in the UI but there was a bug in the Hover that prevented this. It is already fixed in Insider and will be available in next stable.

**Comment by mysticatea** [comment]
Thank you for the pointed out!
