### ISSUE TITLE
eslint-suppress-line action: please add the suppress-comment on the same line

### ISSUE THREAD

**Issue by Friksel** [microsoft/vscode-eslint#573]
When using the new 'Suppress ... for this line' action, which is a very welcome feature, we don't get the suppression on the same line as in the description, but as a `// eslint-disable-next-line`. 

I would rather like to have the suppress line as `// eslint-disable-line` after the code. I normally put these on the same line as the rule I want to suppress for better readability and less disturbing code flow, but this seems to be impossible with using actions. 

Would it be possible to make the 'Suppress .. for this line' insert the suppress-line on the same line after the code, so as `eslint-disable-line`? Being able to insert it with `eslint-disable-next-line` is conveniant in certain situations too, so maybe move the current behaviour to an additional action to add it to the next line (eslint-disable-next-line) with an action title like 'suppress for this line (as next)'?

**Comment by dbaeumer** [comment]
To not pollute the menu too much I would suggest to make this an options instead having both.

**Comment by dbaeumer** [comment]
PR for this is welcome.

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
