### ISSUE TITLE
[Solved] eslint can't not find the module "babel-eslint" when I have installed the module babel-eslint?

### ISSUE THREAD

**Issue by brucejo75** [Microsoft/vscode-eslint#574]
I found a solution to #82.  You have locked up that issue and no more comments are allowed. So I am adding a new issue with my solution to help anyone else that runs into it.

### Issue
`babel-eslint` cannot be found when loading VSCode.

1. I noticed that this only happened when I opened a certain project, it seems to work fine for my main project.
2. In the Output window I saw the line:
`[Info  - 11:02:44 AM] ESLint library loaded from: E:\u\temp\node_modules\eslint\lib\api.js`

### Repair
This was an unused `node_modules` directory.  So I deleted the unused `node_modules` directory and the ESLint found my global `node_modules` directory.

Problem solved.

**Comment by dbaeumer** [comment]
Or bot locks it :-)

Thanks for the issue and the solution. Closing the issue. Please ping if you think an action is needed.
