### ISSUE TITLE
eslint.autoFixOnSave requires multiple saves

### ISSUE THREAD

**Issue by thernstig** [Microsoft/vscode-eslint#575]
I've installed the eslint extension. The npm packages installed are eslint, prettier, eslint-config-prettier, eslint-plugin-prettier.

Prettier best practices integration with eslint tells you to use `"extends": ["plugin:prettier/recommended"]`. This will make `eslint --fix` also run the prettier formatter. If I run this on command line like so `node_modules/.bin/eslint --fix server FILE` it formats everything perfectly.

In VS code I've set:
```json
"editor.formatOnSave": true
"eslint.autoFixOnSave": true,
"javascript.format.enable": false,
```

When I then save the same `FILE` in VS Code, I have to do three consecutive saves in order for the formatting to end up in its final state, equal to as when I ran it from command line.

Why is this?

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode-eslint/issues/154 which has all the details around this :-)
