### ISSUE TITLE
Parsing error on template string

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode-eslint#58]
https://github.com/unional/tslint-config-unional/blob/master/gulpfile.js#L25
![image](https://cloud.githubusercontent.com/assets/3254987/14010122/a3caf0b4-f14f-11e5-977c-efedb8e0d1f0.png)

**Comment by egamma** [comment]
Pls update to a newer version vscode-eslint, this has been changed in the latest version:

![image](https://cloud.githubusercontent.com/assets/172399/14011199/f0d05820-f19c-11e5-92c1-4a2d6e728eff.png)

**Comment by unional** [comment]
Closed the wrong issue?
This still exists in the latest version
![image](https://cloud.githubusercontent.com/assets/3254987/14011255/5c524aa6-f15a-11e5-8ecf-85b28c53cb9a.png)

**Comment by egamma** [comment]
Sorry, yes I was in the wrong issue. 

The fact that the error message shows `(undefined)` is a duplicate of #52.

Template strings work for me when I enable ES6 in the .eslintrc

```json
{
    "env": {
        "es6": true
    },
}
```
