### ISSUE TITLE
Use 'unused code' style instead of error squiggle

### ISSUE THREAD

**Issue by jaywick** [microsoft/vscode-eslint#586]
I would like code which fail `no-unused-vars` to use the greyed out code you can see in Javascript and Typescript projects introduced in the [1.24 May 2018 update](https://code.visualstudio.com/updates/v1_24#_highlight-unused-variables-and-imports)

![image](https://user-images.githubusercontent.com/3955052/49618718-aa17b780-fa0d-11e8-9e52-89f174b396d3.png)

Right now it just shows the red error squiggle

![image](https://user-images.githubusercontent.com/3955052/49618612-64f38580-fa0d-11e8-96fe-2c0350f0de45.png)

The [theming guide](https://code.visualstudio.com/docs/getstarted/theme-color-reference) does mention the following two properties, not sure how helpful this is.

* `editorUnnecessaryCode.border`: Border of unnecessary (unused) source code in the editor.
* `editorUnnecessaryCode.opacity`: Opacity of unnecessary (unused) source code in the editor.

**Comment by ajkovar** [comment]
I might be interested in contributing here but am a bit confused.  It seems like it does gray out unused items?

![image](https://user-images.githubusercontent.com/144447/85762838-c0fa2980-b6d9-11ea-8f61-f732a8769055.png)

However, it is also showing the error squiggle.  Would it be sufficient to just not show the error squiggle in this case (possibly under a configuration setting)?

**Comment by dbaeumer** [comment]
@ajkovar  Are you sure these are ESLint errors?

**Comment by ajkovar** [comment]
Good question... it seems there is an error being reported both by ts and eslint.  Not sure which is triggering the squiggle. 
 Maybe both.

<img width="561" alt="Captura de Pantalla 2020-06-26 a la(s) 10 00 09 a  m" src="https://user-images.githubusercontent.com/144447/85871454-0c710e00-b794-11ea-8782-4af2ebd85283.png">

**Comment by dbaeumer** [comment]
The grayed out code comes thorugh the TS error which is reported at the same location as the ESLint error.

**Comment by dbaeumer** [comment]
I no set the diagnostic tag `DiagnosticTag.Unnecessary` for `no-unused-vars` rules. However the rendering of this still depends on VS Code strategy.
