### ISSUE TITLE
Getting "ESLint server shut down itself" message. Linting not working

### ISSUE THREAD

**Issue by sunpietro** [Microsoft/vscode-eslint#589]
Hi,
after the latest update of VS Code, ESLint seems to be not working.
![zrzut ekranu 2018-12-14 o 14 03 08](https://user-images.githubusercontent.com/1736658/50004971-0435f100-ffa9-11e8-8a55-1f9749d0d9c8.jpg)
I'm not sure how can I restart it and make it working again.

**Comment by dbaeumer** [comment]
@sunpietro Which version of ESLint extension are you on?

**Comment by dbaeumer** [comment]
THis works for me using VS Code 1.30 and ESLint 1.7.2
