### ISSUE TITLE
Prefix lint error with [eslint] and the violating rule

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode-eslint#59]
![image](https://cloud.githubusercontent.com/assets/3254987/14010122/a3caf0b4-f14f-11e5-977c-efedb8e0d1f0.png)

Should be at least `[eslint] Parse Error ...`

**Comment by unional** [comment]
This should be close and reopen #58 instead.

**Comment by egamma** [comment]
@unional thanks for cleaning up

**Comment by unional** [comment]
You are welcome. But #58 should be reopened?

**Comment by dbaeumer** [comment]
@unional both issues are fixed with 0.10.13 which I pushed yesterday.

**Comment by unional** [comment]
Thanks!
