### ISSUE TITLE
Panel shows automatically on startup

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-eslint#591]
I noticed that the output panel was opening right on startup opening a JS project I had checked out showing me this:

![image](https://user-images.githubusercontent.com/900690/50083570-8b2ad980-01f4-11e9-9a6e-afdebd9dbd2b.png)

I suggest to use a notification instead that is easier for the user to deal with. A panel is not easy to dismiss, takes a lot of vertical space and destroys my current workbench layout.

**Comment by bpasero** [comment]
Filed https://github.com/Microsoft/vscode-tslint/issues/415 for the related issue in TSLint. 

/cc @egamma

**Comment by dbaeumer** [comment]
![capture](https://user-images.githubusercontent.com/1931590/50103630-5769a700-0228-11e9-9ab9-612e6c92cc11.png)

**Comment by bpasero** [comment]
Thanks!
