### ISSUE TITLE
vscode-eslint work wrong

### ISSUE THREAD

**Issue by shunjinchan** [Microsoft/vscode-eslint#594]
- OS Version: macOS Mojave
- VSCode Version: 1.30.1
- vscode-eslint: 1.7.0

The config of `.eslintrc.json`

```json
{
  "env": {
    "browser": true,
    "commonjs": false,
    "es6": false,
    "jquery": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "ecmaVersion": 5
  }
}
```

code

```javascript
const name = 'test'
const say = () => console.log('say')
const $ele = $('ele')
```

vscode-eslint error log, it can not detect the es6 syntax error.

![image](https://user-images.githubusercontent.com/4383818/50418316-b3a27b80-0865-11e9-9df0-e7e0e3bd2f0a.png)

use `node_modules/.bin/eslint ` check the same file, it can detect and report `Parsing error` cause by `const`.

![image](https://user-images.githubusercontent.com/4383818/50418012-49d5a200-0864-11e9-937a-5951ccc98035.png)

**Comment by shunjinchan** [comment]
I found the cause of this problem.

VSCode User Settings:

```json
"eslint.options": {
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  },
}
```

If I delete the ESLint config in User Settings, it work right.

I guess for vscode-eslint this priority of ESLint config in User Settings is higher than in .eslintrc.json.

**Comment by dbaeumer** [comment]
Closing the issue then since the `eslint.options` act as command line paramters for eslint. It is like passing them to `node_modules/.bin/eslint`.
