### ISSUE TITLE
Unable to resolve path to module in vscode

### ISSUE THREAD

**Issue by hannahjin** [microsoft/vscode-eslint#595]
My eslint passes when running from terminal and in ci. However, in vscode, all absolute paths inside the project cannot be resolved. 

`import formats from 'formatting'`

ex. Error:
```
Unable to resolve path to module 'formatting'
module "/Users/hannah/project-folder/subfolder_app/src/formatting/index"
```

```
.eslintrc (inside subfolder_app)
...
  "env": {
    "browser": false
  },
  "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true
    },
    "import/resolver": {
      "node": {
        "paths": ["./src", "./src/style"],
        "extensions": [".js", ".jsx"]
      }
    },
    "import/core-modules": ["redux-saga/effects"]
  },
...
```

**Comment by Calvin-Huang** [comment]
@dbaeumer 
I tried to add `eslint.workDirectionaries` and it still unable to resolve the path

![Imgur](https://i.imgur.com/iD0YF9u.png)

However, when we use the subfolder as a workspace it is fine.

![Imgur](https://i.imgur.com/6ZTbA2G.png)

**Comment by dbaeumer** [comment]
How does the configuration look like ?

**Comment by hannahjin** [comment]
I can't provide you a repo since they are private. But basically the folder structure looks like
```
projectRoot/
   app1/
       .eslintrc
```
I tried adding `workingDirectories": ["./app1"]` and`workingDirectories": ["./projectRoot/app1"]`. Neither resolved the module paths.

**Comment by Calvin-Huang** [comment]
@dbaeumer 

Here is my workspace configuration. Please take a look. ↓
```
{
  "eslint.workingDirectories": [
    "./app",
    "./worker",
    "./crawler"
  ]
}
```

**Comment by Calvin-Huang** [comment]
@dbaeumer 
Thanks! `changeProcessCWD` works perfectly.  I checked README again and confirmed what you mentioned are documented. Sorry about didn't take notice of that part.
