### ISSUE TITLE
auto quick fix made double comma to fix trailing comma

### ISSUE THREAD

**Issue by LOGANLEEE** [Microsoft/vscode-eslint#598]
when i use quick fix.
it made double comma to fix which mean is causing another error..

<img width="630" alt="screen shot 2019-01-11 at 16 58 19" src="https://user-images.githubusercontent.com/26853553/51020510-1a43cb00-15c2-11e9-9083-41e7b626f21e.png">

```
{
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Default High Contrast",
    "prettier.jsxSingleQuote": true,
    "prettier.singleQuote": true,
    "vtools.autoHideDelay": 0,
    "vtools.autoHideSideBar": true,
    "editor.snippetSuggestions": "none",
    "vtools.autoHideBottomBar": true,
    "javascript.preferences.quoteStyle": "single"
}
```

![comma](https://user-images.githubusercontent.com/26853553/51020598-5d05a300-15c2-11e9-8dec-819960651572.gif)

**Comment by dbaeumer** [comment]
Can you provide me with a GitHub repository I can clone to reproduce this? It works in my simple example.

**Comment by LOGANLEEE** [comment]
> Can you provide me with a GitHub repository I can clone to reproduce this? It works in my simple example.

i would like to give you but it's company project which mean is not allowed to share .
But i can provide conf or setting files which you want me to provide.
what kinda info you need?

**Comment by LOGANLEEE** [comment]
```
import React from 'react';
import ReactTable from 'react-table';
import PropTypes from 'prop-types';
import 'react-table/react-table.css';

import Wrapper from './Wrapper';
import dummyData from './dummyData';

const Table = props => {
  console.log();

  const columns = [
    {
      Header: 'Name',
      accesssor: 'name',,
    },
    {
      Header: 'Age',
      accesssor: 'age',,
    },
    {
      id: 'frindName',
      Header: 'Friend Name',
      accesssor: d => d.friend.name,,
    },
    {
      Header: props => <span>Friend Age</span>, // Custom header components!
      accessor: 'friend.age',,
    },,
  ];

  return (
    <Wrapper>
      <ReactTable data={dummyData} />
    </Wrapper>
  );
};

export default Table;
```

i Think this bug is not related with code..
<img width="450" alt="screen shot 2019-01-14 at 18 39 18" src="https://user-images.githubusercontent.com/26853553/51105203-b58ba900-182b-11e9-902f-01f5d3cee609.png">

**Comment by dbaeumer** [comment]
@LOGANLEEE I am not trying to say it is how you code. To reproduce this on my end I need to have:

- vscode workspace setting
- the package.json file to know which ESLint and plugings you are using
- eslint config files
- a JS file showing it.

The easiest way to provide this is via a GitHub repository. This also ensures that the problem can really be reproduced. Would you be able to provide this information?
