### ISSUE TITLE
Support yarn --pnp

### ISSUE THREAD

**Issue by Ayc0** [microsoft/vscode-eslint#601]
With their new versions, yarn has now a option called ["Plug'n'Play"](https://gist.github.com/arcanis/02b49752c385908479734d8027d7a6c7) (there isn't any official doc yet) which removes the `node_modules/` folder

Do you have plan to support this new feature?

**Comment by dbaeumer** [comment]
I don't have a lot of knowledge about `yarn --pnp` but the ESLint extension only calls yarn to find globally installed packages. I would assume that yarn itself handles this correctly in cases `yarn --pnp` was used.

Installing node modules (even eslint using yarn) is awlays done by the user itself. 

I will keep the issue open in case there is something todo.

**Comment by tunnckoCore** [comment]
Yup. Something should be done.

**Comment by dbaeumer** [comment]
@tunnckoCore can you be a little bit more specific. I still think there is nothing the ESLint extension needs to do.

**Comment by tunnckoCore** [comment]
Maybe. I don't know. Yea, maybe more correct would be eslint to support it.

**Comment by Mykybo** [comment]
This a problem with this extension and has nothing to do with eslint itself. Yarn PnP does not create /node_modules, but your extension tries to load it from there instead of asking yarn to resolve it.

**Comment by dbaeumer** [comment]
I do ask yarn for the node modules path and then use `require.resolve()` to load it. There is no hardcoded knowledge of a `node_modules` folder in this extension. 

Can anyone provided me with hints how that should work with yarn --pnp. To the documentation here it should work out of the box for require.resolve. https://yarnpkg.com/en/docs/pnp/getting-started

**Comment by dbaeumer** [comment]
Setup to reproduce: https://github.com/Microsoft/vscode-eslint/issues/653#issuecomment-481629947

**Comment by jgierer12** [comment]
Seems like this has to be resolved upstream in [microsoft/vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node/), since that is where `Files.resolve` comes from. I opened an issue there: microsoft/vscode-languageserver-node#496

**Comment by dbaeumer** [comment]
See my comment here: https://github.com/microsoft/vscode-languageserver-node/issues/496#issuecomment-500744820

**Comment by Teoxoy** [comment]
This issue can be closed.
It has been resolved at yarnpkg/berry#312

**Comment by dbaeumer** [comment]
@Teoxoy cool to hear. I do have a question: how were you able to solve this in yarn without any changes to ESLint?

**Comment by Teoxoy** [comment]
@vlasenko implemented it.

Yarn v2 has an optional package called `@berry/pnpify` which wraps typescript and now eslint. Installing `pnpify` and then adding this vscode setting `"eslint.nodePath": "scripts/tssdk"` makes eslint work in a pnp environment.

**Comment by dbaeumer** [comment]
Very cool. Thanks for the clarification.

**Comment by TheHolyWaffle** [comment]
Some more info can be found here https://next.yarnpkg.com/advanced/pnpify#vscode-support
