### ISSUE TITLE
eslint parserOption.project path issue

### ISSUE THREAD

**Issue by peterjuras** [Microsoft/vscode-eslint#605]
I encountered an issue while using this extension with the new [@typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) parser and plugin. When opening Visual Studio Code with a parent folder of a project, eslint will no longer work because the `tsconfig.json` file will be looked up relative to the workspace root rather than the directory which contains the `.eslintrc` file.

To reproduce:
1. Clone this sample repository: [typescript-eslint-workspace-issue](https://github.com/peterjuras/typescript-eslint-workspaces-issue)
2. `cd a && yarn install`
3. Open the root folder (not a) in Visual Studio code

-> When inspecting `a/src/index.ts` the eslint plugin will complain that it can not find `tsconfig.json` in the root folder, but running `yarn --cwd a lint` script works as expected. When the `parserOptions.project` path is adjusted to `a/tsconfig.json` the extension works correctly, but the script will no longer work.

Is this an issue of this plugin or rather the @typescript-eslint/parser?

**Comment by dbaeumer** [comment]
This is an issue with @typescript-eslint/parser since the extension itself doesn't look up any config files. It relies on the ESLint npm module which relies on @typescript-eslint/parser

**Comment by dbaeumer** [comment]
Please report the issue with @typescript-eslint/parser

**Comment by andrew-humu** [comment]
For anyone else that finds this issue, the relevant ticket in the [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) project is:

https://github.com/typescript-eslint/typescript-eslint/issues/251
