### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by doublepithre** [microsoft/vscode-eslint#606]
[dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-eslint/files/2801421/dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-eslint`
- Extension Version: `1.8.0`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.2`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by dbaeumer** [comment]
@doublepithre do you have any steps to reproduce this. The profile doesn't provide a lot of insights since it doesn't seem to hit any reasonable ESLint extension code.

**Comment by doublepithre** [comment]
@dbaeumer I'm not sure how to reproduce this. This happened when I tried to open a workspace which has four projects, a text popped up at the bottom asking to report an issue with an auto-filled body.
