### ISSUE TITLE
Add an option to report only the start of an error in the code

### ISSUE THREAD

**Issue by LambdaFalcon** [Microsoft/vscode-eslint#607]
Since ESLint decided to report large error ranges, this tool is completely unusable because multiple errors in a function that e.g. has no return statement will all be covered by the reporting of the "outer" error of the function.

I'm not asking to change the behaviour, but to add an option to visualize just the start of the error.
This should be added because this tool handles visualization of errors reported by ESLint, which is not concerned with visualization.

See my last comment on !463 here:
https://github.com/Microsoft/vscode-eslint/pull/463#issuecomment-453588949

**Comment by dbaeumer** [comment]
I am marking this as a dup of #370.

I am not a fan of this since the extension currently doesn't temper with any results return from ESLint. The only way the extension can do something about this is to store a different range of a diagnostic then reported by ESLint. This will lead to discrepancy between ranges seen in the problems view and ranges seen in the terminal. In addition ESlint tasks that scan the output of the terminal will not honor the shorting either hence resulting in flickering of error ranges in the editor.

**Comment by LambdaFalcon** [comment]
I would say it is not a dup since the other issue is asking about marking the line, whereas in my case I was thinking of marking just the first token.  

Can't the extension keep the complete ranges, but then offer the possibility of showing a red underling just at the beginning of the range?

E.g. the range is `[9:28]`, but just a red underline is shown at position `9`.

**Comment by dbaeumer** [comment]
Left a comment in https://github.com/Microsoft/vscode-eslint/issues/607.

> Can't the extension keep the complete ranges, but then offer the possibility of showing a red underling just at the beginning of the range?

For that the extension needs to report the error on `[9:0]` and not as `[9:28]` which I exactly what I am not a fan of.

**Comment by LambdaFalcon** [comment]
Sorry for asking, but why are you not a fan of this?
It could be an optional setting for how errors should be reported graphically.
It would help the people who are seeing entire files underlined in red

**Comment by dbaeumer** [comment]
> I am not a fan of this since the extension currently doesn't temper with any results return from ESLint

Up to now the ESLint extension uses the eslint npm module and simply transforms the results returned from the npm modules into VS Code data types. This has the advantage that if you run eslint on the console or a task the same error ranges are reported. If we start tempering with the range in one then they will not be the same anymore and you might see flickering or double ranges if the errors from the ESLint extension are combined with errors from tasks.
