### ISSUE TITLE
Can't find modules of .ts extension

### ISSUE THREAD

**Issue by komali2** [Microsoft/vscode-eslint#608]
I have a project with some .ts files. 

Given:

```
src/store.ts
src/hello.vue
src/component.vue

```

And the file **hello.vue**:

```
import component from '@/component';
import store from '@/store';
```

I get the in-line error (red underline and tooltip)  `Cannot find module '@/store'.`

This error only occurs for .ts files, not .vue or .js. 

How can I have eslint recognize these imports are working? (The imports work, as confirmed by vue-cli serving them properly, build working etc.

**Comment by dbaeumer** [comment]
@komali2 does this work for you when using eslint from the command line. If not, then this is a general ESLint problem. If it does work from the command line, can you please create a GitHub repository that helps me reproduce what you are seeing.
