### ISSUE TITLE
About for loop

### ISSUE THREAD

**Issue by mysmlz** [Microsoft/vscode-eslint#610]
Issue Type: <b>Bug</b>

This template contains "let" and "const",and for ie,none of this has been achieved,so,Can you replace these with var?
[let - Browser compatibility - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Browser_compatibility)

[const - Browser compatibility - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const#Browser_compatibility)

Extension version: 1.8.0
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (1.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mysmlz** [comment]
![tim 20190201153938](https://user-images.githubusercontent.com/38951157/52109780-96698580-2639-11e9-88a9-c3a69de22792.png)

**Comment by dbaeumer** [comment]
@mysmlz ESLint doesn't provide any code complete or snippet information. Please report the issue against VS Code itself.
