### ISSUE TITLE
alwaysShowStatus: false - not working, ⚠ eslint always shows in status bar

### ISSUE THREAD

**Issue by Yzrsah** [Microsoft/vscode-eslint#612]
The `"eslint.alwaysShowStatus": false,` setting is not working.

Even when set to false, `⚠ eslint` always shows in the status bar at all times for all file types.

**Comment by dbaeumer** [comment]
This works for me: 

![capture](https://user-images.githubusercontent.com/1931590/53004565-bc609980-3431-11e9-86f7-98f8872d9a44.png)

Can you provide me with a GitHub repository I can clone that demos what you see.

**Comment by Yzrsah** [comment]
hi Dirk,

I am getting this error in console log,
it may be related to the reason why the ESLint indicator stays open:

```
console.ts:134 [Extension Host] Error: command failed with error code 2: error parsing glob '**/.eslintrc*, **/package.json': invalid use of **; must be one path component

    at Object.t.deserializeSearchError (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3815:49)
    at Promise.all.then.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4472:372)
    at process._tickCallback (internal/process/next_tick.js:68:7) (at S.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:685:893))
```

**Comment by Yzrsah** [comment]
@dbaeumer I realized the indicator is staying open when I don't have `${workspaceRoot}/package.json`

I have a multi-root workspace, with nested packages, local_modules

**Comment by dbaeumer** [comment]
Looks indeed suspicious. Can you please provide me with a GitHub repository I can clone which demos this. I don't see that exception in my test cases.

**Comment by Yzrsah** [comment]
It's a large workspace with many nested projects and packages with different eslint scopes, nested inheritance level of plugins being resolved implicitly, a bunch of eslint/lib/api.js's detected

The issue was resolved in part by making an eslintrc at the root level that is compatible with everything. Also by making explicit some plugin scoping.

Without that eslintrc in the root, I get the glob errors. I do not know the meaning of the glob error. But the cause of the error was:
*"Having a bunch of nested projects with different eslint setups, but not having a root level eslintrc that resolves all issues"*

**Comment by Yzrsah** [comment]
It's a large workspace with many nested projects and packages with different eslint scopes, nested scope levels of eslint plugins being resolved implicitly, a bunch of eslint/lib/api.js's detected

The issue was resolved in part by making an eslintrc at the root level that is compatible with everything. Also by making explicit some plugin scoping.

Without that eslintrc in the root, I get the glob errors. I do not know the meaning of the glob error. But the cause of the error was:
*"Having a bunch of nested projects with different eslint setups, but not having a root level eslintrc that resolves all issues"*
