### ISSUE TITLE
Failed to load the ESLint library for the document... (Windows 10, WSL)

### ISSUE THREAD

**Issue by jsejcksn** [Microsoft/vscode-eslint#614]
This works fine for me in macOS. I'm having this issue in Windows:

``` log
[Info  - 8:46:29 PM] ESLint server stopped.
[Info  - 8:46:30 PM] ESLint server running in node v8.9.3
[Info  - 8:46:30 PM] ESLint server is running.
[Info  - 8:46:30 PM] Failed to load the ESLint library for the document Untitled-1
To use ESLint for single JavaScript file install eslint globally using 'npm install -g eslint'.
If you are using yarn or pnpm instead of npm set the setting `eslint.packageManager` to either `yarn` or `pnpm`
You need to reopen VS Code after installing eslint.
```

#### Setup WSL and environment
1. Enable WSL
2. Install an Ubuntu version from the Windows Store  
   _👇 in Ubuntu_
3. Go through setup; Install Node.js and npm LTS
4. Modify npm `prefix` to use path owned by me and not `root`
5. Install `eslint` globally (`npm -g i eslint`)
6. Add `.eslintrc` file to `~/`  
   _👇 back in Windows_
7. Install VS Code Stable
8. Open VS Code  
   _👇 in VS Code_
#### Setup VS Code
9. Install ESLint extension (`dbaeumer.vscode-eslint`)
10. View > Command Palette... > `Terminal: Select Default Shell` > `WSL Bash`
#### Final steps
11. Close VS Code; Open VS Code (via Windows taskbar shortcut / start menu)
12. File > New File
13. View > Command Palette... > `Change Language Mode` > `JavaScript`
14. View > Output
15. Select ESLint in output provider list
16. Output: _See log at beginning of this post_
17. View > Terminal
18. Execute the following commands:

`node -v && npm -v`

``` shell
v10.15.0
6.4.1
```

`npm -g prefix`

``` shell
/home/jesse/.npm-global
```

`npm -g ls --depth 0`

``` shell
/home/jesse/.npm-global/lib
└── eslint@5.13.0
```

`which eslint`

``` shell
/home/jesse/.npm-global/bin/eslint
```

`eslint -v`

``` shell
v5.13.0
```

**Do I need to do something else?**

**Comment by dbaeumer** [comment]
This is currently not working since the ESLint server is started on the Windows side. The issue needs to be addressed by VS Code itself and there is a corresponding item on the VS Code roadmap (see https://github.com/Microsoft/vscode/wiki/Roadmap , WSL support).

As soon as VS Code has support for it I will start adopting in ESLint.

**Comment by jsejcksn** [comment]
> the ESLint server is started on the Windows side
1. Can you elaborate this? I don't understand what you mean.

2. So there's nothing wrong, in theory, with the procedure I listed, and it's just an issue with VS Code [not really supporting WSL yet](https://github.com/Microsoft/vscode/wiki/Roadmap#wsl-support)?

3. What are the steps to get it working until WSL is adequately supported?

**Comment by dbaeumer** [comment]
The ESLint extension runs the eslint npm module on the Windows and not on the WSL side. This is why this is failing. 

There is nothing wrong in theory but it needs better support in VS Code itself to make this scenario happening.

**Comment by snooopcatt** [comment]
ironic, given that Idea works better with WSL than MS product

**Comment by dbaeumer** [comment]
https://code.visualstudio.com/docs/remote/wsl will fix this. I am closing this issue.

**Comment by jsejcksn** [comment]
@dbaeumer So I will need to install another extension before being able to use ESLint in Windows? I'm confused.

Will you please elaborate here what steps will be needed (starting from a fresh Windows 10 installataion) to get ESLint working in VS Code through WSL?

**Comment by dbaeumer** [comment]
@jsejcksn A good documentation on how to use this is here: https://code.visualstudio.com/docs/remote/wsl#_getting-started

The benefit of this approach is that not only the ESLint runs in WSL but also language support and debugging. So it is a more holistic solution then only running ESLint in WSL.

Please note that the general WSL support in VS Code is currently only available in Insider. But it will come to stable.
