### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mtupper** [Microsoft/vscode-eslint#615]
[dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-eslint/files/2843544/dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-eslint`
- Extension Version: `1.8.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `
[dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt]
(https://github.com/Microsoft/vscode-eslint/files/2843545/dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by dbaeumer** [comment]
Trace looks very comparable to the one from #620. Marking as dup.
