### ISSUE TITLE
ESLint server shut down itself

### ISSUE THREAD

**Issue by gonxas** [Microsoft/vscode-eslint#618]
I started getting this error today out of the blue. 

"ESLint server shut down itself. See 'ESLint' output channel for details."

attached is my config: (Haven't touched it since I installed the extention... I actually just found where it was)

[eslintrc.txt](https://github.com/Microsoft/vscode-eslint/files/2846152/eslintrc.txt)

Any ideas what may be causing this?

**Comment by dbaeumer** [comment]
One of the plugins calls process.exit() which make the ESLint process exit. If you can provide me with the repository that shows the behavior I can look which plugin causes this.

**Comment by qzdFront** [comment]
I also encountered the same problem, according to my test, every time I use import to select the path will cause Eslint sever shut down.
plugin list : https://gist.github.com/qzdFront/9bfa512e331bf1e31494f10a1a567dc1

**Comment by dbaeumer** [comment]
@qzdFront can you provide me with a GitHub repository I can clone that repros what you are seeing.

**Comment by gonxas** [comment]
Sorry, can't give you the repo, since it's private. This is the output the console is trhowing:
`[Info  - 11:29:27 AM] ESLint server stopped.
[Info  - 11:29:27 AM] ESLint server running in node v10.2.0
[Info  - 11:29:27 AM] ESLint server is running.
[Info  - 11:29:28 AM] ESLint library loaded from: /Users/gonxas/Projects/iOS/DigitalClipboard/DC/node_modules/eslint/lib/api.js
cosmiconfig requires at least version 4 of Node, please upgrade
[Error - 11:29:29 AM] Server process exited with code undefined. This usually indicates a misconfigured ESLint setup.
[Error - 11:29:30 AM] Connection to server got closed. Server will not be restarted.
[Info  - 11:29:30 AM] ESLint server stopped.`

Attached my configuration file

versions: 
`pc33:DC gonxas$ node -v
v9.11.1
pc33:DC gonxas$ npm -v
5.6.0
[eslintrc.zip](https://github.com/Microsoft/vscode-eslint/files/2909811/eslintrc.zip)

`

**Comment by dbaeumer** [comment]
@gonxas thanks. Unfortunatelly the eslintrc file doesn't provide enough information to understand what is happening. 

Can you run eslint from a terminal and see if there is any additional information written to the console?

**Comment by gonxas** [comment]
Hey @dbaeumer. Sorry for the delay, I've been on vacations.
Can you tell me how to run eslint from a terminal please? I've been only using it on Visual Studio Code

Thanks

**Comment by dbaeumer** [comment]
@gonxas with ESLint both the npm eslint package and all plugins must either be install all globally or all locally. You can't mix the installation scope.

**Comment by gonxas** [comment]
@dbaeumer shouldn't those lines have installed everything globaly?

**Comment by gonxas** [comment]
@dbaeumer I just saw a found log of messages on Visual Studio Code:

> [Info  - 10:35:36 AM] ESLint server stopped.
> [Info  - 10:35:36 AM] ESLint server running in node v10.2.0
> [Info  - 10:35:36 AM] ESLint server is running.
> [Info  - 10:35:39 AM] ESLint library loaded from: /Users/gonxas/Projects/iOS/DigitalClipboard/DC/node_modules/eslint/lib/api.js
> cosmiconfig requires at least version 4 of Node, please upgrade
> [Error - 10:35:42 AM] Server process exited with code undefined. This usually indicates a misconfigured ESLint setup.
> [Error - 10:35:43 AM] Connection to server got closed. Server will not be restarted.
> [Info  - 10:35:43 AM] ESLint server stopped.

does this gives a bit more of information?

**Comment by dbaeumer** [comment]
`npm i -g eslint` installs eslint globally, whereas `npm i eslint-plugin-prettier@latest --save-dev` installs the plugin locally.

The server shuts down because of this

```
/Users/gonxas/Projects/iOS/DigitalClipboard/DC/node_modules/eslint/lib/api.js
cosmiconfig requires at least version 4 of Node, please upgrade
```

Do you have eslint.runtime configured ?

**Comment by gonxas** [comment]
I'm not sure... Searching I found and follow this: https://github.com/runtimejs/eslint-config-runtime

I added edited this line in the config file I uploaded earlier:
  "extends": ["eslint:recommended", "plugin:react/recommended", "runtime"],

but nothing happened.

**Comment by gonxas** [comment]
hey @dbaeumer any ideas what may be happening here?

**Comment by dbaeumer** [comment]
No, since I can't reproduce this (at least not exactly what you are seeing). What happens if you execute eslint directly from the terminal?
