### ISSUE TITLE
Warn about doubled configured validate rules

### ISSUE THREAD

**Issue by pengxiaotian** [microsoft/vscode-eslint#623]
我今天更新了eslint 1.18.0 和 vscode  版本: 1.31.0 (user setup)
然后我发现自动修复功能在 .vue 文件中不生效,只是提示错误, 在 .js 文件中一切正常

**Comment by 282159468** [comment]
same issure in jsx file

**Comment by BigsonLvrocha** [comment]
In my case, with eslint 1.18.0 and vscode 1.31.1 it's not even working for .js files

**Comment by dbaeumer** [comment]
@pengxiaotian can you please provide a description in English?

**Comment by dbaeumer** [comment]
Did you enable auto fix in Vue files as described [here](https://github.com/Microsoft/vscode-eslint) for `eslint.validate`

**Comment by dbaeumer** [comment]
See also https://github.com/Microsoft/vscode-eslint/issues/185#issuecomment-307842751

**Comment by pengxiaotian** [comment]
@dbaeumer okay,I will consider using English in the future.
today, I asked my colleague to install my project on his computer. The same problem.
here are some of my configurations:

.eslintrc.js file configuration
```javascript
// https://eslint.org/docs/user-guide/configuring

module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint'
  },
  env: {
    browser: true,
  },
  extends: [
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/essential', 
    // https://github.com/standard/standard/blob/master/docs/RULES-en.md
    'standard'
  ],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  // add your custom rules here
  rules: {
    // allow async-await
    'generator-star-spacing': 'off',
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
  }
}
```
Workspace configuration
```javascript
{
    "editor.tabSize": 2,
    "files.associations": {
        "*.vue": "vue"
    },
    "eslint.autoFixOnSave": true,
    "eslint.options": {
        "extensions": [
            ".js",
            ".vue"
        ]
    },
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "html",
        "vue",
        {
            "language": "vue",
            "autoFix": true
        },
        {
            "language": "html",
            "autoFix": true
        }
    ],
    "css.validate": false,
    "scss.validate": false,
    "stylelint.autoFix": true
}
```
Partial dependence

```javascript
{
devDependencies: {
    "eslint": "^4.19.1",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-import-resolver-node": "^0.3.2",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "stylelint": "^9.10.1",
    "stylelint-config-standard": "^18.2.0",
    "stylelint-order": "^2.0.0",
    "stylelint-webpack-plugin": "^0.10.5"
},
 "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  }
}
```
VSCode
version: 1.31.1 (user setup)
提交: 1b8e8302e405050205e69b59abb3559592bb9e60
日期: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by dbaeumer** [comment]
Do you have an extension instsalled that adds the VUE file type (e.g. https://marketplace.visualstudio.com/items?itemName=octref.vetur) ?

To make sure we are looking at the same problem could your provide me with a GitHub repository I can clone that demos what you see.

**Comment by pengxiaotian** [comment]
I have already installed

![image](https://user-images.githubusercontent.com/27847994/53001385-6a396b80-3465-11e9-8140-5d90388e867d.png)

**Comment by dbaeumer** [comment]
That looks OK. Can you provide me with a GitHub repository I can clone that demos what you see.

**Comment by pengxiaotian** [comment]
Please understand that the source code is not uploaded to github for work reasons. However, I have a personal experimental project here, which is the same problem.
https://gitee.com/rapex/VCharts-UI.git

**Comment by pengxiaotian** [comment]
If the address cannot be accessed, this is the compressed package of the code.
[VCharts-UI.zip](https://github.com/Microsoft/vscode-eslint/files/2879242/VCharts-UI.zip)

**Comment by pengxiaotian** [comment]
I don't think this has anything to do with the code.........
All my projects have the same problem

**Comment by dbaeumer** [comment]
Can you let me know what you expect to see working and it doesn't with a simple example. I tested it locally and for me eslint validating in Vue files does work.

**Comment by dbaeumer** [comment]
![capture](https://user-images.githubusercontent.com/1931590/53006776-2bd88800-3436-11e9-879a-42b410fd9d88.png)

**Comment by pengxiaotian** [comment]
Now only the error is indicated. When I save, the three semicolons should be automatically fixed and deleted.
![image](https://user-images.githubusercontent.com/27847994/53007036-6a3f6880-3471-11e9-8a65-b52adeac02c3.png)

**Comment by dbaeumer** [comment]
This actually doesn't look like an error produced by eslint. All errors produced by the eslint extension have a eslint(code) prefix. Something like:

![capture](https://user-images.githubusercontent.com/1931590/53007366-62fb6900-3437-11e9-811d-7cff46b943f9.png)

**Comment by dbaeumer** [comment]
Actually I see this when adding extract semicolons when produced by eslint:

![capture](https://user-images.githubusercontent.com/1931590/53007550-c2f20f80-3437-11e9-8a05-5b7075cba7f2.png)

**Comment by dbaeumer** [comment]
What happens if you run eslint on the command line on that file using the `--fix` option

**Comment by pengxiaotian** [comment]
It stands to reason that eslint should be fixed automatically when I save it, but it doesn't actually.
type Ctrl + S
![image](https://user-images.githubusercontent.com/27847994/53007870-1766b080-3473-11e9-83ae-a31d3fdcce94.png)
![image](https://user-images.githubusercontent.com/27847994/53007938-3a916000-3473-11e9-955d-5f2b2b7cbba0.png)

**Comment by pengxiaotian** [comment]
These operations are normal in the .js file.

**Comment by pengxiaotian** [comment]
Problem with the `--fix` option was successfully fixed

![image](https://user-images.githubusercontent.com/27847994/53160123-3fd0e500-3602-11e9-8e0f-3f58ef62a322.png)

**Comment by dbaeumer** [comment]
Since I can't reproduce this can you please create a simple project on GitHub that I can clone that demos this. I agree that this is very likely not specific to your code. It is very likely more caused by a setup problem.

**Comment by pengxiaotian** [comment]
It seems that I have the same error again today. I ignored it last time：

    Failed to load the ESLint library for the document f:\Qlw-VCharts-UI\src\components\Index.vue

    To use ESLint please install eslint by running npm install eslint in the workspace folder Qlw-VCharts-UI
    or globally using 'npm install -g eslint'. You need to reopen the workspace after installing eslint.

    If you are using yarn or pnpm instead of npm set the setting `eslint.packageManager` to either `yarn` or `pnpm`
    Alternatively you can disable ESLint for the workspace folder Qlw-VCharts-UI by executing the 'Disable         ESLint' command.

**Comment by pengxiaotian** [comment]
I know what went wrong, it is the reason for the configuration.
But I don't know what the specific reason is.
> correct configuration
![image](https://user-images.githubusercontent.com/27847994/53696477-3dd90400-3e02-11e9-8ea3-23204ca39171.png)

> wrong configuration
![image](https://user-images.githubusercontent.com/27847994/53696494-5c3eff80-3e02-11e9-8033-3e9b43d44490.png)

Is this order important?

**Comment by dbaeumer** [comment]
The problem is that `"vue"` is listed two times one as a string and one as a literal. Simply the second one wins

**Comment by pengxiaotian** [comment]
I think this is an invisible rule and should be annotated. 
I see that many people are configured this way.

**Comment by Joker0824** [comment]
I find the issue when the .vue file is to big(when the code is more than 1000 lines)
