### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by briosam** [Microsoft/vscode-eslint#624]
- Issue Type: `Performance`
- Extension Name: `vscode-eslint`
- Extension Version: `1.8.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/briosam/dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by dbaeumer** [comment]
Dups #620
