### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Yusadolat** [Microsoft/vscode-eslint#627]
- Issue Type: `Performance`
- Extension Name: `vscode-eslint`
- Extension Version: `1.8.0`
- OS Version: `Linux x64 4.18.0-15-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/yusadolat/dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by dbaeumer** [comment]
@Yusadolat do you still have the cpuprofile?

Dups #620
