### ISSUE TITLE
need update 'problems' message in config file "globals" property

### ISSUE THREAD

**Issue by xianghongai** [Microsoft/vscode-eslint#629]
For historical reasons, the boolean value `false` and the string value `"readable"` are equivalent to `"readonly"`. Similarly, the boolean value `true` and the string value `"writeable"` are equivalent to `"writable"`. However, the use of older values is deprecated.

- [Specifying Globals - ESLint](https://eslint.org/docs/user-guide/configuring#specifying-globals)

![2019-02-22-143343](https://user-images.githubusercontent.com/2075006/53224312-46696600-36af-11e9-8f8a-bd4ade76fae7.png)

**Comment by dbaeumer** [comment]
@xianghongai this is handle by the eslintrc schema file which is maintained here: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/eslintrc.json

Please file the issue there. Thanks.

**Comment by jordanbtucker** [comment]
See https://github.com/SchemaStore/schemastore/pull/645 and https://github.com/SchemaStore/schemastore/pull/651
