### ISSUE TITLE
In NativeScript in app folder there is addtional `package.json` that misleads eslint

### ISSUE THREAD

**Issue by lafriks** [Microsoft/vscode-eslint#632]
In NativeScript apps there is `app/package.json`  file with contents 
```
{
  "main": "app.js",
  "android": {
    "v8Flags": "--expose_gc"
  }
}
```

In project root folder there is also `package.json` that contains all dependencies. There currently seems to be no way to look for dependencies in workspace root package.json instead on app folders one.

**Comment by dbaeumer** [comment]
@lafriks can you provide me with a GitHub repository and steps that show what exactly the issue is you are having?

**Comment by lafriks** [comment]
I just created sample: https://github.com/lafriks/test-nativescript-vue

You could probably need nativescript first.
```
npm install -g nativescript
npm install
```

When running:
```
npm run lint
```

Result is:
![image](https://user-images.githubusercontent.com/165205/53436987-23b7b400-3a05-11e9-838a-a0b7adfc5719.png)

But vscode-eslint shows linting errors for dependencies:
![image](https://user-images.githubusercontent.com/165205/53437073-5a8dca00-3a05-11e9-8c04-061e4b9bad92.png)

**Comment by dbaeumer** [comment]
Actually `npm run lint` doesn't call eslint directly and I have no idea what `vue-cli-service lint` does. However running eslint directly in a terminal produces the same error:

<img width="886" alt="capture" src="https://user-images.githubusercontent.com/1931590/53497153-db9b9e80-3aa3-11e9-8960-73710be13132.png">

So unless someone knows how to setup ESLint (https://eslint.org/) I am a little lost here.

**Comment by lafriks** [comment]
As a workaround I currently have set `.eslintrc.js` for anyone getting this error this way:

```js
module.exports = {
  root: true,

  env: {
    node: true,
  },

  extends: ['plugin:vue/recommended', '@vue/airbnb'],

  rules: {
    'no-console': 'off',
    'no-debugger': 'off',
    'import/no-extraneous-dependencies': ['error', {'packageDir': './'}],
    'import/extensions': 'off',
    'import/no-unresolved': 'off',
  },

  parserOptions: {
    parser: 'babel-eslint',
  },
};
```

**Comment by dbaeumer** [comment]
@lafriks any objection to close this issue. I don't see what ESLint extension can do to make this a better expierence.

**Comment by lafriks** [comment]
Yes sure, I believe this could be actually eslint issue
