### ISSUE TITLE
eslint is not using local config

### ISSUE THREAD

**Issue by bugs181** [Microsoft/vscode-eslint#636]
I have eslint installed globally and locally. However, the vscode plugin is not respecting the local configuration files. When running from terminal, everything works as expected however I want to use VSCode's version that provides gutter colors and other visual indicators.

Directory structure:
```
 |-node_modules
 |-shrinkwrap.yaml
 |-rollup.config.js
 |-package-lock.json
 |-package.json
 |-lib
 | |-index.js // File to lint
 |-build
 |-.eslintrc.json
```

Running eslint from terminal:
```
eslint --debug lib/index.js

eslint:cli CLI args: [ '--debug', 'lib/index.js' ] +0ms
eslint:cli Running on files +6ms
eslint:glob-utils Creating list of files to process. +0ms
...
eslint:cli-engine Processing /Users/levi/.../lib/index.js +0ms
eslint:cli-engine Linting /Users/levi/.../lib/index.js +1ms
eslint:config Constructing config file hierarchy for /Users/levi/.../lib +0ms
eslint:config Using .eslintrc and package.json files +0ms
eslint:config Loading/Users/levi/.../myProject/.eslintrc.json +2ms
eslint:config-file Loading JSON config file: /Users/levi/.../myProject/.eslintrc.json +0ms
...
eslint:linter Linting code for /Users/levi/.../myProject/lib/index.js (pass 1) +0ms
eslint:linter Generating fixed text for /Users/levi/.../myProject/lib/index.js (pass 1) +91ms
eslint:source-code-fixer Applying fixes +0ms
eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms
eslint:cli-engine Linting complete in: 567ms +554ms

/Users/levi/.../myProject/lib/index.js
  20:7  warning  Unexpected console statement  no-console

✖ 1 problem (0 errors, 1 warning)
```

Global linter used: (local `.eslintrc.json` has `"prefer-template": ["off"],"`
![eslint](https://user-images.githubusercontent.com/3699516/53526102-f9b7cd80-3aa8-11e9-87fb-a5f2e5203351.png)

**Comment by dbaeumer** [comment]
@bugs181 can you provide me with a GitHub repository that I can clone that demos this behaviour.

**Comment by bugs181** [comment]
> @bugs181 can you provide me with a GitHub repository that I can clone that demos this behaviour.

Here you go. I'm curious if this could perhaps be a bug with `pnpm` not correctly installing the local eslint version. Not really sure.

https://github.com/bugs181/vscode-eslint-bug-636

**Comment by dbaeumer** [comment]
Works for me out of the box:

<img width="859" alt="capture" src="https://user-images.githubusercontent.com/1931590/53728425-0b1b2400-3e73-11e9-86a9-00f9c10b9a52.png">

One thing you can try is to set the package manage for eslint to pnpm using `"eslint.packageManager": "pnpm"`

**Comment by bugs181** [comment]
Oddly enough, I'm getting completely different behavior with no modifications to the uploaded project. Now eslint is complaining about plugins, however my local eslint does not have any plugins listed.

```
[Error - 11:25:13 AM] 
Failed to load plugin async-await: Cannot find module 'eslint-plugin-async-await'
Happened while validating /Users/levi/.../vscode-eslint-bug-636/lib/index.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-async-await' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-async-await' isn't installed correctly.

Consider running eslint --debug /Users/levi/.../vscode-eslint-bug-636/lib/index.js from a terminal to obtain a trace about the configuration files used.
```

Running the above command from CLI seems to use the correct configuration. Not sure what could be happening at this stage.

```
  eslint:config Using /Users/Levi/.../vscode-eslint-bug-636/.eslintrc.json +206ms
```

Added that line to `package.json`; with the same result. How should I proceed?

**Comment by bugs181** [comment]
Update: after reading through #482, it appears I too have misunderstood the use of `configFile` option. 

I had assumed it acted as a fallback mechanism, only being used if a local `.eslintrc` file didn't exist. After removing that line from my User settings in VSCode, everything behaves as expected. 

Since this is very much a vscode-eslint specific feature (leaving CLI alone), I'd like to add my support for asking you to consider a fallback config option. I too use VSCode in varying degrees with files scattered all through-out my computer. This makes using `.eslintrc` config files problematic. Furthermore, consider what happens when you simply want to add/change a rule. Those changes will have to be propagated to all of the config files, potentially scattered through dozens of directories.

**Comment by dbaeumer** [comment]
@bugs181 I am not sure I understand what you are asking for. The `configFile` is exactly the same as the `--config` option for the command line. This is standard ESLint behaviour. 

Have you looked intpo `baseConfig` (see https://eslint.org/docs/developer-guide/nodejs-api#cliengine). I think that helps in your setup.

**Comment by bugs181** [comment]
Aha! The not so subtle difference between `configFile` and `baseConfig` options.

According to those docs:
> configFile - The configuration file to use (default: null). If useEslintrc is true or not specified, this configuration will be merged with any configuration defined in .eslintrc.* files, with options in this configuration having precedence. Corresponds to -c.

The interesting bit is: 
> with options in this configuration having precedence

Whereas for `baseConfig`:
>  with the .eslintrc.* files having precedence.

My earlier stated problem was that the `configFile` is completely over-riding my local `.eslintrc` rules, so it sounds appropriate to switch to `baseConfig`

Unfortunately, it appears that `baseConfig` has no effect. 
I would assume this is a `vscode-eslint` issue since I've specifically changed my `settings.json` to:
```
// ESlint configuration
"eslint.enable": true,
"eslint.options": {
    //"configFile": "/Users/levi/Documents/vscode-settings/.eslintrc.json"
    "baseConfig": "/Users/levi/Documents/vscode-settings/.eslintrc.json"
},
```

**Comment by dbaeumer** [comment]
To my understanding `baseConfig` is an object literal and not a path to a file.
