### ISSUE TITLE
Suppress warnings only

### ISSUE THREAD

**Issue by ilias-t** [Microsoft/vscode-eslint#637]
### Type of Issue
Feature Request

### Description
Looking for an option that will disable warnings in VSCode, while still displaying errors. Something akin to eslint's quiet [flag](https://eslint.org/docs/user-guide/command-line-interface#handling-warnings).

**Comment by dbaeumer** [comment]
@ilias-t just to clarify. Only for ESlint?

**Comment by ilias-t** [comment]
Yes, an ability to specifically quiet eslint warnings is what I had in mind.

**Comment by silvenon** [comment]
I want this so much. 👍 I'm working on a project with lots of ESLint warnings, so all those orange underlines are incredibly distracting. It would significantly improve my productivity if this can be turned off. 😄

**Comment by silvenon** [comment]
Maybe the option could be `"eslint.quiet": true`?

**Comment by dbaeumer** [comment]
`"eslint.quite"` as a setting name makes sense.  PR welcome :-)

**Comment by dpinol** [comment]
That would be great. I tried https://github.com/aladdin-add/eslint-plugin-no-autofix but I couldn't make it work. 
An alternative to eslint.quiet could be adding an option to specify extra arguments to the eslint command (eg. eslint.flags="--quiet")

**Comment by ilias-t** [comment]
Just up a PR to address this—any feedback welcome & feel free to assign the issue to me 🙏
