### ISSUE TITLE
Feature Request: autocomplete for eslint comment

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode-eslint#641]
![2019-03-06 09 53 18](https://user-images.githubusercontent.com/9758711/53850303-b3f18c80-3ff5-11e9-9d01-7a559c24e629.png)
![2019-03-06 09 53 49](https://user-images.githubusercontent.com/9758711/53850327-c370d580-3ff5-11e9-901d-c9cf1286006e.png)

I am writing an extension that automatically completes these comments.

But I hope that this is implemented by the official extension.

### Why do I need this feature?

Because I can't remember the comment of ``eslint`` every time.

**Comment by dbaeumer** [comment]
Nice idea. Are you willing to provide a pull request ?

**Comment by axetroy** [comment]
@dbaeumer
In fact, I have implemented some functions in here https://github.com/axetroy/vscode-comment-autocomplete.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9758711/53940781-7ffb9180-40f1-11e9-99a4-b208dd54a28b.gif)

But it still has some problems.

1. Cannot render correctly in `JSX/TSX/VUE`
2. No analysis context, frequent auto-completion.

So, if you have a better solution, I might not create a PR.

**Comment by dbaeumer** [comment]
@axetroy I would actually not create a generic extension for this. I think we are better off to have these in the corresponding linters, prettier extensions. 

And you can contribute snippets statically. See https://github.com/Microsoft/vscode/blob/master/extensions/html/package.json#L78 and https://github.com/Microsoft/vscode/blob/master/extensions/html/snippets/html.snippets.json#L1 as an example.

**Comment by axetroy** [comment]
@dbaeumer Yes, I agree that!

But I am afraid that snippets can't achieve this feature.

eg.

```vue
<template>
  <div>
    <!-- eslint-disable -->
  </div>
</template>

<script>
export default {
  date() {
    // eslint-disable
  },
};
</script>

<style>
/* eslint-disable */
</style>
```

**there are 3 comment styles and maybe more.**

It's hard to tell how to comment.

this may require using AST to parse the file.

I will not initiate PR until I solve this problem.

If your team has a better way, then just do it.

**Comment by dbaeumer** [comment]
@axetroy valid point !

**Comment by dbaeumer** [comment]
I think this is obsolete now that we have quick fixes to add these comments.

I will close the issue.
