### ISSUE TITLE
Infer `eslint.validate` from plugins configuration.

### ISSUE THREAD

**Issue by clock157** [microsoft/vscode-eslint#642]
demo repo:
https://github.com/clock157/bug-vscode-eslint-typescript

run command can found error but not report in vscode.

set `setting.json` not work too.
```diff
+"eslint.options": {
+        "extensions": [".ts", ".tsx"]
+},
```

**Comment by Sujimoshi** [comment]
The same. My config:
```
    "eslint.autoFixOnSave": true,
    "eslint.validate": [ 
        "javascript", 
        "javascriptreact", 
        { "language": "typescript", "autoFix": true },
        { "language": "typescriptreact", "autoFix": true } 
    ],
    "eslint.options": {
        "extensinons": [".ts", ".js"]
    },
```

**Comment by dbaeumer** [comment]
Strange. This works for me using the repository from https://github.com/Microsoft/vscode-eslint/issues/642#issue-417763561 and adding the following setting.

```
{
	"eslint.validate": [
		"javascript",
		"javascriptreact",
		{ "language": "typescript", "autoFix": true }
	]
}
```

<img width="531" alt="capture" src="https://user-images.githubusercontent.com/1931590/53940198-53c21f80-40b5-11e9-828a-4da5fbbeb761.png">

**Comment by dbaeumer** [comment]
Any additional information how to reproduce what you are seeing.

**Comment by Sujimoshi** [comment]
Eslint extension info:
```
Name: ESLint
Id: dbaeumer.vscode-eslint
Description: Integrates ESLint JavaScript into VS Code.
Version: 1.8.1
Publisher: Dirk Baeumer
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
```

**Comment by Sujimoshi** [comment]
Work!!! After update to latest vscode

**Comment by dbaeumer** [comment]
@Sujimoshi this was a problem on my end not treating versions correctly. I fixed this and releases 1.8.2 which now prereqs the right VS Code version. Sorry for that.

@clock157 any additional information. Are you still seeing this ?

**Comment by clock157** [comment]
hi @dbaeumer, thanks for your help, It works.
```diff
+"eslint.validate": [
+    { "language": "typescript" }
+]
```
can this option set to default that `tslint` will deprecated?

**Comment by dbaeumer** [comment]
The problem here is that eslint (the npm module) out of the box only validates JS files. Everything else comes in as a configuration. What I can look into is whether I am able to infer this from the plugins section.

**Comment by LeoEatle** [comment]
Any progress? I still need to config `eslint.validate` to make typescript eslint work. But in the doc 
```
Improved TypeScript detection - As soon as TypeScript is correctly configured inside ESLint, you no longer need additional configuration through VS Code's eslint.validate setting. The same is true for HTML and Vue.js files.
```

**Comment by dbaeumer** [comment]
Actually that got fix for 2.x version of ESLint. TypeScript should work out of the box without providing an `eslint.validate` setting.

@LeoEatle does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
