### ISSUE TITLE
Excluding folders does not work

### ISSUE THREAD

**Issue by rowild** [Microsoft/vscode-eslint#648]
I want to exclude a folder by name of "public", so I added a `.eslintignore` and added `/public` to it. 
Additionally, in VS Code und the workspace settings, I added:
```
{
  ...
  "eslint.workingDirectories": {
    "./src"
  }
}
```
hoping that eslint will do its work only in that folder.

Unfortunately, this does not work, the files in `public` are still analysed and marked red by eslint.

If I am doing something wrong, I really don't know. Googled like the devil... 

EDIT:
Configuring VS Code is a night mare IMO.

Adding `**/.js` should obviously ignore ALL js files. But what really happens is: 
* the errors are still underline (a wave line in red)
* on hovering the error, a pop-up shows the error message, and from what I can tell, the error code points to the eslint rule that is not met (e.g. `no-tabs`)
* `autoFixing on save` though is disabled; this will work again, as soon as I remove the glob pattern from the eslingnore file (whyyyyyy I wonder!?!?!?)

And BTW: in VSCode `"javascript.validate.enable": false` and `"files.autoSave": "off"` are set...

Any suggestion at what is gong on here? Bug? Or my misconfiguraton? Thanks!

**Comment by rowild** [comment]
Thanks for your feedback and your offer to take a look at my setup, @dbaeumer ! But i have no github repo where my project is stored. Yet. Sorry...

However - I think, I understood a little bit more about the setup and got it working, at least for this project. One reason might have been that I used "false" instead of "off" in the eslintconfig file...

This is what I have now:
- put .eslintignore in the root folder
- add folder to eslintignore like `/public`
- make sure there are no spelling/config errors in .eslintrc.json
- In VS Code:

```
{
  "eslint.autoFixOnSave": true,
  "eslint.alwaysShowStatus": true,
  "eslint.run": "onSave",
  "eslint.enable": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact"
  ],
  "eslint.workingDirectories": [
    "./"
  ],
  "eslint.options": {
    "configFile": "./.eslintrc.json"
  },
}
```

I'll report back, if something weird is going on again. For now, I close this issue.

Thank you very much again! Highly appreciated!

**Comment by dbaeumer** [comment]
Good to see you got it working.
