### ISSUE TITLE
Suppress autofix when Git merge markers are present

### ISSUE THREAD

**Issue by rjgotten** [microsoft/vscode-eslint#649]
Currently autofix can be either enabled 'on type' or 'on save' and applies while VSCode is used to resolve Git merge conflicts.

This leads to catastrophic corruptions of file content when autofixing files that have HTML(-like) linting enabled via various extension packages such as for `.vue` files, which misinterpret Git merge markers as HTML tags.

As a precaution, autofix behavior should be completely surpressed while merge markers are present in a file.

**Comment by dbaeumer** [comment]
I am still willing to accept a PR if someone wants to work on this.
