### ISSUE TITLE
ESLint: Lint Whole Folder task not appearing

### ISSUE THREAD

**Issue by nphmuller** [Microsoft/vscode-eslint#650]
The docs describe that setting the `eslint.provideLintTask` setting to `true` should add an `ESLint: Lint Whole Folder` command to the Command Palette. The command however is not appearing for me.

VSCode 1.32.3
ESLint: 1.8.2

Repro:
Go to File -> Preferences -> Settings
Under Extensions -> ESLint check `Eslint: Provide Lint Task` (Tested both in User Settings and Workspace Settings)
Restart Code
Open cmd palette (ctrl + shift + p) and type `eslint`.
The command should appear in the suggestion list, but it doesn't.

**Comment by dbaeumer** [comment]
The task doesn't show up in the command palette. It shows up in the task selection box. Execute Terminal > Run Task to see the list of available Tasks.

<img width="673" alt="capture" src="https://user-images.githubusercontent.com/1931590/55249861-58f63280-524d-11e9-949d-92abbbe5f16e.png">

**Comment by nphmuller** [comment]
I almost couldn't imagine the entire feature not working, but I just couldn't figure it out. Thanks for the help!
