### ISSUE TITLE
Eslint quick fix not showing

### ISSUE THREAD

**Issue by gokulsgr** [Microsoft/vscode-eslint#654]
Issue Type: <b>Bug</b>

Eslint quick fix (bulb) not showing
Auto save not working sometimes

Extension version: 1.8.2
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|-psn_0_360536|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by dbaeumer** [comment]
@gokulsgr can you please provide steps on how to reproduce what you are seeing. The light bulb shows for me.

**Comment by dbaeumer** [comment]
Best would be a GitHub repository I can clone.
