### ISSUE TITLE
changeProcessCWD Documentation incorrect

### ISSUE THREAD

**Issue by mcmar** [Microsoft/vscode-eslint#656]
I just wasted several hours trying in vain to debug because 1 small line of documentation in the README file is incorrect.
It states:

Then using the setting:
  ```json
    "eslint.workingDirectories": [
      "./client", "./server"
    ]
  ```
  will validate files inside the server directory with the **server directory as the current working directory**. (emphasis added)

I found an issue where someone was similarly confused and that issue appears to have been closed and locked in error
https://github.com/Microsoft/vscode-eslint/issues/595

The README appears to state that `changeProcessCWD` defaults to `true`, when in fact it defaults to `false`. That can easily be corrected. Perhaps it should also be re-written in a clearer manner showing both syntaxes so that future confusion may be avoided.

**Comment by dbaeumer** [comment]
I agree that the documentationis misleading. The problem is that there are two kind of working directories for eslint:

- the one you can set for eslint
- the one for the process.

I will look at your PR (thanks) and will clarify this to ensure there is no misunderstanding in the fuuture.
