### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Titio-Lele** [Microsoft/vscode-eslint#658]
- Issue Type: `Bug`
- Extension Name: `vscode-eslint`
- Extension Version: `1.8.2`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 169,
		"activateCallTime": 8,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Language client is not ready yet"
		}
	]
}
```

**Comment by dbaeumer** [comment]
@Titio-Lele any additional info how this happend. The error indicates that the client couldn't be started. Can you reproduce this?
