### ISSUE TITLE
Extension seems to choke on symlinked eslintrc files

### ISSUE THREAD

**Issue by benjamincharity** [microsoft/vscode-eslint#66]
I usually keep all of my config files in a `dot-files` directory with any needed files symlinked into my home directory (this way I can track all config via a single git repo).

The error message: `Cannot read config file: /Users/bc/.eslintrc Error: end of the stream or a document separator is expected at line 1, column 5: book ^`

Any ideas on this? (This is my first attempt at VS Code from Vim, so very possible I missed a setup step or something..)
### Reproduce
- move your `.eslintrc` from your user directory (`/Users/bc/` for me)
- create a symlink to this file in your home directory called `.eslintrc`
- open a file 
### My resources

My `.eslintrc` (which _does_ work with vim/cli):

```
{
    "extends": "eslint:recommended",
    "plugins": [
      "angular"
    ],
    "env": {
      "es6": true,
      "env": {
        "browser": true
      }
    },
    "ecmaFeatures": {
      "modules": true
    },
    "globals": {
      "module": true,
      "inject": true,
      "moment": false,
      "_": false,
      "angular: true"
    },
    "rules": {
        "comma-dangle": [2, "always-multiline"],
        "radix": 2,
        "yoda": 2,
        "array-bracket-spacing": [2, "never"],
        "brace-style": 2,
        "camelcase": 2,
        "eol-last": 2,
        "func-names": 0,
        "func-style": [2, "declaration"],
        "indent": 2,
        "key-spacing": 2,
        "lines-around-comment": [2, {
          "beforeBlockComment": true,
          "beforeLineComment": false
        }],
        "no-inline-comments": 0,
        "no-mixed-spaces-and-tabs": 2,
        "no-spaced-func": 2,
        "no-trailing-spaces": 2,
        "one-var": [2, "never"],
        "quotes": [2, "single"],
        "space-before-blocks": 2,
        "space-before-function-paren": [2, "never"],
        "space-in-parens": [2, "never"],
        "spaced-comment": [2, "always", {
          "line": {
            "exceptions": ["/"]
          },
          "block": {
            "exceptions": ["*"]
          }
        }],
        "no-var": 2,
        "prefer-const": 2,
        "max-len": [2, 100, 4, {
          "ignoreUrls": true
        }],
        "no-plusplus": 2,
        "object-curly-spacing": [2, "always"],
        "no-console": 0,
        "consistent-this": [2, "self"],
        "block-scoped-var": 2,
        "eqeqeq": 2,
        "no-var": 2,
        "no-const-assign": 2,
        "max-params": [2, 5],
        "no-redeclare": 2,
        "no-magic-numbers": 2,
        "no-use-before-define": 0,
        "no-unused-vars": 0,
        "angular/log": 0,
        "angular/no-service-method": 0
    }
}
```

I also tried with the example config from the eslint website: 

```
{
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "semi": 2
    }
}
```

Eslint portion of settings file:

```
    //-------- ESLint configuration --------

    // Control whether eslint is enabled for JavaScript files or not.
    "eslint.enable": true,

    // Control whether eslint errors are auto-fixed when a file is saved.
    "eslint.enableAutofixOnSave": false,

    // The eslint options object to provide args to the eslint command.
    "eslint.options": {},
```

**Comment by knownasilya** [comment]
This might also be related https://github.com/Microsoft/vscode/issues/27947

**Comment by dbaeumer** [comment]
@benjamincharity an additional question. Does that work without any problem if you execute eslint from the terminal? And which OS are you on. 

The eslint extension itself doesn't read the config file. It simply forwars this the to the eslint npm module.

**Comment by benjamincharity** [comment]
@dbaeumer It's actually been a bit since I've used ESLint (all work projects have been in TypeScript as of late). That being said, I do believe it was working well from the CLI as I was using ESLint from Vim and the terminal.

OS X Sierra.

Hmm so possibly it can't forward a symlink?

**Comment by dbaeumer** [comment]
@benjamincharity if you are still experiencing this please ping and I will consider reopening it.
