### ISSUE TITLE
使用ESLtINT 保存代码时自动格式化无效

### ISSUE THREAD

**Issue by whoimiArt** [Microsoft/vscode-eslint#660]
Issue Type: <b>Bug</b>

在使用VSCODE 一段时间后，使用ESLtINT 保存代码时自动格式化无效，重启VSCODE 后又会生效。

Extension version: 1.8.2
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (4.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode-eslint/issues/600
