### ISSUE TITLE
VSCODE not linting *.test.js files

### ISSUE THREAD

**Issue by tsysrws** [Microsoft/vscode-eslint#662]
I have VSCODE and have started using ESLINT for all of my projects. ESLINT will run for files with .js and .jsx extensions, but not with test.js extensions.

VSOCDE version 1.31.0
ESLINT version 5.16.0
.eslintrc.json
{ "parser": "babel-eslint", "extends": ["airbnb"], "env": { "browser": true, "node": true, "jest": true }, "rules": { "no-console": 1, "comma-dangle": "off", "react/jsx-filename-extension": "off" }, "plugins": [ "import", "jest", "react", "jsx-a11y" ] }

**Comment by dbaeumer** [comment]
The is default ESLint (https://eslint.org/) behaviour.

Dups https://github.com/Microsoft/vscode-eslint/issues/550
