### ISSUE TITLE
WSL and VSCode eslint not working

### ISSUE THREAD

**Issue by deanhtid** [Microsoft/vscode-eslint#666]
So I can't for the life of me get ESLint to work using WSL and VSCode.

It runs fine in the terminal.

I have node installed through the wsl terninal using /n

I have the eslintrc file saved at ~

Any help getting this set up would be greatly appreciated.

❯ npm config get prefix
/home/deanhtid99/n 

❯ npm root -g
/home/deanhtid99/n/lib/node_modules

**Comment by dbaeumer** [comment]
Dups #251
