### ISSUE TITLE
Eslint server crashes with webpack resolver settings

### ISSUE THREAD

**Issue by revathskumar** [Microsoft/vscode-eslint#667]
Issue Type: <b>Bug</b>

using `eslint-import-resolver-webpack` causes the eslint server to crash.

```diff
{
  "parser": "babel-eslint",
  "extends": [
    "airbnb",
    "prettier/react",
    "plugin:prettier/recommended",
    "plugin:flowtype/recommended"
  ],
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "jest": true,
    "node": true
  },
  "plugins": ["prettier", "flowtype"],
  "rules": {
    "react/prop-types": false,
    "react/jsx-filename-extension": false,
    "comma-dangle": ["error", "only-multiline"],
    "prettier/prettier": ["error", { "tailingComma": "es5" }],
    "import/no-named-as-default": false,
    "import/no-named-as-default-member": false,
    "import/no-extraneous-dependencies": false
  },
+  "settings": {
+   "import/resolver": "webpack"
+ }
}
```

Started to crash when the highlighted part the above `.eslintrc` is added.

In console this error found.

```

[Trace - 4:58:52 PM] 'npm config get prefix' value is: /usr/local
[Trace - 4:58:52 PM] NODE_PATH value is: /usr/local/lib/node_modules
[Trace - 4:58:52 PM] NODE_PATH value is: /usr/local/lib/node_modules
[Trace - 4:58:52 PM] NODE_PATH value is: /usr/local/lib/node_modules
[Trace - 4:58:53 PM] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "ESLint library loaded from: /Users/revathskumar/code/src/node_modules/eslint/lib/api.js"
}


[Info  - 4:58:53 PM] ESLint library loaded from: /Users/revathskumar/code/src/node_modules/eslint/lib/api.js
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/revathskumar/code/src/node_modules/node-sass/vendor/darwin-x64-64/binding.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/revathskumar/code/src/node_modules/node-sass/vendor/darwin-x64-64/binding.node
  Expected in: flat namespace

[Error - 4:58:57 PM] Connection to server got closed. Server will not be restarted.
[Info  - 4:58:57 PM] ESLint server stopped.
```

running `eslint` outside of the vscode works fine with the new `webpack` setting.

Extension version: 1.8.2
VS Code version: Code - Insiders 1.34.0-insider (63655183ba5305b70ffaf1327b8a4708f0a79bd9, 2019-04-26T05:14:50.702Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|-psn_0_2351678|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
This is caused by the same underlying reason as described in #668. See https://github.com/Microsoft/vscode-eslint/issues/668#issuecomment-489607012 for how to fix this.
