### ISSUE TITLE
eslint extension keep crashing in a project created by neutrinojs cli v8.3.0

### ISSUE THREAD

**Issue by crown3** [microsoft/vscode-eslint#668]
eslint keep crashing in this project created by [neutrinojs](https://neutrinojs.org/packages/react/) and `yarn lint` is okay.

## step to reproduce

download [this repository](https://github.com/crown3/eslint-crash-example), just trigger a save action in any js file while `"eslint.autoFixOnSave": true`. I had set `"eslint.runtime": "node"` from this issue #634 , but no use.

![image](https://user-images.githubusercontent.com/19649900/56805036-4bd36000-685a-11e9-8164-24e796549fb0.png)

```
extensionHost.ts:216 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/crown/Desktop/code/Trying/tt/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/crown/Desktop/code/Trying/tt/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace
```

## versions

vscode-eslint: 1.8.2
vscode: 1.33.1
eslint: 5.16.0
node: v10.15.0

**Comment by dbaeumer** [comment]
This is very likely cause by the fact that we use Electron as a node runtime and the native modules compiled are not working with the Electron node version. Can you try to use the following setting `eslint.runtime` and point it to a node version (the executable) for which the libraries got compiled. You can take the node version which is used when executing eslint in a terminal if that works successful.

**Comment by crown3** [comment]
Did you mean that ? 
![image](https://user-images.githubusercontent.com/19649900/57227744-bba8ce00-7044-11e9-8c5d-435abf7f366a.png)
But it still broken ... 
![image](https://user-images.githubusercontent.com/19649900/57227791-d2e7bb80-7044-11e9-936b-c8d61ad2851f.png)

**Comment by dbaeumer** [comment]
Yes, but this is now very strange since it crashes the extension host. Can you provide me with a GitHub repository I can clone that demos what you see (might require some additional info on how to reproduce)

**Comment by crown3** [comment]
@dbaeumer I had listed the address at the beginning, download [this repository](https://github.com/crown3/eslint-crash-example)

**Comment by dbaeumer** [comment]
Sorry, missed that.

**Comment by dbaeumer** [comment]
Can't reproduce this. It works for me even without setting `eslint.runtime`

![capture](https://user-images.githubusercontent.com/1931590/57450022-a5c22580-725d-11e9-8135-a4cfef51b92b.png)

Any additional info?

**Comment by crown3** [comment]
I have open a new project based on neutrino@next, but it's no problem in there. This may be my own personal problem.
 
Turn off the issue first. If find the other reason, I will reopen this.
