### ISSUE TITLE
Eslint doesn't recognize non-numeric values for severity in .eslintrc.json

### ISSUE THREAD

**Issue by vrabcak** [Microsoft/vscode-eslint#67]
After I open a javascript file, i get following error message:

`.eslintrc.json: Configuration for rule "indent" is invalid: Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "error")`

If I run eslint from command line, eslint runs ok. 
It seems like vscode-eslint is using different (older) version of eslint than the one installed in system.

**Comment by dbaeumer** [comment]
The ESLint plugin doesn't ship with its own version of eslint. It always takes the eslint found on the machine using the following order

- installed in the workspace folder open
- globally installed.

I close this one since the problems comes from an eslint installation on your machine.
