### ISSUE TITLE
overrides not working

### ISSUE THREAD

**Issue by SnO2WMaN** [microsoft/vscode-eslint#671]
https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files

This extension does not consider the overrides described in eslint config file ex. `.eslintrc`.

Please confirm it is.

**Comment by dbaeumer** [comment]
Actually, this works for me:

![capture](https://user-images.githubusercontent.com/1931590/57219887-c12cf680-6ff9-11e9-8971-e3f8ffa582f0.png)

Please provide me with a GitHub repository that demos the problem you see.

**Comment by SnO2WMaN** [comment]
I'm sorry. It's my bad in configuration file.

I wanted to report a bug that VSCode does not interpret it as Typescript even if I specify a parser (eg: @ typescripts-eslint/parser) in `overrides`, but my own configuration file `overrides.files` I was just wrong in specifying the pattern of.

Sorry.
