### ISSUE TITLE
vue/valid-template-rule

### ISSUE THREAD

**Issue by codytooker** [microsoft/vscode-eslint#672]
It seems as if the vue/valid-template-rule is not being correctly interpreted by vscode-eslint.

When building Vue VativeScript apps we have the ability to have multiple templates in one file following this format

```
<template web>
    <title>This is the web template</title>
</template>

<template native>
    <title>This is the native template</title>
</template>
```

Vscode marks everything inside the second template as failed saying the vue/valid-template-rule is in error.  However running eslint from the command line doesn't mark this as an error. 

Seems like vsCode doesn't understand the appearance of two template tags within a vue file.

**Comment by dbaeumer** [comment]
@codytooker what happens when you validate that file in a terminal using eslint directly.

**Comment by codytooker** [comment]
@dbaeumer When running eslint from the terminal directly on the file, it shows no eslint errors.

**Comment by dbaeumer** [comment]
@codytooker can  you provide me with a GitHub repository I can clone that demos what you are seeing?

**Comment by codytooker** [comment]
@dbaeumer here you go https://github.com/codytooker/nativescript-todos. It's a simple project building the todomvc.

**Comment by dbaeumer** [comment]
@codytooker I cloned the project however I am not sure which file to open and what error you think shouldn't be presented.

**Comment by codytooker** [comment]
@dbaeumer any of the .vue components that have two template roots.  `<template web>` `<template native>` cause the problem.  in particular `src/components/todo/TodoList.vue`

VsCode underlines the entire second template.

![image](https://user-images.githubusercontent.com/19712217/58028524-89857a80-7ae0-11e9-9974-50cd191badbf.png)

with error [vue/valid-template-root]

**Comment by vpiskunov** [comment]
Any update on this? Same issue here. 

Also, disabling the rule via 'vue/valid-template-root': 'off' doesn’t disable the rule for some reason?

**Comment by dbaeumer** [comment]
Actually, that is not caused by the ESLint plugin. I see this error even with ESLint extension disabled. Looking into this it looks like the diagnostics are generated by the `Vue Language Server`. Disabling the Vetur makes the error go away.

Can you please report the issue against the Vetur plugin?
