### ISSUE TITLE
ESlint throwing lint errors originating in node_modules

### ISSUE THREAD

**Issue by caseysiebel** [microsoft/vscode-eslint#675]
I've opened Visual Studio Code to my working directory with `.estlintrc.js` and `.eslintignore` files.

VS code is showing hundreds of error all originating from the `flow-typed` and `node_modules` directories. This issue persists whether or not `flow-typed` and `node_modules` are present in the `.eslintignore` file.

This issue arouse suddenly a few weeks ago. Before that everything worked as expected.

VSCode v1.33.1 
ESlint extension v1.8.2
Flow Language Support Extension v1.1.1
eslint ^4.5.0
eslint-plugin-flowtype ^2.35.0

**Comment by dbaeumer** [comment]
@caseysiebel can you provide me with a GitHub repository I can clone that demos this. I can not reproduce this.

**Comment by dbaeumer** [comment]
Are you opening these files in the editor (e.g. the once from the node_modules folder?)
