### ISSUE TITLE
eslint.options.env is not respected

### ISSUE THREAD

**Issue by loilo** [microsoft/vscode-eslint#676]
When configuring default options for ESLint through VSCode options, the `env` option is ignored:

```js
// VSCode settings
{
  "eslint.options": {
    "rules": {
      "no-undef": ["error"]
    },
    "env": {
      "browser": true
    }
  }
}
```

```js
// Any JavaScript file, errors with "'alert' is not defined"
alert('baz')
```

**Notes:**
* This seems to be the exact same issue as #395.
* Everything works as expected when the same options are defined in an `.eslintrc` file.

A reproduction repository can be found at [loilo/repro-vscode-eslint-676](https://github.com/loilo/repro-vscode-eslint-676).

**Comment by dbaeumer** [comment]
Actually this is a quirk in npm ESLint itself. In the options for the CLIEngine this is called `envs` not `env`. See https://eslint.org/docs/developer-guide/nodejs-api#cliengine

**Comment by loilo** [comment]
Weird. Thanks for investigating!
