### ISSUE TITLE
ESLint server running in older version of node 

### ISSUE THREAD

**Issue by SheikhG1900** [microsoft/vscode-eslint#678]
**ESLint Log**
```
[Info  - 6:49:45 AM] ESLint server stopped.
[Info  - 6:49:51 AM] ESLint server running in node v10.2.0
[Info  - 6:49:51 AM] ESLint server is running.
```

**Terminal**
```
node -v
v10.15.3
```

Please help me to upgrade eslint's node version.

**Comment by dbaeumer** [comment]
Use the `eslint.runtime` setting to specify the location of the node executable to use. By default Electron's node version is used.
