### ISSUE TITLE
fail to load eslint locally?

### ISSUE THREAD

**Issue by Lynn-cc** [microsoft/vscode-eslint#681]
![image](https://user-images.githubusercontent.com/540202/58621173-60909100-82fb-11e9-97d5-939aeb21bf7b.png)

system:macOS
system version: 10.13.6
vscode version: 1.34
network: company network with proxy, use `tnpm` instead of `npm` when install packages.

Could eslint be loaded locally ?
 I don't want to install it globally because many plugins also need to be installed globally.

**Comment by dbaeumer** [comment]
Installing eslint locally works for me if installed using yarn or npm without any problems. What exactly is `tnpm`. Can you lint your file using eslint installed locally from the terminal?

If it works can you please provide me with a GitHub repository I can clone that demos the problem you are seeing?

**Comment by Lynn-cc** [comment]
Thanks for your tips that I fount `./node_modules/.bin/eslint` link exsit but can't run, because `./node_modules/eslint/bin/eslint` is not exsit. I don't know why but after reinstall the node_modules, the error logs gone. Thanks you very much.

**Comment by dbaeumer** [comment]
OK. Closing the issue then.
