### ISSUE TITLE
Sometimes get no auto-fix

### ISSUE THREAD

**Issue by IanIsFluent** [microsoft/vscode-eslint#685]
I'm very confused by the auto-fix suggestions in the ESLint plugin, some 'easy' ones don't seem to be available - and I'm sure ones that I was just using become unavailable later.

* I **can** auto-fix a `comma-dangle` (which removes it) 
* I **can't** auto-fix a `no-unused-vars` (which should remove it) 
* I **can't** auto-fix a `eqeqeq` (which should add an `=`)
* I **can't** auto-fix a `no-const-assign` (which should change it to `let`).

VSCode Version: 1.35.0
OS: Windows_NT x64 10.0.17134
ESLint plugin: 1.9.1
(running with all other plugins disabled)

.eslintrc:
```
{
  "parser": "babel-eslint",
  "extends": "react-app",
  "rules": {
    "linebreak-style": [
      "error",
      "windows"
    ],
    "arrow-parens": [
      "error",
      "as-needed"
    ],
    "no-warning-comments": "off",
    "no-underscore-dangle": "warn",
    "camelcase": "warn",
    "comma-dangle": "warn"
  }
}
```

**Comment by dbaeumer** [comment]
Could you provide me with a GitHub repository I can clone that demos it. That ensure we have the same eslint and plug-in versions installed.

**Comment by IanIsFluent** [comment]
Oh - so it _should_ be trying to auto-fix these?! Awesome! I'll see if I ever get time then! ;)

**Comment by dbaeumer** [comment]
Any update?

**Comment by IanIsFluent** [comment]
Sorry, mate. I've not been working with VSCode since I posted this. And not sure when I will again. So may as well close it, as I can't provide what you need right now 😢

**Comment by dbaeumer** [comment]
Fair enough

**Comment by IanIsFluent** [comment]
I'm now looking at some JS and thought I'd revisit this. I'm still very confused as to what autofix is, and what list of problems its meant to be able to autofix.

This example https://oprea.rocks/blog/automatically-fix-eslint-code-validation-errors-in-visual-studio-code/ shows auto-fixing a comma-dangle warning - but that's consistently the _only_ auto fix I've ever seen?

Is there a list of available auto-fixes? I'd assumed that fixing `eqeqeq` (for example) was simple enough that there'd definitely be an auto-fix for that. But I wasted a lot of time testing that in different settings, and its never worked!

To reproduce, run `create-react-app` in an empty folder, copy the .eslint above (remove the line about windows lineendings though!) and then add an `eqeqeq` error (like `if(1 == 2)`) and see that there's no autofix suggestion.

**Comment by dbaeumer** [comment]
@IanIsFluent will the error be fixed if you run eslint in the terminal using `--fix`?

**Comment by IanIsFluent** [comment]
It doesn't. I've spoken to our JS expert who points out that `eqeqeq` _is_ different to `comma-dangle` in that `eqeqeq` _could_ have been desired behaviour.
