### ISSUE TITLE
[bug] Fix order 

### ISSUE THREAD

**Issue by thomaLV** [microsoft/vscode-eslint#686]
**Tell us about your environment**

* **ESLint Version:** 5.16.0
* **Node Version:** 12.4.0
* **npm Version:** 6.9.0

**Please show your full configuration:**

<details>
<summary>Configuration (excerpt)</summary>

```js
"extends": "eslint:recommended",
"rules": {
	"template-curly-spacing": ["warn", "never"],
	"no-multi-spaces": "warn",
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
recurse(cur[i], `${prop  }[${  i  }]`);
```

Running in vscode I clicked "Fix all template-curly-spacing problems" as shown in the picture below.
![image](https://user-images.githubusercontent.com/36425287/59304409-81140000-8c98-11e9-8dca-4952c2486c0c.png)

**What did you expect to happen?**
```js
recurse(cur[i], `${prop}[${i}]`);
```

**What actually happened? Please include the actual, raw output from ESLint.**
```js
recurse(cur[i], `${prop }[${ i }]`);
```

**Comment by dbaeumer** [comment]
@thomaLV does the same happen when running ESLint in a terminal requesting fixing problems?

**Comment by thomaLV** [comment]
No, running ESLint in a terminal instead fixes the problem.
`eslint --fix 'file.js'`

**Comment by thomaLV** [comment]
The problem exists for other rules as well. Clicking "Fix all indent problems" in the below picture turns 
```
if (this.colorlist.getData() !== null)
	{lst.push(this.colorlist.getData());}
```
into
```
if (this.colorlist.getData() !== null)
	{ lst.push(this.colorlist.getData()); }
```
![image](https://user-images.githubusercontent.com/36425287/59708025-38ae9200-9204-11e9-98f0-641d0931a3dd.png)

**Comment by dbaeumer** [comment]
OK. Can you provide me with a GitHub repository I can clone that demos this. This ensures that I end up with the same setup and configuration.
