### ISSUE TITLE
Default .eslintrc.json file association

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-eslint#688]
If possible, could the extension make it so that the default file association is set to JSON with comments? Currently I have to use this in my configuration for it to work with comments:

```json
"files.associations": {
    ".eslintrc.json": "jsonc"
},
```

As .eslintrc.json is jsonc by default, it would be better for everyone if the extension defaulted to this. Not sure if VS Code supports the extension API to do this?

**Comment by dbaeumer** [comment]
Nice idea.
