### ISSUE TITLE
Parsing error: File 'tsconfig.json' not found.

### ISSUE THREAD

**Issue by orblazer** [microsoft/vscode-eslint#691]
Hello,
I have an error when i check git diff on vscode with typescript files.

Version of vscode-eslint: 1.9.0
Version of vscode: 1.35.1

The error :
```
Parsing error: File '/home/orblazer/tsconfig.json' not found.
```

Thanks.

**Comment by dbaeumer** [comment]
@orblazer can you please elaborate why you think this is something caused by ESLint. If you think this is a VS Code problem itself please file the issue here: https://github.com/microsoft/vscode

**Comment by orblazer** [comment]
@dbaeumer I think is eslint because on the error is that : ![Screenshot_20190619_114807](https://user-images.githubusercontent.com/1344792/59755394-21b18380-9288-11e9-87d7-c3d94f08e99e.png)

**Comment by dbaeumer** [comment]
@orblazer does this also happen when executing ESLint from the terminal?

**Comment by dbaeumer** [comment]
If not can you provide me with a GitHub repository I can clone that demos this?

**Comment by orblazer** [comment]
@dbaeumer i just use nuxt.js typescript starter

And i have error on file like :
```ts
import { Context } from '@nuxt/vue-app'

declare module '@nuxt/vue-app/types/index' {
  interface Context {
    userAgent?: string;
  }
}
```

Sorry but for now i don't have big time for more investigation :disappointed:

**Comment by dbaeumer** [comment]
How does your `tsconfig.json` content look like ?

**Comment by andrucz** [comment]
Same here

**Comment by yeraydiazdiaz** [comment]
FWIW, I solved this by setting `changeProcessCWD` in the `workingDirectories` setting:

```
"settings": {
	"eslint.workingDirectories": [
		{"directory": "<PATH_TO_TSCONFIG>", "changeProcessCWD": true }
	]
}
```
