### ISSUE TITLE
recognize the variable as a used and read variable

### ISSUE THREAD

**Issue by RexProg** [microsoft/vscode-eslint#692]
```js
  Logout(access_token) {
    this.post('/Account/Logout', this.parsArgs('access_token', arguments));
  }
```

I expected to recognize the access_token as a used and read variable

Something that actually goes
'access_token' is defined but never used.

Environment:
Windows 10 64bit

ESLint Version: 1.9.0
Node Version: 10.16.0
npm Version: 6.9.0

**Comment by golopot** [comment]
This repo is probably a wrong place for this issue. That said, eslint is working as intended in that code snippet because `access_token` is unused.

**Comment by dbaeumer** [comment]
I agree with @golopot. Closing the issue.
