### ISSUE TITLE
Autofix not working correctly when using both `semi` and `eol-last`

### ISSUE THREAD

**Issue by liangzr** [microsoft/vscode-eslint#693]
`eslint.executeAutofix` not working correctly when using both `semi` and `eol-last`

#### Example:
```js
const a = 1;
const b = 2
```
#### Step to reproduce:

1. execute `eslint.executeAutofix`

```js
const a = 1;
const b = 2
;
````

continue to prompt 'eol-last' problem

2. execute `eslint.executeAutofix` again

```js
const a = 1;
const b = 2
;
   
````

no more lint errors

---

As shown above, eslint can't work correctly in this case. However, `eslint src --fix` could fix the problems **as expected**:

```js
const a = 1;
const b = 2;

```

**Comment by dbaeumer** [comment]
@liangzr can you please provide me with a GitHub repository I can clone that demos this. That will ensure that we have the same setup.

**Comment by liangzr** [comment]
I have reproduced the error in this repo: https://github.com/liangzr/vscode-eslint-demo, and configured two ways to lint code

1. Use **vscode**, with .vscode settings

Just execute the `eslint.executeAutofix` twice as mentioned above

2. Use eslint command-line

```
npm run lint:fix
```

**Comment by dbaeumer** [comment]
Since this also happens when executing the command in a terminal it indicates that it is a problem with the ESLint npm module. Please report the issue here: https://github.com/eslint/eslint

**Comment by liangzr** [comment]
@dbaeumer It won't happen when executing the `eslint` command using my repo, did you reproduce it with `eslint` command in a terminal?

**Comment by dbaeumer** [comment]
Sorry, I misunderstood you then. I read your comment https://github.com/microsoft/vscode-eslint/issues/693#issuecomment-505422417 that it does happen in the terminal.

**Comment by liangzr** [comment]
@dbaeumer There is no further progress on this question, but I found that it works fine in the newer version(`dbaeumer.vscode-eslint@2.1.1`), maybe we should close this issue now. Thanks for your works :)

**Comment by dbaeumer** [comment]
@liangzr thanks for coming back. Will close the issue.
