### ISSUE TITLE
Uses the wrong working directory

### ISSUE THREAD

**Issue by TidyIQ** [microsoft/vscode-eslint#695]
My package.json file is located at `C:\Users\Me\Websites\Templates\core`, which I'll refer to here as my Correct Working Directory (CWD). Inside the package.json I have:

```
  "eslintConfig": {
    "extends": [
      "plugin:react/recommended",
      "MY_CUSTOM_CONFIG"
    ]
  },
```
I have also installed `eslint-plugin-react` within CWD.

There seems to be a bug with vscode-eslint ([according to ESLint here](https://github.com/eslint/eslint/issues/11891#issuecomment-504981956)) as instead of looking for the module in CWD, it looks for it in `C:\Users\Me\Websites`, as per this error output message:

```
[Error - 9:18:22 am] Error: Error while loading rule 'react/display-name': Cannot find module 'react' from 'C:\Users\Me\Websites'
Occurred while linting C:\Users\Me\Websites\Templates\core\src\index.tsx
```

I have confirmed that the module exists where it should in `C:\Users\Me\Websites\Templates\core\node_modules\eslint-plugin-react`

This only occurs for the `eslint-plugin-react` module (and the `eslint-plugin-jsx-a11y` module, which I have since removed). It's able to find the other modules I have installed.

**Versions**

- "eslint": "^5.16.0"
- "eslint-plugin-react": "^7.14.2"
- vscode-eslint: 1.9.0

Everything is installed locally.

I can also confirm that this issue doesn't occur when using the ESLint CLI. It's strictly an issue with the vscode ESLint extension.

**Comment by dbaeumer** [comment]
@TidyIQ can you provide me with a GitHub repository I can clone that demos this. 

Which directory is the workspace folder you open. You might need to set the `eslint.workingDirectories` if things are in sub folders since the plugin seems to be loaded relatively.

**Comment by davidysoards** [comment]
I'm having the same issue. It seems to be looking for the "react" module in the parent directory instead of the project root directory. Extremely frustrating
_Error: Error while loading rule 'react/no-typos': Cannot find module 'react' from '/Users/davidsoards/projects/sandbox'_

my project directory is located inside sandbox/

why is it doing this?
This should be reopened.

**Comment by dbaeumer** [comment]
Have you lately upgraded to ESLint 6.0. You might want to look at https://github.com/microsoft/vscode-eslint/issues/696

**Comment by davidysoards** [comment]
update no, but it was a brand new repo, so yes it was on v6.0. Thanks!
