### ISSUE TITLE
.eslintignore is not working in VS Code May 2019 (1.35.1) on MacOS Mojave 10.14.5

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-eslint#697]
Copied from https://github.com/microsoft/vscode/issues/76194 @IndeDude

Issue Type: <b>Bug</b>
create file .eslintignore in project root folder
enter the following.
`**/*.json`
save file
start up VS Code
enable eslint 
set eslint run onType
create jsconfig.json (or any json file of your preference)
and enter the following:

  ```
"compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "*",
      "src/*",
      "assets/*"
    }
  }
}
```

save the file

open any javascript/jsx file
and you will see eslint report problems for jsconfig.json

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>c
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|-psn_0_2609789|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@IndeDude the .eslintignore file is not search the parent chain. This is a ESLint npm module feature. I tested and the ignore works for me in my setup.

By default ESLint is not validating json files. To be sure I am looking at the right problem can you share a GitHub repository that I can clone that demos this.

**Comment by IndeDude** [comment]
@dbaemer I have created a git repo [here](https://IndeDude@bitbucket.org/IndeDude/eslintignoredemo.git).  Thanks

**Comment by IndeDude** [comment]
@dbaeumer the repo you asked for is [here](https://IndeDude@bitbucket.org/IndeDude/eslintignoredemo.git). Thanks

**Comment by dbaeumer** [comment]
@IndeDude thanks. But I have problems accessing this repository. Can you fork it to GitHub?

**Comment by IndeDude** [comment]
@dbaeumer  sorry about that. [Here](https://github.com/IndeDude/eslintignoredemo.git) is the github repo

**Comment by dbaeumer** [comment]
@IndeDude these errors are generated by the jsonc language server. The don't come from ESLint. You see this with the owner of the problem. Is is `jsonc`. ESLint errors do have the `eslint` owner.

These errors are actually valid since the path setting in the jsconfig.json is a object literal.

<img width="358" alt="capture" src="https://user-images.githubusercontent.com/1931590/60420933-17c54400-9be9-11e9-9905-1feec7327878.png">
