### ISSUE TITLE
.eslintignore not working

### ISSUE THREAD

**Issue by Piero87** [microsoft/vscode-eslint#699]
Hi,
I have this version of VSCode 1.35.1, for macOS, this is my project structure:

```
.eslintrc
.eslintignore
js/
   ...
   app.js
```

I want ignore app.js and i have write this in ignore file:

```
js/app.js
```

But Eslint continue a give me error on that file and lint it, I can't understand where is the problem, any help?

**Comment by dbaeumer** [comment]
Is it ignored when running ESLint from the terminal. If yes, can you please provide me with a GitHub repository I can clone that demos what you see.

Also note the the `.eslintignore` file must be in the current working directory to work. It is not honor up the parent file chain. This is ESLint npm behaviour.
