### ISSUE TITLE
provide shortcut for applying fixes

### ISSUE THREAD

**Issue by pke** [Microsoft/vscode-eslint#70]
The lightbulb is nice (reminds me of Eclipse). How about a keyboard shortcut to apply the fixes:

* `MOD+SHIFT+1` Apply all fixes in file
* `MOD+1` Apply all fixes on current line

**Comment by RootMale** [comment]
+1 from prev topic

**Comment by dbaeumer** [comment]
This should be a general language independent actions. See https://github.com/Microsoft/vscode/issues/5650

**Comment by dbaeumer** [comment]
A general language independent action is harder to archive then we thought. So we start with a specific elsint action which I added. I didn't bind a default short cut since almost all short cuts are taken in one way or another. Feel free to bind the command id "eslint.fixAllProblems" as you would like.

**Comment by emzero** [comment]
@dbaeumer Is there a way to view the command id of a command? I spent a while looking for the eslint.fixAllProblems one until I found this issue.

**Comment by dbaeumer** [comment]
![capture](https://cloud.githubusercontent.com/assets/1931590/16261291/4a0794a2-386b-11e6-9f82-645114244ec5.png)

**Comment by dbaeumer** [comment]
Working code code complete helping with this.

**Comment by emzero** [comment]
Yes, but commands from extensions do not show up there.
i.e. `eslint.fixAllProblems`

**Comment by dbaeumer** [comment]
@aeschli is this a know limitation. Should commands from extensions show up here as well.

**Comment by aeschli** [comment]
@jrieken Joh added that...

**Comment by jrieken** [comment]
[All](https://github.com/Microsoft/vscode/blob/joh/menus/extensions/configuration-editing/src/extension.ts#L13) minus those that start with an underscore since we like those to be kept private.

**Comment by gertcuykens** [comment]
Can fixAllProblems be done automatically when you format the code please?

![image](https://cloud.githubusercontent.com/assets/863731/17274220/2034f8a6-56d7-11e6-897c-bab6cd4af40d.png)

**Comment by dbaeumer** [comment]
I would rather have format and fix all on save then binding fix all to format.
