### ISSUE TITLE
Parsing error: Unexpected token /

### ISSUE THREAD

**Issue by sryze** [microsoft/vscode-eslint#702]
When I use eslint on the command line I don't get any errors, but inside VS Code it complains about this line (at the closing h1 tag):

```js
render() {
        return <h1>Hello, World!</h1>;
}
```

.eslintrc.json:

```json
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": false
    },
    "parserOptions": {
        "ecmaVersion": 6,
        "ecmaFeatures": {
            "jsx": true
        },
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "extends": ["eslint:recommended", "plugin:react/recommended"]
}
```

Extensions settings:

```json
    "eslint.enable": true,
    "eslint.options": {
        "extensions": [
            ".js",
            ".jsx"
        ]
    },
    "eslint.validate": [
        "javascript", 
        "javascriptreact",
        "jsx",
        "html"
    ]
```

(VS Code identifies my file as JavaScript React)

ESLint version: tried 6.0.1, 5.16, 5.13 (global eslint - same version)
VS Code: 1.35.1
Extension version: 1.9.0

**Comment by dbaeumer** [comment]
@sryze can you please provide me with a GitHub repository I can clone that demos this. This ensures that we are using the same setup.

**Comment by dbaeumer** [comment]
and one more thing. Can you paste a screen shot of the error first to ensure that the error is really produced by the ESLint plugin.

**Comment by sryze** [comment]
![bug](https://user-images.githubusercontent.com/4525736/60683996-061bbf00-9ebd-11e9-9840-9410df19b1fa.PNG)

**Comment by dbaeumer** [comment]
Can you provide me with a GitHub repository that demos this. HTML support works fine for me.

**Comment by sryze** [comment]
Here you go: https://github.com/sryze/vscode-eslint-issue-702

Reproduce the bug with:

```
Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by sryze** [comment]
I think it has something to do with my local eslint, when I use the global package 

```
eslint react/MyComponent.jsx
```

output:

```
MyComponent.jsx
  1:16  error  'h' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

However, if I run the local version:

```
npx eslint react/MyComponent.jsx
```

it produces:

```
MyComponent.jsx
  6:31  error  Parsing error: Unexpected token /

✖ 1 problem (1 error, 0 warnings)
```

If I uninstall the local eslint package, VS Code ESLint works as it should.

**Comment by dbaeumer** [comment]
> Both local and global eslint are version 6.0.1.

This seems to explain it. ESLint 6.0.1 changed the way how eslint plug-ins are resolved and they now recommend that everything is installed locally. You might want to read https://github.com/microsoft/vscode-eslint/issues/696

I will close the issue. Please ping if #696 is not helpful for you.

**Comment by sryze** [comment]
Same problem with ESLint 5.16, I don't think it's related to the version. 

The extension works only if I delete the local eslint package and install eslint globally.

**Comment by dbaeumer** [comment]
Thanks for the repository.

The same happens when running eslint from the command line

<img width="748" alt="capture" src="https://user-images.githubusercontent.com/1931590/62634152-b144eb80-b935-11e9-9639-317672d13342.png">

**Comment by dbaeumer** [comment]
@sryze I will close the issue since this is not related to the ESLint extension. If you still see the error with a successful validation in the terminal please ping.
