### ISSUE TITLE
新版vscode-eslint1.9.0版本 notice 屎黄色波浪线？超级影响开发感官！！！

### ISSUE THREAD

**Issue by Davidliking** [microsoft/vscode-eslint#704]
新版vscode-eslint1.9.0版本 notice 屎黄色波浪线？超级影响开发感官！！！

**Comment by dbaeumer** [comment]
Can you please provide a description in English with steps on how to reproduce what you are seeing. Thanks

**Comment by Davidliking** [comment]
Okay, I've encountered the problem that the new version of vscode-eslint 1.9.0 code hints turned into shit yellow wavy lines.

**Comment by Davidliking** [comment]
Can you give me some solutions, such as setting some parameters in the configuration file?

**Comment by Davidliking** [comment]
Reproductive steps, such as writing corresponding JavaScript fragments, deliberately expose the problem of writing norms, for example, "! = Then eslint will report, better written as'! == Now you can see that there are shit yellow wavy lines in the compiler, not subject settings.

**Comment by dbaeumer** [comment]
@Davidliking could you please provide steps or a GitHub repository I can clone that demos what you are seeing. Having good reproducible steps is a prerequisite to efficiently act on an issue.

**Comment by Davidliking** [comment]
"if (!utils.isNullOrEmpty(typeID) || typeID== "") {
     searchParams.typeID= typeID;
 }"
or
"if (typeID!= "") {
     searchParams.typeID= typeID;
 }"
You can try these two code snippets in the compiler.

**Comment by dbaeumer** [comment]
Trying those actually produces a reasonable result for me:

<img width="452" alt="capture" src="https://user-images.githubusercontent.com/1931590/60798083-c3820d00-a170-11e9-8c09-978caa7bc392.png">


This is why it is important that you provide me with a GitHub repository I can clone that demos what you are seeing. Otherwise we will never look at the same setup.

**Comment by Davidliking** [comment]
Sorry, the details can not be released, because it will involve confidential company content, I think my description is very clear, just read the code screenshot you released, I seem to think of a solution, if possible, I will put the solution under the problem. Thank you for your support.

**Comment by dbaeumer** [comment]
What do you think should be different in my screen shot? the two red squiggles are there because my linter rules require `===` and `!==`.

**Comment by Davidliking** [comment]
Two red wavy lines seem to be the effect of your eslint prompt
![A3LV4)LY7)DK2P~FHL5K{`4](https://user-images.githubusercontent.com/28680808/60799177-3f964800-a1a5-11e9-912b-222483c3017d.png)

**Comment by dbaeumer** [comment]
What is the exact error of those?
