### ISSUE TITLE
Autodetect and propose working directories in mono repositories

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-eslint#708]
See https://github.com/microsoft/vscode-eslint/issues/696#issuecomment-509036017

We could add a command that tries to auto-detect working directories in monorepros and propose a corresponding configuration.

**Comment by MAPESO** [comment]
@dbaeumer This problem is not presented in versions before to **6.x.x**. I am aware that version 6 of eslint handled differently the way the plugin behaves by treating the installation locally. I would really love to know why this problem is not presented in version 5 :)

**Comment by dbaeumer** [comment]
This got addressed. There is now a setting: `[{ "mode": "auto" }]`
