### ISSUE TITLE
Quick Fix menu options are not working

### ISSUE THREAD

**Issue by MuhammadJamaluddin** [microsoft/vscode-eslint#710]
Issue Type: <b>Bug</b>

Install the ESlint extension & Airbnb linting style guide & then try to use any of the actions listed in the "Quick Fix" menu...

Extension version: 1.9.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
This is a know VS Code issue and will be fixed there for the next recovery build.

**Comment by MuhammadJamaluddin** [comment]
When would that be?

**Comment by dbaeumer** [comment]
Soon.

**Comment by DesignBySite** [comment]
I have been affected by this as well. individual quick fix option does not work, but if there are repeat instances of an error, it will apply the fix if I select the "Fix all ...". Is it possible to revert back to a previous version of VS code installation on my machine? Or when will the next build be released that resolves this issue?
