### ISSUE TITLE
Add option for delay 

### ISSUE THREAD

**Issue by SHxKM** [microsoft/vscode-eslint#711]
My proposal is to implement one of the following options: 

A) _don't_ display any warnings (and possibly errors) in the editor, but *do* fix those on save.

or:

B) Add an option to add a time delay between the last character typed, and the appearance of warnings/errors

or:

C) Add an option to only display warnings and errors on save

A, B, C all solve the same problem: For `.vue` files for example, the editor is instantly filled with warnings/errors as soon as I open a new `<div>` tag because it's already recognizing a few rules that are broken with this temporary state. This is aesthetically unpleasant, and honestly sometimes distressing to see over and over again.

Setting `eslint.quiet: true` hides the warnings, but also ignores them, which means they aren't fixed on save.

Would this be complicated to implement? am I missing some setting?

**Comment by dbaeumer** [comment]
Sounds like a dup of https://github.com/microsoft/vscode-eslint/issues/655

**Comment by SHxKM** [comment]
@dbaeumer fair enough. I thought the other issue wasn't as detailed and wasn't even sure I was talking about the same as the other poster. I will the contents there to augment.
