### ISSUE TITLE
Use file location for `.eslintrc.js` resolution

### ISSUE THREAD

**Issue by buschtoens** [microsoft/vscode-eslint#712]
It seems that when using multiple `.eslintrc.js` files throughout the workspace (of which some may use `root: true`), vscode-eslint doesn't follow the same [resolution algorithm that eslint itself uses](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy).

It seems that `eslint.workingDirectories` could be a (very inelegant and manual) solution to this problem, by specifying every directory, that has an `.eslintrc.js` file as a working directory.

Is there no way for vscode-eslint to "just" follow the same resolution logic that eslint uses? Am I doing something wrong?

**Comment by buschtoens** [comment]
Hm, I'm having trouble reproducing this in a fresh repo... 🤔
I'll investigate further.

**Comment by dbaeumer** [comment]
I actually should since the extension uses the eslint npm module. Best to understand what goes wrong would be a GitHub repository I can clone that demos the behaviour.

**Comment by buschtoens** [comment]
> a GitHub repository I can clone that demos the behaviour.

That's what I was trying to set up, but so far I couldn't reproduce the issue. 😅
I'll give it another go in the next days though.

Thanks for replying already!

**Comment by Lighttree** [comment]
I have same issue in newly created project.

With following dependencies:

```json
"dependencies": {
    "react": "^16.8.6"
},
"devDependencies": {
    "eslint": "^6.0.1",
    "eslint-config-workhuman-react": "^1.0.2",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.2",
    "eslint-plugin-react-hooks": "^1.6.1",
    "prettier": "^1.18.2"
}
```

and following folder structure:

```sh
| my-project-parent ## Actual root folder where Git initialized
      | my-project ## Folder with `JS` project actually created
      | -- node_modules
      | -- src
      | -- ## ... other folders ...
      | -- .eslintrc
      | -- package.json
| .gitignore
| README.md
```

If I use `my-project-parent` as `WORKSPACE ROOT` I start to have issues with `ESLint` in `Output` and it throws issues about missing `modules`.

In case I open `my-project` as `WORKSPACE ROOT` it works fine.

Log:

```sh
[Info  - 4:02:47 PM] ESLint server stopped.
[Info  - 4:02:50 PM] ESLint server running in node v10.11.0
[Info  - 4:02:50 PM] ESLint server is running.
[Info  - 4:02:55 PM] ESLint library loaded from: c:\Development\Projects\celebrations-ui-parent\celebrations\node_modules\eslint\lib\api.js
[Error - 4:02:55 PM] 
Failed to load plugin 'import' declared in 'celebrations\.eslintrc.js » eslint-config-workhuman-react » eslint-config-workhuman-base': Cannot find module 'eslint-plugin-import'
Require stack:
- C:\Development\Projects\celebrations-ui-parent\__placeholder__.js
Referenced from: C:\Development\Projects\celebrations-ui-parent\celebrations\node_modules\eslint-config-workhuman-base\lib\base.js
Happened while validating C:\Development\Projects\celebrations-ui-parent\celebrations\src\App.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-import' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-import' isn't installed correctly.

Consider running eslint --debug C:\Development\Projects\celebrations-ui-parent\celebrations\src\App.js from a terminal to obtain a trace about the configuration files used.
```

It also works fine if I run following command from folder where `.eslintrc` file exists:
```sh
./node_modules/.bin/eslint src/App.js --debug
```

**Comment by Kosta-Github** [comment]
This is a test repo similar to the setup described by @Lighttree : https://github.com/Kosta-Github/eslint-vscode-issue

The contained `REAMDE.md` contains some more infos for running `eslint --debug` in the different folders.

The quick summary is:

Note that the `vscode` plugin is already detecting the correct (i.e., local) `eslint` instance to use:

```text
[Info  - 9:52:22 AM] ESLint library loaded from: /Users/kosta/devel/misc/eslint-vscode-issue/nested/node_modules/eslint/lib/api.js
```

As well as the correct `eslint config` file (i.e., `nested/.eslintrc.json`):

```text
Failed to load plugin 'promise' declared in 'nested/.eslintrc.json': Cannot find module 'eslint-plugin-promise'
```

What seems to be missing is that the `module`/`plugin` search path should be extended to include the `node_modules` folder the `eslint` instance is located in (i.e., `/Users/kosta/devel/misc/eslint-vscode-issue/nested/node_modules`).

I would really love to get this somehow detected automatically, since I have 10s (close to 100) projects setup like this and I don't want to manually configure them for `vscode-eslint` usage...

**Comment by dlferro** [comment]
Another example where this wouldn't work since it doesn't follow the native eslint resolution would be

```
| Project
  | folder 1
    | -- .eslintrc *root:true
    | -- index.js
  | folder 2
    | -- .eslintrc *root:true
    | -- index.js
```

**Comment by buschtoens** [comment]
I think most issues can be traced back to an incorrect `process.cwd()`.

I have a [shareable config](https://github.com/ClarkSource/eslint-config/tree/master/packages/eslint-config-ember-order-imports) that looks up the package name from the `package.json` of the project, to configure [`import-helper/order-imports`](https://github.com/Tibfib/eslint-plugin-import-helpers/blob/master/docs/rules/order-imports.md). It basically does this:

```js
const APP_NAME = require(`${process.cwd()}/package.json`).name;

module.exports = {
  plugins: ['import-helpers'],
  rules: {
    'import-helpers/order-imports': [
      'error',
      {
        newlinesBetween: 'always',
        groups: [
          // ...
          [`/^${APP_NAME}\\//`],
          // ...
        ],
        alphabetize: { order: 'asc', ignoreCase: true }
      }
    ]
  }
};
```

I have a monorepo with a `package.json` at the root of the repository, that basically looks like this:

```js
// ./package.json
{
  "name": "my-monorepo",
  "workspaces": [
    "packages/*"
  ]
}
```

And then in the package where I use my shareable `import-helper/order-imports` config, I basically got this `package.json`:

```js
// ./packages/some-app/package.json
{
  "name": "some-app",
  "scripts": {
    "lint:js": "eslint --ext ts,js ."
  },
  "devDependencies": {
    "@clark/eslint-config-ember": "^1.8.0",
    "eslint": "^6.1.0"
  }
}
```

And this `.eslintrc.js`:

```js
// ./packages/some-app/.eslintrc.js
module.exports = {
  root: true,
  extends: '@clark/eslint-config-ember'
};
```

When I run `yarn lint:js` somewhere inside the `some-app` package (can even be a subdirectory of `some-app`), the `process.cwd()` is `./packages/some-app`.

The `require()` shown in the first code snippet thus works like this:

```js
process.cwd(); // => ./packages/some-app
const APP_NAME = require(`${process.cwd()}/package.json`).name; // => 'some-app'
```

When `vscode-eslint` runs the litner for this any file inside the `some-app`, package, the `process.cwd()` is `./` (the repo root).

The `require()` shown in the first code snippet thus works like this:

```js
process.cwd(); // => ./
const APP_NAME = require(`${process.cwd()}/package.json`).name; // => 'my-monorepo'
```

I think `vscode-eslint` should do two things:

When a file is linted, traverse up the directory hierarchy and read all `package.json` files on the way. Once a `package.json` that lists `eslint` as a dependency is found, use it's directory as the `process.cwd()` and also resolve `eslint` relative to this directory. As an added bonus, this allows using different versions of `eslint` in a monorepo, even though I would generally consider this to be an anti-pattern.

**Comment by buschtoens** [comment]
@dbaeumer I can provide a reproduction repo, if it helps! What is your opinion on my suggestion above?

**Comment by dbaeumer** [comment]
@buschtoens I am actually against such an automatic mechanism. Major reasons are:

- we might do something work and then the user has no control over this
- it makes the extension `duplicate` resolving code from eslint which I so far stayed away from. If eslint for some reason changes I need to rewrite this.

I am also pretty sure that if in your example you validate a file in one of these folders from the root workspace folder using the eslint command in a terminal it will fail in the same way as the extension does. ESlint is very cwd sensitive :-)

However I do see the problem that setting up these working directories is sometimes painful in mono repros. So having a command that infers them and writes them to the settings.json after having the user look at them is something I think is definitely useful. 

Might be a good opportunity for a PR.

**Comment by buschtoens** [comment]
FWIW I was able to fix my config by extending [`import-helper/order-imports`](https://github.com/Tibfib/eslint-plugin-import-helpers/blob/master/docs/rules/order-imports.md) as [`eslint-plugin-import-helpers-with-package`](https://github.com/ClarkSource/eslint-config/blob/9aba9c2204db6e1c62af8e20533254e33c8f5a21/packages/eslint-plugin-import-helpers-with-package/rules/order-imports.ts), which can now understand the `package` keyword. It's substituted with the `name` property of the first sibling or ancestor `package.json`.

**Comment by dbaeumer** [comment]
@buschtoens cool.

**Comment by buschtoens** [comment]
Whoops, didn't mean to close this issue. GitHub did this for me, since I referenced this as `Fixes` in a PR in a private repo.

If any of the other participants feel that this should be reopened, I can do so. But at least for me, the issue is solved for now.
