### ISSUE TITLE
[Feature request] suggest a fix if eslint npm package isn't installed.

### ISSUE THREAD

**Issue by tomerep** [microsoft/vscode-eslint#716]
Problem description:
1. open VSCode and install vscode-eslint extension.
2. Create / Import a project.
3. Open js file.

Actual: the user gets an error message saying that eslint package isn't installed.

Proposal: To display a message with 2 buttons: 'npm install' and 'Disable Eslint'.

**Comment by dbaeumer** [comment]
There is a command `Disable ESLint`. An npm install would be helpful as well.

Good candidate for a PR :-)

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
