### ISSUE TITLE
ESLint in VSCode shows errors that the command line ESLint does not

### ISSUE THREAD

**Issue by ThibaultVlacich** [microsoft/vscode-eslint#718]
I'm noticing an issue with ESLint in VisualStudio Code. As you can see in the following screenshots, I'm seeing errors in the editor that are not here when I'm testing the same file directly with the command line tool.

I feel like the issue is the due to the use of the "@" alias, that VueJS adds.

PS: I created a Vue project using Vue CLI, using the ESLint+AirBnb preset, and haven't made any custom change to the config.

![error1](https://user-images.githubusercontent.com/334940/61667914-9b9bb900-acdb-11e9-9602-1ffcc84e2f0f.png)
![error2](https://user-images.githubusercontent.com/334940/61667968-ba9a4b00-acdb-11e9-86b3-d746e6068e4a.png)

**Comment by dbaeumer** [comment]
@ThibaultVlacich when executing the command in the terminal are you doing this from the workspace folder or the client folder. If the second then you need to tell ESLint about your working directories (see the `eslint.workingDirectories` setting). I am pretty sure you see the error in the terminal as well if you validate the file from the root folder.

If not, can you please provide me with a GitHub repository I can clone that demos this.

**Comment by ThibaultVlacich** [comment]
You are right, I'm not seeing the error when I use the `client` folder as the root directory.
