### ISSUE TITLE
Parsing error: File 'tsconfig.json' not found - if project does not contain tsconfig.json in workspace root

### ISSUE THREAD

**Issue by joepio** [microsoft/vscode-eslint#722]
I have a project ([repo link](https://github.com/ontola/ori-search/)) that has two separate tsconfig files in non-root folders. When I open this project in VScode, the linter gives this error in every TS file:

```
Parsing error: File '/project-root/tsconfig.json' not found.
```

That path indeed does not link to an existing file, since it should look in a specific subdirectory of `project-root` .

Whenever I open one of the subfolders, the error goes away and the plugin functions as expected.

Possibly related to #691

**Comment by TylerR909** [comment]
I also just ran in to this in a yarn workspace.

```
/project
|-- tsconfig.json <-- ESLint resolves to, but says doesn't exist
|-- packages/
|    |-- first/
|      |-- tsconfig.json <-- ESLint pointing to this, extends base config
|      |-- .eslintrc.js
|    |-- second/
|      |-- tsconfig.json
```

Trying to plug in ESLint in `first/` right now. The package `tsconfig.json`s both extend the root `tsconfig.json`. The `.eslintrc.js` file has this set...

```js
  parserOptions: {
    project: './tsconfig.json',
  },
```

But it looks like the VSCode plugin is resolving that to `project/tsconfig.json` according to the error. If I set `project: './packages/first/tsconfig.json` then VSCode starts reporting all the errors but the command line is now reporting `project/packages/first/packages/first/tsconfig.json` is an error (shocker, I know).

Interesting note: The `tsconfig.json` that it's reporting isn't there... totally is. VSCode Tooltip on any file within `packages/first/*`:
```
Parsing error: File '/Users/{me}/Projects/{project-root}/tsconfig.json' not found. eslint
```

I'm going package by package to start, but planning on hoisting stuff to the root of the project and extending eslintrc files from a base. The plan right now is for every packages' eslintrc to point to its `tsconfig.json` project. May jump the gun on those plans a bit to see if it starts working with a root-level eslintrc.

**Comment by cyberixae** [comment]
I was able to fix the issue in my case by removing parserOptions entirely. I realise this may not work for everyone but for me it seemed fine.

**Comment by TylerR909** [comment]
For me the error resolved when I got started on integrating ESLint into a 2nd package. At that point, yarn workspace hoisting took over and pulled ESLint up to the root node_modules, VSCode ESLint Plugin could find the executable, and it started respecting nested .eslintrc files.

**Comment by TylerR909** [comment]
Sorta broke again. Yarn Workspaces stopped hoisting `eslint-plugin-prettier` even though it's used in two packages. `packages/server` and `packages/client` both use it and extend their common configs from the root of the project. The VSCode plugin is seeing `eslint-plugin-prettier` in the root config then instead of resolving it from `packages/*/.eslintrc.js` where it's used (and root=true for what it's worth), by searching `packages/*/node_modules/eslint-plugin-prettier`, the plugin is only searching `/node_modules/eslint-plugin-prettier` and since it's no longer being hoisted it's failing.

Over at the Yarn repo, since [this](https://github.com/yarnpkg/yarn/issues/1743) has turned into a crapshow, I just did a `cp -r packages/server/node_modules/eslint-plugin-prettier ./node_modules` to effectively manually hoist it and immediately the VSCode ESLint plugin started working and reporting all my warnings and errors.

But that'll stop working the second I `yarn install` again, and it won't work for the rest of my team unless they do that too.

**Comment by ErikHumphrey** [comment]
Also experiencing the same issue because our project has no tsconfig.json in the root directory. Is it possible to specify a custom path?

**Comment by ErikHumphrey** [comment]
Possibly can't be fixed until https://github.com/typescript-eslint/typescript-eslint/issues/251 is resolved (from #605)

**Comment by dbaeumer** [comment]
I am pretty sure that this is unrelated to the extension itself. 

@joepio what happens if you validate files in the front / server folder in a terminal using eslint command. Will that work?

**Comment by joepio** [comment]
> @joepio what happens if you validate files in the front / server folder in a terminal using eslint command. Will that work?

Running eslint in the `/front` subdirectory works just fine.

`eslint --ext .js,.jsx,.ts,.tsx ./src  `

**Comment by dbaeumer** [comment]
@joepio I mean running it in the workspace folder. Something like

`eslint --ext .js,.jsx,.ts,.tsx ./front/src`

Have you tried to add the following configuration to tell eslint what your working directories are:

```
  "eslint.workingDirectories": [
    { "directory": "front", "changeProcessCWD": true },
    { "directory": "server", "changeProcessCWD": true }
  ]

```

**Comment by joepio** [comment]
> @joepio I mean running it in the workspace folder. Something like
> 
> `eslint --ext .js,.jsx,.ts,.tsx ./front/src`

Does not seem to work:  `ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".`, which makes sense, since there is no `node_modules` folder with the plugin in that dir.

> Have you tried to add the following configuration to tell eslint what your working directories are:
> 
> ```
>   "eslint.workingDirectories": [
>     { "directory": "front", "changeProcessCWD": true },
>     { "directory": "server", "changeProcessCWD": true }
>   ]
> ```

This works! Nice, thanks!

**Comment by dbaeumer** [comment]
Closing the issue then.
