### ISSUE TITLE
Console escape characters show up in the error message

### ISSUE THREAD

**Issue by xsrvmy** [microsoft/vscode-eslint#723]
When the eslint error message contain console escape sequences such as color change, the sequence shows up in vscode's error message as raw text.

For example, a bold light blue word "Link" is showing up as `[1;96mLink[0m`.

Presumably the `--no-color` option need to be enabled. #460 is similar but for a different problem.

**Comment by dbaeumer** [comment]
The ESLint extension doesn't shell out to the eslint cmd. It uses the ESLint npm module directly which doesn't embed any ANSI codes. 

Are you using the babel-eslint parser which seems to embed this directly.
