### ISSUE TITLE
Checking is silently failing

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode-eslint#724]
I am experiencing no errors at all in my files, even when I intentionally break the rules. Linting with the CLI works fine, so I know there should be errors and warnings, but nothing appears. 

The errors raised by the `ts` compiler still do appear and the `lint whole folder` task is registered.

The problem is occurring in both JavaScript and TypeScript problems, and only started with a recent update (either to the extension or VSCode).

<details><summary>System Info</summary>

- Version: 1.37.0-insider (user setup)
- Commit: [microsoft/vscode/cf03ea3729dc37e439d724267ad29dc5840f903a](https://github.com/microsoft/vscode/commit/cf03ea3729dc37e439d724267ad29dc5840f903a)
- Date: 2019-07-30T07:15:22.972Z
- Electron: 4.2.7
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.15063
- Extension Version: 1.9.0

</details>

**Comment by mckernanin** [comment]
I am seeing the same issue. Here's a repo you can clone for an example. This does seem specific to remote WSL setup, as the same repo works fine on my mac. https://github.com/mckernanin/eve-mining-manager/

**Comment by dbaeumer** [comment]
@iansan5653 can you provide me with a GitHub repository I can clone that demos this. ESLint still works for me (even in a WSL setup).

**Comment by dbaeumer** [comment]
I can't clonse mckernanin/eve-mining-manager

**Comment by iansan5653** [comment]
@dbaeumer It wasn't linked to a specific project for me. I was able to fix it though with:
```bash
npm uninstall -G eslint
npm i -G eslint
```
Although I'm surprised that was necessary because `eslint` was installed locally as well.

**Comment by dbaeumer** [comment]
@iansan5653 sounds indeed wired. What might has changed with this is the version of ESLint (-> 6.1.0). 

I will close the issue. Please ping if you see this again or if you have additional information.
