### ISSUE TITLE
[Feature Request]: Toggle/Display ESLint Status in Statusbar 

### ISSUE THREAD

**Issue by AlexZeitler** [microsoft/vscode-eslint#730]
When migrating code bases it can be useful to disable ESLint at first because of too much squiggly red lines.
Sometimes then I forget to re-enable it again so it would be nice to have the status of ESLint displayed in the VS Code Status bar and also be able to enable/disable it by just clicking on it.

I can send a PR if you're willing to include it.

**Comment by dbaeumer** [comment]
Yes, PRs are always welcome. Couple of hints:

- this should be combined with `alwaysShowStatus` setting
- if this is true the status item could indicate that eslint is disabled for the current workspace.

**Comment by AlexZeitler** [comment]
Is there something else to do to display the status bar item?

![image](https://user-images.githubusercontent.com/287480/63127832-b1875b80-bfb3-11e9-979f-7fd6dd782277.png)

**Comment by dbaeumer** [comment]
Yes, since the item only shows if a server is running. If you want to indicate the non runnning additional code is necessary.

**Comment by dbaeumer** [comment]
A lot has change around the status bar item due to the execution confirmation dialog. I will close the issue. Feedback is welcome around the confirmation flow.
