### ISSUE TITLE
[Feature Request] A more friendly way to mark the "no-trailing-space" in the editor

### ISSUE THREAD

**Issue by semenov-k** [microsoft/vscode-eslint#731]
I have a bit confusing thing. 
![space](https://user-images.githubusercontent.com/16195166/63163431-c6f59780-c03e-11e9-90fa-f596ada12aa6.png)
When I see an error like in the picture above, I cannot say what exactly the type of error I have. It seems like `Unexpected token` error. I should go to the "PROBLEMS" tab and find that's `eslint(no-trailing-space)` error. But if to mark the "trailing space", I will see that I should remove it. Like in the picture below.
![space_fixed](https://user-images.githubusercontent.com/16195166/63163750-c14c8180-c03f-11e9-85f2-ff4835ce95c1.png)

**Comment by dbaeumer** [comment]
Currently the ESLint extension doesn't modify the error ranges provided by eslint itself. However I see that for this particular problem moving it might be helpful although I could argue that eslint itself could profit from this as well. Have you talked to the eslint folks about this.

**Comment by semenov-k** [comment]
@dbaeumer, not yet. I will write to them.

**Comment by golopot** [comment]
I believe this is fixed by https://github.com/eslint/eslint/pull/12477.

**Comment by dbaeumer** [comment]
@golopot thanks. Will close the issue as upstream then.
