### ISSUE TITLE
Adding resolvePluginsRelativeTo in eslint.options

### ISSUE THREAD

**Issue by ehellman** [microsoft/vscode-eslint#734]
We have our build system split into 2 parts for various reasons. But we'd like to keep everything related to ESLint in the buildsystem package instead of spreading it out. This is our current setup for `eslint@6.2.0`:

```
/
/.vscode
../settings.json
/buildsystem
../.eslintrc.js
../package.json <-- contains ESLint, plugins etc
/src
../.eslintrc.js <-- extends ../buildsystem/.eslintrc.js
../package.json  <-- has no ESLint, but uses a lint task which points to node_modules in ~/buildsystem
```

The lint task in package.json uses `-resolve-plugins-relative-to` in the command to make it work. Is it possible to do something to make this work from the VS Code extension?

Our current `.vscode/settings.json":

```json
{
  "editor.formatOnSave": true,
  "eslint.alwaysShowStatus": true,
  "eslint.autoFixOnSave": true,
  "eslint.nodePath": "./buildsystem/node_modules",
  "eslint.enable": true,
  "eslint.workingDirectories": ["./buildsystem", "./src"],
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    { "language": "typescript", "autoFix": true },
    { "language": "typescriptreact", "autoFix": true }
  ],
  "prettier.eslintIntegration": true
}
```

The only way I've gotten it to work is to add ESLint and all our plugins to the `src/package.json` as well. It is possible to point to local versions of the packages to avoid too much duplication but it would be super smooth if we could do `resolvePluginsRelativeTo` in the VS Code settings instead.

```json
{
  "eslint.options": {
    "resolvePluginsRelativeTo": "~/buildsystem/node_modules"
  }
}
```

**Comment by dbaeumer** [comment]
The extension has such a settting. It is historically called `eslint.nodePath` and works like the NODE_PATH environment variable.
