### ISSUE TITLE
resolve %appdata% from vs code settings properly

### ISSUE THREAD

**Issue by jekusz** [microsoft/vscode-eslint#737]
Having a vscode setting as follows:
```
"eslint.options": {
		"resolvePluginsRelativeTo":"%appdata%\\npm\\node_modules"
	},
```
gives this error:
```
Failed to load plugin 'react' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-react'
Require stack:
- C:\Users\userDir\Documents\dir\dir\%appdata%\npm\node_modules\__placeholder__.js
```
If the path in the settings file is provided absolute (i.e. C:\\...) then everything works fine which leads to the belief that %appdata% doesn't get resolved as it should.

**Comment by dbaeumer** [comment]
@jekusz please file the issue against VS Code directly. This should be handle there since the ESLint extension calls VS Code API to resolve a setting.

**Comment by tHBp** [comment]
@dbaeumer According to [this comment](https://github.com/microsoft/vscode/issues/2809#issuecomment-396842807), extensions are supposed to resolve variables. For example, [python extension](https://github.com/Microsoft/vscode-python) does this.

**Comment by dbaeumer** [comment]
@tHBp I added this https://github.com/microsoft/vscode/issues/2809#issuecomment-525675543 to convince them to add it. Let's see and wait.
