### ISSUE TITLE
Plugin locks *.asar files

### ISSUE THREAD

**Issue by thomassuckow** [microsoft/vscode-eslint#739]
This plugin seems to lock *.asar files (As identified with LockHunter) in the project output directories despite being in .gitignore and not being an extension eslint should be scanning.

I suspect this plugin is traversing directories looking for files and because vscode is an electron app, *.asar files are handled "unusually". I believe they appear as directories to the normal node.js file manipulation functions.

**Comment by dbaeumer** [comment]
@bpasero do you know if electron scans for ASAR's in the working directory (the ESLint server starts on the folder directory).

@thomassuckow you can work around this for now using the `eslint.runtime` setting and pointing it to a install node version.

**Comment by bpasero** [comment]
I doubt electron would scan, but for sure any fs operation that we do can result in ASAR code being executed because we do not disable ASAR every since we use it for our node modules (@alexandrudima to confirm).

**Comment by dbaeumer** [comment]
@bpasero do you know if I can disable ASAR support for the spawned server. I am sure I don't need it.

**Comment by bpasero** [comment]
@dbaeumer https://electronjs.org/docs/api/environment-variables#electron_no_asar

**Comment by dbaeumer** [comment]
@bpasero thanks.

**Comment by dbaeumer** [comment]
Fix in VS Code LSP libraries which actually launch the server.

**Comment by thomassuckow** [comment]
For reference:
https://github.com/microsoft/vscode-languageserver-node/commit/1e7962e4b6484c66e784af1c9fc343a630872db0
