### ISSUE TITLE
Definition for rule not found

### ISSUE THREAD

**Issue by gong12339** [microsoft/vscode-eslint#742]
Hello there, I use custome rules on my repo, but it keeps reporting this error while I'm writing code. feels really annoying. Is there any way I can disable it or apply them to the current repo?  
![image](https://user-images.githubusercontent.com/16729152/63578664-89a38380-c5c3-11e9-9886-df5e723f1478.png) . 

I use command line eslint to check files like this . 
`npx eslint --rulesdir eslint_rules somefile.js`

**Comment by dbaeumer** [comment]
@gong12339 if this happens when using the command line (e.g. `npx eslint --rulesdir eslint_rules somefile.js`) then you need to report this against the eslint node module directly.

**Comment by gong12339** [comment]
emmmm. what I mean is I use `pre-commit` hooks  to `eslint --fix` all the staged file.but when I'm writing code, The plugin check the `.eslintrc` file and can't find my custome rule location.So it keep having this warning.It won't affect anything, but it's kinda annoying.

**Comment by dbaeumer** [comment]
@gong12339 can you provide me with a GitHub repository I can clone that demo's this?
