### ISSUE TITLE
extensions.map is not a function

### ISSUE THREAD

**Issue by stevemc4** [microsoft/vscode-eslint#743]
Hello there

As the title suggest, VSCode shows this error:
![Screenshot from 2019-08-27 23-22-47](https://user-images.githubusercontent.com/20576341/63789498-b20fe280-c921-11e9-8329-0f784097ee5b.png)

And the ESLint extension output giving me this:
![Screenshot from 2019-08-27 23-24-39](https://user-images.githubusercontent.com/20576341/63789636-f602e780-c921-11e9-9b75-6ec23bcc60e4.png)

The error only occurs on a new project with ESLint 6 installed (in my case, 6.2.2) since my company's project that uses ESLint 5.16 doesn't giving me this error.

Thank you!

**Comment by dbaeumer** [comment]
@stevemc4 this error comes from the ESlint library itself and I am pretty sure you see this as well if you validate the file in the terminal. Is this the case?
