### ISSUE TITLE
Need to press save multiple times to have the warning autofixed

### ISSUE THREAD

**Issue by jean-moldovan** [microsoft/vscode-eslint#744]
Hello!

I'm using vscode-eslint to autofix my vue files on save with the following setup:
```
    "eslint.autoFixOnSave": true,
    "eslint.validate": [
        "javascript",
        {
            "language": "vue",
            "autoFix": true
        }
    ]
```

I have this rule where multiple html attrs are not allowed on the same line. vscode-eslint identifies the issue correctly, although it does not fix it properly when I press save. After I press save file a couple more times it finally gets it right.

Please see the video attached:
![eslint](https://user-images.githubusercontent.com/3635352/63866048-49754400-c9bb-11e9-9237-05545079ccdd.gif)

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode-eslint/issues/154
