### ISSUE TITLE
Disabling of Eslint marks on the scrollbar 

### ISSUE THREAD

**Issue by ProHronus** [microsoft/vscode-eslint#746]
Is it possible to disable the error indicators on scrollbar (color dots)?

**Comment by dbaeumer** [comment]
@alexandrudima is there a setting for this in VS Code?

**Comment by ProHronus** [comment]
The problem is that I did not find any settings for this either in the VScode or in the ESlint plugin. Can you, please, guide how to achieve it?

**Comment by dbaeumer** [comment]
@ProHronus to my knowledge there is none in VS Code. Since this can't be controlled via the ESLint extension please file an issue against VS Code to get this feature.

**Comment by ProHronus** [comment]
Thank you, @dbaeumer !
