### ISSUE TITLE
Apply two eslintrc.json files for one workspace, possible?

### ISSUE THREAD

**Issue by iniatse** [microsoft/vscode-eslint#747]
I have the following folder strucure:

```
branches
|---.vscode
	|---settings.json
|---dev-branch
	|---node_modules
	|---src
		|---lib
			|---Tools.build.js
			|---Tools.src.js
		|---index.js
	|---test
		|---dependencies
		|---html
			|---js
		|---js
		|---.eslintignore
		|---.eslintrc.json
		|---automatedTest.test.js
		|---automatedTestWithinBrowser.test.js
		|---indexForManualTesting.html
	|---.eslintignore
	|---.eslintrc.json
	|---package-lock.json
	|---package.json
	|---README.MD
```

`.vscode/settings.json` does look like this:

```
{
	"eslint.workingDirectories": ["./", "./branches/dev-branch", "./branches/dev-branch/test"]
}
```

`branches/dev-branch/.eslintrc.json` looks like this:

```
{
    "env": {
				"browser": true,
        "commonjs": true,
        "es6": false
    },
    "parserOptions": {
        "ecmaVersion": 6
    },
    "rules": {
        "indent": [
            "error",
						"tab",
						{ "SwitchCase": 1 }
				],
				"no-mixed-spaces-and-tabs":"error",
        "linebreak-style": [
            "error",
            "windows"
        ],
        "quotes": [
            "error",
            "single",
						{
							"avoidEscape": true,
							"allowTemplateLiterals": true
						}
        ],
        "semi": [
            "error",
            "always"
				],
				"no-param-reassign": [
					"error", 
					{ "props": false }
				]
    }
}
```

`branches/dev-branch/.eslintignore` looks like this:

```
# path/to/project/root/.eslintignore
# /node_modules/* and /bower_components/* in the project root are ignored by default

test/**/*.test.js
/**/*.build.js
```

`branches/dev-branch/test/.eslintrc.json` looks like this:

```
{
		"env": {
			"node": true
		},
		"globals": {
		
		},
		"parserOptions": {
			"ecmaVersion": 8
		},
    "rules": {
        "indent": [
            "error",
						"tab",
						{ "SwitchCase": 1 }
				],
				"no-mixed-spaces-and-tabs":"error",
        "linebreak-style": [
            "error",
            "windows"
				],
				"quotes": [
						"error",
						"single",
						{
							"avoidEscape": true,
							"allowTemplateLiterals": true
						}
				],
        "semi": [
            "error",
            "always"
				],
				"no-param-reassign": [
					"error", 
					{ "props": false }
				]
    }
}
```

`branches/dev-branch/test/.eslintignore` looks like this:

```
# path/to/project/root/.eslintignore
# /node_modules/* and /bower_components/* in the project root are ignored by default

**/*.js
!**/*.test.js
```

As you can see I need different configurations, because the test is written in node and the other code runs in the browser, even some code within `test/` runs in the browser in particular `test/js` and `test/html/js`.

Now the problem is that `branches/dev-branch/test/.eslintrc.json` has no business with `*.js` files, because they are ignored within `branches/dev-branch/test/.eslintignore`. But why do `branches/dev-branch/.eslintrc.json`s rules not apply for my `.js` files in `branches/dev-branch/test/js/`? It seems to me that one workspace an only respects one `.eslintrc.json` (the nearest one) and everything else around is is void. This is a directory-structure which is fairly common, is there any way to support it correctly? I currently use the workaround of copying `branches/dev-branch/.eslintrc.json` and `branches/dev-branch/.eslintignore` into both `branches/dev-branch/test/js` and `branches/dev-branch/test/html` (which is kind of weird and redundant) and instead of the above `.vscode/settings,json` I use this one:

```
{
	"eslint.workingDirectories": ["./", "./branches/dev-branch", "./branches/dev-branch/test", "./branches/dev-branch/test/js", "./branches/dev-branch/test/html"]
}
```

When I want to lint my whole folder I use the following to `npm` scripts and that works perfectly fine and I do not need four config files, but only as expected two config files:
```

"scripts": {
		"eslint": "eslint \"./**/*.js\" --ignore-path \".eslintignore\"",
		"eslintNodeTestCode": "eslint \"./test/**/*.test.js\" --config \"test/.eslintrc.json\" --ignore-path \"test/.eslintignore\"",
}
```

I digged into the documentation, but I could not find anything to support this IMO fairly common folder-structure, because many programs will have a test in them and therefore need a `.eslintrc.json` specific for nodejs and the test also may have folders in it with `.js` files which are executed within the browser (for example GUI-tests or in case you want to execute the test within a browser and not nodejs, for example via puppeteer) and therefore for these ones a `.eslintrc.json` should apply which has specific configuration for browsers.

**Comment by dbaeumer** [comment]
`.eslintignore` files are not resolve relative to the file validated. They are resolve relative to the working directory. This is native ESLint behavior. To make this work you need to tell the ESlint extension to do a change directory by using the following syntax for the workind directory entries:

```
   { "directory": "./branches/dev-branch", "changeProcessCWD": true }
```


If this doesn't solve your problem can you please provide me with a GitHub repository I can clone that demos the problem you are seeing.

**Comment by iniatse** [comment]
[https://github.com/iniatse/vscode-eslint-issue747](https://github.com/iniatse/vscode-eslint-issue747)

In the ´README.MD` I try to describe what the problems are and what I would expect and why I would expect it to work like that.

Thank you very much.

**Comment by iniatse** [comment]
What I see is that the concept is missing some points in order for this to work. 

At the moment eslintrc and eslintignore files have no connection. When they live within the same folder there should be a connection between them as follows. When a file is linted and it is ignored within the next eslintignore upwards, then the eslintrc on the level or in other words in the same folder should be void and so on when traversing the parents. When it is not ignored within the eslintignore file then do what is corrently doing. Without that you will always receive unintended behaviour by the user who does not know the exact interals. It is possible to work without that concept with this extension, but more eslintrc and eslintignore files are required then with that concept implemented. Without that concept the vscode-eslint extension is not as powerful as the cli API, **because you need more files to achieve the same result**.

**Comment by dpkirchner** [comment]
> It is ok that the internal logic traverses upwards, but it should support the top down approach via the concept I mentioned above.

Do you mean that it should already support the top down approach or that it should at some point in the future?

**Comment by dbaeumer** [comment]
The eslint extension doesn't implement any lookup algorithm itself. It uses the standard eslint npm module and its provided API. So all lookup behaviour are the same for running eslint in the terminal and running eslint inside the VS Code extension.

The only  thing that you need to keep in mind is that when executing eslint in a terminal and you do a change directory into a sub directory of the workspace folder to run eslint you need to configure these directories in the eslint extension using the `eslint.workingDirectories` setting as described in this comment https://github.com/microsoft/vscode-eslint/issues/747#issuecomment-527617388

@iniatse are you sure this works in the terminal from the workspace folder directory for you? I tried your provided example but it is not self contained (cloning and running npm install don't install any eslint).

What I did notice is that your setting definitelly need to be:

```
	"eslint.workingDirectories": [
		{ "directory": "./branches/dev-branch", "changeProcessCWD": true },
		{ "directory": "./branches/dev-branch/test", "changeProcessCWD": true}
	]
```

**Comment by iniatse** [comment]
Can you please not close a issue after 2 days... I'm busy until next month at the moment. I will respond as soon as I can.
