### ISSUE TITLE
IE11 support?

### ISSUE THREAD

**Issue by iniatse** [microsoft/vscode-eslint#748]
Hello,

my `eslintrc.json` looks like this:

```
{
    "env": {
				"browser": true,
        "commonjs": true,
        "es6": false
    },
    "parserOptions": {
        "ecmaVersion": 5
    },
    "rules": {
        "indent": [
            "error",
						"tab",
						{ "SwitchCase": 1 }
				],
				"no-mixed-spaces-and-tabs":"error",
        "linebreak-style": [
            "error",
            "windows"
        ],
        "quotes": [
            "error",
            "single",
						{
							"avoidEscape": true,
							"allowTemplateLiterals": true
						}
        ],
        "semi": [
            "error",
            "always"
				],
				"no-param-reassign": [
					"error", 
					{ "props": false }
				]
    }
}
```

Now IE11 supports es5 but also some keywords like `let` and `const` can be used within ie11. Problem is eslint will throw an error for these two keywords, when 

"parserOptions": {
        "ecmaVersion": 5
}

is set. 

Obviously I do not want to set `"ecmaVersion"` to `6`, because I only need to support IE11. What do do now? I could not find any plugin or so. Why do I even need a plugin for this, does eslint only adhere to the spec but does not care about what actually is implemented within browsers? Is there anything I can do that is not setting `"ecmaVersion"` to `6`?

**Comment by dbaeumer** [comment]
@iniatse please open the issue against [ESLint](https://github.com/eslint/eslint) directly. The VS Code extension reuses the linter code from there.
