### ISSUE TITLE
autoFix doesn't work with markdown files

### ISSUE THREAD

**Issue by chrisdothtml** [microsoft/vscode-eslint#749]
eslint **v6.2.2**
vscode **v1.37.1**
vscode-eslint **v1.9.1**

Repro repo [here](https://github.com/chrisdothtml/vscode-eslint-749)

**Comment by dbaeumer** [comment]
You need to tell the extension to accept auto fixes from the markdown plugin. Simply use the following line in the validate setting: `{ "language": "markdown", "autoFix": true }`
