### ISSUE TITLE
Cannot lint anything under node_modules, even if excluded in .eslintignore

### ISSUE THREAD

**Issue by icantgetittowork123** [microsoft/vscode-eslint#751]
Hi,

I want to exclude 1-2 files under node_modules (using npm link for local development) so that if someone navigates to them the eslint plugin highlights problem areas. If I add files to the .eslintignore file (!node_modules/blah/blah.js) it seems to work for eslint itself, but I don't see anything happening inside of the vscode editor.

**Comment by dbaeumer** [comment]
Interestingly I can only get this working in a terminal if I put the following into the `.eslintignore` file:

```
!node_modules/*
```

If I put a specific file in there (e.g. `!node_modules/cli-width/index.js`) and validate the file on the command line using `.\node_modules\.bin\eslint .\node_modules\cli-width\index.js` I get

```
Playgrounds\bugs\eslint\751> .\node_modules\.bin\eslint .\node_modules\cli-width\index.js

C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\751\node_modules\cli-width\index.js
  0:0  warning  File ignored by default. Use "--ignore-pattern '!node_modules/*'" to override

✖ 1 problem (0 errors, 1 warning)
```

@icantgetittowork123 can you provide me with a GitHub repository I can clone that demos that you have a single file in `eslintignore` and eslint works in the terminal but not in the extensions?
