### ISSUE TITLE
Consider adding a feature to not show warnings for specific rules

### ISSUE THREAD

**Issue by gregtatum** [microsoft/vscode-eslint#755]
I work on a codebase where I am not in control of the eslint rules, and we have linting running during hooks to autofix errors. I would like to be able to disable showing errors for certain rules, without modifying the eslint configuration. Specifically my use case is that these rules are not helpful to show errors on while I'm writing new code, but are useful for when I'm committing and pushing to repos where I have hooks installed.

The Atom eslint plugin has this feature under:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/1588648/64961662-a0a06300-d85b-11e9-96f5-270ed3363bd6.png">

For instance, with Prettier, it auto-fixes on save. So almost everything I type has red squigglies around it until I save, which is just noise and not helping me find real linting issues.

**Comment by dbaeumer** [comment]
I will fold this issue with https://github.com/microsoft/vscode-eslint/issues/655.
