### ISSUE TITLE
Irrational "irregular whitespace not allowed"

### ISSUE THREAD

**Issue by torava** [microsoft/vscode-eslint#756]
Issue Type: <b>Bug</b>

Irregular whitespace not allowed might show up with no reason in totally well formed expression like "asd = 1" or "foo || bar". It appears only on one side. When I rewrite the whitespace, the error disappears.

Extension version: 1.9.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@torava does this also occur when running eslint in the terminal?

**Comment by lcospain** [comment]
Hi, I am also encountering this issue in VsCode since some months and can confirm running the eslint cli tool alone also trigger this error.

**Comment by dbaeumer** [comment]
@lcospain thanks. I will close the issue then since it is nothing that should be fixed in the VS Code extension. As anyone reported this to the eslint itself?
