### ISSUE TITLE
eslint.executeAutofix shortcut not working in typescript files

### ISSUE THREAD

**Issue by inferusvv** [microsoft/vscode-eslint#757]
I configured **Option+F** shortcut to run `eslint.executeAutofix` command (Mac OS). It works fine in javascript and javascriptreact files. But if I open typescript/typescriptreact then nothing happens. But errors are underlined with red line which means that ESLint works fine in this type of files. I have this in my **settings.json** file:

```
"eslint.validate": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact"
    ],
```

VSCode Version: 1.38.1
ESLint Plugin version: 1.9.1

**Comment by dbaeumer** [comment]
Autofix support for TS is not enabled by default since there were problems in the past. You need to do:

```
"eslint.validate": [ { "language": "typescript", "autoFix": true } ]
```
