### ISSUE TITLE
"Fix all auto-fixable problems" does not seem to do anything

### ISSUE THREAD

**Issue by Thorocaine** [microsoft/vscode-eslint#760]
I am trying vscode-eslint plugin in VS Code.

I took a file (typescript) that is formatted incorrectly, and I ran "Fix all auto-fixable problems", and nothing happened.

To make sure this isn't a problem with ESLint I run
`node_modules/.bin/eslint src/Path/File.ts --fix`

This works as expected, and the file is reformatted.

**Comment by dbaeumer** [comment]
@Thorocaine auto fix is not enabled by default for TypeScript since there were cases in the past that it caused problems. To enable it do
```
"eslint.validate": [ { "language": "typescript", "autoFix": true } ]
```

**Comment by Thorocaine** [comment]
Thank you, I missed that.
