### ISSUE TITLE
Plugin do not recover after correcting an erratic `.eslintrc`

### ISSUE THREAD

**Issue by golopot** [microsoft/vscode-eslint#761]
When I tweak `.eslintrc` and left `.eslintrc` in an erratic state (e.g. syntax error), this plugin will **not** recover after I correct the `.eslintrc`. Instead, a reload is needed to get the plugin working. I would expect the plugin to watch `.eslintrc` and recover when possible.

**Comment by dbaeumer** [comment]
This works for me using a .eslintrc.json file without problem. Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by golopot** [comment]
I cannot reproduce this. Probably a mistake by me. Sorry.
