### ISSUE TITLE
Disable rule for entire file places inserted comment above shebang

### ISSUE THREAD

**Issue by mrxdst** [microsoft/vscode-eslint#762]
The comment gets inserted like this:

```
/* eslint-disable no-unused-vars */
#!/usr/bin/env node

...rest of your code
```

The eslint rule should be inserted under the shebang.

vscode version: 1.38.1
eslint extension version: 1.9.1
eslint version: 6.4.0

**Comment by dbaeumer** [comment]
Agree.
