### ISSUE TITLE
`reportUnusedDisableDirectives` top-level property

### ISSUE THREAD

**Issue by milesj** [microsoft/vscode-eslint#763]
This property was added in ESLlint v6.3. It's currently erroring in VSCode when used:

```
Unexpected top-level property "reportUnusedDisableDirectives". Referenced from: ./.eslintrc.js. Please see the 'ESLint' output channel for details.
```

**Comment by dbaeumer** [comment]
@milesj does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by guilhermejcgois** [comment]
I have the same issue...

https://travis-ci.org/guilhermejcgois/gor-commit/builds/589981166
https://github.com/guilhermejcgois/gor-commit/tree/greenkeeper/eslint-config-xo-0.27.1

**Comment by guilhermejcgois** [comment]
@milesj I've updated eslint to >= 6.4 and the problem was solved to me.

```
gor-commit$ npm ls eslint
gor-commit@1.0.0 /mnt/c/Users/guijo/Projects/gorila/gh/gor-commit
└── UNMET PEER DEPENDENCY eslint@6.1.0

npm ERR! peer dep missing: eslint@>=6.4.0, required by eslint-config-xo@0.27.1
```

**Comment by milesj** [comment]
I was using v6.4 and it was happening. Let me double check I don't have dupe modules and get back.

**Comment by dbaeumer** [comment]
@milesj can you still reproduce this?

**Comment by milesj** [comment]
Sorry, I'm out of country for 2 weeks. Will have to report back after that.

**Comment by dbaeumer** [comment]
Thanks for letting me know.
