### ISSUE TITLE
ESLint fails to load config files

### ISSUE THREAD

**Issue by DragonOsman** [microsoft/vscode-eslint#765]
When I try to write JS code in VS Code, I get an ESLint error that says:
```
ESLint: Failed to load config "defaults/configurations/eslint" to extend from.  Referenced from: C:\Users\<name>\.eslintrc.  Please see the ESLint output channel for details
```
I need help on fixing this error.  Note: I don't know where to find the ESLint output channel.

**Comment by dbaeumer** [comment]
@DragonOsman does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
