### ISSUE TITLE
Allow specifying a subset of rules to be autofixed on save

### ISSUE THREAD

**Issue by pablobirukov** [microsoft/vscode-eslint#767]
With `eslint.autoFixOnSave` on, ESLint applies all the fixes to a file while I only need just few of them to be applied automatically and have ability to decide whether the rest is ignored or fixed via Quick Fix.

It might be achieved via supporting `boolean | string[]` as a value for `autoFixOnSave`, as it was done in older version of [TSLint plugin](https://github.com/microsoft/vscode-tslint/blob/1f23aa3ca1e14120db3bd7675532df26327927b1/tslint-server/src/tslintServer.ts#L28).

I'd be happy to send a PR if you consider this change useful

**Comment by dbaeumer** [comment]
@pablobirukov there was a long discussion about that feature here: https://github.com/microsoft/vscode-eslint/issues/208 and it got not implemented in favour of a solution that works in eslint itself even when executed in the terminal. See https://www.npmjs.com/package/eslint-plugin-no-autofix 

Would that work for you?

**Comment by pablobirukov** [comment]
@dbaeumer thanks for pointing me out, couldn't find the original issue.

I want _all_ rules to be autofixed once I run `eslint --fix` and a very few of them to be fixed while I edit a file.

Having namespaced (with `no-autofix/`)  rules names makes it impossible to maintain two separate configs.

For the moment being, I'm thinking of creating a pipeline for building and distributing `master`+https://github.com/microsoft/vscode-eslint/pull/325 in-house, as it's a stopper for our migration from TSLint

**Comment by dbaeumer** [comment]
@pablobirukov what exactly do you mean by editing a file: typing / saving ?

**Comment by pablobirukov** [comment]
@dbaeumer saving an opened file in VS Code

**Comment by pablobirukov** [comment]
@dbaeumer too bad, GitHub doesn't want on label's change. I already have made a straight fix (keep the list of edits, apply the ones that are listed under `autoFixOnSave`) and even published the forked plugin, which we use inside of my company

Please take a look at submitted PR #798

**Comment by dbaeumer** [comment]
@pablobirukov the PR has merge conflicts since the way how the fixes are computed change to fix other problems around auto fix (e.g. that basically not all fixable problems got fixed. See https://github.com/microsoft/vscode-eslint/issues/154). In addition the auto fix will migrate to a Code Action to support other wanted features. 

You approach will still be valid however it needs some different coding. The new method computing all fixes (this time it really computes all) is here: https://github.com/Microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1545

**Comment by pablobirukov** [comment]
@dbaeumer I'd love to adopt my changes.

However, this time I'm struggling with #600 in ext debug mode, hope to find a way to have it gone

**Comment by pablobirukov** [comment]
Oh, my, didn't notice [disabled `willSaveWaitUntil`](https://github.com/microsoft/vscode-eslint/commit/861931b0e0f876d1aab7279fd663eeaac5a13661#diff-2cb5369b1fe91d5b13cb5a36ce8fdd58R816).

Now the fix seems straight, I just want to make sure I get it right.

The changes on save will be applied the same way they applied via code action. Which means that a new setting for specifying the subset of rules is to be added, as there is no way of passing a parameters from `setting.json` config

```js
"editor.codeActionsOnSave": {
    // it would be great to have ability to pass a list of rules
    "source.fixAll.eslint": true, // but the valued could be only boolean
},
```

So, instead, there will be either

```json
...
"eslint.autoFixSubsetOfRules": ["semi"],
... 
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": false,
    "source.fixSome.eslint": true,
},
```
or just
```json
...
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
},
```

Please correct me if I'm wrong

**Comment by dbaeumer** [comment]
@pablobirukov I think we can make this now a lot easier. Since auto fix on save now re-runs CLIEngine#executeOnText with `{ fix: true }` I would implement that as follows now:

- have a custom eslintrc* file for this
- add one setting to point to that custom file.
- use that file in https://github.com/Microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1516

This will give users the full flexibility of the eslintrc configuration without us duplicating thing in the eslint server implementation.

**Comment by pablobirukov** [comment]
@dbaeumer  I, personally, don't think this is a desirable behavior of the plugin.

I don’t see the right place for another eslintrc file. It does not belong to version control, as it’s an IDE-specific and even if we use the same IDE, some people prefer having different set of rules they want to be auto fixed.

Also, some people store their .vscode/ configs in non-project VCS and I can imagine such set up with an extra file being problematic

**Comment by dbaeumer** [comment]
I don't see a big difference between having a setting in the settings.json file or having a separate file (which by the way could easily live the the .vscode folder). I really want to avoid re-implementing something that eslint already supports including defining JSON schemas for it.

**Comment by gyratorycircus** [comment]
I would also like to see this feature, and I agree with @dbaeumer. Separate rules for linting vs fixing is already supported in ESLint by way of separate config files (I use this via `$ eslint --config <path>/.eslintrc-fix.js --fix <path>`), so it would make sense to accept a specific autofix config file. This implementation would be compatible between IDEs.

I'd expect this to be configured similar to how the current `configFile` can be specified:

        "eslint.options": { 
            "configFile": "C:/mydirectory/.eslintrc.json",
            "autoFixConfigFile": "C:/mydirectory/.eslintrc-autofix.json"
        }

**Comment by dbaeumer** [comment]
The code for the next ESLint version is not in master. @gyratorycircus are you interested in providing a PR for this. The code to addresses this is here: https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1621

**Comment by gyratorycircus** [comment]
Very interested! I may not be able to commit to this immediately, but I can hopefully find some time over the holidays. I'm not well-versed in TypeScript, nor VSCode plugins, so it may take me a bit to get up to speed.

**Comment by dbaeumer** [comment]
@gyratorycircus great. Ping me if you need support.

**Comment by valerybugakov** [comment]
@dbaeumer, is the above discussion and suggested implementation details still relevant?

**Comment by dbaeumer** [comment]
The extension has in the meantime support to customize rules. But only their error behavior. Before going down the route of a separate config it would be worthwhile to think about extending the customization. However my gut feeling tells me that it will not provide the same flexibility or it requires a lot of additional code in the server to generate the right config file in memory. But I am open for ideas how to achieve this with customization.

**Comment by dbaeumer** [comment]
2.2.0 will ship with a new setting `eslint.codeActionOnSave.rules` to customize the rules used while running code action on save.
