### ISSUE TITLE
.eslintrc is (partially) ignored but eslint.options works...

### ISSUE THREAD

**Issue by Krisa** [Microsoft/vscode-eslint#77]
I got originally this issue https://github.com/babel/eslint-plugin-babel/issues/61 which I have reported probably in the wrong place. To sum up, by using the babel eslint plugin, I couldn't get `async` function to be parsed correctly even so my .eslintrc file was configured correctly. I copy/pasted all the options into the "eslint.options" key of `.vscode/settings.json` and it suddenly worked. I'm using the latest version of VSCode, vscode-eslint, etc.

**Comment by madcampos** [comment]
I've got the opposite: it works if i have a `.eslintrc` file, but seems to ignore some configurations, anything other than the `rules` field, in the `eslint.options` setting.
This is mostly problematic when working with es6 as it complains about things like `Map` and `Set` not been defined.

**Comment by dbaeumer** [comment]
@Krisa this is very strange. What happens if you execute eslint from a terminal. Is the .eslintec file taken into consideration. If so could you share your workspace so that I can investigate.

**Comment by Krisa** [comment]
Well, the issue is 5 months old and I don't have this project anymore. Will close it and reopen it if I face the same issue again.
