### ISSUE TITLE
Rush monorepo: cli working, vscode-eslint throwing exception

### ISSUE THREAD

**Issue by willmtemple** [microsoft/vscode-eslint#770]
In https://github.com/Azure/azure-sdk-for-js we are using [Rush](https://rushjs.io) to manage our packages as a monorepo. We have a set of eslint rules in a different package that are referenced from an eslintrc file in each package (e.g. `sdk/template/template/.eslintrc.json`). That eslintrc extends a root eslintrc (`sdk/.eslintrc.json`) that is two folders up in the hierarchy and specifies more rules and options that are common to all of our packages.

I have a multi-folder workspace open in the monorepo root that has several of the package folders loaded into the workspace. When I start ESLint in vscode and open a file under the `sdk/template/template` path, I get the following trace printed in the output:

```
[Error - 3:56:54 PM] ESLint stack trace:
[Error - 3:56:54 PM] Error: Failed to load config "prettier" to extend from.
Referenced from: ...\azure-sdk-for-js\sdk\.eslintrc.json
    at configMissingError (...\azure-sdk-for-js\common\temp\node_modules\.registry.npmjs.org\eslint\6.2.1\node_modules\eslint\lib\cli-engine\config-array-factory.js:233:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (...\azure-sdk-for-js\common\temp\node_modules\.registry.npmjs.org\eslint\6.2.1\node_modules\eslint\lib\cli-engine\config-array-factory.js:710:23)
    at ConfigArrayFactory._loadExtends (...\azure-sdk-for-s\common\temp\node_modules\.registry.npmjs.org\eslint\6.2.1\node_modules\eslint\lib\cli-engine\config-array-factory.js:615:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (...\azure-sdk-for-js\common\temp\node_modules\.registry.npmjs.org\eslint\6.2.1\node_modules\eslint\lib\cli-engine\config-array-factory.js:546:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (...\azure-sdk-for-js\common\temp\node_modules\.registry.npmjs.org\eslint\6.2.1\node_modules\eslint\lib\cli-engine\config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (...\azure-sdk-for-js\common\temp\node_modules\.registry.npmjs.org\eslint\6.2.1\node_modules\eslint\lib\cli-engine\config-array-factory.js:546:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (...\azure-sdk-for-js\common\temp\node_modules\.registry.npmjs.org\eslint\6.2.1\node_modules\eslint\lib\cli-engine\config-array-factory.js:491:20)
```

I have `"prettier": "^1.16.4"` in my dependencies and a symlink to it exists under node_modules.

These are my workspace settings related to eslint:

```
"eslint.options": {
	"debug" : true,
},
"eslint.validate": [
	"javascript",
	"javascriptreact",
	"typescript",
	"json"
],
"eslint.workingDirectories": [
	{"directory": "sdk/template/template", "changeProcessCWD": true }
]
```

When I run eslint from the `sdk/template/template` folder in CLI, either with `npm run lint` or via `npx eslint src --ext ts`, the linter runs without issue.

I've put together a minimal repro at https://github.com/willmtemple/eslint-issue-repo . Simply install rush (`npm install -g rush`) and run `rush update` in the repo to install all the dependencies into the right places. Then open the included vscode workspace and try to use eslint. On my machine it crashes with the same error resolving `prettier`, but `npm run lint` works fine.

**Comment by dbaeumer** [comment]
I am pretty sure that you need to use the `eslint.workingDirectories` as described here: https://github.com/microsoft/vscode-eslint.

If you use eslint in the terminal with the workspace folder (not changing into a project folder) as the current cwd will eslint in the terminal work correctly. If not this is mostly an indication that you need to configure `eslint.workingDirectories`

**Comment by willmtemple** [comment]
Right, I cannot do that. But I thought that I had set up workingDirectories correctly in the workspace settings. Am I misunderstanding how the workingDirectories works? My understanding is that if I specify a path relative to the workspace root in that setting, and set `"changeProcessCWD": true`, then whenever vscode-eslint inspects a file that is within that directory, it will first `chdir` to do that directory and then run eslint.

If I follow those steps (`cd sdk/template/template/ && npx eslint package.json tsconfig.json api-extractor.json src test --ext ts`), then eslint works fine.

Or maybe there is something I don't understand about the vscode-eslint `eslint.workingDirectories` config option.

**Comment by willmtemple** [comment]
I've been digging into this over the past several days. I don't think this has anything to do with the workspaces or monorepo. If I open the package folder directly in vscode it still doesn't work because vscode-eslint is somehow trying to resolve plugins differently than the CLI. Still works in CLI but does not work in vscode. If I create a symlink `node_modules -> ../common/temp/node_modules` next to the master eslint config, then it suddenly works fine in the UI. It will also work if this symlink is placed in the root of the entire monorepo.

It seems to me as if eslint resolves plugins referenced in extension eslint configs relative to the extender, and vscode-eslint tries to resolve them relative to the extended file.

**Comment by willmtemple** [comment]
I think I've gotten to the bottom of it, but it isn't pretty.

Actually in my little repro repository doing `.\common\temp\node_modules\.bin\eslint .\packages\a\index.ts` __does__ work. It just causes a parser error because the `project` is no longer pointing to `tsconfig.json` relative to cwd.

I can override that setting manually and it works fine:

```
eslint-issue-repo $ ./common/temp/node_modules/.bin/eslint --parser-options "{\"project\": \"packages/a/tsconfig.json\"}" ./packages/a/index.ts

.../eslint-issue-repo/packages/a/index.ts
  3:24  error  Don't use 'String' as a type. Use string instead  @typescript-eslint/ban-types

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

```

It __does not__ work if I invoke node directly:

```
eslint-issue-repo $ node ./common/temp/node_modules/eslint/bin/eslint.js --parser-options "{\"project\": \"packages/a/tsconfig.json\"}" ./packages/a/index.ts

Oops! Something went wrong! :(

ESLint: 6.5.1.

ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".

...
```

nor can I do this from within the package's directory:

```
eslint-issue-repo/packages/a $ node node_modules/eslint/bin/eslint.js ./index.ts

Oops! Something went wrong! :(

...
```

I was not correct that the CLI and the VSCode plugin are resolving modules differently. It is actually because Rush replaces the contents of the `node_modules/.bin` folder with versions of installed executables that correctly set up NODE_PATH for Rush before executing them. However, even when I set `"eslint.nodePath": ".../common/temp/node_modules"` in workspace or user settings, it does not resolve the plugins because that setting only affects the path used to search for eslint itself, not the path eslint uses to search for its plugins.

Plugins cannot be referenced using relative paths in eslintrc, and eslint does try to resolve plugins using module.resolve relative to the included file, not relative to cwd. _However_, because Rush is setting the node path for me, a configuration which _shouldn't_ work actually does and confused me into thinking that eslint is doing something that it isn't actually.

I'm going to go ahead and close this since I don't think there's anything sane that vscode-eslint can or should do about this. I will probably open issues on Rush and maybe VSCode instead. Maybe VSCode itself can expose a setting allowing us to inject a directory into the node path of the extension from the workspace configuration. Or Rush can add a location to store persistent configs that also has access to the shared modules folder. For anyone else who comes by this issue: another thing that would probably work is to create a utility package in the monorepo where this config can be stored.

**Comment by crhayes** [comment]
@willmtemple I am experiencing the same issue and stumbled across this issue.

I found someone's workaround that involves monkey patching module resolution so that ESLint resolves plugins relative to the config file they are referenced in (i.e. the base config in a shared config setup).

Thought you might find the discussion and code interesting:

https://github.com/eslint/eslint/issues/3458#issuecomment-516666620
https://github.com/eslint/eslint/issues/3458#issuecomment-516716165
