### ISSUE TITLE
Not getting option to disable rule on line

### ISSUE THREAD

**Issue by ericbiewener** [microsoft/vscode-eslint#774]
As far as I can tell, this feature [should exist](https://github.com/microsoft/vscode-eslint/pull/530). But the code action doesn't appear for me:

<img width="660" alt="Screen Shot 2019-10-05 at 3 55 06 PM" src="https://user-images.githubusercontent.com/253298/66261779-8f76b200-e788-11e9-9d51-b618998e57b1.png">

<img width="401" alt="Screen Shot 2019-10-05 at 3 55 11 PM" src="https://user-images.githubusercontent.com/253298/66261780-91d90c00-e788-11e9-88f8-0411a0a6e962.png">

**Comment by dbaeumer** [comment]
The second screenshot in my opinion shows a TS quick action not a quick fix from ESLint.

Can you provide me with a GitHub repository I can clone that demos what you are seeing.

**Comment by elado** [comment]
Can confirm - disabling lint rules function shows only on `.js` files, not `.ts`.

I also enabled `eslint.validate` with typescript.

```
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ]
```
