### ISSUE TITLE
After modification eslint signals non existing comma-spacing errors

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode-eslint#775]
Issue Type: <b>Bug</b>

- Load the attached file (change extension to .ts). Eslint should signal no error.
[formats.ts](https://github.com/microsoft/vscode-eslint/files/3700674/formats.txt)
- Make a change.
- Suddenly eslint will signal comma-spacing, space-infix-ops, keyword-spacing and other similar errors that are not there.

Here is the eslint.json in use:
[eslint.json](https://github.com/microsoft/vscode-eslint/files/3700682/eslint.txt)

The problem started after a recent plugin update. Unfortunately I cannot be more specific.
Thanks for looking!
mario

Extension version: 1.9.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.43GB free)|
|Process Argv|--file-uri file:///d%3A/Projects/CouchDB/CouchDB.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by crystalfp** [comment]
Should add that the squishes signalling the errors are in positions that have no relation to the potential error
![image](https://user-images.githubusercontent.com/865866/66456015-b6750280-ea6c-11e9-83da-07545ae6c60e.png)
I'm desperate. I should disable eslint if I want to work.

**Comment by crystalfp** [comment]
It does not happen with 1.9.0 Or better it happens if there is a legitimate error, like a trailing space.

**Comment by xlc** [comment]
I am having similar issue, just like the file been processed does not have any spaces. Running `eslint` from command line does not find any spaces issue.

```
{
	"resource": "redacted",
	"owner": "eslint",
	"code": "@typescript-eslint/indent",
	"severity": 8,
	"message": "Expected indentation of 2 spaces but found 2.",
	"source": "eslint",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 5
}
```

**Comment by dbaeumer** [comment]
Can either of you provide me with a GitHub repository I can clone that demos what you are experiencing?

**Comment by xlc** [comment]
@dbaeumer https://github.com/laminar-protocol/flow-protocol-ethereum/blob/master/test/flowToken.ts

**Comment by dbaeumer** [comment]
@xlc I can not reproduce this with the provided repository.

![capture](https://user-images.githubusercontent.com/1931590/67102938-9956d700-f1c4-11e9-90c9-3b012c34e87a.png)


Any additional steps ?

**Comment by xlc** [comment]
Ha not sure what's going on. I tried last time and it wasn' working so I always had eslint extension disabled for this workspace. Just enabled it now and it works. Since last time I tried I downgraded my node version from 12 to 10 because it was causing trouble to other dependencies and bumped few dependency versions.

**Comment by dbaeumer** [comment]
Good to hear that it is working for you now. Although I have to say that downgrading node shouldn't have this impact. 

I will keep the issue open a little longer. If someone can provide me with a test repository I can clone I am happy to investigate.

**Comment by AndySteel-kcom** [comment]
I too have been seeing this error since upgrading packages and/or working more on typescript files recently. Basically, as soon as you type a change into the editor (typescript file in my case), the eslint extension goes really corrupt from the point where you'd typed. The errors bear no relation to the code. Disabling & Enabling the extension doesn't solve the problem. I have to close vscode folder and reopen.

I turned on tracing of the extension and have seen some sort of stack trace within the ESLint output window. I'm suspecting that the ESLint extension has thrown an exception in the "Indent.js" rule/module and this has caused all of the remaining errors to be displayed on the editor window.

```
[Info  - 15:19:27] ESLint server stopped.
[Trace - 15:19:27] Sending request 'initialize - (0)'.
[Trace - 15:19:27] Received notification 'window/logMessage'.
[Info  - 15:19:27] ESLint server running in node v10.11.0
[Trace - 15:19:27] Received notification '$/progress'.
[Trace - 15:19:27] Received notification '$/progress'.
[Trace - 15:19:27] Received response 'initialize - (0)' in 359ms.
[Info  - 15:19:27] ESLint server is running.
[Trace - 15:19:27] Sending notification 'initialized'.
[Trace - 15:19:27] Sending notification 'textDocument/didOpen'.
[Trace - 15:19:28] Received request 'client/registerCapability - (0)'.
[Trace - 15:19:28] Sending response 'client/registerCapability - (0)'. Processing request took 1ms
[Trace - 15:19:28] Received request 'client/registerCapability - (1)'.
[Trace - 15:19:28] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
[Trace - 15:19:28] Received request 'workspace/configuration - (2)'.
[Trace - 15:19:28] Sending response 'workspace/configuration - (2)'. Processing request took 1ms
[Trace - 15:19:32] NODE_PATH value is: C:\Users\steela.JNO\AppData\Roaming\npm\pnpm-global\3\node_modules
[Trace - 15:19:33] Received notification 'window/logMessage'.
[Info  - 15:19:33] ESLint library loaded from: C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\node_modules\.pnpm\registry.npmjs.org\eslint\6.5.1\node_modules\eslint\lib\api.js
[Trace - 15:19:42] Received notification 'textDocument/publishDiagnostics'.
[Trace - 15:19:42] Received notification 'eslint/status'.
[Trace - 15:28:22] Sending request 'textDocument/codeAction - (1)'.
[Trace - 15:28:22] Received response 'textDocument/codeAction - (1)' in 7ms.
[Trace - 15:28:26] Sending request 'textDocument/codeAction - (2)'.
[Trace - 15:28:26] Received response 'textDocument/codeAction - (2)' in 4ms.
[Trace - 15:28:28] Sending request 'textDocument/codeAction - (3)'.
[Trace - 15:28:28] Received response 'textDocument/codeAction - (3)' in 3ms.
[Trace - 15:28:43] Sending notification 'textDocument/didChange'.
[Trace - 15:28:43] Received request 'window/showMessageRequest - (3)'.
[Trace - 15:28:43] Received notification 'window/logMessage'.
[Error - 15:28:43] ESLint stack trace:
[Trace - 15:28:43] Received notification 'window/logMessage'.
[Error - 15:28:43] RangeError: Maximum call stack size exceeded
Occurred while linting C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\gadget.ts:16
    at RegExp.test (<anonymous>)
    at OffsetStorage.getDesiredIndent (C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\node_modules\.pnpm\registry.npmjs.org\eslint\6.5.1\node_modules\eslint\lib\rules\indent.js:449:33)
    at OffsetStorage.getDesiredIndent (C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\node_modules\.pnpm\registry.npmjs.org\eslint\6.5.1\node_modules\eslint\lib\rules\indent.js:455:45)
    at OffsetStorage.getDesiredIndent (C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\node_modules\.pnpm\registry.npmjs.org\eslint\6.5.1\node_modules\eslint\lib\rules\indent.js:455:45)
    at OffsetStorage.getDesiredIndent (C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\node_modules\.pnpm\registry.npmjs.org\eslint\6.5.1\node_modules\eslint\lib\rules\indent.js:455:45)
    at OffsetStorage.getDesiredIndent (C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\node_modules\.pnpm\registry.npmjs.org\eslint\6.5.1\node_modules\eslint\lib\rules\indent.js:455:45)
    at OffsetStorage.getDesiredIndent (C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\node_modules\.pnpm\registry.npmjs.org\eslint\6.5.1\node_modules\eslint\lib\rules\indent.js:455:45)
    at OffsetStorage.getDesiredIndent (C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\node_modules\.pnpm\registry.npmjs.org\eslint\6.5.1\node_modules\eslint\lib\rules\indent.js:455:45)
    at OffsetStorage.getDesiredIndent (C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\node_modules\.pnpm\registry.npmjs.org\eslint\6.5.1\node_modules\eslint\lib\rules\indent.js:455:45)
    at OffsetStorage.getDesiredIndent (C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap\node_modules\.pnpm\registry.npmjs.org\eslint\6.5.1\node_modules\eslint\lib\rules\indent.js:455:45)
[Trace - 15:28:43] Received notification 'eslint/status'.
[Trace - 15:28:50] Sending notification 'textDocument/didChange'.
[Trace - 15:28:56] Sending request 'textDocument/codeAction - (4)'.
[Trace - 15:29:03] Sending request 'textDocument/codeAction - (5)'.
[Trace - 15:29:05] Sending request 'textDocument/codeAction - (6)'
```
Here's the package.json information:
```
  "devDependencies": {
    "@babel/cli": "^7.6.0",
    "@babel/core": "^7.6.0",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-numeric-separator": "^7.2.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
    "@babel/plugin-transform-runtime": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "@babel/preset-typescript": "^7.6.0",
    "@kcom/eslint-config": "^5.0.20",
    "@kcom/gadget-scaffold-library": "^1.0.18",
    "@types/node": "^12.11.5",
    "@types/websocket": "^1.0.0",
    "@typescript-eslint/eslint-plugin": "^2.2.0",
    "@typescript-eslint/parser": "^2.2.0",
    "babel-loader": "^8.0.6",
    "clean-webpack-plugin": "^3.0.0",
    "del": "^5.1.0",
    "eslint": "^6.5.1",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-import-resolver-node": "^0.3.2",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-plugin-ie11": "^1.0.0",
    "eslint-plugin-import": "^2.18.2",
    "file-loader": "^4.2.0",
    "gulp": "^4.0.0",
    "gulp-babel": "^8.0.0",
    "gulp-batch": "^1.0.5",
    "gulp-chmod": "^3.0.0",
    "gulp-debug": "^4.0.0",
    "gulp-eslint": "^6.0.0",
    "gulp-if": "^3.0.0",
    "gulp-less": "^4.0.1",
    "gulp-replace": "^1.0.0",
    "gulp-scp2": "^0.2.0",
    "gulp-watch": "^5.0.1",
    "less": "^3.9.0",
    "ssh2": "^0.8.2",
    "typescript": "^3.6.3",
    "webpack": "^4.39.3",
    "webpack-bundle-analyzer": "^3.4.1",
    "webpack-cli": "^3.3.8",
    "webpack-stream": "^5.2.1"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "debug": "^4.1.0",
    "es6-promise": "^4.2.8",
    "es6-template-strings": "^2.0.1",
    "libphonenumber-js": "^1.7.18",
    "moment": "^2.24.0"
  }
```
![image](https://user-images.githubusercontent.com/17144224/67497295-b0d70980-f675-11e9-9d2d-124203b70220.png)

![image](https://user-images.githubusercontent.com/17144224/67497393-cf3d0500-f675-11e9-8c18-62e98bbd6fb1.png)

**Comment by AndySteel-kcom** [comment]
As an example, I loaded vscode and proceeded to line 192 which had eslint reporting that the comment needed a space after the double slash //. So I added a space at column 6 and then ESLint extension went wrong thereafter as you can see below. It appears to be miscounting the number of spaces everywhere as I now have 782 problems reported all relating to spaces.


![image](https://user-images.githubusercontent.com/17144224/67498046-c1d44a80-f676-11e9-918c-1bb9edcedf73.png)

**Comment by AndySteel-kcom** [comment]
I just realised that the installed versions of packages may be later than those listed in the package.json so i've listed out the actual packages being used locally below.

```
λ pnpm list -depth 0
Legend: production dependency, optional only, dev only

responsetap@1.0.0 C:\develop\workplaces\NFUM\Finesse_Gadgets\ResponseTap

dependencies:
@kcom/finesse-modules-kcom 2.0.36
@kcom/types-finesse 2.0.36
babel-polyfill 6.26.0
babel-runtime 6.26.0
debug 4.1.1
es6-promise 4.2.8
es6-template-strings 2.0.1
libphonenumber-js 1.7.26
moment 2.24.0

devDependencies:
@babel/cli 7.6.4                                 babel-loader 8.0.6                               gulp-debug 4.0.0
@babel/core 7.6.4                                clean-webpack-plugin 3.0.0                       gulp-eslint 6.0.0
@babel/plugin-proposal-class-properties 7.5.5    del 5.1.0                                        gulp-if 3.0.0
@babel/plugin-proposal-numeric-separator 7.2.0   eslint 6.5.1                                     gulp-less 4.0.1
@babel/plugin-proposal-object-rest-spread 7.6.2  eslint-config-airbnb-base 14.0.0                 gulp-replace 1.0.0
@babel/plugin-transform-runtime 7.6.2            eslint-import-resolver-node 0.3.2                gulp-scp2 0.2.0
@babel/preset-env 7.6.3                          eslint-import-resolver-typescript 2.0.0          gulp-watch 5.0.1
@babel/preset-typescript 7.6.0                   eslint-plugin-ie11 1.0.0                         less 3.10.3
@kcom/eslint-config 5.0.21                       eslint-plugin-import 2.18.2                      ssh2 0.8.5
@kcom/gadget-scaffold-library 1.0.27             file-loader 4.2.0                                typescript 3.6.4
@types/node 12.11.6                              gulp 4.0.2                                       webpack 4.41.2
@types/websocket 1.0.0                           gulp-babel 8.0.0                                 webpack-bundle-analyzer 3.6.0
@typescript-eslint/eslint-plugin 2.5.0           gulp-batch 1.0.5                                 webpack-cli 3.3.9
@typescript-eslint/parser 2.5.0                  gulp-chmod 3.0.0                                 webpack-stream 5.2.1
```
And here's my global install base of packages.
```
λ npm list -depth 0 -g
C:\Users\steela.JNO\AppData\Roaming\npm
+-- @typescript-eslint/parser@2.5.0
+-- babel-eslint@9.0.0
+-- eslint@6.5.1
+-- gulp@4.0.2
+-- gulp-eslint@6.0.0
+-- install-peerdeps@1.10.2
+-- json-server@0.15.1
+-- npm@6.9.0
+-- pnpm@3.6.0
+-- rollup@1.19.4
+-- ts-node@8.3.0
`-- typescript@3.5.2
```

**Comment by AndySteel-kcom** [comment]
I've been changing versions of a couple of packages in my project devDependencies to narrow down what may be the cause. simply by editing the typescript file and removing a space between // and following text will cause the error.

@typescript-eslint/eslint-plugin v2.5.0
@typescript-eslint/parser v2.5.0
The above combination results in the errors within vscode.

@typescript-eslint/eslint-plugin v2.4.0
@typescript-eslint/parser v2.4.0
The above does not have any problem

@typescript-eslint/eslint-plugin v2.5.0
@typescript-eslint/parser v2.4.0
The above does not have any problem

@typescript-eslint/eslint-plugin v2.4.0
@typescript-eslint/parser v2.5.0
The above has the problem/error displayed within vscode.

Therefore, for me, the problem appears when upgrading @typescript-eslint/parser to v2.5.0
Since there doesn't appear to be a version between 2.4.0 & 2.5.0 I couldn't go any further.

Hope this helps.

**Comment by dbaeumer** [comment]
@AndySteel-kcom thanks for the detailed analysis. Can you reproduce the exception mentioned here: https://github.com/microsoft/vscode-eslint/issues/775#issuecomment-545957027 in the terminal as well. This looks like a general eslint problem to me and should be filed against them.

**Comment by AndySteel-kcom** [comment]
hi. eslint on the terminal was fine. problem only with vscode editor

**Comment by dbaeumer** [comment]
@AndySteel-kcom thanks. Any GitHub repository I can clone that demos this?
