### ISSUE TITLE
Handle workingDirectories glob paths

### ISSUE THREAD

**Issue by nmussy** [microsoft/vscode-eslint#778]
It would be a nice feature to be able to set wildcards in `workingDirectories` directory paths.
The use-case I'm facing is a large lerna project with lots of packages, and more to come in the future ([aws-cdk:packages/@aws-cdk](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk)). Creating and maintaining that package list would be a bit of a pain:

```json
{
    "eslint.workingDirectories": [
        { "directory": "./packages/@aws-cdk/alexa-ask", "changeProcessCWD": true },
        { "directory": "./packages/@aws-cdk/app-delivery", "changeProcessCWD": true },
        { "directory": "./packages/@aws-cdk/assert", "changeProcessCWD": true },
        // ...
    ]
}
```

```json
{
    "eslint.workingDirectories": [
        { "directory": "./packages/@aws-cdk/*", "changeProcessCWD": true },
    ]
}
```

As a side-note, I tried using `"parserOptions": {"project": "./packages/@aws-cdk/*/tsconfig.json"}` in the root `.eslintrc`, but the plugin was running out of memory trying to parse everything

I'd probably be able to make a PR for it if needed.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode-eslint/issues/745

@nmussy PRs are always very welcome.
