### ISSUE TITLE
ts2307 for .vue files imported to ts

### ISSUE THREAD

**Issue by viT-1** [microsoft/vscode-eslint#779]
Related: https://github.com/vuejs/vue-cli/issues/1198
ESLint configuration is ok, I haven't this error in console & unit testing npm scripts (tsc & eslint),
but IDE & vscode-eslint plugin giving me error suggestion & underlines path in import.

**Comment by dbaeumer** [comment]
@viT-1 can you please provide me with a GitHub repository I can clone that demos what you are seeing?

**Comment by viT-1** [comment]
@dbaeumer https://github.com/viT-1/systemjs-ts-es6-vue/commit/d0cbb3bcfaa32436fd74e4f37372aeedd2efa02a#diff-30f7c26bd279aea412e8d79fff465f5bR4

**Comment by dbaeumer** [comment]
Actually the error comes from the TS language server not from ESLint (see the ts source).

![capture](https://user-images.githubusercontent.com/1931590/67102262-72e46c00-f1c3-11e9-9fd6-5b71c55f45cc.png)


Please report the problem against TS.

**Comment by viT-1** [comment]
Related and solved: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24788#issuecomment-516981522
