### ISSUE TITLE
Look for .eslintrc up the tree

### ISSUE THREAD

**Issue by wmira** [Microsoft/vscode-eslint#78]
Can this please work like any other eslint plugin? Doesn't seem to lookup eslintrc from project.

**Comment by dbaeumer** [comment]
I retested this and it works for me. The plugin actually uses the eslint API to do this. So if you use a decent eslint version it should work.

@wmira could you provide a test case demonstrating the failed behavior so that I can investigate.

**Comment by wmira** [comment]
Hi @dbaeumer  initially I thought it wasn't looking it up but it looks like the plugin just does not work. I loaded the same project on Atom and Code and Code wasn't showing eslint errors. Do I need to tell it where to look for eslint? Can it use the global eslint? I really like to try VSCode but not having a linter really is stopping me from trying it out. I'm on Ubuntun 14.04 btw. 

Is there a console (sorry new with vscode) I can look at to see any errors in the plugin?
Thanks.

**Comment by wmira** [comment]
@dbaeumer I just tried this again with 1.2 and eslint works now. Closing this.
