### ISSUE TITLE
Inline linter is lagging

### ISSUE THREAD

**Issue by cawoodm** [microsoft/vscode-eslint#780]
If I correct a reported error, the error remains reported in the VS Code editor long (minutes) after it has been corrected. Also, new mistakes are reported very late. Laptop is not "spinning" or overloaded.

Options: run onType true

Windows 10, latest VSCode 1.39.2 (user) and ESLint 6.5.1 and ESLint plugin 1.9.1.

![image](https://user-images.githubusercontent.com/498834/66983272-750dd400-f0b8-11e9-83bb-582bca9d15ed.png)

**Comment by dbaeumer** [comment]
@cawoodm any steps on how to reproduce what you are seeing.  Best would be a GitHub repository I could clone.

**Comment by cawoodm** [comment]
Hey Dirk, it's a sporadic problem which is behaving now. Anything I can check the next time it happens?

**Comment by dbaeumer** [comment]
You can enable tracing to see if the server is still responding. See the setting: `"eslint.trace.server": "messages"`
