### ISSUE TITLE
eslint runs from /, not working directory

### ISSUE THREAD

**Issue by bmalehorn** [microsoft/vscode-eslint#784]
I'm trying to use [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import). This takes in a `src` directory to better understand import statements:

```json
  "settings": {
    "import/resolver": {
      "node": {
        "paths": ["src"]
      }
    }
  }
```

# Reproduction

I've made a small package showing the error here: https://github.com/bmalehorn/eslint-monorepo-example

When I run `yarn eslint`, `src` is resolved to `./src`, and runs correctly:

```
> git clone https://github.com/bmalehorn/eslint-monorepo-example
> cd eslint-monorepo-example/my-react-app
> cd my-react-app
> yarn eslint src
yarn run v1.12.0
$ /Users/brianmalehorn/eslint-monorepo-example/my-react-app/node_modules/.bin/eslint src
✨  Done in 1.77s.
```

However, when I open the file in VSCode, `src` is resolved to `/src`, which causes eslint errors:

![image](https://user-images.githubusercontent.com/3344958/67230724-ab1dc180-f3f2-11e9-8fcb-20d4b717a60a.png)

# Fix

I can workaround this by specifying an absolute path:
```diff
-        "paths": ["src"]
+        "paths": ["/Users/brianmalehorn/eslint-monorepo-example/my-react-app/src"]
```

I can tell it's running in `/` because I can leave of the the leading `/` and it still works:

```diff
-        "paths": ["src"]
+        "paths": ["Users/brianmalehorn/eslint-monorepo-example/my-react-app/src"]
```

However, and ideal fix would be to **run eslint in the same directory as package.json**. This way, relative paths in eslint plugins would work correctly.

Related: https://github.com/microsoft/vscode-eslint/issues/712

**Comment by dbaeumer** [comment]
Since you use relative paths you need to let the extension know that you want to change the working directory (which is off by default since it might cause other side effects since eslint is very sensitive to the current working directory).

Something like
```js
{
  "eslint.workingDirectories": [
    { "directory": "my-react-app", "changeProcessCWD": true }
  ]
}
```
