### ISSUE TITLE
eslintServer.js locking files under node_modules?

### ISSUE THREAD

**Issue by GordonBlahut** [microsoft/vscode-eslint#785]
Trying to update packages with yarn are getting lots of `An unexpected error occurred: "EPERM: operation not permitted, unlink 'D:\WebClient\ClientApp\node_modules\loader-fs-cache\node_modules\find-cache-dir\node_modules\.bin'".` error messages. The actual file may differ each time.

Running SysInternals Process Explorer and VS Code's Process Explorer shows file handles from the **electron_node eslintServer.js** process.

Is it normal for **eslintServer.js** to have handles to everything under my **node_modules**? I thought **node_modules** was excluded by default and I also exclude **node_modules/\*\*** in ***.eslintignore** and **tsconfig.json**.

I'm trying to figure out if this an issue with eslint or yarn.

VS Code 1.39.2
Windows 10 x64
ESLint 1.9.1

**Comment by dbaeumer** [comment]
I checked locally and for me this doesn't happen.

I am not sure if this is a problem with the eslint extension or with a ESLint plugin in your configuration. Since the ESLint server loads the configured ESLint plugins a misbehaving plugin is very likely causing this.

Can you share your setup that demos this?

**Comment by GordonBlahut** [comment]
Thank you for clarifying that it's likely a plugin. 

I will see if I can reproduce in a minimal setup to share and/or narrow it down to a specific plugin and go from there.

**Comment by dbaeumer** [comment]
Thanks for getting back. Ping when you have a minimal setup.

**Comment by GordonBlahut** [comment]
I suspect this was caused by a specific version of the typescript-eslint plugin and fixed in the next version. I can no longer recreate the issue since I've updated the plugin.
