### ISSUE TITLE
ESLint (or Prettier?) randomly stops working

### ISSUE THREAD

**Issue by dugajean** [microsoft/vscode-eslint#787]
I have the latest VS Code and I use ESLint and Prettier for my projects. Very often, ESLint, which is supposed to work together with Prettier according to the rules I've setup and plugins I've installed, will just stop working.

For example: I have some badly formatted code and ESLint will show the red underlines normally. With my current settings, saving the file will fix those errors automatically by reformatting the code. Now in some cases, the error shows up and saving will not fix it anymore! Even if you fix the error manually by adding the necessary spaces and whatnot, the error will remain and saving the file doesn't do anything anymore.

This forces me to reload VS Code to get it to work again. Then again after a couple minutes this will happen forcing me to reload again etc.

Why is ESLint (or Prettier?) just randomly stopping?

Relevant VS Code settings:

    "vetur.format.defaultFormatter.html": "prettier",
    "eslint.validate": [
        {
            "language": "vue",
            "autoFix": true
        },
        {
            "language": "html",
            "autoFix": true
        },
        {
            "language": "javascript",
            "autoFix": true
        }
    ],
    "terminal.integrated.rendererType": "dom",
    "prettier.requireConfig": true,
    "prettier.disableLanguages": [],
    "eslint.autoFixOnSave": true,
    "editor.formatOnSave": false,
    "vetur.validation.template": true,
    "vetur.useWorkspaceDependencies": true,

Relevant `.eslintrc.json` config:

    "plugins": ["prettier"],
    "extends": [
      "plugin:prettier/recommended",
      "plugin:vue/recommended",
      "plugin:vue/essential",
      "eslint:recommended",
      "@vue/standard",
      "prettier/vue"
    ],

Help would be appreciated

**Comment by dbaeumer** [comment]
@dugajean can you please provide me with a GitHub repository I can clone that demos what you are experiencing (including steps how to replay).

**Comment by dugajean** [comment]
@dbaeumer It happens in all of my code bases. I'll try to provide a recording of it happening.

**Comment by dugajean** [comment]
@dbaeumer 

![req](https://user-images.githubusercontent.com/2448254/67772056-b8255b00-fa59-11e9-8313-474259de544e.gif)

**Comment by dbaeumer** [comment]
@dugajean I am not questioning that you are seeing this. But without reproducible steps something like this is hard to track down and to fix. So I still welcome a GitHub repository I can clone that demos this.
