### ISSUE TITLE
Need help to get eslint-plugin-amo to work in VSCode

### ISSUE THREAD

**Issue by odebroqueville** [microsoft/vscode-eslint#788]
I've installed both eslint 6.51 and eslint-plugin-amo@latest globally. 
My eslintrc.json looks as follows in VS Code:
<img width="391" alt="Screenshot 2019-10-25 at 22 20 56" src="https://user-images.githubusercontent.com/4818315/67602331-a486a580-f776-11e9-8bd6-bd2670201b03.png">
You can see that eslint is picking up a problem "browser not defined" from browser.i18n.getMessage in my background.js file.
@willdurand I thought [eslint-plugin-amo](https://www.npmjs.com/package/eslint-plugin-amo) would prevent 'browser' from being reported as a problem.
Have I done something wrong or is there a bug somewhere?

**Comment by willdurand** [comment]
`eslint-plugin-amo` is a plugin for the AMO website, so it is configured for a browser + node app, not for a web extension (`browser` only exists in the context of a web extension, not in the browser or node IIRC).

**Comment by odebroqueville** [comment]
Does that mean that there is no way not to have 

> 'browser' is not defined

 show up as a problem? Is there no eslint plugin for web extensions?

**Comment by willdurand** [comment]
You can probably declare `browser` as a global variable, I dunno.. I am not aware of an eslint plugin for web extensions, but that is a neat idea.
