### ISSUE TITLE
ESLint does not do anything

### ISSUE THREAD

**Issue by javierguzman** [microsoft/vscode-eslint#789]
Hello all,

I am trying to setup my VSCode ES Lint but it does not seem to work properly. I have to specify where my lint configuration is because is not in the root, and because of that it does not find "eslint-plugin-react". To fix this late error I specify the "nodePath" option but still it does not find eslint-plugin-react!

This is my workspace configuration:
```
{
    "eslint.options": {
        "configFile": "C:/blablabla/proyect/client/config/.eslintrc.json"
    },
    "eslint.autoFixOnSave": true,
    "eslint.nodePath": "C:/blablabla/proyect/client/node_modules"
}
```
Thank you in advance!

**Comment by dbaeumer** [comment]
@javierguzman can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by javierguzman** [comment]
Hello @dbaeumer !! 

Thank you for your response and sorry for the delay, I have been away this weekend. I have created this simple example, I hope is good enough for you:

https://github.com/javierguzman/eslint-plugin-test

You will have to modify the settings.json as it contains absolutes paths but the project represents the folder structure I am trying to make work.

**Comment by dbaeumer** [comment]
This also fails for me in the terminal:

```
eslint-plugin-test\client-example [master ≡]> .\node_modules\.bin\eslint --config .\config\.eslintrc.json .\src\index.js

Oops! Something went wrong! :(

ESLint: 6.6.0.

ESLint couldn't find the plugin "eslint-plugin-jsx-a11y".

(The package "eslint-plugin-jsx-a11y" was not found when loaded as a Node module from the directory "C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\eslint-plugin-test\client-example".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-jsx-a11y@latest --save-dev

The plugin "eslint-plugin-jsx-a11y" was referenced from the config file in "--config » eslint-config-airbnb » C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\eslint-plugin-test\client-example\node_modules\eslint-config-airbnb\rules\react-a11y.js".

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

I recommend to get this working in the terminal first. If you then still see problems in the VS Code extension please ping again.

**Comment by javierguzman** [comment]
Hello again @dbaeumer,

Sorry I missed a couple of dependencies. I have updated the package.json to reflect this.

I run now ok in the terminal but when using the plugin it says "No ESLint configuration (e.g .eslintrc) found for file: " blabla.

**Comment by dbaeumer** [comment]
When you run in the terminal do you run the command from exactly the same folder on which you open VS Code.

**Comment by javierguzman** [comment]
Hello!

At the end I have managed to solve the problem. The solution was to use VSCode workspaces. I guess the problem was I had the parent folder open on VS Code rather than the client/server folder only, so with workspaces I can have both folders open at the same time with individual settings set and it seems to work in this way.

Thank you for your help Dirk!
