### ISSUE TITLE
Cannot read property 'parent' of null

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode-eslint#790]
Issue Type: <b>Bug</b>

Load the attached file, change it, after a while this error appears:
Parsing error: Cannot read property 'parent' of null - eslint [1, 1]

The above error does not appear when running eslint outside VSCode.

[eslint.yaml](https://github.com/microsoft/vscode-eslint/files/3775657/eslint.txt)
[synonyms.ts](https://github.com/microsoft/vscode-eslint/files/3775651/synonyms.txt)
[tsconfig.json](https://github.com/microsoft/vscode-eslint/files/3775659/tsconfig.txt)

Extension version: 1.9.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.76GB free)|
|Process Argv|D:\Projects\CouchDB\CouchDB.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RodyGL** [comment]
Same error happening to me. I can't continue to use ESLint cause is throwing none existing errors...
I get

- **Cannot read property 'parent' of nul**
-  **`>` can be escaped with `&gt;`.**

Among other errors just by editing or adding files. The only fix for now is reloading vscode like 1000 times a day...

**Comment by dbaeumer** [comment]
@crystalfp can you please provide me with a GitHub repository I can clone that demos what you are experiencing. Usually errors like this highly depend on the used npm package versions as well.

**Comment by xg4** [comment]
It seems that typescript-eslint error https://github.com/typescript-eslint/typescript-eslint/issues/1114

**Comment by dbaeumer** [comment]
@xg4 thanlks for pointing this out.

**Comment by dbaeumer** [comment]
I will close the issue in favour of typescript-eslint/typescript-eslint#1114
