### ISSUE TITLE
eslint doesn't work in my project

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode-eslint#792]
os: win10pro 1909
vscode: 1.39.2
project repository: https://github.com/tjx666/refined-nowcoder

I use typescript + prettier + react.
It works well when I use the command tool, but VSCode can't real-time show the error or warning Infos of lint problems.

**Comment by dbaeumer** [comment]
Since you try to validate TS you need to tell VS Code to validate TS files. See here to find out how: https://github.com/microsoft/vscode-eslint#using-eslint-to-validate-typescript-files
