### ISSUE TITLE
Autofix lightbulb not showing / Autofix on save not working (Typescript)

### ISSUE THREAD

**Issue by evanwellens** [microsoft/vscode-eslint#796]
Even the most trivial fixes are not auto fixing (like making let -> const or spacing) . It finds the  problems , just no option to fix. I tried auto fix on save , 
The following is set
"eslint.autoFixOnSave": true,
"files.autoSave": "off",

.eslintrc.js
module.exports = {
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint'],
  extends: ['plugin:@typescript-eslint/recommended'],
}

settings..

{
    "window.zoomLevel": 1,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "editor.tabSize": 2,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "svn.enableProposedApi": "argument",
    "javascript.implicitProjectConfig.experimentalDecorators": true,
    "eslint.validate": [
        "typescript"
      ],
      "eslint.autoFixOnSave": true,
      "eslint.lintTask.options": ""
}

My Dev Deps
"devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular-devkit/build-ng-packagr": "~0.13.0",
    "@angular/cli": "^7.3.8",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "~8.9.4",
    "@typescript-eslint/eslint-plugin": "^2.6.1",
    "@typescript-eslint/parser": "^2.6.1",
    "codelyzer": "~4.5.0",
    "eslint": "^6.6.0",
    "eslint-config-node": "^4.0.0",
    "eslint-config-prettier": "^6.5.0",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-prettier": "^3.1.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.6",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.2.0",
    "prettier": "^1.18.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.37.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }

**Comment by dbaeumer** [comment]
Please see:  https://github.com/microsoft/vscode-eslint#using-eslint-to-validate-typescript-files

You need to enable auto fix for TS.
