### ISSUE TITLE
Fix doesn't give the same output as `eslint --fix`

### ISSUE THREAD

**Issue by mikew** [microsoft/vscode-eslint#799]
We're using jsx-sort-props, and with the recent update to VS Code, have noticed that fix is ... introducing errors.

With this input:

```js
const foo = <Foo prop2="lol" prop1="gg" />
```

The output of running `fix all auto-fixable problems` is:

```js
const foo = <Foo prop2="lol"prop1="gg" />
```

While the output of `./node_modules/.bin/eslint --fix eslint-issue.js` is:

```js
const foo = <Foo prop1="gg" prop2="lol" />
```

**Comment by dbaeumer** [comment]
@mikew can you provide me with a GitHub repository I can clone that demos this. 

I have no idea why an update of VS Code should change this since the ESLint extension computing the fix didn't change.

**Comment by sman591** [comment]
Hi @dbaeumer, I'm seeing what I believe is the same thing. This seems like the working directory respected by eslint might have changed in a recent VSCode update?

**Comment by dbaeumer** [comment]
No, the working directory is a pure eslint extension feature not influenced by VS Code.

Can you provide me with a GitHub repository I can clone that demos what you are seeing?
