### ISSUE TITLE
eslint does not work unless I terminate all nodejs processes 

### ISSUE THREAD

**Issue by christos312** [microsoft/vscode-eslint#800]
Hello

After searching over the internet for days now, and finding many posts either here or other places I still haven't manage to make VSCode run eslint on the editor.

Suddenly I noticed something by accident, and I would like to have your opinion

ESLint is installed globally and in the project using npm. As soon as I open VSCode and I go ti OUTPUT > ESLINT I see the following output

```
[Info  - 4:11:31 PM] ESLint server stopped.
[Info  - 4:11:32 PM] ESLint server running in node v12.4.0
[Info  - 4:11:32 PM] ESLint server is running.
```

If I then open a CMD window with elevated permissions and I run the following command

`taskkill /f /im node.exe`

Then the VSCode Output shows this message

`[Info  - 4:13:36 PM] ESLint library loaded from: c:\Users\Username\Desktop\development\project1\node_modules\eslint\lib\api.js`

And ESLint suddenly starts workings on VScode

So my question is from where does VSCode tries to load ESLInt Library? And is there a way to specify that? I searched the settings and found nothing.

PS: Same problem (ESLint not working) happening on both Windows and MacOS

**Comment by dbaeumer** [comment]
The eslint library is loaded from the opened workspace folder.

can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by christos312** [comment]
Sure this is a test [repo ](https://github.com/christos312/vscode_eslint_test) that experience the same behavior. Its a simple test project since its happening for all projects.

[1] I open VSCode and this is what I see in the Output > ESlint
[2] Then I open PowerShell, kill all node processes and this is what I see. Then VScode starts working and underlining errors

![1](https://user-images.githubusercontent.com/1250521/69215526-a0ca2100-0b72-11ea-9403-31b474fde753.PNG)

![2](https://user-images.githubusercontent.com/1250521/69215570-bdfeef80-0b72-11ea-9a91-4fb0706086ff.PNG)

**Comment by dbaeumer** [comment]
@christos312 can you please add a package.json to the repository that list your eslint version and plugins you are using. This makes it self contained and ensures we are seeing the same behaviour.

**Comment by christos312** [comment]
Sorry for that, I have added the package.json

**Comment by dbaeumer** [comment]
This works for me without any problems.

![capture](https://user-images.githubusercontent.com/1931590/69327905-9b420900-0c4e-11ea-939f-68a4c912ac64.png)

Anything that you think could be special for you?

**Comment by christos312** [comment]
So you got the message

`ESLint library loaded from: c:\Users\Username\Desktop\development\project1\node_modules\eslint\lib\api.js`

as soon as you opened VSCode?

**Comment by dbaeumer** [comment]
Yes I did.

**Comment by christos312** [comment]
Then something is wrong with my system :/

I will have to check it. Thanks for taking the time to check this

**Comment by dbaeumer** [comment]
OK. Please ping if you find something. I will then reopen the issue.
