### ISSUE TITLE
Load workspace eslint config file for untitled files

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode-eslint#801]
If we're in a workspace, then please load the workspace's eslint config file for untitled files.

Otherwise, when we're in a workspace, and we open a new untitled file, and set the language to JavaScript, we get the following error in eslint-vscode:

```
[Warn  - 1:44:50 AM] 
No ESLint configuration (e.g .eslintrc) found for file: Untitled-1
File will not be validated. Alternatively you can disable ESLint by executing the 'Disable ESLint' command.
```

Unless there is a way to apply eslint to an untitled file, that I'm not aware of? Other than placing an eslint file in the user's home dir.

**Comment by dbaeumer** [comment]
Agree.
