### ISSUE TITLE
Mark working directory case insensitive on case insensitive file system.

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoft/vscode-eslint#804]
Hi, I know, that happens quite often, but my searches did not reveal a solution to my problem

I have following constellation:

My Frontentpart (with .eslintrc.json and node_modules) is under 

./DAP/Webkomponenten

I installed eslint & Co locally and also did a eslint --init. so everything is installed correctly. Linting a file from the command line also works. 

However, the eslint-plugin always fails when loading plugins (no matter which). When I remove "react" from my plugins, then it fails with the next one in the line.

I played around with workingdirectories and nodepath, but nothing seems to solve it (like `"eslint.nodePath": "./dap/webkomponenten/node_modules"`)

the same path in workingdirectories (of course without node_modules) also did not have any effect, even with the option for changeWorkingDirectory set to true.

Would be happy if anybody can help me

**Comment by LeopoldLerch** [comment]
Just figured it out:

It is obviously case-sensitive. is there any way, to bypass this (as windows is not really case-sensitive?)

**Comment by dbaeumer** [comment]
@LeopoldLerch I looked through the code and I couldn't find any place were I compare or access files myself. I always go through node API which is case insensitive under Windows.

I will close the issue. If you still see this please provide me with a GitHub repository I can clone that demos what you are experiencing.
