### ISSUE TITLE
Autocompletion inside package.json for tooling packages configs (e.g. eslint, babel)

### ISSUE THREAD

**Issue by doplumi** [microsoft/vscode-eslint#805]
A lot of tooling packages are now offering the capability to declare the configuration inside of `package.json`

E.g.

```
{ 
  “name”: “my-app”,
  ...,
  “esconfig”: {
    “rules”: [...],
  }
}
```

I was wondering if autocompletion inside of the file for the various tooling packages was a WIP. 

Otherwise, I’d love to produce a PR for it.
What are the modules involved with the autocompletion in this repo?

**Comment by dbaeumer** [comment]
@aeschli any tip on how to achieve this for eslint. I have the following already in my package.json

```
		"jsonValidation": [
			{
				"fileMatch": ".eslintrc",
				"url": "http://json.schemastore.org/eslintrc"
			},
			{
				"fileMatch": ".eslintrc.json",
				"url": "http://json.schemastore.org/eslintrc"
			}
		],

```

**Comment by aeschli** [comment]
Example is here: https://github.com/microsoft/vscode/blob/782f1592de7733cfbc6675300371ae8fd88bdd57/extensions/css-language-features/package.json#L792

https://github.com/microsoft/vscode/blob/782f1592de7733cfbc6675300371ae8fd88bdd57/extensions/css-language-features/schemas/package.schema.json

**Comment by dbaeumer** [comment]
@aeschli thanks. I don't want to come up with my own schema. I actually want to express that in the package.json under the `eslintConfig` property the `http://json.schemastore.org/eslintrc` schema applies. Is this possible?

**Comment by ark120202** [comment]
@dbaeumer you can use `$ref` to reference schema by url, Prettier extension uses it: https://github.com/prettier/prettier-vscode/blob/master/package-json-schema.json

**Comment by dbaeumer** [comment]
@ark120202 thanks for the pointer. Very helpful.

**Comment by tswaters** [comment]
Anyone seeking this without relying on this change can add the following to `settings.json`

```json
{
    // etc...
    "json.schemas": [
        {
            "fileMatch": [
                "package.json"
            ],
            "schema": {
                "$schema": "http://json-schema.org/draft-07/schema",
                "properties": {
                    "eslintConfig": {
                        "description": "Eslint configuration",
                        "$ref": "http://json.schemastore.org/eslintrc"
                    }
                }
            }
        }
    ]
}
```
