### ISSUE TITLE
Support new eslint suggestions API

### ISSUE THREAD

**Issue by wdoug** [microsoft/vscode-eslint#806]
Eslint has a new Suggestions API that was initially described in [this RFC](https://github.com/eslint/rfcs/pull/30/files), and recently [merged](https://github.com/eslint/eslint/pull/12384) and released in eslint [6.7.0](https://github.com/eslint/eslint/releases/tag/v6.7.0).

The suggestions API provides information for users to manually apply fixes for lint issues that don't have enough context to be auto-fixable. I think we'll want to have vscode-eslint support suggestions as a Quick Fix. Here is an example of how it would work:

```js
new RegExp("*\.js", "u")
//           ^^
//           ├ Remove the `\`. This maintains the current functionality. (no-useless-escape)
//           └ Replace the `\` with `\\` to include the actual backslash character. (no-useless-escape)
```

**Comment by dbaeumer** [comment]
I agree that adopting this in ESLint makes sense. However for auto fix on save there can't be an additional UI and for single error fixing we would simply provide both fixes as a code action.

**Comment by dbaeumer** [comment]
This would be a good candidate for a PR.
