### ISSUE TITLE
Parsing error: Unexpected token

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode-eslint#807]
This keeps happening in html files of this format https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/integrations/analytics.html

```
Parsing error: Unexpected token

> 1 | <!--
    | ^
  2 |   Copyright (c) 2016-2019 Martin Donath <martin.donath@squidfunk.com>
  3 | 
  4 |   Permission is hereby granted, free of charge, to any person obtaining a copy
```

eslintrc is here https://github.com/squidfunk/mkdocs-material/blob/master/.eslintrc

**Comment by dbaeumer** [comment]
@Stanzilla does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Stanzilla** [comment]
Yeah it works from the CLI. You can use the repo I linked above for testing

**Comment by dbaeumer** [comment]
Actually I get the same when executing it in the terminal:

<img width="627" alt="capture" src="https://user-images.githubusercontent.com/1931590/69955437-ea652500-14fd-11ea-8488-5e5f9656166b.png">


If this doesn't happen for you in the terminal when 'cding' in another directory you need to tell the extension about this using the `eslint.workingDirectories` setting.

Closing for now. Please ping of this not helpful.

**Comment by Stanzilla** [comment]
I think it might just have needed `eslint-plugin-html` is there a way to make the extension tell the user when it opens a certain filetype that needs a plugin?

**Comment by dbaeumer** [comment]
Actually, that would be something eslint itself has to do. Otherwise I start to reinterpret something that depends on the npm eslint configuration. Have you reported the idea to the eslint repository ?

**Comment by Stanzilla** [comment]
Not really, no. It does make sense that that's exactly what caused this, right?

**Comment by dbaeumer** [comment]
Yes, it does make sense.

**Comment by Stanzilla** [comment]
Alright, thank you! :)
