### ISSUE TITLE
Cannot read property 'body' of null

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode-eslint#808]
I made a .d.ts file that contains a class without constructor function body, the eslint plugin report the error message as title.

screenshot:
![Snipaste_2019-11-25_12-40-45](https://user-images.githubusercontent.com/41773861/69512893-db6ff700-0f80-11ea-89e0-6c2da27d843b.png)

**Comment by dbaeumer** [comment]
@tjx666 what happens when you validate the file in the terminal. I am pretty sure it results in the same exception since it originates from a eslint npm module. 

If it occurs in the terminal can you please report this against ESLint (see https://eslint.org/)
