### ISSUE TITLE
Support to lint files of type 'flow'

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-eslint#81]
Please see https://github.com/Microsoft/vscode-react-native/issues/85#issuecomment-222341341.

There is an eslint plugin for flow so it make sense to support it. Should the language to be linted be configurable as a setting?

**Comment by mrmckeb** [comment]
I think this could be resolved as a part of #74, which is adding TypeScript and HTML support.

**Comment by faceyspacey** [comment]
whats the status of this now that https://github.com/Microsoft/vscode-eslint/pull/74 is done?

**Comment by dbaeumer** [comment]
Follow the steps here to beta test the new extension: https://github.com/Microsoft/vscode-eslint/issues/42#issuecomment-264828064

I will close this one as a dup of #42.
