### ISSUE TITLE
No quick fix availabe

### ISSUE THREAD

**Issue by Ranguna** [microsoft/vscode-eslint#816]
There are lot's of closed issues in the repo about this but this problem still persists.

The image bellow shows an example of this bug. I have the `quotes` rule enabled to use single quotes and vscode doesn't show any quick fix.

![image](https://user-images.githubusercontent.com/5003755/69913743-c63d1180-1433-11ea-8a40-4df5fd31f10d.png)

I'm using vscode 1.40.2, the latest version of the eslint extension and eslint package.

Here's the output of the eslint console in vscode:
```
[Info  - 12:04:04] ESLint server stopped.
[Info  - 12:04:06] ESLint server running in node v12.4.0
[Info  - 12:04:06] ESLint server is running.
[Info  - 12:04:11] ESLint library loaded from: /home/me/some/project/folder/node_modules/eslint/lib/api.js
```

**Comment by dbaeumer** [comment]
This is addressed with the next version of ESLint. If you want to help me to test it, please see: https://github.com/microsoft/vscode-eslint/issues/815

**Comment by Ranguna** [comment]
Will do, thanks.
