### ISSUE TITLE
自动插入分号

### ISSUE THREAD

**Issue by Terryzjn** [microsoft/vscode-eslint#817]
Issue Type: <b>Bug</b>

自动插入分号没有办法关闭。试了很多种方法。放弃了

Extension version: 1.9.1
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
Can you please provide a GitHub repository I can clone that demos the problem you are seeing. Otherwise it is very hard to react on this.
