### ISSUE TITLE
ESlint easy for the user to not notice it is misconfigured

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-eslint#819]
Refs: https://github.com/microsoft/vscode/issues/85933

As specified in https://github.com/microsoft/vscode/issues/85933 when the workspace has eslint misconfigured the eslint extension is pretty quite and not in the users face complaining. I personally like this, however due to this it is easy for the user to not be aware that eslint is misconfigured.

I suggest the following, if the user triggers ES Lint: Enable -> you currrently say "ES Lint is already enabled". If the user is triggering this action it is pobaably because es lint is not working. So in that case I would expect that at least the ES Lint output gets shown.

Similarly if I do ES Lint: Configure -> you currently say " there is already a configuration". I suggest that you could open the eslint configuration file.

**Comment by dbaeumer** [comment]
This got all reworked with the new ESLint status item and the library confirmation (e.g. `Enable ESLint` is basically gone). I will close the issue and will react on the feedback I get for the new status item.
