### ISSUE TITLE
eslint can't not find the module "babel-eslint" when I have installed the module babel-eslint?

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-eslint#82]
_From @fantasyKing on June 2, 2016 2:57_

- VSCode Version:latest
- OS Version:mac os x

Steps to Reproduce:

1. I install the extension eslint for vsc,and write parser : "babel-eslint" after I have installed babel-eslint locally,but the eslint extension reminds me that can't find the module babel-eslint?

_Copied from original issue: Microsoft/vscode#7113_

**Comment by dbaeumer** [comment]
You need to have both eslint and babel eslint installed either globally or locally. Mixing it will not work. See https://github.com/Microsoft/vscode-eslint/issues/2.

If this is not the case for you can you please share your workspace. I tried it locally and I can run eslint with babel-eslint installed.

**Comment by radiosilence** [comment]
I'm also getting this issue on OSX. I don't have babel, babel-eslint, or eslint installed system wide.

Here's a repo that this happens in:

https://github.com/radiosilence/LintTest


Here's an LS of my *system* node packages:

    flow-bin
    gulp
    jscodeshift
    mocha
    node-dir
    node-static
    now
    now-serve
    npm
    npm-check-updates
    pouchdb-server
    prettyjson
    webpack
    webpack-bundle-size-analyzer
    webpack-dev-server

**Comment by dbaeumer** [comment]
@radiosilence thanks for the test case. Here is what I see using the workspace:

![capture](https://cloud.githubusercontent.com/assets/1931590/16263037/8cf0bb70-3872-11e6-887a-f9187ad36689.png)

The interesting finding is that aribnb plugin list eslint-plugin-jsx-a11y as a dev dependencies which doesn't install it when running npm install in the root.

**Comment by dbaeumer** [comment]
Running npm run lint on a command line results in the same problem:

![capture](https://cloud.githubusercontent.com/assets/1931590/16263127/fd6ada48-3872-11e6-9a30-1d7136cde62f.png)

@radiosilence any additional information / steps.

**Comment by radiosilence** [comment]
Did you run an `npm install` ?

**Comment by dbaeumer** [comment]
@radiosilence yes I did. However I used node > 6.x which uses an npm version that doesn't install peer dependencies by default (eslint-plugin-jsx-a11y is listed as a dev and peer dependency in airbnb). Which node version are you using?

**Comment by dbaeumer** [comment]
Here is what I see on npm install:
```
npm WARN peerDependencies The peer dependency eslint-plugin-jsx-a11y@^1.2.0 included from eslint-config-airbnb will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint-plugin-import@^1.7.0 included from eslint-config-airbnb will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint-plugin-import@^1.7.0 included from eslint-config-airbnb-base will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by radiosilence** [comment]
Ah, I'm using node LTS (v4.4.5) at the moment. Perhaps I've pushed a fix that has eslint-plugin-jsx-a11y in the deps.

**Comment by dbaeumer** [comment]
I will close this issue since there is nothing I can do. NPM doesn't install peer dependencies anymore and eslint-plugin-jsx-a11y is not listed as a normal dependency.
