### ISSUE TITLE
ES Lint not reacting to changes in eslint configuratino files

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-eslint#820]
Refs https://github.com/microsoft/vscode/issues/85933

1. Use the workspace https://github.com/microsoft/vscode-eslint/tree/2.0.1-next.1/playgrounds/ts
2. Change the `eslint.base.json` to have something invalid
3. Reload the workspace -> notice how eslint properly does not detect any errors (since it is misconfigured). Fix the `eslint.base.json`. In order for eslint to start working I have to reload. It should pick up the changes on the fly ideally

Also note that if I break `eslintrc.json` the eslint errors will remain in the problems view forever. I would expect if eslint setup gets broken that all errors get removed.

**Comment by sana-ajani** [comment]
Yeah, agreed here. If I have ESlint enabled, I'd like for the problems view to pick up when I fix the .eslintrc

**Comment by dbaeumer** [comment]
The plugin does react to changes in `.eslintrc*` file which are the normal ESLint setup files. The `eslint.base.json` was my name choice and someone else could name this `xyz.json`. 

I could make this a setting put this feels like an overkill. Given that `.eslintrc*` file work any objection to close as wont fix?

**Comment by isidorn** [comment]
I noticed that the .eslintrc files you watch. However the `eslint.base.json` is specified in the `.eslintrc`. Can we not auto detect this?

**Comment by dbaeumer** [comment]
ESLint has quite some rules and different file type which I would all need to understand and reimplement how the resolving works in them. In addition users usually reach to a base config that is outside of the workspace (in some home directory) which I can't watch anyways. The example I gave you is very unusual :-).

**Comment by isidorn** [comment]
Ok, thanks for explanation. It is fine to close as will not fix as far as I am concerned.

**Comment by dbaeumer** [comment]
Thanks @isidorn. Closing then.
