### ISSUE TITLE
Incorrent trigger of react/no-unused-state when using optional chaining operator

### ISSUE THREAD

**Issue by papadi** [microsoft/vscode-eslint#821]
If a state variable is used only with the optional chaining operator, like this:
`this.state?.something`
then the following will trigger the "react/no-unused-state" rule:
`this.setState({ something });`

**Comment by dbaeumer** [comment]
@papadi please report this to the owner of the rule. The ESLint extension is relying in ESLint (https://eslint.org/) itself and doesn't implement its own rules.
