### ISSUE TITLE
ESLint Plugin warnings don't match npm run lint output

### ISSUE THREAD

**Issue by patrickliechty** [microsoft/vscode-eslint#822]
I need to get my output to match.

The ESLint Plugin is saying my indent is wrong in a javascript file (IIFE), but Node eslint says it is ok.  Both are using my .eslintrc.json file.  I did not do any custom settings to the ESLint Plugin except to add the same task options as my package.json script file which is this:

    "lint": "eslint --cache --ignore-path .gitignore ./**/*.html ./**/*.js && polymer lint"

So I added the same options to the settings.json here:

    "eslint.lintTask.options": "--cache --ignore-path .gitignore ./**/*.html ./**/*.js && polymer lint"

This was my attempt to get the same output from both.  It didn't work.

ESLint Plugin version: 1.9.1. 
VSCode version: 1.40.2
Node eslint version: 4.19.1
Node eslint-plugin-html: 4.0.6
Node eslint-plugin-jsdoc: 3.9.0

**Comment by dbaeumer** [comment]
@patrickliechty are you validating the files using a task inside VS Code (e.g. executing a task) or are you relying on live validation in the editor. If the second you need to use the `eslint.options` setting to customize the linting.

If this doesn't help please provide me with a GitHub repository I can clone the demonstrates what you are experiencing.
