### ISSUE TITLE
`Fix all auto-fixable Problems` doesn't yield the same result as `eslint file.js --fix`

### ISSUE THREAD

**Issue by mmahdigh** [microsoft/vscode-eslint#823]
I have configured ESLint for an already written project, but the problem is when I click `Fix all auto-fixable Problems` it doesn't do a great job of fixing indents whereas running `eslint file.js --fix` does it well (to be precise sometimes after two times of running it ).

Below is a code sample with which `Fix all auto-fixable Problems` doesn't work well:

        <LanguageContext.Consumer>
            {(value) => {
                const vocabs = getTranslator(value.language);
                return (
                    <Grid container direction="row"
                          justify="center" alignItems="center">
                        <ButtonGroup size={"small"}>
                            <Button variant={props.authFormState === 'login' ? 'contained' : 'outlined'} color='primary'
                                    className={props.authFormState === 'login' ? classes.disabledButtonRight : classes.switchButtonRight}
                                    onClick={changeFormStateToLogin}>
                                {vocabs('login')}
                            </Button>
                            <Button variant={props.authFormState === 'register' ? 'contained' : 'outlined'} color='primary'
                                    className={props.authFormState === 'register' ? classes.disabledButtonLeft : classes.switchButtonLeft}
                                    onClick={changeFormStateToRegister}>
                                {vocabs('register')}
                            </Button>
                        </ButtonGroup>
                    </Grid>
                )
            }}
        </LanguageContext.Consumer>

**Comment by dbaeumer** [comment]
This got addressed for the next version of ESLint. Pls see https://github.com/microsoft/vscode-eslint/issues/815 if you want to help test this.

**Comment by dbaeumer** [comment]
2.0.4 now shipped.
