### ISSUE TITLE
Provide quick fix for prettier suggestions

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode-eslint#824]
You [can run `prettier` through ESLint](https://prettier.io/docs/en/integrating-with-linters.html) and it works very well, *except* it gives you quite hard to understand instructions. For example:

![image](https://user-images.githubusercontent.com/376842/70459562-528eaa80-1aac-11ea-883f-1b9882804c5d.png)

Normally I ignore these and fix them later via `npm run lint` which does some kind of magic to automatically fix them. However it would be better if it provided a quick fix to do it for you in VSCode.

I'm not sure if #806 would solve this - that task says it is for ambiguous fixes which this isn't.

**Comment by dbaeumer** [comment]
@Timmmm this should be addressed with the new version since it will execute the same code path as  `eslint --fix`. 

Can you please test this as soon as I have released the new version which should happen the next couple of days.

**Comment by Timmmm** [comment]
Excellent, will do!

**Comment by dbaeumer** [comment]
Let me know how it goes.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode-eslint/issues/830
