### ISSUE TITLE
improve out of the box support for coffeescript

### ISSUE THREAD

**Issue by AntonioMeireles** [microsoft/vscode-eslint#825]
Hi all, 

there's now on `eslint`'s (and `prettier`'s btw) ecosystem side proper support for **coffeescript** per @helixbass 's **[eslint-plugin-coffee](https://github.com/helixbass/eslint-plugin-coffee)**  and **[prettier-plugin-coffeescript](https://github.com/helixbass/prettier-plugin-coffeescript)** ongoing (great) work.

This is all good and things work out of the box mostly on `vscode-eslint` side almost fully except in one case - when an issue pops, when quickfixing it *if* one wants to disable affected line or next one (calls to [`eslint.{createDisable{,Same}LineTextEdit}`](https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1456-L1462)) the inserted comment (with hints to `eslint`) is inserted with the wrong (from coffeescript's point of view) syntax, since `vscode-eslint` has   (on  https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1456-L1462) the comment _style_ hardcoded.

So, i'd plead you to refactor that part a bit so that the comment prefix (`//` in general vs `#` for coffeescript dialects) would be infered from the actual language being linted and not just assumed unconditionally to be `//` which in coffeescript's  case is definitively not true. 

thanks in advance and keep the awesome work :-) 

All the Best

António

**Comment by dbaeumer** [comment]
A PR would be welcome here.

**Comment by AntonioMeireles** [comment]
@dbaeumer, thanks for the quick reply.  Sadly, i'm not privy with vscode's internals nor with typescript (sorry). fwiw and afaics on a quick glance all it is needed is to look at files's `languageId` and in `eslint.{createDisable{,Same}LineTextEdit}` turn the comment style conditional on it.

**Comment by helixbass** [comment]
@AntonioMeireles ok opened #857, thanks for the pointer to the right spot in the source code to modify
