### ISSUE TITLE
Code Helper (Render) processes not quitting

### ISSUE THREAD

**Issue by ajoslin103** [microsoft/vscode-eslint#826]
I see Code Helper (Render) processes not quitting when dealing with large files

Steps to Reproduce:

1. open a .js file containing a large object (attached) 

[datasets-RI.js.zip](https://github.com/microsoft/vscode-eslint/files/3965102/datasets-RI.js.zip)

2. wait for Code Helper (Render) process to climb
3. see that the Code Helper (Render) process doesn't quit

Does this issue occur when all extensions are disabled?: Not reproducibly

This is the extension that causes the problem

vscode-eslint | dba | 1.9.1

--- system information ---

CPUs | Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 3, 3, 3
Memory (System) | 16.00GB (0.03GB free)
Process Argv |  
Screen Reader | no
VM | 0%

--- extensions information ---

Extension | Author (truncated) | Version
-- | -- | --
markdown-toc | Ala | 1.5.6
markdown-extension-pack | bat | 0.3.0
Aurelia | beh | 1.2.2
markdown-emoji | bie | 0.0.9
path-intellisense | chr | 1.4.2
markdown-table-prettify | dar | 2.4.0
vscode-markdownlint | Dav | 0.32.0
vscode-eslint | dba | 1.9.1
xml | Dot | 2.5.0
vscode-surround-with | drc | 1.1.3
vscode-babel-coloring | dza | 0.0.4
EditorConfig | Edi | 0.14.3
mdmath | goe | 2.4.0
todo-tree | Gru | 0.0.162
json-to-ts | Mar | 1.5.5
rainbow-csv | mec | 1.3.1
vscode-language-babel | mgm | 0.0.25
formate | Mik | 1.1.3
vscode-html-format | moh | 0.0.3
vscode-docker | ms- | 0.9.0
remote-containers | ms- | 0.94.0
remote-ssh | ms- | 0.48.0
remote-ssh-edit | ms- | 0.48.0
remote-ssh-explorer | ms- | 0.48.0
remote-wsl | ms- | 0.41.5
vscode-remote-extensionpack | ms- | 0.19.0
atom-keybindings | ms- | 3.0.6
vscode-typescript-tslint-plugin | ms- | 1.2.3
vsliveshare | ms- | 1.0.1377
debugger-for-chrome | msj | 4.12.3
edit-with-shell | ryu | 1.2.0
vscode-gtm | s3r | 0.2.0
markdown-preview-enhanced | shd | 0.5.0
quokka-vscode | Wal | 1.0.265
change-case | wma | 1.0.0
markdown-pdf | yza | 1.4.1
markdown-all-in-one | yzh | 2.6.1

**Comment by dbaeumer** [comment]
I can not reproduce this using a basic ESLint setup. Can you please provide me with a GitHub repository I can clone that demos what you are experiencing. Here is what I see:

<img width="713" alt="capture" src="https://user-images.githubusercontent.com/1931590/70895328-09c87b80-1fef-11ea-87bc-7f2dd65c25af.png">

**Comment by ajoslin103** [comment]
I'm sorry I may not have been clear -- the ESLint plugin does it's job wonderfully and always performs very well, I depend on it and it works fine.

The problem is that for some reason the Code Helper (Render) process that does the work for the ESLint extension proceeds to take up more and more cpu -- even after the offending file has been closed it just keeps working on it.  The process has to be killed, it doesn't die or slow down.

I use the react-boilerplate framework, here is the .eslint.js file they provide.  

Thank you for your time and attention.

```
const fs = require('fs');
const path = require('path');

const prettierOptions = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, '.prettierrc'), 'utf8'),
);

module.exports = {
  parser: 'babel-eslint',
  extends: ['airbnb', 'prettier', 'prettier/react'],
  plugins: ['prettier', 'redux-saga', 'react', 'react-hooks', 'jsx-a11y'],
  env: {
    jest: true,
    browser: true,
    node: true,
    es6: true,
  },
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  rules: {
    'prettier/prettier': ['error', prettierOptions],
    'arrow-body-style': [2, 'as-needed'],
    'class-methods-use-this': 0,
    'import/imports-first': 0,
    'import/newline-after-import': 0,
    'import/no-dynamic-require': 0,
    'import/no-extraneous-dependencies': 0,
    'import/no-named-as-default': 0,
    'import/no-unresolved': 2,
    'import/no-webpack-loader-syntax': 0,
    'import/prefer-default-export': 0,
    indent: [
      2,
      2,
      {
        SwitchCase: 1,
      },
    ],
    'jsx-a11y/aria-props': 2,
    'jsx-a11y/heading-has-content': 0,
    'jsx-a11y/label-has-associated-control': [
      2,
      {
        // NOTE: If this error triggers, either disable it or add
        // your custom components, labels and attributes via these options
        // See https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-associated-control.md
        controlComponents: ['Input'],
      },
    ],
    'jsx-a11y/label-has-for': 0,
    'jsx-a11y/mouse-events-have-key-events': 2,
    'jsx-a11y/role-has-required-aria-props': 2,
    'jsx-a11y/role-supports-aria-props': 2,
    'max-len': 0,
    'newline-per-chained-call': 0,
    'no-confusing-arrow': 0,
    'no-console': 1,
    'no-unused-vars': 2,
    'no-use-before-define': 0,
    'prefer-template': 2,
    'react/destructuring-assignment': 0,
    'react-hooks/rules-of-hooks': 'error',
    'react/jsx-closing-tag-location': 0,
    'react/forbid-prop-types': 0,
    'react/jsx-first-prop-new-line': [2, 'multiline'],
    'react/jsx-filename-extension': 0,
    'react/jsx-no-target-blank': 0,
    'react/jsx-uses-vars': 2,
    'react/require-default-props': 0,
    'react/require-extension': 0,
    'react/self-closing-comp': 0,
    'react/sort-comp': 0,
    'redux-saga/no-yield-in-race': 2,
    'redux-saga/yield-effects': 2,
    'require-yield': 0,
  },
  settings: {
    'import/resolver': {
      webpack: {
        config: './internals/webpack/webpack.prod.babel.js',
      },
    },
  },
};

```

**Comment by dbaeumer** [comment]
@ajoslin103 could you please provide me with a GitHub repository I can clone. This very likely also depends on the eslint and eslint plugin versions you are using. Do you see the same behavior if you disable the eslint plugins (e.g. `plugins: ['prettier', 'redux-saga', 'react', 'react-hooks', 'jsx-a11y']`). 

The ESLint extension at the end loads the eslint npm module so I am almost confident that this is more a problem with ESLint or one of it plugins than the extension itself.
