### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by vjancik** [microsoft/vscode-eslint#827]
Hi, I'm trying to use Typescript with ESLint in VSCode.

The problem si two-fold:
1. The ESLint extension doesn't initialize when opening `.ts` files. Only `.js`.
2. The extension doesn't seem to be respecting `eslint.options` nor `eslint.lintTask.options`. I've tried both:
```json
"eslint.packageManager": "yarn",
"eslint.lintTask.options": "--ext .ts,.tsx .",
"eslint.lintTask.enable": true,
"eslint.options": {
     "extensions": [".ts", ".tsx", ".js", ".jsx"]
 }
```
The extension still doesn't run on `.ts` files. But it still runs on `.js` files even if I remove the extensions from these commands, unless I blacklist `*.js` in `.eslintignore`

### Context
I'm running VSCode Insiders build, Extension version `1.9.1` and using `yarn` local `eslint` installation which works as expected when running through `yarn run lint`

Is this known? I couldn't find similar issues?
Thank you!

**Comment by larshp** [comment]
Same problem, guess https://github.com/microsoft/vscode-eslint#using-eslint-to-validate-typescript-files is required

But yea, https://code.visualstudio.com/updates/v1_41#_eslint says its not required anymore, but the changes mentioned in https://github.com/microsoft/vscode/issues/85933 is not part of the latest release of the extension

🤔

**Comment by vjancik** [comment]
That solved the issue. It's still worth noting however, that those config options that are perfectly valid (worked in command line) got ignored.

**Comment by dbaeumer** [comment]
@vjancik  @larshp: Please see https://github.com/microsoft/vscode-eslint/issues/815 which ask for feedback for the new ESLint version which will be released soon.
