### ISSUE TITLE
Suggestion for README: include formatter settings for settings.json

### ISSUE THREAD

**Issue by sfsccn** [microsoft/vscode-eslint#829]
For some reason my ESLint formatter got lost when I was using the pre-release. In the 2.0.4 release the "select a default formatter for JavaScript file" dialog inserts this into settings.json when ESLint is selected:

`"[javascript]": {
        "editor.defaultFormatter": "dbaeumer.vscode-eslint"
}`

I assume this need to be set in addition to `"eslint.format.enable": true`, is that right? If so, then maybe include this in the README just to be safe.

**Comment by dbaeumer** [comment]
Good point. Updated the readme. To see it in VS Code we need a new version of the extension.
