### ISSUE TITLE
eslint tips: Create missing module file: 'gulp.js'

### ISSUE THREAD

**Issue by lslz627** [microsoft/vscode-eslint#83]
- VSCode Version: latest
- OS Version: mac os x
- npm install -g eslint
- npm install -g babel-eslint 

I met a mistake like this.

![gulp](https://cloud.githubusercontent.com/assets/18484770/15804813/2fdc1d1c-2b48-11e6-89fd-94b4abdf0173.png)

my `.eslintrc`: 

``` javascript
module.exports = {
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": true
    },
    globals: {
    },
    "parser": "babel-eslint",
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true,
            "modules": true
        },
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            2
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ],
        "no-console": 0
    },
};
```

Anybody ever met before？ Thanks!

**Comment by dbaeumer** [comment]
@ritayzy the screenshot is from sublime. Do you want the same feature from VS Code. Or is something not working in VS Code?

**Comment by ritayzy** [comment]
@dbaeumer  It's the later, something not working in VS Code. i use es6's syntax `import`, when i import a library, for example `gulp`, it's not the end of `.js`, vscode will prompt the info.

```
os version: 10.11.3
vscode version: 1.2.1 (1.2.1)
node version: v6.3.0
```

Thank you for your reply.
