### ISSUE TITLE
Explain the difference between using ESLint as a formatter and formatting on save vs running ESLint through codeActionsOnSave

### ISSUE THREAD

**Issue by hrastnik** [microsoft/vscode-eslint#835]
Since the 2.0.4 update I've noticed there are two approaches to getting ESLint to run when the file is saved. These are the contents of the VSCode's `settings.json` file:

Approach 1.
```json
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
```

Approach 2. 
```json
  "eslint.format.enable": true,
  "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  "editor.formatOnSave": true,
```

Is there a difference between the two approaches? Is there a preferred method between the two?

The documentation on this could be improved.

**Comment by dbaeumer** [comment]
Good question:

The recommended way is `editor.codeActionsOnSave` since it allows for better configurability. Format on save is either on or off. Code action on save can be configured differently for n providers. I updated the readme.
