### ISSUE TITLE
forcing codeActionsOnSave config in settings.json

### ISSUE THREAD

**Issue by narnia1991** [microsoft/vscode-eslint#836]
this is getting added.

"editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    }

code cannot be removed in settings.json

**Comment by dbaeumer** [comment]
The reason is that you have `"eslint.autoFixOnSave": true` in your setting. To preserve the feature with the new code action on save implementation the setting gets added. If you remove `"eslint.autoFixOnSave": true` the setting will not be added.

**Comment by dbaeumer** [comment]
Please ping if this is not the case for you and provide steps on how to reproduce. Thanks!

**Comment by narnia1991** [comment]
Thanks about that.
