### ISSUE TITLE
crashing while restarting the vscode after installing Eslint

### ISSUE THREAD

**Issue by itsparser** [microsoft/vscode-eslint#837]
Issue Type: <b>Bug</b>

* i have add es-lint extentsion into my vscode
* In my project i have es-lint in root folder and src folder 
* which make the lint to run in recrussion 

Extension version: 1.9.1
VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 9, 7|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@itsparser can you please provide me with a GitHub repository I can clone that demos that. I can not reproduce this.

**Comment by itsparser** [comment]
@dbaeumer, sorry it private repo and this accrue for the first time once I restarted my vs code it working now, so I am closing this ticket, thanks a lot
