### ISSUE TITLE
how to silence warnings about ignored files in eslint?

### ISSUE THREAD

**Issue by AlgusDark** [microsoft/vscode-eslint#838]
After upgrade, the plugin is showing:
```
File ignored because of a matching ignore pattern. Use "--no-ignore" to override.eslint
```

Yes, it's included in `.eslintignore` but in my `eslintrc` I added to `project` a new `tsconfig` that adds that file.

Before the update was working linting as expected, but with change now isn't working anymore.

**Comment by dbaeumer** [comment]
I already started looking into this and I agree that you should be able to silence this.
