### ISSUE TITLE
Please mention editor.codeActionsOnSave > source.fixAll.eslint in the settings.json autoconverter popup

### ISSUE THREAD

**Issue by cb109** [microsoft/vscode-eslint#839]
As I understand the former `eslint.autoFixOnSave` has been deprecated and now we should use `editor.codeActionsOnSave` with a key of `source.fixAll.eslint` instead. That's fine, but the current way the settings.json file is converted automatically can be quite confusing.

If the old `eslint.autoFixOnSave` is present in settings.json, a new `editor.codeActionsOnSave` is added automatically to the end of that settings file. Trying to toggle that new option is very confusing, as its value is forced from the deprecated setting:

![Peek 2019-12-17 15-35](https://user-images.githubusercontent.com/6052590/71005216-8b013a80-20e3-11ea-8958-faaf4a98535c.gif)

The popup however does not mention the new setting (`source.fixAll.eslint`) at all, whereas the README linked in the popup does not mention the old setting at all (`autoFixOnSave`). We are left to make that connection ourselves somehow, which can be tough if you rarely ever touch these settings.

I think just adding those mentions would help a lot with "transitioning" settings like this. 

Thanks!

**Comment by dbaeumer** [comment]
@cb109 very good catch and suggestion. I should document that in the read me and in addition don't convert if the setting is set actively to false.

**Comment by dbaeumer** [comment]
I added a confirmation dialog to inform the user about the conversion.
