### ISSUE TITLE
Errors in Untitled files stay around

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-eslint#84]
_From @joaomoreno on June 6, 2016 9:26_

1. Create a new Untitled file
2. Type `const hello;` in it
3. Change its mode to JavaScript
4. Close the file, don't save

There is an error laying around in the Problems view

_Copied from original issue: Microsoft/vscode#7244_

**Comment by dbaeumer** [comment]
Will investigate. Very likely the tsserver not cleaning up correctly.

**Comment by dbaeumer** [comment]
This is ESLint.

**Comment by fantacytyx** [comment]
VSCode: 1.3.0-insiders, Commit:716f76, Data:2016-07-01
ESLint: 0.10.17

File was deleted, but the error message still stay in the Problems view

![image](https://cloud.githubusercontent.com/assets/8966236/16514573/446868c4-3f9f-11e6-9caf-e12060dcbdb5.png)

**Comment by dbaeumer** [comment]
This got addressed with eslint 0.10.18
