### ISSUE TITLE
Eslint isn't running on save

### ISSUE THREAD

**Issue by dokugo** [microsoft/vscode-eslint#841]
Since the 2.0.4 release eslint is running only when I try to «double save». What I mean is, first I edit the file, then I press `ctrl+s` and instead of autofix eslint just starting to show an error without doing any fixes. Magically error is being fixed if I press `ctrl+s` again.

Demonstration: https://streamable.com/1qciz
First I spam some spaces, then save and see an error in the "problems" tab at the bottom bar. Then I `ctrl+s` again and the error fixes.

Relevant settings:
```
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "eslint.run": "onSave",
}
```

**Comment by dbaeumer** [comment]
You might need to increase the `editor.codeActionsOnSaveTimeout` setting (see also https://github.com/microsoft/vscode-eslint#release-notes). If this doesn't help can you provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by AbdelrahmanHafez** [comment]
@dbaeumer 
I am not sure I know what an example of a GitHub repo that can help you reproduce the issue would look like, but here is a video explaining the issue further. Hope it helps.

https://streamable.com/fhx78

**Comment by dokugo** [comment]
@dbaeumer
Increasing the `editor.codeActionsOnSaveTimeout` doesn't help.
I was recording a demonstration with [this](https://github.com/dokugo/getajob) repo opened in VS Code (but I'm experiencing the same eslint behaviour in any project).

**Comment by dbaeumer** [comment]
@dokugo: I cloned the repository you provided and can't reproduce this after adding the setting

```
	"editor.codeActionsOnSave": {
		"source.fixAll.eslint": true
	}
```` 

Please note that fix on save (as previous) is not enabled when auto save is on. If you have auto save on you need to press Ctrl+S to get the fixes applied.

**Comment by dbaeumer** [comment]
![cast](https://user-images.githubusercontent.com/1931590/71103981-637da100-21bb-11ea-8ef4-6d956450cdf1.gif)

**Comment by dbaeumer** [comment]
In the above video I pressed Ctrl+S to trigger the fixing.

**Comment by dbaeumer** [comment]
Any additional information you can provide?

**Comment by dokugo** [comment]
If I have only the following setting (the same setting as yours) everything works fine.
```
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
}
````
But if I add `"eslint.run": "onSave"` there comes that "double save" problem. My main concern is that I don't want ESLint running `onType`.

**Comment by vincaslt** [comment]
So for me, the new option did not work on save, but when I executed the command manually, sometimes it worked. I found that if I increase the allowed time for autofix, it works. So my guess it just slowed down a lot?

```
"editor.codeActionsOnSaveTimeout": 5000,
  "editor.codeActionsOnSave": {
    "source.fixAll": true,
  }
```

**Comment by dbaeumer** [comment]
@vincaslt the reason why fix on save got slower is that it is more complex to ensure that all auto fixable problems get fixed. ESLint (the npm module) uses an n path approach to compute all possible fixes. In the past I only did one pass leaving a lot of problems not fixed. The new approach ensures that all n paths are executed.

**Comment by dbaeumer** [comment]
@dokugo now I see. I think I can fix this :-)
