### ISSUE TITLE
Doesn't work with external config file from node module

### ISSUE THREAD

**Issue by skaraman** [microsoft/vscode-eslint#842]
I have my own eslint config that is hooked into .eslintrc.js ->
`extends: ['eslint-config-myconfig']`

this causes an error to be thrown in VSCode, note that the same setup works in Atom.io

```Failed to load plugin 'promise' declared in 'myProject/.eslintrc.js » eslint-config-myconfig': Cannot find module 'eslint-plugin-promise' Require stack: - /Users/{...myWorkspace}/__placeholder__.js Referenced from: /Users/{...myWorkspace}/{...myProject}/node_modules/eslint-config-myconfig/index.js```

**Comment by dbaeumer** [comment]
@skaraman can you please provide me with a GitHub repository I can clone that demos what you are experiencing. Thanks.

**Comment by skaraman** [comment]
@dbaeumer setting up a repo isn't something i can do just to preserve my project integretity but you can reproduce this issue by using https://www.npmjs.com/package/eslint-config-synacor in a project, it follows the same principles, please review the readme

**Comment by dbaeumer** [comment]
@skaraman my experience shows that bugs like this depend on many things, especially on workspace settings and versions used. So I would highly appreciate if you could provide me with reproducible steps.

If you use eslint from the terminal validating that file from the workspace folder (e.g. the folder you have open in VS Code) will it succeed ? Or do you need to do a cd into one of the sub folders. If so you need to tell eslint about these working directories using the `eslint.workingDirectories` setting.

**Comment by skaraman** [comment]
@dbaeumer 
I've setup a test repo here - https://github.com/skaraman/test
Current behavior 
![current](https://user-images.githubusercontent.com/2840020/71929786-39caf080-314f-11ea-88fc-01f17a2d1dc2.jpg)
![error](https://user-images.githubusercontent.com/2840020/71929784-39caf080-314f-11ea-8119-eba7e63e386c.jpg)

Expected behavior
![expected](https://user-images.githubusercontent.com/2840020/71929783-39caf080-314f-11ea-8f93-b27a271c0e2e.jpg)

I don't think it's an issue with workingDirectories but if it is, please let me know again

**Comment by dbaeumer** [comment]
@skaraman can you please had a eslintrc config file. Otherwise it is hard to tell what is going wrong.

I do see errors with my eslint configuration.

![capture](https://user-images.githubusercontent.com/1931590/71968345-021e8000-3205-11ea-9ac7-6285b3c3b7a3.png)

**Comment by skaraman** [comment]
The issue is that the config file is in a node module. Why don’t I need esconfig in atom? What is your configuration file?

**Comment by dbaeumer** [comment]
This is what I see in VS Code

![capture](https://user-images.githubusercontent.com/1931590/72004502-d70b4f00-324b-11ea-8826-c4189232d094.png)

and this when running eslint in a terminal:

![capture](https://user-images.githubusercontent.com/1931590/72004545-edb1a600-324b-11ea-96a7-a21ea5e43d5b.png)

which is the same result. I am not sure what atom does but I try to stay as close as possible to what happens when running eslint from the terminal.

**Comment by dbaeumer** [comment]
What do you see when you run eslint from the terminal ?

**Comment by skaraman** [comment]
Hi @dbaeumer I see correct errors in terminal <img width="756" alt="Screen Shot 2020-01-08 at 10 41 59 AM" src="https://user-images.githubusercontent.com/2840020/72008828-83781180-3209-11ea-8f8d-f32a1ac5a137.png">

but i also see this output from eslint saying failed to load 'compat'
<img width="1424" alt="Screen Shot 2020-01-08 at 11 24 49 AM" src="https://user-images.githubusercontent.com/2840020/72008829-83781180-3209-11ea-96ad-fc91b41dd1cc.png">

**Comment by dbaeumer** [comment]
Can you run in the terminal with --debug to see which config files are read and provide them to me as well (best in the GitHub repository so we are using the same config)

**Comment by skaraman** [comment]
there's a lot of output so i put it in a txt file, all the config is in the node modules so you should have it with npm i and i'm not sure which files you need (if you still need some let me know which ones from the output.txt) , i don't have eslint installed globally either
[debug_output.txt](https://github.com/microsoft/vscode-eslint/files/4037343/debug_output.txt)

**Comment by dbaeumer** [comment]
Actually comparing your output with mine reports exactly the same errors and for me they are even correctly reported in VS Code itself. I have actually no idea why in you setup the  `compat` plugin can not be loaded.  On which folder do you open the workspace ?

**Comment by skaraman** [comment]
you figured it out!
the workspace i have is setup on a 'dev' root of my own, then i have subfolders for projects, then i have subfolders for branches (you should be able to see by the smudges in the screenshot above), when i open the branch in the workspace as the root, the eslint plugin works and reports errors correctly 
<img width="604" alt="Screen Shot 2020-01-09 at 9 50 16 AM" src="https://user-images.githubusercontent.com/2840020/72091623-7882b700-32c5-11ea-8adc-5bc3f8b58847.png">

**Comment by skaraman** [comment]
@dbaeumer Altought changing the workspace solves the issue, i would appreciate it if you could try to resolve the issue when there are high up folders, i would like to have a workspace where i can have project folders as some of my projects are like this :
myProject1/oneBranch
myProject1/twoBranch
myProject2/oneBranch
myProject2/twoBranch

if i have two of these same branches set at the roots it's hard to tell what branch is from what project

**Comment by dbaeumer** [comment]
@skaraman have a look at the `eslint.workingDirectories` setting which allows you to customize these setups (https://github.com/microsoft/vscode-eslint#settings-options).  They new `[{ "mode": "auto" }]` might be your friend here.
