### ISSUE TITLE
ESLINT is changing a setting without my permission

### ISSUE THREAD

**Issue by Andriy-Kulak** [microsoft/vscode-eslint#844]
Every time it's trying to alter the file automatically. wtf is going on. It's blocking me from pulling from origin because I have an uncommitted change (that's already origin).

<img width="1340" alt="Screen Shot 2019-12-18 at 9 20 25 AM" src="https://user-images.githubusercontent.com/12179976/71093763-d5cc9200-2177-11ea-90af-6c4d4a1e01c7.png">

 Please stop automatically updating settings that can affect commits...

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode-eslint/issues/840.

I am working on a confirmation dialog before I write the settings.
