### ISSUE TITLE
Version 2.x doing nothing

### ISSUE THREAD

**Issue by p3k** [microsoft/vscode-eslint#849]
I noticed my files are not being validated by the ESLint plugin after upgrade to version 2.x.

![image](https://user-images.githubusercontent.com/16631/71177390-31784780-226c-11ea-928d-22ed3b68d1ea.png)

![image](https://user-images.githubusercontent.com/16631/71177414-3fc66380-226c-11ea-967a-e1f8affa8f86.png)

When I downgrade to 1.x linting works as expected again.

![Screenshot 2019-12-19, 14 28 36](https://user-images.githubusercontent.com/16631/71177328-10175b80-226c-11ea-9106-39318bb2cdf4.png)

![image](https://user-images.githubusercontent.com/16631/71177307-04c43000-226c-11ea-9666-b9d22611b606.png)

**`.eslintrc`:**

```plain
{
	"env": {
		"amd": true,
		"browser": true,
		"es6": true
	},
	"parserOptions": {
		"ecmaVersion": 6,
		"sourceType": "module"
	},
	"extends": [
		"eslint:recommended",
		"prettier"
	],
	"plugins": [
		"prettier"
	],
	"rules": {
		"prettier/prettier": [
			"error",
			{
				"printWidth": 120,
				"useTabs": true,
				"singleQuote": true
			}
		]
	}
}
```

**ESLint Output:**

```plain
[Info  - 2:19:58 PM] ESLint server stopped.
[Info  - 2:19:58 PM] ESLint server running in node v12.4.0
[Info  - 2:19:58 PM] ESLint server is running.
```

**About VS Code:**

```plain
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:32:17.711Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.88-1-MANJARO
```

**Comment by dbaeumer** [comment]
@p3k can you provide me with a GitHub repository I can clone that demos this. Usually this depends on many things like folder layout, versions, ... and it is hard to find out whats wrong without that information.

**Comment by awreese** [comment]
I too have seen this after the extension updated to version 2.x. It appears that perhaps the validating _is_ actually occurring, since I'm able to hover & fix, but the highlighting feature seems to have disappeared. Reverting back to v1.9.1 restores the code highlighting in the editor.

**Comment by dbaeumer** [comment]
@awreese could you provide me with a GitHub repository I can clone that demos this or with steps on how to reproduce?

@p3k from your log the eslint library is not loaded. How does the output look like when using 1.9.x?

**Comment by awreese** [comment]
@dbaeumer Thanks for the response. You mentioning to @p3k that the eslint library wasn't loaded forced me to check that mine was running and sure enough it was not (for reasons unknown), but running `npm install -g eslint` rectified that and brought back the linting highlighting after updating to latest v2.0.11. Now I have the highlighting back but auto-fix on save doesn't seem to be working correctly now. I see the fix applied but then immediately get undone. I'll look for solutions on that.

Thanks.

**Comment by dbaeumer** [comment]
It is correct that you should either use formatOnSave or codeActionsOnSave but not both together. I will clarify this in the docs.
