### ISSUE TITLE
Extension should not report errors in the .eslintrc file while I edit it

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-eslint#85]
- Have auto save `ON`
- Edit the `env` section of the `.eslintrc` file; try to add a new environment but stop entering its name in between.

The extension pops up an error message, before I'm done editing it:

![image](https://cloud.githubusercontent.com/assets/22350/15874840/7a33e55c-2d05-11e6-85ae-c27cb7ca9b83.png)

**Comment by joaomoreno** [comment]
I was coming here to report this issue again.

**Comment by egamma** [comment]
@dbaeumer in vscode-tslint I've added logic to not invoke lint on a document when the configuration file has errors. This seems to work fine.

**Comment by dbaeumer** [comment]
Was still on my list for August. Got addressed in the following way: I will lint the files but only report the errors once for a given broken config file. If the config file changes I will revalidate. The reason being is that eslint give a proper error message about what is not correct with a config file.
