### ISSUE TITLE
Eslint not working when open above level directory

### ISSUE THREAD

**Issue by Jer-X** [microsoft/vscode-eslint#854]
When i upgrade to 2.0.6. It doesn't work when i open above directory. like this photo
![pic](https://user-images.githubusercontent.com/19970845/71225572-ffbabb80-2313-11ea-94f9-135aafcdb27f.png)
Q1: I must to add "eslint.workingDirectories" into setting.json to make It work in version 2.x.x?
Q2: But it must not to be added into setting.json that plugin can working in version 1.9.1? Can the version 2.x.x work same as the version 1.9.1

**Comment by phaibin** [comment]
Some issue, please  help!

**Comment by dbaeumer** [comment]
Published 2.0.11

**Comment by Jer-X** [comment]
@dbaeumer thanks!
