### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by olaluwe** [microsoft/vscode-eslint#858]
- Issue Type: `Bug`
- Extension Name: `vscode-eslint`
- Extension Version: `2.0.11`
- OS Version: `Linux x64 4.19.0-6-amd64`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by dbaeumer** [comment]
@olaluwe without the information provided in the clipboard hard to action on. When you see this again can you please attach the required information.
