### ISSUE TITLE
Does not read .eslintrc file when project folder is located on a network drive

### ISSUE THREAD

**Issue by behnoodk** [Microsoft/vscode-eslint#86]
I am using VS Code on Win10. My project folder is located on a Unix system shared on the network. The extension does not read my `.eslintrc` when I open my project. However if I copy the project folder on my local drive and open the project all the rules are applied.
I was able to get around this by copying all my `.eslintrc` config into `"eslint.options"` key in `.vscode/settings.json` file.

**Comment by dbaeumer** [comment]
@behnoodk this sounds very strange since we don't have any special code here. It is actually the eslint library itself that looks for the .eslintrc file. The extension doesn't do anything special. Does everything work for you if you run eslint from a terminal.

**Comment by n0v1** [comment]
Maybe this has something to do with file/folder watcher having to use polling to detect changes on network drives. See paulmillr/chokidar#242

**Comment by dbaeumer** [comment]
@behnoodk closing since I haven't received any answer. Please ping if the problem still exists for you.
