### ISSUE TITLE
Incorrect "'title' is declared but its value is never read"

### ISSUE THREAD

**Issue by Fi1osof** [microsoft/vscode-eslint#860]
Code:
```
if (field_as_pagetitle) {

  const {

    // Here error 'title' is declared but its value is never read.ts(6133
    // And it's grey
    [field_as_pagetitle]: title,
  } = object || {};

  meta = {
    ...meta,
    title,
  };

}
```

But code correct and works fine. And F12 move cursor into [field_as_pagetitle]: title

![Screenshot from 2019-12-24 08-05-11](https://user-images.githubusercontent.com/2550668/71394793-2898c480-2624-11ea-8a20-f01ebb48bca6.png)

But if i change var name, i got correct error/
![Screenshot from 2019-12-24 08-06-14](https://user-images.githubusercontent.com/2550668/71394818-45cd9300-2624-11ea-9f78-6fcc2dc8e633.png)

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-24-generic

Name: ESLint
Id: dbaeumer.vscode-eslint
Description: Integrates ESLint JavaScript into VS Code.
Version: 2.0.11
Publisher: Dirk Baeumer
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by dbaeumer** [comment]
@Fi1osof does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Fi1osof** [comment]
Sorry, maybe it's my local case and this hard to reproduce.
I close this issue. 
@dbaeumer excuse me for troubling.
