### ISSUE TITLE
ESLint running but not linting

### ISSUE THREAD

**Issue by cprasad111** [microsoft/vscode-eslint#862]
Issue Type: <b>Bug</b>

ESLint running. Status is also showing as running but not linting the code

Extension version: 2.0.11
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@cprasad111 can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
