### ISSUE TITLE
Can't lint .ts files when use vue-eslint-parser

### ISSUE THREAD

**Issue by odanado** [microsoft/vscode-eslint#864]
`eslint-plugin-vue` uses `vue-eslint-parser` as a parser.
https://github.com/vuejs/eslint-plugin-vue/blob/e8f130c20c0ba6213009e1230a294b0f091e57bb/lib/configs/base.js#L7

I need configure `@typescript-eslint/parser` in `parserOptions.parser` so as to lint `.ts` files.
https://eslint.vuejs.org/user-guide/#usage

`.ts` files aren't linted, because `@typescript-eslint/parser` isn't configured in `parser` options.
<img width="167" alt=" 2019-12-25 22 51 20" src="https://user-images.githubusercontent.com/6040962/71446654-1ffdd680-2769-11ea-87a8-9c85c48dfd0a.png">
reproduction repository: https://github.com/odan-sandbox/vscode-eslint-vue-typescript-reproduction

I suggest that  include `"typescript"` in `eslint.validate` by checking `@ typescript-eslint` in `plugins` or `parserOptions.parser`.

**Comment by dbaeumer** [comment]
@odanado this is what is happening now since version 2.x. 

I cloned your project but it is unclear to me what you think is not working correctly. Can you please provide steps to reproduce the problem.

**Comment by odanado** [comment]
## reproduction steps
- Run `git clone https://github.com/odan-sandbox/vscode-eslint-vue-typescript-reproduction`
- Run `cd vscode-eslint-vue-typescript-reproduction`
- Run `yarn install`
- Run `code .`
- Open `code/code.js`, `code/code.ts` and `code/code.vue` in VSCode

## captures
`code/code.js` and `code/code.vue` have a warning (`Replace `=` with `·=·`eslint(prettier/prettier)`). But, `code/code.ts` doesn't have a warning.

### code/code.js
<img width="1136" alt=" 2020-01-07 8 52 32" src="https://user-images.githubusercontent.com/6040962/71857483-155d1d00-312b-11ea-8219-1943d15adf63.png">


### code/code.vue
<img width="1136" alt=" 2020-01-07 8 52 39" src="https://user-images.githubusercontent.com/6040962/71857489-19893a80-312b-11ea-9af1-cb85d3194c5f.png">



### code/code.ts
<img width="1136" alt=" 2020-01-07 8 50 13" src="https://user-images.githubusercontent.com/6040962/71857516-2d34a100-312b-11ea-9a50-c790a02ad190.png">

**Comment by dbaeumer** [comment]
The reason for this is that although the `.eslintrc.js` tells to use the `@typescript-eslint/parser` the eslint npm module tells me that it uses the `vue-eslint-parser`. Need to understand why this is the case.

![capture](https://user-images.githubusercontent.com/1931590/71883405-adaccf00-3136-11ea-8f4f-bc2c2d318216.png)

**Comment by dbaeumer** [comment]
The problem is that the `parser` property is outside the `parserOptions`. So a correct parser configuration looks like this:

```
  parser: "@typescript-eslint/parser",
  parserOptions: {
  }
```

However that doesn't help since vue configuration require the `vue-eslint-parser`.

**Comment by dbaeumer** [comment]
Actually in your setup parser seems to be a valid option for the `vue-eslint-parser`.

**Comment by dbaeumer** [comment]
See https://github.com/mysticatea/vue-eslint-parser

**Comment by ozum** [comment]
@dbaeumer, I have same problem with same configuration as @odanado.

VS did not show and/or fix eslint problems for .ts files in Vue project. However 

`$ node_modules/.bin/eslint src/some.ts`

lists errors as expected:

![image](https://user-images.githubusercontent.com/1497060/71893188-f165ff80-315b-11ea-9a39-c52fc61e3539.png)

**Comment by dbaeumer** [comment]
Fixed for 2.0.12

**Comment by ozum** [comment]
Until 2.0.12 is published as a vs code extension, I would like to share my workaround.

I usually put .ts files in a directory in vue projects. I added a separate `.eslintrc.js` config file into that directory which is specific to .ts files. It works as expected with vscode-eslint 2.0.11. Hope helps.

**Comment by odanado** [comment]
I also would like to share my workaround.

Add `eslint.validate` option in `.vscode/settings.json`

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "eslint.validate": [
    "typescript"
  ]
}
```
