### ISSUE TITLE
vscode does not use rules in  .eslintrc.js

### ISSUE THREAD

**Issue by ahuigo** [microsoft/vscode-eslint#866]
# I have set .eslintrc.js  to  ignore some rules.
```
module.exports = {
    rules: {
        '@typescript-eslint/no-unused-vars': 'off',
   }
};
```
# eslint command works well
```
$ npx eslint --ext .js,.jsx,.ts,.tsx  "test.tsx"
```

# But vs code  ignore these rules.

![image](https://user-images.githubusercontent.com/1781999/71737054-94352a00-2e8d-11ea-9980-2f1c695a9b38.png)

# Here is my repo example
https://github.com/ahuigo/vscode-eslint-react-ts

**Comment by dbaeumer** [comment]
@ahuigo can you please add your ESLint version and plugins to the `package.json` of the provided test project. Otherwise it is very hard for me to reproduce the problem since it depends on some global configuration you are using.

**Comment by ahuigo** [comment]
Here is my full test project with eslint version:

https://github.com/ahuigo/vscode-eslint-react-ts/tree/88a1538d3ea40d0918c5974639a6d61e92ec6290

```
git clone https://github.com/ahuigo/vscode-eslint-react-ts
cd vscode-eslint-react-ts && yarn
npx eslint --ext .js,.jsx,.ts,.tsx  src/test.tsx
```

**Comment by dbaeumer** [comment]
@ahuigo actually the errors you are seeting are from the TypeScript extension not from ESLint. The code is `ts(6133)`. All ESLint error codes start with `eslint`
