### ISSUE TITLE
no validation of .vue files (2.0.12)

### ISSUE THREAD

**Issue by ozum** [microsoft/vscode-eslint#870]
Hi,

After updating to 2.0.12, I removed deprecated configuration `"eslint.validate"`. No validation occurs for .vue files.

```
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  },
```

When I add `"eslint.validate": ["vue"]`, it works again. Is it supposed to be added?

Thanks,

**Comment by thebspin** [comment]
Thanks for the quick fix, `"eslint.validate": ["vue"]` helps me out for now but it it is weird it happens all of the sudden.

**Comment by ozum** [comment]
Awesome, thanks for quick response. 2.0.13 is working as expected.
