### ISSUE TITLE
eslint doesn't work in vscode

### ISSUE THREAD

**Issue by only4s44u** [microsoft/vscode-eslint#874]
there is an error in output
`(node:44839) UnhandledPromiseRejectionWarning: Error: Request workspace/configuration failed with message: Cannot create property 'source.fixAll.eslint' on boolean 'true'
    at /Users/jiali/.vscode/extensions/dbaeumer.vscode-eslint-2.0.14/server/out/eslintServer.js:1:8459
    at /Users/jiali/.vscode/extensions/dbaeumer.vscode-eslint-2.0.14/server/out/eslintServer.js:1:8753
    at Immediate.<anonymous> (/Users/jiali/.vscode/extensions/dbaeumer.vscode-eslint-2.0.14/server/out/eslintServer.js:1:9114)
    at processImmediate (internal/timers.js:439:21)`

**Comment by dbaeumer** [comment]
@only4s44u hmm, this is strange. Can you provide me with your settings file? I suspect a problem in there.

**Comment by only4s44u** [comment]
@dbaeumer 

```
{
  "files.associations": {
    "*.wxs": "javascript",
    "*.wxss": "css"
  },
  "eslint.alwaysShowStatus": true,
  "minapp-vscode.wxmlFormatter": "prettier",
  "minapp-vscode.prettier": {
    "parser": "html"
  },

  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,
  "stylelint.autoFixOnSave": true,
  "search.followSymlinks": false,
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  }
}
```

**Comment by dbaeumer** [comment]
Thanks.
