### ISSUE TITLE
Auto fix made double comma to fix trailing comma (Another issue)

### ISSUE THREAD

**Issue by charlie0228** [microsoft/vscode-eslint#875]
Dear @dbaeumer 
Thanks for helping resolve #871, but I found another similar issue.
(commented under origin issue: https://github.com/microsoft/vscode-eslint/issues/871#issuecomment-574229982)

My settings are the same as the previous comment.

When I try to fix empty function like below:
```
  methods: {
    test() {

    }
  },
``` 
It will turn:
```
  methods: {
    test() {},,
  },
```
![Jan-14-2020 23-27-46](https://user-images.githubusercontent.com/24387287/72357206-88ffbb00-3725-11ea-9df7-68d8f5089890.gif)

Here is the project https://github.com/charlie0228/vscode-eslint-issue
You can edit the file `src/pages/Example.vue`

**Comment by dbaeumer** [comment]
@charlie0228 thanks for the issue. Just to point out why this is happening: you basically have two rules (eslint and prettier) that deal with the comma (you even have two error messages) and I used a fast path for format where I reused the computed edits. I now run the formatter as a whole linting round.
