### ISSUE TITLE
Custom Tags

### ISSUE THREAD

**Issue by Betanu701** [microsoft/vscode-eslint#876]
Does ESLint has an option to include custom tags so they do not get marked as problems?

I have an extension for EJS, it embeds javascript into html much like the script tags are used for. However when placing the tags inside of script or style tags, the error console is not recognizing the tags for either javascript or css. 

Showing the issue:
![image](https://user-images.githubusercontent.com/5798012/72648720-ce9ccd80-3949-11ea-9d6c-fd06c49f41f4.png)

Problem console:
![image](https://user-images.githubusercontent.com/5798012/72648776-eaa06f00-3949-11ea-92b4-fe3878343b35.png)

I would love to be able to put some default configurations within the extension itself so that it automatically clears the problems.

**Comment by dbaeumer** [comment]
@Betanu701 does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
