### ISSUE TITLE
how to config the ignore file of project root

### ISSUE THREAD

**Issue by NewFuture** [microsoft/vscode-eslint#879]
I have a `.ignore` in the project root for sharing ignore config.
How to config it with vscode-eslint ? 

```json
{
  "eslint.options": { "ignorePath": ".ignore" }
}
```
it dosen't works,  it will found the .ignore for relative path.

**Comment by dbaeumer** [comment]
@NewFuture does the validation happen correctly when you use eslint in the terminal (e.g run eslint with --ignorePath). If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
Works for me

<img width="917" alt="capture" src="https://user-images.githubusercontent.com/1931590/72713753-e359ab00-3b6d-11ea-9d91-c01776cb1902.png">

Please note that since you named the ignore file `.ignore` (not the default .eslintignore) changing the file is not hot.

**Comment by NewFuture** [comment]
@dbaeumer thanks for your reply,

yes, it works in the root folder,
but it will fail in the subfolder, such as `src/test.js`.

**Comment by dbaeumer** [comment]
@NewFuture can you provide me with a GitHub repository I can clone that demos this?
