### ISSUE TITLE
Using arrow functions causes an error

### ISSUE THREAD

**Issue by rodweb** [Microsoft/vscode-eslint#88]
I have this piece of code that has arrow function in it:
```js
load(action, data)
  .then(onLoad)
  .then(loadingEnabled => isLoadingEnabled = loadingEnabled)
; 
```
It causes an `Error: Cannot read property 'length' of undefined` notification at the top of the editor:
<img src="http://storage1.static.itmages.com/i/16/0616/h_1466072866_6203464_a04e24998f.png">

Developer Tools show this error in `messageService.ts:119`:
<img src="http://storage4.static.itmages.com/i/16/0616/h_1466073030_5235516_1cfaf22bca.png">

It happens only when writing arrow functions without block definition:
```js
.then(loadingEnabled => isLoadingEnabled = loadingEnabled) // error
.then(loadingEnabled => { return isLoadingEnabled = loadingEnabled; }) // no error
```

If I disable the extension (`"eslint.enable": false` in settings.json), the issue disappears, so I suppose the problem lies in the extension itself.

**Comment by dbaeumer** [comment]
@rodweb which version of eslint are you using and could you provide the eslintrc file to have the same config. I was not able to reproduce this so far.

**Comment by rodweb** [comment]
I'm terribly sorry I haven't checked it right away :disappointed: 
I had stuck with `eslint@1.6.0` because of the wrong `npm` configuration, and it didn't update until I fixed my `.npmrc`. The problem is gone after installing fresh version of `eslint`.
Thanks!

**Comment by dbaeumer** [comment]
No problem
