### ISSUE TITLE
Only apply error fixes (not warnings)

### ISSUE THREAD

**Issue by arcanis** [microsoft/vscode-eslint#882]
Reviving #208 which got closed with the wrong solution. I'm looking for the following use case:

- Warnings and errors are both shown in the editor
- Pressing Ctrl-S autofixes errors, but warnings are left as-is
- I don't need to use specific ESLint plugins that implement rules without autofixes

The solution with `CLIEngine` would be to use`fix: lintResult => lintResult.severity === 2` in the options, but since the VSCode settings are JSON only it's not clear how to achieve the same effect. Any idea?

**Comment by dbaeumer** [comment]
One idea that got requested in a different context is to run the fix with a different `.eslintrc` config file. 

How would you do this when using eslint in the terminal ?

**Comment by arcanis** [comment]
> How would you do this when using eslint in the terminal ?

We use the equivalent of `--fix --quiet`, which autofixes errors but not warnings:

https://github.com/eslint/eslint/blob/master/lib/cli.js#L31-L40

**Comment by dbaeumer** [comment]
Actually quiet is supported. Setting is `eslint.quiet`. Have you give that a try?

**Comment by arcanis** [comment]
Yep but when I looked at the source and the PR is sounded like the intent was to hide warnings altogether. In my case it's more like I don't want them to be fixed, but I still want them to appear.

**Comment by dbaeumer** [comment]
Now I get it. I think the fix might be simple. If `eslint.quite` is set we could pass it to the engine when computing the fixes. https://github.com/microsoft/vscode-eslint/blob/d40b96d4a2f0d085770b2bdce87b985bdd198bec/server/src/eslintServer.ts#L1817

But may be we need another setting since users might be surprised if they don't get fixed anymore.

**Comment by barroudjo** [comment]
I completely and wholeheartedly agree with @arcanis proposal !

**Comment by dbaeumer** [comment]
In 2.2.0 you can control which rules will be considered during auto fix on save and format. Setting is `eslint.codeActionOnSave.rules`
