### ISSUE TITLE
eslint.run "onTypeOrSave"?

### ISSUE THREAD

**Issue by michaelfig** [microsoft/vscode-eslint#885]
This is a feature request.

Would it be possible to add an `"onTypeOrSave"` option to eslint.run?

My custom `.eslintrc.js` scans the sources on disk to determine which overrides should be enabled (i.e. when a `'use awesome-syntax';` token appears at the start of the file).

Currently, `"onSave"` doesn't happen frequently enough for my normal linting workflow, and `"onType"` doesn't trigger after the file is saved.

If there is a better way to solve this problem, I'd be open to it.  Thanks!

**Comment by dbaeumer** [comment]
In VS Code hitting `Ctrl+S` even if the file is saved will trigger a re-validate of the file. I am not a fan of mixing `onType` and `onSave`.

in your custom `.eslintrc.js` are you doing the scanning without waiting it?

**Comment by michaelfig** [comment]
@dbaeumer Thanks for your comments.  I am hitting `Ctrl+S` but the `.eslintrc.js` is not being reevaluated (like it is for `onType`).  Maybe that's a different kind of problem.

How can I "wait for" the right time to scan?

**Comment by dbaeumer** [comment]
>  I am hitting Ctrl+S but the .eslintrc.js is not being reevaluated (like it is for onType). Maybe that's a different kind of problem.

Both run through the same code path in the eslint extension and it is the ESLint npm module that reads in the `.eslintrc.js` file.

How to you ensure that this is working when executing eslint in the terminal?
