### ISSUE TITLE
Require initial value for .reduce()

### ISSUE THREAD

**Issue by fkereki** [microsoft/vscode-eslint#888]
I'm reposting this from a proposal I found at the TSLINT project, at https://github.com/palantir/tslint/issues/4173, from where I quote:

**Rule Suggestion**
When using `Array.prototype.reduce()` the `initialValue` parameter is optional. As per MDN docs: "If the array is empty and no `initialValue` is provided, TypeError will be thrown." Therefore the suggestion is to provide a rule where the initialValue is required to be specified to avoid TypeErrors being raised.

**Is your rule for a general problem or is it specific to your development style?**
It is a general problem that is likely to occur as the code grows.

**What does your suggested rule do?**
Requires `initialValue` to be specified when calling `Array.prototype.reduce()`

**List several examples where your rule could be used**
As per MDN docs:
"It is usually safer to provide an initial value because there are three possible outputs without initialValue, as shown in the following example."

```
var maxCallback = ( acc, cur ) => Math.max( acc.x, cur.x );
var maxCallback2 = ( max, cur ) => Math.max( max, cur );

// reduce() without initialValue
[ { x: 22 }, { x: 42 } ].reduce( maxCallback ); // 42
[ { x: 22 }            ].reduce( maxCallback ); // { x: 22 }
[                      ].reduce( maxCallback ); // TypeError

// map/reduce; better solution, also works for empty or larger arrays
[ { x: 22 }, { x: 42 } ].map( el => el.x )
                        .reduce( maxCallback2, -Infinity );
```
Another example: when reduce is being called on an array passed in as a parameter, or injected (e.g., using Redux), providing the `initialValue` parameter to reduce avoids having to check if the array is empty, however, that is easy to forget while coding.

```
function sumArray(values: number[]) {
    return values.reduce((a, b) => a + b);
}

sumArray([1,2]); // 3
sumArray([]); // TypeError

function sumArrayWithInitial(values: number[]) {
    return values.reduce((a, b) => a + b, 0);
}

sumArrayWithInitial([]); // 0
```

**Comment by fkereki** [comment]
Personally, I found errors in an existing code base, that would have been caught by this rule, so I second it.

**Comment by dbaeumer** [comment]
@fkereki please propose the rule to the ESLint npm module managed [here](https://github.com/eslint/eslint). The VS Code extension is based on the general ESLint rule engine.
