### ISSUE TITLE
No `Disable ESLint for this Workspace` command in Command palette

### ISSUE THREAD

**Issue by daytonlowell** [microsoft/vscode-eslint#889]
I have a workspace open, so I'm not sure what I need to do to make the command show up.

![Screen Shot 2020-02-03 at 10 56 51 AM](https://user-images.githubusercontent.com/305993/73673225-ea0b1680-4673-11ea-9d92-150ce5407300.png)

**Comment by dbaeumer** [comment]
The `Disable ESLint` will disable it for the workspace folder not globally. OK to close.
