### ISSUE TITLE
Object rest/spread causes an error in VSCode despite not causing an error from command line

### ISSUE THREAD

**Issue by vulpino** [Microsoft/vscode-eslint#89]
The following code:

```javascript
function example ({ first, second, ...rest }) {
  return rest
}

console.log(example({ first: 1, second: 2, third: 3 }))
```

Results in a clean bill of health from eslint on the command line, and runs correctly under `babel-node`:

![Screenshot](https://i.imgur.com/S0UYt2J.png)

However, a number of errors are shown inside of VSCode:

![Screenshot](https://i.imgur.com/MeJYMiJ.png)

I can't fathom why this would happen. My `.eslintrc` is as such:

```
{
    "extends": ["standard", "standard-jsx"],
    "parser": "babel-eslint"
}
```

`.babelrc`:

```
{
  "presets": ["es2015", "stage-2", "react"]
}
```

My ESLint version is v2.10.2.

**Comment by eldarshamukhamedov** [comment]
I ran into the same issue, but it is not related to the ESLint plugin. Unfortunately, [VSCode does not support object prop spread](https://code.visualstudio.com/Docs/languages/javascript#_disable-syntax-validation-when-using-non-es6-constructs). You can disable JS validation and rely on the ESLint plugin instead. More on the topic: https://github.com/Microsoft/vscode/issues/3804

**Comment by vulpino** [comment]
Ah, if the issue is with vscode instead of the eslint plugin I'll close this issue. Thanks for the pointer.

**Comment by egamma** [comment]
This is now also documented in the [Code docs](https://code.visualstudio.com/docs/languages/javascript#_disable-syntax-validation-when-using-non-es6-constructs)
