### ISSUE TITLE
ESLint with TypeScript not picking up tsconfig's compilerOptions.target under specific circumstance

### ISSUE THREAD

**Issue by LuminescentMoon** [microsoft/vscode-eslint#891]
Note: ESLint behaves as expected when run from the command line so this is not due to ESLint itself or any project dependencies. TypeScript behaves as expected from the command line as well.

TS configured with child tsconfig does not use any `compilerOptions.target` for particular files when base tsconfig does not contain those particular files via `include`.

Minimal reproduction: https://github.com/LuminescentMoon/vscode-eslint-bug-repro

When `.eslintrc` rules only have `semi` enabled, `.eslintrc` is setup for linting TypeScript projects, `.eslintrc`'s `parserOptions.project` contains `./tsconfig.eslint.json`, `tsconfig.json` targets ESNext, only `tsconfig.eslint.json` includes `tests/**/*.*`, and `tests/index.test.ts` contains `let x = 0n;`

#### Expected behavior

Problems list only contains eslint(semi).

#### Actual behavior

Problems list contains eslint(semi) and ts(2737) - "BigInt literals are not available when targeting lower than ESNext".

#### Behavior of running `eslint tests/index.test.ts`

Problems list only contains eslint(semi).

#### Behavior of running `tsc --project tsconfig.eslint.json`

Compiles without errors.

#### Behavior after adding `compilerOptions.target = ESNext` to `tsconfig.eslint.json`

Problems list contains eslint(semi) and ts(2737) - "BigInt literals are not available when targeting lower than ESNext".

#### Behavior after adding `tests/**/*.*` to includes of `tsconfig.json`

Problems list only contains eslint(semi).

**Comment by dbaeumer** [comment]
@LuminescentMoon if I read your description correctly then your issue is the error produced by the TypeScript compiler which shows up even if ESLint is disabled.  Since this error is produced by VS Code itself (e.g. the TypeScript extension shipping in VS Code) please file the issue against the VS Code repository.
