### ISSUE TITLE
Eslint does not check for errors when the file is closed

### ISSUE THREAD

**Issue by wuming123** [microsoft/vscode-eslint#894]
Issue Type: <b>Feature Request</b>

Eslint does not check for errors when the file is closed

Why is that? I've added the project to the workspace

Extension version: 2.0.15
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by dbaeumer** [comment]
Support is there using a task in VS Code. See the settings `eslint.lintTask.*`. Triggering it needs an additional user action since it is an expensive operation.
