### ISSUE TITLE
Eslint.lintask is enable, but it doesn't work

### ISSUE THREAD

**Issue by wuming123** [microsoft/vscode-eslint#896]
Eslint does not check workspace files when they are closed.

**Comment by wuming123** [comment]
Eslint works when the file is in the editor

**Comment by hugofabricio** [comment]
I have the same error

**Comment by arvigeus** [comment]
Noticed this as well

**Comment by dbaeumer** [comment]
You have to trigger the task using the run task command. The task is not run automatically since validating all files is quite expensive since ESLint has no incremental update strategy.

**Comment by arvigeus** [comment]
This makes the whole idea of errors/warnings statusbar item kinda pointless since it is not going to show correct number. TypeScript is the same in that regard.

**Comment by dbaeumer** [comment]
Usually people combine the reconciling of the open files with the tasks. As said constantly running ESLint over the whole project is not feasible unless they add incremental support.

Regarding Typescript: it does support watch and incremental support and VS Code has support for this via task which always give you the errors for the whole project.
