### ISSUE TITLE
timeout 

### ISSUE THREAD

**Issue by congtrieu112** [microsoft/vscode-eslint#899]
Issue Type: <b>Bug</b>

timout check tyescirpt in visualCode

Extension version: 2.0.15
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|12.00GB (0.06GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@congtrieu112 can you please provide a description of what exactly your issue is with detailed steps on how to reproduce this.
