### ISSUE TITLE
Feature request: option to disable certain rules

### ISSUE THREAD

**Issue by zypA13510** [microsoft/vscode-eslint#902]
Dup of #755, but I can't reopen or comment on that thus the new issue.

How is this different from #267:
- In #267, the list of rules to disable is determined by this plugin alone. While sometimes it's not only this plugin that can auto-fix on save, others like editorconfig also fix things like indent, EOL, and sometimes we can have scripts to fix things too. A manually configured list is probably more appropriate in this case.
- Also in #267, you have to enable auto-fix on save to ignore the rules, why do I have to do that? I don't trust the machine, I don't want auto-fix. I just want to ignore certain rules.

And it's probably easier than #267 to implement, I guess.

**Comment by dbaeumer** [comment]
Actually I din't want to build a mechanism on top of `.eslintrc` config files to enable / disable rules. IMO if you want to have two set of rules you typically validate then when running in the terminal you typically have two distinct `eslintrc` files. Pointing the extension to a different config file is supported. 

Have you tried this?

**Comment by zypA13510** [comment]
Well, sure that'll work for a folder. But what about global config? For example, if I work on Windows, I rely on editorconfig to convert CRLF to LF for me, which will only happen on save. So now I need to include `"linebreak-style": "off"` in my special config for vscode, or else eslint warns me for every new file I create. But which base config to extend? Each project may have its own config. Basically, I need to do this special configuration for every project once. If this feature is built into the extension, however. I only need to configure once, in the global config, and then every project automatically ignores `linebreak-style`.

**Comment by dbaeumer** [comment]
I will keep it open then but as said I am not a fan of adding another config UI on top of the already very sophisticated eslint configuration.

How do you deal with this in the terminal then ?

**Comment by zypA13510** [comment]
> How do you deal with this in the terminal then?

These errors will be fixed on save (just not by vscode-eslint), so by the time a terminal is involved, the error is corrected already - usually you'd save your code before doing something in the terminal, no?

**Comment by SiarheiKuchukBelitsoft** [comment]
Hi
I've implemented saving with execution of fixing eslint through node with different config via plugin Run on Save. But on my development machine it takes 3 seconds (!!!!) to wait till file is updated.

And moreover if i continue edit, VS Code detects that file was changed and asks me to merge them both.

It is really needed to have that in Ms Eslint plugin

**Comment by dbaeumer** [comment]
There are two new ways to customize this: `eslint.customization.rules` for the general rules and `eslint.codeActionOnSave.rules` for the rules to be honored during save and format.

**Comment by amunrarara** [comment]
@dbaeumer Is there documentation available for this feature? I cannot find it.

**Comment by amunrarara** [comment]
This is probably better for a discussion thread, but if it isn't a pain I'll ask here. Particularly, I simply want to omit a single rule. What's the best way to achieve that?

**Comment by dbaeumer** [comment]
The doc is here: https://github.com/microsoft/vscode-eslint/blob/main/README.md#settings-options

**Comment by amunrarara** [comment]
Thank you @dbaeumer , it is unclear how I can omit only a single rule however. Do I need to specifically include every single rule, except for the omitted rule, in the `eslint.codeActionsOnSave.rules` array? That would mean I'd have to update both my eslintrc.js and my settings file places anytime I'd make a change to my rules.

**Comment by dbaeumer** [comment]
`!` is your friend :-). Look at the examples in the doc. There are some that disable rules with the `!` operator.

**Comment by amunrarara** [comment]
> `!` is your friend :-). Look at the examples in the doc. There are some that disable rules with the `!` operator.

Awesome. I hope this is my last question on the subject; if I use an empty array for codeActionsOnSave.rules, it will consider all my ESLint rules. If I include a single member inside that array, it will ignore all rules except that single member. Now, if I include only a single member, prefixed with !, will that still consider all my other rules?

**Comment by dbaeumer** [comment]
Here is an example from the doc

This example removes all TypeScript ESLint specific rules from the code action on save pass but keeps all other rules:
```
"eslint.codeActionsOnSave.rules": [
  "!@typescript-eslint/*",
  "*"
]
```
