### ISSUE TITLE
ES Lint not working in Dev Container

### ISSUE THREAD

**Issue by ijeriomit** [microsoft/vscode-eslint#903]
I am using VS code's docker extension to create a Vue project in a container. For some odd reason my linter doesn't show errors or warnings in my editor. Formatting works just fine. However, **Linting** ( the red or yellow squiggly underlines) does not work. **P.S. The extension works just fine locally with the exact same settings.json!**
I followed the official vue setup from VScode [https://code.visualstudio.com/docs/nodejs/vuejs-tutorial](url)
Note. I have Vetur and ESlint installed in my container. In my node_modules: eslint, eslint-loader, eslint-config-prettier, eslint-plugin-prettier, eslint-plugin-vue, eslint-utils and eslint-visitor-keys are installed 

 Here is my settings.json for VSCode: `{
  "javascript.validate.enable": false,
  "vetur.format.defaultFormatterOptions": {
    "prettier": {
      "printWidth": 200
    }
  },
  "window.zoomLevel": 0,
  "diffEditor.ignoreTrimWhitespace": false,
  "vetur.format.defaultFormatter.html": "prettier",
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "eslint.format.enable": true,
  "editor.formatOnSave": true,
  "eslint.alwaysShowStatus": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "vue",
      "autoFix": true
    },
  ],
  "vetur.validation.template": false,
  "eslint.run": "onType",
  "vetur.format.defaultFormatter.js": "prettier-eslint"
}`

Not quite sure how fix this issue. Please help and thank you in advance.

**Comment by dbaeumer** [comment]
I tested it and ESLint works for me in a dev container and WSL setup.

Is there anything in the ESLint output channel. Does eslint work in the terminal when executed in the dev container ?

**Comment by ijeriomit** [comment]
For example this is what happens with the ESLint + standard config.
No error in my editor
![image](https://user-images.githubusercontent.com/32554410/75051590-c75e6780-5493-11ea-8e8b-9b4acd73cb00.png)
Here are the errors when I run eslint manually in the terminal
![image](https://user-images.githubusercontent.com/32554410/75051669-eceb7100-5493-11ea-9564-33b9c532d086.png)

**Comment by ijeriomit** [comment]
> I tested it and ESLint works for me in a dev container and WSL setup.
> 
> Is there anything in the ESLint output channel. Does eslint work in the terminal when executed in the dev container ?

My Eslint output is empty

**Comment by dbaeumer** [comment]
Can you share your container. Best would be to have access to the image.

**Comment by dbaeumer** [comment]
Are you running eslint from the same directory as the folder you have open in VS Code ?
