### ISSUE TITLE
failed to tokenize...expected attribute, ">" or "/>".

### ISSUE THREAD

**Issue by SeanSobey** [microsoft/vscode-eslint#906]
Hi

I am seeing this issue using this extension:
![image](https://user-images.githubusercontent.com/6775902/75857659-3a0a0400-5dff-11ea-96ad-5faea5ce97a9.png)

See the source in [this repo](https://github.com/SeanSobey/ts-std-lib/blob/master/src/Optional.ts#L29).

**Comment by dbaeumer** [comment]
@SeanSobey what happens if you validate the file using ESLint in the terminal. If you see the same error (which I think will very likely be the case) please report the issue to the ESLint repository.

**Comment by SeanSobey** [comment]
Hi, thanks for the quick reply!

I did check that, and the console command runs fine. It does, however, appear that it may possibly be another extension causing this issue. I will disable and re-enable what I have one-by-one until I can confirm it is coming from here.

I didn't consider it might be another extension, sorry for the rash posting of the issue, I will reopen if/when it is definitely this one!
