### ISSUE TITLE
How disable line within documentation comments

### ISSUE THREAD

**Issue by iniatse** [microsoft/vscode-eslint#907]
```
/**
* @param {string} firstName // eslint-disable-line
*/
```

That does not work. I'm using `eslint-plugin-jsdoc` and I activated `"jsdoc/check-param-names": 1` which now throws a warning and I want to disable that warning only for that line.

Pls help

**Comment by dbaeumer** [comment]
@iniatse does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
