### ISSUE TITLE
Parsing error: Unexpected token import

### ISSUE THREAD

**Issue by Fi1osof** [microsoft/vscode-eslint#908]
```
const moduleURL = new URL(import.meta.url);
```
This is valid code for .mjs https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/import.meta
But i got eslint error and can not disable this.

**Comment by dbaeumer** [comment]
@Fi1osof  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Fi1osof** [comment]
> @Fi1osof does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

Yes, i do.
```
$ yarn eslint src/modules/index.mjs 
yarn run v1.19.2
$ @prisma-cms/module-boilerplate/node_modules/.bin/eslint src/modules/index.mjs

@prisma-cms/module-boilerplate/src/modules/index.mjs
  12:27  error  Parsing error: Unexpected token import

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
```

Code source: https://github.com/prisma-cms/module-boilerplate/blob/9ce05031e7a84bc06f2e62a6efdeb3d0e9cb011a/src/modules/index.mjs#L12

eslint@6.8.0

**Comment by dbaeumer** [comment]
@Fi1osof the error also exist when running ESLint from the terminal hence VS Code reports it as well. I am not sure what exactly you are asking for.

**Comment by Fi1osof** [comment]
@dbaeumer so is this bug in https://github.com/eslint/eslint ?
Am I wrong with the source?

**Comment by dbaeumer** [comment]
Yes, since the bug happens on the terminal this is an issue with https://github.com/eslint/eslint

**Comment by Fi1osof** [comment]
@dbaeumer thanks!
