### ISSUE TITLE
Does it makes sense to support workspaceFolders capability?

### ISSUE THREAD

**Issue by rchl** [microsoft/vscode-eslint#909]
Eslint language server doesn't support [workspaceFolders capability](https://microsoft.github.io/language-server-protocol/specification#workspace_workspaceFolders) and instead implements something similar by expecting `workspaceFolder` property on configuration passed from `workspace/configuration`.

Is there a specific reason why it's implemented that way? Would `workspaceFolders` provide comparable functionality or it's not suitable?

**Comment by dbaeumer** [comment]
The ESLint plugin has full support for workspace folders. They are resolved in the getConfiguration request sent from the server to the client. See  https://github.com/Microsoft/vscode-eslint/blob/master/client/src/extension.ts#L1055

**Comment by rchl** [comment]
I know about that functionality but that's not what LSP specification describes.

The eslint server doesn't announce `workspace.workspaceFolders` capability and doesn't send the `workspace/workspaceFolders` request but instead does it in a seemingly server-specific and custom way.

Instead, it expects to receive `workspaceFolder` (no `s` at the end) from the `workspace/configuration` response which looks to me like just a custom way of handling workspace folders.

My question is whether there is a specific reason for doing it that way?

**Comment by dbaeumer** [comment]
The reason is that for ESLint itself workspace folders don't add a scoping capability and hence separating it from the configuration call will simply complicate the code. I have no problem adding the server capability. Why do you think that is important ?

**Comment by rchl** [comment]
To be clear, I'm not saying the server capability should be added unless the relevant implementation is added also. I think it would be wrong to announce the capability while not supporting actual functionality from the spec.

**Comment by rchl** [comment]
I'm asking this question because I'm coming from the Sublime Text camp and the LSP implementation used there supports `workspace.workspaceFolders` capability but that doesn't help with this server as it supports it in a custom way.

To support this server's implementation in Sublime's equivalent of this client, it requires implementing server-specific handler code there.

So I'm trying to figure out whether Sublime's equivalent of this client needs to add custom support for this server or there is a possibility for this server to switch to spec-compatible implementation.

**Comment by rchl** [comment]
@dbaeumer any further thoughts after my clarifications?

Again, I'm asking whether it's feasible to switch to spec-compliant implementation?
That would entail passing all workspace folders to the server with `InitializeParams` and then report changes through `DidChangeWorkspaceFoldersParams`.
The server would have to figure out on its own if a given file belongs to one of those folders.

Is that something you see being done (either by you or through contribution)?

**Comment by dbaeumer** [comment]
In terms of fetching this information from the client the ESLint server is spec compatible since it uses the `workspace\configuration`  request (see https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration).

So even if I would recode the server a client would still need to implement that request and provide the correct settings which are necessary for the server to work.

I addition (for better UI integration) the server sends some custom messages.

In general I think a better approach would be to document this for the server so that clients can implement it accordingly.

**Comment by rchl** [comment]
> In terms of fetching this information from the client the ESLint server is spec compatible since it uses the `workspace\configuration` request

Sorry, but I would disagree that it's per spec. The `workspace/configuration` message is for getting any arbitrary workspace settings from the client. It's not specifically intended for sending the workspace folder for given file/uri. Sure, you can use it for that also, but since there is a specific API for notifying about workspace folders, the way you do it is custom and server-specific.

> So even if I would recode the server a client would still need to implement that request and provide the correct settings which are necessary for the server to work.

Yes, `workspace/configuration` would still be needed to report all eslint-specific settings (not including workspace folders though).

> I addition (for better UI integration) the server sends some custom messages.

I have no issue with eslint server supporting some custom messages (I guess you mean `eslint/*` messages). That's IMO not relevant to that issue.

> In general I think a better approach would be to document this for the server so that clients can implement it accordingly.

I'm still not convinced and don't understand why it would be better. The spec-compliant way seems like a better way overall as that would cause less friction for various clients to support it (some would support it out-of-the-box as they already support workspace folders API).

If your think that changing it would require extra work and wouldn't add any benefit to vscode extension itself then, sure, I can understand that. But I think you are not clear on your reasoning so that's why I'm not pushing this topic while trying to understand your reasoning.

**Comment by rchl** [comment]
Ping.

Also, I saw you've added fb8194ed0240aa7fef02921b1c4fc2a34bf99f38 but, as I've said before, I believe it's wrong to advertise that capability when not actually supporting connected functionality. That is, not supporting reading folders from `InitializeParams`. It can actually even break functionality in spec-compliant clients.

**Comment by dbaeumer** [comment]
The ESLint server is workspace folder agnostic and therefore as a side effect supports workspace folders. Structurally it doesn't care about workspace folders. It is working DIRECTORY sensitive and from that regard (to make this more obvious) the `workspaceFolder` property in the config should may be folded into a better structure with the working directory. 

I decided to set the boolean in the server capabilities since there might be clients out there that might disable working folders if a server doesn't signal support for it.

**Comment by dbaeumer** [comment]
The ESLint server even happily works on files outside of any workspace folder.
