### ISSUE TITLE
Not linting markdown files

### ISSUE THREAD

**Issue by arvigeus** [microsoft/vscode-eslint#912]
**vscode-eslint version**: 2.1.1
**eslint version**: 6.8.0
**vscode version**: 1.42.1

**settings:**
```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  },
  "javascript.validate.enable": false,
  "typescript.validate.enable": false,
  "eslint.lintTask.enable": true,
  "eslint.probe": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "html",
    "vue",
    "markdown",
    "md"
  ]
}
```
**file.md** (_note: there is a zero-width whitespace in this code sample to "escape" the backticks_)

```md
​```js
let x;
if ((x = 0)) { }
​```
```

Running eslint (with markdown plugin installed) correctly displays warnings, but editor shows nothing.

**Comment by dbaeumer** [comment]
@arvigeus can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by arvigeus** [comment]
https://github.com/arvigeus/eslint-markdown-issue

**Comment by dbaeumer** [comment]
Actually, probing for markdown is not working correctly right now. You can force markdown linting using

```
  "eslint.validate": [
    "markdown",
    "md"
  ]
```

**Comment by arvigeus** [comment]
You can deprecate `probe` in the future: https://github.com/eslint/eslint/issues/10828

**Comment by dbaeumer** [comment]
I don't think so. What I want to avoid is that I load eslint extension and server for files that can definitely not be linted by ESLint (for example java).
