### ISSUE TITLE
Eslint not working at 1.43

### ISSUE THREAD

**Issue by wonderlandpark** [microsoft/vscode-eslint#913]
It worked well at early version, but after I updated my VSC eslint does not show anything. I have checked eslint log, and this works at log, but error is not shown.

**Comment by dbaeumer** [comment]
It actually works for me. Does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by JohnPiepersSmits** [comment]
ESlint seems to ignore the rules section in its eslintrc.json file.
I have VSC 1.43

**Comment by dbaeumer** [comment]
@JohnPiepersSmits  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by JohnPiepersSmits** [comment]
Hi,
I noticed that I was missing eslint in my node_modules directory (don't ask me why that happened) and after reinstalling eslint globally it works perfectly!
Thanks for your time Dirk!

**Comment by rodrigomcoelho** [comment]
Hi @dbaeumer. That's my VSCode version.

`Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic snap`

The extensions I have been using:

`bierner.markdown-shiki
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
dracula-theme.theme-dracula
eamodio.gitlens
EditorConfig.EditorConfig
eseom.nunjucks-template
jpoissonnier.vscode-styled-components
luwenjiechn.nunjucks-vscode-snippets
mikestead.dotenv
ms-vsliveshare.vsliveshare
naumovs.color-highlight
PKief.material-icon-theme
ritwickdey.LiveServer
rocketseat.RocketseatReactJS
rocketseat.RocketseatReactNative
ronnidc.nunjucks
wix.vscode-import-cost
Zignd.html-css-class-completion`

Here is a project I have been working on [https://github.com/rodrigomcoelho/fastfeet-mobile](url) and ESLint suddenly stopped.  

Note: No matter whether I create a new project or open a existing one (one where ESlint was working before) it simply does not work.

**Comment by dbaeumer** [comment]
@rodrigomcoelho works for me without any problems:

![capture](https://user-images.githubusercontent.com/1931590/77891312-0e006800-7271-11ea-880d-88099c42d0a5.png)

Any additional information. Is there anything in the ESLint Output channel.

**Comment by rwam** [comment]
Maybe related, but ESLint stop working after upgrade my Mac OS to Catalina. Linting and automated fixing work on the terminal but neither highlighting nor fixing work in VSCode. I'm using **ESLint 2.1.2** on **VSCode 1.43.2**.

**Comment by rodrigomcoelho** [comment]
> @rodrigomcoelho works for me without any problems:
> 
> ![capture](https://user-images.githubusercontent.com/1931590/77891312-0e006800-7271-11ea-880d-88099c42d0a5.png)
> 
> Any additional information. Is there anything in the ESLint Output channel.

@dbaeumer shows no error in the Eslint Output channel.
![screenshot-eslint](https://user-images.githubusercontent.com/45849030/77965044-38244b00-72ae-11ea-888f-878d4e965904.png)

**Comment by rodrigomcoelho** [comment]
> > @rodrigomcoelho works for me without any problems:
> > ![capture](https://user-images.githubusercontent.com/1931590/77891312-0e006800-7271-11ea-880d-88099c42d0a5.png)
> > Any additional information. Is there anything in the ESLint Output channel.
> 
> @dbaeumer, yes there are erros on this.
> 
> `[Info - 5:59:20 PM] ESLint server stopped. [Info - 5:59:21 PM] ESLint server running in node v12.8.1 [Info - 5:59:21 PM] ESLint server is running. [Info - 5:59:24 PM] ESLint library loaded from: /home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/api.js (node:7553) UnhandledPromiseRejectionWarning: Error: Failed to load config "airbnb" to extend from. Referenced from: /home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/.eslintrc.js at configMissingError (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9) at ConfigArrayFactory._loadExtendedShareableConfig (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23) at ConfigArrayFactory._loadExtends (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25) at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25) at _normalizeObjectConfigDataBody.next (<anonymous>) at ConfigArrayFactory._normalizeObjectConfigData (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20) at _normalizeObjectConfigData.next (<anonymous>) at createConfigArray (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25) at ConfigArrayFactory.loadInDirectory (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16) at CascadingConfigArrayFactory._loadConfigInAncestors (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46) (node:7553) UnhandledPromiseRejectionWarning: Error: Failed to load config "airbnb" to extend from. Referenced from: /home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/.eslintrc.js at configMissingError (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9) at ConfigArrayFactory._loadExtendedShareableConfig (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23) at ConfigArrayFactory._loadExtends (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25) at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25) at _normalizeObjectConfigDataBody.next (<anonymous>) at ConfigArrayFactory._normalizeObjectConfigData (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20) at _normalizeObjectConfigData.next (<anonymous>) at createConfigArray (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25) at ConfigArrayFactory.loadInDirectory (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16) at CascadingConfigArrayFactory._loadConfigInAncestors (/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46) (node:7553) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:7553) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:7553) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. (node:7553) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. [Info - 5:59:26 PM] Failed to load config "airbnb" to extend from. Referenced from: /home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/.eslintrc.js `

It took me sometime to solve. 
I reached out to ESLint chat channel and they told me obvious. The ESlint output was saying that the file that was being considered was one in a previous folder. 

`/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/.eslintrc.js`  (backup ESLint field with my rules)

But my project and my eslint file
`/home/rcoelho/Documents/courses/rocketseat/gostack/desafios/fastfeet/fastfeetMobile/.eslintrc.js`

When I renamed the eslint file in the previous folder, closed and reopened the VSCode it's started taking into the account the correct one.

Thank you @dbaeumer for taking a look into that.

**Comment by rwam** [comment]
Hm, the output channel shows:
```
…
(node:19755) UnhandledPromiseRejectionWarning: Error: Failed to load plugin 'import' declared in 'frontend/.eslintrc.js » @nuxtjs/eslint-config': Cannot find module 'eslint-plugin-import'
Require stack:
- /…/static-site-generators/strapi-nuxt/__placeholder__.js
Referenced from: /…/static-site-generators/strapi-nuxt/frontend/node_modules/@nuxtjs/eslint-config/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function.resolve (internal/modules/cjs/helpers.js:74:19)
…
```
I've tried the following without luck:

- installing **eslint-plugin-import**
- reinstalling **@nuxtjs/eslint-config**
- manual creation of file **__placeholder__.js**

The following error is always existent: `Cannot find module 'eslint-plugin-import'`

**Comment by dbaeumer** [comment]
@rodrigomcoelho these are errors from ESLint itself and not the extension. What happens when you try to validate the file using ESLint in the terminal?

@rwam same here.  Does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by rwam** [comment]
Hi @dbaeumer, validation and fixing work in the terminal. As an example you can use <https://strapi.io/blog/build-a-blog-using-nuxt-strapi-and-apollo> I've created nuxt with ESLint support and linting in VSCode don't work.

**Comment by dbaeumer** [comment]
@rwam I cloned https://github.com/strapi/strapi-starter-nuxt-blog.git but that doesn't have any ESLint installed into it. Can you provide me with a repository that is self contained in terms of the ESLint setup and the VS Code settings. Thanks.

**Comment by rwam** [comment]
Hm strange. I've created an example repository for you: https://github.com/rwam/eslint-example It's the frontend part of the strapi tutorial. I've added and configured eslint manually. And the result is: no linting in VSCode but on the shell only.

But here comes the weird part I don't understand: you can find another branch https://github.com/rwam/eslint-example/tree/using-eslint-init where I set up eslint using `eslint --init` and this setting works either on terminal and in VSCode. Any help appreciated.

**Comment by dbaeumer** [comment]
@rwam: which file do you expect to be linted and how do you lint on the terminal?

**Comment by rwam** [comment]
@dbaeumer all `*.vue` and `*.js` files should be linted. I'm using `yarn lint` which is a shortcut for `eslint --ext .js,.vue --ignore-path .gitignore .`. On `master` this results in
```bash
…

/…/pages/index.vue
  27:13  error  Missing trailing comma  comma-dangle
  34:52  error  Missing trailing comma  comma-dangle
  34:53  error  Missing trailing comma  comma-dangle
  35:8   error  Missing trailing comma  comma-dangle
  36:6   error  Missing trailing comma  comma-dangle
  37:4   error  Missing trailing comma  comma-dangle

/…/plugins/uikit.js
  6:16  error  Missing trailing comma  comma-dangle

✖ 52 problems (52 errors, 0 warnings)
  52 errors and 0 warnings potentially fixable with the `--fix` option.
```
And with `yarn lint --fix` I can fix all of the errors.

**Comment by dbaeumer** [comment]
Here is what I see if I open `nuxt.config.js`

<img width="704" alt="capture" src="https://user-images.githubusercontent.com/1931590/78573564-25b78d80-7829-11ea-81de-18c1d8686ec5.png">

**Comment by rwam** [comment]
Hm, I see. It seems that js files work, but all `.vue` files show no problems furthermore. Maybe an issue with the vue plugin.

**Comment by dbaeumer** [comment]
@rwam Let me know if you think there is anything else not working in regards of the ESLint extension.

**Comment by rwam** [comment]
Too bad: after upgrading the dependency tree old projects are affected too now: no eslint in VSCode 😞. Have to check <https://medium.com/@agm1984/how-to-set-up-es-lint-for-airbnb-vue-js-and-vs-code-a5ef5ac671e8> maybe I find a solution to get it work again.

**Comment by dbaeumer** [comment]
Is there anything special in the ESLint Output channel. What helps as well is to ensure that validation works correctly in the terminal before getting it to work in VS Code.
