### ISSUE TITLE
Auto import auto fix missing

### ISSUE THREAD

**Issue by pailhead** [microsoft/vscode-eslint#914]
I cannot get the import option when trying to auto fix `no-undef`, i can only disable the rule. I've seen vscode offer to import files in this menu. If i start typing the class, it will offer to auto import, just can't autofix. Is there a way to get this functionality?

![image](https://user-images.githubusercontent.com/4681282/76596211-cb8e0b80-64ba-11ea-8677-e5776a5adc6f.png)

**Comment by dbaeumer** [comment]
@pailhead only if ESLint offers is (e.g. https://github.com/eslint/eslint). Can you fix the problem using ESLint when running ESLint in a terminal with --fix.
