### ISSUE TITLE
some problem with custom rules

### ISSUE THREAD

**Issue by Firstnote** [microsoft/vscode-eslint#915]
I wrote some non-built-in eslint rules myself, but vscode doesn't recognize them.
"Definition for rule 'no-@zl' was not foundeslint(no-@zl)",How to get vscode to recognize these rules

**Comment by dbaeumer** [comment]
Does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Firstnote** [comment]
> Does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

it really works when i use eslint in the terminal with the option "--rulesdir",here is the GitHub repository:https://github.com/Firstnote/eslint.git.

**Comment by Firstnote** [comment]
> Does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

I just want to know if there is any configuration that can solve this problem

**Comment by dbaeumer** [comment]
@Firstnote the settin `eslint.options` is your friend. See https://github.com/microsoft/vscode-eslint.

Please ping if this doesn't fix your problem.
