### ISSUE TITLE
Respect the `typescript.tsdk` setting

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode-eslint#923]
I was trying to use a version of TypeScript that was built locally by using the `typescript.tsdk` setting, but was getting strange parse errors like `Parsing error: ',' expected.` and `Parsing error: ')' expected.` when using the `awaited` type. It turns out that the extension wasn't using the same version of TypeScript as the editor itself.

The ESLint extension didn't inform me that these errors were coming from ESLint, so I was very confused about what was going on and I didn't realize what was wrong until I disabled extensions one-by-one.

**Comment by dbaeumer** [comment]
@DanielRosenwasser I am not sure exactly what the issue is. The VS Code ESLint extension doesn't ship with any TS reference. It even doesn't ship any eslint version. Are you using the typescript eslint parser. If so I think that parser would need to respect that setting (although I don't know how it would).

**Comment by dbaeumer** [comment]
@DanielRosenwasser anything you can provide for clarification.

**Comment by DanielRosenwasser** [comment]
@dbaeumer yes, I was using typescript-eslint-parser. So is the idea that this extension strictly uses whatever is in `node_modules`?

**Comment by dbaeumer** [comment]
@DanielRosenwasser No, it uses what a user would use when running eslint in the terminal executed from the workspace folder. So if the `typescript-eslint-parser` is able to pick up a custom TypeScript parser in the terminal I would pick it up when running ESLint inside the extension. I try very hard to stay "terminal" compatible
