### ISSUE TITLE
Consistently provide attribution of diagnostics to ESLint

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode-eslint#924]
Based off of the experience in #923

> The ESLint extension didn't inform me that these errors were coming from ESLint, so I was very confused about what was going on and I didn't realize what was wrong until I disabled extensions one-by-one.

Similar to how TypeScript and ESLint errors have an attribution with a code (e.g. `ts(XXXX)`, `eslint(linebreak-style)`), I think this error should have pointed out that it was coming from ESLint.

**Comment by dbaeumer** [comment]
Can you provide me with a screen shot on were that error was shown. All diagnostics reported by ESLint should get an eslint prefix.

**Comment by dbaeumer** [comment]
@DanielRosenwasser any screen shot you can provide?

**Comment by DanielRosenwasser** [comment]
@dbaeumer might take me a bit because I'm working off of a spare computer since my main one went bad, but I'll try to get back to you on that.

**Comment by dbaeumer** [comment]
OK. I will reopen the issue then.

**Comment by DanielRosenwasser** [comment]
Okay, I figured it out. The use-case where you'd run into this is

* running the nightly version of TypeScript via the VS Code extension
* having a stable version of TypeScript and ESLint installed locally
* using a feature that's supported by the nightly TypeScript version, but not the local one.

At the time, the experience I had was writing code like the following:

```ts
export class Container<T> {
    private value: T;
    constructor(value: T) {
        this.value = value;
    }

    async getAsyncValue(): Promise<number> {
        throw "";
    }
}
```

![image](https://user-images.githubusercontent.com/972891/78405415-4aa3ca80-75b5-11ea-8668-2aba86b7af8a.png)

We removed the `awaited` operator, so you'll now get an error from TypeScript as well, but before that you'd just get an error message like

```
Parsing error: '>' expected
```

**Comment by dbaeumer** [comment]
This might be a VS Code UI problem. I the screen shot below the problems view shows that the error came from ESLint. However no code since the ESLint library didn't provide one.

<img width="504" alt="capture" src="https://user-images.githubusercontent.com/1931590/78572299-952c7d80-7827-11ea-832d-d740c0f82476.png">

@sandy081 do you know who owns the code for showing error messages in the hover?

**Comment by sandy081** [comment]
Its me :) So you do not see source in the hover is the issue?

**Comment by DanielRosenwasser** [comment]
Yeah, I think what I would expect is something along the lines of

```
Parsing error: '>' expected (eslint)
```

**Comment by sandy081** [comment]
Fixed - https://github.com/microsoft/vscode/issues/94588

**Comment by dbaeumer** [comment]
@sandy081 THANKS!
