### ISSUE TITLE
Quick fix puts import at wrong location for vue components

### ISSUE THREAD

**Issue by chbndrhnns** [microsoft/vscode-eslint#926]
When I try to use quick fix actions for the `no-undef` error, the resulting `import...` statement ends up in the wrong location.
Looking at the screencast, the import statement is put at the top of the file instead of at the top of the `<script></script>` section.

![Kapture 2020-03-17 at 16 24 09](https://user-images.githubusercontent.com/7534547/76871873-ea4e2280-686b-11ea-8a6f-c536a0032412.gif)

**Comment by dbaeumer** [comment]
@chbndrhnns how does the error look like at that position. I am pretty sure this is a TypeScript error and the fix comes from TypeScript.

**Comment by chbndrhnns** [comment]
The error message is:

```
any
'Prop' is not defined.eslint(no-undef)
Cannot find name 'Prop'.Vetur(2304)
```

**Comment by chbndrhnns** [comment]
An interesting fact is that if there is already one existing import statement in the `script` block, the quick fix succeds like here:

![Kapture 2020-03-18 at 15 24 14](https://user-images.githubusercontent.com/7534547/76970716-93f4e880-692c-11ea-9bc7-6b4b1de99931.gif)

**Comment by dbaeumer** [comment]
What happens if you fix the error using eslint in the terminal. Does the import statement get inserted at the right location?

**Comment by chbndrhnns** [comment]
When I am running `./node_modules/.bin/eslint --fix src/components/test.vue`, I get this output:

```
/<redacted>/src/components/test.vue
  9:2  error  'Component' is not defined  no-undef
```

**Comment by dbaeumer** [comment]
@chbndrhnns this indicates that the problem is actually not a eslint problem as I was speculating before. Can you please provide me with a screen shot showing your problems to see who else reported the problem.

**Comment by chbndrhnns** [comment]
Are you thinking of such a screenshot?

<img width="841" alt="Screenshot 2020-03-20 11 14 19" src="https://user-images.githubusercontent.com/7534547/77154438-f9b3b280-6a9b-11ea-8cb6-65605ffcd697.png">

**Comment by dbaeumer** [comment]
Yes, exactly. This is actually not a ESLint issue. The error `Cannot find name 'Prop'` comes from the Vetur extension including the fix to insert the import. Please report the issue there.

**Comment by chbndrhnns** [comment]
Thanks so much for troubleshooting that with me!

**Comment by chbndrhnns** [comment]
Created https://github.com/vuejs/vetur/issues/1795
