### ISSUE TITLE
保存代码右下角一直提示信息

### ISSUE THREAD

**Issue by BobsLi** [microsoft/vscode-eslint#927]
Issue Type: <b>Bug</b>

vue-cli3，在组件内修改保存代码时，右下角一直提示信息，“正在保存“CommandChart.vue”: 正在从“'Vetur', 'ESLint'”获取代码操作([配置](命令: workbench.action.openSettings?%5B%22editor.codeActionsOnSave%22%5D))。”，从而导致所有扩展插件都不能用，有时候重启打开有用，有时候这样操作也无效

Extension version: 2.1.1
VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by dbaeumer** [comment]
@BobsLi can you please provide the description in English. And to ease tracking down your problem a GitHub repository that I can clone is appreciated.

**Comment by mrtangdong** [comment]
@dbaeumer  I encountered the same problem, but I am not this project. It should be a problem with the VScode editor. The problem description is: "XXX.vue" is being saved: getting code operations from "'Vetur', 'ESLint'". I don't know how to solve the problem of stuck on the verification when saving the file.

**Comment by dbaeumer** [comment]
@mrtangdong do you have a GitHub repository I can clone that demos what you are seeing.

**Comment by mrtangdong** [comment]
@dbaeumer  
This is not a problem with the code, it is a problem with the VS Code editor. I have solved it.

**Comment by dbaeumer** [comment]
@BobsLi any additional input?

**Comment by miomua** [comment]
![image](https://user-images.githubusercontent.com/33140872/78002059-32d80680-7369-11ea-8970-ad30d9236d75.png)
