### ISSUE TITLE
Not underlining errors

### ISSUE THREAD

**Issue by Jamesgz** [microsoft/vscode-eslint#928]
No no-undef errors are getting underlined.
[gif of it happening](https://gyazo.com/b45230b3830c0f0887868e64aff5d4a0)

**Comment by dbaeumer** [comment]
@Jamesgz does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Jamesgz** [comment]
Solved. It was a problem in my package.json
