### ISSUE TITLE
Investiagte to pass probe / validate settings  as `--ext` 

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-eslint#929]
See https://github.com/microsoft/vscode-eslint/issues/922

**Comment by ford04** [comment]
Not sure, if this is the same issue, as mine is specifically about `eslint.lintTask.options`:

Workspace is linted fine on a per-file basis with no custom config of vscode-eslint.
However, if I define a lint task for the whole project by
```
"eslint.lintTask.enable": true,
```
, it does not work out of the box:
>  Executing task: node_modules\.bin\eslint.cmd . <
> Oops! Something went wrong! :(
> ESLint: 6.8.0.
> You are linting ".", but all of the files matching the glob pattern "." are ignored.
> ...

I have to manually repeat the extension just for the project linting:
```
"eslint.lintTask.options": ". --ext .js,.jsx,.ts,.tsx",
```
This came surprising, as the linting on a per-file basis worked like a charm without any configuration of file extensions. Adding 
```
"eslint.options": {
    "ext": ".js,.jsx,.ts,.tsx"
},
```
, while leaving `"eslint.lintTask.options"` out did not work for me. I think, the best developer experience would be to automatically pass the information about checked extensions on to the task.

---

vscode-eslint 2.1.3
VS Code 1.44.0
"eslint": "^6.8.0"

**Comment by snebjorn** [comment]
To others finding this looking for a fix to ESLint squigglies in HTML files.
I only had to add: `"eslint.validate": ["typescript", "html"]`

🤞 for a fix

**Comment by dbaeumer** [comment]
No further action planned.
