### ISSUE TITLE
show documentation not showing up in right click menu

### ISSUE THREAD

**Issue by shaileshiyer** [microsoft/vscode-eslint#932]
The show documentation action which used to show up in the right click menu when clicking on a linting problem is no longer showing up. Earlier it even used to show fix issue or peek at issue from the problems panel in vscode.
![Screenshot_20200326_160700](https://user-images.githubusercontent.com/19362829/77637675-06dd0f80-6f7c-11ea-901e-7a7e8664f047.png)

**Comment by dbaeumer** [comment]
@sandy081 did anything changed here. I see the same and I am pretty sure this worked before.

**Comment by dbaeumer** [comment]
Look like the UI changed. @shaileshiyer you now have to hover over the error icon. If it is fixable it truns into a light bulb. @sandy081 is this correct ?

**Comment by dbaeumer** [comment]
Actually there is more to it. It works after there is the first TS error. Otherwise it doesn't.

**Comment by dbaeumer** [comment]
I debugged it and my code action provider is called and returns code actions. @sandy081 can you please investigate or let me know what I could do wrong here.

**Comment by shaileshiyer** [comment]
Ya hovering on top of the icon works. The Icon changes to a light bulb and shows all the actions available autofix, show documentation etc. Only after that are the actions being showed up after right clicking on the line.

**Comment by sandy081** [comment]
@dbaeumer I have not changed anything here. I ask for code actions as follows:

```
getCodeActions(model, markerRange, { type: CodeActionTriggerType.Manual, filter: { include: CodeActionKind.QuickFix } }, Progress.None, cancellationToken)
```

Can you please keep a breakpoint at following location and see if quick fixes are set?

https://github.com/microsoft/vscode/blob/56a33c4198937092426dac5be064e8dc9c71ecfd/src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts#L631

**Comment by dbaeumer** [comment]
I was debugging it and the code actions make it to the problems view. They show up today with one exception where I clicked on the error icon right after VS Code opened. In that case the code actions never showed up. I had to reload the window. Is there some cancelling involved or do you cache the result?

**Comment by sandy081** [comment]
Yeah, code actions promise is cached here - https://github.com/microsoft/vscode/blob/9f4af01e72a0196b0f4e6e4e5e60d35168b6e468/src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts#L643

Is there an issue with caching?

**Comment by dbaeumer** [comment]
I have no steps but what I noticed is that I ended up in a state where the light bulb never showed up even after clicking on it several times. What happens if the code action promise runs for a long time. Is there a timeout. 

And in ESLint some of the actions I contribute depend on settings. Might be minor but the problems view wouldn't honor a settings change.

**Comment by sandy081** [comment]
I do not look for any settings and I just ask for code actions with specific types. Not sure if there is something I need to adopt there.

Re timeout, I also do not do anything here. I expect the util or service I am calling is taking care of it.

@mjbvz any insights?

**Comment by mjbvz** [comment]
@sandy081 The problems panel only shows code actions with the `QuickFix` kind. We don't have any timeout for code actions themselves but the requester can cancel the request

**Comment by dbaeumer** [comment]
@sandy081 any plans to change this?

**Comment by sandy081** [comment]
@dbaeumer Do the timeout or?

**Comment by dbaeumer** [comment]
@sandy081 I was referring to this

> @sandy081 The problems panel only shows code actions with the QuickFix kind (you need to explicitly set this)

**Comment by dbaeumer** [comment]
Not sure if it is actually the problem.

**Comment by sandy081** [comment]
Yeah, I am only asking for quick fixes. Not sure if I have to change this?

**Comment by dbaeumer** [comment]
@sandy081 I am actually a little at a loss here. In the screen shot below I see quick fixes in the light bulb but hovering over the icon in the problems view nor clicking on it reveals any code actions. Any idea why this would be.

<img width="681" alt="capture" src="https://user-images.githubusercontent.com/1931590/78569172-7fb55480-7823-11ea-9e77-30d9dfbd08c1.png">

It works as expected if another error shows up in the problems view. The error can be totally unrelated to TS (for example a JSON error). 

I also noticed some other weirdness. If I reload in the above setup with the problems view *NOT* visible quick fix in the problems view does not work. If I reload with the problems view visible everything works as expected.

I still think that this is a timing problem with the problems view on startup given the different behavior whether the problems view is active or not.

**Comment by sandy081** [comment]
@dbaeumer Can you provide steps to repro so that I can investigate ?

**Comment by dbaeumer** [comment]
@sandy081 fait to ask for steps :-).

- clone https://github.com/Microsoft/vscode-eslint.git
- checkout `88aaa9e`
- chdir `playgrounds/ts`
- npm install
- open VS Code with eslint extension installed.
- open test.ts
- make sure problems view is not visible
- reload Window
- wait until ESLint errors show up in editor
- open problems view
- click on problem to see quick fixes. **Observe**: it doesn't work
- reload Window
- wait until problems show up in problems view.
- click on problem to see quick fixes: **Observe**: it does work

**Comment by dbaeumer** [comment]
@sandy081 did you have time to look into this

**Comment by sandy081** [comment]
Not yet. Filed issue in VS Code repo to track it - https://github.com/microsoft/vscode/issues/95461

**Comment by dbaeumer** [comment]
OK. Ping if there is anything for me to do.

**Comment by jeanp413** [comment]
Took a shot at this and created https://github.com/microsoft/vscode/pull/95653 that seems to fix the issue

**Comment by dbaeumer** [comment]
@jeanp413 thanks. 

@sandy081 can you have a  look?

**Comment by sandy081** [comment]
Sure.

**Comment by sandy081** [comment]
Thanks @jeanp413 for the PR. Its fixed.

**Comment by dbaeumer** [comment]
@sandy081 can I close this issue ?

**Comment by sandy081** [comment]
Yeah

**Comment by dbaeumer** [comment]
Closing then. Thanks for looking into this.
