### ISSUE TITLE
Nested package.json configs conflict.

### ISSUE THREAD

**Issue by mikestopcontinues** [microsoft/vscode-eslint#933]
This is related to #712 .

In my monorepo project, I have a root package.json and nested package.jsons. I expect that the nearest eslint config will apply to the files within that directory, but so far, the only way I could get that to work was using .eslintrc files instead of package.json.

I tried setting "root" = true in different permutations. And I also tried using package.eslintIgnore in the root directory to ignore the nested package dirs, then not-ignoring them in the subs.

It probably seems like a minor thing since I have the functionality working with the .eslintrc files, but eslint itself worked fine with nested package configs. Also, package config helps to keep the file tree from exploding.

**Comment by mikestopcontinues** [comment]
The problem turns out to be a bit worse. If I switch to .eslintrc, for some reason I then have to use babel.config.js over package babel config, which then breaks my code sharing.

**Comment by dbaeumer** [comment]
I think you very likely need to define a working directory setting. When you lint in the terminal directly do you need to do a cd into some of the sub folders to make it work correctly?

**Comment by mikestopcontinues** [comment]
Exactly. I'll take a look at setting working dir and get back to you. Thanks!

**Comment by mikestopcontinues** [comment]
@dbaeumer that was it! Thanks, man!

For others who find this, the fix was to set settings.json `"eslint.workingDirectories": [{ "mode": "auto" }]`.
