### ISSUE TITLE
React Native components not found

### ISSUE THREAD

**Issue by tapz** [microsoft/vscode-eslint#936]
Started to give me errors about react-native components even though everything works and is as before. Just these ugly eslint errors:

<img width="573" alt="Screenshot 2020-03-31 at 0 21 28" src="https://user-images.githubusercontent.com/11726387/77963201-9fa9bd00-72e5-11ea-81eb-6243b616d72c.png">

**Comment by dbaeumer** [comment]
@tapz does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by tapz** [comment]
Looks like eslint gives the same error in command line. Weird as the app works perfectly fine.

**Comment by dbaeumer** [comment]
Then this is expected since the extension relies on the behaviour of ESLint on the command line. I will close the issue then. Please ping if you think otherwise.
