### ISSUE TITLE
Solution for global plugin installs with eslint > 6.0 

### ISSUE THREAD

**Issue by baybal** [microsoft/vscode-eslint#938]
A solution for global plugin installs have been completely overlooked during discussion about https://github.com/microsoft/vscode-eslint/issues/696

I can confirm that the solution below works for me with eslint 6 and up, with plugins and configs

I think we should get path for resolvePluginsRelativeTo from the system node install
----
Memo for monorepo players:

1. install all modules globally, `npm i -g ...`
1. add the option to force vscode-eslint to use global path (`npm list -g | head -n 1`) instead the local path (always 404 😂 )

```json
// settings.json
{
    "eslint.options": {
        "resolvePluginsRelativeTo": "/usr/local/lib/node_modules"
    }
}
```

Refs:

- https://eslint.org/docs/user-guide/migrating-to-6.0.0#-plugins-and-shareable-configs-are-no-longer-affected-by-eslints-location
- https://eslint.org/docs/developer-guide/nodejs-api#cliengine

_Originally posted by @up9cloud in https://github.com/microsoft/vscode-eslint/issues/696#issuecomment-543549287_

**Comment by baybal** [comment]
npm root -g to get NODE_PATH

**Comment by dbaeumer** [comment]
@baybal I am not sure exactly what you think is missing. The extension does honor the global install using the command `npm config get prefix`. 

Can you please explain.

**Comment by up9cloud** [comment]
I guess he just wish you could reconsider https://github.com/microsoft/vscode-eslint/issues/696#issuecomment-566127447. Instead, to use global as default to solve the mono issue.

**Comment by dbaeumer** [comment]
@up9cloud I see the wish but I still have no idea on how to solve this since whatever I do will make another camp unhappy. So the best you can do tight now is to use

```
"eslint.workingDirectories": [
    { "mode": "auto" }
],
```

In a mon repro or explicitly list the working directories. I will close the issue. Please ping if someone disagrees.

**Comment by Kagami** [comment]
I've installed eslint plugins globally because I find it tedious to install them for every project, especially given amount of dependencies. Linter's plugin versions is not something you need to differentiate much.

Setting `resolvePluginsRelativeTo` helped, but it won't work for parsers due to https://github.com/eslint/eslint/pull/13234. After applying the fix from the PR everything works fine, I don't need to install copy of plugins to every project anymore.
