### ISSUE TITLE
Watch dependencies of eslintrc for changes

### ISSUE THREAD

**Issue by ayush000** [microsoft/vscode-eslint#941]
For a list of files, I have set up an override in eslintrc. This list of files comes from another file

overriddenFiles.js
```js
module.exports = ["path1", "path2"]
```

.eslintrc.js
```js
const overriddenFiles = require("./overriddenFiles");

module.exports = {
 parserOptions: {
  sourceType: "script"
 },
 overrides: [
  {
   files: overriddenFiles,
   parserOptions: {
    sourceType: "module"
   }
  }
 ]
}
```

Whenever I make a change in `overriddenFiles.js`, I need to reload the whole editor for config changes to take effect. Is it possible to provide an option to watch files other than eslintrc for changes and reload automatically?

**Comment by dbaeumer** [comment]
I will still accept a PR if someone wants to work on this.
