### ISSUE TITLE
codeActionsOnSave as array opens browser tab?

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-eslint#942]
- VSCode Version: 1.44.0
- OS Version: Ubuntu 16.04.5 (via remote SSH)

Steps to Reproduce:

1. Changed my config to:
```javascript
  "editor.codeActionsOnSave": [
    "source.organizeImports",
    "source.fixAll.eslint"
  ],
```
2. Make some changes in a file that ESLint tries to fix. I am using the Prettier plugin+config `"plugin:prettier/recommended"`.
3. It opens https://github.com/prettier/eslint-plugin-prettier#options 😆 

Yes, I know it sounds weird, but it is consitent. Restart of VS Code after changing from object to array also did not help.

Does this issue occur when all extensions are disabled?: Since I assume this is in combination with an extension, I'm not sure disabling is of any value.

Original issue I wrote on VS Code: https://github.com/microsoft/vscode/issues/94774

**Comment by thernstig** [comment]
Here is the change that happened in VS Code 1.44.0: https://code.visualstudio.com/updates/v1_44#_explicit-ordering-for-code-actions-on-save

**Comment by 0x80** [comment]
I'm experiencing the same issue since my vscode updated itself.

Maybe worth mentioning that I'm using prettier v2, and I'm seeing these types of errors in the eslint output:

> Failed to apply command: eslint.applyDisableLine

**Comment by 0x80** [comment]
As suggested in the linked issue, reverting back to the object definition solved the issue for me:

```
"editor.codeActionsOnSave": {
    "source.organizeImports": true,
    "source.fixAll": true
  },
```

**Comment by 0x80** [comment]
I'll have to walk that back a bit. I am now editing a file where the organizeImports and fixAll have a race-condition and organize happens after the fix, messing up the formatting again. 

I assume this is why they introduced the array format. So that you can explicitly define the order of actions.

**Comment by yonifra** [comment]
Happens to me as well all the time, really annoying since I end up with a tab in Chrome for each fix, and it distracts me from working properly.

**Comment by yonifra** [comment]
Btw, @0x80  - I tried reverting back to object format, I get a huge degregation in performance. I wasn't sure why but I guess I'm experiencing the same race condition as you are.
I see we're all using `organizeImports` in our settings and I guess this specific setting might break stuff like it does in our case.
My setting is:

```
"editor.codeActionsOnSave": [
    "source.organizeImports",
    "source.fixAll"
  ],
```

**Comment by 0x80** [comment]
@yonifra I simply removed organizeImports from the actions for now, until there is a fix. I think you need the array format / sequential order to make it work properly.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode-eslint/issues/939.
