### ISSUE TITLE
Error: "Cannot read property 'source.fixAll.eslint' of null"

### ISSUE THREAD

**Issue by andrao** [microsoft/vscode-eslint#945]
This issue has come up with the latest version – `2.1.3`:

![image](https://user-images.githubusercontent.com/20170243/79378304-ef0d0180-7f11-11ea-9edf-63b5609c1510.png)

I reckon it's caused by the new `CodeActionsOnSave.isExplicitlyDisabled()` function here: https://github.com/microsoft/vscode-eslint/commit/5d3bc851de5a841ac90432e3bc95797c30eaf1da#diff-bc3c0f2fe3aca9ddbe96347ffb00641eR466-R471, which doesn't account for the case where `setting` is `null`.

Through no deliberate action of my own, my _User_-level settings were updated to include:
```
{
   // ...
   "editor.codeActionsOnSave": null
}
```

Again I'm unsure as to why this happened – it wasn't a manual edit. I am indeed told that `null` is an invalid value when viewing my settings file:

![image](https://user-images.githubusercontent.com/20170243/79379716-29779e00-7f14-11ea-8dd6-f2d30c4660a7.png)

May be common enough to warrant a fix.

---
Issue is resolved by reverting to `2.1.2`.

**Comment by dbaeumer** [comment]
@andrao How do your user level and workspace level settings look like when this happend?
