### ISSUE TITLE
all suggestions being applied on save

### ISSUE THREAD

**Issue by henriiik** [microsoft/vscode-eslint#947]
Hello!

Since i upgraded vscode-eslint to 2.1.3 it seems like all suggestions are being applied on save. So for instance if i have an unused variable in a file, it will add a comment to the line above and open up the documentation for the rule.

```ts
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const foo = "bar";
```
my settings looks like this:

```json
{
	"[typescriptreact]": {
		"editor.codeActionsOnSave": {
			"source.organizeImports": true
		}
	},
	"editor.codeActionsOnSave": {
		"source.fixAll.eslint": true
	},
}
```

but i change it to the following, the problem goes away:

```json
{
	"[typescriptreact]": {
		"editor.codeActionsOnSave": {
			"source.organizeImports": true,
			"source.fixAll.eslint": true
		}
	},
}
```

**Comment by dbaeumer** [comment]
I am able to reproduce this. Looking into a fix. In the worst case downgrade to 2.1.2.

**Comment by dbaeumer** [comment]
@henriiik I have created a new preview version which should address the problem. Can you please give it a try and let me know if it works for you. It is available here: https://github.com/microsoft/vscode-eslint/releases/tag/release%2F2.1.4-next.1 and you can install it using the `Install Extension from VSIX` command.

Thanks.

**Comment by henriiik** [comment]
I tried it and it does fix the problem, thanks! 🙂

**Comment by dbaeumer** [comment]
Thanks for testing it.
