### ISSUE TITLE
eslint suggested fix for `no-unused-vars` breaks function signature

### ISSUE THREAD

**Issue by Morriz** [microsoft/vscode-eslint#948]
When I choose "Delete all unused declarations" this signature (of which `res` _is_ used):

```js
function errorMiddleware(err, req, res, next) {
...
```
gets converted to:
```js
function errorMiddleware(err, res) {
...
```
which swaps `req` for `res`

**Comment by dbaeumer** [comment]
@Morriz  does the validation/fixing happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Morriz** [comment]
This only happens when I choose the blue icon suggestion "Delete all unused declarations" in vscode. There is no autofix available for these situations as it needs to be user determined. Right?

**Comment by dbaeumer** [comment]
@Morriz are you sure this comes from ESLint and not from TypeScript itself. How does the corresponding error look like
