### ISSUE TITLE
"Do you want Code to open the external website?" on eslint errors

### ISSUE THREAD

**Issue by ruffin--** [microsoft/vscode-eslint#949]
VS Code has started trying to open links to eslint rule failure descriptions related to my code in my browser since it (VS Code) last updated.

Each time my code builds with eslint errors, I receive a dialog with "Do you want Code to open the external website?" with links to eslint issues, like `https://eslint.org/docs/rules/quotes`.

!["do you want code to open" dialog example](https://i.imgur.com/nz6Q9QL.png)

Is there anything about the extension that would cause this? It did start after VS Code updated on restart earlier today.

Here's my VS Code info:

```
Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:47:00.296Z (5 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

v2.1.3 for this extension.

---------

**EDIT:** Just for fun, I uninstalled and reinstalled, and now it's shoving in line-specific fixes when I save and then trying to open the URL. 

For example, I'm now getting `// eslint-disable-next-line no-console` inserted above each `console.log` I add in a file on save. It's never done this before, and I would ob prefer it didn't now.

Hopefully I just have a wacky setting, but I haven't changed anything since it was working without all this mess.

Changed settings to have 

```
  "eslint.codeAction.showDocumentation": {
    "enable": false
  },
```

... which seems to have stopped the browser opening [though it sounds like the external browser opening still wasn't what the extension expected].

~~I can't get the auto disables to stop though. I don't want `problems` or `all` for `eslint.codeActionsOnSave.mode"`, I don't think. I want none so I can do it manually.~~

And adding this...
```
  "[typescript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": false
    }
  }
```

... seems to fix the auto-correct, but, um, why did this just start happening? I'm curious if the settings migration screwed something up recently. 

I do have prettier installed as well.

**Comment by ruffin--** [comment]
[Issue-947](https://github.com/microsoft/vscode-eslint/issues/947) looks related, huh?

**Comment by dbaeumer** [comment]
@ruffin-- do you have a repository I can clone that demos this. I was not able yet to reproduce. I think I have a fix in master but without being able to reproduce I am not sure :-).

**Comment by dbaeumer** [comment]
@ruffin-- I have created a new preview version which should address the problem. Can you please give it a try and let me know if it works for you. It is available here: https://github.com/microsoft/vscode-eslint/releases/tag/release%2F2.1.4-next.1 and you can install it using the `Install Extension from VSIX` command.

Thanks.
