### ISSUE TITLE
ESLint doesn't find recommended react preset

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode-eslint#95]
I get this error whenever I open a javascript file. No global eslint is present, only a local installation.

VSCode: 1.3.1-insiders

Error Message:
```
Cannot read config package: eslint-config-plugin:react/recommended Error: Cannot find module 'eslint-config-plugin:react/recommended' Referenced from: /Users/marvinhagemeister/dev/test/.eslintrc
```

.eslintrc
```json
{
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "ecmaFeatures": {
        "modules": true,
        "blockBindings": true,
        "jsx": true
    },
    "env": {
        "es6": true,
        "node": true,
        "browser": true,
        "mocha": true
    },
    "plugins": [
        "react"
    ],
    "extends": ["eslint:recommended", "plugin:react/recommended"]
}
```

package.json
```json
{
  "devDependencies": {
    "eslint": "^2.13.1",
    "eslint-plugin-react": "^5.2.2"
  }
}

```

**Comment by dbaeumer** [comment]
@marvinhagemeister does that local eslint installation have the plugin:react installed. And please note that either both eslint and plugins must be installed locally or  globally. Eslint doesn't work if parts a local and parts are global.

Could you share your project. I tested this with a toy example and it works for me.

**Comment by scvnc** [comment]
I spun my wheels on this issue but solved it (in my case) by trying to remove every trace of eslint on my system before installing eslint and eslint-plugin-react locally to the project.  After I did that I realized that I had the following tree and that was probably screwing it up

```
- project_folder (vscode open here)
   - node_modules/eslint
   - experimental_react_boilerplate
       - node_modules/eslint
       - node_modules/eslint-plugin-react
```

I surmise vscode was focused on the root `node_modules` it was opened with and thus didn't find the accompanying `eslint-plugin-react`.

vs code 1.3.1

**Comment by marvinhagemeister** [comment]
The issue for me was that I had eslint installed both globally and locally. Removing the global installation solved this issue for me.
