### ISSUE TITLE
"Extension 'eslint' cannot format file.ts" error

### ISSUE THREAD

**Issue by adunne-resilient** [microsoft/vscode-eslint#951]
Eslint extenstion is not formatting my files at all. Random indentation remains, after saving or even when attempting to formatt manually by right-click > format.

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

It is working for me. Please be aware that format must be explicitly enable to be used with ESLint.

**Comment by JustFly1984** [comment]
@adunne-resilient can you please look at output Eslint in vscode? does it have errors? note - you need to have js/ts file open and in focus, to get Eslint output in the list

**Comment by adunne-resilient** [comment]
Apologies, it took me quite a while to sort out my workspace (and forgot to get back to this thread). I believe it was a combination of bad settings and prettier config in vscode.
