### ISSUE TITLE
Directories starting with. Will not be checked

### ISSUE THREAD

**Issue by bosens-China** [microsoft/vscode-eslint#953]
## Example
``` js
docs
├─ .vuepress
│    ├─ config.js
│    ├─ enhanceApp.js
│    └─ styles
│           └─ index.styl
└─ README.md
src
├─ main.js
└─ utils.js
```
JS under docs will not be checked，Please tell me how to solve it?

**Comment by dbaeumer** [comment]
@bosens-China directories starting with the dot are ignore by default by ESLint. You need to include them in the `.eslintignore` file. After doing that please check if the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by bosens-China** [comment]
> @bosens-China directories starting with the dot are ignore by default by ESLint. You need to include them in the `.eslintignore` file. After doing that please check if the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

Isn't `.eslintignore` ignore the specified file or directory?
I now want to force check this folder

**Comment by dbaeumer** [comment]
See https://eslint.org/docs/user-guide/configuring#eslintignore and the `!` syntax
