### ISSUE TITLE
[Error] Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser

### ISSUE THREAD

**Issue by lordisback** [microsoft/vscode-eslint#954]
Hi~ I found an error descibed above, and my versions are listed below:

package | version
-- | --
vscode-eslint | 2.1.5
@typescript-eslint/parser | 2.27.0
TypeScript | 3.7.2
ESLint | 6.8.0
vscode|1.44.1
Node.js|12.8.1
V8|7.8.279.23-electron.0
OS| Linux x64 4.13.0-36-generic

eslint configs:
```
module.exports = {
    parser: '@typescript-eslint/parser',
    parserOptions: {
        warnOnUnsupportedTypeScriptVersion: false,
        ecmaVersion: 6,
        sourceType: 'module',
        project: 'tsconfig.json',
    }
}

```

This error happens when I use symlink as my workspace dir, e.g.
`/home/xxx/workspace/  -> /workspace `

I tried to div into source code and found languageServer use symlink uri when file changed, e.g. 
`/home/xxx/workspace/src/index.js`
 but typescript-estree use extra.tsconfigRootDir = '/workspace' to createProjectProgram.

I also found a way to solve this problem: 
```
function getFileSystemPath(uri: URI): string {
	const result = uri.fsPath;
	if (process.platform === 'win32' && result.length >= 2 && result[1] === ':') {
		// Node by default uses an upper case drive letter and ESLint uses
		// === to compare paths which results in the equal check failing
		// if the drive letter is lower case in th URI. Ensure upper case.
		return result[0].toUpperCase() + result.substr(1);
	} else {
		return fs.realpathSync(result); // I added fs.realpathSync to solve this problem
	}
}
```
Let me know if this solution is correct, thank you

**Comment by lordisback** [comment]
Hi~ I found an error descibed above, and my versions are listed below:

package | version
-- | --
vscode-eslint | 2.1.5
@typescript-eslint/parser | 2.27.0
TypeScript | 3.7.2
ESLint | 6.8.0
vscode|1.44.1
Node.js|12.8.1
V8|7.8.279.23-electron.0
OS| Linux x64 4.13.0-36-generic

eslint configs:
```
module.exports = {
    parser: '@typescript-eslint/parser',
    parserOptions: {
        warnOnUnsupportedTypeScriptVersion: false,
        ecmaVersion: 6,
        sourceType: 'module',
        project: 'tsconfig.json',
    }
}

```

This error happens when I use symlink as my workspace dir, e.g.
`/home/xxx/workspace/  -> /workspace `

I tried to div into source code and found languageServer use symlink uri when file changed, e.g. 
`/home/xxx/workspace/src/index.js`
 but typescript-estree use extra.tsconfigRootDir = '/workspace' to createProjectProgram.

I also found a way to solve this problem: 
```
function getFileSystemPath(uri: URI): string {
	const result = uri.fsPath;
	if (process.platform === 'win32' && result.length >= 2 && result[1] === ':') {
		// Node by default uses an upper case drive letter and ESLint uses
		// === to compare paths which results in the equal check failing
		// if the drive letter is lower case in th URI. Ensure upper case.
		return result[0].toUpperCase() + result.substr(1);
	} else {
		return fs.realpathSync(result); // I added fs.realpathSync to solve this problem
	}
}
```
Let me know if this solution is correct, thank you

**Comment by dbaeumer** [comment]
Actually I am not a fan of blindly making this change since it will affect quite some other code passes as well. Can you please elaborate what you think is the root cause of this and why the `typescript-eslint/parser` complain about it with a parsing error. This is absolutely not clear to me.

**Comment by lordisback** [comment]
This error happend at @typescript-eslint/typescript-estree/src/createProjectProgram.ts line 35
![image](https://user-images.githubusercontent.com/13757260/79864024-5263cb80-840b-11ea-94bd-5df0f6504c52.png)

```
extra = {
    tsconfigRootDir: '/workspace',
    filePath: '/home/xxx/workspace/src/index.ts'
   // ignore other properties
}
```
typescript-estree uses 'extra' opotions to init typescript program, typescript will read all files defined by our '/workspace/tsconfig.json' and stores as a Map, the key is the filename start with '/workspace'  not '/home/xxx/workspace', here is my case: ('/ssd' is mine real path and the symlink is '/home/ycma/workspace/ssd')
![image](https://user-images.githubusercontent.com/13757260/79865009-06b22180-840d-11ea-9c42-50035c4ffbe2.png)
so `currentProgram.getSourceFile(extra.filePath)` returns undefined

**Comment by dbaeumer** [comment]
@lordisback is this still an issue for you. If so can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
