### ISSUE TITLE
eslint格式化jsx的时候总要弹出配置受信任域,并不想打开eslint页面啊

### ISSUE THREAD

**Issue by arieltlm** [microsoft/vscode-eslint#957]
代码格式有问题了，此时一点保存，就会弹出配置受信任域，但是并不想信任eslint,不配置的话 每次都会弹出来，配置了又每次都在浏览器上打开eslint页面，而且只在jsx中有问题

**Comment by dbaeumer** [comment]
@arieltlm  does the validation/fixing happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
