### ISSUE TITLE
All plugins stop working

### ISSUE THREAD

**Issue by maxistahl** [microsoft/vscode-eslint#961]
Issue Type: <b>Bug</b>

Eslint stop working, so I tried to restart my vscode but seems like some random error affect some others plugins cause when vscode start again Eslint stop working, and then GitLens stop working... just that. A message error says eslint server fails 5 times in 3 minutes.

Extension version: 2.1.5
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (1.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@maxistahl  can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by matzeeable** [comment]
Had the same issue today. I am using the VSCode Remote Extension and a simply `Uninstall` and `Install` of the extension fixed the issue.

**Comment by dbaeumer** [comment]
@matzeeable extensions don't room to remote automatically.
