### ISSUE TITLE
How to make an import always at the top?

### ISSUE THREAD

**Issue by weihao** [microsoft/vscode-eslint#965]
I want `reflect-metadata` to always be imported first:
```
import 'reflect-metadata' // I want this at the top
import express from 'express'
import { ValidationError } from 'express-validation'
import fs from 'fs'
import morgan from 'morgan'
import cron from 'node-cron'
import path from 'path'
import routes from './routes'
```

But when I format using eslint organize imports, I get:
```
import express from 'express'
import { ValidationError } from 'express-validation'
import fs from 'fs'
import morgan from 'morgan'
import cron from 'node-cron'
import path from 'path'
import 'reflect-metadata' // this will get sorted, oh no.
import routes from './routes'
```

Is there a way to make an import `always placed at the top`? or is there a flag that ignores the sorting of a specific package? Thank you!

**Comment by dbaeumer** [comment]
@weihao this functionality comes from ESLint or one of its plugins itself and not from the extension and will be the same when executing eslint in the terminal. Please file the issue against the corresponding eslint plugin you are using to do the sorting.
