### ISSUE TITLE
[Suggestion] Allow paths to configs in 'package.json' key

### ISSUE THREAD

**Issue by davidbwaters** [microsoft/vscode-eslint#968]
Hi, when adding config through package.json using the 'eslintConfig' key, it only accepts objects and won't accept a path to a config file.  It works with both when running eslint-cli through the command line.  It would be nice to have it try to resolve a path when it gets a string value. It would keep the file cleaner and look consistent other popular project's conventions.

**Comment by dbaeumer** [comment]
A path to the config file is supported via VS Code settings. See the setting `eslint.options`. The default eslint config file `.eslintrc.*` are read by default.

**Comment by dbaeumer** [comment]
Please ping if this doesn't help solve your issue.
