### ISSUE TITLE
Eslint . not working.

### ISSUE THREAD

**Issue by hieusmiths** [microsoft/vscode-eslint#969]
Hi, team.

I met a bug about run eslint all project for CI.
if eslint with relative path file as well.
in the progress dev it working.
it only not working with eslint .
Thank so much to team.

**Comment by dbaeumer** [comment]
@hieusmiths does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
