### ISSUE TITLE
eslintrc configuration cascading not being honored

### ISSUE THREAD

**Issue by johnwest80** [Microsoft/vscode-eslint#97]
This seems obvious, so it's probably something I'm doing wrong.  But I'm seeing that this extension doesn't seem to support hierarchical .eslintrc files.  Check my screenshot.  When I rename the first .eslintrc to .eslintrc.blah, the root .eslintrc rules are applied.  When I rename the .eslintrc.blah back to .eslintrc, the root rules are ignored again.

Is this expected behavior?  In reading the eslint docs, it supports configuration cascading, so I'd think this plugin would support that as well.  I'm hoping I'm just missing something obvious?

![image](https://cloud.githubusercontent.com/assets/1585088/16589326/a17c18b8-42a0-11e6-9fc5-b2537ba83b4f.png)

**Comment by dbaeumer** [comment]
@johnwest80 no this works and when I tested it with a toy example I don't see any problem. Could you share your project. Then I will have a look.

**Comment by johnwest80** [comment]
Ok, so I think I know what the issue is.  eslint from the command line still supports cascading even if "extends:recommended" is specified. However, this plugin no longer uses cascading configuration if "extends:recommended" is specified.  

The below works because I explicitly told eslint to use the parent .eslintrc file after extending recommended.  eslint by default, however, uses the parent .eslintrc without explicitly extending from it when extends:recommended is used.

Does that make sense?

![image](https://cloud.githubusercontent.com/assets/1585088/16634041/14d211c4-439a-11e6-9eda-c9f80714c0c1.png)

**Comment by johnwest80** [comment]
@dbaeumer did the information i provided explain the issue?  i've tried looking through the source, but frankly have no idea where to go to fix this.  can it be fixed?

**Comment by dbaeumer** [comment]
@johnwest80 sorry for the long delay. Actually I delegate all of this to ESLint by using its node API (see here: http://eslint.org/docs/developer-guide/nodejs-api#executeontext). The corresponding code part in the plugin is here: https://github.com/Microsoft/vscode-eslint/blob/master/eslint-server/src/server.ts#L242

I have no idea why ESLint behaves different. If you do any tip is welcome.

**Comment by plug-n-play** [comment]
https://github.com/dbaeumer - Also, please suggest if it is possible to have a standard fallback file .eslintrc.json for all projects which do not have a local file. The idea is to make eslint validate using a local .eslintrc.json if it is available, else refer to a global rule-set defined centrally.

**Comment by dbaeumer** [comment]
@plug-n-play: Yes, this is possible. ESLint by itself looks up the directory parent chain for an ESLint configuration. You can always test this in a terminal by running eslint in there. The ESLint extension doesn't do anything than using the ESLint node library to do its job :-).

**Comment by shreyas-a** [comment]
Any update on the issue. I'm stuck with the same problem.

**Comment by shreyas-a** [comment]
.eslintignore is not being honored, .eslintrc.json does.

**Comment by dbaeumer** [comment]
@shreyas-a does it work for you in the terminal in our setup. If so could you share your project so that I can investigate?

**Comment by shreyas-a** [comment]
root
|
--- client
------.eslintignore
------ eslintrc.json
|
.eslintignore
eslintrc.json

> Something like this. So whatever I've mentioned in client/.eslintignore is not being honored.

**Comment by NicolasVargas** [comment]
Hi,

I'm using a custom name for my .eslintrc file. I only got one in my project and it is located in the root dir. After this fix, i can't refer my file. I can't even use `${workspaceRoot}` variable.
`{"configFile": "${workspaceRoot}/eslint_rules_sonar.json"}`.

Did i do something wrong ?

**Comment by dbaeumer** [comment]
@NicolasVargas the change I did does break something for you. The problem is that when I trigger a validate of a file in a sub directory I used the workspace directory as the current working directory and not the sub directory hence not correctly reading .eslintignore file chains. With the change I did you can't point to the options file using a relative path in our case since the relative path is no cwd dependent (e.g when validating a file in a sub directory I look for the custom config file in a sub directory).

Setting the cwd correctly is still the right fix. You can workaround it for now by making the path to the config file absolute. 

The eslint extension never supported variables in settings (e.g. ${workspaceRoot}). So I can not imagine how that ever worked. But I see the need for it now that the extension correctly used the cwd. Can you open an issue for it. Then I will add support in future releases.
