### ISSUE TITLE
Notification toast per each key stroke

### ISSUE THREAD

**Issue by sajithneyo** [microsoft/vscode-eslint#971]
I have configured my ESLint to run on 'onType'. 

`"eslint.run": "onType"
`

![Capture](https://user-images.githubusercontent.com/27737837/81513018-d6daa780-9342-11ea-88f5-cf9e7a5e5e53.PNG)

This triggers endless notification toasts in vs-code. Please fix this. I want notifications only when ESLint crashes. Not for my lint errors. Underlining errors is enough.

Thank you!

**Comment by dbaeumer** [comment]
I am pretty sure that this is a problem with ESLint itself. 

@sajithneyo  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by sajithneyo** [comment]
It's something related to plugin settings `eslint.validate`. I had it as `"eslint.validate": ["javascript", "typescript"],`. After removing it those notifications went away.

**Comment by dbaeumer** [comment]
Actually a better setting now is `eslint.probe`.

I will close the issue. Please ping if you think there is something outstanding.
