### ISSUE TITLE
Shareable config as baseConfig

### ISSUE THREAD

**Issue by cyberbiont** [microsoft/vscode-eslint#976]
The situation:
My aim is to use some default shareable config across all of my projects, while being able to override it with local .eslintrc.js config files.
At the same time, I also need this setup to work globally in case when I for example work with remote project via SSH and cannot install any local modules.

So I have created a shareable config package eslint-config-myconfig and installed it globally. Now I want to set it as default (extendable by local .eslintrc files).
There's an option in ESLint config called `configFile` that takes a path to configuration file, but this config will override everything else, which is not what I want.
There is also another option called `baseConfig` , that does exactly what is needed, but the problem is that this option takes a configuration object and not a file path. And since I have to specify it in settings.json, I cannot require it from my eslint-config-myconfig to pass it to ESLint.

Maybe vscode-eslint could provide a separate setting for `baseConfig` as file path, that will require config file and pass it as `baseConfig` argument to ESLint?

**Comment by dbaeumer** [comment]
@cyberbiont I am not sure I fully understand what you are proposing. Could you make an example. And could it be related to https://github.com/eslint/eslint/issues/3371

**Comment by cyberbiont** [comment]
Thanks for your attention!

Not sure what eslint/eslint#3371 is about, it seems to be already addressed somehow. I presume currently baseConfig works as intended: 
> baseConfig - Set to false to disable use of base config. Could be set to an object to override default base config as well.
[see](https://eslint.org/docs/2.0.0/developer-guide/nodejs-api#cliengine)

OK, the general idea is to have a global (base) configuration for eslint, that can be extended by local `.eslintrc.js` files per-workspace.
The requirement is to have this configuration inside "shared-config" package, i.e. eslint-config-something, to be able to share it via Github, npm whatever.
So, I can not use traditional "search-up" way and just place this base config somewhere up the path (or in my User folder) for Eslint to pick up, because a) Eslint will not see it inside package subfolder b) eslint-config-something package will be installed globally with npm, and Eslint doesn't search there.
So, what options come to mind? one possible workaround is to use `configFile` CLI option, which allows me to set an explicit path to config file that will be used, but it just overrides everything (i will not be able to extend it this .eslitec.js in workspace).
 `baseConfig`  would allow me to set _base_ config (i.e. extendable), but it takes a config _object_, not a path to config file, and there is no way I can import this config object from my eslint-config-something package and pass it. It would be possible though with a little help from vscode-eslint,
if I could pass 'baseConfig' a filepath instead of object literal in settings.json. So that the file I point to would be imported and passed to eslint's baseConfig CLI option.
Maybe there is something that I'm missing, but I can't see another way to make it work.

**Comment by dbaeumer** [comment]
Actually I am still lost :-(. In general the ESLint extension is relying on the ESLint npm module to resolve and read config files. And I am very reluctant to deviate this is any from since.

Are you able to do what you want in the terminal using normal ESLint cli options? If so can you please provide me with an example?

**Comment by cyberbiont** [comment]
OK, I see your point. The vscode-eslint strictly relies on ESlint options, and that is how it should be, I don't propose you to deviate from it.
The things that vscode-eslint is responsible, though, is how this options are set (with configuration object in settings.json, in this case) and then passed to ESlint itself.

So, the problem is that ESlint itself does not provide `baseConfigFile` option, that should take a path to the arbitrary configuration file. Maybe I should rather open the issue in ESlint and ask them to add one... but, currently, when using ESlint API, there _is_ a possibility to pass a configuration object, exported from file, to baseConfig option. Something like
```js
const eslint = new ESlint({
  baseConfig: require('C:\Program Files\nodejs\node_modules\eslint-config-cyberbiont")
});

eslint.lintFiles(...)
```
So, how can I do this with vscode-eslint? I can not use `require` in settings.json.

**Comment by dbaeumer** [comment]
@cyberbiont thanks for the clarification. You can't do that right now. As I was trying to explain the vscode-eslint extension tries to not provide any features that are not available on the ESLint CLI. So all I can ask you is to create an issue against ESLint directly and see if they are willing to add this.

OK for you to close?

**Comment by cyberbiont** [comment]
OK, thanks. Let's close it then.
