### ISSUE TITLE
Cannot format files with brackets in the name

### ISSUE THREAD

**Issue by veikovx** [microsoft/vscode-eslint#977]
When trying to format a file with square brackets in the name ESLint plugin fails
`Extension 'ESLint' cannot format 'somepath/somefile.[square].ts'`

Also fails for `{curly}`

Files without brackets are formatted correctly.
`eslint --fix` works correctly with these files.

Tested in Windows and also in WSL2

**Comment by dbaeumer** [comment]
The problem is that I need to escape these brackets since they have a special meaning in glob patterns.

@jrieken I am now escaping them to `somepath/somefile.\[square\].ts` when I create the document filter but I am still not called. Anything else I would need to consider?

**Comment by jrieken** [comment]
Not sure I understand. Is there a special formatting registration for names with square- and curly-brackets which uses glob-patterns?

**Comment by dbaeumer** [comment]
Sorry for not being preceise. To only register the formatter for file I care about in ESLint I create a `DocumentFilter` with a pattern where the pattern is basically the file path (e.g. '/home/dirkb/project/file.ts`) Now if the file name has a `[]` in it I need to escape it. So in the example I convert the pattern to `/home/dirkb/project/file\[square\].ts`. But even with that pattern I will never be called. Everything works fine for patterns like `/home/dirkb/project/file.ts`

**Comment by jrieken** [comment]
Thanks for clarifying. Adding @bpasero who implemented the glob pattern matching

**Comment by bpasero** [comment]
To my knowledge, our glob library does not support escaping.

**Comment by dbaeumer** [comment]
@bpasero can you give me a tip on how to create a pattern for a file name that has `[` in it ? Is the recommendation to exchange it with a `.`

**Comment by bpasero** [comment]
`?` matches any single character except path separator (/ and \)

**Comment by dbaeumer** [comment]
@bpasero thanks.

**Comment by goloroden** [comment]
Any update on this?

**Comment by dbaeumer** [comment]
Actually no :-).

Would you be willing to work on a PR?

**Comment by goloroden** [comment]
What a pity 😞
But being an open-source maintainer myself, I know that you hardly have the time to care about *everything*.

Anyway, theoretically I'd say "yes", but in this case it's not something I need personally, but one of our customers.
So given that I have lots of other things as well, unfortunately, I have to pass …

Thanks anyway, for the quick reply, and for the work you do on the plugin!

**Comment by yuan9090** [comment]
try: 
```
file.replace(']','[]]').replace('/[','/[[]');
```
