### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by subbiah-logichub** [microsoft/vscode-eslint#979]
- Issue Type: `Bug`
- Extension Name: `vscode-eslint`
- Extension Version: `2.1.1`
- OS Version: `Darwin x64 19.4.0`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 41,
		"activateCallTime": 15,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "dbaeumer.vscode-eslint",
				"_lower": "dbaeumer.vscode-eslint"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Language client is not ready yet"
		}
	]
}
```

**Comment by dbaeumer** [comment]
@subbiah-logichub can you reproduce this? If so can you share the repository?
