### ISSUE TITLE
Extension showing Eslint errors that don't exist

### ISSUE THREAD

**Issue by Mahan-F** [microsoft/vscode-eslint#981]
Hi, I have an issue where my javascript files on the first line I always see this eslint error highlighted:

![image](https://user-images.githubusercontent.com/6375360/83031076-d0377a00-a03c-11ea-8f36-669ebd8b69f9.png)

As far as i'm seeing this is not an actual eslint error because when I run the eslint command, it reports that everything is okay. I did a test to make sure the eslint is working correctly by indenting a line too much and eslint threw an error.

Because of this, I thought it is most likely that the issue is coming from the extension.

This is my eslint config:
```
{
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module"
  },
  "extends": [
    "eslint:recommended",
    "plugin:node/recommended",
    "plugin:security/recommended"
  ],
  "rules": {
    "strict": 0,
    "indent": [
      "error",
      2
    ],
    "linebreak-style": [
      "off"
    ],
    "quotes": [
      "error",
      "single"
    ],
    "semi": [
      "error",
      "always"
    ],
    "security/detect-non-literal-require": [
      "off"
    ],
    "security/detect-object-injection": [
      "off"
    ]
  }
}
```

Version information:
- eslint: 7.1.0
- babel-eslint: 10.1.0
- VSCode eslint extension: 2.1.5
- Node.js: 10.16.3

**Comment by dbaeumer** [comment]
@Mahan-F can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
