### ISSUE TITLE
Configure `rulePaths` relative to project root?

### ISSUE THREAD

**Issue by IanVS** [microsoft/vscode-eslint#985]
I have custom eslint rules in a directory of a monorepo, and am using `eslint.workingDirectories` like `{"directory": "./projectA", "!cwd": true}`.  But when I try to add a `rulePaths` in my workspace settings to point to my custom rules, it always seems to try to resolve from `projectA` instead of the root of my project.  I've tried using `${rootPath}`, but it seems that it is not being interpreted, instead the string `"${rootPath}"` is added to the path verbatim.  Is this a bug, or am I possibly configuring something incorrectly?  Thanks!

**Comment by dbaeumer** [comment]
@IanVS does the validation happen correctly when you use eslint in the terminal no cd into `projectA`. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
