### ISSUE TITLE
[feature request] Offer code mark styles and gutter marks

### ISSUE THREAD

**Issue by darkred** [Microsoft/vscode-eslint#99]
_(Using VSCode 1.3.0 in win 10 x64 build 10586 with vscode-eslint extension 1.10.18)._

Currently the code marks(for errors and warnings) appear only as squiggly underline (i.e. as **spellchecker errors** in browsers, e.g. Firefox, Chrome):
_(the error is in red, and the warning is in green)_
![2016-07-11_020259](https://cloud.githubusercontent.com/assets/723651/16716650/b635a444-470b-11e6-82fc-90770e8bea05.png)

My suggestion is to offer more code mark styles (ideally  the **outline** style, as it highlights the errors/warnings the best way -see below- ) and **gutter marks** :
_(with the errors to be in red, and the warnings to be in yellow, as ESLint itself uses these colors - not green)_
![2016-07-11_020203](https://cloud.githubusercontent.com/assets/723651/16737733/59dedc70-479b-11e6-8da9-0789ade17143.png)
([here is another screenshot](https://sublimelinter.readthedocs.io/en/latest/_images/marks-outline-dark.png))

It's more easy to distinguish the errors this way.

Thank you

---

_For reference SublimeLinter3 package offers [five different code mark styles](https://sublimelinter.readthedocs.io/en/latest/mark_styles.html) :_ 
* fill, 
* outline   _(the default style)_,
* solid underline, 
* squiggly underline, and 
* stippled underline

_and two types of gutter marks:_ 
* errors, and 
* warnings

**Comment by AndrewIngram** [comment]
I found myself searching around for a setting to enable this, I guess i've been heavily spoiled by Atom and Sublime. This is pretty important for me, because I find the squiggly lines to be far too difficult to see when scrolling through a file.

**Comment by glebec** [comment]
I second the use of yellow for warning. For one thing, red-green is always a poor UI choice as it ignores the 7%+ of XY-chromosomal people who have red-green color blindness. For another, it matches ESLint. Also yellow just feels more like a warning than green, culturally speaking.

**Comment by dbaeumer** [comment]
Moving to vscode since such a feature has to be implemented in the editor.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode#9209
