### ISSUE TITLE
The ".ts ", ".tsx "files cannot be highlighted

### ISSUE THREAD

**Issue by WangJiangJiaoZi** [microsoft/vscode-eslint#990]
You can format the code with commands, but VsCode does not highlight error syntax. Also, the ".js" file is good.

version:
vscode v1.46
vscode-eslint v2.1.5
node v14.3.0
eslint v^6.8.0
typescript v^3.7.3
@typescript-eslint/parser v^2.12.0
@typescript-eslint/parser v^2.12.0

.eslintrc.js:
``` javascript
module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    parserOptions: {
        'project': './tsconfig.json',
    },
    extends: ['plugin:@typescript-eslint/recommended'],
    plugins: ['@typescript-eslint'],
    env:{                         
        browser: true,
        node: true,
    },
    rules: {
        'semi':[2, 'never'],
        '@typescript-eslint/no-explicit-any': 0,
        '@typescript-eslint/explicit-function-return-type': 0
    }
}
```

settings:
```json
{
    "eslint.codeAction.disableRuleComment": {
        "eslint.validate": [
            "javascript",
            "javascriptreact",
            "html",
            "vue",
            "typescript",
            "typescriptreact"
        ]
    }
}
```

**Comment by dbaeumer** [comment]
This works for me in TS files

<img width="420" alt="capture" src="https://user-images.githubusercontent.com/1931590/84377023-4f52b380-abe2-11ea-8771-c8f20a2e2b21.png">

@WangJiangJiaoZi  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.
