### ISSUE TITLE
Being able to configure eslint.runtime at workspace level

### ISSUE THREAD

**Issue by ylesaout** [microsoft/vscode-eslint#991]
Hi,

Sometimes ago, it was possible to configure the eslint runtime at workspace level. It was perfect for my use case because I need to work with different legacy code and then run different version of eslint and node.
It would be great if this can be re-enabled.

The change is probably due to the fact the runtime configuration scope has been moved from `window` to `machine` in this commit:  https://github.com/microsoft/vscode-eslint/commit/b92413a368434cedf5c3595f74f8a21abb895ff3.

Note that there was a issues requesting this change here: https://github.com/microsoft/vscode-eslint/issues/690

**Comment by ylesaout** [comment]
After looking at the [scope documentation](https://code.visualstudio.com/api/references/contribution-points) on vscode, the `machine-overridable` could be the scope to use as it is machine specific but allows to override the configuration at workspace/folder levels.

If needed I can make a pull request for such a change.

**Comment by dbaeumer** [comment]
@ylesaout eslint.runtime needs to be a machine level setting due to remote. 

@sandy081 any suggestions?

**Comment by dbaeumer** [comment]
@sandy081 missed @ylesaout last comment. Is that the way to go?

**Comment by sandy081** [comment]
Yeah this is exactly the suggestion.

**Comment by dbaeumer** [comment]
@sandy081 thanks !
