### ISSUE TITLE
Diagnostic code is not per spec

### ISSUE THREAD

**Issue by rchl** [microsoft/vscode-eslint#992]
The `code` property in the diagnostic notification is specified as:
```ts
	 /**
	 * The diagnostic's code, which might appear in the user interface.
	 */
	code?: number | string;
```

but eslint sends, for example: `'code': {'value': 'no-trailing-spaces', 'target': 'https://eslint.org/docs/rules/no-trailing-spaces'}`

Useful information to have but nonetheless not per spec.
Is spec gonna change in this regard?

**Comment by dbaeumer** [comment]
@rchl. Yes, it it proposed that way for 3.16 which I already started to adopt in ESLint.

**Comment by rwols** [comment]
Shouldn't this be guarded by a client capability?

**Comment by dbaeumer** [comment]
@rwols  if we publish the ESLint server independent of VS Code I agree.

**Comment by rwols** [comment]
That sounds fair. I hope this language server can be published as an independent package one day.
