### ISSUE TITLE
Get Show Documentation Link instead of opening in default browser…?

### ISSUE THREAD

**Issue by rareyman** [microsoft/vscode-eslint#994]
When choosing to Show Documentation for an Eslint rule…

![image](https://user-images.githubusercontent.com/846457/84605685-01dd7d00-ae54-11ea-9b0b-84a0ad7d0369.png)

…it automatically opens in Safari for me. Yes, I have Safari set as my default browser, which is why this is occurring.

Is there a way to just get the link to the documentation instead of forcing open the URL in my default browser? Or, is there a way to tell Eslint to open the documentation in another browser?

Thanks!

**Comment by dbaeumer** [comment]
Actually no. VS Code has no API to tell which browser to use. I would accept a PR to allows a code action to Copy the documentation link. But that needs to be behind a setting.

**Comment by rareyman** [comment]
Excellent! Thinking out loud…

I’d expect the menu to look like this:
…
**Open Documentation for xxx-yyy
Copy Documentation URL for xxx-yyy**
…
Settings can be something along the lines of:
`offerDocumentationUrl: true,`

**Comment by dbaeumer** [comment]
The setting should be along the lines of `eslint.codeAction.showDocumentation`

**Comment by rareyman** [comment]
For whatever it's worth for anyone having similar issues:

There is a $10 utility for macOS called Choosy that allows you to configure how links are handled from any program. Basically, you set Choosy as your default web browser, then you can set rules on how links are handled.

So, in this case, I can say any links opened in VS Code will be forced to open in a particular browser.

https://www.choosyosx.com/
or 
`brew cask install choosy`

I hope that is helpful!

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
