### ISSUE TITLE
How to lint yaml files with eslint-plugin-yaml?

### ISSUE THREAD

**Issue by JustFly1984** [microsoft/vscode-eslint#997]
I have setup eslint-plugin-yaml, and it works in terminal and with lint-staged, but doesn't work in vscode. No highlighting, or errors in Eslint output.

I've added

```json
{
"eslint.probe": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "yaml",
    "yml"
  ]
}
```
to .vscode/settings.json,

but it doesn't fixed highlighting

Do I miss some steps?

**Comment by dbaeumer** [comment]
@JustFly1984 since it works for you in the terminal can you provide me with a GitHub repository that demos the failing YAML validation?

**Comment by JustFly1984** [comment]
@dbaeumer sorry, it is private repositories, and I don't have access rights to add users

**Comment by dbaeumer** [comment]
WIthout a repository to clone this is hard to track down. Can you make me a small example?
