### ISSUE TITLE
Run across "eslint/probleFailed" for typescript in Vue project

### ISSUE THREAD

**Issue by stuartZhang** [microsoft/vscode-eslint#998]
Hello guys,

I enabled eslint.server.trace to gather the logs:

> [Trace - 上午12:06:58] Received request 'eslint/probleFailed - (58)'.
> Params: {
>     "textDocument": {
>         "uri": "file:///h%3A/minxing_workshop/github/derivative_h5/src/app.ts"
>     }
> }
> [Trace - 上午12:06:58] Sending response 'eslint/probleFailed - (58)'. Processing request took 0ms
> No result returned.

None of eslint warnings and errors were reported in the code editor.

However, vscode-eslint works well for "*.vue" files along with <script lang="ts">. 
Moreover, the command "npx eslint src/app.ts" work as expected.

This is my project: [ts-admin-elementui-demo2.zip](https://github.com/microsoft/vscode-eslint/files/4808221/ts-admin-elementui-demo2.zip)

1. unzip it to a directory.
2. npm i
3. run the command "npx eslint src/axios.ts" and see the errors are reported in the terminal.
4. open the file "src/axios.ts" in vscode editor. None of eslint errors appears in editor.
5. open the file "src/App.vue" in vscode editor. The eslint errors appears as expected.

**Comment by dbaeumer** [comment]
@stuartZhang  does the validation happen correctly when you use eslint in the terminal. 

Having this probe massage is expected if the project is not setup correctly to validate TS files.

**Comment by AlexandreBonaventure** [comment]
@dbaeumer please consider reopening, I stumble upon the same issue when I switched from Mac OS to Windows WSL (Ubuntu). Node runtime is 12.4
I can totally confirm everything @stuartZhang said, that is:
- eslint CLI validation works just fine
- in VSCode, ts validation works inside .js files + script block in .vue files but probe fails in .ts files.
+ in Mac OS I don't have any issue.

Do you need anything else other the already provided repro ? I can provide logs etc...
THanks!

**Comment by chriswoodle** [comment]
I've got a similar problem when using yarn2

**Comment by dbaeumer** [comment]
I need a project I can clone that demos the problem. The zip from @stuartZhang doesn't install for me. I get a ton on npm error.

**Comment by AlexandreBonaventure** [comment]
got it! I'll free some time to send you a repro

**Comment by chriswoodle** [comment]
I've created a repo where I can produce the same original behavior described above:
* No eslint warning or errors in `.ts` files. (expected linting wernings/errors) 
* Correct linting in .vue files 
* Correct linting via the cli

## https://github.com/chriswoodle/vscode-eslint-998

It uses Vue3, and Yarn2 PnP.

I've included screenshots, commands and console output in the repo, I'll add some screenshots here for convenience. 

### File without linting (`"no-console": "warn"`)
![Image 1](https://raw.githubusercontent.com/chriswoodle/vscode-eslint-998/master/ts-file-not-linted.png)

From CLI

![Image 2](https://raw.githubusercontent.com/chriswoodle/vscode-eslint-998/master/expected-lint.png)

With trace server set to "verbose"
![Image 4](https://raw.githubusercontent.com/chriswoodle/vscode-eslint-998/master/trace-server.png)

### Correct linting for .vue files

![Image 6](https://raw.githubusercontent.com/chriswoodle/vscode-eslint-998/master/vue-sfc-correct-linting-output.png)

Hope this helps, thanks for your support.

**Comment by AlexandreBonaventure** [comment]
nice! If anything I am also using yarn2 ...

**Comment by dbaeumer** [comment]
@chriswoodle thanks for the great repro. I know what fails. An easy workaround for now is to change the parser line in the `.eslintrc.js` to `parser: '@typescript-eslint/parser'`. That makes it work for now.

**Comment by chriswoodle** [comment]
> 
> 
> @chriswoodle thanks for the great repro. I know what fails. An easy workaround for now is to change the parser line in the `.eslintrc.js` to `parser: '@typescript-eslint/parser'`. That makes it work for now.

@dbaeumer  Oh wow, this works, glad it was that easy. Thanks for the fast solution.

**Comment by heavenkiller2018** [comment]
I've got a similar problem when using yarn monorepo

**Comment by dbaeumer** [comment]
@heavenkiller2018 please open a new issue with a GutHub repository attached that demos what you are seeing.
