### ISSUE TITLE
Stuck in Saving 'foo.vue' Getting code actions from 'ESlint' or 'Vetur'

### ISSUE THREAD

**Issue by liumt1993** [microsoft/vscode-eslint#999]
- VSCode Version:1.46.1
- OS Version:Windows_NT x64 10.0.18362

Steps to Reproduce:

1.Write a self close tag, eslint will make tag self close
`<router-link></router-link>` 
gonna be :
`<router-link />`
2.Make the tag split and insert value
`<router-link>foo</router-link>`
3.Execute Save action then VSCode Stuck in Saving 'foo.vue' Getting code actions from 'ESlint'
4.
![image](https://user-images.githubusercontent.com/4754770/85242608-16340200-b472-11ea-861f-28cd00c1daa4.png)

Does this issue occur when all extensions are disabled?: No

**Comment by rw251** [comment]
I also came across this.  At the time I had:

```
eslint v4.19.1
dbaeumer.vscode-eslint v2.1.7
```

It only happened intermittently and upgrading to `eslint v7` resolved the problem.

**Comment by liumt1993** [comment]
> I also came across this. At the time I had:
> 
> ```
> eslint v4.19.1
> dbaeumer.vscode-eslint v2.1.7
> ```
> 
> It only happened intermittently and upgrading to `eslint v7` resolved the problem.

I'll try it, and i found this issue it's not intermittently.There is a problem when you make the self-close tag to split, even make the tag self close again, there still have this problem.

**Comment by dbaeumer** [comment]
I need a GitHub repository that demos the problem to investigate. If not provided our bot closes issues automatically to keep the number manageable.

**Comment by heemoe** [comment]
some here

```
Saving 'invitation.ts': Getting code actions from ''ESLint', 'TypeScript and JavaScript Language Features''
```

<img width="925" alt="image" src="https://user-images.githubusercontent.com/9105193/89503880-c0d16b80-d7f9-11ea-9724-845115d0d7e6.png">

vscode infomations:
```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

<img width="2011" alt="image" src="https://user-images.githubusercontent.com/9105193/89504352-6e447f00-d7fa-11ea-87c2-eea39bc09056.png">


it seems come from the latest version of vscode.

**Comment by dbaeumer** [comment]
Actually the high CPU load is in the extension host not in the ESLint server (which would actually do the computation of the code actions). @heemoe can your reproduce this and could you share the repository?

**Comment by heemoe** [comment]
> Actually the high CPU load is in the extension host not in the ESLint server (which would actually do the computation of the code actions). @heemoe can your reproduce this and could you share the repository?

It seems fixed after add `editor.codeActionsOnSave`

Here is some related settings

```
"editor.codeActionsOnSave": {
    "source.fixAll": true
  },
  "[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  },
  "[typescript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[json]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  },
  "[javascript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "editor.formatOnSave": true
```

**Comment by itsalb3rt** [comment]
I made a risky decision and deleted the line.

```json
"editor.codeActionsOnSave": {
    "source.fixAll": true
  }
```
